### ISSUE TITLE
routing takes unnecessary u-turns - should auto-report those

### ISSUE THREAD

**Issue by KlavsKlavsen** [osmandapp/OsmAnd#10230]
### Routing engine

- [x ] OsmAnd's in-app offline routing

Car, fastest route.

### Start and end points
I asked for a route from "hædersdalvej, hvidovre" https://www.openstreetmap.org/way/10636079
to "vestergade, roskilde" https://www.openstreetmap.org/way/145394545

### Actual and expected routes

![image](https://user-images.githubusercontent.com/2737885/99667180-4d7ffc80-2a6c-11eb-9b3e-6fedb60a37d8.png)

Problem was that osmand told me to turn right (right after getting off freeway) - and then directly after, do a u-turn (which I actually could not until a few km further down).

I could have just turned left.

### Is this a regression?

I don't know. I think its a map issue?

## 🌍 Your Environment

osmand 3.8.3

Android 8.1 (lineageOS 15.1)

**Maps used (online or offline):**
Offline - Denmark map.

- [x] Offline maps offered within the OsmAnd app for download.

**Comment by osmgit** [comment]
I've fixed this problem. I can confirm this was a problem with the turn restrictions at that node on the map. In this case Left Turn was set to allowed.

Do you have an openstreetmap.org account? If not then you just go here https://www.openstreetmap.org and sign up. You can then log in and edit or add to the map!

**Comment by vshcherb** [comment]
Yes we have this bug reported often and we will need to create a solution for it, we will need somehow to introduce a right penalty for such turns that will penalize enough to avoid them

**Comment by KlavsKlavsen** [comment]
@osmgit I do have an account on openstreetmap.org and I have added roadnames I found weren't in openstreetmap etc. - but I have yet to figure out how to figure what goes wrong (f.ex. here) - with the routing, and as such - how to fix this in openstreetmap. It seems rather difficult to debug, if you're not very well versed in the subject (and I'm really not :)
If you wrote down "incident reports" and corrections - a small.. Had this bug: "image of routing error" - and described how you fixed it (in absense og a git log I could view and repeat for openstreetmap.org ) - then everyone could learn from how you fixed those - and thus hopefully more easily, figure out how to fix the bug they found ?

**Comment by KlavsKlavsen** [comment]
Is the route calculations documented somewhere @vshcherb ? then I'd gladly read that and see if I have any bright ideas :)
I would think that the fact that going left is a shorter should be enough. Perhaps a U-turn is set to take "too little time/too low cost", compared to regular turns ? U-turns that are NOT done in an intersection - should cost 2x a "regular turn" ? (totally guessing, based on zero knowledge of the routing calculations :)

**Comment by KlavsKlavsen** [comment]
@osmgit "I can confirm this was a problem with the turn restrictions at that node on the map. In this case Left Turn was set to allowed." - I would have thought it should still have chosen just to "turn left" directly from the free-way off ramp (as I clearly can) - instead of telling me to turn right and then make a u-turn.
How does disallowing left turn help that ?

**Comment by osmgit** [comment]
At the node where the U-turn is shown it's classed as a left turn rather than a U-turn since the road is made from 2 different one way line segments. If you log into OSM account, then click on the node where it shows the U-turn. You should then see a box to the left of your screen. This shows you a zoomed in view of the intersection at that node. Then you can click on each line segment in that box and set the turn restrictions.

**Comment by alisa911** [comment]
https://github.com/osmandapp/OsmAnd-resources/pull/658

**Comment by alisa911** [comment]
https://github.com/osmandapp/OsmAnd-core/pull/173

**Comment by alisa911** [comment]
https://github.com/osmandapp/OsmAnd/pull/10481

**Comment by vshcherb** [comment]
We've fixed couple of issues, so even without map change that u-turn will have enough penalty to not be suggested.

**Comment by Famlam** [comment]
Do I understand correctly that it is no longer possible to distinguish between right rurns (almost no stopping as you're not crossing other vehicles) and left turns (crossing a road and giving way to all other traffic)?

**Comment by vshcherb** [comment]
It was not possible before, that change was done 3-4 years ago but was not reflected in the code variables

**Comment by Lee-Carre** [comment]
> Do I understand correctly that it is no longer possible to distinguish between right rurns (almost no stopping as you're not crossing other vehicles) and left turns (crossing a road and giving way to all other traffic)?

Keep in mind that for several nations, one needs to invert left & right. That is, vehicles drive on the left-hand (port) side of the road. In which case, left-turns are easy, and right-turns are hazardous.

Though, I imagine that such matters are handled by driving region selection, and the code uses the more common case (starboard) as default(?)

**Comment by Lee-Carre** [comment]
@KlavsKlavsen

> I would have thought it should still have chosen just to "turn left" directly from the free-way off ramp (as I clearly can) — instead of telling me to turn right and then make a u-turn.
How does disallowing left turn help that ?

Firstly; human perception & intuition != software algorithm.

The challenge is in devising an algorithm which suggests sensible routes, from generic parameters, without requiring special-case overrides.

Disallowing a left turn *at the node where it's doing a U-turn* causes the algorithm to find an alternative.

Why not that alternative route to begin with? Probably because the left turn you're meaning, was deemed undesirable, since it requires driving *away* from the destination.

If you want a better understanding of what's going on conceptually / computationally:
* [Introduction to Graph Theory: A Computer Science Perspective](//www.youtube.com/watch?v=LFKZLXVO-Dg)
* [A* (A Star) Search Algorithm](//www.youtube.com/watch?v=ySN5Wnu88nE)

**Comment by KlavsKlavsen** [comment]
@Lee-Carre as it told me to do right turn - and then do u-turn - to get to destination - turning left immediately is clearly CLOSER to the destination - and directly leading me the way I need to go (so turning left does NOT requires me driving away from the destination).
What it did - was to request me to drive away from the destination - and then make a U-turn.
I expect data in that intersection in openstreetmap to simply be wrong - so its not marked as left-turn allowed?

**Comment by Lee-Carre** [comment]
Hmm, then I'm somehow misunderstanding the image in your OP.

**Comment by Lee-Carre** [comment]
@KlavsKlavsen

> the part that is wrong

I'm confidently clear on that part, at least 🙂.

> … it should just have told me to keep left — to follow the small road and turn left directly 🙂

From the loop (which I presume is an exit ramp) onto the small(er) straight red road that runs (SE) parallel to Lille Holbaekevj, to form a T-junction with the orange road (instead of continuing around the loop (SW)), where you could've done a left-turn to head north-east (on orange, putting you back on the suggested route)?

Otherwise, I'm not seeing where a left-turn would cause you to be heading NE.

If so (🤞), then the misrouting would seem to be due to the general preference of more major roads (and with higher maxspeed) than minor ones. Especially if configured to prefer the fastest (as opposed to shortest, or most (fuel) efficient) route.

Else, an algorithm given bogus data will do weird things. Hence the remedy is to mark the junction where it suggests doing a hairpin U-turn as not permitting such a turn. So that it knows to disregard what might otherwise be deemed optimal, and find a different route.

Similar principle applies to oneway=yes roads; shortest (absolute) route probably means going the wrong way down some (unless on foot). With correct one-way set on the roads, it'll figure out what convoluted path is needed to reach the destination while complying with the directionality rules.

**Comment by Lee-Carre** [comment]
For future reference (since I went digging, out of curiosity):
* [directions](//www.openstreetmap.org/directions?engine=fossgis_osrm_car&route=55.6637%2C12.4659%3B55.6451%2C12.0598) based on OP origin & destination
* [troublesome junction](//www.openstreetmap.org/#map=17/55.62609/12.06057) which, interestingly, isn't along the suggested route (by either OSRM or GraphHopper)
