### ISSUE TITLE
u-turn bug map issue detection

### ISSUE THREAD

**Issue by KlavsKlavsen** [osmandapp/OsmAnd#10231]
I just opened https://github.com/osmandapp/OsmAnd/issues/10230

and I've seen several of those.. and I notice them while driving - so they're kinda hard to report :)

I have 2 ideas that could improve the state of the maps (I would assume the above is a map issue):

1) When you activate map - it shows the blue arrow if you're "being led to somewhere" - and if it just had an icon as well - for "save route bug info -  right here" - which saved the route - the current location - and could then be opened when one had time in a list of "route bugs" - and submitted from there with an explanation - it would be very easy to report any bug found - and improving on this - would be a function to "email me a link to how I can fix/report the bug on openstreetmap.org"

2) Atleast in Denmark - you (almost?) NEVER have to turn one way - and then do a u-turn right after.  Which means - that atleast per-country, an automatic "report u-turn calculated in original route" feature - would automaticly catch almost ALL the bugs I've seen in routes while using osmand for the last few years. One could then "whitelist" places as one hits them - which means those reports could be filtered off (and even saved in osmand - so it could just recognize the location and not send report).

**Comment by osmgit** [comment]
Yes, I see bugs all the time when driving and they are very hard to report while driving I know.

I can tell you a way to do this in OsmAnd:

1. Menu Button > Configure Screen
2. Enable "Quick Action"
3. Click on "Quick Action" Action and then "Add Action"
4. Click "Add OSM Note"
5. Make up a note eg. "No U-Turn Allowed" (this is the label you see) then type a message "No U-Turn Allowed" (this is the message seen if uploaded to OSM).
6. You can then tap the Quick action button and then tap on your Action, while driving and it logs your current position along with the note you set up.
7. Then I usually go back and edit the points my self over at https://www.openstreetmap.org. Rather than uploading them, I fix them myself by looking at them on the phone and then finding the same place on https://www.openstreetmap.org and then I make the edits.
8. You can then make up more quick action notes eg. No Left Turn etc.
