### ISSUE TITLE
One way rode, zone 30, and biking

### ISSUE THREAD

**Issue by letypequividelespoubelles** [osmandapp/OsmAnd#10462]
# 🚀 feature request

### Description

In France, in "zone 30", one way road are always bidirectionnal for bike, unless it is explicitly written it's not. This come from a [2018 law](https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000039277970/). But OSMAnd doesn't take this law into account and so the bike routing in France in city is usually not so good.

### Describe the solution you'd like
OSMAnd should consider french one-way zone 30 road as bidirectional for bikes, unless it is explicitly tagged as also one-way for bike.

For information, a french zone 30 way is tagged with "source:maxspeed=FR:zone30". Beware, take all road with "maxspeed=30" is not enough because it can not be a "zone 30". 
A one-way zone 30 which is explicitly also one-way for bike (it's not common, but it happens) is tagged with "oneway:bicycle=yes"

### Describe alternatives you've considered

None. Thank you all for this wonderfull app.

**Comment by xmd5a2** [comment]
Can you give an example of problematic road? Do I understand correctly that ALL roads are bidirectional in zone 30? If yes, why not just remove all oneway tags from OSM database?

**Comment by letypequividelespoubelles** [comment]
> Do I understand correctly that ALL roads are bidirectional in zone 30?

No, in zone 30 you can have one way or bidirectionnal ways for cars. But, the huge majority of one-way road that are one-way for cars are bidirectional for bikes, thanks to the law given in my previous comment.  

>Can you give an example of problematic road?

Someone just added (10 hours ago ) oneway:bycicle=no in all zone 30 roads of my neighborhood (but it's normaly not needed). I'll search and tell you.

**Comment by vshcherb** [comment]
I think that's an OSM issue, so I hope guys @xmd5a2 @letypequividelespoubelles you will figure out how to deal with it via OSM Notes / OSM Forum.

**Comment by letypequividelespoubelles** [comment]
>I think that's an OSM issue
I don't get your point. French one way zone 30 are bidirectional for bikes unless it's explicitly tagged as oneway:bycicle=yes.
FYI, this has been discussed and agreed via the French OSM telegram chat.

**Comment by xmd5a2** [comment]
@letypequividelespoubelles Do I understand correctly than adding `oneway:bicycle=no` to ways with `source:maxspeed=FR:zone30` solves issue?

**Comment by letypequividelespoubelles** [comment]
@xmd5a2 yes. it should solve it I guess. But when adding oneway:bicycle=no , take care that the oneway:bicycle=yes is not already here ! :)

Thanks

**Comment by foux** [comment]
Hello there!
I reopen this issue, because the law is quite clear (for those who reads french) : https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000045025523/

So all roads with a maxspeed of 30km/h or less, in France, are authorized in both ways for cyclists, unless told otherwise. So we don't have to have `source:maxspeed=FR:zone30` in the metadatas, but just check that the max speed is less or equal to 30 km/h

**Comment by AdrienJaguenet** [comment]
Hi, contrary to what OP initially said, since 2016, French road law makes no distinction between "zone 30" and a simple 30 km/h limit, when it comes to one-way streets. This means OSMAnd should take into account all `maxspeed=30` ways. The relevant law can be found [here](https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000045025523).
