### ISSUE TITLE
Incorrect Lane Guide while navigating

### ISSUE THREAD

**Issue by AnastasiaTiutina** [osmandapp/OsmAnd#10480]
an issue with the turn by turn directions while navigating.

![img2](https://user-images.githubusercontent.com/72389175/103226593-25ba6900-4935-11eb-9185-6d9d56c85e45.jpg)

![img1 (2)](https://user-images.githubusercontent.com/72389175/103226600-29e68680-4935-11eb-88e9-26e2558ae874.jpg)

Stop at the traffic light in front of this intersection.
The blue route shows the way to the left. That is correct so far.
On the screen, the center shows 3 lanes. 
The Line Guide should have shown the two arrows to the left.

The nearest coordinates 48.1853947,16.393426

**Comment by jfburke3** [comment]
I've seen some lane guidance issues recently, too. Unfortunately I haven't been able to capture data about most of them yet.

**Comment by vshcherb** [comment]
@scaidermern https://www.openstreetmap.org/edit#map=19/48.18577/16.39647
It looks very messy intersection and mostly incorrect.
![image](https://user-images.githubusercontent.com/1042025/104212844-f0824080-5435-11eb-9430-677df7706850.png)
The problem that there is no restriction to turn from https://www.openstreetmap.org/way/495511493
 to https://www.openstreetmap.org/way/892244323. But by geometry it looks like completely invalid turn (forbidden u-turn). It looks like that triangle would be better 1 point to avoid confusion between clear u-turn and left turns

Could you please help with map data at that point?

**Comment by alisa911** [comment]
https://github.com/osmandapp/OsmAnd-resources/pull/665

**Comment by alisa911** [comment]
https://github.com/osmandapp/OsmAnd-resources/pull/665

**Comment by scaidermern** [comment]
Indeed, it looks very messy. Partly because the real intersection is messy, partly because the representation in OSM is way too complicated.

I've tried to simplify it by replacing both triangles with a single intersection node. Because in my opinion there are just two intersections right next to each other. First image is before, second image is after the edit:
![foo01](https://user-images.githubusercontent.com/1040784/104294349-59fa6180-54bf-11eb-9910-8470674c516e.png)
![foo02](https://user-images.githubusercontent.com/1040784/104294350-5a92f800-54bf-11eb-95e2-899dce79b43b.png)

Looks way cleaner and less complicated. I hope I've preserved/fixed all turn restrictions.

**Comment by scaidermern** [comment]
@vshcherb Looks like the lane instructions are unchanged, though. Not sure why the through arrow is still highlighted instead of the two left turn arrows.

**Comment by vshcherb** [comment]
Now we will double check , thanks! @scaidermern

**Comment by vshcherb** [comment]
@scaidermern looks like you dropped turn:lanes tag, so now the issue doesn't make sense. Is it possible bring back lanes indication : "turn_left|turn_left|straight" before the intersection?

**Comment by vshcherb** [comment]
Justify turn, so TL looks more like a left turn https://www.openstreetmap.org/changeset/97393751#map=19/48.18601/16.39653.
And introduced 1 more way to separate left / right turn so geometry is closer to realistic

**Comment by scaidermern** [comment]
Has there been any code change in OsmAnd to resolve this issue?

**Comment by vshcherb** [comment]
Nope, we've added the tests to this turn and it was working correctly as we see.
