### ISSUE TITLE
Product management status labels:

### ISSUE THREAD

**Issue by sonora** [osmandapp/OsmAnd#10505]
Happy 2021 to everyone in our community!

@vshcherb  Here is my first thought for 2021: We have hundreds of open issues (even sometimes pull requests) with unclear status, both to the author and the readers. I suggest the following label categories to document the product management status or decision: 

**Observed**
Needs more clarification, feedback, or research

**Accepted**
Bug, regression, or feature, to be fixed in a milestone.

**Help Wanted** (was: Nice to have)
Will not be in a milestone, but a fix could be merged

**No Action**
Decision made to close without code change.

Only items which have not been looked at by product management at all will carry none of these categories (i.e. only rather new ones)!

I guess this would showcase a lot more clarity and provide more transparency for each contribution?

**Comment by vshcherb** [comment]
I simplified Labels to keep only 3 of them even though I don't whether we want to use Help Wanted.
All open issues are plan to be fixed somehow.
- Nice to have - means there is no priority / way to fix it within current horizon of the existing roadmap
- Observed - agree
Help wanted is very strange cause it could be fall into category Observed (research needed) or Nice to Have.

Every issue that I certainly disagree will be just closed. 
If issue remains open, milestone will be assigned (to show horizon planning) so there is no need to have Accepted at all. Even more Nice to Have could migrate back to the planning and be included in one of the milestone or could be migrated back out. 

What I certainly check that there is no open issue without milestone or without label. These issues are always subject for me to process.

**Comment by sonora** [comment]
What caused me to suggest a pattern **which forces us to visibly accept or reject each item** are these numbers:

As of today we have
- 203 open issues without any label, i.e. there is no systematic feedback in all these cases as to what the status  is
- there are 954 open issues labeled 'Nice to have', and I perceive these as 'unclear': Does it mean it would be truely appreciated to have these if only somebody would invest to implement (which is 'Help wanted'), or is it 'Nice to have' in the colloquial sense, meaning that it is really considered obsolete?

So in a sense I wanted to force us, in particular you ;), from a product management  point of view to showcase in a very structured fashion a strict yes/no decision, and not leave hundreds of issues open with often no common understanding between the authors and us.

**Comment by vshcherb** [comment]
- 203 open issues without any label. How many of them are not included in the roadmap ? i.e. don't have milestone set
- 954 open issues labeled 'Nice to have' -  each issue has own solution and it is not closed means that it would be good to find that solution though it doesn't mean that proposed solution is good, it means the problem is valid and needs to be addressed in the future.
For some issues I see solution, for some I don't see it yet but I'm open to communicate what solution people are ready to propose.

I think product management process should be clear to product manager but it doesn't mean clear to everybody. Probably I described in a more clear way now but feel free to clarify things.

**Comment by sonora** [comment]
Victor, It's no big deal, I just felt it would be more rewarding for our contributors to always receive a clear feedback by seeing a clear label. But the decision is certainly yours. :)

Since you asked: We currently have 26 issues without label and without assignment to any of the currently 6 open milestones. It takes 2 consecutive filters to arrive at that number. I wanted to make sure people not aware of the milestones would always be awarded a simple "Accepted" or similarly unmistakable feedback.

**Comment by vshcherb** [comment]
Yeah I believe it's my duty to go through all enormous issue, please if you see the issue is hanging without reply / label for over a week probably I've overlooked it. So far I have 13 to go through. 
Sometimes I recheck everything with such filter https://github.com/osmandapp/OsmAnd/issues?q=is%3Aopen+is%3Aissue+-label%3A%22Nice+to+Have%22+-label%3AObserved+no%3Amilestone+.

I see support / help from some people including you that's why I try to refer them in comments as CC, though I don't expect much code coming in cause it becomes more and more complicated and requires code ownership transfer.

**Comment by sonora** [comment]
All I'm saying is always state your opinion in the clear labels as I describe.

Then it will be simple to filter for `Unlabeled` to check for older ones likely overlooked, or e.g. pick up some of the `Approved` or `Help wanted` to assist with code over a weekend,  or pick an `Observed` one to conduct or evaluate research.
