### ISSUE TITLE
City name in search altered on some streets close to other cities since map update 1.12.2020

### ISSUE THREAD

**Issue by RURon** [osmandapp/OsmAnd#10558]
### Description

After the map update on 1.12.2020 I can no longer find some streets that are close to other cities, because all of a sudden they belong to those close cities instead of the "real" city.

### How to reproduce?

Try to search for "Rheinstahlstraße" in Düsseldorf, Germany - you will most likely not see any result. OsmAnd now thinks, that this street belongs to the city Hilden, which is a few km east of this street.

This happens to many (all that I checked actually) streets that belong to Düsseldorf and are close to other cities around it (in the western part for example the city Neuss). When checking at www.openstreetmap.org, everything is as it should be (all streets belong to Düsseldorf only), so I guess something is happening in the conversion from OSM data to OsmAnd map data...

### Your Environment
OsmAnd Version: 3.8.3
Android/iOS version: 7.1.1
Device model:

**Maps used (online or offline):**   
standard vector "Nordrhein-Westfalen Regierungsbezirk Düsseldorf" date 1.1.2021

**Comment by vshcherb** [comment]
We didn't do any changes in OsmAnd street detection algorithms last year at least. So very lilkely 
- city boundaries has changed
- city boundaries don't match names
- city boundaries are broken or were broken at the 1.1.2021

It's possible to generate nightly map to double check that problem is persistent

**Comment by RURon** [comment]
I can probably not help to analyze further - but if I can do anything to help, let me know. I only am a regular paid OsmAnd customer, no additional services booked. At the moment I can only see that address search is broken for streets close to other cities - havent checked if this affects any other cities as well.

But isnt it strange that on openstreetmap.org the affected streets are okay as they appear?!

**Comment by CJTmmr** [comment]
I expirience the same in The Netherlands. Many streets in places around Zoetermeer are listed under Zoetermeer.
e.g. Groendalseweg in Bleiswijk and all streets nearby. 
e.g. Keulseweg and Pieter Bregmanlaan in Pijnacker are listed under Zoetermeer

Also reverse geocoding gives Zoetermeer in stead of Bleiswijk or Pijnacker

maybe relayed.. Zoetermeer is mentioned  when you search Place Bleiswijk as in:
Bleiswijk, Dorp  6.3 km from Zoetermeer. 

Boundaries seem okay and unaltered for many months

**Comment by vshcherb** [comment]
I'm going to write an article how to detect which are most typical issues. Most of the could be identified with https://nominatim.openstreetmap.org/ui/search.html?q=Rheinstahlstra%C3%9Fe+D%C3%BCsseldorf

**Comment by CJTmmr** [comment]
On nominatim "Groendalseweg": is place Bleiswijk (housenumbers 2 - 94) or Berkel en Rodenrijs (housenumber 98,100 and 100a)
50, Groendalseweg, Bleiswijk, Lansingerland, Zuid-Holland, Nederland, 2665MG, Nederland
98, Groendalseweg, Berkel en Rodenrijs, Lansingerland, Zuid-Holland, Nederland, 2651WZ, Nederland
This correct.

in OsmAnd nightlies (also with new map dated 2021-01-01 Netherlands) Groendalseweg is wrongly in place Zoetermeer:
![2021-01-18 17 13 17](https://user-images.githubusercontent.com/15076257/104939344-98f15100-59b0-11eb-9ff7-d33ef99b5ceb.jpg)

I could test with older version OsmAnd+3.8.4 (2020-10-29) from PlayStore and map Netherlands from 2020-06-01.
Now search was okay, with housenumber 2-94 in Bleiswijk and 98,100 in Berkel en Rodenrijs:

![2021-01-18 17 16 43](https://user-images.githubusercontent.com/15076257/104939754-1ae17a00-59b1-11eb-9fab-488eab7d8f66.jpg)

![2021-01-18 17 15 22](https://user-images.githubusercontent.com/15076257/104943001-66962280-59b5-11eb-9588-36072810daef.jpg)

Further testing:
OsmAnd Nightly and Map The Netherlands from 2020-06-01:  **Search was okay**
OsmAnd 3.8.4 and Map The Netherlands from 2020-12-01 of 2021-01-01: **Search was broken**

So I guess something is wrong in map-generating-process.
The admin_level=10 boundaries-relations and ways for Zoetermeer, Bleiswijk and Berkel en Rodenrijs are okay and not broken.

I do no longer have the maps from 2020-07 to 2020-11..

**Comment by Marc959** [comment]
Hello,
Here is my personal experience with that bug if that can help you.
I have OsmAnd version 3.8.4 on my personal and my profesional mobile phones. The first one is OsmAnd+ / Live with the most recent maps and I have the bug of the streets assigned to wrong cities. I've seen that bug in France, Spain, Italy... On my pro mobile I have OsmAnd (free version), last maps are from August 2020 and the bug is not present.
The bug is present on road only and standard recent maps.
Let me know if you need more information.
Best regards.

**Comment by teiksef** [comment]
> We didn't do any changes in OsmAnd street detection algorithms last year at least. 
I'm not sure if my comment will be helpful for this issue, though there were some - maybe small - changes in indexing. It seems these changes made streets in our project (UMP) not to be indexed (due to the fact that we in general don't have city boundaries and rely on 'addr:city' and 'is_in'). One of changes (somewhere between 2020-02-01 and current) in IndexAddressCreator.java:

```
                for (City c : nearestObjects) {
                        Boundary boundary = cityBoundaries.get(c);
                        if (isInNames.contains(c.getName()) || (boundary != null && boundary.containsPoint(location))) {
-                               result.add(c);
+                               if (boundary != null && boundary.getCityType() != null && boundary.getCityType().storedAsSeparateAdminEntity()) {
+                                       result.add(c);
+                               }
```

So with no change on the map side the indexing could stop working due to non-ideal boundaries (which you pointed out, anyway).
I'm promising myself one day I'll send a pull request with an option like "forget city boundaries" (this would imply not searching by proximity), so some non-OSM datasets could be used more easily.

**Comment by vshcherb** [comment]
@teiksef Yes that change was in November! And we've got tons request only by the end of January and that confused me a lot. That change is reverted and now the workarounds are investigated. February maps should be fixed now.

We probably had to create some unit tests but it's very difficult to isolate those issues in the small tests.

**Comment by alisa911** [comment]
The bug will be fixed with February maps.
