### ISSUE TITLE
Voice Announcements for Autobahn Junctions/Exits contain the (correct) information too late or at wrong times

### ISSUE THREAD

**Issue by leogott** [osmandapp/OsmAnd#10718]
### Description
When using OsmAnd to navigate the German Autobahn, the Voice Announcements produce the correct information, but fail to do so at appropriate times.

_Examples:_
**Junction Numbers**
<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/Zeichen_406-50_-_Knotenpunkte_der_Autobahnen_%28ein-_oder_zweistellige_Nummer%29%2C_650x650%3B_StVO_2013.svg/240px-Zeichen_406-50_-_Knotenpunkte_der_Autobahnen_%28ein-_oder_zweistellige_Nummer%29%2C_650x650%3B_StVO_2013.svg.png"/>
The voice announcements appear to reference the junction's number (probably ref=*, idk) only in the TURN_NOW message(?), which plays immediately before the exit, after the respective signage appeared for the final time.
Since the signage is usually placed at 300m before, or for large junctions often 2000-3000m before the exit, it should be included in the PREPARE_TURN message.
(This Number should also be visible on screen as soon as the exit is referenced at all, which is probably a related problem)

**In places, where the right lane splits from the remaining ones for a couple hundred meters and junctions two or more exits bundled together:**
<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/7/71/Zeichen_449_-_Vorwegweiser_auf_Autobahnen_%28nach_RWBA%29%2C_StVO_1992.svg/225px-Zeichen_449_-_Vorwegweiser_auf_Autobahnen_%28nach_RWBA%29%2C_StVO_1992.svg.png" />
Reliably identifying which exit to take requires more information than is included in the PREPARE_TURN message(?).
It seems likely that OsmAnd handles the exit as two successive turns and not one.
The voice announcements referencing the signage with possible destinations often only play after switching to the correct lane is nigh- or actually -impossible. 
A human co-pilot might give instructions on which lane to take after the exit, (instead of waiting until the first exit was taken to begin reading out the entire content of the now-relevant signage), and in general instruct which lane to switch to.
Reading out the entire list of possible destinations takes a long time, and in some situations **the destinations lowest on the sign might be the only ones relevant**.

**Possibly** an unrelated hardware problem:
The distance to the junction used in the voice message and the distance on the signage deviate by a bit, which can lead to missed exits, when having to rely on the distance to identify the correct exit.
A human co-pilot might inform me of how many exits to pass before the turn, similarly to the voice messages in a roundabout. 
A possible supplement is stating the cardinal direction in which the highway continues after the juction.

**In this specific junction (which is Bundesstraße and not Autobahn):**
![map](https://user-images.githubusercontent.com/61663141/106462448-622e3700-6496-11eb-9aa0-ccdf84ecde71.png)
[Show on osm](https://www.openstreetmap.org/#map=19/50.16818/8.62910)
Coming from Marie-Curie-Straße, OsmAnd instructs me to go right before the right-hand exit to Rosa-Luxemburg-Straße is passed.

I suspect this is not entirely uncommon, but if required, I can take the time and find junctions for each of the situations I described.

### How to reproduce?
Navigate along the Autobahn in Hessen/Germany (especially with a smartphone that is not entirely visible to the driver.)

### Your Environment
OsmAnd Version: OsmAnd+ 3.8.4, released: 2020-10-29
Android/iOS version: 7.1.2
Device model:  Fairphone 2
Interface Language: English, Voice Language set to German
**Maps used (online or offline):**   
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.
offline maps

**Comment by leogott** [comment]
This is my first issue report with OsmAnd. I hope it's helpful as-is, but please tell me, if you require additional information!

**Comment by scaidermern** [comment]
This might be related to #9592.

**Comment by sonora** [comment]
I am a bit confused because at one point you state instructions come too late (_'... only play after switching to the correct lane is nigh- or actually -impossible_"), then too early ("_...and the referenced junction only becomes visible later_"), and then it seems you indicate a general accuracy problem possibly experienced by your hardware or use case ("_The distance ... used by OsmAnd appears to be the physical distance, where the distance on the signage is usually shorter_").

I am sure you understand the programatic challenge to derive every possible situation from just analyzing map data and converting it to a precise narrative.

The way you state the issue report unfortunately seems little helpful because it neither contains precise information to reproduce concrete sitiations you would like to see amended nor a clear expectation of how you would like to see things adjusted or a description of your expectation about the target scenario?

**Comment by sonora** [comment]
The way to success is this: We work on a table for
- PREPARE_TURN
- TURN_IN
- TURN_NOW

announcements stating exactly
- what information should be displayed / announced primarily
- what as a fallback if not existent
- timing of the announcements, but this is a separate test case

Then we could check how well an adjusted system would fit the signing practices and related timing in major different countries.

You primarily need to factor in how much time there usually is at each stage (space respectively to show things on screen). E.g destination lists can be quite lengthy, that's why it is in many cases adequate to shorten to e.g. the motorway exit name, if tagged, which in most countries is the major destination.

**Comment by leogott** [comment]
> I am a bit confused because at one point you state instructions come too late […] and then it seems you indicate a general accuracy problem possibly experienced by your hardware or use case […].

It's likely that the latter is an unrelated issue.
 
> I am sure you understand the programatic challenge to derive every possible situation from just analyzing map data and converting it to a precise narrative.
> 
> The way you state the issue report unfortunately seems little helpful because it neither contains precise information to reproduce concrete sitiations you would like to see amended nor a clear expectation of how you would like to see things adjusted or a description of your expectation about the target scenario?

I'll edit the text for clarity and add some info.

**Comment by vshcherb** [comment]
@sonora you can also refer to distances cause now it's displayed to user in Settings at what time / distance it will be announced.

**Comment by sonora** [comment]
True, thanks!  ;)

**Comment by vshcherb** [comment]
Discussion moved to  https://github.com/osmandapp/OsmAnd/issues/11778
