### ISSUE TITLE
Ski map plugin: nordic ski trails always shown as solid green lines - difficulty and grooming is not shown

### ISSUE THREAD

**Issue by averza** [osmandapp/OsmAnd#11102]
It works perfectly for the downhill trails - you see color-coded difficulties and the grooming type. With nordic trails, however, it is always green and solid lines. The only exception is if there is a tag "colour".

![image](https://user-images.githubusercontent.com/20924082/110607338-c3cb7a80-8193-11eb-9e12-6273d09934d6.png)

**Comment by clementcontet** [comment]
Linked with https://github.com/osmandapp/OsmAnd/issues/10784

**Comment by xmd5a2** [comment]
Piste grooming for nordic pistes are rendered exactly as for downhill pistes. Difficulty is displayed as text outline colour. I don't see another way of rendering difficulty because pistes are coloured according to `colour` tag. We can remove support of colour tag but not all users will like it. Or we can make an option but again, not all of users will find it in UI.
![Screenshot_2021-03-12_11-16-43](https://user-images.githubusercontent.com/5829014/110912015-7fbbaf80-8324-11eb-8602-1e4908653af1.png)

**Comment by clementcontet** [comment]
Hi, the difference with nordic pistes is that they rarely have a `colour` tag.
And in that case OsmAnd seems to use the `piste:difficulty` to compute the track color.

So for nordic pistes that have more commonly `colour` tags, we see the `colour` as track color and the `piste:difficulty` as text outline.
This is problematic because depending on the zoom level, text outline is shown or not, whereas you always see the track color.

A solution would be to switch information: always show `piste:difficulty` as track color and `colour` as text outline.
This way:
- you don't lose any information
- the `piste:difficulty` is alaways "visible" (which is for me the most important information)

**Comment by averza** [comment]
Thank you for your replies! I would also prefer switching colors as clementcontet suggested.

About grooming: which tags are required for it to be rendered? I've set `piste:grooming=classic+skating`, for example, but I still always see solid lines. Is there anything else that needs to be set?

**Comment by xmd5a2** [comment]
![Screenshot_2021-03-15_11-11-08](https://user-images.githubusercontent.com/5829014/111124535-aaef0a80-8581-11eb-9315-a902b2cbfd40.png)

**Comment by xmd5a2** [comment]
@averza OsmAnd maps are not updated instantly if you are not using OsmAnd Live. They are updated at beginning of every month.

**Comment by clementcontet** [comment]
@xmd5a2 that's perfect for the colors, thanks!
I just have a last issue with the overlapping labels => https://github.com/osmandapp/OsmAnd/issues/10784

**Comment by averza** [comment]
@xmd5a2 Yes, I know, the map I have is fresh. Could you give me an example (GPS coordinates or name of a place) where I can see that the grooming is rendered correctly?

**Comment by xmd5a2** [comment]
@averza https://overpass-turbo.eu/s/152D

**Comment by averza** [comment]
@xmd5a2 All the lines are solid even at max zoom level... am I doing something wrong? I am on Android and the latest version of OsmAnd.

![photo_2021-03-15_13-42-49](https://user-images.githubusercontent.com/20924082/111148660-95371080-8594-11eb-9c19-fb841679e8fe.jpg)
