### ISSUE TITLE
Web interface for planning a trip 

### ISSUE THREAD

**Issue by drazde** [osmandapp/OsmAnd#11134]
# 🚀 feature request

### Description

Create a Web interface for Plenning a trip. 
Osmand app has a very beatiful features for planning a trip and it is very fast!. But when you are at home I think is more comfortable use a PC.

There are may web site for planning a trip but nobody have the same rich features that osmand has. For example, configure the map with overlap _Waymarkedtrails Hiking_  (essential for planning a hiking route).

I hope I'm not too OT

**Comment by njohnston** [comment]
I like Waymarked Trails too, but can you configure OsmAnd to show hiking routes with "Configure Map", "Routes", and then "Colouring according to OSMC" below "Hiking symbol overlay".

**Comment by drazde** [comment]
> I like Waymarked Trails too, but can you configure OsmAnd to show hiking routes with "Configure Map", "Routes", and then "Colouring according to OSMC" below "Hiking symbol overlay".

Yes, I do so that.
Now I try to use remote app (anydesk) to use OsmAnd from my PC to use with a screen more big

**Comment by vshcherb** [comment]
I think we need to mention that maps should be similar to maps we have in Android otherwise some functionality will be lost.

**Comment by MaartenDeen** [comment]
The one thing I would like this for is because no planners that I know of have options for height, width, length or weight restrictions while planning a route and OsmAnd has.

**Comment by rooart** [comment]
I am a big fan of this feature request.
The main advantages that I see compared to existing web planners:
- web planners use OSM maps based on tile servers and the choice/quality of existing maps is very limited for hiking. OpenTopoMap is great but do not clearly render sac_scale and trail_visibility attributes (difficulty/visibility of paths), is slow to update and is missing many usefull POIs. => All this can be solved in Osmand by a customised renderer. It would be so good to have the same map quality on a web app to plan our trips with a big screen (providing that the web interface allow using a customised map rendering file...)
- there could be a sync mechanism between web planner and mobile app using a token or account so that you do not manage twice your profiles/tracks/favorites ...
- It would give even more visibility to the wonderful OsmAnd project

I tried using an android emulator on PC to do exactly that but 3 main drawbacks:
- data are never sync between PC and Mobile. You need frequent file exchanges (profiles, gpx tracks, etc) to keep both synchronised.
- based on local PC setup, can't use it on another computer (the big advantage of a web based solution available from anywhere without setup)
- not very fluid, commands get lost : zooming is a nightmare (using bluestacks)

And finally just to mention that Locus is currently doing exactly that (with full sync with app for Gold members).
Beta version available here : [https://web.locusmap.app/en/](url)

**Comment by dmpr0** [comment]
Beta version is available on [osmand.net/map](https://osmand.net/map/)
