### ISSUE TITLE
Old terrain data in England

### ISSUE THREAD

**Issue by xmd5a2** [osmandapp/OsmAnd#11152]
50.8886693, -0.0107583

**Comment by thompehw** [comment]
A lot of thought and effort has clearly gone into this, (thanks!) but speaking as just one user I would love to have the unsmoothed data! Is it really "noise" (inaccurate measurement) or rather "more detail than a typical user wants"?

With the availability of hillshade and slope colourings these days, might even a typical user of contours want maximum detail? It would also help with the difficulty of mapping all cliffs in OSM, and how to render them with sufficient prominence without cluttering the map. (I know SRTM contours won't show every cliff, but they often give an indication.)

Thanks for your consideration.

**Comment by xmd5a2** [comment]
To map cliffs you can use source data https://data.opendataportal.at/dataset/dtm-europe
> Is it really "noise" (inaccurate measurement) or rather "more detail than a typical user wants"?

I think both of them. I can generate some maps without smoothing personally for you.

**Comment by sonora** [comment]
But the legitimate question remains if we should smoothe something which per se we do not know is smooth.

I am working with contour line data a lot, and in remote areas like deserts they are often the only data we have in our maps to facilitate precise orientation. And yes, xmd5a2 is right that we usually see a mix of noise and data. And while in hilly country smoothed lines look a lot 'nicer', in mountain terrain any smoothing can mean severe data loss of e.g. rock formations which otherwise would have been indicated on our maps but we threw that away....

I vote for being rather careful with any smoothing for the sake of appearance. Our only benchmark for appearance must be reality, not 'nicety'. ;)

**Comment by xmd5a2** [comment]
We must take into account the interests of the majority of users. Most of them live and use contours on plains. There are many examples when small elevation fluctuations leads to unusable chaos of contour lines that makes it difficult to read not only them but entire map. They are almost completely useless in such areas. Especially in deserts with small sand dunes. What kind of details user can understand from these maps? Smoothing that was applied to tiffs during contour creation process improves situation.
![Screenshot_2021-03-16_11-15-44](https://user-images.githubusercontent.com/5829014/111276977-fddfc500-8648-11eb-9478-fdce27fafb9a.png)
![Screenshot_2021-03-16_11-14-11](https://user-images.githubusercontent.com/5829014/111276979-ff10f200-8648-11eb-8c9b-16507214a524.png)
> in mountain terrain any smoothing can mean severe data loss of e.g. rock formations which otherwise would have been indicated on our maps but we threw that away....

This is only partially true. I've done a lot research and haven't found examples when terrain feature was **completely** removed. But I agree that we should be careful with smoothing.

**Comment by Hades1503** [comment]
> We must take into account the interests of the majority of users. Most of them live and use contours on plains. There are many examples when small elevation fluctuations leads to unusable chaos of contour lines that makes it difficult to read not only them but entire map. They are almost completely useless in such areas. Especially in deserts with small sand dunes. What kind of details user can understand from these maps? Smoothing that was applied to tiffs during contour creation process improves situation.
> 
> ![Screenshot_2021-03-16_11-15-44](https://user-images.githubusercontent.com/5829014/111276977-fddfc500-8648-11eb-9478-fdce27fafb9a.png)
> 
> ![Screenshot_2021-03-16_11-14-11](https://user-images.githubusercontent.com/5829014/111276979-ff10f200-8648-11eb-8c9b-16507214a524.png)
> 
> > in mountain terrain any smoothing can mean severe data loss of e.g. rock formations which otherwise would have been indicated on our maps but we threw that away....
> 
> 
> 
> This is only partially true. I've done a lot research and haven't found examples when terrain feature that exists in reality was **completely** removed. But I agree that we should be careful with smoothing.

Hello,

I have already challenged you for the bare_rock and the cliffs because I made a specific rendering for hiking (trekking).

more precise contour lines and shading would allow a better reading of the terrain. it is important, even very important to prepare its route.

is it possible to download and integrate them into osmand for a profile specially made for trekking?
If yes, how ?
what procedure on iphone and android?
