### ISSUE TITLE
Constant recalculation

### ISSUE THREAD

**Issue by EugeneZmeuk** [osmandapp/OsmAnd#11236]
Firstly a screen video capture of a calculated short route overview on Osmand shows the path spontaneously changing between two possible ones as the screen is zoomed in and out. A behaviour I have just noticed today and possibly related to the problem. It's attached as a 7MB mp4 file.

https://user-images.githubusercontent.com/44466116/112201760-a1207380-8c21-11eb-8263-1771d0f276ec.mp4

I then calculated a similar route, screenshot attached, to drive over. I drove this and video/audio captured as well as recording the track as you suggested. The gpx is attached but the large entire video capture has been put on YouTube.
 Link here https://youtu.be/t_nmZZTLA3c

- At 2m40s intermediate destination 1 the route has altered from that at the start. Continued with original route which is now restored.

- At 3m50s "route recalculated" starts to repeat on the original calculated route. Next turn panel becomes indeterminate. Driving through this section, the remainder of route is without incident.

The behaviour at 3 minutes 50 seconds is my main concern, as previously described. It has been much worse than this example. On this example today I never deviated from the original calculated route.

![image](https://user-images.githubusercontent.com/44466116/112201794-ab427200-8c21-11eb-998d-182f473d3145.png)
[2021-03-19_19-35_Fri.zip](https://github.com/osmandapp/OsmAnd/files/6192059/2021-03-19_19-35_Fri.zip)

**Comment by go4tidal** [comment]
This data was obtained using Osmand+ release 3.9.10 on a Google Pixel 2 phone, running Android 11. That said, this behaviour started in Android 10 and earlier versions of Osmand, although perhaps to a lesser extent.

**Comment by Chumva** [comment]
Route recalculation was fixed here for old android versions - https://github.com/osmandapp/OsmAnd/pull/11257.

**Comment by go4tidal** [comment]
Since initiating this issue with support I have investigated Osmand and the settings in depth to try and shed more light on the problems.

Firstly the embedded video showing spontaneous rerouting was calculated from "my position", which relied on the phone location. I have seen similar route changes occur without any zooming, but simply switching back and forth with no obvious prompting. In the settings, navigation/route parameters/recalculate route I found the setting was 9m. I had not previously seen this option, but I do know that location, even high accuracy, is often worse than 9m and noisy. This means the start position changes causing a route change in some cases, as I found. Sure enough with a more reasonable 100m setting the switching between routes stopped. Equally if a start position on the map or a favourite was chosen rerouting did not happen. 

Moving now onto the YouTube link showing constant recalculation announcements. This behaviour can happen in many locations and I have found that once again if the option mentioned in the paragraph above is increased beyond the minimum setting the behaviour stops. I have tested this on the road. Clearly Osmand will recalculate the route if the on road position differs by more than the setting, and will continue until the they converge. As I said previously exceeding 9m positional accuracy is not unusual and so is a bad choice for general car navigation here in the UK. How the minimum was set on my phone is a mystery. Perhaps some more explanation of the more obscure settings to users might be helpful, or possibly a default settings reset option.

So it would seem that the issue is resolved. My thanks to Eugene and Chumva for stepping up.

**Comment by vshcherb** [comment]
Report from user who originated the issue:
"Ironically I solved the problem myself, by investigating all the Osmand settings in depth, and their effects. I found that the recalculation limit on my phone was set too tight at 9m which could not be satisfied by Google location accuracy. Essentially the phone didn’t know where it was !! "
