### ISSUE TITLE
Bug in the priority of the appearance of the cities names 

### ISSUE THREAD

**Issue by anastasiia936** [osmandapp/OsmAnd#11246]
### Description
The small town name Glanmire appears earlier than the big city name Cork

![image](https://user-images.githubusercontent.com/80623554/112337285-72a8a400-8cc6-11eb-92ee-0fc3da0dc6e8.png)
![image](https://user-images.githubusercontent.com/80623554/112337355-82c08380-8cc6-11eb-9381-a18aff03d605.png)

### Your Environment
OsmAnd Version:
Android/iOS version:
Device model:

**Maps used (online or offline):**   
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.

**Comment by xmd5a2** [comment]
Place names are sorted by value of `place` tag and by `population` tag. Our basemap was created when population was "210,000" which means 210 citizen. Now it is fixed in OSM and will be fixed in next basemap generation.
![Screenshot_2021-03-28_13-25-03](https://user-images.githubusercontent.com/5829014/112749176-58720d00-8fc9-11eb-9ab5-ce4ca591cf9a.png)
