### ISSUE TITLE
importing favorites from a file or web source

### ISSUE THREAD

**Issue by jasontrublu** [osmandapp/Osmand#1127]
For longer trips or vacations, I like to mark personal POIs in advance on my pc. It would be nice to have a feature to import them either from a file or a web based resource.

(Should this be already possible, I apologize for wasting your time)

**Comment by rigid** [comment]
:+1: 

it would be awesome, if Osmand would support POIs from .csv or .csv.gz files instead of just .obf file, thus eliminating the need to convert files on a PC. 
Using http URLs to .csv(.gz) files would even be more user friendly. That way, the modification time could be used to keep POIs up to date (displaying a dialog & let the user optionally download  the new version)

**Comment by vshcherb** [comment]
For now we support GPX file (open file in OsmAnd and it allows to import these points)
