### ISSUE TITLE
SharingTrack.gpx route from OpenTracks not reset

### ISSUE THREAD

**Issue by caspervk** [osmandapp/OsmAnd#11332]
I have a list of routes in OpenTracks, which I can open in OsmAnd, but when I go back to OpenTracks (using the back button) and open a different track, the old one is shown in OsmAnd instead. If, however, I close OsmAnd from the app-switcher, a new track is successfully able to be opened.

**Comment by Ungoose** [comment]
This happens only when "Show on map" is enabled for SharingTrack. If you press back, open another track from OpenTracks, the file contents is updated but the old track is still displayed. If you then go to My places and toggle visibility off and on again - the correct one shows up. In older versions, this was less of an issue, because pressing Back turned the visibility off. Now you need to turn it off manually in the menu (lower left button) before pressing back if you intend to view another track, which is neither convenient nor intuitive. 

Can we make it work as before?
