### ISSUE TITLE
Consolidate Track actions on My places / Tracks

### ISSUE THREAD

**Issue by sonora** [osmandapp/OsmAnd#11336]
Original title: My Places/Tracks Visible group misses context menu
Title already says it all. On screen My Places/Tracks you see the tracks currently visible on the map in the top section. That section offers only the switch to show or hide a track, but misses the 3-dot menu for each track with its track related functionality.

If you want to use any of that, you have to scroll down through a (potentially lengthy) folder list and locate the track's 'twin entry',  only then you can use functionality like 'Rename' etc.

**Comment by vshcherb** [comment]
That's a valid issue in many aspects: 
- As of today,  Actions list is complete only in Context menu of the Track.
- Obviously, user doesn't want to leave the screen to do certain actions with track 
- Possible solution for original issue could be to introduce long tap on actions
-

**Comment by vshcherb** [comment]
Partially it will be implemented in 4.3 as https://github.com/osmandapp/OsmAnd/issues/11974

**Comment by Rowin63** [comment]
Thanks for 4.1.1 and the new track-editing-options/menu.
But I dont know how to work with it.

First, I create a new track from A to B. This track is displayed RED in the map.
Getting to the editing menu this track has setting GREEN. This seem to be standard, because all of my tracks (which I did not edit yet) are displayed GREEN here, though they are not green in the map, but RED.

Now I want to set a color to every group/tab.
For this here I miss a checkbox "select all (in this folder/tab)". I have to select 70 tracks.
So I check one by one and set color, width "medium", "arrows on" and "start/finish off".
Step one is done, first group of tracks is blue.

Now I want to continue with the next group of tracks, they have to be yellow.
How do I continue? 
First I have do deselect all previous displayed tracks, otherwise they´re edited again.
HereI would prefere, that the settings I do, only apply to the selected folder, the folder I´m in right now.

Here I have to select again about 70 tracks one by one and edit them.
To avoid this "one-by-one"-selecting I can to go back to the old "my-places-menu" to select and display all tracks in one folder.
And once I´m here, deselect all other displayed tracks.

Now I can switch back to the new menu and continue with my editing of the desired tracks.

Next group, next colour, same procedeure again from the beginning.

You´re on a good way, but this needs to have a better workflow.
Thanks!

**Comment by dmpr0** [comment]
We don't yet implement new track editing menu.

**Comment by Rowin63** [comment]
What´s this?

![Screenshot_20230305_144635_OsmAnd+](https://user-images.githubusercontent.com/95540936/222964347-89b971cd-f10e-4576-bcf9-dd1a5423207d.jpg)

**Comment by dmpr0** [comment]
> What´s this?
> 
> ![Screenshot_20230305_144635_OsmAnd+](https://user-images.githubusercontent.com/95540936/222964347-89b971cd-f10e-4576-bcf9-dd1a5423207d.jpg)

this is new screen to control tracks visibility on the map

**Comment by Rowin63** [comment]
Ok, so my term "track editing" was wrong.
But still my experience with this new "control screen" remains the same. It was nothing but a user feedback.

**Comment by sonora** [comment]
I any case, and understanding that this is more a long term strategy than a short term understading, the very intent of me opening this issue is to combine all track-related functionality from today different places on one convenient screen.

My issue title above targets this to be "MyPlaces > Tracks", but all recent effort which went into the new "Configure map > Tracks" probably indicates that could be the possible target screen.

**Comment by sonora** [comment]
So what"s the point in recently again updating the old  `MyPlaces > Tracks `(https://github.com/osmandapp/OsmAnd/commit/7960d6d1535ca6ccddf43778d8528bee8909005c) with all the functionality the new `Configure map> Tracks `now also has?, (And we now have twice but with a different design, look and feel?)

Isn't it about time to end the dualism between both screens, pick one of the 2 designs, use and maintain one screen only?

**Comment by dmpr0** [comment]
> So what"s the point in recently again updating the old `MyPlaces > Tracks `([7960d6d](https://github.com/osmandapp/OsmAnd/commit/7960d6d1535ca6ccddf43778d8528bee8909005c)) with all the functionality the new `Configure map> Tracks `now also has?, (And we now have twice but with a different design, look and feel?)
> 
> Isn't it about time to end the dualism between both screens, pick one of the 2 designs, use and maintain one screen only?

Configure Map > Tracks is designed to enable or disable tracks visibility on the map.
My Places > Tracks is designed to manage user tracks.

**Comment by Rowin63** [comment]
Two different menus looking almost the same. A little bit confusing.
And still no practical possibility to:
) select all tracks in a folder > set appearance of this selected tracks > deselect all selected tracks
continue with the next folder.

Yes its possible in parts, but not in a nice workflow.
I know it is beta, but it´s pretty confusing... 
Why it has to be two menus...? Here I can set the appearance, but not display them. On the other side, in a far away place of the menu, I can display the tracks, but not change their appearance...

It would be so nice, to have _one_ clear menu with _all_ options.

**Comment by dmpr0** [comment]
As I see, we need to made alpha build because not all understand that nightly builds are not release and development are still in progress. 
@vshcherb please think about providing alpha builds only for team use, I think it well help us to focus on development, not to chat.

**Comment by sonora** [comment]
I like the new MyPlaces design! It is a lot like a conventional file manager and many users will intuitively be able to use it. (OsmAnd as a "GPX Manager", as I had proposed elsewhere.)

So the concept could be to
-  transfer the long-tap functionality to it
- transfer the 'Change appearance' funtiinality to it 
- facilitate 'Change appearance' in combination with its multi-track 'Select' functionality

The result could be the consolidated screen for all "Tracks" functionalities?

**Comment by vshcherb** [comment]
@sonora my observations are
- long tap functionality will stay on selection rather hidden to keep Configure Map emptier
- Change appearance likely to appear in My Places (cause it's full functionality)
- Track management actions shouldn't be present in Configure Map but you can navigation to a track where you can do

**Comment by sonora** [comment]
Here's one bug, let me know if you want these reported as new issue: https://github.com/osmandapp/OsmAnd/pull/17245#issuecomment-1558615941
