### ISSUE TITLE
[Feature Request] Automatic updating of offline maps

### ISSUE THREAD

**Issue by Mosrite** [osmandapp/Osmand#1136]
I think it would be cool if downloaded offline maps could be updated automatically. As the files are huge, there should be additional options to only download maps while charging and while on wifi, so battery and data plan won't be affected. Maybe, a further option could limit these automatic downloads to a certain time of the day, so they will only happen at night and not while the user wants to use the phone.
Thanks for considering my suggestion!

**Comment by ximex** [comment]
:+1

**Comment by mircozorzo** [comment]
Very nice to have!

**Comment by jkufner** [comment]
To make automatic updates possible, a partial updates must be available
first. Map updates are usualy small, but it is hard to effectively
detect what changed in packed binary file without introducing big
overhead to server.

Without partial updates it would significantly increase server load. And
user often does not need to update all maps he has downloaded, because
he donwloaded that map for holiday trip and he will not return there for
next few months if ever, but he is too lazy to delete the map (who would
bother with 32GB SD cards).

**Comment by Mosrite** [comment]
The feature could be implemented as opt-in while asking the user only to enable automatic updating for frequently used maps. Furthermore, a limit could be set how often there will be checks for updates. E.g. the update frequency could be set to one month or so.
Would this decrease the additional server load enough?

**Comment by cserpell** [comment]
I proposed this once in the [mailing list](https://groups.google.com/forum/#!topic/osmand/YNynls7dsz0).

**Comment by vshcherb** [comment]
It is working for OSM Live. Release 2.3.5 will have more stable implementation.
