### ISSUE TITLE
Search screen initialisation

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/Osmand#1143]
Search screen initialisation: Enter Search (POI, Afdress, Coords, History. Find something. Leave screen by any other method than the device's BACK button, e.g use Show on map, or Directions to. Later, from the map screen, go to the dashboard and hit a Search button, but NOT the type of search you had used previously. But regardless, you will falsely always end up on the search tab you had used previously, not the on selected now.

**Comment by sonora** [comment]
Victor, Thanks for fixing this!

Regarding the other issue of "Search screen remains in memory somehow, even
after app is otherwise closed": Of all our screens, the search screens seem
to be the only ones showing this "dirty" behavior (unless exited via the
device's back button), so my impression was we do something wrong when
leaving these screens (or their respective intents), which on the other
hand we do get completely correct on all our other screens or intents. I
read your comment about "let us not fight the platform", but still I would
like to understand why we seem to have this "un-clean" behavior only when
leaving our search screens? I do not seem to have any other Android app
which shows a similar behavior of only one type of screen always residually
remaining in memory when closing the app.

I am aware that removing the "Exit" button would hide (not solve) the
issue, but it may be a bad fix: For one, it does not fix the underlying
issue (if it is one), and secondly , a clean Exit from the app and a clean
re-start is the basis for many debugging activities, and something I often
ask users to perform before reporting "flaky" OsmAnd issues, so we know
exactly what state the app is in when an issue occurs and can reproduce
things better (as some issues naturally depend on usage history).

Best,
Hardy
