### ISSUE TITLE
Trip recording, GPS is lost when screen is turned off

### ISSUE THREAD

**Issue by Zafrkant** [osmandapp/OsmAnd#11602]
Android: ArrowOS 11 (MicroG)
Device: Xiaomi Mi 9T Pro
OsmAnd+: 3.9.10 (F-Droid)

Thanks for great contribution to community.
When I turn off the screen during Trip recording is active, I have issues with interupted tracking and it needed to lock GPS sygnal again.
Doze optimization is disabled for OsmAnd+ and notification is active during tracking.

I've read following article and I got familiarized with Android 11 backgroud location access.
https://docs.osmand.net/en/main@latest/osmand/troubleshooting/track-recording-issues

Some apps like Sygic works normally and have permission for location "Allow all the time".
Is there other way to get it working in background exept that screen needs to be active during tracking, which in my case is not suitable for hiking, usually ~8 hours.

**Comment by duesentrieb17** [comment]
With Android 10 an app needs to request android.permission.ACCESS_BACKGROUND_LOCATION in the AndroidManifest.xml in order to be able to access location, when running in the background.  
Code: <uses-permission android:name="android.permission.ACCESS_BACKGROUND_LOCATION"/>

Users cannot grant this, if the app does not request it.

**Comment by Zafrkant** [comment]
Thanks for explanation.
I've also tried with older version 3.8.5 which had permission "Allow all the time", but issue is the same.
Do you know maybe other solution?

Thanks
