### ISSUE TITLE
In OsmAnd+ appears text message "multiple points"

### ISSUE THREAD

**Issue by anastasiia936** [osmandapp/OsmAnd#11649]
- [x] Fix maps
- [x] Fix C++ code (as Java)
- [x] Fix Maps generation, so it doesn't happen again

### Original issue 
After OsmAnd Live updates when open the OsmAnd+ appears text message "multiple points"

### How to reproduce?
Download the above part of Germany and performed a manual update of the data via OsmAnd live. The last action causes a crash. When restarting the app there is a message on the screen "multiple points" and only the base map is visible. In addition, in the map management menu the continent / country etc selection is missing.

This only happens with Niedersachsen, all other parts of Germany I tried had no problems when doing the live update. 

### Your Environment
OsmAnd Version:3.9.10
Device: Samsung S7
OS system Android 8

**Comment by scaidermern** [comment]
Probably related to #11632 and 11633.

**Comment by tiffchros** [comment]
Because the other two issues (in my opinion duplicates) were closed, I'd like to copy my comment here:
I have the same issue:

Device : dreamlte
Brand : samsung
Model : SM-G950F
Product : dreamltexx
Build : PPR1.180610.011.G950FXXUCDUD1
Version : 9
App Version : OsmAnd~
Apk Version : 3.9.10 400

[exception.log](https://github.com/osmandapp/OsmAnd/files/6462150/exception.log)

for me it worked

-   Goto Menü / OsmAnd Live / Live-Aktualisierungen [deactivate]
-   Menü / Kartenverwaltung / Tab LOKAL / Find "Germany niedersachsen europe" (three dots) / Deaktivieren
-   You have do download a map to have your search index back. Search for addresses results in empty suggestions, if not.

**Comment by ivanPyrohivskyi** [comment]
https://github.com/osmandapp/OsmAnd-tools/pull/398
https://github.com/osmandapp/OsmAnd/pull/11664
https://github.com/osmandapp/OsmAnd-core-legacy/pull/4

**Comment by scaidermern** [comment]
Will there be a new OsmAnd version soon? Or is the fix inside the live diffs? Would be nice to have some more information.

**Comment by ivanPyrohivskyi** [comment]
This problem was fixed inside live diffs. You can safety use live diffs with old OsmAnd versions.
