### ISSUE TITLE
Wikipedia articles restructure

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/Osmand#1166]
https://code.google.com/p/osmand/issues/detail?id=2469

**Comment by vshcherb** [comment]
Fixed

**Comment by crypto-rsa** [comment]
Could you please provide a link to the commit which fixes this issue? It would be great if you did it for all issues :-) I am actually interested in learning a bit about the Osmand code and this would help me greatly.

**Comment by vshcherb** [comment]
It just a new type of downloads available per country and everything else stayed the same.

**Comment by crypto-rsa** [comment]
Sorry, I don't quite understand. Is there not any associated change in the Osmand code?

**Comment by sonora** [comment]
I am a bit puzzled about our new feature, too. We used to have, and still have, the worldwide Wikipedia POIs available per language, so that people speaking e.g. Spanish and English could have these 2 files on their devices.

Now you have to have regional wiki files, right? How would I get the different languages? The English Wikipedia for England is better than the Spanish, so if a Spanish tourist travels to England, they better also have the English Wikipedia present (if they speak English), what is our concept here?

**Comment by vshcherb** [comment]
Per language is deprecated, it is usually to have more than less information. And poi without map doesn't make too much sense. So, now you will have all translation in 1, with smart selection of the top language, but it is possible to switch between translations.

**Comment by sonora** [comment]
That's a good explanation, now I understand. We will have to explain this
in the release notes. What confused me is that the Global Wikipedia files
are still visible under "All Downloads", so we should remove them there?
Thx- Hardy

**Comment by vshcherb** [comment]
Yes, but only after relase. I'm still thinking about conversion and it will be special UI in downloads that explains that. But not sure how yet.

**Comment by sonora** [comment]
Statistically, most people will not speak most languages ...  (another way
of saying most people speak only VERY few languages :-) ). So if we now put
POI files containing ALL languages (per region) on their devices (because
all languages are now packaged in into one file each per region, right?),
aren't we wasting storage with a mess of mostly useless data?

**Comment by vshcherb** [comment]
I wouldn't say useless. As I see few people download English, even if they could somehow read it. They don't download because the size is huge. In the end people see less clue's on the map. Statistically POI are mostly in the Local translation (I think > 95% what I see Netherlands are dutch)! Which to another interesting observation, people visiting other country starting get used to that language anyway! Because they see it on streets and so on. Wikipedia data is very important for sightseeing, even if you couldn't read the article you could get a clue that something is interesting there or get enlighted by local name. This information is anyway on the map, but with Wikipedia is more highlighted. I see only disadvantage for people who would like to download "the whole world" and keep it, but this is not possible today and tomorrow will be less possible I think (or may be more).

**Comment by sonora** [comment]
Yes, I think you have a point. I was thinking about having an article about
the Grand Canyon in 150 languages on my phone, while I can barely read 5
....  :-)  But I guess that's the exception, it may well be that the vast
majority of POI articles exists in only one or 2 languages.

**Comment by sonora** [comment]
So is the following a bug, or a feature:
Have your phone set to English, and OsmAnd set to "System language". Now
via POI search pick a Wiki place for which only a foreign language article
exists. The article is displayed in that language, of course. But the
language indicator (top right) displays the option "English", although
selecting it will only produce the foreign language article again.
Shouldn't the selector be strictly limited to show only available languages?

**Comment by vshcherb** [comment]
POI search now is localized! You can search all languages! basically through all name:*. Displaying "EN" without en article of course is a bug, small but annoying.
