### ISSUE TITLE
Osmand 2.0.1 town search not working with some languages

### ISSUE THREAD

**Issue by l2212** [osmandapp/Osmand#1185]
Hi,
Using OsmAnd 2.0.1 on my LG E460 there are still really big problems if I use determinated languages (since at least 1.9.2, as far as I know):

- Armenian
- Basque
- Bosnian
- Georgian
- Marathi
- Sardinian
- Welsh

I can't search for a lot of towns or streets (I did download the maps, of course), they just do not appear on the results. 
![2015-05-07-00-40-48](https://cloud.githubusercontent.com/assets/11271324/7505383/2b9e19ea-f452-11e4-91a9-7e5897a683d1.jpg)

If I switch, for example, to Italian or English, it works.
![2015-05-07-00-47-46](https://cloud.githubusercontent.com/assets/11271324/7505445/d6008f3a-f452-11e4-9fa8-be4ff6fbf94f.jpg)

Example: downloading the map Italy_Sardinia and searching for Magumadas/Magomadas.

**Comment by xmd5a2** [comment]
I confirm this

**Comment by l2212** [comment]
But why it's happening?

UPDATE: With OsmAnd 2.0.4 the problem is the same.

**Comment by vshcherb** [comment]
We use Сollator (http://docs.oracle.com/javase/7/docs/api/java/text/Collator.html Primary) from Android in order to find similar names by language, it looks like in older Android versions it is not working fine (before 4.3 at least). In these cases we rely on system functions and it works fine on newer functions. For older versions we suggest to use english languages
