### ISSUE TITLE
Map language selection not working on Online tiles

### ISSUE THREAD

**Issue by ddaemon82** [osmandapp/OsmAnd#11928]
### Description
Map language selection and transliteration is only working on Offline vector maps.
When user selects OsmAnd online tiles it is not working.

### How to reproduce?
Set English as map language, you can turn on transliteration too.
Find a location in Cyrillic (Serbia for example, city Subotica)
Using Offline vector maps, the cities are in Latin letters. Changing to OsmAnd online tiles switches back to cyrillic, regardless of the selected map language. (Although streets also have multiple latinic names in openstreetmaps)

### Your Environment
OsmAnd Version: 3.9.10
Android/iOS version:Android 10
Device model: Samsung S8

**Comment by scaidermern** [comment]
Well, the language and transliteration settings work for offline maps because these maps are generated by OsmAnd according to the user's preferences. Online maps are composed of many static images instead. These images already contain all the labels. The labels depend on the settings of the tile server which OsmAnd can't influence.

Maybe there should be a hint somewhere that various map settings won't influence the appearance of online maps.

**Comment by ddaemon82** [comment]
Thank you for the insight.
Ticket should be a Feature request
