### ISSUE TITLE
recalculate route fails...

### ISSUE THREAD

**Issue by noci2012** [osmandapp/Osmand#1222]
Since 2.0.4 (upgraded from 1.9.4)
In NL, i drove from Utrecht to Almere over the A27,the osmand app points me to go over the A1, A6, ...
I continued straight ahead because i needed to refuel, and there are fuel stations further on the A27.
From then on it just complained i need to turn around to the A27->A1 turn right until i was at my destination (going through to A27, waterlandseweg and local roads into Almere-Haven).
It still wanted me to make a 1hour detour, back through waterlandseweg, A27, A1, A6,...
until i was within match distance from my endpoint. (i entered the last street oposite from the original direction).

IMHO the recalculation should find a new match based on the direction of travel. Just as it used to do.
BTW, as i am riding a motorbike, there is no way i can push the screen without stopping at a safe place. So at least it should auto select a new route.

**Comment by vshcherb** [comment]
That was a critical issue in 2.0.1 but it was fixed in 2.0.4.

**Comment by noci2012** [comment]
i didn't get 2.0.1, i will verify again early next week.

**Comment by noci2012** [comment]
works now... 
maybe i did get 2.0.1, after 1.9.4 i upgraded, the upgrade didn't work, because it lost all maps in the process. I removed the version installed within hours and reinstalled again. After that i did ride with it and found the error (2.0.4 was the reported version) . deleted again everything, and reinstall again. after that i actualy could move the maps to the uSD card and things now work like before.

So maybe problems with remnants of the unknown inbetween version.
(oh my Adroid does not auto update)

**Comment by sonora** [comment]
I still think we may have some underlying issue here. I sometimes also seem to observe that e.g. I am on a longer router, but drive a small detour, then come back to the route a little further down before OsmAnd even notices that a re-calculatoin should probably have started. I then follow on the "prescribed" route, but OsmAnd never notices that I am "ahead" of the original route start, (or that maybe a completely new route should be calculated) which starts where I am now and not 10 km back. The only remedy in these cases seems to manually stop/re-start the navigation, which fixes the issue immediately. I have seen these (often hard to reproduce) issues on and off throughout our nightlies and releases for a long time.
