### ISSUE TITLE
Offline routing: brain-dead preference for U-turn & right turn over left turn

### ISSUE THREAD

**Issue by skquinn** [osmandapp/Osmand#1223]
In my city the gaps in the hard median on a secondary road are tagged as secondary_link. In the middle of these is a tertiary road that goes into my neighborhood within about 100 m / 300 ft of my house. Apparently, the offline router sees the secondary_link as more desirable than the tertiary road which crosses the divided secondary road, and instructs me to pass the road I can just make a left turn onto, instead making the next U-turn and a right turn. I can provide origin/destination points to reproduce this upon request.

**Comment by vshcherb** [comment]
It will be good to have screenshots or draw it on the map

**Comment by skquinn** [comment]
Turns out it's not just at a lower ranked road, it happens frequently turning from a secondary onto a secondary road as well. It's almost as if secondary_link is ranked higher than secondary (for example).

Directions from 25 Tidwell Road to 9903 Bauman Road, both in Houston, Texas, should reproduce the issue. As soon as I figure out how to do screenshots and I'm the passenger on a trip where this occurs, I will provide those as well.

**Comment by vshcherb** [comment]
I guess it is about this cross http://www.openstreetmap.org/node/3148308713#map=19/29.84566/-95.37132. May be you can draw how it happens.

Definitely there is a penalty going from secondary to tertiary, but it will be good to understand the whole route.

**Comment by skquinn** [comment]
Actually it has happened other places since, even going secondary to secondary. I originally thought it was due to the lower ranked road but it appears there is more to it than that.

**Comment by vshcherb** [comment]
Could you please draw a path or an example how does it route wrong.

**Comment by skquinn** [comment]
![screenshot_2015-06-02-19-54-35](https://cloud.githubusercontent.com/assets/1595959/7953537/ccc219f4-098b-11e5-9ee5-cc0b5bf4c5e8.png)

This happened just today. There's no good reason to go 0.6mi (close to 1 km) out of the way to make this U-turn and then come back.

**Comment by vshcherb** [comment]
The latest screenshot doesn't really show the problem, because it is possible that your location was detected a little bit higher and UTurn was needed by the location determined, but not the real location.

**Comment by skquinn** [comment]
I was most definitely a good 100 ft (30 m) south of Aldine Mail Route at the time of this screenshot. In fact, if you look at [this map on OSM](http://www.openstreetmap.org/#map=19/29.90192/-95.33237) I'm near the portion where John F Kennedy Boulevard turns around and the service road (into the school) continues east.

**Comment by mjarmstr** [comment]
I can say I'm also seeing this a lot so I'd add a couple of data points.  This first one is at the intersection of US 18 and V56 near [Fredericksburg, IA, US ](http://www.openstreetmap.org/#map=13/42.9544/-92.1500).  The routing is following a GPX route, which accounts for the right turn and U-turn.  The U-turn the on the left is the issue.  It should just turn right when it comes back to V56. 

![screenshot_20151221-102523](https://cloud.githubusercontent.com/assets/5436650/11935894/066c0876-a7d0-11e5-9040-b9495f309711.png)

(Incidentally, if I set the route to Shortest instead of Fastest, it will follow the GPX route correctly and avoids this problem.  It also says that the shortest route is faster than the Fastest route.)

![screenshot_20151221-102608](https://cloud.githubusercontent.com/assets/5436650/11936207/e75644c2-a7d1-11e5-8710-44a661a2cf5a.png)

The second example is near [at the intersection of  US 24 and MO H near Hannibal, Mo](http://www.openstreetmap.org/#map=14/39.6890/-91.5435).  Instead of just turning left onto MO H it goes past the intersection and performs a U-turn.  

![screenshot_20151221-103311](https://cloud.githubusercontent.com/assets/5436650/11935893/066ab3fe-a7d0-11e5-9463-d335133b4971.png)

Both of these examples are following a GPX route, but I've seen the issue other times as well.

**Comment by vshcherb** [comment]
The original issue is fixed
