### ISSUE TITLE
Dutch TTS does not work

### ISSUE THREAD

**Issue by TheLastProject** [osmandapp/Osmand#1229]
I downloaded and enabled Dutch TTS on OsmAnd 2.0.4 and it never outputs any sound. When switching back to English TTS, navigation instructions are spoken currently, yet Dutch stays quiet at all times.

This behaviour is reproducible for me on the Huawei Y530.

**Comment by sonora** [comment]
Likely a tts engine setup issue on the user's device? I have checked our current nl ttsconfig.p file and it looks all right to me (file has not changed since last December). I have also test-downloaded nl-tts, and it does produce sound on my phone (garbled, of course, as my tts engine is not configured to produce Dutch :-) ).

**Comment by vshcherb** [comment]
It was tested on several devices dutch TTS pronounces correctly and it was not changing for a while so it is the same as for 1.9

**Comment by TheLastProject** [comment]
That's all nice and dandy, but that doesn't change the fact that it doesn't work on this device, while English does work. The fact that it is the same as earlier versions is irrelevant as it was the first version installed on the device. Surely, having it work on as many devices as possible, especially ones so common in the basic consumer market, must be worth at least giving me the opportunity to try to help debug why it is broken on this device?

**Comment by sonora** [comment]
@TheLastProject; When we close the issue here, it does not mean we think you have no issue .... but it does mean that to the best of our collective research, given the current information provided, we believe the issue does not lie with the OsmAnd app. Would you please e.g  test if on your device you can get ANY Dutch tts voice , via the OS or other apps? Like: Go to your device's Android tts settings, and listen to a test voice prompt as provided by most versions of the OS? Does that sound all right? We can only fix issues specific to our app. If you PM me, I may be able to give you some hints of how to setup your device to correctly support tts in general, or how to debug if you really find you have issue with Dutch OsmAnd only.

**Comment by TheLastProject** [comment]
You are indeed correct, Dutch TTS engine support was simply not added to Pico on this Huawei device. I have switched to the pre-recorded Dutch voice, which worked.

For comparison, TalkBack talked Dutch with a heavy German accent. I still feel it may be worth trying to figure out if a device supports the chosen TTS language and recommend installing the pre-recorded voice otherwise, but you are correct that it is not really an OsmAnd issue.
