### ISSUE TITLE
Incorrect elevation data on the map

### ISSUE THREAD

**Issue by anastasiia936** [osmandapp/OsmAnd#12306]
In the track created via the Plan route option the elevation change (Aufstieg / Abstieg) is displayed as 21 and 39 meters, but the actual route is nearly perfectly level like the small river in parallel.
Obviously the wrong values are caused by the bridge that crosses the valley.
![Screenshot_20210726-210531](https://user-images.githubusercontent.com/80623554/127491412-36eecc7c-33cb-4b52-ab3f-4b34a340cbf0.png)
![Screenshot_20210726-210550](https://user-images.githubusercontent.com/80623554/127491421-91bff7cd-99dd-4eb7-958f-e544a9b7fc07.png)

**Comment by vshcherb** [comment]
Yes we could detect that situation based on map data as we process cause we know there is a bridge over that place

**Comment by scaidermern** [comment]
I guess this needs to be fixed dynamically? If you pass under the bridge then the previous elevation needs to be kept. If you pass across the bridge then the elevation from the data must be used.

**Comment by yuriiurshuliak** [comment]
The user emphasizes that the higher the altitude, the greater its error. Sometimes it is reduced by 30-40%. 
This was compared to a dedicated GPS device. The app was updated and the altitude correction was uploaded.
![20230510_183624](https://github.com/osmandapp/OsmAnd/assets/127092082/925d0d22-3909-41ac-b217-fd06c87958f3)

![Screenshot_20230510_183643_OsmAnd+](https://github.com/osmandapp/OsmAnd/assets/127092082/42095554-2b73-46f6-933f-ef0626440f43)

**Comment by Fedsmachine** [comment]
Elevations are actually INCREASED not decreased.

**Comment by vshcherb** [comment]
@yuriiurshuliak we don't have a goal to have exactly same number of Garmin, it's not a standard to measure Uphill / downhill and it's algorithm is not open, so this is a irrelevant case.

**Comment by vshcherb** [comment]
@sonora from now we consider to take an integral approach to calculate uphill / donwhill. It means we will use green graph as a reference i.e. if 1st deriviate > 0, it will accumulate uphill as integral, < 0 downhill. It will be visual & easy testable approach. 

In case data of 1st derivative won't be correct we will take specific ways to test it and fix it.

**Comment by Fedsmachine** [comment]
I have travelled with others with several GPS devices (Wahoo, Garmin) and
apps and for some reason OSMand is always 20-40% too high in terms of
elevation calculations. It makes route planning and day planning difficult
so I have to use other apps to route plan. I still live it for navigation.

**Comment by vshcherb** [comment]
@Fedsmachine how do you treat which numbers are correct? 20-40% sounds not much but it's still not clear what it means, obviously counting all points gives higher numbers in uphill / downhill but it's not clear how low uphill / downhill should be

**Comment by Fedsmachine** [comment]
40% error on a 2,000 m day is a lot on a bicycle.

**Comment by sonora** [comment]
Victor is right: There is no "truth", it's a fractal situation. And this is not ideology but pure signal processing: It is all about noise, and with that about the question: "_What type of fluctuation do we want to ignore because we consider it a likely measurement artifact, vs. what do we want to keep as an effect significant for travel_". (Elevation gain/loss for an ant hiking up a mountain and climbing millions of pebbles is completely different than for a human hiker stepping over most pebbles.)

I advise we answer the noise question first. The corresponding algorithm to use, like frequency filtering, moving average, amplitude cut-off, trend channel, etc. needs to be derived, not selected up front.

By my testing the current OsmAnd implementation is quite in line with many "conventional" analysis tools, as long as you don't oversample tracks, which unfortunately many users think increases accuraccy, while it also increases noise. If you limit your sampling rate to e.g  1/30sec for hiking, you will likely find the results quite agreeable.

**Comment by Fedsmachine** [comment]
Thanks for the explanation. How about setting a route? Is there a way to
make that more accurate? That is more important for me. I import the GPX
file and look at the data on the track that shows elevation gains. I also
will set the track using OsmAnd and use elevation data.

**Comment by vshcherb** [comment]
The real data is only "KWh" spent on bicycle or by foot, that allows to measure relief, obviously measuring it correctly is very tricky....

**Comment by sonora** [comment]
@Fedsmachine Setting a route is no different: The "noise question" to be decided is then in our elevation data (SRTM, etc.).

**As an example of how to solve the "noise" question:**
- My previous approach was to say "_Trends which break before reaching 5m vertical change are neglected, trends which exceed that are counted._".

**Brief discussion:**
- That principle implies that (mountain) hikers are not usually worried about <5m undulations, as long as all elevation changes of greater amplitude are accumulated correctly.
- Naturally, a 'dune hiker' or a surfer straddling small undulations all day ling would get 'under-estimated'. 😉
- And the principle is sensitive to large singularity outliers - they count full unless detected as measurement artifacts and filtered.
- The principle is also comparatively insensitive to oversampling, because the 5m-amplitude limit triggers if a vertical change is considered as contributing to an elevation change, but the actually change is then taken from the trend, ignoring any interim fluctuation.

**Comment by vshcherb** [comment]
@sonora I think we should align model to terrain SRTM data, it's well maintained, it doesn't have infinite scale problem (i.e. fractal) we could calculate interpolation based on it and it will be consistent result doesn't matter how many points we put on the track 100 or 10000

**Comment by sonora** [comment]
@vshcherb Yes precisely, valid idea!

The limitations are, naturally, surface-independent motion (e.g.airborne) or steep terrain (e.g.cliff climbing), where recording will beat modeling, of course.

**Comment by vshcherb** [comment]
We already have Elevation correction (in Track / Plan Route), so it's worth to test it out.

**Comment by Cubly** [comment]
Not sure this is the same issue, but I recently started using OSMAnd but find all my imported tracks have an elevation 50-60m higher than reality. 
Havent had this on other apps, I installed the world altitude correction map, but no change. Am I missing something or has OSMAnd always displayed incorrect elevation?
