### ISSUE TITLE
Allow local names for user's own country and English names for rest of world

### ISSUE THREAD

**Issue by cmeeren** [osmandapp/Osmand#1231]
I live in Norway and naturally use local names in OsmAnd when I'm travelling within Norway (as well as Sweden or Denmark, since the languages are very similar and we know the local names). However, when I'm travelling to other countries, I have to switch to English or I won't understand a thing.

It would be great if I could choose a list of countries for which OsmAnd should use local names, and default to English for the rest.

**Comment by derfasthirnlosenick** [comment]
This is a great feature, esp. if one could also have them read by the respective tts. I had a similar thought when the english one absolutely butchered a french name.

**Comment by cmeeren** [comment]
Yes, having it read by the respective TTS would be great!

**Comment by cmeeren** [comment]
Just wondering if this will make it into a release in the forseeable future. I'd absolutely love to have this feature and it would make it much easier for me to recommend osmand to my friends.

**Comment by pieleric** [comment]
I'd say that it shouldn't be an association of country to language, but just languages to languages. Currently, you can either select local language, or one specific language. So your request would be to be able to select a couple of languages to not translate, and the rest default to another (English or selectable?) language.

That said, maybe it could be improved already quite a bit without interface change by having the transliteration of the local name -> English also happening as a fallback for any language which uses latin characters. For instance, in your case, you could then force "Norwegian" as language, and all the Scandinavia would appear pretty much the same as 'local', but when you look at China, you'd have the pinyin display (instead of the Chinese characters).

Concerning reading the names correctly in TTS, I think this is already proposed in issue #1617.

**Comment by sonora** [comment]
We have made the settings for both voice and map language much more directly accessible in recent releases.

Nothing more planned, I am afraid.

I do understand the purpose of this request, but in my opinion it is not a very mainstream feature requested by a significant portion or our uses.
