### ISSUE TITLE
Android emoticons erase all favourites

### ISSUE THREAD

**Issue by sybrenstuvel** [osmandapp/Osmand#1234]
Using Osmand+ 2.0.4. I added a favourite with a pizza-"emoticon" in the description field. After closing and reopening Osmand, all my favourites were gone. The /sdcard/osmand/favourites.gpx file is 0 bytes, and there doesn't seem to be a backup.

Losing all favourites like this is Really Bad. There was no warning that the favourite could not be properly saved. It accepted the pizza-symbol, and when such a symbol is accepted it should never cause such data loss.

**Comment by sybrenstuvel** [comment]
PS: the file /data/data/net.osmand.plus/files/favourites_bak.gpx is also zero bytes long. Apparently it overwrites the old backup, even when the current favourites.gpx is not a valid GPX file.

**Comment by vshcherb** [comment]
Loosing favorites is really bad and we support this request. We will investigate it.

**Comment by jkufner** [comment]
This issue also should be understood as feature request for regular
backups of such important files. Since favorites are typically small XML
file, it should be no problem to make simple copy from time to time.
Lets say once a week. Simply add date into filename and store it next to
live file.

Btw, thank you for reminding me to backup my phone ;)

**Comment by alexey-pelykh** [comment]
This issue is related to https://code.google.com/p/osmand/issues/detail?id=2394 (which was fixed for category and name, but remained for description). Fixed in ff4fe92c149c5c03c6ea334ba5a7b358a73c1aaf

**Comment by sybrenstuvel** [comment]
Thanks for the quick fix!
