### ISSUE TITLE
 "addr:flats" tag does not show in OsmAnd

### ISSUE THREAD

**Issue by anastasiia936** [osmandapp/OsmAnd#12356]
Check coordinate:
52.13188, 21.06403
https://nominatim.openstreetmap.org/ui/details.html?osmtype=R&osmid=1576621&class=building
![image](https://user-images.githubusercontent.com/80623554/127890144-a25a3baf-58e5-4401-a708-9e944413cdc1.png)

**Comment by xmd5a2** [comment]
Partial fix. Names should be rendered for this particular case but not addr:flats
https://github.com/osmandapp/OsmAnd-resources/commit/63ec83fabf97bec2869668207c643309d9357b48

**Comment by syntex1** [comment]
> Partial fix. Names should be rendered for this particular case but not addr:flats
> [osmandapp/OsmAnd-resources@63ec83f](https://github.com/osmandapp/OsmAnd-resources/commit/63ec83fabf97bec2869668207c643309d9357b48)

Why? The name of it is totally irrelevant. The only thing that matters here is the addr:flats, very usefull for the couriers or delivery men. No one needs the name, the problem is, even without any name assigned to the entrance, the addr:flats does not show even after clicking the entrance, which is weird.

**Comment by vshcherb** [comment]
Rendering is important to be worldwide accessible, so in many cases name has priority over addr:flats
