### ISSUE TITLE
In "My tracks" track size of small tracks shown as 0kb

### ISSUE THREAD

**Issue by xmd5a2** [osmandapp/Osmand#1239]
But it's size is less than 1kb, not 0kb.
https://dl.dropboxusercontent.com/u/4624786/osm/Screenshot_2015-05-16-12-26-26.png
It is better to round upward.

**Comment by sonora** [comment]
Leonid, yes, I had investigated that some time ago. Turns out that an "empty" gpx file, i.e. containing just the headers, is already some 300+ bytes long, and as soon as it contains at least one recorded point, it is usually over 500 bytes. So I guess if I implemented a "correct" mathematical rounding, it would do the trick, and the remaining "0 kbyte" files would then just be the ones not containing any points anyway?  Best, Hardy

**Comment by xmd5a2** [comment]
Yes, I think it is correct way of showing gpx size in UI: if file contains at least 1 point - it is 1kb not 0kb. If file contains only header - it has 0kb data.

**Comment by sonora** [comment]
The alternative way of doing this would be we simply do not save any track file at all as long as it has no trackpoints in it ... I will take a look at the code and see what can be done. I guess the easiest is I just implement the mathematical rounding, maybe with an exception to round to "zero" only if the file length is <= the "header-only-file-length".

**Comment by sonora** [comment]
I used math rounding, so only files of 511 Bytes or less now appear as 0 kB, in practice these should all be files without data points.
