### ISSUE TITLE
Info about route lenght for rtept gpx

### ISSUE THREAD

**Issue by xmd5a2** [osmandapp/Osmand#1240]
For now it is not possible to view route length for routes created by OsmAnd itself using "Distance measurement" plugin.

**Comment by sonora** [comment]
True, we show distances between trkpts directly, but rtept need to either be loaded into the distance measurement plugin (then distance is shown in the widget) , or used to calculate a route (in which case the route length is shown by our route details interface). Probably sufficient?

**Comment by vshcherb** [comment]
Distance measurement plugin is a bit in a bad shape cause it is too generic and we simply need to change the way we deal with it otherwise we are doing it too complex. One of the following approaches planned through Map Markers and GPX Tracks, hoping nice combination of these 2 feature will deprecate the plugin.
