### ISSUE TITLE
Search Backerstrabe 14 - point is displayed outside the building

### ISSUE THREAD

**Issue by anastasiia936** [osmandapp/OsmAnd#12517]
### Description
![telegram-cloud-photo-size-2-5251433268912436910-y](https://user-images.githubusercontent.com/80623554/129688048-f280b009-44dd-4cf9-9ea4-0b8b8b6a9fa0.jpg)
![telegram-cloud-photo-size-2-5251433268912436911-y](https://user-images.githubusercontent.com/80623554/129688409-6d21d5bd-af64-43aa-bc07-43bd53d44ca7.jpg)
https://www.openstreetmap.org/way/166869954
### How to reproduce?
Check address 49.82781° N, 10.00839° E

**Comment by thomas01h** [comment]
Hallo together,
the information about the Problem comes from me (by mail to support).
But i mean it a little bit different! 
I find it good if he try to make the navigation to the Entry!

My Problem:
I find the Supermarket and i wont to know the Address! I can read the Street, but without number!
![OsmAnd_Supermarket-PROBLEM](https://user-images.githubusercontent.com/89390529/130440085-bda7e954-17d9-44ac-a25f-3bae7286e100.PNG)

It is in OSM Mapped as Area withe the Tags for Address and Supermarket!

A other Shop where it works with the same Tags in OSM (there is only no Entry Mapped):
![OsmAnd_Other1](https://user-images.githubusercontent.com/89390529/130441984-fb9fb005-64ff-4377-89c5-06de5b908f40.PNG)

And in the bakery in the same Address like the Supermarket it show me the Address too. And this is Mapped without Address!
![OsmAnd_Other2](https://user-images.githubusercontent.com/89390529/130442249-cd3054eb-66c9-4f57-b7fb-44f7317b100f.PNG)

It will be nice if it´s every time possible to see the Address in the details!
And i don´t see the problem by the Mapped Tags in OSM.

**Comment by alisa911** [comment]
https://github.com/osmandapp/OsmAnd/pull/12836
проверила баг по закомментированной сортировке - не воспроизвелся (https://github.com/osmandapp/OsmAnd/issues/9293)
прошлая сортировка была неправильная - нужно сортировать по подсчитанному полю dist так как оно считается по connectionPoint, а у некоторых мест connectionPoint и point отличаются
в текущем баге брался первый в списке адрес, но он был не ближайший
