### ISSUE TITLE
Speed limit voice warnings appear to be broken

### ISSUE THREAD

**Issue by Zero3** [osmandapp/OsmAnd#12672]
### Description

The speed limit voice warnings does not appear to be working. What I have tried/checked:

* I verified that other voice announcements work just fine.

* I checked that speed limit voice warnings are enabled under `Settings -> <profile> -> Navigation settings -> Voice announcements -> Speed limit -> Warning when exceeding` (menu names are roughly translated from Danish, but you get the idea).

* I set the tolerance to -10 km/h. , and drove many hours at maximum allowed speed on different kinds of roads.

* I tested the speed limit warning in the developer module in OsmAnd (number 9.1), and it works fine when triggered from there.

I am using Danish voice announcements. One could think it was related to that, but as mentioned above, the warning works fine when triggered from the developer module, so I am guessing something else is the cause of the problem.

### How to reproduce?

Unsure. They never worked for me. Presumably it works for others, since I could not find any other issues on GitHub about this being broken.

I am available for further testing and debugging, if I can be of any assistance.

### Your Environment
OsmAnd Version: 4.0.7

**Maps used (online or offline):** Online

**Comment by vshcherb** [comment]
? -10 kmh ?

I guess you need to exceed max speed (example 50 kmh) by 10 kmh, i.e. driving 60kmh to get a warning. Probably you've configured it to other way around than expected

**Comment by Zero3** [comment]
@vshcherb I started testing with a tolerance setting of **5 km/h**, which surely must mean "do not warn if you only exceed the speed limit by up to 5 km/h".

But since that did not work, I tried setting it to **-10 km/h** (yes, *minus*! It is available as an option in the selection list!), for which I would expect it to trigger all the time when driving maximum speed. I would not use that value under normal circumstances.

Are you sure that it is the other way around? That makes little sense, in my opinion. But I will test with **10 km/h** as well, just in case.

**Comment by sonora** [comment]
"+" means "exceeding", -means "still below".

You mention above you are using "onli e" maps?? Please use our standard offline map, and start a navigation, then it should work.

**Comment by Zero3** [comment]
@sonora I am using the "standard" map that uses OSM data as well as "live updates". I thought that is what is meant by "online maps"? But it sounds like you are talking about a completely different kind of low-tech static map tiles? So maybe I misunderstood?

**Comment by sonora** [comment]
I have tested yesterday with latest nightly: It seems to work fine during a car navigation. But after stopping the navigation (OsmAnd goes back to my default Browse map profile) I seemed to never get a voice warning again, nor did I ever see the speed limit sign displayed in the lower left corner, which makes me think we do in deed have a regression here of some sort...

**Comment by Lee-Carre** [comment]
I've always experienced this problem using v3 (for several versions (since mid-2019), currently v3.9.10).

I'm definitely using offline maps (kept updated), with live updates enabled.

The problem has persisted regardless of various configuration combinations I try. Both with recorded voice announcements, and TTS (though, both were English-speaking since I'm not fluent in other languages).

This has definitely occurred on roads for which OsmAnd (visually) displayed the tagged maxspeed (as I had configured it to do), so I doubt it to be a problem with OSM data. This has included long drives traversing many roads.

Some announcements do work; directions. However, it seems that no warning announcements are spoken. Be that for ‘speeding’, approaching a hazard. Come to think of it, I don't recall hearing anything other than direction announcements.

The failure occurs regardless of if the warning threshold was set low (like the OP did, to trigger it without actually speeding), and when it was set to ~0 and I happened to be passenger in a vehicle whose driver did exceed the actual posted limit. In both cases, no warning was heard, yet directional instructions were heard reliably.

**Comment by sonora** [comment]
I've tested a lot now, but can only reproduce for the non-navigation case.

(@Lee-Carre Of course settings "Announce if exceefed" and "Traffic warnings" must be selected under the used navigation profile's voice prompt settings.)

**Comment by Lee-Carre** [comment]
> Of course settings "Announce if excee[d]ed" and "Traffic warnings" must be selected under the used navigation profile's voice prompt settings.

Indeed; and they were so enabled.

**Comment by Zero3** [comment]
@sonora I tested some more, with various settings, and in my case, this bug seems to occur when the setting "Traffic warnings" (3rd slider setting) is disabled. But the setting in question, "Announce if exceeded" (9th slider setting), is not displayed as being a subsetting of the "Traffic warnings" setting, nor is it even placed in the same section. It is not grayed out when "Traffic warnings" is disabled either, so I think this bug, in my case, is about the hidden dependency on the "Traffic warnings" setting, which I believe should not be there.
