### ISSUE TITLE
Rendering of cycleway= tags

### ISSUE THREAD

**Issue by 32Vache** [osmandapp/OsmAnd#12708]
# 🚀 feature request

### Description

It would be nice if we could have rendering of cycleway=* tags on the map with a toggleable layer in the Details... menu, to easily see cycling tracks or lanes on the map for easier bicycle trip planning..

Something like this :
![](https://user-images.githubusercontent.com/42336759/132335913-0d9fa623-ef7a-4c6b-a17f-758cbe5c4b5c.jpg)

**Comment by kevinp2** [comment]
Hi @32Vache 

I just recently edited a main road near my neighborhood and faithfully added the cycleway tags as it has bike lanes on both sides.

Having done that, how would you (or others) use or consume this information?  I don't bicycle frequently, so am trying to understand the use cases for this.

**Comment by yeus** [comment]
I can chime in here a little bit.. I would love to have cycle ways in high contrast in the bicycle view. What I do very often is:  start navigation to some destinaion and then just get on the bike and drive in the "rough direction" of the destination. very often, When doing bicycle tours you don#t know the area. So in order to find nice ways I spontaneously choose the directions during the trip while roughly adhering to the osmand navigation. These descisiona re really spontaneous because I don#t want to spend half my tie looking at the map every couple minutes. 

Lets do this as an example:

In the above view. lets say I need to go "south". I am at the intersection "Rue des Chauffours"/"D39" coming from the north. Should i turn left or right? A quick look on (osmand in that situation for example without stopping at the intersection) would immediatly tell me that if I take a right turn, I would have a cycle way on the D39 after the next turn which I don't see from that crossing. These decisions have to be made every couple minutes on a bike trip. High contrast cycle ways as in the above map would tremendously help here.

On another note: 

https://www.openstreetmap.org/#map=15/52.4504/13.3371&layers=Y

the "cyclosm" render engine gives a nice example on what would work here..

**Comment by yeus** [comment]
ohhh one more thing:  in fact its already possible to choose cyclosm as a map source in osmand. But it would be nice to have this kind of style in the cyclemap of the vector view in osmand as well. Bike trips tend to have low signal strengths for your cellphone/internet ;).

**Comment by sonora** [comment]
Actually, accentuating bicycle travel capabilities is one of the purposes of having the bike profile, i.e. if we do not accentuate that enough in that profile it seems like a deficieny...

**Comment by adelobosko** [comment]
It will be nice if it will be in the same appearance as transport.
Or will has a possibility change colour and size by themselves.

**Comment by vshcherb** [comment]
https://github.com/osmandapp/OsmAnd-core/pull/261

**Comment by vshcherb** [comment]
@xmd5a2 
- To have nice we could introduce Main OBF tag like [highway=cycleway-left-major, highway=cycleway-left-medium, highway=cycleway-left-minor]

**Comment by vshcherb** [comment]
Waiting to accept PR https://github.com/osmandapp/OsmAnd-core/pull/261

**Comment by StarQuasar** [comment]
![Screenshot from 2021-12-28 15-00-15](https://user-images.githubusercontent.com/74009448/147618877-24bec2f0-c401-42e1-b78e-63062d459816.png)
![Screenshot from 2021-12-28 15-00-55](https://user-images.githubusercontent.com/74009448/147618880-d140a000-734a-4696-8dea-d092b81e3984.png)
![Screenshot from 2021-12-28 15-01-13](https://user-images.githubusercontent.com/74009448/147618881-3fb29c08-1580-4e5f-b981-96f0d26ea899.png)

`osm`- test map that was used for tests; [tst_cycleway.zip](https://github.com/osmandapp/OsmAnd/files/7786948/tst_cycleway.zip)

**Test environment:**
Test screenshots were obtained by desktop application (`bird`) on the _Ubuntu 18.04.6 LTS_
There actual status of implementation:
https://github.com/osmandapp/OsmAnd-core/pull/261
Known issues:
 - corners is not really smooth for now;
 - intersections of the independent paths.

**Comment by yeus** [comment]
nice work @StarQuasar. Would it be possible to emphasize the cycleways a bit more similar to the cyclosm style?

**Comment by vshcherb** [comment]
![telegram-cloud-photo-size-2-5417997568144685053-y](https://user-images.githubusercontent.com/1042025/149950056-d753daba-7d0c-412d-8bf3-8640d198f51e.jpg)
![telegram-cloud-document-2-5418134590030091347](https://user-images.githubusercontent.com/1042025/149950086-5479f154-31b8-4d43-a69a-3aa3e2965473.jpg)
![telegram-cloud-document-2-5418134590030091349](https://user-images.githubusercontent.com/1042025/149950112-0876dc81-07f3-4233-868d-db1ccbdabb3c.jpg)

**Comment by alex-osm** [comment]
https://github.com/osmandapp/OsmAnd-core/commit/50df37c3792b70fcffadfa1735f2d6bc0aa71e4d
