### ISSUE TITLE
Audio Focus Overhaul - Fix sound management and volume control

### ISSUE THREAD

**Issue by speleoluc** [osmandapp/OsmAnd#12715]
This morning I rode my bicycle to a destination with Google Maps, and came back with OSMAnd+ 4.0.7 on Android 8. The latter's voice directions were played at a lower sound volume (yet, my cellphone Media volume was at maximum setting all the time), making them harder to hear.

**Comment by sonora** [comment]
Have ypu checked that you indeed are using the **media channel** for output, under the respective (in your case likely bike)  profile's `Navigation settings/Voice prompts/Voice guidance output `?

Using the Notification or the phone speaker channel will mean that a different volume setting applies. On most systems the hardware volume buttons are momentarily mapped correctly for any currently playing sound, so using them **during an OsmAnd announcement** should help?

**Comment by speleoluc** [comment]
Yes, the current setting for the Guidance channel is Media. It must be the
default because I never touched that.


-- 
Luc Le Blanc

**Comment by sonora** [comment]
I finally encountered one situation which makes me believe we do have some spurious issue with the audio initialization under certain circumstances: I had a radio app playing via the media output at volume at ~50%,  then in parallel I startet an OsmAnd car profile navigation with output also set to the media channel. 

The OsmAnd prompts were about equally loud, maybe slightly lower. Tapping the device's volume up button during an OsmAnd prompt showed what looked like the media volume setting bar, but set only at about 40%. That being weird already, I upped the volume to where it finally showed 100%. But the OsmAnd prompt sounded unchanged.  When the radio app came back on, its volume sounded unchanged from before, and its volume bar still reported 50%. So in that situation OsmAnd's alleged "media" volume was decoupled  from the system's media volume., and I could not even change it. Also vice versa: Upping the radio app to 100% made the music scream at me, while OsmAnd's loudness remained unchanged.

I then went into OsmAnd's Navigation settings and changed the prompts to the Notification channel. Things worked fine as expected, with the music app continuing to obey the media volume, and OsmAnd now obeying the separate ringtone volume.

Then I changed OsmAnd back to the Media channel, and since then both the music app and OsmAnd were perfectly synced in volume via the media volume sletting, as it should be, i.e. I could make both scream at me at 100%.

Cannot reproduce the bug ever since, no matter what I try.


Will probably have to sift through the AudioManager code to see where the issue could be.

Any help in describing how to reliably reproduce much appreciated. I particularly would like to know if using the Notification audio for OsmAnd fixes the issue for you, and if subsequently changing back to Media reproduces it?

**Comment by sonora** [comment]
Will overhaul our Audio Focus code as I find time, rough battle plan:

- [ ] For API>=26, call `requestAudioFocus()` using an `AudioFocusRequest` parameter: the system will manage the gain and loss of audio focus automatically.

- [ ] Need to verify that the call returns `AUDIOFOCUS_REQUEST_GRANTED`. (Missing so far!)

- [ ] Need to handle when another app gains audio focus (stop / pause / duck playing, likely simply stop). Missing in our code so far from what I see

- [ ] Verify that we reliably abandon focus when playback stops.

- [ ] Verify that we use the same `AudioAttributes` for the focus request and the playback

- [ ] Check "Pausing vs. Ducking" automatic behavior for type SPEECH

- [ ]  `acceptsDelayedFocusGain()`=FALSE

- [ ]  `willPauseWhenDucked()`=TRUE

**Comment by sonora** [comment]
Will continue to monitor but I believe this is fixed.
