### ISSUE TITLE
Speech not working on Samsung Galaxy Ace GT-S5830i

### ISSUE THREAD

**Issue by DrVanScott** [osmandapp/Osmand#1272]
Speech is not working on this phone - neither tts nor samples. Just silence. Interestingly, in the Dev plugin the test does work for samples.

The phone uses android 2.3.6

EDIT: Using Osmand 2.0.4

Do you need further information?

**Comment by vshcherb** [comment]
Most likely it is mute, please check Route Settings -> Top Right corner (was in the same situation recently).

**Comment by DrVanScott** [comment]
Thanks a lot. Issue solved... ;-)

**Comment by DrVanScott** [comment]
Sorry, unfortunately not solved. Today, while biking and using osmand, the speach notifications suddenly stop. Routing still worked, click on the upper left corner (direction arrow for routing) does not repeat speach notification, but the "click sound" was there...

Some minutes later there was an system message informing me about a severe low memory situation.
Restart of OsmAnd does not "unmute" and also does not solve the high memory usage. After rebooting the phone speach worked again. So i assume that the low memory was not OsmAnd's fault. It just suffered from it.

Could low memory be the reason for mute of speach?

I would at least expect a dialog message that speach notification failed. Maybe OsmAnd silently ignores the according exceptions?

**Comment by sonora** [comment]
DrVanScott , I test OsmAnd extensively also on long routes, and I have never encountered anything like this, so I am inclined to say it may be caused by some other process outside OsmAnd. Maybe you want to monitor what other apps are running, and also check RAM usage, e.g. via Android built-in tools like the memory page in the settings? Some devices have something like a "RAM Manager", usually in their Task Manager or Task Killer app, where you can recover used-up RAM, so maybe playing with it can help clarify what the situation is and how it arises.

OsmAnd uses Android's (built-in or separately installed) text to speech (TTS ) engines, I am not aware what kind of feedback OsmAnd could/would get if something fails in TTs. Maybe some of our other developers can comment here.

Best,
Hardy

**Comment by Norbert80** [comment]
Duplicate of #1351.
