### ISSUE TITLE
TIFF images in Wikimedia Commons categories have missing thumbnail 

### ISSUE THREAD

**Issue by Discostu36** [osmandapp/OsmAnd#12765]
### Description
If a linked Wikimedia Commons Category contains images in unsupported format (e.g. TIFF), OsmAnd doesn't show a thumbnail. 

![Screenshot_20210914_170709_net.osmand.jpg](https://user-images.githubusercontent.com/30999326/133284561-0049fc3f-d8db-4ecf-b585-e80ee19a6791.jpg)

### How to reproduce?
Download the latest Osmand Live map for Schleswig-Holstein, Germany and click on https://www.openstreetmap.org/way/580913180

**Comment by Discostu36** [comment]
I think that TIFF support is "nice to have" but displaying URL instead of thumbnail is a bug. Osmand should ignore file types it cannot show a thumbnail of.

**Comment by Danysan1** [comment]
I'm not sure which technique OsmAnd uses for Wikimedia Commons image visualization, in case it's [hotlinking](https://commons.wikimedia.org/wiki/Commons:Reusing_content_outside_Wikimedia/technical#Hotlinking) (linking to `https://commons.wikimedia.org/wiki/Special:FilePath/...`) the solution might be really easy.

Take for example [`node/731008234` ("Ala di Francesco Baracca")](https://www.openstreetmap.org/node/731008234) which links to [Category:Monumento a Francesco Baracca (Lugo di Romagna)](https://commons.wikimedia.org/wiki/Category:Monumento%20a%20Francesco%20Baracca%20(Lugo%20di%20Romagna)).

One of the files in that category is [File:Il Monumento a Francesco Baracca - Lugo - 3.tif](https://commons.wikimedia.org/wiki/File:Il_Monumento_a_Francesco_Baracca_-_Lugo_-_3.tif).

Wikimedia Commons can link to the original .tif file or to a fixed width .jpg thumbnail which is more likely compatible to be shown:
| This URL | results in | because it redirects to |
| --- | --- | --- |
| https://commons.wikimedia.org/wiki/Special:FilePath/Il_Monumento_a_Francesco_Baracca_-_Lugo_-_3.tif | ![image](https://commons.wikimedia.org/wiki/Special:FilePath/Il_Monumento_a_Francesco_Baracca_-_Lugo_-_3.tif) | https://upload.wikimedia.org/wikipedia/commons/4/47/Il_Monumento_a_Francesco_Baracca_-_Lugo_-_3.tif |
| https://commons.wikimedia.org/wiki/Special:FilePath/Il_Monumento_a_Francesco_Baracca_-_Lugo_-_3.tif?width=300px | ![image](https://commons.wikimedia.org/wiki/Special:FilePath/Il_Monumento_a_Francesco_Baracca_-_Lugo_-_3.tif?width=300px) | https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/Il_Monumento_a_Francesco_Baracca_-_Lugo_-_3.tif/lossy-page1-300px-Il_Monumento_a_Francesco_Baracca_-_Lugo_-_3.tif.jpg |

On OsmAnd it appears like this:

![Screenshot_20220131-171142](https://user-images.githubusercontent.com/8406735/151836964-d7eff1eb-1bcb-4eb0-a49b-232c1744c0ea.jpg)

By adding `?width=300px` to the URL it could be possible to solve this problem.
