### ISSUE TITLE
Navigation engine or OSM issue

### ISSUE THREAD

**Issue by EugeneZmeuk** [osmandapp/OsmAnd#12795]
It consistently gives me errors where it will tell me to make a 90 degree turn on an interstate instead of directing me up the exit ramp. Here is an example. This is the junction of I-40 and I-540 in RDU, NC, USA.

![image](https://user-images.githubusercontent.com/44466116/133734268-3bce145f-88b6-40e3-a4ab-8faa3970b5de.png)

Also navigation will sometimes try to get me to turn and go across an area of nothing where there are no roads instead of staying on the actual roads. This is on the iOS app with OsmAnd+ subscription.

**Comment by Zero3** [comment]
@EugeneZmeuk I checked the OSM data, and the issue in your screenshot is caused by a mapping error that was introduced in this changeset 5 months ago: https://www.openstreetmap.org/changeset/104459657. The author unfortunately (most likely by mistake) linked the motorways together in the place where the route turns in your screenshot, and in one other place as well.

I just corrected the mistake in this changeset: https://www.openstreetmap.org/changeset/111698609, and also wrote to the author about it and asked him to correct any other similar mistakes he might have made.

So try updating your map tomorrow, and check if this intersection is then fixed for you.

> Also navigation will sometimes try to get me to turn and go across an area of nothing where there are no roads instead of staying on the actual roads.

This sounds like a different problem, which you probably should create a separate issue for :).
