### ISSUE TITLE
Wrong navigation instructions when biking or hiking along GPX track

### ISSUE THREAD

**Issue by woheller69** [osmandapp/OsmAnd#13031]
Today I tested with 2 devices in parallel with F-Droid OSMAND~ versions 3.9.10 and 3.9.8.
Riding by bike along a GPX route planned with osmand on a third device and shared to the 2 devices used.
Both gave the same wrong instruction:"in 90m (=68m after stopping)  turn right onto Weisspfennigweg"

As you see in the picture the distance to Weisspfennigweg (arrow) is about 500m and several turns away.

![image2](https://user-images.githubusercontent.com/68678880/138127143-38aec02e-b763-4e29-bcab-dd67f654ddf4.png)

If - in such a situation - I go back for maybe 50m and then turn again the route is calculated again and correct. For a while...

_Originally posted by @woheller69 in https://github.com/osmandapp/OsmAnd/issues/11991#issuecomment-947804575_

**Comment by woheller69** [comment]
For whatever reason after a while of working correctly the app starts giving instructions which should be given at the next waypoint or even later.
So the navigation thinks we are already further than we actually are.

**Comment by woheller69** [comment]
With my findings in #13033 that routes planned on my Galaxy TAB 7 with exactly the same fresh installed v3.9.10 APK file and the same installed map lead to wrong times I now wonder if the Galaxy TAB 7 is also the reason for this issue here with wrong instructions. I usually plan all routes on the Galaxy (larger screen) and then send them to the phone for navigation.
Can this be the root cause? But why?

**Comment by EssBee59** [comment]
Hello,
Just for understanding the situation:
The attached gpx file contains for the tour 2 things:
-a track with 370 track-points (trkpt)
- AND a route with 20 route-point (rtept)

It seems, OSMAND is using the route (not the track as shown in RED on the screen shot) for navigation.

For me a very confusing situation!!!!!!!!
(the track was probably created with another profile as currently active on the navigation-phone)

**Comment by woheller69** [comment]
the tour was planned on my tablet with OSMAND -> plan a route
There I set "route between points" to bicycle.
After planning I shared the route to the 2 phones I used for testing.

**Comment by EssBee59** [comment]
Yes, 
but it is strange to find 20 route-points (generally a route only contains start and end points, possibly with some intermediates points)
So, you entered the 20 points manually? Why?

Further, I don´t understand why the navigation differs from the track at the Gnadenwaldplatz... (red track)

Sorry, I tried to reproduce, but no chance.
(I also suspect an issue in ols versions)
I suggest you retest using Osmand 4.1 as suggested by vshcherb
Ess Bee

**Comment by woheller69** [comment]
When making a bike tour I do not want go from A to B. Usually I want to do a round trip along a certain route with nice panorama.
My latest test was with v4.0.7 which was the latest version on F-Droid. This was a different track.
And the strange thing was this:

"The instructions are not given when I have reached a waypoint but when the app thinks it has reached a waypoint."

So lets assume a simple tour:
1000m from now turn right, 200m later turn left.
In such a situation the app might tell me:
in 500m turn right and then 200m later it will tell me to turn left even though I have not even reached the first turn.

At some point it syncs with the real position and works fine for a while

**Comment by EssBee59** [comment]
Hello,

Just a remark:
A lot of errors occur by entering manually so much route-points on the smartphone or the tablet 
==> Look exactly at your router-point number 19, it deviates about 20 meters from your tour?

In the same way I can not understand why your track deviates to the left at the Gnadenwaldplatz... (red track)

I suggest you retest with the version 4.1 and check the quality of your route (if possible only few points entered manually!!)

**Comment by woheller69** [comment]
Will test again next year. For now biking season is over...

**Comment by woheller69** [comment]
But I have a very simple question - leaving all the other details aside:

How can the app tell me "In 90m turn right onto Weisspfennigweg" when I am 500m air line away from this point.
Doesn't the app know my location? I am using GPS only and under free sky my GPS usually has an accuracy of 6m.
Or does the app calculate my position based on assumptions like average speed, direction or whatever?
If it compared my real GPS position with the map it should never get to this instruction, right?

**Comment by EssBee59** [comment]
Your position seems ok (see on your screenshot the blue circle! an it indicates  "582 mter to the goal")

I think, the problem is a wrong routing at the Gnadenwaldplatz, no idea why the red track (left side of the place) appears

**Comment by woheller69** [comment]
maybe the app internally uses a different position for instructions than for display?
Whatever route it takes to the point - it can never be less than air line...
Unfortunately the code is so big, I do not know where to search for the problem.

**Comment by woheller69** [comment]
Retested with latest F-Droid Version 4.0.9

Failed again.

![Screenshot_20211125-144132_OsmAnd~](https://user-images.githubusercontent.com/68678880/143454164-127ed70b-b045-4a8d-9386-46776950f529.png)

Next test Ehen 4.1.x is available

**Comment by EssBee59** [comment]
Hello,

I installed the daily build 4.1.0#33129m and started some tests with "plan a route":
On the quite the same tour I started 2 tests:
First by entering only the start and the end point  ==> Result OK
Then I entered additionaly 3 intermediate route points  ==> Result NOT OK (wrong turn instruchtions and/or  at wrong positions)

**Comment by woheller69** [comment]
Good to hear someone can reproduce this issue... :-)

**Comment by EssBee59** [comment]
Yes, I think, a real problem exists..BUT, only when more than 2 route-points are entered to generate your track/route!

The function "Plan a route" was introduced to build a route by adding existing tracks or routes or creating a new route.

To build your route on a tablet or PC with 20 points, you do not need absolutly this function, 100 alternatives exists!
(As example I create my tours with the brouter-web:
http://brouter.de/brouter-web/#map=13/49.9746/9.1152/osm-mapnik-german_style
Brouter also supports the creation of turn instructions, you have to set the option "turn-instruction-mode" to "osmand-style")

**Comment by woheller69** [comment]
Are you sure this is a problem of the plan a route tool?
Does this problem not exist, if the route is planned somewhere else?

**Comment by woheller69** [comment]
I hope it going to be fixed soon. Sometimes I want to change the route when I am in the mountains without internet access...

**Comment by EssBee59** [comment]
Hello,
I will attach the gpx of my tests:
I created a tour with "plan a route" in 2 ways:
- gpx1 with entering only start and end route-points
- gpx2 with entering additionally 5 intermediate route-points
( I manually inserted a blank line at the place of the intermediate points in the "segment" tags, as example:

          <segment id="39576989" length="3" segmentTime="69.9" speed="6.94" types="49,50,51,52,53,54,23,55,16,35,56" pointTypes=";;" />
 
         <segment id="39576989" length="2" segmentTime="35.43" speed="6.94" turnType="C" types="49,50,51,52,53,54,23,55,16,35,56" pointTypes=";" />

As allready reported, the problem only occurs with gpx2!
To reproduce the error:
-Start navigation using/following the gpx2 track
-type details
-in the "turn list", click on the turn at 32.1 km (TR + Egerländer Straße)
You see, that the tun instruction in entended at a wrong position!

(doing the same with gpx1, the same turn instruction starts at 32.4 km, and this is OK)

So, I think this confirm, that the issue only occurs when several intermediate route points were entered.
(Possibly a "shifting" occurs on the route, because the turns instructions are not linked with a coordinate but with a distance from start which becomes unaccurate wfehn intermediate points are specified.)


 
[GPX1-Only-start-end-point.gpx.txt](https://github.com/osmandapp/OsmAnd/files/7612317/GPX1-Only-start-end-point.gpx.txt)
[GPX2-5-intermediate-points.gpx.txt](https://github.com/osmandapp/OsmAnd/files/7612318/GPX2-5-intermediate-points.gpx.txt)

**Comment by spaanse** [comment]
I had the same issue today, first time I used the app for long distance bicycle navigation.
I originally had a gpx planned in the route planner of the fietsersbond.
Imported this into the app and asked OSMAnd to attach the route to the roads (reducing the hundreds of  track points into 29 route points).
I had few issues in the first part of navigation (quite a few keep left instructions when I am on a single seperated bicycle lane when I needed to go straight).
But at some point the instructions were about three instructions ahead.
However it still properly announced waypoints along the route, and whether I left the route.
When you would leave the route it would recalculate, probably to the next route point. Then instructions would be fine for a bit.

At some point it instructed me to turn left where I knew that it would be a while until the turn. I counted out 75 seconds until the actual intersection. I just looked where route points are of the track; it seems the left turn instruction was given at a route point.

Without knowing anything about the code, I think the the idea of the voice instructions shifting at route points has merit. One part of the code keeps track of the next location to give an instruction at, which has a list of coordinates where to announce something which includes the route points. Another part of the code then has a list of announcements, which does not include route points since nothing has to be said there.

**Comment by daveshaw** [comment]
I also see this problem and have posted about it here https://github.com/osmandapp/OsmAnd/discussions/13546. This was converted to a discussion by an admin but I am certain we are experiencing a genuine bug so I'll throw my lot in with this thread.

**Comment by vshcherb** [comment]
We're investigating the issue but as I see we only have tracks that are created by Plan Route but we don't have actual recorded track, so we can't reproduce it.

**Comment by daveshaw** [comment]
Hi @vshcherb . Just to be completely clear you want me to plan a route, export it, then navigate the same route whilst recording it and provide you both files?

**Comment by spaanse** [comment]
@vshcherb
Could you try the following:

Use the plan route (with snap to road for bicycle).
Plan a route as normal, but before each turn place roughly 3 route points spaced about 100m apart.
Finish the route with a lot of distinct turns.
Then emulate the route.
In the emulation the "virtual GPS" stops at every route point and you get a turn announcement.
As the route goes on the announcements get more out of sync.

I tried the route points for longer distances, but it seems to only trigger announcements at route points if the next (I think actual, not offset) turn is within roughly 200 m from where the GPS location.

Attached is a route for which the bug is noticable with emulation.
I have also included a screenshot where the route points are, in case the gpx didn't remember that.
[OSMAnd Bug.zip](https://github.com/osmandapp/OsmAnd/files/8008254/OSMAnd.Bug.zip)

Map used: Netherlands Gelderland, 1 jan 2022 with incremental updates up to now.
OSMAnd version: 4.1.11, Android

**Comment by daveshaw** [comment]
If it helps I have uploaded a video to YouTube which demonstrates the problem here https://www.youtube.com/watch?v=le86197x9G8. Things start going wrong just after 2:45s and never recover. This is a simulated Navigation of a route built using the Plan a Route functionality but the simulation exactly mirrors my experience when cycling the route for real.

**Comment by Gbernardy** [comment]
I do not know if it will help you to solve the bug of navigation with track,

to by pass the bug I export the track, 
i import the track on another app ... 
i do nothing on this one ... 
I export the track with the navigation instructions ... 
i reimport the track in OsmAnd ...

originally the track had 50 points, 
after the various passages over the thousand points.

i use the track (reimport track) to navigate
