### ISSUE TITLE
Incorrect names in Kurdish language

### ISSUE THREAD

**Issue by anastasiia936** [osmandapp/OsmAnd#13097]
From OsmAnd support request:

There is a problem in osmand and osmand+ with ckb language (central Kurdish branch).
It is specifically with the letters (ڵ، ێ، ڕ، ە), they are don't connect to other letters when they come in the words on the map only (not in the app menus).
The correct writing form of the examples (see the attached images) I gave you, is:
1_ باڵچۆغ / ڵ
2_ عەزیزاوە / ە
3_ جێشانە / ێ
4_ سێخڕان / ڕ

35.51466 45.34537

![1](https://user-images.githubusercontent.com/80623554/139650213-46d752fd-bbce-4c8a-9b44-1940f95524a9.jpg)
![2](https://user-images.githubusercontent.com/80623554/139650229-eeab445f-1c6c-479b-a2f4-7a5d6db90a43.jpg)

Note the mentioned letters in the above words i wrote, how they are connected to each other when they combined to form words.

**Comment by ivanPyrohivskyi** [comment]
Already fixed by new Skia and Harfbooz libraries.
Please use updated OsmAnd app

<img src="https://user-images.githubusercontent.com/1040293/142228321-6c237cbb-4839-424d-ab8b-3fe795b45fd1.png" width="400" /> <img src="https://user-images.githubusercontent.com/1040293/142228315-d94b3f19-5a95-455f-be78-859916238137.png" width="400" />
<img src="https://user-images.githubusercontent.com/1040293/142228308-ff68fdc2-3f75-49ed-bb2c-ba320b6d63ef.png" width="400" /> <img src="https://user-images.githubusercontent.com/1040293/142227680-a2de41c2-6330-4eea-9db7-276f9d575756.png" width="400" />
