### ISSUE TITLE
Route line width

### ISSUE THREAD

**Issue by Nine-Tailed** [osmandapp/OsmAnd#13193]
The default track line thicknesses are now too thin.

![Screenshot_2021-11-17-10-15-24-387_net.osmand.plus.jpg](https://user-images.githubusercontent.com/12549744/142153103-431c5347-dc8b-4eba-8d7f-2c1ef3e0026a.jpg)

OsmAnd Version: OsmAnd~ 4.1.0#33082m, дата выпуска: 2021-11-16
Android: 11
Device model: poco x3 pro

**Comment by Nine-Tailed** [comment]
oddly enough, I can no longer reproduce this bug.

**Comment by vshcherb** [comment]
may be fixed... it appeared very strange probably related to rendering style

**Comment by Chumva** [comment]
Can`t reproduce it

**Comment by seahorse41** [comment]
I am seeing something similar to this, although in the opposite direction. The line width as configured is not as drawn on the screen.
Starting in version 4.3.3 after changing the rendering engine to V2, the track line set to custom 1 px jumped up to 20 or 21 px. Look at the property line shown colored blue.
![20230101-091523_L_osmand-4 3 3_track-line-1px-actually-21px](https://user-images.githubusercontent.com/14300304/210440508-0e6f28df-60f0-4be5-9e6b-22746a64fabe.jpg)
It was never as thin as 1 px in actual on screen, and was about 11 or 12 px in V1. But this jump up is very noticable. I did try editing the track appearance to Thin, but still 21 px.

Now after changing back to V1, and updating to 4.3.5, the line is drawing as 11 px. Instead of a similar screenshot, here is opening the track appearance settings, to show set to 1 px.
![20230103-123306_L_osmand-4 3 5_track-line-show-set-1px](https://user-images.githubusercontent.com/14300304/210440581-46f9fb09-8c6e-46e7-b16c-64458bdb2f76.jpg)

The very next screen, it redraws it, jumping up to a much thicker line in this view. I think I changed it to thin.
![20230103-123315_L_osmand-4 3 5_track-line-now-thicker-than-1px](https://user-images.githubusercontent.com/14300304/210440706-5735baf3-0c6d-425b-984a-3be71a96ea90.jpg)

After exiting the track editor, It resumes 11 px. So same Thin is drawing the same as 1 px.
This above is running on the LG H932.
However on the OnePlus 6T with render V2, it does indeed display as 1 px.
Except actually jumps back and forth from 1 to 2 px where anti-alias wants to make it partially transparent, but is actually displaying solid. That is probably a different issue.

Back to the LG I tried changing the render engine to V2, and confirmed it jumps up to 21 px.
Back down to V1. Back to 11 and 12 px. This is repeatable, a consistent bug here.

Then I opened the track again, and cycled through the Thin, Medium, Thick, and Custom 1 px. Apply. Back. 
Surprise it is now 1 px. I don't know what triggered it to work correctly this time. I'll Guess it is because I also pressed Medium and Thick, instead of just back and forth between Thin and Custom.

Switch to rendering V2. Now 6 or 7 px. This is thinner than 11 px (Thin) but not truly 1 px. Probably an issue for the team working on V2 of the rendering engine.
