### ISSUE TITLE
mandatory migration to new storage folder

### ISSUE THREAD

**Issue by frasty** [osmandapp/OsmAnd#13219]
### Description
Running osmand~ build from Nov 7 2021. Storage folder is /storage/emulated/0/osmand.
After Upgrading to latest nightly build (2011-11-20) osmand forcibly asks to migrate data to new storage location. If I manually specify a storage location, i.e: /storage/XXXX-XXXX/osmand it throws out an error (I/O Error ENOENT). I just want to use a manually specified folder.
After downgrading to master build from 07/11/2021 I can manually specify my storage folder again.

### Your Environment
OsmAnd Version: nightly build from 20/11/2021
Android/iOS version: Android 11
Device model: Realme 7 Pro

**Comment by sonora** [comment]
I hope I am wrong, but I am afraid we may see the effect of
- Google's Target API Level requirememt since 2021-11-01: https://support.google.com/googleplay/android-developer/answer/9859152?visit_id=637731024020996454-1935750653&rd=1#targetsdk&zippy=%2Ctarget-api-level-requirements-for-play-console

- and the 'Android storage updates':  https://developer.android.com/about/versions/11/privacy/storage,

the combination of which may effectively be the end of all prior practice to organize OsmAnd's files in external storage in a both accessible and performant fashion ...

**Comment by vshcherb** [comment]
Yes, we need to migrate. If you see Shared Storage migration, that's the change we have to follow

**Comment by sonora** [comment]
Well, so far the effect seems triggered by targeting API level 30, and that again is mandated by the Play store policy, right? This means that we would have more freedom with builds for other distribution channels?

Also: I already see quite a community saying We will **not** upgrade OsmAnd from v4.0x for now. o there is a certain tendency and risk we may lose all these people for future upgrades of the app...

**Comment by vshcherb** [comment]
It's ok cause it's not our decision. We will remove the check for API level and introduce the check that folder is not available any more for writing. Obviously with target sdk 30 less folders will be available for writing... 

The biggest majority of new users / paid users comes from Google Play so we can't stop this process of developing the application there.

**Comment by sonora** [comment]
Yes, it's the right move to simply check if a folder is writable or not. Any restrictions imposed should come from the system, not be anticipated or pre-filtered in our code with any kind of assumptions.

**Comment by Chumva** [comment]
This check for storage migration dialogue should be changed here - https://github.com/osmandapp/OsmAnd/commit/979b9f3c3ba5523de1ee5b7217765c53eb12b3ef
