### ISSUE TITLE
TTS: street name is prnounced in the wrong way, but TTS engine pronounces it correctly

### ISSUE THREAD

**Issue by thuryn** [osmandapp/OsmAnd#13216]
### Description
When app navigate to a street "K Šíbrovce", it is pronounced "ká šíbrovce" - as two words. But it should say "kšibrovce" - one word. I've checked the spelling with TTS Test app (https://play.google.com/store/apps/details?id=com.artemnikitin.tts) and when I type "K Šíbrovce" it is pronounced correctly. So it seams to me that Osmand sends the name as two separate strings or so.

### How to reproduce?
Navigate to 50.20225° N, 14.47440° E point.

### Your Environment
OsmAnd Version: 4.0.8
Android/iOS version: Android 11
Device model: Xiaomi Mi 9

**Maps used (online or offline):**   
offline

**Comment by sonora** [comment]
From what I see, the street names in OsmAnd get passed to the TTS engine unaltered, i.e. as they appear in the OSM tag.

Can you maybe test in your TTS Test App

- (1) to pronounce the **entire sentence** like OsmAnd speaks it, not just the standalone street name, to see if context makes a difference

- (2) I am aware that some of the sentences OsmAnd passes to the TTS engine contain **an extra blank**, e.g. in total **two blanks** before the street name. Please test if pronunciation is affected by one vs. two blanks.

**Comment by thuryn** [comment]
You were right. When I put one word before the street name, it is pronounced in the wrong way. Only solution I've found is to:
1) remove the colons - colons are wrong anyway, because it says "colon" then
2) when I put dot "." before street name, it is pronounced correctly
Do you think that put the dot character before the street name is correct solution?
I can fix it in the js file and create pull request with this fix.

**Comment by sonora** [comment]
In general, all improvement work invested various TTS engines aims to improve that they **more naturally pronounce the text as it is conventionally written**', i.e. with all the punctuation you would expect exactly in your written language.

As a result, it is not a good idea to introduce any 'extra' or 'special' punctuation just to get one particular TTS engine to pronounce something a little better. My advice would be as follows:
1. Double-check that you are using the latest update of both your **TTS engine**, and your **TTS language file**. Updates for both can normally be installed via the Android (not OsmAnd) system (Input&Language) settings.
2. Maybe try another TTS engine. Even as factory-installed, your system settings may already give you the choice between e.g. using the Google TTS engine and a manufacturer TTS engine (like Samsung usually also supplies their own engine as an option.) In addition, there are third party engines available you can install like an app. Using another TTS engine may make a big difference in how street names, highway abbreviations, distances, etc. are pronounced, because the capabilities between engines vary a lot!
3. If you resort to tune something in OsmAnd's js file, you must be aware that this may improve something for the particular particular TTS engine and version you happen to be using, but would normally break some things for other users and other engines. Hence you may use your own xx_js file and put it in a local folder of your device for OsmAnd to use it, but more than likely this is not a good pull request to OsmAnd because it is not a valid overall improvement.

**Comment by thuryn** [comment]
I agree with you, even it's not good if I suggest the somebody a and then this. But anyway, how can I upload new js file. I've found I'm not able to copy or push the file into the location - it says: error: stat failed when trying to push to /mnt/sdcard/Android/data/net.osmand.plus/files/voice/cs-tts: Permission denied
Is there any solution how to do it?
