### ISSUE TITLE
BROUTER - 4.1

### ISSUE THREAD

**Issue by anten1222** [osmandapp/OsmAnd#13313]
With Osmand 4.09 Brouter was offered, 4.19 no longer

**Comment by TremlC** [comment]
To expand on this: It seems to me like the file access permission system was changed in the latest version. Now Osmand doesn't recognize brouter output files. In the past it worked like this: Either (1) Osmand and brouter were installed in the so called "Common Storage", where Osmand could detect a brouter installation. Or (2) you install Osmand to "external storage" and put a file - specifying the path to the brouter installation - into the tracks folder of osmand. 
With the update, option (1) is gone, since Osmand cannot be installed there anymore. 
With the new permission system, however, Osmand cannot detect any file in its directory that was not created by Osmand itself. This undermines option (2).

**Comment by vshcherb** [comment]
Actually it's quite strange it should not be related to storage cause it's checked via AIDL https://github.com/osmandapp/OsmAnd/blob/feadaa0da5804d9f3312e6df852ef96093fb82ec/OsmAnd/src/btools/routingapp/BRouterServiceConnection.java#L28 and it should not be an option.

**Comment by Chumva** [comment]
This should be fixed here - https://github.com/osmandapp/OsmAnd/pull/13328
