### ISSUE TITLE
Screen orientation change during route calculation causes black screen 

### ISSUE THREAD

**Issue by DaimonPl** [osmandapp/Osmand#1333]
Happened on OsmAnd 2.0.4

**Comment by DaimonPl** [comment]
Once issue

**Comment by breversa** [comment]
I had the same problem with the current version 2.1.1 : changing screen orientation (typically by turning the devices) during calculation would sort of "crash" to my device home screen.

However, I then had to reinstall the app, and I THINK it stopped crashing after that. So maybe it only happens if OsmAnd is updated, not freshly installed ?

**Comment by vshcherb** [comment]
Unfortunately update vs fresh install issue are really annoying, I experienced it many times myself and I can't explain why update process is not reliable sometimes. In many cases you don't really need fresh install, you need to run reupdate, but as a Google Play user you don't have that option.

**Comment by vshcherb** [comment]
Looks related to #1245
