### ISSUE TITLE
All maps deletet

### ISSUE THREAD

**Issue by anten1222** [osmandapp/OsmAnd#13348]
After updating to 4.1, all maps were deleted

**Comment by Rowin63** [comment]
Hello!

Because the other issue #13349 is already closed, I have to reply here:
I double checked it again on another (3rd) device with the same result for 3rd time: 
all existing map data was deletet (almost immediately at the beginning) performing the update from 4.1.9 to 4.1.10
Favourites.gpx, ind.cache, itinerary.gpx, regions.ocbf and World_basemap_mini.obf is all what´s left in that folder (beside all the existing subfolders) after the update. 

Data folder was before and after the update "multi user memory 1": /storage/Cxxx-xxxx/Android/obb/net.osmand.plus

Samsung Galaxy S20+
Android 11

Kind regards,
Robert

**Comment by vshcherb** [comment]
Merged to #13404
