### ISSUE TITLE
Latest nightly: It seems that Announcement Time setting has no effect

### ISSUE THREAD

**Issue by AlexNcUa** [osmandapp/OsmAnd#13445]
### Description
It seems that Navigation Settings -> Voice Promts -> Announcement Time setting has no effect on the latest nightly build. Latest 4.1.x is not affected.

### How to reproduce?
Specify "Early" in the setting, alert announcements played too late, seems to be less that 100 meters / 3-5 seconds.

### Your Environment
OsmAnd Version: OsmAnd Nightly 4.1.0#33309m, released: 2021-12-29, clean install with all caches / data reset.
Android/iOS version: 6.0.1
Device model: Lenovo YT-X703L, Lenovo P2

**Maps used (online or offline):**   
Offline.

### Additional Info
I have also noted that in some settings incorrect units of measurement used for distance. Units of length specified as kilometers / meters in the general settings, but feets used in the Route parameters for some reason (screenshots attached). Probably it is somehow related.

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/91841394/147657755-4cbf3f15-dba0-4099-9516-4b2719c03186.png"  width="300" height="auto"/> </th>
 <th><img src="https://user-images.githubusercontent.com/91841394/147657767-c7f2b8ac-2c9e-45aa-aec9-c3bb70f99942.png"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by Zirochkabila** [comment]
4.2.7 and OsmAnd~ 4.3.0#13799mqta, released: 2022-09-20 - **reproduced** 
[Announcement Time.log.zip](https://github.com/osmandapp/OsmAnd/files/9606600/Announcement.Time.log.zip)
[Announcement Time nightly.log.zip](https://github.com/osmandapp/OsmAnd/files/9606623/Announcement.Time.nightly.log.zip)

**Comment by vshcherb** [comment]
It shouldn't  according to docs https://docs.osmand.net/docs/technical/algorithms/voice-prompt-triggering. I actually don't remember why we disabled that factor for turn preparations.

**Comment by vshcherb** [comment]
Probably @sonora could recall story about it.

**Comment by sonora** [comment]
@vshcherb The answer in the history of what we did here:
- We first had it "one size fits all": Timing was only based on default speed, actual speed, threshold distances, and minimum lead time, i.e. with no overall user setting to uniformly scale all this via "early"/"normal"/"late" etc.
- Then we learned that some devices had so bad GPS reception that due to fluctuations in reported position (e.g. 20 meters behind where you actually are) the very close-up prompts like the "_Turn_ (now)" or "_you have arrived..._" could occur uselessly late (e.g. after you already past the turning point, or after you had already stopped at your destination anyway).
- That's why we introduced the user setting and even called it **ARRIVAL**_DISTANCE_FACTOR, because it was meant to mitigate the use case that your (immediate) arrival at a point was misjudged by your device under the circumstances.
-> _To my recollection, we have never applied that setting to anything further out than the very close prompts on the last few meters._

- With devices getting better over time, the setting for its original purpose would perhaps be obsolete today.
- But in the mean time it perhaps grew into a "matter of taste" setting where users think they can overall scale the timing of **all** voice prompts, also because we have subsequently added more prompts to be affected by the setting, namely
  - Approaching waypoint / favorite / POI
  - Passing waypoint / favorite / POI
  - Off-route announcement,
essentially all line items in the lower half of table  https://docs.osmand.net/docs/technical/algorithms/voice-prompt-triggering which carry a green check mark in column "Arrival setting".

So assuming we do not consider removing the setting entirely, we can leave things much like they were originally, with the setting only affecting very close prompts, or we could simplify the system and expand the setting to affect ALL prompts. This would mean that e.g. something you now hear 1km out would then perhaps move to 2km or so. For the sake of simplicity and discoverability, maybe that's the solution?

**Comment by Zirochkabila** [comment]
@AlexNcUa According to the above @sonora information - you can see on the video that when you change the Announcement time configuration, all indicators except Prepare and Approach was changing. Accordingly, during the navigation, they remain unchanged - what you hear during the navigation.

https://user-images.githubusercontent.com/104760013/192806106-98dfe437-f5d6-4d2b-816a-1cec27837eb0.mp4

**Comment by vshcherb** [comment]
As we stil didn't understand what exactly message prompt is not good though we understand that setting is more complicated i.e. default speed is used for example. I think we can close that setting cause for most of the users it's enough to change just this UI setting
