### ISSUE TITLE
Use Move, not Copy files when changing data storage folder

### ISSUE THREAD

**Issue by sonora** [osmandapp/OsmAnd#13484]
It seems that whenever we change the OsmAnd data storage folder _even within the same storage_ (e.g. within the removable SD card), OsmAnd applies a file-by-file copy mechanism to transfer all files between the old and the new folder.

For the many Gigabytes the OsmAnd data folder usually contains this takes very long. When performing the same operation as a "move" in a file manager app, it will only take a second, because all that is needed is to update the path entries in the file system table (the files will not be re-written).

**Comment by mariush444** [comment]
I vote NO for this.
It is not save especially when osmand move to the folder that can NOT be access by other programs e.g. like file manager.

**Comment by sonora** [comment]
Misunderstanding: Please note this issue does not talk about importing data, but about the OsmAnd data setting to change the data folder. Iam merely talking about the technical method we use. The end result (that the files will appear moved from source to target) will be the same. Only that it will take 3 seconds instead of 30 minutes. 😉

**Comment by mariush444** [comment]
nop, it is not misunderstanding.
Sorry I vote NO.
I lost my data twice because osmand did something during update/upgrade without leaving old data.

Additionally, new rules of Android reject direct access to app's directories/folders.

Sorry again, My point of view is different even it costs 30 min.
I can imagine that osmand team can implement choice copy or move then OK
but if I have to choose copy or move then I choose COPY.

**Comment by vshcherb** [comment]
@sonora we need not only just use copy but probably do something better after copy i.e. verify hashsum / length and only after that remove original file .

I understand for testing is not handy and for cases when you change storage too often but it should not be often though. 

Unfortunately file system api android is not close to normal OS implementation where it wouldn't be an issue.
