### ISSUE TITLE
day/night mode switch only in routing mode

### ISSUE THREAD

**Issue by flohoff** [osmandapp/Osmand#1355]
Hi,
the night view will only be used if in routing mode. When not routing the day view will always be used.

I verified yesterday - At night i had the map running in day view - after selecting a destination and enabling routing osmand switches to night view.

It was much to bright to have it running on the windscreen.

Flo

**Comment by sonora** [comment]
flohoff, the way you describe it is our default behavior, but it can always be changed.

Please go to "Menu/Map configuration" (also accessible via the top-left icon on the map screen). There is a setting for Day/Night view which can be set to different options. Our standard is "Day always" in normal map browsing mode, and "use Sunrise/sunset information" (we have a library to get this right wherever you are on the planet :-) ) in Car mode. Since, when starting a navigation and not specifying a different means of transportation, OsmAnd will switch to car mode by default (for the time of the navigation), you see the behavior you observe. But you can certainly change any profile (like the Browse map, Car, bicycle, Pedestrian profile) to your liking.
