### ISSUE TITLE
Time Zones World

### ISSUE THREAD

**Issue by snooppr** [osmandapp/OsmAnd#13648]
Add an 'overlay' to the time zone map in the form of color and numbers/times.

Advantages: competitors do not have such functionality.

**Comment by mariush444** [comment]
I couldn't find wms or wmst for this but 
in meantime, maybe you'll find as useful gpx  [timezone.zip](https://github.com/osmandapp/OsmAnd/files/7963927/timezone.zip) for borders of time zones that I converted from 
https://openlayers.org/en/latest/examples/kml-timezones.html

**Comment by basings** [comment]
@mariush444 that is genius! 

The map doesn't render anymore when the timezone track is displayed and I am recording a bike trip. Meaning, it's only useful for map exploring and shouldn't be enabled always.

**Comment by mariush444** [comment]
hmmm.... the timezone.gpx is gpx track as any other so it shouldn't be such kind of problems that you noticed.
I try to verify it in mean time.
any way - the gpx seems to be the best workaround for TZ because user can choose color and thickness.
I tried to create obf but the file has some limitations because of rendering.
One can choose only the line defined in rendering file by osmand (seen by osmand)
If you choose line like country border then the zone near/on the border is not visible.
Choosing highway line is not clever.
Any other not important line are usually rendered at the high level of zoom.
e.g. I set "wall" (gray line) for test but it is visible in zoom 14 and higher so it is useless.
[Tzn-wall.obf.zip](https://github.com/osmandapp/OsmAnd/files/8513234/Tzn-wall.obf.zip)
![Screenshot_2022-04-19](https://user-images.githubusercontent.com/66887280/164013371-bf3d1085-c43c-49f3-b48f-ac8cc8b2e720.jpg)

**Comment by basings** [comment]
If it's not bundled within the app, "noone" will use it. Customization is nice but you can't easily modify any other element either, except predefined road styles. 
 Wouldn't either of following customization possibilities suffice?

```
	<renderingProperty attr="showTimezone" name="Show Timezone" description="Show Timezone"
		type="boolean" possibleValues=""/>
```

```
	<renderingProperty attr="TimezoneStyle" name="Timezone style" description="Timezone style"
		type="string" possibleValues="None,Gray,Red" defaultValueDescription="default"/>
```

minzoom 2, nightmode color=white
