### ISSUE TITLE
Regions are not translated to russian when display language is set to "Device language" and device language is "ru"

### ISSUE THREAD

**Issue by xmd5a2** [osmandapp/Osmand#1365]
![screenshot_2015-06-18-11-00-34](https://cloud.githubusercontent.com/assets/5829014/8226688/8d855d76-15a9-11e5-824b-aff8d4100750.png)
![screenshot_2015-06-18-11-01-05](https://cloud.githubusercontent.com/assets/5829014/8226690/908de100-15a9-11e5-811c-1e0b79148416.png)

**Comment by sonora** [comment]
I have not checked to detail, but think we are not very precise with our current concept of when we use the "display language"  (setting PREFERRED_LOCALE) vs. when we use the map display language (setting MAP_PREFERRED_LOACLE) as the basis for which language to use.

Please note that our default values (and this makes sense) are as follows:
- PREFERRED_LOCALE = system locale
- MAP_PREFERRED_LOCALE = local names

I think that most users expect the display language to be honored in most cases (it is usually a language they speak and can read, and the one they set their devices to), while they expect the "map language" to be used only for labels where they may want to compare things with what street signs show, or map labels they are showing natives asking for directions. In a way, people would maybe buy a map at a local gas station, so it would display its labels in the local language and maybe writing, often in addition to English/Latin caharacters, but they would buy their travel guidebooks at home, in their own native language because otherwise they cannot read articles).

What I am saying is we may need a quick plausibility check of which setting we use when we determine the default language to display certain things in, like POI names, wiki articles, etc.

**Comment by vshcherb** [comment]
The issue is somewhere in the code, we should never use PREFERRED_LOCALE in the code and only use Java Locale API. PREFERRED_LOCALE is kind of duplicate setting because it is much better configurable in Android settings. The region names for me looks like the border line because this the entity which is not clearly belong to a map names (because it is too big to have local names and local names will not be clear to anyone), not to user interface language. Though I believe we better display here the language of UI instead of local names, for POI/Address search we should use the map language as more natural.

I will reply about article language & MAP_PREFERRED_LOCALE = local names in a wiki issue.

**Comment by vshcherb** [comment]
Fixed

**Comment by sonora** [comment]
Victor, I concur that the PREFERRED_LOCALE is kind of a duplicate OsmAnd setting, because this should really be set on the device level.

Nevertheless it is no uncommon for bigger apps to have their own interfacec language selector, mainly due to the fact that maybe not all possible device languages may be supported in OsmAnd well enough, so people may want to have a separate choice. Also: For our debugging this is quite handy, I often change the OsmAnd locale to try to assist with issues, without always having to change my whole device locale. Best - Hardy
