### ISSUE TITLE
Make european style coordinates readable

### ISSUE THREAD

**Issue by tradavyvy** [osmandapp/OsmAnd#13653]
# 🚀 feature request

When i copy coordinates from google maps (or some other sources they look like this: 
33,1508340, 74,8831541

With decimal commas instead of decimal points

To use these in the osmand searchbar i have to manualy change the commas into points.

(Technicaly decimal commas are the correct notation)

Please make decimal commas readable in the searchbar.

Manny thanks in advance

**Comment by vshcherb** [comment]
This is looks region specific, I couldn't find in Google these coordinates. In url it's obviously dots and when you copy you get OLC code instead of coordinates. In context menu I see dots

![Screen Shot 2022-01-31 at 13 52 38](https://user-images.githubusercontent.com/1042025/151796910-f526aa85-fb57-40e3-bb7d-bc55f0a7d405.png)

**Comment by tradavyvy** [comment]
When i put a pin on g-maps the only coordinates that coppy easily are the ones i get when i pull up on the horisontal line in the first screenshot.
And there i get the comma version


![Screenshot_20220131-141521_Maps](https://user-images.githubusercontent.com/71978409/151800046-2b0bc620-3cfd-4c36-81ce-3a568c21e793.jpg)

![Screenshot_20220131-141351_Maps](https://user-images.githubusercontent.com/71978409/151800080-68ce7b43-1038-48fd-91c7-f3476e557af4.jpg)

**Comment by vshcherb** [comment]
I have a bug in GMaps ;-) they are displayed as 0.000, 0.000 however on menu displayed correctly

**Comment by vshcherb** [comment]
Merged to #14082
