### ISSUE TITLE
Action arrows too short in roundabouts

### ISSUE THREAD

**Issue by Norbert80** [osmandapp/Osmand#1372]
I found the following bug with OsmAnd+ 2.1.1 "second release" from Play Store.

Depending on zoom levels, action arrows are too short within round abouts. This irritates drivers.

(Perhaps this is a regression of the patches from issue #1337 and issue #1366 respectively. I don't know if this code is in that release.)

The first screen shot is good. The second and third screen shots are bad.

![screenshot_2015-06-21-10-27-42](https://cloud.githubusercontent.com/assets/6921696/8271011/df2ce104-1800-11e5-9fc2-d3073eb6176b.png)
![screenshot_2015-06-21-10-27-50](https://cloud.githubusercontent.com/assets/6921696/8271012/df2d1336-1800-11e5-8548-015587a8a7fa.png)
![screenshot_2015-06-21-10-28-00](https://cloud.githubusercontent.com/assets/6921696/8271013/df2e9a76-1800-11e5-8493-e7be68da99e3.png)

**Comment by vshcherb** [comment]
Certainly not a regression and might not be a bug, because it was not working in any previous build. Certainly it is an issue or a missing feature. 
In this particular case it is bug, because there was intention to get it working.

**Comment by Norbert80** [comment]
The sense of action arrows is additional highlighting beside the purple route line. In the case of round abouts the action arrows are telling the driver to take one exit earlier. So the situation is worse than before the introduction of action arrows.

**Comment by vshcherb** [comment]
I disagree, but that's a subjective question

**Comment by raindropsfromsky** [comment]
Victor,

I have a different take on the yellow arrows: They are like how a navigator commands the driver in a car race. ("Left!", "Right!") The driver is supposed to ***throw*** his car in that direction blindly.

Note that the voice command associated with the arrow is even more important than the arrow itself.
(Reason: The purple line already shows the path. So the arrows really don't add much value visually.) 
It is the voice command that makes the driving safe.

Thus, IMHO the yellow arrows must follow the following rules:
1. They must be as SHORT as possible.

2. Place the arrows on (a) forks, (b) sharp bends and (c) zigzag (because the driver must slow down).

3. Do NOT place arrows at natural bends on the road: The driver will follow the road anyway.
    This reduces chattiness, and information overload.

4. Use a separate arrow for each fork, sharp bend or zigzag.
    Any given arrow must not cover multiple maneuvers.

Thanks!

**Comment by CJTmmr** [comment]
Also: as soon as you enter a roundabout,the turn-"arrow" (top-left) go to the next turn.
Some roundabouts are rather big, it take a while to drive 3/4 round.
I would be nice if the roundabout-turn-arrow (top-left on the screen) could stay there as long as you a driving on the roundabout.
Next-turn could show up as soon as you leave the roundabout.

Good Luck
Kees-Jan

**Comment by raindropsfromsky** [comment]
@CJTmmr,

This discussion is about the yellow arrows that are ovrelaid on the route (purple) line.
You are talking about the ***Next turn*** icon, which is a totally different part of the display.
Please raise a separate bug.

Thanks!
