### ISSUE TITLE
Ring track. App considers to finish just after start of navigation

### ISSUE THREAD

**Issue by Gbernardy** [osmandapp/OsmAnd#13851]
### Description

When starting a ring track, with the starting and ending point very close (A few meters, 5 ÷ 20 meters), if you are closer to the finish when you start navigation, OsmAnd declares that you have reached the finish.

P.s.: Track is imported

### Your Environment
OsmAnd Version:
Android/iOS version:
Device model:

**Maps used (online or offline):**   
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.

**Comment by Lee-Carre** [comment]
Ensure that you instruct OsmAnd to navigate from the start of the track (rather than finding the nearest intersection to have you reach the destination).

**Comment by Gbernardy** [comment]
> Ensure that you instruct OsmAnd to navigate from the start of the track (rather than finding the nearest intersection to have you reach the destination).

Start of track is "My Position". My position is closer to the end than to the beginning of the track.  But if the track is 10/50/100km and the distance between the beginning and the end is only 10/50/100 meters ... it's obvious that I want to start the ring !!

**Comment by vshcherb** [comment]
Nope it's not obvious, in many cases you would like to finish track. So we need to know information whether you continue track or you want to pass whole track.

**Comment by Gbernardy** [comment]
not my case, I open the track and start it for the first time.

**Comment by Lee-Carre** [comment]
> Start of track is "My Position". My position is closer to the end than to the beginning of the track.

There you have it, then; it's doing as you've told it to.

If you want different behaviour, then you need to instruct it, like I advised. Software isn't magic, or telepathic. No amount of complaining will change this.

> if the track is 10/50/100km and the distance between the beginning and the end is only 10/50/100 meters ... it's obvious that I want to start the ring !!

How is it obvious (to anyone else, or especially software)?
How is software supposed to accurately guess your intentions?

Ordinarily, the goal is to reach the destination. So, why would a router take you away from the destination?

You're wanting a special case, for which there is a mechanism to tell OsmAnd. Yet, you refuse to use it, then complain about the results?! 🤨🤦‍♂️

**Comment by Lee-Carre** [comment]
> ![Screenshot of route](//user-images.githubusercontent.com/99968793/156925771-b5acfa2b-0a4f-4b7a-829b-0ca5707bf6f8.jpg)

That's not even a ring. A ring is a closed (continuous) loop.

> I think that if the difference between start and end is less than 20/30mt … if you start the track it is to start it not to end it.

Why, when the destination is just around the corner?
How would that make sense in other cases?

If you want OsmAnd to blindly follow the track, then (once again) you need to tell it to do that. I don't see what's so difficult about giving clear instructions to software for getting the desired results.

I say all this as a user who (for e.g. data-collection / surveying reasons) sometimes uses convoluted planned routes (saved as a GPX track for OsmAnd to follow), and has to tell OsmAnd to follow the track from the start.
The way that OsmAnd does things (i.e. the defaults) makes a lot of sense. I'm glad for the smarter routing, and having the option to alter the behaviour. It's well-designed for being so capable & complex.
It makes me sad (especially for developers on the receiving end of such ungrateful complaining) that some users are, seemingly, never happy (unless the app is perfectly tailored to their exact use-case; everyone else be damned). Not surprising why Linus, occasionally, has an epic rant at people.

Regardless, you could always deviate from the suggested route and let it recalculate.

I did actually have a thought / suggestion, about a remedy / workaround, but I don't think I'm gonna bother explaining it, since that just enables more dysfunctional behaviour, which should be discouraged.

Ultimately; works-for-me & can't-reproduce.

**Comment by Gbernardy** [comment]
I think there is no comment to write ...

**Comment by vshcherb** [comment]
We have some checks some checks to avoid this behavior to not introspect or finish route that is too long away i.e. > 5-10 km if I'm not wrong. In your case you probably also have "very short round track", so software thinks you are about to finish your track already.

**Comment by Gbernardy** [comment]
> We have some checks some checks to avoid this behavior to not introspect or finish route that is too long away i.e. > 5-10 km if I'm not wrong. In your case you probably also have "very short round track", so software thinks you are about to finish your track already.

No min > 30km ...

The following could be one of the algorithms that could give an answer to my question.

If (navigation with track
            And
     start from "MyPosition")
then
     If paremeter <> 0
     Then
         If distance between "MyPosition"
            and start track < parameter
         Then
              Departure from the beginning
              of the track
          else
              Departure from the closest
               point to the track (like now ...)
          end if
       else
           Departure from the closest
               point to the track (like now ...)
        endif
   endif
endif
       
   
Parameter: 
minimum distance to start from beginning of the track;
the use of the parameter could be limited to only a part of the Osmand profile types.

**Comment by pythonneur** [comment]
Hey I just thought I'd give a bit of feedback on navigating loop tracks. I tried using the 'navigate from the start of the track' a few months earlier in the summer on my road bike. It indicated I'd arrived at the destination immediately after starting, but since I didn't want to mess around with it at the side of the road I just put my phone away and let it be. Then I had the idea of making a simple loop track that I would walk around in my neighbourhood. I made a simple loop track, about 700 m that goes up the street, around a small crescent and back down the original street back to the starting point. I made sure to select navigate from the start, but it still said I had arrived at the destination right off the bat. This time, since the point of going on the walk was to see if I could make this work, I simply tried it again and it worked. I'm going to give this another try on a bike ride and see how it goes.
