### ISSUE TITLE
Lanes not rendered or not connected to round abouts at zoom levels 15 and 16

### ISSUE THREAD

**Issue by Norbert80** [osmandapp/Osmand#1385]
Lanes not rendered or not connected to round abouts at zoom levels 15 and 16.

Screen shots have been taken with OsmAndF~2.1.0#7944D.

![zl_15_16](https://cloud.githubusercontent.com/assets/6921696/8316481/a67cac92-19f7-11e5-89ed-cd079a9633e8.png)

**Comment by vshcherb** [comment]
It is always better to show lat/lon on screenshots

**Comment by Norbert80** [comment]
47.983723, 7.7956257

**Comment by vshcherb** [comment]
Strangely enough can't reproduce it, is it latest night build?

**Comment by Norbert80** [comment]
OsmAnd-default.apk	 23-Jun-2015 15:56 	40M

**Comment by Norbert80** [comment]
Will now try...
OsmAnd-nightly.apk	 23-Jun-2015 15:54 	40M

Is it the same but registers as separate App?

**Comment by Norbert80** [comment]
-nightly fails to install. But I think -default is ok.

**Comment by sonora** [comment]
Very strange, I cannot reproduce this at all. Here are my screenshots, using our June 20 (basically 2.1.1 release) dev build. It is Map Style= Touring view, which uses thicker roads and some different colors nut using Map Style OsmAnd default makes no difference.

I have also never seen any issue like this at zoom levels =>12, ever, I think. So I guess we are hunting a completely different phenomenon here ... 
![screenshot_2015-06-24-12-56-34](https://cloud.githubusercontent.com/assets/845735/8328451/1cb7c436-1a71-11e5-8162-76b61188766c.png)
![screenshot_2015-06-24-12-56-40](https://cloud.githubusercontent.com/assets/845735/8328453/1fb11d04-1a71-11e5-892f-707fb552ac71.png)

**Comment by Norbert80** [comment]
@sonora have you tried also "my" resolution? (I can't download youre images on my mobil phone at the moment.)
Could there be any related file in my osmand folder in an old version that I should try to delete?

**Comment by Norbert80** [comment]
Deleting...
- default.render.xml
- regions.ocbf
- poi_types.xml
- ind.cache
... has not solved the problem. :-(

**Comment by sonora** [comment]
Ok, I have been looking into this again, and have identified the problem. It is a "feature" (maybe bug...) of our default renderer. I had never noticed, because I 99% of the time use my Touring view renderer, which by default renders more map detail. 2 ways to work around this issue:
- Either use "Touring view" map style, or
- In Map configuration, under "Details", check the "More details" flag (I use this by default, for all map styles)

Note to Leonid: I think the culprit is the limitation of the number of road segments we display in default.render, likely to increase performance, or to limit map clutter. I have 100 by, while default render uses different much lower values. 

Best, Hardy

**Comment by Norbert80** [comment]
@sonora thanks for investigation and information on this. Do you provide a patch?

**Comment by sonora** [comment]
Norbert, it is almost a "philosophy" question. :-)  For personal and
professional reasons I need a renderer which shows the maximum map detail
we can fit on any screen, that's why a few years back I have developed the
Touring view Map style. Subsequently Leonid has thankfully more and more
taken over maintenance of the default renderer, and has tweaked the
parameters there to find good compromises for a "less cluttered" map
display philosophy (more suitable to the average user), which can also
produce issues, as you discovered.

I copy him on this message.

A patch is not urgent because you can use the "More details" setting and
fix the issue.

Best, Hardy

**Comment by Norbert80** [comment]
@sonora urgent or not... users want this working out of the box. Most users experiencing this may consider OsmAnd as crap and try an other app. Connecting roads to round abouts is not question of additional detail.

**Comment by xmd5a2** [comment]
This issue was fixed some days ago. Can't reproduce.

**Comment by Norbert80** [comment]
@xmd5a2
Have you also tried the following night build?
OsmAnd-default.apk 23-Jun-2015 15:56 40M
OsmAndF~2.1.0#7944D


@xmd5a2 and @sonora
Any chance that you both guys are clearifiying why @xmd5a2 cannot reproduce it and make? Im not involved in the technical details enough... :-(

**Comment by sonora** [comment]
Leonid, I see you fixed it via roadDensityZoomTile, not via
roadsDensityLimitPerTile, like I would have expected. Not sure what the
difference is, should both be ok. I will test and report. Thx - Hardy

**Comment by xmd5a2** [comment]
It was Victor who found solution. Personally I'm not sure with difference roadDensityZoomTile and roadsDensityLimitPerTile

**Comment by sonora** [comment]
I have just tested it using exactly Norbert's coordinates, and the issue is
still there (at least partly, the white road not touching the yellow.).
Fact is that either Touring view with default settings, or with the "More
details" setting the issue disappears. Touring view uses tile size 3, and
roadsDensityLimitPerTile=100, always. default.render uses
roadsDensityLimitPerTile=55 when "More details" is on. So I think we need
to revise the fix, looks like 55 would fix the issue already ... but may
have other unwanted effects in default..

**Comment by xmd5a2** [comment]
Here is a screen from default renderer without moreDetailed option, zoom 16. Same at zoom 15. I think it is fixed.
![_2015-08-04_11-22-18](https://cloud.githubusercontent.com/assets/5829014/9056347/241c7e0c-3a9b-11e5-960e-714e933a0834.png)
