### ISSUE TITLE
Geo share cause tracks to duplicate 

### ISSUE THREAD

**Issue by stevenroose** [osmandapp/OsmAnd#14021]
### Description

I realize this report is quite random and strange. But I recently did an update and updated some maps and I noticed map rendering slowed down **significantly*. To the point that I had to wait 10 seconds for a bit more map to load and I just couldn't use the app anymore. I thought it was a bug in the update and waited several days for a fix, but didn't happen.

I wanted to report the issue, but I first wanted to see if I perhaps enabled some new features or so. I disabled shadows and contour lines and it improved, but not entirely.

Then I noticed I had "98xx tracks shown". I occasionally record a track but not 10 thousand. I opened the track list and just my own 10 tracks were there. I flipped the tracks flipswitch off and the rendering delay disappeared. When I flipped the switch back on, it said only my own "10 tracks shown" and rendering was fine.

So somehow, I didn't try importing anything that I remember, a ton of tracks showed up and totally ruined rendering speed.. 

### How to reproduce?

Absolutely no idea.. 

### Your Environment
OsmAnd Version: 4.1.11
Android/iOS version: Android 9, Oxygen 9.0.2
Device model: OnePlus 6

**Maps used (online or offline):**   
I use the offline vector maps and I have a bunch of zones downloaded. I can provide the full list if that might be relevant.

**Comment by vmicho** [comment]
I can confirm. I have same version and android 11.
It happens (slow down to a slug) during recording.
My observations:
* not showing the recorded track helps a bit - this needs to be set up before starting the REC, because:
* show/not show option of the recorded track does not work during recording when the sluggish mode happens, is stuck on ON (from both recording plugin options, and from My Places -> Tracks)
* deleting all markers and recorded tracks does not help at all.
* reinstalling the app (and thus resetting/deleting all data) removes this condition - i.e. helps (you should not forget to backup markers, tracks, favourites!).
* after recording several more tracks the situation repeats (in my case in about 1-2 months)
* I am using quite lots of markers in the map (might not be related)
* When adding a new marker (long press on map screen) and when it is near a recording trace curve, I get an enormous list of "currently recording track"s - the i can chose any and it will create the marker on the clicked area
* When I tap on a marker that is near the recorder track curve, I get again an enormous list with the marker somewhere there between. But usually it is impossible to find it as there is about thousand other lines of "currently recording track". So the only possibility is to add marker in high zoom and not near the recording track.
* does not happen immediately after starting recording, need to record for several minutes, maybe 1 hour

For me this looks like the app treats the recorded points (or sets of points) as tracks (just my idea)


I've found an older screenshot to illustrate the marker selection:
mtp://%5Busb%3A001,012%5D/Internal%20shared%20storage/Pictures/Screenshots/Screenshot_20211211-174823_OsmAnd+.png

**Comment by rafalwlo** [comment]
[<img src="https://user-images.githubusercontent.com/66125746/165394848-c3138388-1b7e-4fe4-99e3-448183813c0d.png" width="250"/>](https://user-images.githubusercontent.com/66125746/165394848-c3138388-1b7e-4fe4-99e3-448183813c0d.png)

**Comment by vmicho** [comment]
Update: I've found in the Menu->Configure Map->Tracks
that it shows 4042 tracks (which I definitely do not have physically). After disabling the only one that was checked, the counter fell down to 0 or 1.
Now it seems stable during recording.
I'll update if/when the problem reproduces (might take 1-3 months).

![Screenshot_20220428-153357_OsmAnd+ not recording, only showin Rec track from yesterday](https://user-images.githubusercontent.com/66125746/166153188-4709beb7-dee4-456b-a002-21f0fbcb516d.png)

**Comment by scaidermern** [comment]
> Looks like it does not come from normal usage, but from external app asking to show position. Every time osmand is opened for position, the number of shown tracks roughly doubles.

Indeed, I can reproduce this (with OsmAnd 4.2.2).

**Comment by vmicho** [comment]
Update: Still happens in osmand+ 4.2.4 2022-06-15

**Comment by vmicho** [comment]
Update:
With over "200000" tracks displayed, I cannot even turn them off. Turning off markers also does nothing.
Also Osmand takes a lot of CPU.
Also as before it slows down to a crawl until even the android dialog for non-responding app appears.

Even after removing the app from task manager, it still runs! :

![image](https://user-images.githubusercontent.com/66125746/177000922-3a82bda3-e06d-4b8a-883e-550600768c8c.png)

Can be only removed by killing the process, needs root:
```
dipper:/ $ su
dipper:/ # killall net.osmand.plus
```

**Comment by scaidermern** [comment]
Still no milestone set? Several users reported serious performance issues with OsmAnd due to this bug. I think it should get a higher priority. A fix is probably not very hard.

**Comment by vshcherb** [comment]
> Still no milestone set? Several users reported serious performance issues with OsmAnd due to this bug. I think it should get a higher priority. A fix is probably not very hard.

Why users would have over 9000 tracks displayed? It sounds very personal issue. If we talk about heatmap or large collection of GPX it should be converted to OBF file which can support 100 000 of lines

**Comment by vmicho** [comment]
It's not that user have 9000 or 200000 tracks on device. The issue is that osmand displays so many tracks even when they are not there physically.
And every further normal usage (like restarting app, choosing tracks to display, ...) increases that number exponentially when the bug occurs ... until the app is not responding.

**Comment by vshcherb** [comment]
Please post the simplest you know scenario how to get tracks replicated.

**Comment by scaidermern** [comment]
> Please post the simplest you know scenario how to get tracks replicated.

Tap on the map. Share the position. Select OsmAnd for opening. Now the number of displayed tracks has increased. Repeat.

**Comment by vmicho** [comment]
Hi. I described it in few comments above: https://github.com/osmandapp/OsmAnd/issues/14021#issuecomment-1145330641

After several thousands tracks are reported as shown, then the number increases by itself just by using the app (adding markers, show/disable tracks on map, restarting app, adding new tracks by tracking, ...)

**Comment by vshcherb** [comment]
Tried in the latest nightly couldn't reproduce so far.

**Comment by vmicho** [comment]
Do you have few tracks active + currently recording track? Not sure if it will work from 0.
Also try to reproduce first on some of the released versions.

**Comment by scaidermern** [comment]
> Tried in the latest nightly couldn't reproduce so far.

I can reproduce it with the nightly 4.3.0#34323m.

**Comment by Zirochkabila** [comment]
The case was tested with OsmAnd 4.3.0#13626mqta, released: 2022-07-05, and OsmAnd 4.2.6, released: 2022-06-29 - it succeeded, the number of tracks increased

### Steps to reproduce
Configure map > Tracks > Show current track (THIS IS A BASIC CONDITION TO REPRODUCE THE BUG) > a long press on the map > Share > geo: > Select OsmAnd > Configure map > The number of tracks has increased

### Environment
OsmAnd Version: 4.3.0#13626mqta, released: 2022-07-05 / 4.2.6, released: 2022-06-29
Android/iOS version: Android 11
Device model: POCO X3 NFC

https://user-images.githubusercontent.com/104760013/177292289-98411733-38eb-45b7-9e43-c16cc3468942.mp4

**Comment by Discostu36** [comment]
Please fix this bug. For me Osmand has been nearly impossible to use for weeks until I found out (with help from the guys from the telegram channel) that I had 1024 (not physically existing) tracks that were displayed on the map. This bug affects every user who often opens `geo:` links with Osmand. it should not be ignored for months.
