### ISSUE TITLE
Update online map for OsmAnd tracker

### ISSUE THREAD

**Issue by EugeneZmeuk** [osmandapp/OsmAnd#14033]
Telegram message (map update) is not updated 1 hour after the first message was sent. There is an error sending the location.

**Comment by anastasiia936** [comment]
Another case:

**Comment by Aiurek** [comment]
Having similar issues with OsmAnd Tracker loosing the location of multiple people of a group :/ 
Currently planning an game event with around 50 adult people sharing their Live Location using the OsmAnd Tracker, but during test runs it wasn't possible to keep location sharing active, whereby some phone stopped updating their locations almost immediately after their phone screen went black (receiving ERR within the widget in OsmAnd). No obvious access restrictions (unrestricted data access granted, no additional battery saving tools installed) were in place... since the event is planned to take place in 3 weeks from now and I'm still looking forward to it as an opportunity to advertise OsmAnd I really don't know how to deal with that behaviour.

Are there any recommendations on how to alter the Android settings for OsmAnd, Osmand Tracker, Telegram and the Location Sharing in general as well as the Battery saving options in order to make sure that the LiveLocation Tracking is working smoothly (like as a workaround for now)? 

Might the issue be somehow connected to https://github.com/osmandapp/OsmAnd/discussions/11713?

**Comment by Chumva** [comment]
https://github.com/osmandapp/OsmAnd/pull/14135
