### ISSUE TITLE
Feature Request: New Navigation Type for Motorcycles 

### ISSUE THREAD

**Issue by Ralf-88** [osmandapp/OsmAnd#14074]
Hello, I saw that there is a profile for motorcycle in OsmAnd. With the profile I would have connected that the route planning includes a special navigation mode tailored to the needs of motorcycling. When navigating and route planning for motorcycles, some additional attributes are necessary. With a motorcycle, you look for winding routes, you avoid cities and town crossings (if possible). Highways and national roads are used for a day trip to get there, and then you switch to beautiful and idyllic country roads to tour. Desired are the small connecting roads between towns and waypoints and not necessarily the fast main roads. Of course, a highlight would be if there was also a route generation function that automatically creates a route from a few waypoints and allows manual adjustments.
Best regards, Ralf

**Comment by Lee-Carre** [comment]
@Ralf-88

While I relate to what you describe & seek, that's not about the vehicle but the type of journey (touring).

In my area, many people use 2-wheels (often moped, but similar enough) so that they can skip past congestion. They still want a direct (short / quick) route for their commune, though.
I've also done some touring on 4-wheels (well, actually 6-wheels (arguably 8), but that's quite another story).

OsmAnd already has a few features which you can use to tune the router (for your motorcycle profile, separate from other profiles);
* you can tell it to **avoid** certain _types_ of roads, and/or _specific (individual)_ roads
* you can **limit the maximum speed** (vehicle properties / characteristics), so that roads with a high maxspeed (or lower minspeed, I'm not quite sure of the specifics) will be avoided
* when configuring navigation, you can set not only a final destination, but also **waypoints** (intermediate destinations, or `markers`), to influence the routing algorithm's suggested route
* there's a **route planning mode** within OsmAnd for designing a custom scenic tour (this generates a GPX which you can have it follow during navigation; thus, it can also be used to edit existing / imported GPX routes)
* you can **import a GPX** from elsewhere (again, just need to tell it to follow that path, when configuring navigation)
  * perhaps you prefer using other software to plan tours, which outputs a GPX route file
  * maybe you have a favourite website which hosts GPX routes of desirable tours in your area
  * GPX tours you receive from fellow bikers

Hope this helps.

However, very much as a nice-to-have, a touring / scenic mode for the router (regardless of vehicle) would be an interesting feature. Perhaps it could simply (in the background) automate the use of some of the features I mentioned above (ideally user-configurable).
Else, users could configure multiple profiles per vehicle; one for regular day-to-day, and one tuned to suggest scenic / touring routes. Easy to switch between them, then.

**Comment by scaidermern** [comment]
Related to #11606 and #7049.

**Comment by APneunzehn74** [comment]
Hello, I noticed that the motorcycle profile (routing profile) also routes over roads that are explicitly closed to motorcycles. These are entered correctly in OSM. That's not okay.
Best regards Andreas

**Comment by dmpr0** [comment]
Hi @APneunzehn74!
What OsmAnd version are you using?

**Comment by vshcherb** [comment]
Introduced in 4.2 at least, now we can start tweaking specific options

**Comment by APneunzehn74** [comment]
> Hi@APneunzehn74! Welche OsmAnd-Version verwendest du?

Version 4.1.11

**Comment by scaidermern** [comment]
OsmAnd 4.2.2 has the same problem. An example is [this tunnel](https://www.openstreetmap.org/way/154236531) with `motorcycle=no`. With the motorcycle profile OsmAnd still uses this tunnel for routing.
