### ISSUE TITLE
Voice output says "1,000 m" instead of "1 km"

### ISSUE THREAD

**Issue by PinkDuck** [osmandapp/Osmand#1408]
I suspect distances such as 999.6 m are being rounded after conversion to distance unit instead of before, causing metre unit use instead of the more appropriate kilometre.

**Comment by sonora** [comment]
Yes, we do in deed round for e.g.<1000m round to the nearest full 50m, so if this occurs for the example you specify, you will hear "1000m", and serves to indicate  a precision within 50m. The next step up would be hearing "about x km" , indicating things have been rounded to the nearest kilometer, precision is then 500m. Frankly, I see no big benefit in making any change, since how it is now is both mathematically and conventionally/linguistically ok. Also motorway exit signs in many coutries use 1000m to indicate higher precision of  the specification than km-rounded distance measurements to e.g. towns or cities.
