### ISSUE TITLE
(Voice guidance) Voice promts shut off during a phone call?

### ISSUE THREAD

**Issue by Lumordi** [osmandapp/OsmAnd#14083]
Just updated my OSMand maps and now whenever I make a call my voice prompts shut off.  It was annoying before to not be able to hear the other person sometimes, but I would prefer to have them as I've missed several turns and ended up lost because of it.  Is this a bug that can be fixed, or a feature that was implemented?  Are there any settings which can be changed to turn voice prompts back on during phone calls?

**Comment by sonora** [comment]
I am not aware of any change to OsmAnd's audio focus setup ever since I updated it to the recommended best practice. The configuration is described somewhere in this thread https://github.com/osmandapp/OsmAnd/issues/12715.

Bottom line is that OsmAnd ever since truthfully declares its audio output as type Navigation, observes proper etiquette vs. other apps by asking for audio focus before producing sound, and stops any ongoing voice prompt if other apps ask for focus because they deem their output has priority over navigation prompts.

Essentially this means that your phone app decides how to handle OsmAnd prompts both for incoming calls during a navigation prompt and a new navigation prompt asking for audio focus during an ongoing call.

Chances are that most system phone apps will claim high priority and only allow limited or no interruption during a phone call. You may test, for your respective OsmAnd profile(!), OsmAnd's setting 'Navigation/Voice Prompts/Voice guidance output'. Chances are that the phone app may e.g. admit interruptions when you use not the media but the notification channel.

**Comment by sonora** [comment]
Long time no feedback, and I think there is no further action here.
