### ISSUE TITLE
Area amenity=hunting_stand rendered only at high zoom levels

### ISSUE THREAD

**Issue by martinstingl** [osmandapp/OsmAnd#14085]
amenity=hunting_stand which are mapped as an area are only rendered at higher zoom levels than if they were mapped as a single node.
Example:
https://www.openstreetmap.org/way/1021687696
([example](https://www.openstreetmap.org/way/988876874))

### Your Environment
OsmAnd Version: 4.1.11
Android/iOS version: LineageOS 18.1
Device model: Samsung A71

**Comment by Lee-Carre** [comment]
This may also need to be applied for
* `leisure=bird_hide` ([example](//www.openstreetmap.org/way/215605421))
* `leisure=wildlife_hide`

---

> `amenity=hunting_stand` which are mapped as an area

Hmm, [according to the wiki, `amenity=hunting_stand` is supposed to only be a node](//wiki.openstreetmap.org/wiki/Tag:amenity=hunting_stand). Though, over 1000 are already mapped as ways (presumably areas; TagInfo doesn't differentiate).

Though, since it may also count as a building … 🤷‍♂️.
I've certainly mapped the outline of bird hides (designating the area of the physical hut / shelter, itself) as `leisure=bird_hide`, before.
Having checked; bird hides are permitted to be areas (likely as `building=*`).

Perhaps the wiki needs a discussion / update.

**Comment by ivanPyrohivskyi** [comment]
Same as https://github.com/osmandapp/OsmAnd/issues/12968

**Comment by ivanPyrohivskyi** [comment]
PR from https://github.com/osmandapp/OsmAnd/issues/12968

https://github.com/osmandapp/OsmAnd-core-legacy/pull/84
https://github.com/osmandapp/OsmAnd-resources/pull/818
