### ISSUE TITLE
problem to show all POI

### ISSUE THREAD

**Issue by lanlock** [osmandapp/Osmand#1412]
Hey guys,
lately I discovered that osmand is giving me a hard time showing all available POI. The earlier option to set a user defined filter with all categories works but it doesn't save so I need to do all over again after next start. Besides the mark everything button seems to only activate the Wikipedia POI

Best Sven

Version: osmand+ 2.1.1
Htc one x+ 
Android 4.2.2

**Comment by sonora** [comment]
Confirmed, something looks messed up with our Custom POI filter mechanism: Not only that the "Select all" on the categories screen only selects all wikipedia pois but nothing else, also tapping on any category itself, then selecting some or all subcatrgories, then trying an additional selections in another cstegory is broken now.

**Comment by xmd5a2** [comment]
Confirm. But "Select all" option selects "Emergency" category and nothing else in my case, not wikipedia.

**Comment by sonora** [comment]
The problem is that we clear the selections again when for "Select all" we step through the different POI categories, the bug seems in or near PoiUifilter.jave / updateTypesToAccept, but I currently have no access to a machine to fully debug and modify the code, maybe Victor can help out here.

**Comment by sakudo** [comment]
Hi, I'm not sure if I understand the mentioned issues here correctly.But I would be very happy to have better interface to display POIs on the map. Currently, you go through the symbol on the upper left to configure the map, then choose "POI...", then you have to decide on the categories.
It would be nice to have "tick boxes" there, or even a kind of submenu where you could filter e. g. "bars only". (Currently, there is no way to display "bars" and "museums" at the same time.

**Comment by vshcherb** [comment]
Fixed

**Comment by sonora** [comment]
@sakudo: Yes, there is. (Side note to Victor: Many people from my support area do not find it, just like sakudo, because we have 2 ways to display POIs and the one some people only find, like sakudo, has less functionality).

sakudo:
1. From the map screen, tap the dashboard button (lower left corner),
2. on it tap search POI.
3. On the search POI screen tap the 3 dots icon next to the text filter box, and select "Custom filter". 
4. On the resulting selection screen, tap any combination of categories or sub-categories.
5. When done, hit the "Tick" icon in the upper right corner of the screen.
6. To save your selection as a custom filter, hit the "Start" icon (again upper right corner), and select a name for your filter.

Quite a lengthy procedure, and not very obvious, we should probably try to simplify it some, e.g. by explicitly offering "Save as", and not make people guess what icon needs to be tapped next.

**Comment by sakudo** [comment]
Hi sonora, thank you very much for the individual and detailed instructions! It's all there and Osmand - once more - is so full of features!

Two suggestions:

1.) In the "map layer dialogue" (the round button on the left top corner), you could link the first item "POI..." to the very same POI search interface you reach from the "POI" button in the dashboard, hence the user is always lead to the very same interface to filter and show POIs. (NB: This makes a lot of sense because the display of POIs (via dashboard) can be switched off by unchecking the box in the map layer dialogue. So give the user the same experience / interface even if he goes through different menus.)
In more detail: a) If the POIs are not visible (box unchecked in the map layer dialogue), lead the user to one POI search/filter/display interface (that you hit by going through the dashboard).
b) If the POIs are visible (hence box checked in the map layer dialogue), tapping the box just uncecks it. If you tap it again, see a).

2.) In the POI search and filter interface you could replace the three dots at the right top corner as follows:
a) Each category has a check box right in front of it (either as check box then symbol + name, or first symbol, check box then name)
b) Tapping the category's name, opens up a submenu (like already existing in the custom filter menu after hitting the three dots), where individual categories can be checked / unchecked.
This suggestion is not a big change, it only gets rid of the three dots (that can be easily overlooked at the right top corner) and incorporates them in the main window.

I hope, my suggestion is constructive feedback and might help to improve Osmand...
Thank you for taking care of a great app!

**Comment by vshcherb** [comment]
I replied to it in a different group, I think we are moving more to a multiselect option of POI and most likely we will have a special search query "All POI"

**Comment by sonora** [comment]
Dear sakudo, Victor,

Thanks for your suggestions and replies. I guess I was ahead of my time
when I had recently drafted the following suggestions as a result my my
usability analysis ...   :-)

- https://github.com/osmandapp/Osmand/issues/1340
- https://github.com/osmandapp/Osmand/issues/1434

:-)

Best, Hardy
