### ISSUE TITLE
OsmAnd sporadically stopps automatic routing and voice while display is turned off

### ISSUE THREAD

**Issue by Norbert80** [osmandapp/Osmand#1413]
OsmAnd sporadically stopps automatic routing and voice while display is turned off. It also looks like that if the bug is occurring, GPS is turned off while the display is turned off.

Found with OsmAnd+ 2.1.1 second release.

Device is Samsung Galaxy S3.

As already mentioned the bug only occurs sometimes. Until now I don't how to reproduce it step by step.

**Comment by pajakgdynia** [comment]
Re-starting application doesn't help, messages aren't back.
 Only phone reset helps, thus I assume that it is a bug in the Android.

**Comment by Norbert80** [comment]
I'm not sure if this is a Android bug. I only experience this with OsmAnd.

**Comment by vshcherb** [comment]
This issue could definitely be related to memory leaks or even to Android issues. Please be aware that Android tries to kill everything that consumes quite a lot of memory in the background. 
Again this good to have that issue to continue discussion, but it couldn't be opened as a bug, because it couldn't be reproduced.  I hope we can find the reason or at least the stable way how to reproduce it.

**Comment by pajakgdynia** [comment]
Issue is closed, but I have found what's going on.
The problem is with available memory. If not enough is available.. notification silently stops working. Memory leaks, storing too much in the memory, or other applications cause the issue.

.tts sound don't work on my Xperia Active. Too low memory? Before trying sound, memory usage is as follow:
memory usage: 40MB (android limit 41MB, dalvik 17MB)
main memory 12MB (dalvik 40MB, another 8MB)
proportional memory 12MB (android limit 40MB, dalvik 23)
Is is helpful?

On Xperia Z3 it works much better. At least all TTS work. But checking several languages causes stop playing (somehow "randomly"). Other sounds is selected have no messages to be read.
Another thing, I noticed that playing third sound from developer menu ("ROUTE RECALCULATED ..") with PL (non-tts) causes stopping other sounds. It quite repeatable.

I don't know how the sounds are played (internally or via android), but adding "beeps" before sounds would be helpful. This is common way in car navigation (to "wake up" speakers when navigation is connected to AUX)

**Comment by vshcherb** [comment]
I think when you are talking about memory it simply runs out of C++ memory (which is not displayed here). Of course on old smartphones when the whole memory was limited to 512MB and OsmAnd takes 100-150MB for 100-200km ride it was causing even phone reboots.
