### ISSUE TITLE
Pedestrian routes are not prioritised

### ISSUE THREAD

**Issue by toas-koas** [osmandapp/OsmAnd#14148]
# 🐞 routing report

### Routing engine

 OsmAnd's in-app offline routing

### Routing Profile

Pedestrian

### Start and end points

Start
AkademieHotel
Seewiesenäckerweg 54, Rüppurr
Standort: geo:48.98112,8.41349?z=19
https://osmand.net/go?lat=48.98112&lon=8.41349&z=19

Endpoint
Freibad Rüppurr
Nähe Mühlwiesenweg, Rüppurr
Standort: geo:48.97964,8.40081?z=20
https://osmand.net/go?lat=48.97964&lon=8.40081&z=20

### Actual and expected routes

Although there are parallel footpaths to the road, routing is via the road

Version 4.1.11

with http://map.project-osrm.org/ it is not reproducible if you set it to "Foot" there. 

### Screenshots
<details>
    <summary>Details</summary>

![Screenshot_20220427-072023](https://user-images.githubusercontent.com/74021807/165498364-0de6ba3a-2e01-4cd8-8a09-70efb58f12ce.png)
![Screenshot_20220427-072006](https://user-images.githubusercontent.com/74021807/165498373-b9da6d3a-beaa-4b35-8d0c-cd5bfa65b57c.png)
![Screenshot_20220427-071947](https://user-images.githubusercontent.com/74021807/165498380-d26f79a6-89a6-4737-9019-2582d9c83c3b.png)

MagicEarth and OrganicMaps dutifully route over pedestrian paths

![Screenshot_20220427-123009](https://user-images.githubusercontent.com/74021807/165499417-0b17380b-07f5-48e5-9db8-f0c13775d023.png)
![Screenshot_20220427-122939](https://user-images.githubusercontent.com/74021807/165499434-2207d2ab-0f36-4d5b-a068-10087527453f.png)
    Something small enough to escape casual notice.

</details>

**Comment by Nine-Tailed** [comment]
And I have the opposite.  The road is taged as a living street, but the Osmand doesn't want to go along it and makes an unreasonable detour.
![Screenshot_2022-04-27-21-13-53-678_net.osmand.plus.jpg](https://user-images.githubusercontent.com/12549744/165594730-137280fa-1c82-45e6-b4cb-87c8de9163a3.jpg)

**Comment by vshcherb** [comment]
As I see moving around intermediate points it produces 
https://osmand.net/map?start=48.981118%2C8.413484&end=48.980654%2C8.401486&mode=pedestrian#18/48.98009/8.40621 (Cost 955 seconds) vs any other route over pedestrian routes > 1050 seconds.

- So probably if this request is about to sacrifice speed over safety then we need to create special setting to do it.
- If this request is about to forbid routing over these roads then it needs to be mapped as ```pedestrian=no```. 
- Parallel roads is not used likely because there are some penalties over crossings (needs to be checked)

**Comment by vshcherb** [comment]
Parallel roads:
- Pedestrian https://osmand.net/map?start=48.981167%2C8.406222&end=48.980836%2C8.404352&mode=pedestrian ( Cost 181)
- Road https://osmand.net/map?start=48.981135%2C8.406270&end=48.980836%2C8.404352&mode=pedestrian (Cost 127)

Looks like that the main issue with parallel road - unfortunately I don't see the reason of 60 extra seconds, so that looks need to be fixed

**Comment by toas-koas** [comment]
> If this request is about to forbid routing over these roads then it needs to be mapped as pedestrian=no.

Here probably foot=no should be entered. pedestrian=no should not be entered according to the wiki.

**Comment by vshcherb** [comment]
Work in progress:
https://github.com/osmandapp/OsmAnd/commit/2cce2a292df8b484e76486a8bd762749b38ea4d9
https://github.com/osmandapp/OsmAnd-resources/commit/47cd34df7b7ba28e771a2fd515990a4002298178

**Comment by alisa911** [comment]
java [#14256](https://github.com/osmandapp/OsmAnd/pull/14256)
c++ [osmandapp/OsmAnd-core-legacy#87](https://github.com/osmandapp/OsmAnd-core-legacy/pull/87)
test [osmandapp/OsmAnd-resources#822](https://github.com/osmandapp/OsmAnd-resources/pull/822)

**Comment by alisa911** [comment]
- [ ] compensate first segment difference
- [ ] fix routing time on crossroads (penalty ~ 50 sec) 
from https://www.openstreetmap.org/way/183568147 to https://www.openstreetmap.org/way/193455264
- [ ] ? add https://github.com/osmandapp/OsmAnd-resources/blob/master/routing/routing.xml#L1935
<select value="1.2" t="highway" v="path"/>

**Comment by alisa911** [comment]
https://github.com/osmandapp/OsmAnd-resources/pull/824
<img width="902" alt="Screenshot 2022-05-20 at 13 55 55" src="https://user-images.githubusercontent.com/38911173/169514253-b0f93417-62ef-4410-8054-8a217f77b683.png">
