### ISSUE TITLE
Navigation sending me through u-turn

### ISSUE THREAD

**Issue by vmicho** [osmandapp/OsmAnd#14173]
My version: osmand+ 4.1.11, android 11

Osmand sent me through a U-turn and slightly longer way.
Checked OSM in edit mode, nothing really unusual. Just the B 1 road should have 3 lanes (one extra slight-right) to be 100% correct.
As a workaround I can also add a (logical) no-u-turn to B 1.
But still the mystery is the current osmand routing not going through the first link.
Tested on maps (Germany - Lower Saxony) from Jul 2021 and now fresh from Apr 2022.

The expected routing is as shown on OSM (also on gmaps):
https://www.openstreetmap.org/directions?engine=graphhopper_car&route=52.15891%2C9.86951%3B52.15713%2C9.87227#map=18/52.15824/9.87285

<details>
    <summary>Screenshots</summary>

Current routing:
![Screenshot_20220501-165159_OsmAnd+](https://user-images.githubusercontent.com/66125746/166152450-4efa4ed9-7b41-4fcf-95ca-3fce001dac01.png)

Expected routing (using waypoint):
![Screenshot_20220501-170520_OsmAnd+](https://user-images.githubusercontent.com/66125746/166152476-6aeebbb1-e1b7-4847-a8ce-728d40479461.png)

</details>

**Comment by vshcherb** [comment]
The easiest would be to disable u-turn if it's not legal there.

The cost is nearly the same 130 seconds vs 125 seconds (u-turn), mostly due to primary -> tertiary -> secondary road maneuvre which considered to be incorrect.

<details>
    <summary>Screenshot</summary>

![Screen Shot 2022-05-02 at 12 39 48](https://user-images.githubusercontent.com/1042025/166222123-f474f16f-9eee-455d-ae70-b17024243384.png)

</details>

**Comment by vmicho** [comment]
Well i've added no-u-turn and some turn lanes as said before, should help for this ^.^
