### ISSUE TITLE
Osmand should remember to the chosen menu view

### ISSUE THREAD

**Issue by enomat** [osmandapp/Osmand#1417]
When I open the menu, there is a button in the top-right corner to switch between the new dashboard view, and the list view.

![screenshot_2015-06-28-12-22-06](https://cloud.githubusercontent.com/assets/12612250/8396009/38dac044-1d93-11e5-85b2-903b6f0c583a.png)

If you want to open the menu, Osmand always opens in the dashboard view mode.

Osmand should remember and open in the view mode that you chose last time.

**Comment by sonora** [comment]
We actually had this for some trial builds while we introduced the dashboard, and I can report that it confused the heck out of people, because then tapping our "Menu" button in the lower left corner of the map screen resulted in different actions depending on usage history. I know it would not be _that_ unusual to have something like this, but I had a LOT of user feedback saying they found this very incomprehensible...

**Comment by enomat** [comment]
It's sad to hear. I can't understand those people/users.

But you can make it optional in the General settings.

**Comment by sonora** [comment]
Honestly, I personally think the underlying issue here is that our new UI implementation is still incomplete: We now have a dualism of the old menu-driven and the new dashboard-driven approach, i.e. one has not completely replaced the other, and hence we have both, duplicating some 90% of the functionality. If we trust the dashboard is a good design, our goal should probably be to replace the menu completely.

**Comment by enomat** [comment]
The dashboard is good, because it offers quick acces to the most frequently used features.
The old list menu is good, because it offers more features in a smaller place, so we don't have to scroll much. And the list view is more obvious.

Anyway, until the time comes when you decide to use one menu view only, until that you should implement an option in the General settings to remember the last used view OR to set which should open as default.
