### ISSUE TITLE
Not searching Address in Bolzano -  Bozen

### ISSUE THREAD

**Issue by EugeneZmeuk** [osmandapp/OsmAnd#14198]
### Description

Not searching Address in Bolzano

### How to reproduce?

Start to find:  
**1. Bolzano, Piazza Walther** - This search doesn't find the needed place (Address in Piazza Walther)
![image](https://user-images.githubusercontent.com/44466116/166639833-1507cbfb-dd19-493e-bdd6-fc1bcff95e70.png)

**2. Piazza Walther** - This search find the needed place (the screed of device on the city of Bolzano)

![image](https://user-images.githubusercontent.com/44466116/166639896-a9c27039-eaa1-4be2-a009-e61a5809ab2b.png)
![image](https://user-images.githubusercontent.com/44466116/166639917-075b88ab-7e69-41ff-91ac-6856b2916aa4.png)
![image](https://user-images.githubusercontent.com/44466116/166639930-adec4005-7e70-46dd-8cb6-2ab0d329352c.png)

### Your Environment
OsmAnd Version: 4.1
Android/iOS version: 11
Device model: Samsung 10e

**Maps used (online or offline):**   
Italy Trentino-Alto 1 Apr 2022

**Comment by scaidermern** [comment]
The first one contains a typo? You are trying to search for Walther but you did enter Walhter instead.

**Comment by flobee** [comment]
Ja das ist in Bozen tatsächlich ein wenig schwierig gewesen wie ich aus dem letzten Jahr erinnere. Phonetisch oder Tippfehler in der Suche ist ein technisches und schwieriges Problem! Und dann kommen noch die Daten und Aktualität der OSM Karten dazu.

Kannst Du bitte beschreiben: 
- Was hast Du eingegeben?
- Was erwartest Du als Ergebnis?
- Was hat das Programm ausgegeben?
Damit die techniker das besser differenzieren können. Da würde sehr viel helfen das Problem in die richtige Richtung deuten zu können!


---

Yes this has actually been a little difficult in Bolzano as I remember from last year. Phonetic or typing errors in the search is a technical and difficult problem! And then there are the data and timeliness of OSM maps.

Can you please describe: 
- What did you enter?
- What do you expect as a result?
- What did the program output?
So that the technicians can better differentiate. It would help a lot to be able to interpret the problem in the right direction!


Translated with www.DeepL.com/Translator (free version)

**Comment by vshcherb** [comment]
Duplicate https://github.com/osmandapp/OsmAnd/issues/5409
