### ISSUE TITLE
Coastline drawn by artifacts around the Ministry of Business in the Azores with a zoom of 1 km (14) or more

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd#14208]
### Description
When increased to 1 km (14) the coastline breaks down 

### How to reproduce?
Follow the link and scale the map
[http://osmand.net/go.html?lat=16.88981&lon=-24.99167&z=14](url)

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/166910505-d5c90277-807e-4aab-9f22-eb5efcb6fac8.jpeg"  width="300" height="auto"/> </th>
 <th><img src="https://user-images.githubusercontent.com/104760013/166907986-6f4be9ba-28a5-49f7-926f-884200ab41cf.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table> 

### Your Environment
OsmAnd Version: 4.1.11
Android/iOS version: MIUI GLOBAL 12.5.5 Android 11
Device model: POCO X3

**Maps used (online or offline):**   
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.

**Comment by xmd5a2** [comment]
This is because of line 74 https://github.com/osmandapp/OsmAnd-resources/blob/master/obf_creation/rendering_types.xml#L74
This line was introduced to fix names of `place=island` but it causes such glitches when coastline of island is in basemap.
It is needed to increase order of `natural=coastline` in data https://github.com/osmandapp/OsmAnd-resources/blob/master/obf_creation/rendering_types.xml#L5125 to at least 51 to be before `place=island` but for some reason island names is not rendered at all.

**Comment by ivanPyrohivskyi** [comment]
Tags of https://www.openstreetmap.org/way/9884465 :
place island
natural coastline

<entity_convert pattern="tag_transform" from_tag="natural" from_value="coastline" if_tag1="place" if_value1="island"/>
https://github.com/osmandapp/OsmAnd-resources/blob/355a84d97349f4f6ce7854351bb5baccab4c3814/obf_creation/rendering_types.xml#L74

**Comment by vshcherb** [comment]
Caused by fix https://github.com/osmandapp/OsmAnd/issues/12937

**Comment by vshcherb** [comment]
New basemap should be available this week.

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14127mqta, released: 2023-01-25
Done
