### ISSUE TITLE
Informations missing when editing POI

### ISSUE THREAD

**Issue by tla-dev** [osmandapp/Osmand#1439]
when editing POI info, some info (like website and phone) are absent

![Image POI info](http://thibautmariel.free.fr/Screenshot_2015-07-05-15-28-18.png)

![Image POI info](http://thibautmariel.free.fr/Screenshot_2015-07-05-15-28-25.png)

i'm using the last nightly build

**Comment by vshcherb** [comment]
This is not a critical issue, because osm tags will be presumed when you edit them. So in case you want to keep website/phone, you just keep them blank. Most of the tags are not present in POI offline editing, so this issue is applicable to all tags in advanced mode.

**Comment by Barrocas** [comment]
It would be usefull to have all available tags displayed for editing, so if it was necessary to just correct a typo error, or mod the info, it was easier.

Also, please check the night builds, because when the option to 'modify poi' is selected, the values for 'name' and 'poi type' are not displayed in the Advanced tab, and the 'poi type' doesn't even show up in the Basic tab.

One more thing:
In 'modify poi' or 'add poi', when inserting the 'name' with the phone placed in landscape mode, there used to be a button to click 'next' that is now replaced by a 'send', but this is not good, since we need to first insert a 'poi type' to be able to send.
The 'send' button is great in the 'poi type' field, but the 'name' field should maintain the 'next' button.

**Comment by GaidamakUA** [comment]
I believe we have fixed this with new edit POI UI.
