### ISSUE TITLE
Constant notification push to smartwatch

### ISSUE THREAD

**Issue by einard85** [osmandapp/OsmAnd#14410]
Using a Garmin Venu 2S. Osmand pushes a message to the watch with every update on the map it seems. 

When driving it is pretty mush constantly vibrating. Couldn't find a way to disable this.

![20220528_102820](https://user-images.githubusercontent.com/64213213/170822237-40ad4c78-ec48-4e46-9b95-7dd1a6c2e609.jpg)

**Comment by vshcherb** [comment]
Duplicate https://github.com/osmandapp/OsmAnd/issues/14406

**Comment by tylla** [comment]
Actually this is not  duplicate of #14406, rather this is the issue that describes properly the problem, while #14406 is about a different problem which has been addressed meanwhile, but that thread has been hijacked to solve this problem. 
Either reopen this, or change the description of the other issue to properly reflect the real problem. 
Btw. I have the same problem, Osmand's notifications are mostly unusable for me, because it is constantly bugging my smartwatch, which is really-really annoying. And dangerous as well because it makes you constantly check your watch to see what happened.
OsmAnd 4.2.7 / Android 9 / Sony Xperia X Compact / Pebble Time Steel

**Comment by sonora** [comment]
@tylla You are reporting for v4.2.7. You need to update your version of  OsmAnd, the likely fix is included in v4.3.10.

**Comment by einard85** [comment]
@vshcherb I didnt notice you noted is as duplicate earlier (missed that e-mail) 

I don't think this is a dupliacte issue.  Let me clarify the issue slightly. 

I have a garming watch, it reads notifcations of the phone, OSM pushes a notifcation every second or something - causing the watch to vibrate constantly. 

I don't have an option to change polling or notifcation in interval. This makes the App completely unusable for me. Imagine driving and getting a vibration pretty much every second for the entire journey.

**Comment by vshcherb** [comment]
Yes it's a duplicate issue and yes the problem still goes on, I can reproduce but there is no known yet fix available. Unfortunately I don't know anyway to update notification (which we need to do on the phone) so it's not triggered as a new notification on the watches, so it looks like we can't get it solved (or of course don't update notification on the phone itself which is ugly solution)

**Comment by sonora** [comment]
@vshcherb Apologies for repeating myself, and I have so far refrained from providing a PR because I have no hardware to test it with. But here's my point: In our method `refreshNotification()` https://github.com/osmandapp/OsmAnd/blob/44d2e7964b4912b1a4be513db437064ce68a8737/OsmAnd/src/net/osmand/plus/notifications/OsmandNotification.java#L143-L144 when you trace the code it appears to me that we **re-create** the notification for any update,?

Rather than having a loop to **update the existing notification**, following the guidance provided here https://stuff.mit.edu/afs/sipb/project/android/docs/training/notify-user/managing.html and here https://stackoverflow.com/questions/6406730/updating-an-ongoing-notification-quietly?

**Comment by vshcherb** [comment]
You are probably right but there is an ID to track that, we have an other open issue to test that idea that's why I don't immediately believe it works but anyway worth to try (planned next week)

```int notifyID = 1;```

**Comment by tylla** [comment]
@vshcherb In my understanding these are two separate, but maybe connected issues. 
But I do not want to enter into any dispute about the exact nature of the issue, especially if this would mean that it would waste anyone's time. Not to mention that I have infinitesimally small knowledge of the inner workings of OsmAnd code.
Anyway I am really happy to see that there is some progress!
@sonora Will try to update and check it. Will report back.

**Comment by vshcherb** [comment]
Its a duplicate of this bug https://github.com/osmandapp/OsmAnd/issues/16310

**Comment by sTiKyt** [comment]
Guys you know this still is an issue, right? Why is this closed?
