### ISSUE TITLE
Raster download crashes with ign proxy

### ISSUE THREAD

**Issue by ouioui7538** [osmandapp/OsmAnd#14534]
### Description
Previously, download raster tiles from ign was working nicely. Now it crashes after a couple hundreds tiles downloaded.

### How to reproduce?
Create an online raster source with https://proxy-ign.openstreetmap.fr/94GjiyqD/bdortho/{0}/{1}/{2}.jpg
Then selecting this source as the map type. Then long press on the map, action, download map.

### Your Environment
OsmAnd Version: 4.2.1
Android/iOS version: iOS 15.4.1 and 15.5
Device model: iPad 5th and iphone 13 pro

**Comment by Zirochkabila** [comment]
Your case was tested with OsmAnd app version 4.2.2 - it could not be reproduced
Please check the link you attached. Maybe the problem is in it

**Comment by ouioui7538** [comment]
Thanks for taking the time to test. Unfortunately, all downloads from links to french ign servers will stall after a couple hundreds of tiles, even when scrolling through the map.

**Comment by vshcherb** [comment]
We're preparing the fix for OpenGL when downloads actually stall, it's another issue being fixed. As you've tested on iOS we probably will release next week the fix https://github.com/osmandapp/OsmAnd/commit/85e52d615ca7076c1708068c83f42fdb7a98eeec#diff-55277816516329a31d6360cbd669ad455130dc45be4b5886faa203695e055671R35

**Comment by ouioui7538** [comment]
Thanks, will have a look then !
