### ISSUE TITLE
maxspeed:motorcar should override maxspeed

### ISSUE THREAD

**Issue by Vascom** [osmandapp/OsmAnd#14822]
### Description
A few month ago for some toll roads was added additional `maxspeed` tags to follow truth on the ground rule. For example:
added
```
maxspeed:motorcar=110
maxspeed:goods=110
```
and maxspeed changed from 110 to `maxspeed=RU:rural` (90 kmph).

Now Osmand always use only `maxspeed=RU:rural` tag so it produce wrong speed limit alerts and can wrongly calculate routes.

This roads has speed limit sign 110 with clarifying plate "for cars and trucks less than 3.5t". So tags looks correct but Osmand can't understand them.

Example roads:
https://www.openstreetmap.org/way/1068479200#map=18/55.62498/37.17539
https://www.openstreetmap.org/way/184324542#map=15/53.6438/38.0653

### How to reproduce?
Always

### Your Environment
OsmAnd Version: 4.2.6
Android/iOS version: 12
Device model: Xiaomi Mi 9

**Maps used (online or offline):**   
Issue for all recent offline maps and must be for online maps too.

Please make Osmand to correct handle this situation.

**Comment by literannn** [comment]
support this issue. It's applicable for many freeways in Russia - M4 "Don" for example.

Tag maxspeed:motorcar is used more than 4000 times worldwide: https://taginfo.openstreetmap.org/keys/maxspeed%3Amotorcar

**Comment by vshcherb** [comment]
As I understand the request is following ```maxspeed:motorcar should override maxspeed``` for cars. I would say situation here is very confusing and it's totally not clear what's default speed. As I see default speed maxspeed = 90 kmh but for cars it's 110 kmh. Then who is going to use default maxspeed, I think it's rather exceptional that cars on motorway can drive faster than default maxspeed.

**Comment by vshcherb** [comment]
That's very exceptional as I see, that's why I marked it Nice to have. Moreover it's not clear why without specific setting we should display "motorcar" settings when for "truck" / "motorcycle" we have profiles but car is very generic.

I would say it should be default 110 or conditional ... 
![Screen Shot 2022-07-11 at 14 42 39](https://user-images.githubusercontent.com/1042025/178266810-c28b29ce-86c5-4009-929f-25317d2835c0.png)

**Comment by literannn** [comment]
In this issue we talk about this sign combination: https://yandex.ru/maps/-/CCUNNZFPPA

not about electronic road signd

**Comment by ZinaidaZ** [comment]
> 

Hi there!

Actually, we are talking about another signs combination:
![Снимок экрана 2022-07-11 в 18 06 12](https://user-images.githubusercontent.com/109091750/178295931-f8454f26-535b-4383-a014-bea83f2d8e3d.png)

These signs represent that mentioned speed limit relates to motorcars and lgv only. And default speed limit is RU:rural, which is applicable for all other vehicle types.

**Comment by ZinaidaZ** [comment]
Also this signs combination quite frequently appears on many major roads (highway=motorway/highway=trunk)

**Comment by vshcherb** [comment]
I could agree that community decides it's a better way to tag and to describe ToG. Though "maxspeed" tag means default tag and it's used by applications not by Human! So it means by default we should use "maxspeed" and only if specific vehicle specified we should switch to "maxspeed:<specific_tag>". 

Even though I would say we already support similar behavior to "oneway:<>" - https://github.com/osmandapp/OsmAnd-resources/blob/master/routing/routing.xml#L630.  So that's probably an argument to support here as well. However it might be not that easy here as in routing.

**Comment by Vascom** [comment]
> I could agree that community decides it's a better way to tag and to describe ToG. Though "maxspeed" tag means default tag and it's used by applications not by Human! So it means by default we should use "maxspeed" and only if specific vehicle specified we should switch to "maxspeed:<specific_tag>".

Yes, this is what we are talking about. The `maxspeed` tag remains, but if there is a `maxspeed:<specific_tag>` then use it.

**Comment by alexey-zakharenkov** [comment]
@vshcherb I think different interpretations of what is "default" are used in this discussion. Everything falls into place as soon as we don't consider motorcar (aka "passenger car") a default vehicle type. Motorcar is means of transport like motocycle or bus, not worse and not better. OsmAnd processes maxspeed:hgv, so what's the reason not to process maxpeed:motorcar?

**Comment by vshcherb** [comment]
No ```maxspeed:hgv``` is not supported in the widget either, so it's need to be implemented first

**Comment by vshcherb** [comment]
The changes are in place
```
<select value="$maxspeed:motorcar" t="maxspeed:motorcar"/>
			<select value="$maxspeed:practical" t="maxspeed:practical"/>
			<select value="$maxspeed:advisory" t="maxspeed:advisory"/>
			<select value="$maxspeed" t="maxspeed"/>
```

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14217mqta, released: 2023-03-04
4.4.6.2

Limit 110, but displayed 90 https://www.openstreetmap.org/way/184324542#map=16/53.6405/38.0708

<details><summary>Limit 110</summary>
<img width="240" alt="Screenshot 2023-01-31 at 11 19 41" src="https://user-images.githubusercontent.com/104760013/222955011-5d568d3c-51d3-4446-ab6e-f579a5786247.jpeg">
<img width="400" alt="Screenshot 2023-01-31 at 11 19 41" src="https://user-images.githubusercontent.com/104760013/222955015-e21b75b0-8472-40ff-ab67-2d6f44faa3eb.jpeg">
</details>

**Comment by literannn** [comment]
OsmAnd~ 4.5.0#35815m, 2023-04-19 Android 13

nothing changed: on the road where we have tags:
```
maxspeed:motorcar=110
maxspeed=RU:rural
```
https://www.openstreetmap.org/way/249455819

OsmAnd shows 90 restriction on "Автомобиль" profile.

Please add support of maxspeed:motorcar tag

**Comment by Zirochkabila** [comment]
@literannn is it related to https://github.com/osmandapp/OsmAnd/issues/17017?

**Comment by literannn** [comment]
Do we have any chance to solve this issue?

No possibility to use OsmAnd for navigation on main russian toll highways cause every 3-5 minutes I get fake "you exceeding the speed limit" warning

**Comment by vshcherb** [comment]
The issue was fixed in 4.4, so it's already 4.5 is out though we reopened but it deserves a new issue. We regularly release betas so it's worth to test once issue is closed

**Comment by literannn** [comment]
Night version 4.6.0#565m от 05.08.2023, fresh Moscow region maps (01.08.2023)

https://www.openstreetmap.org/way/1067603700

maxspeed:goods=110
maxspeed:motorcar=110
maxspeed=RU:rural

navigator says: "Speed limit 90" :(((

![photo_2023-08-06_14-54-01](https://github.com/osmandapp/OsmAnd/assets/46343992/f54f091d-519e-448b-9534-768d0664125a)

**Comment by xmd5a2** [comment]
Routing data for https://www.openstreetmap.org/way/184324542#map=15/53.6438/38.0653
`
	Encoding rules 33 (0 KB): {osmand_ele_desc=7, maxspeed=4, osmand_ele_asc=3, surface=1, osmand_highway_integrity_brouting=1, motorroad=1, toll=1, oneway=1, osmand_ele_end=1, int_ref=1, ref=1, road_ref_1=1, lit=1, osmand_ele_decline_1=1, name=1, lanes=1, route_road_1_ref=1, osmand_ele_decline_3=1, osmand_ele_start=1, highway=1, osmand_ele_decline_7=1}
Road 11796770697 osmid 184324542 highway='trunk' lanes='2' lit='no' maxspeed:goods='110' maxspeed:motorcar='110' maxspeed:practical='110' motorroad='yes' oneway='yes' surface='asphalt' toll:designated='yes' osmand_ele_start='247' osmand_ele_end='215' osmand_highway_integrity_brouting='0' maxspeed='90' int_ref="E 115" name="«Дон»" ref="М-4" road_ref_1="М-4" route_road_1_ref="М-4"
`

**Comment by literannn** [comment]
@xmd5a2 and what it means ("maxspeed=4")?

**Comment by xmd5a2** [comment]
> @xmd5a2 and what it means ("maxspeed=4")?

Number of tags in the entire map

**Comment by Dima-1** [comment]
[Way: «Дон» (184324542)](https://www.openstreetmap.org/way/184324542#map=13/53.6439/38.1067)
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/31807095/480b4b5a-9c24-48eb-9b16-413b5dd2341f"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by ivanPyrohivskyi** [comment]
Also need porting code to C++ (core-legacy) and iOS

**Comment by ivanPyrohivskyi** [comment]
Also need porting code to C++ (core-legacy) and iOS

**Comment by yuriiurshuliak** [comment]
The bug has been resolved, we've conducted testing on the three problematic routes mentioned earlier. When simulating navigation along these routes at a speed limit of 110 kilometers, the Alert widget now correctly displays a speed limit of 110 kilometers instead of the previous 90 kilometers.

Check out the tested routes by following these links:

[Route 1](https://www.openstreetmap.org/way/184324542#map=13/53.6411/38.1105)
[Route 2](https://www.openstreetmap.org/way/1067603700#map=16/55.6925/37.2828)
[Route 3](https://www.openstreetmap.org/way/1067603700#map=14/55.6934/37.2994)

OsmAnd~ 4.6.0#818m, released: 2023-09-29


<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/ccf3ee5d-da40-4603-aad3-036e9cc70450"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/0dec94af-a910-4753-8426-7082d254a118"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/85a39c4e-5526-494d-b8a9-ef8573859f21"  width="300" height="auto"/> </th>
  </tr>
</table>
