### ISSUE TITLE
Consider x:conditional tags when routing

### ISSUE THREAD

**Issue by 32Vache** [osmandapp/OsmAnd#14908]
# 🚀 feature request

Routing should be able to consider conditional tags like `motor_vehicle:conditional` when routing.

Example here the street is closed Tuesday and Friday 6:30 to 14:00, but when routing through Friday on 12:00, osmand still goes into the street

![IMG_20220722_120540.jpg](https://user-images.githubusercontent.com/42336759/180417603-f18c8c0c-ed2e-4dc0-bc02-a3500008c57e.jpg)

![IMG_20220722_120702.jpg](https://user-images.githubusercontent.com/42336759/180417632-bcc79998-eb16-41eb-9c0b-3b450459d3b0.jpg)

**Comment by scaidermern** [comment]
OsmAnd already recognizes this tag. I'm wondering if the value has a syntax problem. Shouldn't the time be enclosed by parenthesis, i.e. `no @ (Tu,Fr 06:30-14:00)` instead of `no @ Tu,Fr 06:30-14:00`? Not sure if this could be the problem.

Also please include a link to the map or the OSM object in question. This helps a lot.

**Comment by Dima-1** [comment]
https://www.openstreetmap.org/way/865635309
