### ISSUE TITLE
Routing Bug 

### ISSUE THREAD

**Issue by Norbert80** [osmandapp/Osmand#1501]
https://groups.google.com/forum/#!topic/osmand/XJ-HVOHhKEM

Works with other OSM routing algorithms:
http://www.openstreetmap.org/directions?engine=osrm_car&route=40.53177%2C-80.01080%3B40.52917%2C-79.99938#map=17/40.53049/-80.00500

@vshcherb one more routing bug that needs investigation.

**Comment by stephan75** [comment]
Maybe in this case a maxspeed tag is missing on a link way?

BUT: Osmand should have a bigger penalty on link ways, I suppose.

**Comment by rickmastfan67** [comment]
The reason is has 'NO' maxspeed tag is because it doesn't have a speed limit posted.  995/1000 slip lanes like this in the USA do NOT have a speed limit posted, and if they do, it's an 'advisory' warning (like this: https://goo.gl/maps/77miK).

And yes, I'm VERY familiar with adding maxspeed tags in OSM.  I'm a power editor.  Almost 99% of the road edits you see in that area are of my doing, including all the speed limits on the roads there.

Anyways, shouldn't the U-Turn penalty have outweighed the short 'no speed' _link way in the first place?  I would have put a 'NO U-Turn' restriction there, but there are no signs posted in the field for it unlike on the other side of the intersection on Siebert Road where the road is wider (more lanes) and has no center divider.  My local township and PennDOT will post the 'NO U-Turn" signs where it's illegal.  Still, the drivers should have common sense not to do it there since the turn lanes are usually backed up during the day.

-James

**Comment by vshcherb** [comment]
This doesn't look much like a bug, conceptually it tries to avoid traffic signals.  And if by that manoeuvre you can avoid 1 traffic signal, then it is even shorter route. I don't know how it looks, but I suspect by making U-turn, you can't avoid traffic signals, so it is a map data related issue.

**Comment by rickmastfan67** [comment]
However, shouldn't the 'sharp' U-Turn there have a much higher penalty than the 'false' extra traffic light?  Especially when Siebert Road is posted @ 25mph there, and McKnight Road is posted @ 40mph (both properly tagged).  I don't want to add in a 'false' NO U-Turn relation to the database there to do the routing engine's job when both OSMR and MapQuest Open both route thru that intersection correctly and have somebody call me out for 'mapping for the router'.  This does indicate there is something wrong in the OSMAnd routing engine, and not the map data to me.

Honestly, there should be a way for OSMAnd to know when traffic lights are 'linked' together as part of one entire intersection, especially for divided roads like this.  Maybe when another light is less than 75 feet from another, OSMAnd doesn't add an extra penalty, thus get the 'correct' route?  This would solve a ton of problems IMO.

I mean, look at the 3rd image in #1468.  This is almost exactly the same problem, expect you flip the slip lane and U-Turn.  It also provides a 'dumb' route to just avoid one traffic light node.  I think @Goodingn would agree with me on this.

**Comment by vshcherb** [comment]
Technically this is not U-Turn, cause it goes to another OSM way. U-Turn when you get back to the same road, because most of the roads are drawn as 2 ways, that's why U-Turn is just a turn on the different street. 

There is no penalty based on the sharpeness of the turn, cause there is no clear algorithm to say how much sharp turn is and what is the penalty. 

Related to OSM, if it is allowed to make such a turn, you should not change OSM definitely, otherwise you better change. Related to that question is about traffic lights, yes, there is an issue where it could be smarter about traffic lights, but in that case it is mapped in such a way, that you can avoid traffic light, that might be incorrect mapping.

**Comment by jojo4u** [comment]
Traffic signals detail mapping is still lacking in OSM. This intersection can be improved by moving the traffic signals from the intersection to the individual oneways like here: http://wiki.openstreetmap.org/wiki/File:Traffic_signals_example_4.png

**Comment by jojo4u** [comment]
I moved the traffic signals. With this style no double traffic signals are encountered Also I suggest to add an no_u_turn restriction with 
from: https://www.openstreetmap.org/way/66446499
via: https://www.openstreetmap.org/node/703035303
to: https://www.openstreetmap.org/way/56007381
