### ISSUE TITLE
Routed in a Circle Instead of a Right Turn

### ISSUE THREAD

**Issue by Norbert80** [osmandapp/Osmand#1502]
https://groups.google.com/forum/#!topic/osmand/s64X6oQZCWs

@vshcherb one more routing bug that needs investigation.

**Comment by vshcherb** [comment]
It is another issue, it is critical but has a very simple workaround and reproducible in very few places. 
The issue somehow is related to the first road, which doesn't allow by unclear reason turn right. If you select point further on the street (make route longer by moving start point) the issue is not appearing. I guess experiment on the data by splitting the way into 2 ways will help, but then we will not be able to reproduce the issue and fix it ( so please don't change the map, only if temporary)

**Comment by vshcherb** [comment]
More information: looks like the first turn is always skipped (if there is no nodes before this turn, basically if the turn on the first node after closest point)! It should be easily reproducible in many places, however didn't see it yet.

**Comment by vshcherb** [comment]
Start: 32.95486, -117.23116
End: 32.9506, -117.2291
OpenStreetMap link: http://www.openstreetmap.org/directions?engine=osrm_car&route=32.95486%2C-117.23116%3B32.95060%2C-117.22910#map=18/32.95308/-117.23008&layers=N

**Comment by vshcherb** [comment]
Not reproducible any more
