### ISSUE TITLE
OpenGL: With OSM-carto, Park operators are too intrusive

### ISSUE THREAD

**Issue by michaelblyons** [osmandapp/OsmAnd#15166]
### Description

The OpenGL version is newly available to me. (Thanks F-Droid maintainers!) It looks great. It loads fast.

But my primary map style is [OSM-carto][1] which on OGL (but not before?) shows the `operator` tag for parks. Since my local area has a number of parks, the viewing area is really crowded with text for them.

### How to reproduce?

- Change map style to OSM-carto.
- Find (or add tags to!) a nearby park to add its operator.
- See lots of text and irregular line spacing.

### Your Environment

OsmAnd Version: OsmAnd~ 4.2.7
Android/iOS version: 12
Device model: Pixel

[1]: https://github.com/osmandapp/OsmAnd-resources/blob/master/rendering_styles/osm-carto.render.xml

**Comment by scaidermern** [comment]
Also happens with OsmAnd 4.2.7 from the PlayStore and the default "OsmAnd" map style:

51.03617,13.73045
![photo_2022-08-29_09-24-10](https://user-images.githubusercontent.com/1040784/187146496-668854c3-f6aa-41d1-96bd-5cb37840ca03.jpg)

https://www.openstreetmap.org/way/188913420
https://www.openstreetmap.org/way/41986868

"Studentenwerk Dresden" is the operator, "Zugang nur für Mieter und Mitarbeiter des Studentenwerks" is a note tag (see #14950).

I'm wondering if this has already been fixed with #14950.

**Comment by michaelblyons** [comment]
Looks like that issue, yes. Sorry I did not find it when searching for "operator."

I also thought I had tried main OsmAnd style without the issue, but I tried it just now and it's definitely there. 🙂
