### ISSUE TITLE
Complex router routes me the wrong way on cycle paths with cycleway=opposite_lane

### ISSUE THREAD

**Issue by jean-de-grenoble** [osmandapp/Osmand#1520]
Using the complex router, I get routed in the wrong direction on roads with cycleway=opposite_lane. Here's an example: From: 45.18990N,5.74212E To: 45.18786N,5.71917W. If I disable complex routing, I don't have this problem.

**Comment by Zahnstocher** [comment]
You are talking about bicycle routing (your route starts and ends on a way which allows only foot and bicycle)?
But cycleway=opposite_lane allows to drive (bicycle only) in both directions (no oneway for bicycles).
How could OsmAnd route you in the wrong direction then?
I guess you are talking about these ways (they are part of the OsmAnd route and have cycleway=opposite_lane):
https://www.openstreetmap.org/way/4262554
https://www.openstreetmap.org/way/4262459
https://www.openstreetmap.org/way/321330764
https://www.openstreetmap.org/way/37855006
https://www.openstreetmap.org/way/37855007

Please could you explain exactly where the problem is?

**Comment by vshcherb** [comment]
I also didn't understand the problem..
