### ISSUE TITLE
OSM editing: OsmAnd (still) loses modifications on upload

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/OsmAnd#15207]
This is either a regression of [#9093](https://github.com/osmandapp/OsmAnd/issues/9093#issuecomment-960482918) or the original fix wasn't correct.

Steps to reproduce:
- edit a POI, add a tag ("tag1"), save _without upload_
- edit the POI again (the original POI, not the existing edit)
- previous tag changes _are visible_ in the advanced tab
- add another tag ("tag2")
- upload
- only the new tag "tag2" will get uploaded, the tag "tag1" from the first edit is not uploaded although it has been visible in the advanced tab

OsmAnd 4.2.7

**Comment by Zirochkabila** [comment]
As you can see from the link, both tags were loaded into the OSM https://www.openstreetmap.org/node/9995036208#map=16/49.7174/28.5709

Make sure you set a value for the tag
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/188165024-b475375a-f54a-4a4a-bbf9-68abb8c7a95e.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by scaidermern** [comment]
> Make sure you set a value for the tag

Sure, I'm editing OSM for more than ten years now :)

Still, for me the bug exists nevertheless.

**Comment by Zirochkabila** [comment]
You can see my steps in the video

https://user-images.githubusercontent.com/104760013/188170449-c817aed1-6308-410c-b7bc-8de67e85aec6.mp4

**Comment by scaidermern** [comment]
See this video please:

https://drive.google.com/file/d/1MCZJPxdlCFzXuqW4H94EwbdrCe87Ru-C/view?usp=drivesdk

https://www.openstreetmap.org/node/2304076827

I edit the POI and add the tag "payment:girocard=no" and save.

Then I edit the original POI again and add "diet:vegan=yes" and "diet:vegetarian=yes". The previous "payment:girocard=no" is visible right above these new tags. Then I save.

Then I check the tags of this edited POI in OsmAnd. All three newly added tags are still showing. Then I upload.

Then I open the node on OSM and the "payment:girocard=no" tag from the first edit is suddenly missing.

**Comment by scaidermern** [comment]
> You can see my steps in the video
> telegram-cloud-document-2-5229175850280165440.mp4

Sorry but these aren't the steps I explained.

Don't open your edit a second time. Instead edit the original POI again. OsmAnd will then show the previously added tags but it won't upload them.

**Comment by Zirochkabila** [comment]
OsmAnd 4.2.7, OsmAnd~ 4.3.0#13753mqta, released: 2022-09-05 - reproduced

**Comment by OsmMUC** [comment]
> Don't open your edit a second time. Instead edit the original POI again.

Just wondering: Does it matter (by design or otherwise) whether one opens the original or the previously edited POI when one wants to do further editing?

In any case, I typically opened the already modified POI (not the original one) for further editing (seemed more intuitive to me), and am also seeing tags getting lost.

I don't recall what happens in case of simply changing a tags content, vs. adding additional ones.

Also, I have seen the issue mentioned in [https://github.com/osmandapp/OsmAnd/issues/9093#issuecomment-997233407](https://github.com/osmandapp/OsmAnd/issues/9093#issuecomment-997233407), i.e. that moving an edited POI ends up in no modification being uploaded at all, i.e. neither any added tags nor the position change.

Last seen with OsmAnd+ 4.2.7, but I noticed this quite a while back already. Since the issue persisted for so long, and I never saw an issue raised for it (I missed #9093), I kind of figured it was an issue on my end only, and from then on just refrained from doing further edits to previously edited but not-yet-uploaded POIs, or changing a POI's position.

So thanks for (re-)raising this, @scaidermern ;-)
