### ISSUE TITLE
Regression - map change an orientation and day/night state event when Start button is not pushed

### ISSUE THREAD

**Issue by thuryn** [osmandapp/OsmAnd#15235]
### Description
It works originally well: I put the target, click on Navigate, path is calculated, but the map still points to North. When I click on Start button the map orientation changes to "in direction of the route". This behavior is perfect.
It works in different way now - I put the target, click on Navigate and the map immediatelly rotate to the direction of the route.

### How to reproduce?
Just put the target and click on navigate to - map orientation bacomes changed immediatelly.

### Your Environment
OsmAnd Version: 4.2.7
Android/iOS version: 12.1
Device model: Xiaomi Mi 9

**Maps used (online or offline):**   
offline

**Comment by sonora** [comment]
This seems because ever since a few weeks ago we change to the app profile of the selected transport **already when the route is being claculated**, not just afer starting the turn-by-turn navigation. It initially confused me, too,  I wonder if this was an intentional change or accidental?

The 'workaround' is as follows: While in the Browse map profile (which is the default), you see a blue globe icon top left on the map screen. Calculate e.g  a car route and this now immediately changes to a car icon (car profile has direction of motion, not north is up, as default.). You can tap the icon and use the selector to switch your view back to the Browse map profile. This is a bit awkward, but is what I do if I just want to follow a calculated route without turn instructions.

**Comment by vshcherb** [comment]
It's designed I think long time ago that we have navigation profiles and that direction we need to follow i.e. if you calculate the route it automatically changes profile. 

If you've configured profile you can switch back to Browse Map manually after you hide the route (swipe down).

**Comment by thuryn** [comment]
It worked before in a comfortable way so I'm sad that this is feature. Why the map is switched to night mode when I don't driving. The previous behavior had been natural.

**Comment by dmpr0** [comment]
App is switched to the first profile with navigation before taping Start so you can see how the map will look while navigation and what data will be displayed.

**Comment by vshcherb** [comment]
Map and all settings are switched to selected Route Profile before you click Start.

**Comment by ristein** [comment]
This is very annoying. I often browse the map and want to see suggested routes.
Every time I calculate a route I now have to swipe the route down and click on the profile and switch it back to standard and swipe the settings back down. Otherwise the map shows all icons are big and ugly even the magnifier is on the same level. I can't see details either, as intended when driving. But I am not driving, only checking which route I would take later in 90% of the cases I use route calculations.

Please please make this feature deacivatable

**Comment by thuryn** [comment]
I found one more bug regarding profile switching - when the routing finishes it does stay in the car profile and the destination flag stays on map. I have to click on route button and then click on Cancel to get it back. But anyway - it could be switchable feature - switch to profile when turn-by-turn routing is started or immediately.
The main point is, how people uses the software. I use it in this way - find the destinations, click on navigate by motorbike - what to stay in general profile to see the route on map (but navigation limitation shoud be applied for motorbike). The I check the route, can add some mid-points and when I'm satisfied, I click on Start and want to switch profile to motorbike one (change the screen orientation, day/night mode etc.

**Comment by vshcherb** [comment]
I think this is related to this one https://github.com/osmandapp/OsmAnd/issues/15283
