### ISSUE TITLE
Tracking?

### ISSUE THREAD

**Issue by olivier-cailloux** [osmandapp/Osmand#1526]
Hi,

The F-Droid [store](https://f-droid.org/wiki/page/net.osmand.plus) says that OsmAnd somehow tracks its users: “It will send your device and application specs to an Analytics server upon downloading the list of maps you can download.”

Is this true? What is the purpose of this functionality?

Thanks!

**Comment by jkufner** [comment]
Also there is OsMo plugin. That is proprietary service. Disabled by
default, tho.


Olivier Cailloux wrote, on 4.8.2015 11:45:

**Comment by vshcherb** [comment]
Actually it was always source of confusion, originally it was a google analytics library, which was removed in order to solve that issue. The issue was solved but the message was left. There is java call to   duplicate information sent to the server, but we don't need it, because we have that information available on the server anyway. 
So it is finally deleted ! https://github.com/osmandapp/Osmand/commit/513024eac7ceca812ddc94056fc0ac0d5d2772ec and no need in that message, because it sounds a bit offending to the software that doesn't track anything about the user.

**Comment by vshcherb** [comment]
OsMo plugin clearly has the data you sent to him, but that's a 3rd party service
