### ISSUE TITLE
switching between the compass modes

### ISSUE THREAD

**Issue by Rowin63** [osmandapp/OsmAnd#15285]
### Description
When switching from one compass mode (north, magnetic, direction) to another, one has to tap two times for each operation. At the first tap osmand always shows the notice "if you tap again, Osmand will swith from x to y mode", at the second tap Osmand switches the compass mode. I know that, so Osmand does not need to tell me this each time :-)

At no other functionality Osmands behaviour is like this.
Is this a feature or a bug ;-)

### Your Environment
OsmAnd Version: 4.2.7. (but was also before)
Android/iOS version: 12
Device model: S20+

**Comment by sonora** [comment]
This seems about this code: https://github.com/osmandapp/OsmAnd/blob/4f4d6d5d97be753ec7a8ee6780e65b058138bfef/OsmAnd/src/net/osmand/plus/base/MapViewTrackingUtilities.java#L499-L512

Looks like in navigation mode (and only then) we require two taps on the compass icon (within a certain time) to actually change the map orientation. The message is actually needed to make users aware, because the behavior outside navigation mode is just a single tap. Question is why this double tap requirement was introduced here, it is like guarding against some involuntary action which may happen rather frequently?

**Comment by vshcherb** [comment]
It's a feature cause we have issue for nonexperienced users during navigation

**Comment by Rowin63** [comment]
Sorry, but what kind of issues do "nonexperienced" users have when switching the compass? Do they also have issues when starting a download ("next tap the download will start") or changing the profile? Or at any other function?
Of course it is your decision to leave it as it is - but I really dont understand the "issue"

**Comment by sonora** [comment]
I have no really strong feeling here, and my first impulse was actually that a map orientation change during an ongoing navigation is probably not a widespread use case, so requiring a double tap can actually be considered reasonable, if it helps reducing adverse experience for novice users.

But on second thought, isn't our default behavior such that the compass icon is hidden anyway for the default map orientation of all standard navigation profiles, so that in order to accidentally touch the compass a user would already have reconfigured things to make the widget visible in the first place?

**Comment by vshcherb** [comment]
During navigation almost every user expects that Location is displayed on the bottom and ongoing route is displayed from bottom to top. We have users complaining that navigation doesn't work correctly after investigation we've realized they tapped accidentally compass and switched "map orientation mode" that's why we now require confirmation.

**Comment by sonora** [comment]
If that's our experience, I think we should leave it as is.

**Comment by Rowin63** [comment]
I do respect your experience, but I still consider the double-tap as an absolutely unnecessary action.
Switching the compass mode is Osmands one and only function that requires this.

**Comment by sonora** [comment]
My understanding is that this prevents immediate triggering of a really unusual use case  by an accidental tap. I think there is a popup text instructing you to repeat the tap should you really mean to perform that use case?

**Comment by Rowin63** [comment]
Yes, there is a popup text that tells you to repeat. My point is, I still dont see this importance to use a double-tap at this one and only function in an app with a thousand functions. And for me personally this double tap annoying, when I´m on the bike and just want to switch orientation for a short moment.

It is an old and closed issue, I know, but I just wantet to tell you my opinion, because it still concerns me again and again.
Thanks for noticing!

**Comment by Rowin63** [comment]
I´m sorry, I was in an older version. 
This double tap does not exist anymore...
Sorry!

**Comment by sonora** [comment]
Yes,you're right, I just tested and the behavior seems changed now - fine by me! 😉  I had also noted that the text popups are quite laggy somehow... I wonder if that's worth a separate issue. Possibly this is a matter of overlapping text popups being queued instead of discarded and just the latest one showing, not sure...
