### ISSUE TITLE
Navigation for pedestrians creates big detour

### ISSUE THREAD

**Issue by AxelBoldt** [osmandapp/Osmand#1529]
![screenshot_2015-08-04-18-00-59](https://cloud.githubusercontent.com/assets/8941698/9068890/69765f90-3ae6-11e5-9c48-d54d18c9a270.png)
Using the offline navigation in osmand  2.0.4. with map data Spain_europe_2.obf.zip from 21.07.2015: I want to navigate from 39.568,2.648 to 39.569,2.648 as pedestrian. This is just 200m up the road Carrer del Palau, but osmand proposes an 800m detour (see screenshot attached). Switching to car navigation will take the direct path. If I move the start and destination coordinates slightly closer together, osmand will also find the direct route even for pedestrians. 

The osmand offline pedestrian navigation seems to engage in some very wrong-headed attempt at minimizing the travel time.

**Comment by vshcherb** [comment]
I think the issue is both  in the data http://www.openstreetmap.org/way/173188624 and in the program. In  the data these streets should have additional tag foot=permissive to indicate there is no restrictions foot and in the program there is a question how to express it.

I fixed the program even for that data, but I opened a question to see if somebody will contribute and find a better solution.https://github.com/osmandapp/OsmAnd-resources/commit/a00ea38cc182dfda88671cf0d5c34c554d388394
