### ISSUE TITLE
OSMAnd does not display turn lanes at a particular intersection in Ogden, UT

### ISSUE THREAD

**Issue by kevinp2** [osmandapp/OsmAnd#15388]
### Description
I have tagged plenty of turn lanes in OSM and they all show up perfectly in OSMAnd.  Except the intersection of Washington Blvd and 12th Street in Ogden, Utah, USA.  I have made tweaks to the roads and tags, but nothing works - the turn lanes are simply not displayed.  **Perhaps someone can review the tags and see if I am missing something or if this is some kind of bug.**

### How to reproduce?

OSM way: https://www.openstreetmap.org/way/1097138027
This section of road has the actual turn lanes and I have tagged them as:

> turn:lanes=left;reverse|left||||right

But OSMAnd simply does not display the turn lanes at all. 

![image](https://user-images.githubusercontent.com/609677/193141970-4a7d29cb-42fb-4191-a907-ec6b5dee2763.png)

### Your Environment
OsmAnd Version: 4.2.4
Android/iOS version: 15.7
Device model: iPhone XR

**Maps used (online or offline):**   
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.

**Comment by pm4rcin** [comment]
Looking at other parts of intersection you didn't specify 2 turn lanes. I guess you're missing `through|through` or whatever lanes are there.

**Comment by Henry00572** [comment]
There are a few ideas I have to explain this. Maybe you can check them against the other edits you've made to see if they're plausible explanations.

- The OSM data you are using hasn't updated yet.
- OSMAnd doesn't understand the `left;reverse` turn. Personally I would write it as `reverse;left` because reverse is even more to the left, but this might not make a difference at all.
- The way https://www.openstreetmap.org/way/1097138026 which is actually the one right before the turning point https://www.openstreetmap.org/node/10049973838 doesn't have `turn:lanes`. Maybe only those values are considered.

- The implicit `none` by having no value between the `|`s shouldn't be a problem as it is documented in the wiki and not unique to this particular junction.

**Comment by vshcherb** [comment]
It's important to have tags as well on https://www.openstreetmap.org/way/1097138026, otherwise they are ignored and considered related to intersection.

**Comment by vshcherb** [comment]
But https://www.openstreetmap.org/way/1097138026 is too long, so it needs to be split and each segment should have own traffic:lanes
