### ISSUE TITLE
Trip Recording with coordinates "snapped" to the road

### ISSUE THREAD

**Issue by ShelleyLake** [osmandapp/OsmAnd#15443]
Dear OsmAnd Team,
I have a special request regarding the recording of GPX tracks with the "Trip recording" plugin.

I would like to ask you if it would be possible to add an option so that Osmand **does not** record the real coordinates (latitude and longitude) provided by the satellite, but **rather** the coordinates "sticked" to the road being traveled, based on the chosen profile.

This option would obviously only work if the navigation with OsmAnd was started.

The position of the arrow on the screen, during navigation, is in fact glued to the road, even if the gps data is not 100% the same as the road map.

This would be useful in my opinion to eliminate approximate data and have more homogeneous tracks when traveling the same road several times.
The other data, such as altitude, could remain the actual data provided by the gps.

(Both iOS and Android would be nice)

**Comment by vshcherb** [comment]
Yes that would of course interesting actually...

**Comment by ShelleyLake** [comment]
In order not to interfere with the normal behavior of OsmAnd, with the possibility therefore of creating problems, could this information be inserted for example as an extra tag within extensions?
```
        <extensions>
          <osmand:trkpt lat="39.5469598" lon="2.7310116" />
        </extensions>
```

**Comment by ShelleyLake** [comment]
Again and again moved to indefinite release. Nice treatment for a paying customer.

**Comment by vshcherb** [comment]
We think it creates too much problems in UI and it's better to use snap to road functionality for recorded tracks or to create a fresh track by plan route.

**Comment by ShelleyLake** [comment]
@vshcherb in this case I am closing the request because your answer does not leave hope to get this done in the next 10 years.

**Comment by sonora** [comment]
@ShelleyLake IMHO, your reaction seems exaggerated, because on one hand @vshcherb is right that this is a niche request and carries some risk for the vast majority of app users. And on the other hand there is the functionality to snap any recorded  track to the roads, with any profile you want to, save it again, and thus create precisely the result you are looking for.

**Comment by ShelleyLake** [comment]
@sonora
If the snap to road functionality were as foolproof as you advertise, I would not have made this request.
Unfortunately, one of the limitations is that your infallible feature removes timestamps and altitude from points (there is another request to keep them and or interpolate them) and also makes up absurd routes in case the road restrictions on the map don't match the actual road restrictions (e.g. I drive a cab and can drive where cars are not normally allowed).

I don't understand the problem: the software knows the real position and the "anchored" position on the map (in fact, the position is never "offroad", it is always on a road or another): what is the problem with adding this information as additional data in the registered gpx?

My reaction is due to the fact that I made a request, for a paid product, that has been moved from release to release for months. In short, it seems like a joke.

**Comment by sonora** [comment]
Thank you for responding again and explaining these points! I had in fact neither been aware of your particular use case, nor had I made the connection to your other reqeust #14034, and had also in a sense lost track of any remaining issues there may still be around the functionalities "Attach to the roads" and "Track approximation" for recorded gpx files. 

The blame for at least the latter 2 of the 3 points is entirely on me, and I offer my apologies.

In particular since, going back through our Issue  history, I discover that last year I myself had opened #15025 about the difference between and the weaknesses of the new "Atttach2roads" and "Track approximation" functionalities. I recall that the first uses a routing algorithm, which may in deed result in funny detours around road gaps, while the second uses a closest roadway approach, and sounds in line with what you suggest, only that it is not applied at recording time but later. Had you tried that? Is it useless because of what may be a bug, (and could/should be fixed), or is it not the functionality you have in mind?
