### ISSUE TITLE
Bug in colouring of activated vs deactivated maps

### ISSUE THREAD

**Issue by pebogufi** [osmandapp/OsmAnd#15478]
### Description
When i zoom out, normally i should see colouring of activated (green) vs deactivated (orange) maps.
In latest nightly i see a strip at left (and other borders) which is overwritten immediately.

### Your Environment
OsmAnd Version: OsmAnd~ 4.3.0#34742m, veröffentlicht: 2022-10-14
Android version: 8
Device model: samsung S7

![Screenshot_20221014-112923_OsmAnd~](https://user-images.githubusercontent.com/18628183/195815631-514af45c-a383-40d1-93fc-b293b773f7f9.jpg)

**Comment by vshcherb** [comment]
Looks weird ...

**Comment by pebogufi** [comment]
Problem raised after
OsmAnd~  4.3.0#34692m.apk 
and with
OsmAnd~  4.3.0#34721m.apk (maybe earlier)

**Comment by sonora** [comment]
https://github.com/osmandapp/OsmAnd/commit/cbfd79029524328a0c24a96c8e4ba39db73e705d ?

**Comment by ivanPyrohivskyi** [comment]
https://github.com/osmandapp/OsmAnd/pull/15584

**Comment by sonora** [comment]
So is it inevitable that we have this complication of different layer orders in OpenGL and legacy?

Just to make us aware of issues this creates:
- If I test a build which has legacy libraries only, and I have the Development plugin's "Use OpenGL rendering" set to OFF, https://github.com/osmandapp/OsmAnd/pull/15584 actually fixes this issue for me.
- But if on such a build I set the OpenGL setting to ON, which otherwise has no effect on a build without the OpenGL libraries, the issue returns(!)
- To make things worse: I just notice that for the second case all GPX tracks which are set to "visible" are not displayed, they are probably on the wrong layer (though they remain clickable), so this has a potential of creating all sorts of support nightmares... (It may have been created by switching back and forth between OpenGL and legacy builds, not sure).

Please note that there are many users and devices out there for which legacy performs enormously beter than OpenGL, I do not expect we can retire legacy any time soon... I personally even prefer non-OpenGL builds because they are more universally usable (and perform faster on many mid range outdoor devices).

**Comment by vshcherb** [comment]
I think it's inevitable cause here we have layers order which is different then symbols order. But layers order still matters in which order symbols will be preprocessed.

https://docs.osmand.net/docs/technical/algorithms/map-rendering-layers 

So non-opengl is easier to understand but less flexible and next year will be outdated.
