### ISSUE TITLE
Route and Tracks not shown if OpenGL is selected but not successfully initialized

### ISSUE THREAD

**Issue by HW-Jarausch** [osmandapp/OsmAnd#15627]
Since à few weeks, OSMAND doesn't show a computed route on the map anymore, neither just before nor during navigation. 
Navigation is working though since I get correct voice directives. 
### How to reproduce?
Every time

### Your Environment
OsmAnd~ 4.3.0#34841m, veröffentlicht: 2022-11-01
Android/iOS version:
8.1
Device model:
Samsung Galaxy S5  as well as Galaxy Tab A (2016) 

**Maps used (online or offline):**  
Belgium and Nordrhein-Westfalen (Germany) 
I don't think the issue is related to a map. 
The issue didn't exist with the development version a few weeks ago.

**Comment by sonora** [comment]
I think I had this problem under certain circumstances when enabling the OpenGL rendering engine in an OsmAnd build with no OpenGL libraries contained. Try going back to "Legacy" rendering, does that fix it?

**Comment by HW-Jarausch** [comment]
Thanks, that fixes my problem,
Helmut

Hardy ***@***.***> schrieb am Do., 3. Nov. 2022, 16:56:

**Comment by sonora** [comment]
@vshcherb Not sure if you consider this a bug worth fixing? We could potentially run a check if the OpenGL properly initializes,  and if not  reset USE_OPENGL_RENDER back to false, this would circumvent this issue.

**Comment by vshcherb** [comment]
yes it's a bug, if build doesn't contain opengl, the app should work as before

**Comment by akbarazimifar** [comment]
Hi . how to enable OPENGL ?

**Comment by sonora** [comment]
@akbarazimifar To check if you suffer from the known bug, you need to check if it is enabled by accident and need to **disable** it.

As I stated above: Prior to 2022-11-01 it was in the Development plugin's settings, now it is in the General settings.

**Comment by sonora** [comment]
@Chumva, @ceppice, @vshcherb Regarding: https://github.com/osmandapp/OsmAnd/commit/48d785fb82a7ff86fa0126286d35113653eb7577: Why hide the menu, instead of just graying it out?

Not being able to see (and positively verify) what it's currently set to will make things difficult to support in light of all the troble we have had with the setting being falsely set to V2, like #15627, #15557,  #15683, , #15613, #15374...

**Comment by sonora** [comment]
PS: From what I can see, to solve all the issues I quoted above, we need to put 
`settings.USE_OPENGL_RENDER.set(false);`
in case the OpenGL init fails, but we have this nowhere in our code?

**Comment by cepprice** [comment]
@sonora I did it in first commit. This switch be done strictly at the beginning of initialization (because of opengl/non-opengl dependent code), but app initialization is already complex enough. Thats why @alex-osm suggested to always check, whether app contains opengl libs or not, along with cheching above-mentioned setting, not to compilate initialization code

**Comment by sonora** [comment]
I have done some further testing, as follows:
- Installed an early November build which does contain the OpenGL libraries, and does unconditionlly show the renderer setting.
- As suspected, renderer is found to be set as set to Version 2 OpenGL
- Reset it to Version 1

**Now all builds (old and new) run again without crash.**

So the issue is related to a false setting of "Version 2" in setups where this has issues. I can only recommend to put `settings.USE_OPENGL_RENDER.set(false);` in case the OpenGL init fails.
