### ISSUE TITLE
Please render highway=corridor

### ISSUE THREAD

**Issue by bkil** [osmandapp/OsmAnd#15687]
As per

* https://wiki.openstreetmap.org/wiki/Tag:highway%3Dcorridor
* https://wiki.openstreetmap.org/wiki/Simple_Indoor_Tagging

Here's a related issue, but that one seems to be too big to be solvable, hence why I recommend splitting it to smaller subtasks:

* https://github.com/osmandapp/OsmAnd/issues/3559

**Comment by hakuchi** [comment]
highway=corridor is rendered on the latest version from PlayStore, but not used in routing.
The rendered corridor is visible in "browse map" and "pedestrian" mode.

For me the issue is that the corridor is not used for routing, because some time it is shorter to cross a mall to reach the other site.

**Comment by bkil** [comment]
Please ping when when it becomes available via f-droid.

**Comment by bkil** [comment]
Okay, it now works, thanks.
