### ISSUE TITLE
OSM data on builder is damaged

### ISSUE THREAD

**Issue by Zahnstocher** [osmandapp/Osmand#1568]
A user reported double rendering:
http://forum.openstreetmap.org/viewtopic.php?id=32352
http://www.cshare.de/file/23f5fc4eee2177656e63bdf2d6d2c0a4

I checked it and I can confirm that the OSM data on builder is damaged.
There is old and new data mixed.
I downloaded germany_bremen_europe.pbf from builder, extracted the area on the screenshot and checked with JOSM:
> osmconvert germany_bremen_europe.pbf -b=8.89087,53.10021,8.89566,53.10453 -o=test.osm

The big building, which was deleted and replaced by the small buildings, is still in this file, but it should not be there:
https://www.openstreetmap.org/way/205743436/history

This is one of the small buildings, which replaced the big building:
https://www.openstreetmap.org/way/363826871/history

I remember, that other areas also have this problem.

**Comment by vshcherb** [comment]
Are you checking this file http://builder.osmand.net/osmc/germany_bremen_europe/germany_bremen_europe.pbf

I checked diff file for OSM for August it contains line deleted and line added (though I'm curious now why it reports line deleted twice)
http://builder.osmand.net/osmc/germany_bremen_europe/Germany_bremen_europe_15_08_00.obf.gz

**Comment by vshcherb** [comment]
Checked again duplication is not an issue. I didn't check pbf file but I suspect (because lines where in the same transaction) there is an issue with osmconvert utility which apply patches (otherwise the issue will be also visible in obf patches but it is not visible there). It applies patches (log here http://builder.osmand.net:8080/job/MapsDaily_GenerateOsmPerCountry/lastBuild/console) the same time it generates diff.

**Comment by Zahnstocher** [comment]
> Are you checking this file http://builder.osmand.net/osmc/germany_bremen_europe/germany_bremen_europe.pbf

Yes.

By the way, the new "Live updates" announced here
https://twitter.com/osmandapp/status/627770254798811136
have a similar issue.
If a way is deleted and another way is created (in the same changeset or diff?), both ways (the deleted one and the new one) are shown.
This leads to double rendering and double routing.

**Comment by Zahnstocher** [comment]
--merge-versions (osmconvert)?

**Comment by vshcherb** [comment]
>> The OSM objects in the change file must be unique. That means, there has to be only one occurrence of every node, way or relation. Minutely and hourly change files may contain more than one version of OSM objects, therefore you will get warning messages. You can combine all versions of each object if you specify the option --merge-versions. Then, only the newest version of each object will remain in the file.

How will it help? I put that argument let's see. 

Coming back to "Live updates" it might be a different issue. Both ways should be shown (but 1 way will have different tag/value = osmand/deleted), so it will not be rendered. In the new engine (latest night build) we filter out duplicated ids, so this will not be shown. The routing should work the same way. 

So I don't see how the way in the issue is rendered twice (the data handled adding/deleting way correctly). P.S. Technically it is not possible to have the same id in the same obf file twice.

Let's take a look at specific issue.

**Comment by vshcherb** [comment]
[Need to double check]: for OsmAnd file uniqueness changes in OSC file is not required, it process them linearly

**Comment by Zahnstocher** [comment]
> How will it help? I put that argument let's see.

You are right, it will probably not help, because there is already only one version of the deleted file in the OSC in this case.
To be honest, I don't have an idea how it could be, that a deleted way remains in germany_bremen_europe.pbf after the OSC is applied which contains the deletion of this way.

**Comment by vshcherb** [comment]
Looking here at examples, http://wiki.openstreetmap.org/wiki/Osmconvert#Updating_OSM_Files, I don't see --merge-versions is applied. It says below that if you want to have unique, you should use that parameter.
On the other hand, I have no understanding why this parameter is optional then!? It is not good when you apply the change it stays in the obf. Another problem having "--merge-versions" is actually very-very slow , I do believe that parameter should be used when you combine 2-... or more osc files but not when you apply the changes. I will run several tests and will you know what is the result

**Comment by vshcherb** [comment]
Here is also examples without --merge-versions http://wiki.openstreetmap.org/wiki/Daily_update_an_OSM_XML_file

**Comment by vshcherb** [comment]
For quite a small region (30MB) it didn't finish in the reasonable time frame limit (15 minutes), so it is not a viable option for osmconvert a.pbf a.osc -o=b.pbf

**Comment by vshcherb** [comment]
The issue has found.
osmconvert was confusing with processing 1 file.
So, the command osmconvert 1.osc.gz -o=2.osc.gz, instead of outputting osc.gz or giving an error, was wrongly outputting osm.xml (not even osc!, so all delete ways were lost), strangely enough it was applying changes to pbf file itself.
On the other hand osmconvert 1.osc.gz -o=2.osc, works as expected! I changed the command and deleted all pbf files (they will be regenerated from planet file again), it will take a while, but not they issue has fixed. Tested on some updates (adding and deleting ways) in russia_vladimir.pbf already.
