### ISSUE TITLE
Rotation reset GPS search

### ISSUE THREAD

**Issue by postadelmaga** [osmandapp/Osmand#1573]
I notice that that everytime the screen rotate the satellite number is reset to 0 and the GPS connection start from scratch.
I'm not sure if this is something done on purpose ... but looks a bug to me

**Comment by xmd5a2** [comment]
Also "Audio/video notes" widget and speed disappears after rotation. Speed restores on update, but audio/video only after restart.

**Comment by vshcherb** [comment]
Audio/video notes and other widgets serious issue and requires separate thread (could you create it please).

GPS search resets on rotation and that's techinically fine, it doesn't start "cold GPS look up" again, because the chip handles it correctly. So having 2-3 rotates doesn't increase time for GPS lookup, however you see that satellites are reset. We don't use background service (which you can see in navigation) if it was not requested on purpose
