### ISSUE TITLE
Bicycle routing breaks when `cycleway=track` turns into `cycleway=shared`

### ISSUE THREAD

**Issue by haukepribnow** [osmandapp/OsmAnd#15788]
# 🐞 routing report

### Routing engine

- [x] OsmAnd's in-app offline routing
- [ ] Any online routing provider (YOURS, openrouteservice, OSRM, etc.)

### Routing Profile

Standard bicycle routing profile.

### Start and end points

- Exemplary start: [Nordstraße 2, Kreuzviertel, Innenstadtring, Münster-Mitte, Münster, Nordrhein-Westfalen, 48149, Deutschland](https://www.openstreetmap.org/way/233545415)
- Exemplary end: [Schlaunstraße 4, Buddenturm, Altstadt, Münster-Mitte, Münster, Nordrhein-Westfalen, 48143, Deutschland](https://www.openstreetmap.org/way/184291224)

### Actual and expected routes

Expected route: Go straight south.
![image](https://user-images.githubusercontent.com/811850/203099789-4fc8706f-c4db-4297-b46a-e2e182c45ac2.png)
([Link to route as calculated by Graphhopper](https://graphhopper.com/maps/?point=51.968624%2C7.622245_Nordstra%C3%9Fe+2%2C+48149+M%C3%BCnster%2C+Deutschland&point=51.965201%2C7.623374_Schlaunstra%C3%9Fe+4%2C+48143+M%C3%BCnster%2C+Deutschland&profile=bike&layer=Omniscale))

Actually proposed route by OsmAnd: Go south, then right on "Promenade", then left, down the stairs, onto the road, then left, then right.
![image](https://user-images.githubusercontent.com/811850/203100178-cd0c8a8d-d388-4323-bdcb-01fe59dff136.png)
([Link to OsmAnd's routing simulated in Graphhopper](https://graphhopper.com/maps/?point=51.968624%2C7.622245_Nordstra%C3%9Fe+2%2C+48149+M%C3%BCnster%2C+Deutschland&point=51.966784%2C7.621369&point=51.965201%2C7.623374_Schlaunstra%C3%9Fe+4%2C+48143+M%C3%BCnster%2C+Deutschland&profile=bike&layer=Omniscale))

### Is this a regression?

Unknown, not to my knowledge.

## 🌍 Your Environment

**OsmAnd Version:**

<pre><code>OsmAnd~ 4.2.6</code></pre>

**Device and Android/iOS version:**

- Samsung Galax S20 FE
- Android 12

**Maps used (online or offline):**

- [x] Offline maps offered within the OsmAnd app for download.

- [ ] Online (tile / raster) maps 

**Anything else relevant?**

I believe that OsmAnd has a higher preference to keep cyclists away from streets (even if they're "only" `highway=tertiary`) and rather sends them onto footpaths. However, in this particular situation, the town actually intended to have cyclists ride onto the street (namely via https://www.openstreetmap.org/way/1113013642, https://www.openstreetmap.org/way/220471882 and https://www.openstreetmap.org/way/4985978) - the streets have an explicit `cycleway=shared` attribute. Here's a visualization for how cyclists are supposed to ride:
![image](https://user-images.githubusercontent.com/811850/203103432-585220c4-edf9-4888-b9de-4e320e97a766.png)

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.3.0#13973mqta, released: 2022-11-25
Not Reproduced

On your second screenshot "Actually proposed route by OsmAnd" there is an intermediate point - that's why the route is built this way.

So, to get such a route as on your screenshot "Expected route: Go straight south" - set Riding style **Balanced**
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/203986320-a049bf34-4fee-4593-9004-0cd043fa2be2.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table>  


To get a route like on your screenshot "Actually proposed route by OsmAnd" - set Riding style **Prefer byways**
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/203986416-8fcc4ade-db11-43d6-ab08-c29eedc038bf.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table>  

Also, note that the OSM bicycle OSRM offers a similar route [OSM bicycle OSRM](https://www.openstreetmap.org/directions?engine=fossgis_osrm_bike&route=51.96862%2C7.62225%3B51.96520%2C7.62337#map=18/51.96647/7.62449)
