### ISSUE TITLE
vehicle=private/destination is ignored in bicycle routing

### ISSUE THREAD

**Issue by Langlaeufer** [osmandapp/OsmAnd#15814]
# 🐞 routing report

### Routing engine

OsmAnd Offline

### Routing Profile

Bicycle 

### Start and end points

vehicle=private https://www.openstreetmap.org/way/128881972
vehicle=destination https://www.openstreetmap.org/way/28630594

### Actual and expected routes
OSMAnd ignores vehicle = private and vehicle=destination for bicycle routing.
I expect that OSMAnd respects at least vehicle=private

## 🌍 Your Environment

**OsmAnd Version:**
4.3.0

**Comment by Zirochkabila** [comment]
Reproduced
OsmAnd~ 4.3.0#13979mqta, released: 2022-11-28
Even with deactivated of access to the private sector - the route is laid through the private sector (Bicycle)


https://user-images.githubusercontent.com/104760013/204272113-cdb2ac76-4b4c-4162-b7f9-d803fc3ee7ad.mp4


[OSM GraphHopper](https://www.openstreetmap.org/directions?engine=graphhopper_bicycle&route=52.4579%2C9.8788%3B52.4546%2C9.8796#map=16/52.4574/9.8842)
[OSM OSRM](https://www.openstreetmap.org/directions?engine=fossgis_osrm_bike&route=52.4579%2C9.8788%3B52.4546%2C9.8796#map=15/52.4591/9.8861)
[OsmAnd Bicycle](https://test.osmand.net/map/?start=52.457794%2C9.878785&end=52.454774%2C9.879563&mode=bicycle#17/52.45646/9.88081)

Regarding your second link, the route is built on OSM (GraphHopper or OSRM) [Tag:vehicle=destination](https://wiki.openstreetmap.org/wiki/Tag:vehicle=destination?uselang=uk)
Also, it is noted that transit traffic using a vehicle is not allowed, **but** anyone can still use it to reach a destination that cannot be reached otherwise. Overrides access=* and in turn can be overridden by more specific motor_vehicle=*, bicycle=*, etc.

**Comment by Langlaeufer** [comment]
Regarding the second example, in the meanwhile the tagging was changed. I will look for a new example.

**Comment by vshcherb** [comment]
- The issue quite unclear cause https://wiki.openstreetmap.org/wiki/Tag:foot=permissive?uselang=en there is foot permissive person could go by foot with a bike at least. 
- To disable bicycle it's possible to put a lock_gate and barrier restriction. 

Right now I see quite contractive access-private and foot-permissive tags.

P.S. current configuration access-private will block bicycle https://www.openstreetmap.org/way/128881972#map=18/52.45595/9.87968

**Comment by Langlaeufer** [comment]
In fact there this is a private property where passage by foot is tolerated.
The intension of tagging access=private was to stop the bicycle rooting through the property.

But it is a general issue:  on vehicle=private I do not expect bicycle routing!

**Comment by vshcherb** [comment]
Added vehicle - private restriction

**Comment by Langlaeufer** [comment]
new example for **vehicle=private**
https://www.openstreetmap.org/way/208840556#map=15/52.3240/9.5797

example for **bicycle=private** (i guess bicycle=private here it is wrong, but it should simply demonstrate the routing on private way)
https://www.openstreetmap.org/way/57778109

**Comment by vshcherb** [comment]
And ? can we drive here by bicycle or not https://www.openstreetmap.org/way/208840556#map=17/52.32442/9.57867 ?

**Comment by Langlaeufer** [comment]
you can ride a bicycle there, but it is not allowed.
and yes its also allowed to push your bicycle (but I guess this is not calculated when 0.9 km takes  2 min)

I do not understand your questions. It is not about solving wrong tagging.
The tagging clearly says that bicycle riding is not allowed. osmand route anyway over the way (without a penalty for pushing)
