### ISSUE TITLE
OsmAnd crashes when rotating in simulation mode and sometimes when navigating

### ISSUE THREAD

**Issue by hvdwolf** [osmandapp/Osmand#1582]
I posted this a few days bag in the forum:
Today I was trying the simulation mode of a route with the 2.1.1 OsmAnd+ from the play store. 
I accidentally rotated my phone duringthe simulation and nothing functioned anymore: it was completely blocked. I really had to open the phone and remove the battery.

After starting it up again I very reluctantly tried it a second time. And again: the phone was completely blocked upon rotation during the simulation. Again I had to open the phone and remove the battery.
I used it with a roads-only map. I don't know whether it also crashes with normal maps but I don't even want to try.

Please fix this bug.

OsmAnd+ 2.1.1 Play Store.
Samsung S5 mini Android 4.4.2
==
thread: https://groups.google.com/forum/#!topic/osmand/ohZPN5JImqE
equal thread (my mistake): https://groups.google.com/forum/#!msg/osmand/PD92AIgZo5c/aS2ZjsqOR5cJ

**Comment by Boothy99** [comment]
Having read hvdwolf's post in Google Groups, I repeated the steps described above. In simulation mode of a route with the 2.1.1 OsmAnd+ Play Store, rotating the screen does crash & lock the phone, requiring phone reset hard.
The issue was repeated using the standard Offline vector map, so not "road only map" specific. I was using an HTC One M7 on android Lollipop.

**Comment by Boothy99** [comment]
Just tried to repeat the issue on my LG G Pad 8.3 (android 4.2.2), using the above route simulation. On rotating screen, OsmAnd force closes the screen view ( black screen) then view reappears. Simulation continues but no map seen (will attach screenshot). Every few seconds, the screen view shuts down and reopens. On this occasion, I was able to close down OsmAnd but tablet was not crashed. Am using it currently without a hard reset.
![screenshot_2015-08-26-17-22-44](https://cloud.githubusercontent.com/assets/13983995/9499533/e9a261e0-4c17-11e5-8f20-8862a370d803.png)

**Comment by vshcherb** [comment]
There is a UI memory leak on rotation which we finalize the fix just in nightlies. Every phone reacts differently on these type of issue, the normal reaction map doesn't display any more after 4-5 rotations. I will try to reproduce it, but having hard phone restart is definitely wrong phone reaction. I think this issue is related to previous mentioned by Harry, I don't know how yet.

**Comment by vshcherb** [comment]
Fixed memory leak for simulation mode.
