### ISSUE TITLE
OsmAnd could detect if wrong means of transportation is chosen

### ISSUE THREAD

**Issue by MichaelHaeckel** [osmandapp/Osmand#1585]
When entering a destination and starting navigation it easily happens that a wrong means of transportation is set, because in some cases OsmAnd simply doesn't ask for it and also does not display it anywhere but uses what was used last time. For example when using address search and then the navigation button then this is the case. When starting navigation in a different way the choice is offered, however.

This could be improved in the UI but it brings me to a different point. If pedestrian routing is active and I drive with a speed of for example 80 km/h OsmAnd could detect automatically that probably something is wrong and ask me if I would actually prefer car navigation instead of suggesting ways which are not allowed for cars.

**Comment by Barrocas** [comment]
As it is now, it appears that Osmand is judging the transportation mode by the the destination distance.

With today night build, I set a destination in the town were I was, and strangely noticed that although I usually travel in a car, it was now sending me against incoming traffic on a one way road!
I obviously ignored this, and went the correct way, then I realized that there were no turn indication icons on the top left, because when I was planning the trip, Osmand had decided that my transportation mode would be to go pedestrian... When I wanted to go by car.

The app itself has no means of knowing if I will travel by foot, bike or car, if I am at a stoped position, so that choice should always belong to the user. 
Osmand should maintain my previous navigation mode.

After being on the move, then Michael is right, it could decide that it's unlikely to someone run on foot at 80km/h :) and change to car mode, if it was set to pedestrian at the start of navigation.
But even this can be tricky at times, dependind on circumstances, since I also used the bike mode to go on motorcicle (+200km/h possible top speed), and wouldn't want to be annoyed with questions along the trip.

This reminds me of another question:
Does the bike mode allow to go against traffic on one way streets?
Does bike mode act more like pedestrian (free moving) or like car mode (with road restrictions)?

**Comment by Barrocas** [comment]
Tested on night build, bike mode follows car restrictions, so no problem there.

Jack Burke also reported having a problem with routing against traffic:
https://groups.google.com/forum/m/#!topic/osmand/q_5G0DsYVbQ

**Comment by Barrocas** [comment]
Please remove the Osmand self-decided routing mode change.

If I navigate on Car, I want it to stay in Car mode.
I should decide what way of transportation I will be using, not the app by itself changing my last setup, without notice.

I had several ocasions were I was in Car, setup a route nearby, and Osmand (night build) would change the routing mode to Pedestrian (by itself).
This results in routing agains incoming traffic (oneway streets) when driving on car, so that's dangerous for the user who didn't notice that the app changed the routing profile.

**Comment by sonora** [comment]
I tend to agree. I also see no benefit in having it. We have a default mode (car, unless you change it), and it should be used by default. If you start a follow-up navigation, it should again be using the prior mode. 
On the rare occasion that you change your way of transport, let people specify this explicitly, it is more transparent than unexpectedly making an automatic assumption.

**Comment by Barrocas** [comment]
I would see no problem if I was in Pedestrian mode, and Osmand would ask if
I wanted to change to Car mode, if a 120km route was to be planned.

But I really don't like it changing (without notice) from Car mode to
Pedestrian, just because the route is like 2.5km away, or less.
If the user doesn't notice the automatic change, it may cause him to get in
troubles.


-- 
Cumprimentos,
D.er Hugo Barrocas

**Comment by vshcherb** [comment]
Yes, I updated / reverted to kind of previous behavior please check here https://github.com/osmandapp/Osmand/commit/39c94b82a6ca059cdfc5df29ae3cad9351523b1d
