### ISSUE TITLE
German translation: Search for Campingplatz

### ISSUE THREAD

**Issue by seppwabala** [osmandapp/Osmand#1593]
The POI search in german language for Campingplatz only finds caravan places but not camping sites.
In english working fine.

Osmand+ 2.1.1

**Comment by xmd5a2** [comment]
https://github.com/osmandapp/Osmand/blob/master/OsmAnd/res/values-de/phrases.xml#L92
```xml
	<string name="poi_camp_site">Campingplatz</string>
	<string name="poi_caravan_site">Campingplatz</string>
```
There is two identical translations, but only caravan_site is found during POI search.

**Comment by seppwabala** [comment]
"poi_caravan_site" should be better translated as Wohnmobil-Stellplatz, see
https://wiki.openstreetmap.org/wiki/DE:Tag:tourism%3Dcaravan_site

**Comment by xmd5a2** [comment]
Done

**Comment by vshcherb** [comment]
As a side-notice comment, we are working on updating documentation for translators. Actually in phrases.xml we should not have any duplicates in order to avoid confusion with a small exception of poi_additional. We would need to design proper validation tool may be, but these issue could be fixed only manually by changing translation.

**Comment by seppwabala** [comment]
By the way. There is a typo in
https://wiki.openstreetmap.org/wiki/DE:Tag:tourism%3Dcaravan_site

Kommunikationstumr -> Kommunikationsturm

**Comment by stephan75** [comment]
@seppwabala
You can fix those typos inside  the osmand instance in hosted.weblate.org ... Log in there with your github account.

**Comment by seppwabala** [comment]
Thanks for the hint. Done.
