### ISSUE TITLE
All data lost after moving osmand to a user specified data folder 

### ISSUE THREAD

**Issue by Rowin63** [osmandapp/OsmAnd#16043]
### Description
@vshcherb 
Sorry, but I don't know, if you will respond on a message in an already closed issue, so I start this theme again. 
I tried the same procedure again, moving osmand to a user specified data folder outside obb. And again, all data is lost, nothing remains in the previous location and nothing is moved to the new data folder. 
No tracks, no favorites, no maps, no contour lines, no av-notices, nothing. Everything lost again. 
See the attached screenshots. All previous and all new folders are empty.

So please tell me the correct way, how to move osmands data to a user specified folder outside "obb", that gives me access to my data? I want access to favourites, tracks, ... to be able to sync this data on my three devices (via Onedrive), like it was possible until A12. Thanks!

Merry christmas to all of you.

### Your Environment
OsmAnd Version: +4.3.3
Android/iOS version: 13
Device model: S20+ 5G

**Maps used (online or offline):**   
offline

![1a](https://user-images.githubusercontent.com/845735/209344492-cf587d0a-beb4-4736-bbe3-70a0518c99ef.jpg) ![2a](https://user-images.githubusercontent.com/845735/209344733-ef329553-adcd-4602-9814-aa9c82fa87ee.jpg)
![3a](https://user-images.githubusercontent.com/845735/209344839-1d4f96b2-d393-4810-94c1-9d2711ea0fff.jpg) ![4a](https://user-images.githubusercontent.com/845735/209344859-3f08b9b9-478e-4846-915e-498f80430e58.jpg)

**Comment by sonora** [comment]
"Not-so-fun" facts about the entire situation:

1. Ever since Android 11 (plus/minus, it came in waves), apps can access arbitrary custom folders only under one of two conditions: Either the app targets Android 10, or the app requests permission "All files access". Both solutions are straightforward, but severely restricted by the Google Play Store rules.

2. Otherwise, app access to folders is severely limited, in terms of available folder selection as well as read/write mechanisms and performance.

3. In addition, newer versions of Android have started to limit or inhibit access to exactly these 'allowed' folders both for on-device file manager apps, as well as via USB connection to e.g. a PC.

It seems the Android ecosystem is trying to severly move towards _hiding the file system from the device user_ under many circumstances, even for power users, with all impact that has on many formely common processes like e.g. syncing files via flexible, ecosystem-overarching mechanisms.

I currently fall back to using custom-builds of OsmAnd for that reason, but that cannot be mainstream. It remains to be seen if the new Digital Markets Act of the European Union (potentially enhancing the business case of alternative app stores) or user feedback to Google can serve to change the situation in the future.

Regarding the OsmAnd issue reported here: We need to research if there is some flaw in OsmAnd we could fix. I am currently at loss why there can be situations where OsmAnd would  succeed to create custom folders and then fails to write files.

**Comment by Rowin63** [comment]
Thanks for that detailed answer 👍

**Comment by Rowin63** [comment]
> Regarding the OsmAnd issue reported here: We need to research if there is some flaw in OsmAnd we could fix. I am currently at loss why there can be situations where OsmAnd would succeed to create custom folders and then fails to write files.

All the previous existing, but now empty data folders have a "new" time stamp. 
The previous empty ones (roads, routing) dont change their time stamp.

**Comment by vshcherb** [comment]
I will respond in a closed issue which indicates that no action is planned to be done.

Another side action that we've created a possibility to download all files as a zip if they are in OsmAnd Cloud 
![Screen Shot 2022-12-23 at 19 10 11](https://user-images.githubusercontent.com/1042025/209376287-54b4f862-b396-42c2-90c9-5ee917c95b14.png)

**Comment by sonora** [comment]
Any explanation how this could happen in the first place? Is it posssible that we copy/move files and delete the source before having verified that the target is written and accessible?

**Comment by vshcherb** [comment]
First location is changed and then files are copied. Files could fail to copy and then they're stayed in previous location. I think there is a dialog that displays that X of Y files has been moved you can revert to previous location to get access to missing files

**Comment by sonora** [comment]
Exactly. But it seems the user insists there was permanent data loss, which I find hard to believe. Should maybe @Zirochkabila try to reproduce?

**Comment by Rowin63** [comment]
The only dialogue/message was a pop-up that said (something like) "maps could not be moved". Nothing else. Source and target was empty after that.

**Comment by Rowin63** [comment]
This issue reminds me to the one, where osmand "threw away" all data at running an update. 
The result seems the same, only the standard-files did remain, then and now.

**Comment by Rowin63** [comment]
OsmAnd+ 4.4.0#14131:
I changed the data folder from "External 1" to Multiuser 1" ("data" to "obb") and all data seems to be moved correctly 👍

**Comment by sonora** [comment]
Yes, but the true test for the fix is try to move to a _not writeable_ location and see what happens, right?

**Comment by Rowin63** [comment]
Ok, my last failed try was moving data to a "user specified folder" I created outside "obb". 
I don´t know if this was a _not writeable location_ or not, it just failed. 
BTW: the empty folders in the origin (data folder/external 1) were not removed after succesfully moving all data.
