### ISSUE TITLE
Trip recording / online tracking: Huge battery consumption

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/OsmAnd#16044]
Enabling online tracking from the trip recording leads to a huge power consumption. The battery drains really fast and the phone gets hot, even if the display is switched off. Something is really wrong with this feature. Restarting OsmAnd didn't help. 

OsmAnd 4.3.3. Tracking interval set to 15 seconds. Samsung Galaxy S9.

**Comment by Eheran1** [comment]
Doesn't seem to be a general issue, I just logged for about 30 min with a Galaxy S20. Does it take longer to notice the issue?

**Comment by scaidermern** [comment]
> Doesn't seem to be a general issue, I just logged for about 30 min with a Galaxy S20. Does it take longer to notice the issue?

No, it becomes immediately visible for me.

**Comment by sonora** [comment]
Perhaps it's related to sone error condition, like a typo in the URL, or missing internet connectivity?

**Comment by scaidermern** [comment]
URL looks fine to me (it is the one from https://github.com/osmandapp/OsmAnd/issues/6878#issuecomment-1361601785, `https://trafficpixel.tk/trafficSql/createEntryPdo.php?lat={0}&lon={1}&speed={5}`). Internet connection exists. Since there is no feedback from OsmAnd I can't really check if everything is working as expected.

**Comment by mvglasow** [comment]
Battery consumption could be because Osmand is almost constantly exchanging data; every single point is sent in a separate HTTP request. Doing that in real time probably isn’t very efficient. I suspect it would be more economic to upload points in bulk every couple of minutes (the interval should be user configurable). If we then use HTTP connection keep-alive, we’ll only have one TCP handshake every couple of minutes, rather than one per point. Also, there is a longer interval between transfers, possibly allowing the modem to go into power-saving mode.

This is, however, just speculation and would need to be tested. If it turns out this helps, then choosing the interval would be a tradeoff between power efficiency vs. responsiveness and therefore depend on the use case.

**Comment by Rowin63** [comment]
Can someone please guide me how to use this traffic info?
Thank you!

**Comment by scaidermern** [comment]
> Battery consumption could be because Osmand is almost constantly exchanging data; every single point is sent in a separate HTTP request. Doing that in real time probably isn’t very efficient

Well, I set the time interval to 15 seconds. So I expect OsmAnd to upload data only every 15 seconds which shouldn't be very ressource intensive. I haven't checked yet if the log entries correspond to this time interval.

**Comment by vshcherb** [comment]
I think battery consumption related to OpenGL rendering which is more powerful than Rendering v1.

**Comment by sonora** [comment]
What's the consumption in terms of battery percentage points per hour? "_the phone gets hot, even if the display is switched off_" somehow does not sound ok in any case?

**Comment by scaidermern** [comment]
> I think battery consumption related to OpenGL rendering which is more powerful than Rendering v1.

As stated, it happens with the screen being *off*. Also, it doesn't happen with regular track recording. Only with online tracking enabled.

**Comment by otteresk** [comment]
Hi, I have the same issue with OsmAnd 4.5.10 on a Fairphone 4 (Android 13). This makes online tracking nearly unusable. Any recommendation/solution?

**Comment by scaidermern** [comment]
Bug still exists for me, too. No workaround known.

OsmAnd 4.6.6, Android 10. Almost one percent battery usage _per minute_ if trip recording _with online tracking_ is enabled and display is switched _off_ (see the dip in the middle of the graph):

![photo_2023-11-21_17-56-43](https://github.com/osmandapp/OsmAnd/assets/1040784/e6100e4c-2b75-4aaa-b89a-e6e2dd2dc7b5)

Logcat (I've obfuscated my positions): 
[logcat.log](https://github.com/osmandapp/OsmAnd/files/13429129/logcat.log)

Profile: 
[Export_2023-11-21.zip](https://github.com/osmandapp/OsmAnd/files/13429134/Export_2023-11-21.zip)

The phone gets very hot. Thanks for reminding me of this issue. Now I have something to keep my fingers warm in the winter. After I've found some more power power banks...

**Comment by bastimeyer** [comment]
After happily discovering the online tracking feature in OsmAnd a while ago, as a fun exercise, I decided to build my own server backend for collecting my live cycling data, so I could show my route and current position to friends+family in a web front end using the openlayers project. That worked really well.

Unfortunately though, the battery consumption is ridiculously high when online tracking is enabled, which makes this feature unusable in the latest version of OsmAnd (4.7.10).

I had already discovered this during my initial implementations where I discovered that the same HTTP request is attempted up several times per second if the server response is not 200. I thought that this was the reason for the massive battery drain at first.

But after trying out my working server/frontend implementation with actual live data for the first time today and setting the upload interval in OsmAnd from 5 seconds to 60 seconds in order to try saving battery, I noticed that my phone's battery still went from 100% to 90% in just ten minutes (I can see 10 HTTP requests from today in my server log), so I had to disable online tracking again at the beginning of my cycling tour.

The battery consumption rate doesn't seem to depend on the upload interval from what it looks like, because a couple of HTTP requests are surely not responsible for losing 10% of battery. I had seen similar battery usage with an upload interval of 5 seconds. The phone's screen is always turned off, and no other apps are running. Disabling online tracking and just offline-recording my cycling route doesn't drain much battery. Having online tracking enabled while not recording a tour also seems to send HTTP requests, which means having the phone idle with the app running and the feature enabled already drains battery massively. This is obviously not the case when the feature is turned off.

Regarding the data collection and bulk-uploading when there's no connection, as talked about in previous comments here, this is already implemented, isn't it? That's what the storage option is for in the same settings menu.

And regarding HTTP/TLC connections, I don't know if OsmAnd keeps HTTP/TLS sessions alive and doesn't re-initialize everything on each request, but even that shouldn't cause that much battery drain.

I would massively appreciate if someone could have a look at this issue and apply a fix. Thank you very much!

Btw, in case that matters, I'm using LineageOS 18.1 / Android 11 (last update from 2024-01-15) on an old Samsung Galaxy S7.

**Comment by bastimeyer** [comment]
I have no experience with Java/Android development at all, but I found this, where the data sending is implemented in what it appears to be a dedicated thread:
https://github.com/osmandapp/OsmAnd/blob/785cd191967181b65246fb9b070e8675ddb6fb9b/OsmAnd/src/net/osmand/plus/plugins/monitoring/LiveMonitoringHelper.java#L166-L185

According to
https://developer.android.com/reference/android/os/AsyncTask

> This class was deprecated in API level 30.

> AsyncTask is designed to be a helper class around [Thread](https://developer.android.com/reference/java/lang/Thread) and [Handler](https://developer.android.com/reference/android/os/Handler) and does not constitute a generic threading framework. AsyncTasks should ideally be used for short operations (a few seconds at the most.) If you need to keep threads running for long periods of time, it is highly recommended you use the various APIs provided by the java.util.concurrent package such as [Executor](https://developer.android.com/reference/java/util/concurrent/Executor), [ThreadPoolExecutor](https://developer.android.com/reference/java/util/concurrent/ThreadPoolExecutor) and [FutureTask](https://developer.android.com/reference/java/util/concurrent/FutureTask).

As said, I don't know any Java and the APIs in use here, so apologies if I'm wroing, but this data sending worker-thread is running a while loop as long as the settings are enabled and pulls data from a non-blocking thread-safe queue:
https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/ConcurrentLinkedQueue.html

This would mean, if I'm not mistaken, that this worker thread is simply running a while-loop and checks for queue items without blocking its execution on an empty queue. If the upload interval time has not been reached yet, it simply keeps iterating the loop instead of waiting for a specific time. That doesn't seem right.

**Comment by vshcherb** [comment]
Please give it a try with 4.8 nightly

**Comment by bastimeyer** [comment]
Thanks for the fix. The battery usage is fine now. :+1: 

However, I'm seeing some HTTP requests being skipped. I've set the interval to 5 seconds and my server logs sometimes have a gap of 10 seconds. Maybe a race condition between the main and sender thread?

```
my-ip-address - - [29/Apr/2024:15:12:33 +0200] "GET /in?timestamp=1714396350647 HTTP/1.1" 200 - "-" "Dalvik/2.1.0 (Linux; U; Android 11; SM-G930F Build/RQ3A.211001.001)"
my-ip-address - - [29/Apr/2024:15:12:38 +0200] "GET /in?timestamp=1714396355693 HTTP/1.1" 200 - "-" "Dalvik/2.1.0 (Linux; U; Android 11; SM-G930F Build/RQ3A.211001.001)"
my-ip-address - - [29/Apr/2024:15:12:43 +0200] "GET /in?timestamp=1714396360727 HTTP/1.1" 200 - "-" "Dalvik/2.1.0 (Linux; U; Android 11; SM-G930F Build/RQ3A.211001.001)"
my-ip-address - - [29/Apr/2024:15:12:53 +0200] "GET /in?timestamp=1714396370722 HTTP/1.1" 200 - "-" "Dalvik/2.1.0 (Linux; U; Android 11; SM-G930F Build/RQ3A.211001.001)"
my-ip-address - - [29/Apr/2024:15:12:58 +0200] "GET /in?timestamp=1714396375740 HTTP/1.1" 200 - "-" "Dalvik/2.1.0 (Linux; U; Android 11; SM-G930F Build/RQ3A.211001.001)"
my-ip-address - - [29/Apr/2024:15:13:03 +0200] "GET /in?timestamp=1714396380756 HTTP/1.1" 200 - "-" "Dalvik/2.1.0 (Linux; U; Android 11; SM-G930F Build/RQ3A.211001.001)"
my-ip-address - - [29/Apr/2024:15:13:08 +0200] "GET /in?timestamp=1714396385809 HTTP/1.1" 200 - "-" "Dalvik/2.1.0 (Linux; U; Android 11; SM-G930F Build/RQ3A.211001.001)"
my-ip-address - - [29/Apr/2024:15:13:13 +0200] "GET /in?timestamp=1714396390846 HTTP/1.1" 200 - "-" "Dalvik/2.1.0 (Linux; U; Android 11; SM-G930F Build/RQ3A.211001.001)"
my-ip-address - - [29/Apr/2024:15:13:18 +0200] "GET /in?timestamp=1714396395874 HTTP/1.1" 200 - "-" "Dalvik/2.1.0 (Linux; U; Android 11; SM-G930F Build/RQ3A.211001.001)"
my-ip-address - - [29/Apr/2024:15:13:28 +0200] "GET /in?timestamp=1714396405900 HTTP/1.1" 200 - "-" "Dalvik/2.1.0 (Linux; U; Android 11; SM-G930F Build/RQ3A.211001.001)"
my-ip-address - - [29/Apr/2024:15:13:33 +0200] "GET /in?timestamp=1714396410929 HTTP/1.1" 200 - "-" "Dalvik/2.1.0 (Linux; U; Android 11; SM-G930F Build/RQ3A.211001.001)"
my-ip-address - - [29/Apr/2024:15:13:39 +0200] "GET /in?timestamp=1714396415939 HTTP/1.1" 200 - "-" "Dalvik/2.1.0 (Linux; U; Android 11; SM-G930F Build/RQ3A.211001.001)"
my-ip-address - - [29/Apr/2024:15:13:43 +0200] "GET /in?timestamp=1714396420980 HTTP/1.1" 200 - "-" "Dalvik/2.1.0 (Linux; U; Android 11; SM-G930F Build/RQ3A.211001.001)"
my-ip-address - - [29/Apr/2024:15:13:54 +0200] "GET /in?timestamp=1714396431072 HTTP/1.1" 200 - "-" "Dalvik/2.1.0 (Linux; U; Android 11; SM-G930F Build/RQ3A.211001.001)"
my-ip-address - - [29/Apr/2024:15:13:59 +0200] "GET /in?timestamp=1714396436158 HTTP/1.1" 200 - "-" "Dalvik/2.1.0 (Linux; U; Android 11; SM-G930F Build/RQ3A.211001.001)"
```

**Comment by vshcherb** [comment]
There is a maximum time that location could be stored however this log looks like a race condition. Do you have full track saved locally without gaps?

**Comment by vshcherb** [comment]
Then yes it's a separate issue tottally probably some optimization on device?
