### ISSUE TITLE
Issue displaying Ruler on 2-3 zoom

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/OsmAnd#16054]
![telegram-cloud-photo-size-4-5852686874550844046-y](https://user-images.githubusercontent.com/1042025/209440361-ffa3dcf1-a70f-4474-bbdc-c0c381d2fa02.jpg)

**Comment by sonora** [comment]
Is this v1 or v2?

**In v1 tendering**, the issue is present at all zoom levels, only less noticeable at greater ones: While the distortion of the distance circles looks correct, the placement of the text labels is wrong, and increasingly so with smaller zoom levels. Use e.g. zoom 3, 4, or 5 and pan the map, observe how circles and labels drift apart. (But the labels do for me never 'fold back' into the screen  i.e. I cannot fully teproduce the above screenshot.)

**In v2 rendering **I find no flaw, both circle shape and label position seem correct there?

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14125mqta, released: 2023-01-24
Done


https://user-images.githubusercontent.com/104760013/214252339-771759fc-7a90-49d4-8d52-6377cb9d8536.mp4
