### ISSUE TITLE
visability of all buttons

### ISSUE THREAD

**Issue by Rowin63** [osmandapp/OsmAnd#16079]
### Description
Is there a reason, why the menu- and the navigation-button do disappear when routing is active and reappear at a tap?
No other switch/button/widget does so, only these two?
And why all the other buttons are transparent (even "transparency of widgets is "off") but also these two are not?

Of course it´s ok if you want it like this, but it´s not consistent? 

### Your Environment
OsmAnd Version:
Android/iOS version:
Device model:

**Maps used (online or offline):**   
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.

![buttons invisible](https://user-images.githubusercontent.com/95540936/209685816-6b02e90a-4b1d-4623-88f8-e51f9e3a3728.JPG)
![buttons visible](https://user-images.githubusercontent.com/95540936/209685826-62faf27e-781b-49cb-9be0-e6dfa88aab55.JPG)

**Comment by vshcherb** [comment]
They are not widgets (no information) present - just buttons so we need to think what to do with them.

**Comment by Rowin63** [comment]
Any idea about a uniform appearance (button transparency)...?
Sometimes (depending on the background/map) it´s not so easy to recognize/differentiate the icons of the transparent switches.

Generally "non transparent" would be a temporary (and good) solution, until you have some other idea.

![Screenshot_20240901_085022_OsmAnd+](https://github.com/user-attachments/assets/4a2f8fb1-25c7-4635-b858-1212edae655f)

**Comment by sonora** [comment]
I personally have over the yesrs gotten used to these buttons disappearing during a navigation (screens were small years ago), but I kbow of countless users who struggle with this, in particular with how to stop an ongoing navigation.

I suppose that we could simplify this noticeably for the benefit of all users by two measures:
- Let's not hide the buttons
- Perhaps instead of using 'blue' for an ongoing navigation use our more 'active-indicating' orange color. There are several other blue buttons on  the map screen like the profile or location button, so it could be good to signal in orange on the navigation button if something is 'ongoing' and you can stop it there.

**Comment by Rowin63** [comment]
The disappearing of some buttons is another thing and it's good you're thinking about. 
But I'm talking about the different appearance (transparency) of all the buttons. Some are transparent, others are not. User defined I can change the transparency, others (not user defined ones) I can't 🤔

**Comment by Rowin63** [comment]
Appearance of user defined buttons: "apply to all" and/or "apply to all profiles" would be helpful, when changing x buttons in y profiles... 👍

**Comment by vshcherb** [comment]
Yes we apply to all will be in release. Functionality is implemented
