### ISSUE TITLE
Blue routing arrow has extreme "lags" on intersections (since 4.3.3)

### ISSUE THREAD

**Issue by TheSnoozer** [osmandapp/OsmAnd#16081]
### Description
I don't really know how to describe the issue better, but since I updated to 4.3.3 I experience extreme lags of the blue routing arrow (my current position) on intersections. The lag can last anywhere from 10 seconds to 40 seconds. This makes navigation extremely painful and causes a lot of wrong turns if there is a turn shortly after an intersection.

Here is an example:

```
https://user-images.githubusercontent.com/6849390/209714763-9c5bbfca-b65f-450d-88cc-226608936b45.MP4
```

Note that OsmAnd seems to know better about my position since the widget on the top left get's updated (e.g. the distance to the next intersection).

### How to reproduce?
No idea.

### Your Environment

Device : RE513CL1
Brand : realme
Model : RMX3241
Product : RMX3241EEA
Build : RMX3241_11_C.05
Version : 12
App Version : OsmAnd+
Apk Version : 4.3.3 4303

**Maps used (online or offline):**   
Offline, Map-Rendering Engine: V1, in case it may help footage was recorded around https://www.openstreetmap.org/#map=19/43.18995/6.5867

**Comment by Rowin63** [comment]
Can´t play the video, but as you describe it, I can confirm this issue. Same here (+4.3.4)

**Comment by TheSnoozer** [comment]
Can you try downloading it and play it with VLC or something? It indeed doesn't seem to work with the web-interface, but the downloaded version works without issues on my end.

**Comment by Rowin63** [comment]
Seen the video - yes, exactly the same here.

**Comment by TheSnoozer** [comment]
Can confirm the problem is also present in:
```
Version : 12
App Version : OsmAnd+
Apk Version : 4.3.4 4304
```

It also doesn't make a difference if the location provider is changed from "Google Play Services" to "Android API" (or vice versa)

**Comment by Rowin63** [comment]
> Note that OsmAnd seems to know better about my position since the widget on the top left get's updated (e.g. the distance to the next intersection).

You can see this also on the track line itself, especially when the "real" actual position in reaching an guiding arrow.

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14064mqta, released: 2022-12-30

`43.18966° N, 6.58947° E`
It was not possible to reproduce either in the navigation simulation or in the simulation of location on the track.
Try again with the latest nightly (beta version - available on OsmAnd page in OlayStore) version.
Also, the problem may be similar [to](https://github.com/osmandapp/OsmAnd/issues/16086)

**Comment by Rowin63** [comment]
Hello!
It does not happen in a simulation.
I'll try the nightly later 👍
Thank you

**Comment by Rowin63** [comment]
I installed a freshly V4.3.5 from the PlayStore and the problem did not appear.
After that I updatet my +Version to the new V4.3.5 from the PlayStore (is this the "nightly"?) and the problem still existed.
My next step will be de- and re-installing my +Version and see whats happening with a new install.

See the added sceenshots. This problem does not only appear at intersections, but also in long curves and turns like freeway ramps.

lag_1: you can already see, the vehicle doesn´t follow the track anymore, but remains at the same position. Map begins turning, because actual posotion is already a bit further.
lag_2: actual position again further, maprotates, but does not follow the actual position.
lag_3: a few seconsd later, still the same.
lag_4: actual position is about at the red mark. Vehicle still does not folloow the actual position.
lag_5: here the vehicle "jumped" to the actual position again.

You can see by the distances to ne next turns (which are always correct), it took 200m until position was correct again.
It seems, the visualisation does not follow the actual position.
This issue makes it impossible to use Osmand for navigation inside a city. 


![lag_1](https://user-images.githubusercontent.com/95540936/210105585-1e43f02e-448a-45d1-9b41-abc4d7bf6f73.JPG)
![lag_2](https://user-images.githubusercontent.com/95540936/210105596-fcdc84a0-1f42-4302-b087-d62c33360aa9.JPG)
![lag_3](https://user-images.githubusercontent.com/95540936/210105605-fa289560-53fb-41a4-bfc5-9c2936b8b35b.JPG)
![lag_4](https://user-images.githubusercontent.com/95540936/210105612-2e01cf19-e0eb-4ae0-a4bd-989fcc4ceb9c.JPG)
![lag_5](https://user-images.githubusercontent.com/95540936/210105622-4260168f-202a-4f1f-aa9c-5384e32b42fd.JPG)

**Comment by sonora** [comment]
You have an overlay transparency slider visible... could it be the issue occurs only while an overlay is selceted?

**Comment by Rowin63** [comment]
Yes, it's the Microsoft Earth Overlay. 
I'll check this tomorrow 👍

**Comment by Rowin63** [comment]
Good morning!

First: deactivating the overlay in the driving profile did not help.
Second: on my other device (S20+) this issue does not exist! 

I mainly use the same settings, maps, tracks,... on both devices. So at the moment it's not clear to me, what makes the difference. Why the S20+ works fine and the S20+ 5G produces this issue.
Two possibilities: it's the device or it's the app...

How to find out? Comparing every single setting on both devices seems a bit hard to me... Any idea on your side?

**Comment by Rowin63** [comment]
After a first try it does not happen when map rotation is set to "always north up"!

**Comment by sonora** [comment]
Quite possibly this is yet another visual appearance of the various "freeze" occurrences, where the map gets stalled and does intermittently  not perform panning or rotation under engine v2.

**Comment by Rowin63** [comment]
I use engine v1

**Comment by Rowin63** [comment]
I thought to de- and re-install osmand again, to see step by step when bringing my data back, if and when tis issue occurs.

But since there is no more local backup in 4.3.5 I´m not going to do this.
Bring local backup back again please!!!

My last online-backup was a disaster!

**Comment by Rowin63** [comment]
I did a new install of Osmand.
Some data was automatically restored, like favorites and profiles, I don´t know what else and how I can avoid this.
Anyway, this issue was still present after new intsall.
So I did reset the used car-profile to it´s original settings, issue is still present.

I dont know what else to do, like this I cant use Osmand for navigation.
Fact is, it did not happen before 4.3.3.
Happy new year.

**Comment by Rowin63** [comment]
Issue does not seem to be present when running engine 2.

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14068mqta, released: 2023-01-02

It was possible to reproduce a delay of 1-2s when simulating the location by GPX (these are the most similar conditions to the usual navigation) using V1 rendering, Microsoft Earth Overlay, and Location source Android API - but this is far from the delay that the user writes about (10-40s).
@TheSnoozer  Please, provide the header files for the next playback (maybe there will be useful information there): Menu > Help > Send logcat log

**Comment by Rowin63** [comment]
On my last Screenshots you can see a delay of about 200m at speed of ~50km/h. That's a delay of 14s.

**Comment by vshcherb** [comment]
This is Rendering Engine v1, animation likely not optimized for it. You can disable Animate my location in Navigation Settings.

**Comment by vshcherb** [comment]
P.S. Prior 4.3 animation was not working for rendering engine v1

**Comment by TheSnoozer** [comment]
Hello,
thanks for your feedback and investigation!

In Settings Android Menu → Settings → Profiles → Car profile (or any other profile) →General settings I see that I have not enabled "no animations" which means I'll have animations enabled.

Based on the feedback I'd assume animations will work for rendering engine v1 under OsmAnd 4.4.0 and will assume this issue is fixed. I also hope that i'll be able to use rendering engine v2 under OsmAnd 4.4.0 so this problem likely will go away for me anyways.

As a side-note I have not seen any helpful indications what could be wrong in the logcat log but will certainly ensure to provide it when i encounter this with OsmAnd 4.4.0.

Thanks again for your hard work!

**Comment by vshcherb** [comment]
Setting is called "Animate own position"

**Comment by sonora** [comment]
Side note: We either need to have clearer wording for the two animation settings (let me know what they do and 'Il suggest), or we will need to combine them to one settings for all "animation" stuff?

**Comment by scaidermern** [comment]
I'm wondering whether "Animate own position" is broken and needs fixing. Just take a look at how many users complain about  this feature. Isn't there anything which can be done to make this feature more reliable?

**Comment by vshcherb** [comment]
People complain about rendering engine v1 where animation is not smooth for v2 it shouldn't be a problem.

**Comment by scaidermern** [comment]
> People complain about rendering engine v1 where animation is not smooth for v2 it shouldn't be a problem.

So why not disable this function for v1 then? There are periodic complaints about this bug. Not just the >5 tickets linked here but also in other communities (OsmAnd Telegram groups etc.). Looks like this is still a problem for many users.

**Comment by vshcherb** [comment]
I can't confirm on my device that v1 animation has no effect, it has and works probably as before. I can't say whether it's slower than previous versions that's why I think it should stay as it is

You probably underestimate that before opengl version every 1-2 months we were receiving complaints anyway that v1 rendering is slow, so it will continue for v1 as conceptually slower rendering

**Comment by ufotech** [comment]
I had the same issue on a Galaxy S7 Edge with Android 8 in Version 4.7.3 just now.
When told to switch to the new Rendering-Engine v2 (OpenGL) all worked smooth again.

**Comment by scaidermern** [comment]
> You probably underestimate that before opengl version every 1-2 months we were receiving complaints anyway that v1 rendering is slow, so it will continue for v1 as conceptually slower rendering

To me it doesn't look like this has something to do with slow rendering. Looks more like animate own position is just broken for v1. Before this ticket was created nobody complained about this bug, or am I wrong? So somehow this worked before (or didn't exist before at all?) and at some point it broke for v1. So why keep it? Kill it with fire, unless v2 is enabled. Otherwise people won't stop complaining about this bug.

**Comment by sonora** [comment]
I concur with @scaidermern above. I also observe we somehow broke animation for v1 when introducing v2. I tend to support, at the very least, to default-disable the now problematic animation setting with engine v1?
