### ISSUE TITLE
Make cancelling the active navigation easier

### ISSUE THREAD

**Issue by kodiakcreativity** [osmandapp/OsmAnd#16122]
Cancelling a route in progress is a pretty common thing to do, you're navigating to get home but eventually you know where you are and would rather not have your nav interrupting your audiobook to tell you things you already know!

with other maps like Google there is a single button always available on the screen to end navigation, you just push it.
with OSMAND however...
tap the screen to bring up the UI
click the blue arrow icon to bring up the route window
click the dismiss (cancel...I don't remember) button to cancel the route
and then you even have to tap yes to the prompt before it will stop navigating.

that's a lot of taps!
Please consider an alternative like this:
have a button always available on the UI somewhere like google does, or at very least a button that appears whenever you tap the screen, maybe a red X icon next to the blue arrow or something?
then have it do this: immediately stop route navigation, stop prompting for turns etc right away. but, to handle the case of a user who didn't mean to cancel, pop up a message at the bottom of the screen which says route navigation cancelled, press this button to resume your previous route. and have a button there that you can click if you cancelled your route by mistake, a button to clear that message right away in case you cancelled because you want to create a new one right away, and a 60 second (or so) count down where this message will clear itself. this way, you can cancel the route navigation any time with only a single click (or 2 at the most) and immediately the nav stops talking to you, you can just let the timer run out with no further interaction needed.

sometimes when the route is no longer needed it can be very annoying, and the current method needed to cancel the route is so complex it takes your eyes away from the road too long!

thanks for considering this.

**Comment by tradavyvy** [comment]
Sounds good to me.
But I would suggest a modification:
When hitting the 'stop navigation' button the routing software will remove the next destination, not the whole route. This way the function can also be used if you (deliberately or not) missed an intermediate destination.
Sometimes osmand does not realise the intermediate destination is already passed.
Sometimes it is raining and I would like to skip the intermediate stop at the beach or....

For direct routes the effect would be just to stop the navigation, 
If you want to completely stop a multi destination route, just double tap or long tap the stop.

**Comment by mikehgentry** [comment]
I read somewhere (can't remember where I'm afraid) that they're planning on extending quick actions to allow several quick action icons, and presumably activate ones with only one action assigned with a single tap, so you should be able to configure it to do that.

**Comment by sonora** [comment]
Are you aware that the shortest way to terminate an ongoing navigation currently is: this 3-tap actuon:
1. Swipe to the Android system notification
2. Tap the Navigation notification
3.  Tap "Stop"

On the map screen this is indeed one step longer:
1. Tap the map to make the buttons appear
2. Tap the blue route button
3. Tap "Stop"
4. Confirm "Yes" to dissmiss the route.

Here I suggest we could kill the confirmation dialog, because you have alrady taken 3 deliberate taps which makes accidantal stopping at this point unlikely, plus we now offer a way to simply resume the last route.

That would bring us to 3 taps in any case?

**Comment by tradavyvy** [comment]
That does not adress the issue of easily skipping only the next destination.

**Comment by sonora** [comment]
@tradavyvy True, but it's a start which I think most users would benefit from.

Skipping only the next destination is trickier  because what's been suggested so far is not easily discoverable,  i.e. would only serve users knowing about it, while confusing others by sometimes killing the route and sometimes not? And in cases with several destinations it defies the original purpose of quickly killing everything.

So for the use case of killing intermediates an explicit quick action may be the way to go?

**Comment by sonora** [comment]
Yes, it an old topic ... https://github.com/osmandapp/OsmAnd/issues/7726#issuecomment-735367431 :wink:

**Comment by vshcherb** [comment]
https://github.com/osmandapp/OsmAnd/issues/15479
