### ISSUE TITLE
Error launching OsmAnd+ 2.1.1 from Contacts with Nexus 6 5.1.1

### ISSUE THREAD

**Issue by clemefr** [osmandapp/Osmand#1614]
From contacts app, both Google maps location and direction icons launch OsmAnd+ with errors
see image
![2015-08-27 17 42 33](https://cloud.githubusercontent.com/assets/6375236/9542605/8ffb1a86-4d72-11e5-88ea-9f3edb9a552f.png)
![2015-08-28 08 28 29](https://cloud.githubusercontent.com/assets/6375236/9542606/92e8399a-4d72-11e5-9419-6018075fd9f8.png)

**Comment by ericzolf** [comment]
This issue exists since ages (latest on Xperia Z1 compact with Android 4.4 and now 5.0.2) and I don't think it is specific to a certain application or Android version, it is just that OsmAnd isn't able to parse geo intents addresses. It would indeed be a *very* nice extension to have this feature as it would get rid of one of my last reasons to use Google Maps.
Looking at the URIs I guess though that it's not that easy as it requires some intelligence to parse such an address and detect what is country, city, zip code, street, etc... Perhaps a semi manual process would do as a first step?

**Comment by vshcherb** [comment]
We don't support yet search address string, only coordinates. This issue was already reported and that's why this one will be closed.

It is not planned for next release, because first we need to support search functionality.

**Comment by ericzolf** [comment]
Hi,
Thanks for the expansions. Can you perhaps document which ticket is a duplicate so that we can hook to it?
Thanks, Eric

On 10 September 2015 00:39:26 CEST, vshcherb <notifications@github.com> wrote:
>Closed #1614.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/osmandapp/Osmand/issues/1614#event-405376419

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by vshcherb** [comment]
https://github.com/osmandapp/Osmand/issues/1523
