### ISSUE TITLE
Routing issues for A2 and A7 Belgium

### ISSUE THREAD

**Issue by EugeneZmeuk** [osmandapp/OsmAnd#16174]
I left from the "tramlaan" in Sterrebeek" "Belgium" to go to Normandy Amiens.

1) on the first exit after entering France from Belgium. For several months in 2022 the police had cars exiting at this exit on the A2.
Since when I go to France the GPS makes me go out at this exit when I didn't ask for anything.

2) At Nivelles in Belgium the guidance on the A7 says to keep to the right but if you follow that you go towards Charleroi, in fact, you have to continue straight or say to keep the left but not to the right.

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/44466116/211023504-32fb1d60-3a8f-46f0-9095-d65d9096a617.png"  width="300" height="auto"/> </th>
 <th><img src="https://user-images.githubusercontent.com/44466116/211023448-ef60d1e6-eb34-4c25-8b43-88544aff0d2f.png"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by vshcherb** [comment]
Not exactly clear what's wrong please give route links somehow

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14086mqta, released: 2023-01-11

1. Not reproduced - Access is prohibited - that's why the detour on the route
[Map](https://drive.google.com/file/d/1JinIKxIdL2yvuvHaJw2syj26UBmDV4P8/view?usp=sharing)

[OsmAnd](https://osmand.net/map/?start=50.396773%2C3.615425&end=50.417021%2C3.630295&mode=car#16/50.4053/3.6226)
<img width="1206" alt="Screenshot 2023-01-11 at 22 02 19" src="https://user-images.githubusercontent.com/104760013/211906678-9909daf4-45a9-406d-9a1a-219018fe591a.png">

[OSM](https://www.openstreetmap.org/directions?engine=fossgis_osrm_car&route=50.4208%2C3.6342%3B50.3976%2C3.6152#map=14/50.4092/3.6201)
<img width="1206" alt="Screenshot 2023-01-11 at 22 02 08" src="https://user-images.githubusercontent.com/104760013/211906736-3040f93a-d12b-42b2-9299-80d774d186a6.png">

[OSM details](https://www.openstreetmap.org/way/429367528#map=18/50.40498/3.61932&layers=D)
<img width="1206" alt="Screenshot 2023-01-11 at 22 03 28" src="https://user-images.githubusercontent.com/104760013/211906757-fdd25ec4-692d-4859-9f4f-d00f33d529fd.png">

2. Not reproduced - Voice instructions as well as the direction of the arrow in the turn widget match the data on the map, but - **perhaps in such cases, it sounds like "Keep right" and the corresponding turn sign in the widget. Because when the user hears "Turn right", he may think that he needs to turn off the road**

`3. 50.61285° N, 4.29805° E`
[Map](https://drive.google.com/file/d/1lSysqBXT1bBtbIiRzGn_MSUmwX3r5WdJ/view?usp=sharing)

[OsmAnd](https://osmand.net/map/?start=50.612825%2C4.298015&end=50.572685%2C4.302821&mode=car#15/50.5874/4.3089)
<img width="1206" alt="Screenshot 2023-01-11 at 22 17 32" src="https://user-images.githubusercontent.com/104760013/211909008-66e0c27f-47d8-4649-9458-030fbcccb627.png">

[OSM](https://osmand.net/map/?start=50.612825%2C4.298015&end=50.572685%2C4.302821&mode=car#15/50.5874/4.3089)
<img width="1206" alt="Screenshot 2023-01-11 at 22 21 07" src="https://user-images.githubusercontent.com/104760013/211909742-84ef9bdb-bc14-4520-acad-eea438d9f626.png">


https://user-images.githubusercontent.com/104760013/211910520-6174d081-c62e-4ec8-8a1c-d23cdf18ada2.mp4
