### ISSUE TITLE
Data Storage UI: Group all wiki related downloads

### ISSUE THREAD

**Issue by brbar** [osmandapp/OsmAnd#16189]
Need to add "wiki" item to Settings -> Data storage folder -> OSMAnd usage in order to see how much storage my downloaded wikies took.

**Comment by vshcherb** [comment]
@sonora 
I think it's incorrect translation cause Travel Guides with Wikipedia icons is a Wikipedia maps not just Travel guides.

**Comment by brbar** [comment]
No, seems like you have two wiki related data types. One is a travel guides (from wikivoyage), and the other one is Wikipedia (when you open a country and see the optiins to download maps, countour lines and wikipedia stuff related to that country).

**Comment by sonora** [comment]
@vshcherb We have not resynced the `"Data storage folder" / size info screen` with all pur recent folder-restructuring. **I think in order to create clarity again, we should strictly**
- align the screen lines with exactly the folders,
- and show their respective total folder sizes, regardless of file type contained.

Just a few examples of current behavior(heuristically, have not checked the code):
- [ ] `"Data storage folder" / "Maps"`looks into
  - `<data folder>/root-WITHOUT-SUBFOLDERS`
  - `<data folder>/roads`
  - `<data folder>/backup`
  - `<data folder>/travel`
  - `<data folder>/wiki`
  - plus probably even more
- [ ] `"Data storage folder" / "Travel Guides"` looks into `<data folder>/travel` (but not all files in there...)
- [ ] `"Data storage folder" / "Hillshades / Slopes / Contour lines"` looks into
  -  `<data folder>/srtm` and 
  - `<data folder>/tiles (root-ONLY)`,
  - but not `<data folder>/heightmap`
- [x] `"Data storage folder" / "Tracks"` looks into `<data folder>/tracks`
- [x] `"Data storage folder" / "Audio/video notes"` looks into `<data folder>/avnotes`
- [ ] `"Data storage folder" / "Tiles"` looks into `<data folder>/tiles/<sub-folders-ONLY`,
- [ ] `"Data storage folder" / "Other"` seems to look into various places, e.g. non-travel files in travel folder.

**Comment by sonora** [comment]
PS: Here's how we currently cut it: https://github.com/osmandapp/OsmAnd/blob/bf894d5c36771a5e8d26ce4fed54dfcbc4a5d886/OsmAnd/src/net/osmand/plus/settings/datastorage/DataStorageHelper.java#L177

I think now that we use a **much more cleanly aligned folder structure**, it makes more sense to align these `memoryItems` with our folder structure to display the storage used by each.

**Comment by vshcherb** [comment]
@sonora Great

**Comment by sonora** [comment]
Ok, see my PR. I have tested and the storage sizes are ok with it.

I have also made the featured considerably more detailed, I think this is mandatory for transparency with the actual file system becoming more and more hidden for the majority of users.

![Screenshot_20230111-181255_OsmAnd~](https://user-images.githubusercontent.com/845735/211872456-ec8f164c-7153-4a41-973b-3b584933307e.jpg)

**Comment by dmpr0** [comment]
**Data storage folder** is made for view list of available storages with ability to change it. Currently it looks more like **Manage storage** screen. I don't see list of available storage when I open the **Data storage folder** screen in the latest nightly.
<table style="width:100%">
  <tr>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/9365308/214068728-33580b9f-3013-4851-8764-afca11c85b5d.png"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by sonora** [comment]
We could move the section "_Change storage folder_" to the top, i.e before section "_OsmAnd usage_".

However, I believe that the screen is much more used as the info screen to check on the current storage usage than to actually change the storage location (which is a one time occurrence in the lifecycle of the app installation, if ever...).

So that would point to best leaving this screen as is?

**Comment by vshcherb** [comment]
Nope this is too much information, of course simple fix could be to not displayed 0 KB sections.

Though I see several rename issues:
1. Deactivated -> Deactivated Maps
2. Wikipedia + Travel Guides  -> W Travel Guides
3. Maps + Roads only + Nautical Maps + OsmAnd Live -> Maps

**Comment by sonora** [comment]
True, I'm fine if we move a storage info screen of this granular degree of detail to a better place.

**Comment by vshcherb** [comment]
It was never designed to provide detalization especial of maps kind, 3 big groups of maps - SRTM / Online (custom) / Vector is enough, I think.

**Comment by sonora** [comment]
Would you accept a PR where I simply reduce this preference sscreen `Settings > Data storage folder` to the path selection functionality, and move the info section under a headline _OsmAnd storage overwiew_ to the bottom of screen `Download maps > Loca`l?

**Comment by sonora** [comment]
I certainly agree let's first wait for a concept by @dmpr0 on what screen or tab we would like the _Storage info_ screen to be located, then look into the implementation.

**Comment by sonora** [comment]
I've made the storage detail info collapsible and hid it by default. A rather low impact and easy solution https://github.com/osmandapp/OsmAnd/commit/ef0090485c9dd0a58d789c788d7cfaf895334add, acceptable?

**Comment by vshcherb** [comment]
Looks better but still weird. I'm not responsible for UI and definitely not going to make decisions collapsible or not collapsible depends on number of elements and future elements as I see.

Still the list above (slightly changed valid I guess)
```
- Deactivated -> Deactivated Maps
- Wikipedia + Travel Guides -> Wikipedia / Travel Guides
- Maps + Roads only + OsmAnd Live -> Vector Maps
- Tiles -> Raster tile maps
- Hillshade / Slope / Contour lines -> Height maps (1 more folder should be counted now)
- Nautical Maps
```

**Comment by sonora** [comment]
Ok, but as I said, _**there is value**_ in seeing the detailed distinction between e.g. _Wikipedia and Travel guides_, or _Hillshade / Slope / Contour lines_: To see exactly which group is eating up how much of your storage and to make a decision if that particular functionality is worth it for you or not.

And with the collapsed design there is now no penalty any more in having these details available?

**Comment by sonora** [comment]
Apologies, I just notice I may have deleted 2 comments above when adding the current screenshot which strangely appeared as duplicates on my device, but possibly that was a web site glitch. But I think they were referring  to deprecated status anyway.

**Comment by vshcherb** [comment]
To do: delete statistics as it's not needed in new screen.

**Comment by dmpr0** [comment]
# Review 

<details>
    <summary>Screenshot</summary>
<table style="width:100%">
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/fbcbb183-9aac-4b3b-8c32-c4d9b40b7ec5"  width="300" height="auto"/> </td>
  </tr>
</table>   
</details>  

- [ ]  Add card with Device memory from Download Maps – Downloads

**Comment by dmpr0** [comment]
## Doc
Screenshots need to be updated.

**Comment by DmitryAlexei** [comment]
Added new screenshots to the article Download maps (Local maps and resources screen)
https://osmand.net/docs/user/start-with/download-maps#local-resources

**Comment by sonora** [comment]
@DmitryAlexei Are the screenshots in line with our latest build? The one onosmand.net has e.g. a line "Terrain maps", and it is in 4zh place (even below Nautical maps), while my current OsmAnd build shows it as "Topography maps", and immediately under the Standard maps.

**Comment by DmitryAlexei** [comment]
@sonora thanks for review and feedback!
String names have changed last week, I will update screenshots.

The data types in the Resources section are grouped by the amount of storage they take.

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/b457e8c9-582d-4d08-b487-edd68d6d5173"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by EugeneZmeuk** [comment]
**16-04-2024 Review**
