### ISSUE TITLE
Allow to have default icon for a favorite group, so it keeps preselected from the map

### ISSUE THREAD

**Issue by brbar** [osmandapp/OsmAnd#16188]
**Steps to reproduce:**
* Select any restaurant
* Hit Add button to create new favourite
On that step you may notice that app automatically preselect correct icon (restaurant) for such poi - which is great
But if you want to use the other group (want to have a different color for that particular favourite item) you loose preselected icon which is unexpected.

The current behavior seems good for cases when we trying to add a favourite for an empty place on the map - when icon preselection is not appropriate.

**Comment by vshcherb** [comment]
This is related to default group appearance, we can allow special behavior for star favorite

**Comment by tradavyvy** [comment]
I think that when osmand desides what icon, color or shape a favorite gets it should always by default choose the settings of the group this favourite belongs to. 
Because that are the settings the user has chosen, and not the icon osmand itself uses for that poi.
For instance there are many different places you can swim: pools, beaches, lakes, springs, waterfalls ..... When I choose a specific icon and color for my favorite group 'swimming' I want all my marked favorites to look like that. This keeps the map clear and easy to interpret.
You could offer the 'osmand-specific' icon as first alternative choice on the settings-page.

A related item:
When moving a favourite from one group to an other group I think the icon and colour should change to the default settings of the new group.
But that might be a personal thing. Because in my use-case I tend to have 'uniform apearing' groups.

If opinions differ about what use-case is dominant / more logical. Maybe make it an optional user setting.

**Comment by vshcherb** [comment]
I think it's not a big issue cause you can always tap from Special and it will be the default icon of POI, so there is no need to have something special cause the use case is supported with extra click
