### ISSUE TITLE
Map mode Sunrise/sunset doesn't work

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd#16197]
### Description
Map mode Sunrise/sunset doesn't work - Night mode is activated only when Night is selected

### Steps to reproduce
Configure map > Map mode > Sunrise/Sunset > Change the time in the device settings (For example, 22:00 Kyiv time was set)

### Actual result
Map mode is displayed as Day, although the device settings were set to 22:00

### Expected result
Map mode is displayed as Night

### Your Environment
OsmAnd Version: OsmAnd~ 4.4.0#14082mqta, released: 2023-01-09
Android/iOS version: Android 12
Device model: Poco x3 nfc

**Comment by bhankerson** [comment]
I have the Sunrise/Sunset mode set on my app, too. OsmAnd always opens in Day mode and takes 2-3 minutes to realize it's nighttime and turn dark

**Comment by sonora** [comment]
@Zirochkabila Do you have a location fix? OsmAnd needs to know where you are to figure out sunrise/sunset.

**Comment by Dollarius** [comment]
> I have the Sunrise/Sunset mode set on my app, too. OsmAnd always opens in Day mode and takes 2-3 minutes to realize it's nighttime and turn dark

Same behaviour for me on Android 12.

**Comment by bhankerson** [comment]
@sonora That may be my issue. I allow location only while the app is running. I suppose it would increase loading time too much to have the app query location upon startup?

> @Zirochkabila Do you have a location fix? OsmAnd needs to know where you are to figure out sunrise/sunset.

**Comment by Zirochkabila** [comment]
> @Zirochkabila Do you have a location fix? OsmAnd needs to know where you are to figure out sunrise/sunset.

Yes, it was also tested with the location enabled - the result is the same

**Comment by Zirochkabila** [comment]
> @Zirochkabila Do you have a location fix? OsmAnd needs to know where you are to figure out sunrise/sunset.

Yes, it was also tested with location-enabled - with geolocation enabled it works
But, the night mode should be turned on automatically without geolocation too

**Comment by vshcherb** [comment]
It's not clear how it could work without geolocation. We probably could hard-code to 8:00 / 20:00

**Comment by bhankerson** [comment]
Could add a setting to define light and dark periods (I've seen that on other apps). Might be nice to have the bright white in the early evening, while keeping it dark might be preferable in the early morning

**Comment by bhankerson** [comment]
> @bhankerson No, the access permission has zero impact on the app startup time. "_While the App is running_" for the lcation permission is actually correct (at least under newer versions of Android, see e.g. [#12397 (comment)](https://github.com/osmandapp/OsmAnd/issues/12397#issuecomment-1007274041)). Most likely you are looking at some hardware-specific delay your device takes to get a location fix, this can be from a few seconds to a minute+, depending on hardware and environment.

@sonora Sorry, I guess that wasn't really what I meant. I know giving location permission doesn't affect load time. I more meant what would it take to have OsmAnd confirm Day/Night at startup?
Separate question: If I gave OsmAnd background location permission, would it always know whether it's day or night, and thus open in the right mode?

**Comment by sonora** [comment]
@bhankerson  Giving OsmAnd background location permission wouldn't do a thing, because (and on purpose) outside the app being in the foreground or the foreground service running (for navigation or trip recording) there is no process in OsmAnd to do anything, certainly neither to retrieve your location nor to trigger the sunrise/sunset calculation.

Regarding when do we actually trigger it: I think it's quite an expensive operation using some NASA astronomy code, and we restrict execution to once every 60 seconds or so to limit CPU load and power consumption. Maybe that's the delay you see. Not sure it should imperatively be triggered immediately upon app start (app start needs CPU more urgently for more essential tasks.)

**Comment by bhankerson** [comment]
Thank you very much for the honest and complete answers :)

**Comment by Dollarius** [comment]
In my case, this has nothing to do with the location: when I start the app, my position is already known (position arrow shown) and the correct sunset/sunrise times are already shown (in the widget).
Actually the correct sunset/sunrise times are shown even if my position is not yet known.

It takes more than 60s for the app to do the check and change the day/night map accordingly (as someone mentioned?).
Maybe an initial check could be performed, say 2-3s, after app start?

**Comment by sonora** [comment]
@Dollarius I  advise let's separate this. This issue here is about"_Night mode is activated only when Night is selected_", i.e. about the sunrise/sunset mechanism allegedly generally failing. I am trying to understand when this happens,  cannot currently reproduce, hence inquired if this is perhaps while there is no location known, potentially never was.

If you just see a 1 minute delay in the map's reaction to display the correct mode, let's open a separate issue and describe there how to reproduce (I currently cannot). Once I can, I offer to check our code, because we certainly cache some things, so may just have to locate under which condition the cached state is not adequate  or an additional cache recall may be needed.

**Comment by vshcherb** [comment]
I agree that it only could create additional problems then fix them
