### ISSUE TITLE
Duplicate area name at zoom level 11 only

### ISSUE THREAD

**Issue by arncor** [osmandapp/OsmAnd#16202]
### Description

Area name is present twice only at zoom level 11 at this particular location (north east of Lyon, France, coordinate in the screenshot).
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/91597340/211390314-abd84dba-d980-4d34-8df7-cbeb98151881.png"  width="300" height="auto"/> </th>
  </tr>
</table>  

### How to reproduce?

Go at these coordinates and zoom level 11
(edit: with OpenGL)

### Your Environment
OsmAnd+ Version: 4.3.5
Android/iOS version:9
Device model: Ulefone Armor 6E

**Maps used (online or offline):**   
Topo and offroad

Edit : same thing above Geneva at zoom level 10 & 11 
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/91597340/211407429-f9d0b84c-e87b-46cb-a3c3-4d8a9f35e996.png"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by TheSnoozer** [comment]
Can reproduce at 46.000° N, 5.035869° E.

![image](https://user-images.githubusercontent.com/6849390/211426957-9b4b17e2-f980-4eec-8e9d-d20d1783836f.png)

Only seems to be a problem with Map Rendering Engine V2 (OpenGL).

**Comment by arncor** [comment]
I just checked witk 4.4.3 and this bug is still present but now at zoom 10 & 11 and not only 11 like before.

**Comment by cepprice** [comment]
Unreproducible

**Comment by TheSnoozer** [comment]
Indeed, can't reproduce with 4.5.10.

**Comment by yuriiurshuliak** [comment]
The bug was not reproduced in the specified Dombes and Pays de Gex areas. The map doesn't display their names duplicated at zoom levels 10 and 11.

OsmAnd~ 4.6.0#781m, released: 2023-09-19

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/5888daa2-35dd-4af3-9052-be71923553c7"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/f8d37e93-355e-4713-be36-637e81a31cf9"  width="300" height="auto"/> </th>
  </tr>
</table>
