### ISSUE TITLE
Review Notification (Wearable / Smartwatches) code

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/OsmAnd#16310]
https://github.com/osmandapp/OsmAnd/commit/76a163fa8f49ce3eb5716461cdc2235a1089e41f
https://github.com/osmandapp/OsmAnd/commit/0183ac1885355c8d03b46b76488352bec339715c

**Comment by sonora** [comment]
Reviewing our code, I believe that my hint https://github.com/osmandapp/OsmAnd/commit/0183ac1885355c8d03b46b76488352bec339715c#commitcomment-97864585 about always calling for a _New_ notification builder may indeed be applicable here.

**Comment by vshcherb** [comment]
We need to find a way to block notification propagation to Garmin / Samsung
1. Doesn't work: Flags on Builder
```
	.setLocalOnly(true) // Probably should be deleted to not limit notifications
	.setOnlyAlertOnce(true) // Many devices still don't treat that flag correct and keep spamming
```
2. Doesn't work: reuse same instance of Builder

Currently we ran out of ideas what next to try.

**Comment by sonora** [comment]
I think for `.setOnlyAlertOnce(true)` to have an effect, the notification must already be showing. So do we use `setOngoing()` correctly? I see e.g, `.setOngoing(ongoing && !wearable)`, but the arguments may be wrong?

**Comment by vshcherb** [comment]
Well we can retest again all 8 combinations but I think we did it and it was not successful so far. 

In the end we didn't see any application which could update / display notification but disable it to broadcast to watches (except system apps)

**Comment by vshcherb** [comment]
Merged to https://github.com/osmandapp/OsmAnd/issues/16310

**Comment by sonora** [comment]
@vshcherb Regarding

> Merged to https://github.com/osmandapp/OsmAnd/issues/16310

This _is_ #16310, where did you mean to merge it to?

**Comment by ConradHughes** [comment]
Sorry to comment on this after closure, but this still seems to be a bug on 4.8.6, and an unexplained merge to 14406 doesn't make sense: I'm not recording new routes, I'm simply trying to follow OSMAnd's chosen route to a destination.

The bug is absolutely maddening, to the point that I now never press _start_ on navigation in a car, but merely watch my progress on the route preview until I reach my destination.

I think the "disable notifications" feature probably needs to be specific to different app profiles, since notifications at walking pace are useful, at driving pace they're insane, and at cycling pace I am yet to make my mind up, and sometimes (when I'm not in control) I just want to follow progress along the route without being told which way to go (I mean I *can't* turn left etc.).

**Comment by sTiKyt** [comment]
Still an issue with any ActivityWatch watches
