### ISSUE TITLE
Prefer unpaved roads function doesn't work

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd#16369]
### Description
When the Prefer unpaved roads function is activated, the route is built as if it was not activated
For example, the video in the Expected result shows a route with all the restrictions activated (this was done to be on the safe side. In fact, a similar route can be built only by selecting Avoid roads > No motorways) - route will be built in a completely different way

### Steps to reproduce
Navigation > Motorcycle profile > from `55.026256, 9.836190` to `55.775262, 8.409301` > Settings > Navigation settings > Route parameters > Prefer > Prefer unpaved roads > Back > Avoid roads > No motorways

### Actual result

https://user-images.githubusercontent.com/104760013/216075533-0b973182-2b87-4864-b8c5-065d0f6de1e6.mp4

### Expected result

https://user-images.githubusercontent.com/104760013/216076202-e80aecd8-6258-4106-afc0-d94aab5d3133.mp4

### Your Environment
OsmAnd Version: OsmAnd~ 4.4.0#14143mqta, released: 2023-02-01
Android/iOS version: Android 12
Device model: Poco x3 nfc

**Comment by Zirochkabila** [comment]
"No unpaved roads" https://github.com/osmandapp/OsmAnd/issues/16309 changes the route from asphalt roads to paved roads - the logic of the work is broken.
It seems that the logic of the Prefer dirt roads function, which routes through highways, is broken in the same way

**Comment by xmd5a2** [comment]
I wasn't able to test this route in OsmAndMapCreator because of huge memory consumption (?) but these options actually works as expected:
Motorcycle, avoid unpaved:
![Screenshot_2023-03-08_10-27-58](https://user-images.githubusercontent.com/5829014/223649155-560cb951-3fc4-47cc-991b-96a926a6cb07.png)
Motorcycle, prefer unpaved:
![Screenshot_2023-03-08_10-28-17](https://user-images.githubusercontent.com/5829014/223649212-3f36f4f7-3c68-4338-af5f-bfe310cd1d5c.png)

Looks like this is UI issue

**Comment by Zirochkabila** [comment]
@xmd5a2  Most likely, it is.
This is mentioned in this description (UI issue) https://github.com/osmandapp/OsmAnd/issues/16369#issuecomment-1427086223

**Comment by ivanPyrohivskyi** [comment]
Test with full efficient way property

**Comment by Zirochkabila** [comment]
I'm waiting for a reply
