### ISSUE TITLE
Rendering Engine v2 - With many Favorites the map and points rendering is slowly

### ISSUE THREAD

**Issue by EugeneZmeuk** [osmandapp/OsmAnd#16360]
### Description

For Rendering Engine v2 - With many Favorites the map and points rendering is slow. Each zoom or moves map repeats points slowly rendering.
For Rendering Engine v1 -  not reproduce.

### How to reproduce?

Switch on Favorites (500+ points for one area).
[favorites-oil points.gpx.zip](https://github.com/osmandapp/OsmAnd/files/10547040/favorites-oil.points.gpx.zip)

### Your Environment
Device : beyond0
Brand : samsung
Model : SM-G970F
Product : beyond0ltexx
Build : SP1A.210812.016.G970FXXUGHVJ5
Version : 12
App Version : OsmAnd~
Apk Version : 4.4.0#14139mqta 4400

**Maps used (online or offline):**

**Comment by Zirochkabila** [comment]
Probably related to https://github.com/osmandapp/OsmAnd/issues/15968

**Comment by derekvb** [comment]
I encountered UI freezes as well (see #16423 ). 

You asked me to provide the following information:

- Video behavior with Version 1 instead of OpenGL2: UI and rendering is much faster
- Data on the number of downloaded maps and their size: 4 downloaded maps (2.39 GB)
- Number of POIs and tracks displayed on the map: can't see how much but rendering and UI speeds improve drastrically when turning them off
- Whether you are using an overlay or an underlay: no overlay or underlay

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14189mqta, Released: 2023-02-20
Done
