### ISSUE TITLE
Pedestrian voice guidance oddity

### ISSUE THREAD

**Issue by PinkDuck** [osmandapp/Osmand#1636]
I heard the voice guidance say: "Turn left then after 0 metres turn right".
This should be simplified at the point of speech text creation to just "Turn left, then turn right".

Also, in terms of voice guidance if I set a car route whilst at home with location services on then hit go after calculation I hear the following voice guidance in one burst with little gap between sentences:

"Turn right on to Stratford Crescent then after 100 metres turn right. The trip is about 7 km. Time is 25 minutes. Turn right on to Stratford crescent then after 100 metres turn right."

This is a confusing amount of spoken text to hear at the start of the journey with statement duplication.

If I begin navigation before the route has been calculated then I do hear:
"The trip is about 7 km. Time is 25 minutes. Turn right on to Stratford crescent then after 100 metres turn right."

It would be fine just to hear "The trip is about 7 km and will be around 25 minutes. Turn right on to Stratford Crescent" in both cases.

**Comment by massic80** [comment]
Good idea!

**Comment by sonora** [comment]
I am not 100% sure, but I think some weeks ago I may have fixed the issue "Turn xxx. The trip is. Turn xxx" so that one of the Turn xxx prompts is not omitted We dis in deed have an issue of "crowded" repeated voice prompts when turns are close together, and it is not 10% fixed, but should be better now.
