### ISSUE TITLE
Currently recording track is not visible when the starting point is offscreen

### ISSUE THREAD

**Issue by ahgera** [osmandapp/OsmAnd#16380]
### Description
The red path showing the recorded track is not shown unless I zoom out or move the map until the track starting point is visible

### How to reproduce?
Start recording a track, move enough to be able to have to starting point offscreen

### Your Environment
OsmAnd Version: 4.3.10. 
Android/iOS version: Android 10
Device model: Xiaomi Mi 8

![osmand2](https://user-images.githubusercontent.com/34133296/216425593-36383cb9-e817-46d0-bc2d-4f49a889f98b.gif)
(The jerkiness is because of the gif encoding)

This was not an issue previously, I'm not sure if it's because of the new OpenGL renderer or something else in 4.3.10. The issue is only present during recording, when showing a previously recorded or imported track everything works as expected.

**Comment by KaiRo-at** [comment]
The issue is also present when using the v1 renderer, FWIW.

**Comment by sonora** [comment]
Could we merge the fix to master, please?

**Comment by vshcherb** [comment]
@sonora all 4.3 should be in master

**Comment by sonora** [comment]
Yes, but we are lagging behind - last merge of r4.3 to master was Feb 4.

**Comment by vshcherb** [comment]
There are conflicts, I've notified @cepprice

**Comment by FThlrz** [comment]
I have exactly the same problem

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14189mqta, Released: 2023-02-20
Done

**Comment by DmitryAlexei** [comment]
@endolith Please check, that map rendering engine Version 2 is enabled
- go to menu > settings > OsmAnd settings > Map rendering engine

**Comment by endolith** [comment]
Yes switching to 2 seems to fix it

**Comment by KaiRo-at** [comment]
Also, some of us, like those with Fairphones (including the FP5) do not have enough performance to run version 2 decently and need to stick to version 1. Not everyone has high-end phones.

**Comment by sonora** [comment]
We first had his in 4.3.x, and it was fixed in 4.4:
- This issue (#16380)
- #16947

Then again it seems in 4.9.x:
- #21193
- #21266
- Similar, but probably differeent and unrelated: #21675

But I am using (with rendering engine V1) v5.0.4, the current beta, not yet published as full release, **and I cannot reproduce any more**. Perhaps anybody having this can try the current beta, nightly, (or non-beta 5.0.x when it comes). Should it still occur for you on any of these 3, zI suggest to open a new issue about it.
