### ISSUE TITLE
Ant+ sensors added, but there is no "tick" box for "temperature (Garmin Tempe) in the sensors overview

### ISSUE THREAD

**Issue by Cargotourer** [osmandapp/OsmAnd#16522]
### After the two recent updates, there is now support for ant+ sensor, but there is no "temperature" in the "plug in selector". I would like to use my Garmin Tempe sensor. 

Osmand+ 4.3.12

Android 13, Galaxy Xcover Pro,

**Comment by Zirochkabila** [comment]
We need to add a sensor because the Garmin Tempe sensor supports ANT+ technology. 
The Garmin Tempe is a temperature sensor that is designed to be used with compatible Garmin devices such as watches, cycling computers, and other devices. 
It uses ANT+ technology to transmit temperature data to your Garmin device.

**Comment by dmpr0** [comment]
## ToDo
- [ ]  Add support for temperature sensors, both BLE and ANT+

**Comment by Cargotourer** [comment]
Thank you. Will do.
