### ISSUE TITLE
access=no incorrectly handled with "live updates"

### ISSUE THREAD

**Issue by aceman444** [osmandapp/Osmand#1653]
On current Nightly of Osmand 2.2:
1. download map of Slovakia, date 7th Aug 2015.
2. download live updates to Slovakia.
3. put destination on road 1770 at https://www.openstreetmap.org/#map=23/48.711252879617426/18.25446041234846
4. put starting point on road 1770 at https://www.openstreetmap.org/#map=23/48.711252879617426/18.25446041234846

Result:
Calculated route will use road on way 368690669 which has access=no and OsmAnd should have routed around it.

I changed the road to access=no recently, but I think it is picked up in the map updates because there is also the FIXME that I added at the same time.

**Comment by hakuchi** [comment]
OsmAnd/you using Slovakia map from 08.2015 and you have edited the road with access=no on 09.2015

Maps from August don't have edits from September inside!

:grey_exclamation:This is no BUG from OsmAnd:grey_exclamation:

PS: Wait 2-3 Days and new mapupdate from 09.2015 is online to download. With closed road set from you.

PPS:  :pray: please use "brain 1.0" :pray:

**Comment by vshcherb** [comment]
It will be good to check, "Live maps" is available only in the nightlies, so it doesn't affect any stable release yet. Live updates available every 2-3 hours

**Comment by Zahnstocher** [comment]
@hakuchi 
aceman444 is talking about the new "live updates", which provides map updates (delta) about every 3 hours.

**Comment by aceman444** [comment]
Yes, correctly, it is the dev version of OsmAnd nightly (2.2). I did edit that road and added access=no and a FIXME after the last full map updates. Then I ran live updates on the country. The updated map does contain the FIXME so I assume the access=no is also there. But routing is ignoring it. In OsmAnd stable 2.1, with new full maps of 2015-09-07 the access=no is properly honored and routed around.

**Comment by vshcherb** [comment]
I think main issues with osm changes are fixed. Though there is the biggest issue and we decided to disable the osm live for routing. Main issue happens with a road move for more than 100m with same id, basically they are kept together in the big file, but at different tiles, and mislead routing which reads file incrementally tile by tile. Which leads us to another solution that none of the roads could change geometry they could only be deleted or added it is possible to implement with new_id = (id, version), so then every change will be unique. That requires quite a big change and we decided to take a break here before a release.

This issue is closed cause it is no longer valid (it is not implemented) and we know that's a limitation today but we are planning to fix it soon.
