### ISSUE TITLE
Gray screen

### ISSUE THREAD

**Issue by Gizmot** [osmandapp/Osmand#1685]
Using latest version 2.1.1, HTC Desire 510
Note that this is different from the white screen crash cause by screen rotation. When this happened, phone was firmly in the cup holder.
![screenshot_2015-09-10-19-50-47](https://cloud.githubusercontent.com/assets/13919997/9834703/2e637492-5995-11e5-9d8e-c953361dfec4.png)

**Comment by vshcherb** [comment]
This is an issue, which we didn't manage to catch and to reproduce yet. If we are not able to reproduce it, unfortunately it is impossible to fix it. We need to work together somehow to understand what is the root.

How long did you drive before it crashes, is it possible to restore the map view without app restart and any other information which could help to understand the situation

**Comment by Gizmot** [comment]
Happened twice on an HTC desire 510 and on a Samsung Galaxy s3. Both times while driving along a long highway with no interaction in a cupholder. My first guess was some sort on bug related to power saving or standby.
I believe navigation was still working since it was still barking directions. I tried to get the map back (scrolling, zooming, menus, etc) but had to completely reboot the app.

**Comment by Gizmot** [comment]
Happen again today on both phones. 
It happened once when navigating in smaller roads in California (after about 10 min after leaving). I guess this eliminates the long wait theory.

**Comment by Gizmot** [comment]
I'm real close to it.
I did a lot of testing going around Los Angeless running 2 phones at the same time. 
1. LA is crashing the phones a lot more than other places
2. Always seems to happen at highway speed
3. Navigation is always on.
4. Happened a lot more on the Samsung phone. (polygons are on! remember that bug report someone dismissed?)

Also, I managed to restart the map once or twice by waiting, no need to reboot the application.
But the application was mostly unresponsive.

I do not have metrics to prove it, but I'm 90% sure the issue is the application overload either the CPU, GPU or memory and half freeze the application (map display). Sometimes, the whole thing totally freeze. Just need to figure out how to log power use on an Android phone...

Looks like in a big city with a lot of streets,

**Comment by sonora** [comment]
Gizmot, Victor,

not very conclusive evidence from my side here, but the only 3 occasions
when I encountered this (quite a long time ago) was in Las Vega, Phoenix,
and Rome/Italy, so always very big cities. Always when navigation was on,
and on 2 occasions on Samsung, once on an htc phone. But this was >1 year
ago, and have not seen it ever since at all. Could  never reproduce.

Best, Hardy

**Comment by asd-and-Rizzo** [comment]
I has this frequenly on samsung galaxy 5. Sometimes same time I change horizonal vertical position of phone. Downgraded to 1.9.x where thing are gine.

**Comment by asd-and-Rizzo** [comment]
I bought official app on gplay pre 2 era. Will donate few more if 2.x will become stable on my samsung galaxy s5 and be ensured that really do not need exit button.

**Comment by Gizmot** [comment]
Going trough the US Northeast, crashed twice while in NH and Maine.
Both time, could be a simple coincidence:
1. "You are going above the speed limit"
2. Immediately after, " turn right"
- I was going at low speed in tiny towns in the middle of nowhere, so that kills my previous theory again.
- Once the whole phone freezed, had to pull the battery, second time I got:
![screenshot_2015-10-06-00-26-52](https://cloud.githubusercontent.com/assets/13919997/10300691/d83d8a86-6bc7-11e5-9b61-e672dfc6f5b3.png)

**Comment by slackline** [comment]
I've had this happen to me twice now (mistakenly reported it as a new bug as I'd not found this one).  I can't remember the first time, but the second time was only three days ago and was whilst navigating B and A roads in South Wales.  Not heavily residential area, but lots of twists and turns in the road and had been using navigation for around 10-15 minutes.

Using OSMAnd+ 2.1 under Android 5.1 on a Samsung Galaxy S4 (GT-i9505).

Will try and report more details if/when it happens again and see if I can extract anything from CatLog.

**Comment by Barrocas** [comment]
![screenshot_2015-10-21-16-05-14](https://cloud.githubusercontent.com/assets/4006691/10650634/7317de36-7842-11e5-8986-21b08dcd4ba5.png)

This happened today, with the night build from today, but I have seen this several times before with other builds.

This happens when I am navigating, and receive a phone call. I answered the call, the phone goes dark while talking, and when I unlock it, it's just a grey map.
Navigation keeps working, and issuing voice warnings, but no map, so it's not good.
On ocasions, jumping out of the app and returning gets the map on again.
Other times I have to force close the app to get it to work again.

Today, I pushed the back button to exit to the home screen, and when clicked on the app again, it was way zoomed out, like this:
![screenshot_2015-10-21-16-05-36](https://cloud.githubusercontent.com/assets/4006691/10650653/8679e5dc-7842-11e5-9848-03f28fbea476.png)

Using a Bq Aquaris E6 with android 4.4.2.

**Comment by CJTmmr** [comment]
Hi,

With my device (Samsung Galaxy Camera 2, EK-GC200, on Android 4.3) I had the same gray screen and OsmAnd not/slowly responding.

It appeared that a Android-setting (Energy-saving) was causing the problems.
Goto Android Settings, More, Power Supply, Power Saving.
There is a CPU-Setting: limit maximal speed of CPU
Turning this Off - all rendering was quick en smooth again.

Maybe this can help.

CJTmmr

**Comment by oopen** [comment]
Same problem (grey screen after a call with headphone), on a new install of OsmAnd~ 2.1.1 (FDroid & Android 5.0).
The map is replaced by a plain grey background, but GPS work (speed, satellites, directions, menus parameters .. all work) just no map. Hide & show app didn't refresh the map; forced kill process.

**Comment by Gizmot** [comment]
After I turned down OpenGL rendering in OSMand and power saving in Android everything started working fine in OsmAnd~ 2.1.1. Just upgraded to 2.2.4 and back to the old crash party.

I included the exception file. You can look and today multiple crashes
[exception.zip](https://github.com/osmandapp/Osmand/files/97961/exception.zip)

**Comment by sonora** [comment]
Is this deprecated, or still existent?
