### ISSUE TITLE
Pedestrian area navigation not working even on the border

### ISSUE THREAD

**Issue by ceever** [osmandapp/OsmAnd#16850]
### Description
So, I understand from #16714 that no diagonal navigation on areas for pedestrians is possible with OsmAnd and instead it just uses the border of the area. Nevertheless, even then it does not use to most direct way but instead sometimes to most indirect one, see screenshot:

![Screenshot_20230330-191745_OsmAnd~ sml](https://user-images.githubusercontent.com/40247591/228931055-a5767cdc-ee9c-4660-b063-5a805fcf4e7c.jpg)

### Steps to reproduce
1. Find a pedestrian area
2. Start navigation outside and end somewhere inside along the border but clockwise closest to the point where the starting way would hit the area first
3. Note that it navigates counterclockwise instead the longest path, instead of the more direct one

This might though depend on which direction the areas border is pointing.

### Actual result
Took longest path along a pedestrian area border to the destination

### Expected result
Takes shortest path along a pedestrian area border to the destination

### Your Environment
OsmAnd Version: 4.3.12
Android/iOS version: 9
Device model: Galaxy S8

**Comment by scaidermern** [comment]
The reason is not a broken routing along the edge of a highway=pedestrian area. Instead, the reason is this gate: https://www.openstreetmap.org/node/5107077473

The gate is tagged with foot=no and it is part of the steps _and_ the pedestrian area. This is probably a minor mapping mistake. I'm going to fix this.

You can see a similar routing behavior of OSRM:
https://www.openstreetmap.org/directions?engine=fossgis_osrm_foot&route=28.23719%2C-16.84393%3B28.23846%2C-16.84521#map=19/28.23751/-16.84394

And another weird one from Valhalla:
https://www.openstreetmap.org/directions?engine=fossgis_valhalla_foot&route=28.23719%2C-16.84393%3B28.23846%2C-16.84521#map=18/28.23744/-16.84355
GraphHopper instead jumps from behind the gate right to the border of the pedestrian area and then even ignores the gate completely:

https://www.openstreetmap.org/directions?engine=graphhopper_foot&route=28.23719%2C-16.84393%3B28.23846%2C-16.84521#map=19/28.23789/-16.84461

**Comment by ceever** [comment]
Well, I imagine there can be some pedestrian areas where certain ways would be closed, e.g. because their are private and lead to private properties or such. It would be terrible if the routing would always fail at those node.

In general the routing should not at all take into account such nodes if the pedestrian area is freely accessible, because the border is not really the definition of the area, but the area itself is. If there is a inaccessible node, I can just walk around it if the area permits it.

Cheers

**Comment by scaidermern** [comment]
Yes, this is definitely a valid point.

**Comment by Zirochkabila** [comment]
@ceever Most likely, @scaidermern  made changes. 
Because the route was built along the shortest route.
`28.23923° N, 16.84573° W`
OsmAnd~ 4.5.0#14290mqta, Released: 2023-04-03
Map 01.04
Profile settings - default

Can we consider this issue closed?

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/229554145-a4d25731-a395-43c6-bacf-0584dc3ed36f.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by ceever** [comment]
If it is an app change, not a map change, then I guess it is working correctly. 🙏

**Comment by scaidermern** [comment]
I just did some map improvements. No app changes from me.

**Comment by Zirochkabila** [comment]
@ceever I mean, about changing the map. But as you can see on the screenshot, the route is built differently

**Comment by ceever** [comment]
I think the issue was with a gate which was along the border. I don't know whether your example covers the gate. But if you say it is fixed, then it probably is. I don't have the new app yet, always takes a while to come around.

**Comment by scaidermern** [comment]
Again, no code change so far (according to my knowledge at least).

**Comment by ceever** [comment]
My bug was for OsmAnd not OSM. The idea was not to mess up OSM to cover for a shortcoming of OsmAnd. OsmAnd is not the only app using OSM. It also does not cover other similar examples. And I guess we don't want to correct all these examples now.

I am fine with the shortcoming of not being able to navigate across areas, but if the compromise is not working either, it is not really a compromise, is it?

**Comment by scaidermern** [comment]
I see your point (and I'm not an OsmAnd developer anyway, so I can't decide anything here).

However, I'm still convinced that this was a mapping error. It wouldn't have been one if area routing was working in general. But as you can see with the previous examples, other routers have the same problem. As long as proper area routing isn't supported by most routing engines the map data must ensure that routing along the border of pedestrian areas is possible.

If you want this bug (ignore gates at the border when routing along it) to be fixed the routing engine then as a consequence you will have to file the same bug report for these other routing engines.

**Comment by ceever** [comment]
So you are saying, if all tools are bad equally, someone else should take the first step to improve the situation, but not OsmAnd?

Otherwise, I don't see it as a mapping error – the gate has its proper position there. It is just the workaround implemented for areas that is not functional. Why not just ignore anything along the way, except for when it is part of the specification of the area or when swapping from area to path or the other way around?

Either way, you are the developers, it is your decision what you deem reasonable to implement or what not. I can just ask for an improvement. If you cannot and do not want to change the situation, then just close the bug.

However, what I will certainly not do is to mess up OSM because some tools are not functioning properly. I don't seem to remember any such specification in the OSM wiki to create workarounds for this or that tool.

**Comment by vshcherb** [comment]
for now pedestrian area aare not properly supported so this issue could be considered as duplicate. once main issue is fixed this might be invalid
