### ISSUE TITLE
Routes unexpectedly calculated for pedestrian mode

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#1688]
This might be on purpose, but I still think it creates unexpected results: Under certain circumstances, I think when using "Directions from"  and the route distance is below some threshold, OsmAnd seems to silently jump to calculating the route for pedestrian mode.

While this may easily remain undetected (which is not good), what is even worse is that once this happened, the pedestrian mode seems to remain the default route mode even for later longer and or "Directions to" routes (until a fresh app star resets this behavior).

I think we should not make this unpredictable and in all ceases use car mode as the default route mode unless (until) a users has previously explicitly chosen differently

**Comment by Zahnstocher** [comment]
Seems to be this commit:
https://github.com/osmandapp/Osmand/commit/f4d98743f9a1d39e11df6dbaa2b720727aa54bae

**Comment by sonora** [comment]
Right, that's it, it seems!

Good intention maybe, but very intransparent and unpredictable ...

**Comment by vshcherb** [comment]
Yes I believe it could help, now we know what are the constants are used. The main improvement in the commit to save previous application mode used ! Which helps a lot on the other hand, this prediction could be wrong if the distance is too big for pedestrian or too small for car. I think later we can remove that override rule if it causes too many questions. What I think we definitely should show every route calculation, it is a transportation selection. So that top bar should be always visible and it could be 1 click to switch it.
