### ISSUE TITLE
Speak street names in selected language

### ISSUE THREAD

**Issue by bparmentier** [osmandapp/Osmand#1690]
In Brussels, almost all street names are tagged in the following format:

    name=Rue de la Loi - Wetstraat
    name:fr=Rue de la Loi
    name:nl=Wetstraat

As you can see, the main `name` tag combines French and Dutch names.

When navigating with OsmAnd, the French voice then says things like "Tournez à gauche sur Rue de la Loi - Wetstraat" (*Turn left on […]*) instead of just "Tournez à gauche sur Rue de la Loi". 

Wouldn't it be better to take the user language into account and use the appropriate tag when it exists?

**Comment by RicoZ-OSM** [comment]
This seems special to countries with several official languages.. I assume the wrong pronunciation is the biggest problem here?

Generally Osmand should announce what is visible on the street name tables - what do these look like? Are there 2 names bellow each other?

**Comment by RicoZ-OSM** [comment]
see also https://github.com/osmandapp/Osmand/issues/1617

**Comment by vshcherb** [comment]
I agree with proposed approach, we need to speak street names exactly as they are visible and configured via "Configure Map" setting and preferably using different TTS

**Comment by vshcherb** [comment]
I think first part is already working, so only #1617 is left

**Comment by keunes** [comment]
> I think first part is already working, so only #1617 is left [ @vshcherb ]

Nope (assuming this is about pronouncing street names as displayed on map). Just tried:
- OsmAnd voice set to Dutch // map labels: local names // result: street names in audio instructions are pronounced as on map (incomprehensible French, then Dutch)
- OsmAnd voice set to Dutch // map labels: nl // result: no audio instructions at all (speech synthesis tested ok via OsmAnd's developer options)
- OsmAnd voice set to French // map labels: fr // result: no audio instructions at all (speech synthesis tested ok via OsmAnd's developer options)
- All on Fairphone 2, Android 5.1, Brussels city centre, using Google's TTS engine

---

Sharing an insight:
> we need to speak street names exactly as they are visible and configured via "Configure Map" setting

IMHO, this  doesn't necessarily always make sense, esp in a truly bilingual city (like in Brussels)
A) I always want to have 'local names' displayed on map (in Brussels often FR - NL). Why? Because if someone asks me directions I want/need local names are necessary to actually be helpful (or when I'm abroad and I want to navigate easily).
B) When navigating (especially on my bike when I solely rely on audio description) I want to have names only in the language used for navigation (as it increases clarity of instructions)
However: I see it is impossible to have both B) *and* #1617 implemented, as long as OSM does not differentiate between 'official translation' (e.g. the case in Brussels) and 'localised maps' (e.g. often done for major cities throughout the world).

**Comment by rriemann** [comment]
Hey @keunes , have you found a solution for bike navigation in only one language? I work in Brussels and encounter the same problem.
