### ISSUE TITLE
Render style addon rewrite custom rendering style

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd#16914]
### Discussed in https://github.com/osmandapp/OsmAnd/discussions/16699

<div type='discussions-op-text'>

<sup>Originally posted by **cricri-du-lauragais** March 14, 2023</sup>
hello, since version 4.4.1 (and maybe version 4.4.0) the addon styles (xxxx.addon.render.xml) overwrite the definition of the elements in the personal styles (custom render).
if you disable or delete the xxx.addon.render.xml, the standard styles do not display the elements anymore (normal)
and at each update the xxx.addon.render.xml are reloaded.
how to manage these addon.render.xml which we can't change the name, can we create specific ones linked to a particular custom style ?
or choose if a personal style can avoid them ?</div>

**Comment by dmpr0** [comment]
Provide full feedback about what need to be tested, what is works.

**Comment by ivanPyrohivskyi** [comment]
[Enduro style](https://github.com/OsmAnd-Rendering/Motorcycle/blob/main/enduro.render.xml) is works:

Legacy/OpenGL:
<img width="400" src="https://github.com/osmandapp/OsmAnd/assets/1040293/1579c0f0-48b7-408c-a068-4f64b8850488" /> <img width="400" src="https://github.com/osmandapp/OsmAnd/assets/1040293/a8c87f5f-1198-4a2d-ac59-addd58a1d8ec" />

**Comment by ivanPyrohivskyi** [comment]
For OpenGL xxxx.addon.render.xml are loaded after base style (default or custom).

1. [Read addons in Java](https://github.com/osmandapp/OsmAnd/blob/e81c55c0d4343b52fbf60cbdc9c4690ab57c7fbc/OsmAnd/src/net/osmand/core/android/MapRendererContext.java#L176), data is write to C++ from bytes array, stored in object of class UnresolvedMapStyle
2. Init addons after base style [Java](https://github.com/osmandapp/OsmAnd/blob/e81c55c0d4343b52fbf60cbdc9c4690ab57c7fbc/OsmAnd/src/net/osmand/core/android/MapRendererContext.java#L187) and [C++](https://github.com/osmandapp/OsmAnd-core/blob/95b1f1aa7dac59cb0aebcee40abdc4daa9f9d5b2/src/Map/MapStylesCollection_P.cpp#L166)

This [PR 16919](https://github.com/osmandapp/OsmAnd/pull/16919) because we read addons after initializating of map styles, that was wrong (wasn't work hiking routes, contour lines etc.).

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.5.0#90m, Released: 2023-05-25
If setting the **Contour line width to Default** and using [this](https://github.com/osmandapp/OsmAnd/files/11566284/34Customized.render.xml.zip) style, the contour lines are not displayed, although numbers are displayed. If increase the thickness, contour lines are displayed
When enabled the [that](https://github.com/osmandapp/OsmAnd/files/11566290/Enduro.style.xml.zip) style and set **Contour line width to Default**, the lines are displayed


https://github.com/osmandapp/OsmAnd/assets/104760013/5b1fbf54-70cb-476e-a0b9-02145f092ae3

4.4.8.16 - works fine
