### ISSUE TITLE
support for class:bicycle

### ISSUE THREAD

**Issue by RicoZ-OSM** [osmandapp/Osmand#1693]
http://wiki.openstreetmap.org/wiki/Class:bicycle

Maybe something like this would work?
```
	<way attribute="priority">
....
....
			<select value="0.05" t="class:bicycle" v="-3"/>
			<select value="0.2" t="class:bicycle" v="-2"/>
			<select value="0.4" t="class:bicycle" v="-1"/>
			<select value="1.5" t="class:bicycle" v="1"/>
			<select value="2.0" t="class:bicycle" v="2"/>
			<select value="3.0" t="class:bicycle" v="3"/>
```

**Comment by Zahnstocher** [comment]
First you have to get class:bicycle (routing_type) into the obf file:
https://github.com/osmandapp/OsmAnd-resources/blob/master/obf_creation/rendering_types.xml

rendering_types.xml:
First match counts.

Values should not be much higher than 1 (2.0 and 3.0 are to high), otherwise A* algorithm will not work correctly.

**Comment by vshcherb** [comment]
We have double check in the code, so if the end value is more than > 1, it will round it down to 1, so it won't have any effect. Please try to change routing.xml in MapCreator and once you see the difference and satisfied with results please provide a patch. 

Please feel free to ask, I think aceman is mostly doing tweaking coefficients for bicycle routing, so you might want to review latest pull-requests.

**Comment by Zahnstocher** [comment]
@RicoZ-OSM

Sorry this was wrong:
> rendering_types.xml:
> First match counts.

It should have been:
> routing.xml:
> First match (select) counts.

**Comment by Zahnstocher** [comment]
@vshcherb 
> We have double check in the code, so if the end value is more than > 1, it will round it down to 1, so it won't have any effect.

I can't confirm that.
Just did a test in bicycle mode, 3.05 km on a highway=path (speed = 12 km/h) with bicycle=designated (priority (= accelerator) = 1.4):

Time shown to the user (this is the time without priority weighting):
15 min (3.05 km / (12 km/h) = 0,254 h ~ 15 min)

Routing engine time (shown in toast message, if development plugin is enabled):
11 min (3.05 km / (12 * 1.4 km/h) = 0,182 h ~ 11 min)

time ratio: 15/11 ~ 1.4
Thus the priority has full effect of 1.4 (not just 1.0).

**Comment by vshcherb** [comment]
It doesn't break A* algorithm, but it could affect the routing. For A* algorithm there is a limitation
speed * priority <= max_defined_speed. 
That's why in bicycle mode it is quite unnecessary to put priority 1.5 to cycleway, cause 
cycleway_speed = 18 
18 * 1.5 = 24 > max_cycleway_speed = 18, will be rounded to 18 anyway.

But for speed <= 12 it will make effect of course
