### ISSUE TITLE
Change / Default appearance for selected tracks

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd#16943]
### Description
Showing start and finish icons of a track affects the appearance of the entire track

#### Steps to reproduce

* Create two tracks with different colors
* Open **Configure map** - **Tracks** - Select previously created tracks
* Tap on **Menu** in **AppBar** and then **Change appearance**
* Change value for **Show start and finish icons** > 

#### Actual result
* Color of all tracks, as well as other appearance features, have been changed to the standard ones

https://user-images.githubusercontent.com/104760013/230931666-43fd1418-b10e-4b3b-88bd-7f70c5d52534.mp4

### Expected result
**We should agree with @dmpr0  on how to implement this**

But, it would be nice if the changes in the appearance of the tracks applied only to those elements of the track that were changed - the rest of the elements (width, color, etc.) remained unchanged.

### Your Environment
OsmAnd Version: OsmAnd~ 4.5.0#35740m, Released: 2023-04-10
Android/iOS version: Android 12
Device model: Poco x3 nfc

**Comment by sonora** [comment]
Looking at other software: Ideally the formatting dialog would, for any property, detect and indicate if all selected elements have the same value for that property or different ones. E.g. for property 'colorr' either one color would be circled (perhaps using a bold circle) or several ones (using thin or dotted circles,  to  make the user aware. Changing that particular property, e.g. by tapping a color, would subsequently apply it to all selected objects. Not tapping that property would leave it untouched for every object.

**Comment by cbrog** [comment]
When importing a set of tracks into the app, recent versions of the Osmand+ app for Android are now by default showing start and finish icons at the ends of each imported track. This is problematic because the start and finish icons obscure the map, especially when there are large numbers of tracks. In versions of the app prior to the recent 4/7/23 version, one could get around this by going to menu > My Places > Tracks > selecting a set of tracks > selecting the color palette icon (Appearance) > deselecting the toggle slider for "Show start and finish icons" > and the start and finish icons would be hidden and nothing else about the tracks would change. However, in the recent 4/7/23 version of the app, going through the above outlined menu steps results in differently colored tracks being changed to a single color, thereby losing the tracks' color-coding information.

To solve this issue, I would like to suggest one or both of the following fixes to the app, which would return the app to how I believe it worked in previous versions:

(1) Change the app's default setting so that when tracks are imported into the app, the app does not automatically show start and finish icons by default for the imported tracks. In other words, change the app's default setting so that when tracks are imported into the app, the app's default setting is for start and finish icons to be hidden for the imported tracks. This would allow users to avoid having to manually hide unwanted start and finish icons and end up having differently colored tracks changed to a single color in the process. For users who want start and finish icons to be shown for tracks, they could do so via the menu.

(2) When making changes to the appearance of a set of tracks, go back to making it possible to change one aspect of appearance (such as removing start and finish icons) without forcing other aspects of appearance to change (such as color).

**Comment by vshcherb** [comment]
@sonora that's fine but not obvious - actually UI should be more comprehensive i.e.
- Color section should have "extra color" - "As is"
- Width section should have "extra value" - "As is"
....

So you see what you get without relying on software.

**Comment by dmpr0** [comment]
Related https://github.com/osmandapp/OsmAnd/issues/13454

**Comment by dmpr0** [comment]
## ToDo

<details>
    <summary>Overview</summary>
<table style="width:100%">
  <tr>
    <th>Overview</th>
    <th>Color</th>
    <th>Direction arrows</th>
    <th>Width</th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/7bd11f3a-d2b8-4a4d-9cad-b397afd4fa6f"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/93f9cd56-181a-4aba-b3c9-429c93a22a17"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/31cc4dfb-2c4a-495a-937c-b0ea1b9bccd8"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/b9cf8d55-7f3b-4cc1-98c0-29899a13061b"  width="300" height="auto"/> </td>
  </tr>
</table>   

</details>

**Comment by dmpr0** [comment]
## ToDo

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th>Change appearance</th>
        <th>Default appearance</th>
      </tr>
      <tr>
        <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/c4817b2a-e742-40fc-8210-e40248dedbc7"  width="300" height="auto"/> </td>
        <td><img src=""  width="300" height="auto"/> </td>
      </tr>
    </table>   
</details>   



### Default appearance
Access it through folder menu > Default appearance
* By default, all parameters are set to **Original**. This means that when a track is imported right into the folder, all appearance parameters will be the same as in the track file.

### Change appearance
Access it through selection mode by selecting a few tracks > Menu > Change appearance.
* By default, all parameters are set to **Unchanged**.

> Original vs Unchanged 
**Original** parameter value is stored in the track file; OsmAnd doesn't rewrite it, and it can be used after resetting appearance to its original state.
**Unchanged** means the state of the parameter while group appearance editing. Parameters (for example color) would not be changed during the current editing session.

**Comment by nazar-kutz** [comment]
## Key Questions
_**1. Determining Track Parameter Values**_

The question revolves around determining when to use parameters from the **Track** versus those from the **Default appearance**.

@vshcherb suggested the following sequence of checks:

1. Firstly, check the Track appearance from the **Tracks Database**.
2. If a particular parameter (e.g., color) isn't found in the Track Database, attempt to retrieve it from the **"Default Appearance"** for the folder where the track is located.
3.If the folder also lacks this overridden parameter, check extensions in the **GPX file**.
4. If no related extension is found in GPX, then use a default value provided by OsmAnd (e.g., use "red" color to draw tracks by default).
In short, the algorithm is:
Check **"Track Database"** -> check **"Default appearance"** for the folder of the track -> check **GPX file** extensions -> use some **default value** if the previous steps did not yield results.

**_2. Ability to Reset Specific Track Parameters to Default_**

This raises an issue related to the prior point; if we wish to revert a certain parameter to its default appearance, it's necessary to provide an ability to reset this parameter to its default value for a specific track.

Currently, when editing a track via **Track Appearance** dialog, this isn't possible. This means that once a track parameter is edited (e.g., color changed), we can't revert to the color from the **Default Appearance**.

To solve it, we can add a "default" option to each parameter (e.g., color, width, etc.) usable on the Track Appearance screen. Selecting this option will clear the current value stored in the database for a particular track parameter.

**_3. How should the program handle subfolders regarding the usage of Default appearance?_**

Should subfolders be allowed to have their unique Default appearance, or should this ability be restricted to top-level parent folders placed in the root folder "tracks/"? How should this operate in general?

**_4. Appearance of Split Marks Card_**

What should the Split Marks card look like on the Change and Default Appearance screens? Should we continue using the bottom sheet to select the interval and track split type, or can we instead utilize a card resembling the "Width selection" component?

**Comment by cbrog** [comment]
I have quietly watched the thread on this issue for nearly a year now, hoping for progress on either of the 2 issues I initially raised in my Apr 10, 2023 comment above:

(1) Change the app's default setting so that when a set of tracks is imported into the app, the app does not automatically show start and finish icons by default for the imported tracks.

(2) When making changes to the appearance of a set of tracks, allow the user to change one aspect of appearance (such as hiding start and finish icons) without forcing other aspects of appearance to change (such as color).

So far, all the attention in this thread appears to have been focused on issue (2), which seems to have grown in complexity and is taking a long time to resolve.

I would like to humbly and respectfully ask (please, I'm begging!) that attention be focused in the more immediate near term on issue (1), which I imagine would be a relatively "quick and easy" fix. From my perspective, fixing issue (1) would solve the problem I have and make issue (2) irrelevant, from my perspective at least.

Thank you very much for your help!

From a longtime user who relies on importing different colored tracks and greatly dislikes maps being obscured by start and finish icons :)

**Comment by nazar-kutz** [comment]
Hello, @cbrog! We are currently in the final stages of implementing the **Default Appearance** feature, which will soon be completed. Once implemented, both scenarios you outlined (1) and (2) will be readily achievable.

With the introduction of Default Appearance to fulfill scenario (1), you'll be able to configure parameters for the default storage folder of all imported tracks (the "import" folder), or any other designated folder for imported tracks. This includes the ability to globally disable the display of start and finish icons for all existing tracks within this folder, as well as any future additions.

**Comment by cbrog** [comment]
Dear @nazar-kutz, thank you for taking the time to respond to my comment. Please accept my apologies for taking even more of your and your colleagues' time, but I have a feeling my comment was not stated clearly enough to be understood fully. So I will try again, more clearly this time, even if that means a rather lengthy comment, which I hope you'll forgive me for.

It seems to me that most of the attention in this thread has been focused on how to CHANGE the appearance of imported tracks. That is fine, but I am hoping more attention could be focused on how to NOT CHANGE the appearance of tracks when they are imported into the app. I have been an extensive user of Osmand+ for Android for more than 6 years, and the only times I have ever wanted to change the appearance of tracks in the app is because the app changed the original appearance of my imported tracks during the import process. Indeed, if the app did not change the appearance of imported tracks in the first place, then users like me would never need to try to revert those changes or (apparently coming soon) try to re-configure the default settings to prevent the app from making those changes.

To be specific, I would like to ask that the app's original default setting be changed to NOT ADD start and finish icons (or any other feature) to the appearance of imported tracks in the first place, so that users do not have to go through any steps to remove the icons or to re-configure settings to prevent them from being added. In other words, I am specifically asking that the app's original default setting be changed to "not show" (or to "hide") start and finish icons for imported tracks. The start and finish icons Osmand adds by default to imported tracks are not part of the tracks' appearance prior to being imported. Older versions of the app did not add the appearance of start and finish icons by default to imported tracks. But about a year ago the app began adding the appearance of start and finish icons by default when importing tracks, which greatly obscures a map with many tracks. This led users like me to try manually "hiding" the icons to prevent them from obscuring the map, which then led to a bigger problem because changing the setting for one appearance attribute caused the app to change the color of all the imported tracks, even differently colored ones, to a single default color (which if you look at the top of this page is the problem that initiated this thread almost a year ago).

Please don't get me wrong. I appreciate your efforts to facilitate users' ability to change the appearance of tracks in the app if they wish, and to re-configure the app's default parameters for imported tracks if they wish. But for the many users like me who do not wish to spend time reversing appearance attributes introduced by the app or re-configuring the app's default parameters, I would like to please ask that the app's original default settings be set to not introduce any appearance attributes (such as start and finish icons, direction arrows, or color changes) to imported tracks.

Using desktop applications, I frequently create a gpx file containing large numbers of differently colored tracks. This color-coding of tracks is crucial information, and it is very important that the colors and appearance of the tracks be retained as closely as possible when the gpx file is imported by the Osmand app. My biggest fear is that the "Default Appearance" feature being implemented will assign a single default color to all tracks in an imported gpx file, even when that file originally contained differently colored tracks. So I would like to please ask (I'm begging!) that the app's original default setting enable different colors of tracks to be retained when importing a gpx file containing multiple differently colored tracks.

In the past this had not been a problem when importing tracks. But about a year ago, the app began prompting users to choose whether to import tracks as "individual tracks" or as a "single track". Counter-intuitively, if one chooses to import tracks as "individual tracks", the app assigns a single default color to all the tracks in the imported file, even ones that were originally differently colored. Thankfully, one can choose to import tracks as a "single track" and the app will (at least for now) retain differently colored tracks in the imported file. Of course then you end up with an imported file comprised of many different tracks that are all seen by the app as a "single track", meaning you can't analyze the tracks individually (or modify them or change their appearance individually, etc). But hey, at least you get differently colored tracks, which to me is paramount, even if the app renders colors differently than the original, sometimes dramatically (blue becomes orange, orange becomes red, etc). Now if we could just get rid of all the annoying start and finish icons without differently colored tracks being changed to a single default color by the app. One can dream! :)

**Comment by sonora** [comment]
Could a compromise be that unstead or the icons display the direction arrows by default? It seems less intrusive/cluttering and could still provide similar information about the tracks without having to change their appearance after a (mass) import?

**Comment by cbrog** [comment]
Regarding direction arrows and start & finish icons, keep in mind that not all tracks are intended to convey a particular direction. 
In many cases, tracks can be purposely intended to be bi-directional (e.g., two-way roads, streets, trails, etc). 
In other cases, tracks can be "just lines" not meant to convey a direction at all (e.g., boundaries, power lines, etc). 

So one should not assume that the order of the data points comprising a track is useful information that is beneficial to be displayed. Forcing an unintended directional or start/finish representation onto a track would in many cases be misleading or nonsensical. For bi-directional tracks (e.g., two-way roads), assigning a particular direction would cause the track's intended information to be diminished or misconstrued. For non-directional tracks (e.g., boundaries), assigning a particular direction would render the track nonsensical and cause it to be misinterpreted.

In my opinion, as a fundamental principle, the objective should be for the app's default settings to retain the original pre-import appearance of imported tracks as closely as possible, without introducing additional attributes. And in my opinion, as a fundamental principle, customization of appearance attributes should be left to individual users, not forced on users by default.

**Comment by sonora** [comment]
That's very true, I think I withdraw my prior suggestion. :wink:

**Comment by vshcherb** [comment]
@nazar-kutz 
2. Ability to Reset Specific Track Parameters to Default

- It's possible. If you set parameters in Default appearance, you reset in Default Appearance dialog
- If you set on the track, you go to Change Appearance and Select "Original" - thus the track is reset

3. Default appearance shouldn't affect subfolders for now to not complicate situation

**Comment by dmpr0** [comment]
# Review
**Default appearance**
- [ ] Add confirmation dialog with actions:
- - [ ] Apply to existing (quantity)
- - [ ] Apply only to new
- - [ ] Cancel

**Comment by vshcherb** [comment]
- https://docs.osmand.net/docs/user/map/tracks-on-map#track-appearance (section)

**Comment by shurasmiling** [comment]
- https://osmand.net/docs/user/map/tracks-on-map/track-appearence.md
- https://osmand.net/docs/user/map/tracks-on-map/tracks-types.md
- New structure
- Titles
- Link fixing

**Comment by vshcherb** [comment]
Probably should be part of Track appearance content https://osmand.net/docs/user/map/tracks/appearance

**Comment by shurasmiling** [comment]
https://osmand.net/docs/user/map/tracks/appearance#change-tracks-appearance-in-my-places
