### ISSUE TITLE
unpaved roads avoided in pedestrian navigation 

### ISSUE THREAD

**Issue by alexbodn** [osmandapp/OsmAnd#17016]
in more than one case
I'm building a route or 
a navigation
that may use unpaved roads,
but does avoid them 
and creates less proper paths.
here's an example navigation.
https://drive.google.com/file/d/1TsbwuJ7Wn4JKaeeASe_Mls-kNgcUASQN/view?usp=drivesdk

**Comment by Zirochkabila** [comment]
@alexbodn Please clarify:
1. The device you use, OS version
2. Application version
3. Route, start, and finish coordinates 
4. The presence of traffic restrictions (unpaved roads only?)
5. A short video and screenshots where we could see the error

**Comment by alexbodn** [comment]
hello anatolii and thanks for your reply.
in the issue report, there's a link to get my navigation file.
as you can see in the navigation file, there's no road restriction.

alex

**Comment by alexbodn** [comment]
also mentioned in my issue report: no restrictions.
i use last osmand+ on android 8.

the navigation file states the from-to coordinates, and osmand+ can show it
to you, as i have no video.


alex

**Comment by Zirochkabila** [comment]
@alexbodn The track you sent shows one point - **more data** and **details** are needed to understand and reproduce your request.
**Please clarify:**
1. The device you use, OS version
2. Application version
3. Route, start and finish coordinates 
4. The presence of traffic restrictions
5. A short video and screenshots where we could see the error

Beforehand, please install the night version and try to reproduce the behavior in it. The bug may have been fixed by https://osmand.net/docs/versions/nightly_versions

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/235298722-7cfd17cb-ee35-4b23-a807-2c006af76a05.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by alexbodn** [comment]
you are successfully proving me there is an even longer way.


alex

**Comment by vshcherb** [comment]
I think we are talking about that route https://osmand.net/map?start=34.881112%2C32.854695&end=34.884153%2C32.858498&mode=pedestrian#18/34.88245/32.85795

**Comment by vshcherb** [comment]
The problem that 
- https://www.openstreetmap.org/way/633688839 is disconnected from other routes so this issue is related to disjoint road on OSM data which could be fixed by mappers or by you
- This route works https://osmand.net/map?start=34.879968%2C32.857039&ipoints=34.884153%2C32.858498&end=34.884153%2C32.858498&mode=pedestrian#18/34.88176/32.85874

**Comment by alexbodn** [comment]
i thank you very much for your reply.
i will check how to fix disjoint road problem.


alex

**Comment by alexbodn** [comment]
the strait line routing allowed me to plan routes over disjoined ways.
thank you very much, vshcherb.
i will also check how to fix osm.


alex
