### ISSUE TITLE
Track color type does not change

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd#17011]
### To Do

- [x] Change the color type when switching from Surface to Solid

### Description
When switching to a track color type from Surface to Solid, the type is displayed as Surface

### Steps to reproduce

- Select GPX
- Appearance
- Chose Surface
- Back to Solid

### Actual result

https://user-images.githubusercontent.com/104760013/233645395-84ce5d18-adbb-41d3-a210-429b9af84b8f.mp4

### Expected result
Track type changes

### Your Environment
OsmAnd Version: OsmAnd~ 4.5.0#35825m, Released: 2023-04-21
Android/iOS version: Android 12
Device model: Poco x3 nfc

**Comment by Chumva** [comment]
The bug appears only with OpenGL rendering, it looks like there is some issue with [renderedSegmentsCache](https://github.com/osmandapp/OsmAnd/blob/e60c26ed2b4f9cfb7ee188a28973c3bc0638775b/OsmAnd/src/net/osmand/plus/views/layers/GPXLayer.java#L1144), because it disappears if we always call resetSymbolProviders for all segments

**Comment by yuriiurshuliak** [comment]
The bug has been fixed. When changing the track color type from Surface to Solid, the color changes correctly.

OsmAnd~ 4.6.0#915m, released: 2023-10-25

https://github.com/osmandapp/OsmAnd/assets/127092082/129e894b-c6e6-4734-b580-a55d07183545
