### ISSUE TITLE
Relationship between zoom level and distance is mixed up

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd#17037]
### To Do

- [ ] Show one distance per zoom level
- [ ] Show distance vertically (200 km)

### Description
When zooming, sometimes two zoom levels correspond to the same distance. 
Also, sometimes kilometers are displayed below the numbers

### Steps to reproduce

- Randomly change the scale from larger to smaller and vice versa

### Actual result

<table style="width:100%">
  <tr>
    <th>5/500km</th>
    <th>4/500km</th>
    <th>5/200km</th>
  </tr>
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/233964194-3f669ecb-b260-4593-b2fe-ad4438a07602.jpeg"  width="300" height="auto"/> </th>
<th><img src="https://user-images.githubusercontent.com/104760013/233964197-6043cf6e-dee3-47ed-8e3d-50a36d86d936.jpeg"  width="300" height="auto"/> </th>
<th><img src="https://user-images.githubusercontent.com/104760013/233964202-468bfce7-79c4-4332-800c-c2950f23fc21.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table> 

https://user-images.githubusercontent.com/104760013/233964050-c16ec76e-4709-40f7-92cc-7f38e0d564c3.mp4

### Your Environment
OsmAnd Version: OsmAnd~ 4.5.0#35830m, Released: 2023-04-23
Android/iOS version: Android 12
Device model: Poco x3 nfc

**Comment by mikehgentry** [comment]
> When zooming, sometimes two zoom levels correspond to the same distance.

Are you sure that's wrong? There's a scale bar below the distance which is significantly longer in the first image

**Comment by scaidermern** [comment]
The world is round but OsmAnd displays a flat world. The closer you are towards the equator the longer distances become while keeping the same zoom level. I guess that's why you will see the same numbers for different zoom levels. Pan the map a little to the north or to the south and the number might change.
Also keep in mind: the lower the zoom level, the less accurate these numbers will be (because of the behavior described above).

**Comment by vshcherb** [comment]
Not going to be fixed
