### ISSUE TITLE
Prevent rotating the view when "vehicle" is not moving

### ISSUE THREAD

**Issue by mdykierek** [osmandapp/OsmAnd#17053]
I am driving with screen orientation fixed in the direction of my movement.
Then I stop e.g. at traffic light and my view starts dancing around (rotating).
I think it should keep the direction of calculated route until I move again.

**Comment by mikehgentry** [comment]
There's an 'approximate bearing' setting, which might help if it's jiggling.

https://osmand.net/docs/user/navigation/guidance/map-during-navigation/

Otherwise it's probably following the compass? Try Menu -> Profile Settings -> General settings -> Use magnetic sensor (off)

[Kalman filter might have an impact too?]

**Comment by mdykierek** [comment]
The thing is, that in my opinion with this mode on, it should not care about compass. It "knows" where I should go even if I walk and stop just to look around.
I have the magnetic sensor OFF (I think it's default for car).

**Comment by Zirochkabila** [comment]
@mdykierek Do you have the latest version of OsmAnd?

**Comment by mdykierek** [comment]
Oh yes. The latest available in Play Store now - 4.4.7

**Comment by beatnickgr** [comment]
Same issue here, 4.3.12 from F-Droid.
There is no "approximate bearing" in my settings (it was there before the update).
![photo_2023-04-29_18-29-53](https://user-images.githubusercontent.com/17930530/235310750-94e9a2a7-9166-4f60-9849-99beda58dff2.jpg)

**Comment by mikehgentry** [comment]
Have you inadvertently disabled the development plugin?

**Comment by beatnickgr** [comment]
Keeping the map steady should not be reserved to developers.

Furthermore, turning the plugin on/off doesn't put the "approximate bearing" back in the menu (it's not expected to do so).

**Comment by mikehgentry** [comment]
> keeping the map steady should not be reserved to developers.

It's not just for developers, it's also for testing features / fixes

> it's not expected to do so

Yes it is

https://osmand.net/docs/user/navigation/guidance/map-during-navigation/

**Comment by beatnickgr** [comment]
Even if I fail to understand the logic why people who are not devs or testers should have their map rotating, I repeat : **turning the plugin on doesn't put the "approximate bearing" back in the menu.**

**Comment by jelle619** [comment]
I'm having this issue as well. The "approximate bearing" option does indeed show up with the development plugin enabled, and I have turned it on. However, I would like to use OsmAnd while driving without having a destination set, in which case the approximate bearing option would not do anything.

I would like to say that I know for sure that the magnetic readings from my device are bogus due to the magnets in my phone case. However, the magnetic sensor option ks turned off in settings, so as far as I understand it, this should not affect anything. If it does, then that could be a bug.

**Comment by Zirochkabila** [comment]
@mdykierek It was checked on the latest nightly version - it could not be reproduced https://osmand.net/docs/versions/nightly_versions/
Rotation only works when the device is directly rotated

<table style="width:100%">
  <tr>
    <th>Approximate bearing - disable</th>
    <th>Approximate bearing - enable</th>
  </tr>
  <tr>
    <td><video source src="https://user-images.githubusercontent.com/104760013/235345704-fba41d37-64d3-4016-b147-32fd2166b2a8.mp4"  width="300" height="auto"/></td>
    <td><video source src="https://user-images.githubusercontent.com/104760013/235345705-d867024e-a82f-4484-8f50-bd8b4d9c52c7.mp4"  width="300" height="auto"/> </td>
  </tr>
</table> 

Please install the night version and add your video as an example. We need to understand what is happening - also, attach a log file: Menu > Help > Send logcat log

**Comment by mdykierek** [comment]
I reset car profile to default and made further observations. The map rotates, but at least now I know why.
I guess the reason for unwanted map rotation is false movement from GPS (I don't see GPS enabled in your movies).
It seems that from time to time, for a brief moment the speed displays 1 km/h (yet the position doesn't change ;)) and the dot changes to arrow.
It is not a major issue and remedy could have serious impact.
