### ISSUE TITLE
Wishlist: cruising mode - announce speed limits, POIs, etc when not navigating

### ISSUE THREAD

**Issue by RicoZ-OSM** [osmandapp/Osmand#1706]
would that be doable? Maybe internally it could be handled like navigation - whenever the car/cycle.. is moving along a way assume a destination somewhere ahead on that road.

**Comment by davidebaldini** [comment]
This has been previously discussed on Google groups, but IIRC to no avail.
Definitely I enqueue myself this this ticket.

**Comment by sonora** [comment]
Not sure if it still behaves this way (and it probably is not on
purpose...), but from my experience, if you start a navigation and enter
the Follow mode by hitting the "Go" button, so that the voice module gets
activated and you hear an instruction, OsmAnd would continue with prompts
like speed limis even after stopping the navigation again (until the next
time OsmAnd is completely re-started).

**Comment by RicoZ-OSM** [comment]
@sonora : this seems to work for me to some degree in the stable version that I am using. Speed limits and pedestrian xings  are displayed and announced when I am over the threshold. POIs aren't announced but that was not the most important priority.

Would be nice if that functionality is preserved for new versions, didn't have the opportunity to test the nightlies for this.

**Comment by vshcherb** [comment]
I think it is already working this way:
-  if you change your profile to Car and press button to follow my location, it will enable alarms displayed on the bottom and some announcements.
- it should also enable pronouncing waypoints, but that needs to be tested.
