### ISSUE TITLE
Offline routing: Speed cam' announcement

### ISSUE THREAD

**Issue by OpenSourceForEver** [osmandapp/Osmand#1708]
I think speed cams should be announced earlier than they are now (like roundabouts or turns).

**Comment by sonora** [comment]
deprecated, already altered, I think.

**Comment by OpenSourceForEver** [comment]
Osmand 2.4.0#14613D. The issue is not fixed

**Comment by polarbearing** [comment]
@OpenSourceForEver - you might want to give the developers a specific example, where a device is mapped, when it is announced and when you would expect it. 

Otherwise nobody can reproduce your problem. 

For the roads I drive, the devices are announced early enough. 

Hm, in this specific case you might add details about your driving style as well. ;-)

**Comment by sonora** [comment]
;-)

**Comment by OpenSourceForEver** [comment]
I made a mistake. It is ok. Sorry
