### ISSUE TITLE
Increase maximum speed for moped profile

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/OsmAnd#17096]
Currently the maximum speed a user can configure for the moped profile is 53 km/h. This is too low. The famous German (GDR) moped [Simson S50](https://de.wikipedia.org/wiki/Simson_S_50) / [Simson S51 ](https://de.wikipedia.org/wiki/Simson_S_51) has a (legal!) maximum speed of 60 km/h. Depending on the conditions (of the road and the moped) it is even possible to drive ~65 km/h.

Therefore I suggest to increase the maximum speed for the moped profile to 70 km/h. The default values don't have to be modified.

**Comment by Zirochkabila** [comment]
@alex-osm @xmd5a2, can we increase the maximum speed for the moped profile? 
But, the default value leave without unchanged

**Comment by xmd5a2** [comment]
I think some modifications in UI are needed because in `routing.xml` we can assign only default values but not maximum available for user.
`<routingProfile name="moped" baseProfile="moped" restrictionsAware="true" minSpeed="5.0" defaultSpeed="25.0" maxSpeed="35.0"`
![photo_2023-05-26_09-56-03](https://github.com/osmandapp/OsmAnd/assets/5829014/4be44d99-a413-4dc0-9646-2f79071f0405)

**Comment by vshcherb** [comment]
Todo: routing.xml add fields ```uiMinSpeed``` / ```uiMaxSpeed```

**Comment by Chumva** [comment]
- [ ] Probably we have to check for routing profile, not app mode

**Comment by Chumva** [comment]
Max available speed limits can be edited [here](https://github.com/osmandapp/OsmAnd/blob/97167b2d8fbb31cded21cb484e483f3f34e34508/OsmAnd/src/net/osmand/plus/settings/fragments/VehicleSpeedConfigLimits.java#L13-L25) for different routing profiles
