### ISSUE TITLE
Map loading has become incredibly slow after 4.2

### ISSUE THREAD

**Issue by metbic** [osmandapp/OsmAnd#17106]
Please do not file questions or support requests on the GitHub issues tracker.

In case you aren't sure whether to open an issue or not, please send your request to support@osmand.net.

You can get your questions answered using the [Google group](https://groups.google.com/forum/#!forum/osmand) or chat in real-time via our Telegram instances: [English](https://t.me/OsmAndMaps), [German](https://t.me/deosmand), [French](https://t.me/frosmand), [Ukrainian](https://t.me/uaosmand), [Italian](https://t.me/itosmand), [Russian](https://t.me/ruosmand).

Thank you!

**Comment by Zirochkabila** [comment]
@metbic I tested the downloading of the map of Ukraine and Romania, using application versions 4.4.7 and 4.2.7 - the download time is the same.
Please attach a video showing the difference in time in map loading.

It is possible that the download speed was slow due to technical work on the server these days.

Please note that activation of the [Proxy](https://osmand.net/docs/user/personal/global-settings#proxy) may affect the speed of downloading maps

**Comment by Zirochkabila** [comment]
@metbic Thank you for the clarification. But this behavior is not reproducible either.
Maybe it's the location where the data is stored - try using External storage 1 https://osmand.net/docs/user/personal/storage#data-storage-folder
Also, try changing the rendering type settings https://osmand.net/docs/user/personal/global-settings#map-rendering-engine
