### ISSUE TITLE
Silent failure updating maps when low on free space

### ISSUE THREAD

**Issue by mikehgentry** [osmandapp/OsmAnd#17223]
### Description

If you have sufficiently low free space on your device (on the order of a gigabyte or two left, trying to update 1/2 to 1 gigabyte of maps), if you hit 'Update all', the progress bars for downloading and indexing will display and seemingly complete, but nothing will actually happen - exiting the menu and re-entering it again gives you the same list of maps to download.

You can often bypass this by updating maps individually. If you're *even lower* on space, trying to update any single map will fail in the same way.

Rebooting the phone seems to clear cache [- the amount of free space reported by the 'Local' tab goes up], and will sometimes unstick it. I think maybe fully closing and reopening OsmAnd can do the same in certain circumstances.

### Steps to reproduce

Have very little space on the device, attempt to update maps. I have this happening right now, so can provide logs if you tell me which ones (eventually, probably after ~a week, I will delete some stuff and update if I haven't heard back) [edit - some logs sent, may or may not be the right ones]

### Actual result

Silent failure

### Expected result

A warning message, or outright refusal to download.

### Your Environment
OsmAnd Version: +4.5.0
Android/iOS version: 11
Device model: Xcover 4s

**Comment by Zirochkabila** [comment]
I managed to recreate it on the 5th attempt
The warning was also displayed
[exception (55).log](https://github.com/osmandapp/OsmAnd/files/11546714/exception.55.log)


### Step to reproduce

- Download enough maps so that the free space on your device is less than 500 MB
- Menu
- Download maps
- Updates
- Update all (the amount of data to be updated should exceed the amount of free space)
- Warning is displayed
- Without closing the warning, roll up and reopen OsmAnd


<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/104760013/729fcd04-f215-4370-86dc-4eda4d7bf201"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by mikehgentry** [comment]
Updating in stages over the last 24 hours didn't exhibit this bug.

I'm still pretty sure the bug described above was real previously, but I'm not sure the logs provided are an example of it (it seems there have been a few other issues with map updates recently).

So I'll close this for now, and will reopen if I manage to log an instance in future updates.
