### ISSUE TITLE
Regression: Track import behavior: Display on the map

### ISSUE THREAD

**Issue by sonora** [osmandapp/OsmAnd#17270]
It seems that as of late we have created the following deficiencies:
- A user who in a file manager app taps on a gpx file can open the file in OsmAnd, but the file is not displayed on the map by default. Viewing the gpx file on a map is the most common use case for this action. There is a short toast facilitating to view the file, but many users will miss it, and will then have difficulties locating the file in OsmAnd. (Often performing yet another import action.) Displaying the file on the map should become our default again.
- Same if the file already exists, both for the options "Keep both" and "Replace".

**Comment by Zirochkabila** [comment]
@sonora Since the user can skip the notification, I think we can add the display time of this notification to 5 seconds, and the Open button will open the track menu.
As for displaying the track on the map immediately after importing, I agree, it would be more convenient.
We need to clarify the implementation with @vshcherb and @dmpr0 

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/104760013/1031ebc0-6514-4f36-b6c2-194bb5d9fbe2"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by sonora** [comment]
In my mind, someone who taps on a file in a file manager app wants to see that file openened and displayed in a suitable app- any other behavior would be very unconventional?
