### ISSUE TITLE
Audible navigation instructions should be improved when following a curvy main road

### ISSUE THREAD

**Issue by sjvudp** [osmandapp/OsmAnd#17376]
### Description
I was following a curvy main road when the audible instructions were quite confusing.
Here is a basic sketch to illustrate; the main road is the thicker one, and I was driving from bottom to top direction:

![Navigation](https://github.com/osmandapp/OsmAnd/assets/6734808/1f2cba90-fdba-4187-92af-22194a7bf941)

The distance between both turns of the main road is about 50 meters.

### Steps to reproduce
I had "normal" distances for announcements set, and when I was near point "1" the instructions were "take left turn".
I was driving in town at about 40-50 km/h.
That was very confusing, because the next left turn was *not* to be taken!
At point "2" there was no other announcement.
### Actual result
So I think the announcement for the actual turn was too early and confusing.

### Expected result
There should have been some other instructions at point "1", like "keep right", and only after the turn of the main road (near "2") there should have been a second announcement like "take left turn" (My TomTom does such and it's much easier to follow the correct course with the TomTom).

### Your Environment
OsmAnd Version: 4.4.7
Android/iOS version: 13.1
Device model: Oppo Find X5 Lite

### Update
As I was driving the same route again (with a newer version of the app, 4.5.9) I tried to make a screenshot while driving, so the situation is *after* the voice announcement. Also I rotated the screenshot to match my sketch (which wasn't quite exact, but anyway):
![OSMAnd-Map-rotated](https://github.com/osmandapp/OsmAnd/assets/6734808/a12c6e4e-9e0d-4e15-9e77-af83c08eb6e4)

I've added the two red annotations **1** (where the driver might think to turn left) and **2** (where the driver actually should turn left). Also the route displayed uses intermediate stops which has some issues of it's own (which I'm planning to report unless done already).  I was driving 46 km/h where 50 km/h were allowed.

**Comment by DmitryAlexei** [comment]
Tested the work of voice prompts both on the ground (driving a car on narrow roads in the courtyards of multistory houses, on country and forest roads with many branches), as well as using the navigation simulation function. 

I can confirm that when driving at low speed (much slower than the [default speed](https://osmand.net/docs/user/navigation/guidance/navigation-settings#default-speed--road-speeds) that affects the voice prompts), the voice prompts are announced **much in advance** of future turns. In such a case, they also repeated **too far in advance** of the maneuver, even when the turn location may be out of sight. Sometimes a prompt can be voiced when there is another similar (or at least can be considered as such) turn before the required one. 

The problem of voicing prompts too early is even more relevant if the user has **increased** the default speed (for example, if he is driving mostly on high-speed roads), but sometimes drives on roads with low traffic speeds.

It seems that our algorithm for voicing prompts takes into account only the requirement for their pronunciation in advance, which is relevant for high-speed roads.  At the same time, when driving at low speeds, the necessity of voicing cues (and their repetition) in a "reasonable time" is not sufficiently taken into account.

<details><summary>Technical documentation</summary>
According to [technical documentation](https://osmand.net/docs/technical/algorithms/voice-prompt-triggering):
- For close prompts, both a **distance threshold** and a **time threshold** are used. The time threshold ensures that the announcements are triggered **early enough**, even if your current speed **exceeds** the **Default speed**.
</details>

Based on the written above:
- perhaps we should voice prompts not based on the default speed of the vehicle, but use only the real speed (or predicted speed based on data for the last minute or two)?
- for close prompts can we check the possibility of turning in the same direction before the expected turn and, if there is a similar turn, sound the prompt only after passing it? (it can also be useful when driving at any speed)
- if, after notification of a turn in advance, the speed has significantly decreased (or the vehicle has stopped due to a traffic jam or other circumstances), maybe it would be worth turning on additional voice prompts?



My OsmAnd version: latest nightly builds

**Comment by vshcherb** [comment]
Indeed 2 things could be improved:
1. When speed is slower than 20-30 kmh we can lower default speed and use actual speed to pronounce not earlier than 10 seconds (on video above it's 20 seconds too early) - easy to do
2. With curvy roads and intersections, we could analyse there are extra turns and say "Turn left on 2nd intersection in 50 meters..." - harder to implement

**Comment by sjvudp** [comment]
Thinking about it I come to the conclusion that an optimal algorithm probably does not exist, and even a heuristic is everything but trivial. I'm tying to list properties that are to consider IMHO:

  - (H1) The announcement MUST be "_in time_", but SHOULD NOT be "_too early_" (both phrases to be defined later)
  - (H2) The important point in time is when the announcement has finished, and not when it started. This requires the duration of the announcement to be known ahead of time
  - (H3) Announcements SHOULD BE _preemptive_, allowing a more _important_ announcement to preempt a current announcement of less importance
  - (H4) Announcements SHOULD BE as precise and short as possible, because (1) time is rare, and (2) short messages are easier (i.e.: faster) to understand

### The Right Time
Obviously the _right time_ for an announcement leaves enough time to understand it and act accordingly.
So _how much time will be needed?_ Unfortunately that depends on several components:
  - (T1) The _time to understand_ the announcement, probably at least one second, but most likely 3-5 seconds (after it had finished)
  - (T2) The _time to act_ accordingly. Unfortunately that depends on further details:
    - (D1) _Action to perform_: Obviously staying in the current lane is faster than preparing for a turn, and for right traffic, taking a right turn is probably easier (and thus faster) than taking a left turn.
    - (D2)  _Current road_: Some roads have a "turning lane", so most likely you'll have to switch lanes which needs extra preparation time. For example when driving with high speed on a busy three-lane German Autobahn, the exit is via a turning lane beside the rightmost lane, so moving to the correct lane needs significant time and distance to finish.
    - (D3) _Speed_: "Distance = Speed * Duration" (in most simple words); if you take acceleration (speed change) into account, it's a bit more complicated. So "Duration = Distance / Speed" has to be long enough to be able to perform the action: The faster you go, the earlier the announcement must be scheduled.

    My guess is that each action requires at least two seconds: One second to prepare the action, and one second to perform it; however both can be significantly longer (see D1 through D3). 

### Preempting
To be able to "_preempt_" announcements, some queue (heap or priority queue) containing such announcements is needed. The head of the queue should be the oldest announcement not yet finished, and the tail of the queue should be the latest announcement added.
Each element in the queue should have a "_time due_" field that specifies when the announcement should be finished (see H2).
Naturally as speed will change (e.g. due to traffic, speed limits, etc.), the "times due" also will, and probably the _next_ announcement will be due before the current announcement has finished, so the current announcement has to be preempted (discarded) and removed from the queue. Maybe even drop the next one in the queue in favor to the second-to-next one.

So how many items should be in such a queue? My guess is: "At least three"

### Combining and Shortening
When time is tight, subsequent announcement might even be combined to a new, shorter announcement, maybe like this:
"in 50m follow main road"
"in 80m turn left"
"in 120m turn right"
When driving with 50km/h (ca. 14m/s) that would be rather tight, so the combined instructions might be:
"follow main road in 50m, then turn left, finally turn right" (assuming there is no crossing (intersection) between the two turns to take). If the time until action by the driver is required is less than three seconds (after the announcement has finished), skip any distance, and just say "go straight (now)", "turn left (now)", and "turn right (now)" (so very similar)

### User preferences
I also think that basing any timings on distance instead of time is wrong, as I tried to point out with the varying speed. Assuming some average speed (or speed limit) might be OK when planning far ahead of time (when you cannot predict or measure the speed), or when a car is currently waiting at some red traffic light (and thus has zero speed).

### Errare humanum est
Maybe all I said is just plain nonsense; you could ask ChatGPT for the best algorithm for the problem, and then **don't implement**, but _think about that_ instead. ;-)

**Comment by sonora** [comment]
While a prompt that comes too early may be bad, a prompt that comes too late is useless. Too late could e.g. mean the turning point is already behind you (location inaccuracy), or also the turning lane has already begun without you being aware to take it. That's why we rather err on the early side.

I agree with Victor that two things could be looked at:
- At for a car unusuallly low actual speeds we could change the parameterization to more like we have it in the bicycle profile.
- And we could look into detecting and announcing something like "take the second left", like we do in roundabouts. (Not easy.)

**Comment by sonora** [comment]
PS: I was never a big fan of users being able to specify their "default speed". User parameterization can easily aggravate an issue unknowingly.

Maybe we should use the occasion to make the default speed an internal prediction/fallback parameter only, wherever possible replace user parameterization by circumstantial automation via true data. Which would here mean we test to always use actual speed to time "Turn now" prompts.

**Comment by vshcherb** [comment]
@sonora the issue may have roots that we didn't have correct speed values and we didn't want to say too late, imagine that you stand still and then start moving with 60 kmh - 3-4 seconds delay of the system  and you might miss the turn. So we put a speed at minimum 40 kmh because the car could accelerate too quickly but it might be too much.

**Comment by vshcherb** [comment]
Also I remember I've put because there was an old confusing code with min speed and I didn't dare to delete but made it just obvious. Though I don't think that's the main reason:
``` Turn now Driving: 7 s``` (according to docs) I think the minimum speed should exist but not for turn now, for prepare it makes more sense. Even if we skip turn now which I think too rarely happens, it might not lead to bug cause driver is prepared. But too early misleads driver even more often...

**Comment by sonora** [comment]
@vshcherb On a practical note, and from years of testing ("under normal everyday conditions"):
- I am quite satisfied with the timing we have had in recent years, and I think we have drawn few systemic complaints.
- I also cannot teadily reproduce the "much too early"  findings of the video above in my common traffic situations.

So this issue here is very likely limited to exceptional "very low speed" cases of being in a traffic jam or maybe on a very rough dirt track. We should not "overfix". If we change anything at all, make sure it affects only the case where the actual speed is clearly unusually low?

**Comment by DmitryAlexei** [comment]
Unfortunately, incorrect voice instructions when driving at low speed is a very common problem.
*incorrect *it means that they arrive too early, and it is necessary to control the location on the device so as not to make the wrong maneuver* So following only voice prompts may cause (at least) wrong turns.

https://github.com/osmandapp/OsmAnd/assets/116079541/9b133cda-65b3-4ed6-ae5f-a1abc39c3401

https://github.com/osmandapp/OsmAnd/assets/116079541/942b76f8-a61a-43e4-ab38-1f55fb622764

https://github.com/osmandapp/OsmAnd/assets/116079541/e8d63d2a-c52a-4851-bdca-250a56ddf57b

**Comment by sjvudp** [comment]
> PS: I was never a big fan of users being able to specify their "default speed". 

Well, actually with speed limits there should be a default speed per road type. Probably it only makes sense for "Autobahn" where there is virtually no speed limit in Germany at least. Having used a TomTom for some years, I had the impression that the device "learned" from my driving how I'm expected to drive. So the speeds are mostly used to estimate the time of arrival (ETA), not so much to time the announcements (I think).

**Comment by sjvudp** [comment]
I think the ultimate test for voice announcements is not to look at the device and solely act on the voice instructions.
I mean: If you have to look at the map and the indicators on upper left also, you don't need voice announcements at all.

**Comment by sonora** [comment]
Somehow our car profile seems to exactly enforce this, and I wonder why...

Could someone who can reproduce please try this: Go to the Cycling profile's Navigation settings> Vehicle parameters>Default speed, set the max speed to 50km/h, and the default speed to 45km/h. Then use the Cycling profile, and report if this behaves ok.

**Comment by sonora** [comment]
So for the original issue  it looks like for the final "Turn" prompt I may have to tweak the 45m _minDist_ and 7s _minTime_ parameters a bit. Possibly lower them speed-dependent, so they more precisely indicate the position of the actual turn.

For the last 3 recordings I am unclear why they play a prompt about 70m and 80m before a turn, at speeds of 9 and 19 mph. Can you please verify they were taken with the standard car profile default speed / Vehicle parameter settings? Perhaps reset things. Just to rule out there is not an unrelated bug by e.g. using mph as speed unit while region seems to be central Europe?

**Comment by sonora** [comment]
Here's the fix, first version: https://github.com/osmandapp/OsmAnd/pull/17823

The approach is: For low speeds scale down the distance and time triggers, I have tried a proportional approach first. Needs testing in real live (simulation has limited validity).

**Comment by sonora** [comment]
First tests. I think this may be overdoing it slightly (prompts now potentially too late). If anybody feels the same, could try a square root reduction instead of proportional.

**Comment by vshcherb** [comment]
The code needs to be easier to read

**Comment by sonora** [comment]
@vshcherb  Are we ready to merge it now so people could use the nightly build to test the parameterization?

**Comment by vshcherb** [comment]
Documentation needs to be updated as well but let's try to keep it simple to understand we have 2 checks for turn now:
1. Time tirggers
2 a. Distance trigger for speed > default speed
2 b. Distance  trigger for speed < default speed
