### ISSUE TITLE
Rendering of large wind power generators

### ISSUE THREAD

**Issue by RicoZ-OSM** [osmandapp/Osmand#1738]
http://wiki.openstreetmap.org/wiki/Tag:generator:source%3Dwind

The big ones are notable landmarks, wondering if the rendering could be made different depending on height=* ?
Alternatively nameTag2="height" might be a good enough indicator of size.

**Comment by xmd5a2** [comment]
Done. Added height as nameTag2. Also note that ability to view additional poi tags directly from map is planned via context menu. So it may not  be necessary to add more info to map but better keep it hidden but easily accessible.

**Comment by deqoksijnc** [comment]
Came up in the mailing list again and at first I thought that it is a regression because I could not find a well known one on the map.
Only after much zooming I realized that the icon for out 600 feet monster windmills is so miniscule it is almost impossible to find and also displayed only at rather high zoom levels - contrary to the landmark nature of these feature.

Can the numeric value of height  be evaluated for rendering purposes? If not it might require a preprocessing step evaluating height and adding rendering tags for Osmand.. such as small (height<10m), medium (<20m), large (<50m), xlarge (>50m). I would imagine quite some other features have similar problem.
