### ISSUE TITLE
Marker flags not showing up on the map

### ISSUE THREAD

**Issue by MaartenDeen** [osmandapp/OsmAnd#17396]
I've had this a few times now. When I start OSMAnd, no marker flags show up on the map, even though the slider for the markerflags is on. When I turn the slider off and on again, the marker flags show up.

OsmAnd Version: 4.4.7
Android/iOS version: Android 10
Device model: Xiaomi Mi A2

**Comment by Zirochkabila** [comment]
@MaartenDeen Please note that in order to display markers on the map, the marker display feature must be activated for each specific profile: Configure map > Map markers

Please update OsmAnd (install the public beta or nightly version https://osmand.net/docs/versions/nightly_versions) and try again. If the behavior repeats, please attach a video and log file: Menu > Help > Send logcat log

**Comment by MaartenDeen** [comment]
@Zirochkabila As I said: I have the slider for the marker flags on.

**Comment by vshcherb** [comment]
Unfortunately we didn't manage to reproduce the issue.
