### ISSUE TITLE
need more time intervals in voice command tests

### ISSUE THREAD

**Issue by aceman444** [osmandapp/Osmand#1742]
Please add some more combinations of route lengths (in time) in the testing voice commands in the Dev plugin. For some languages we need to test more combinations of times, e.g.:
- 30 seconds
- 1 minute
- 2 minutes
- 4 minutes
- 25 minutes
- 1 hour
- 2 hours, 1 minute
- 3 hours, 2 minutes
- 5 hours 3 minutes
- 7 hours 10 minutes
- 15 hours 30 minutes
- 25 hours 45 minutes

I know it becomes quite a lot. How can we test this in the TTS engine without inflating the number of commands too much. Maybe you could make an input box where we put time (in secods) that is then used in the command?

**Comment by sonora** [comment]
Some remarks:

I think prompts talking about "30 seconds" are ridiculous, because it
implies a precision not useful in practice. I would remove that again and
use "about 1 minute" as the minimum.

For testing almost every time announcement you want, just pick a
destination, calculate the route, hit "GO", listen what time it comes up
with. then slightly shift the destination as needed and and re-calculate.
In this fashion you can rather quickly produce all significant
combinations you want.

PS: From my experience f you get e,g. "15 minutes" right, no big need to
test "15 hours", you will likely get this correct, too ... :-)

**Comment by sonora** [comment]
I think this is solved by the workaround I state above?

**Comment by aceman444** [comment]
Calculating a 1hour route may take some time in Osmand :) And the longer routes may not even be possible currently (memory shortage). There may be something to your 15min. vs 15 hours claim :)

So I assume it would be quite hard to give us some inputbox where we can put the time in seconds and then the command would be spoken?

**Comment by sonora** [comment]
Ok, point taken. I have expanded the voice tests to now include all numbers you wanted for testing, combined them to use a total of 8 buttons for this (in the beginning of the voice prompts test panel). Hope this helps.

**Comment by aceman444** [comment]
Great, thanks!
