### ISSUE TITLE
TravelGuide: Extract coordinates/generate points if there is a wikidata tag available

### ISSUE THREAD

**Issue by TheSnoozer** [osmandapp/OsmAnd#17465]
# 🚀 feature request

Hello,
thanks for OSMAND :-)
Really love the idea of the TravelGuide and having the ability to gather some tourist information / points about a city.
Today I noticed that essentially really only places seem to result in actual points if the coordinates are also encoded in the wikivoyage-website. While this is great I think OSMAND could also extract the coordinates for elements that reference a wikidata object.

For example if there is an object in the wikivoyage-website that would only reference Q83125 (https://www.wikidata.org/wiki/Q83125) one could extract the coordinates from wikidata resulting in [51°30'19.80"N, 0°4'31.46"W](https://geohack.toolforge.org/geohack.php?params=51.5055_N_-0.075405555555556_E_globe:earth&language=en).

Thank you for your time and consideration.

**Comment by vshcherb** [comment]
We already do something similar with Wikivoyage / WIkipedia integration, could you be more specific

**Comment by TheSnoozer** [comment]
Hello,
sure, random example I found is the city of "Haguenau"

When going to the TravelGuide -> "Haguenau" -> POIs only the main railway station is displayed (=Bahnhof in german):

![photo_2023-06-21_19-24-39](https://github.com/osmandapp/OsmAnd/assets/6849390/b98637c5-f7ea-4747-8736-5a9c43116f86)

However going by the wikivoyage website (I picked an older version)
https://de.wikivoyage.org/w/index.php?title=Haguenau&oldid=1498934
under "Sehenswürdigkeiten" (=places to see for toruists) the "Fisherturm" for example shows a linked Wikidata-Object when editing the reference:
![image](https://github.com/osmandapp/OsmAnd/assets/6849390/da155b97-6e6c-4edf-9de4-d0991cfa2a95)

The object itself has no geo location attached, but the linked Data-Object would have such GEO data available: https://www.wikidata.org/wiki/Q15953408

Hence my feature request to make the "Fisherturm" part of the POI list of the TravelGuide which was last updated on 17.05.2023.

**Comment by vshcherb** [comment]
Indeed there is geo data (https://www.wikidata.org/wiki/Q1509611) so it should be possible

**Comment by TheSnoozer** [comment]
Thanks just saying that wikivoyage has the ability to download the GPX of a City (=POIs):
![image](https://github.com/osmandapp/OsmAnd/assets/6849390/948a5340-434a-4e5a-be97-057bb993b756)

I don't know the logic, but maybe when the offline version of the travelguide is generated the process "simply" takes the GPX that is already provided....


Anyhow thanks again for taking a look into this.

**Comment by DmitryAlexei** [comment]
OsmAnd~ 4.6.0#1032m, released: 2023-11-15 + Travel guides updated to the latest version (in my case, simple update didn't work. It is needed to delete and download again fresh Travel guide map)
1. Haguenau article. Later was visible only one waypoint (Bahnhof Haguenau), now - 9 points. Saint-George church (https://www.wikidata.org/wiki/Q1509611) and Tour des Pêcheurs, Haguenau (https://www.wikidata.org/wiki/Q15953408) are visible as waypoint.

- In waypoint menu there are no images of selected objects 
- It is quite unclear why do we create our own GPX file when there is a GPX provided by [wikivoyage](https://de.wikivoyage.org/wiki/Haguenau) ([Haguenau_de.gpx.txt](https://github.com/osmandapp/OsmAnd/files/13377765/Haguenau_de.gpx.txt)). Original gpx has more points including parking and tourism office coordinates). 

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/77770604-9b95-4cfc-bd0b-ba9ffa10738a"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/85fd2bfe-d49a-432e-90c5-cc55297ab950"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/28e83682-b455-4317-9e9c-ddc23a3abd93"  width="300" height="auto"/> </td>
  </tr>
</table>

2. London travel guide article. https://en.wikivoyage.org/wiki/London/City_of_London ([Initial request](https://github.com/osmandapp/OsmAnd/issues/17465#issue-1766005216) in this issue was about Tower bridge). 
- OsmAnd travel guide article has only 20 points (mostly embassies, while gpx file from wikivoyage [London_City_of_London_en.gpx.txt](https://github.com/osmandapp/OsmAnd/files/13377985/London_City_of_London_en.gpx.txt) has more than 120 points (to eat, to see, to sleep etc.). I need to add, that later we had only 14 points in our article. 
- Tower bridge  (https://www.wikidata.org/wiki/Q83125) is not shown.
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/59390b3a-30da-443e-9379-79bd54403020"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by vshcherb** [comment]
To do fix London points
