### ISSUE TITLE
Foot navigation doesn't avoid "avoid road"

### ISSUE THREAD

**Issue by miklcct** [osmandapp/OsmAnd#17492]
### Description
Foot navigation doesn't avoid the roads that I set to avoid in the map

### Steps to reproduce
Pick any start and end point and navigate on foot
Avoid a footpath
Enable temporary restrictions 

### Actual result
It still routes me on the avoided road

### Expected result
It finds another road for me

### Your Environment
OsmAnd Version: 
Android/iOS version: 
Device model: 

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/2827264/663df7b9-398f-4666-82a0-8092bcd4dd75"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by yuriiurshuliak** [comment]
The bug was not reproduced when turning on point-to-point navigation in the pedestrian profile. When pinching a specific road and pressing Avoid road, this road is no longer offered for navigation.

For a pedestrian, it is necessary to close a specific section of the pedestrian road, and sometimes several sections. Please try to use the night version or the beta version and select the road at maximum zoom by precisely clicking on it. You can read this documentation: https://osmand.net/docs/user/navigation/routing/osmand-routing/#avoid-specific-roads

OsmAnd~ 4.5.0#314m, released: 2023-06-30
OsmAnd 4.5.3, released: 2023-06-20

<table style="width:100%">
  </tr>
  <tr>
    <th>Nightly version</th>
    <th>Beta version</th>
  </tr>
  <tr>
    <td> <video source src="https://github.com/osmandapp/OsmAnd/assets/127092082/b9a60d4f-11a5-4d32-a0fd-e71b17369ffe"  width="300" height="auto"/>   </td>
    <td><video source src="https://github.com/osmandapp/OsmAnd/assets/127092082/fda787c1-524d-4236-b075-94514614d886"  width="300" height="auto"/>   </td>
  </tr>
</table>

**Comment by miklcct** [comment]
I can no longer reproduce the issue.
