### ISSUE TITLE
Slow calculation of Public transport route 

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd#17530]
## Description
* Calculation of Public transport route in New York (USA) is slow.
* Similar pedestrian routes is calculated for the same routes.

### Expected result

**Environment**
OsmAnd Version:
Android/iOS version:
Device model:

**Comment by vshcherb** [comment]
3 reasons to check:
1. Routing doesn't take main portion of time (so there is a big delay after route calculated)
2. There is too much pedestrian calculation (how much in %? ) 
3. Pedestrian calculation could be cached if it's same
4. Pedestrian calculation could be avoided if route is not short or something similar

**Comment by vshcherb** [comment]
@Dima-1 Tests in New york before and after?

**Comment by ivanPyrohivskyi** [comment]
To UI/UX designer.
I suggest set max count of changes for public transport to 1.
If route does not found then to suggest to increase count of changes.

Technical debt.
In my emulator (API 29) default count of changes equals to 0 (instead of 3 as set in configuration). For dummy users it is annoying when OsmAnd could not find any route and they don't know yet about configurations deeply.

**Comment by vshcherb** [comment]
To do: 
- [ ] C++
- [ ] Display other (>4) pedestrian routes from cache
