### ISSUE TITLE
Weird routing in Pulawy, Poland

### ISSUE THREAD

**Issue by annasoloviova** [osmandapp/Osmand#1760]
Phone BlackBerry Z10 stl100-1, OsmAnd version 2.1.1, release date (YMD) 2015-06-20, map file of (YMD) 2015-09-03, 51.41474N 21.96911E start, stop 51.44538N 21.97885E . 
![img_20150917_160032](https://cloud.githubusercontent.com/assets/12711814/10220973/d16c603c-6853-11e5-9b43-6dc0e475012f.png)
![img_20150917_160013](https://cloud.githubusercontent.com/assets/12711814/10220974/d1707bfe-6853-11e5-8fa0-8ca5a5c61b30.png)

**Comment by Zahnstocher** [comment]
OSM data was wrong.
A OSM mapper already fixed the data about 19 hours ago (too late for the October 1 build) 
https://www.openstreetmap.org/relation/3324014/history
Next OsmAnd map update should fix this.

**Comment by Zahnstocher** [comment]
It seems that the OSM mapper who created this wrong turn restriction did not understand how turn restrictions work.
I checked some of the turn restrictions he created and they are obviously wrong:
https://www.openstreetmap.org/relation/3324012
https://www.openstreetmap.org/relation/3324013
https://www.openstreetmap.org/relation/3324016

Do you have contact to the Polish OSM community?
If yes, please inform them so that they can review and correct his changes, in particular this changeset:
https://www.openstreetmap.org/changeset/18880523

This service also helps to detect turn restriction problems:
http://map.comlu.com/?zoom=19&lat=51.63886&lon=22.89746&layer=Grayscale&overlays=FTT
"Really only_straight_on? Deviation angle is 169.9°"

Thank you for this report, it was very important to detect these errors.

**Comment by vshcherb** [comment]
I know there is only forum on OSM, that looks like central place http://forum.openstreetmap.org/viewforum.php?id=23

**Comment by Zahnstocher** [comment]
@annasoloviova
I fixed more than 20 turn restrictions created or modified by this OSM mapper.
There are about 1600 changesets left to check, I checked about 250 changesets (the latest ones).
The oldest changeset I checked was 17126413.
