### ISSUE TITLE
Track recording is interrupted at route recalculating

### ISSUE THREAD

**Issue by Rowin63** [osmandapp/OsmAnd#17629]
## Description
When following a calculated route and also tracking this route, on every recalculating (when leaving this route) the tracking is interrupted. From the point of leaving the calculated route (the recalculating starts) until the point, the recalculating is finished, the tracked route is just a straight line. Osmand seems so busy on recalculating, it does not even move the map to follow the actual position. 

### Expected result

**Environment**
OsmAnd Version: +4.5.4
Android/iOS version: 13
Device model: Samsung Tab Act3

**Comment by Rowin63** [comment]
Here is an example of a situation when this happened:

) Starting point Hessendorf. Osmand calculated a route to Vienna ( ~100km)
) Instead of following this calculated route (yellow arrow) I took the other way (red arrow)
) Osmand needed about 4-5km / 3-4min for the recalculating
) during this time no track was recorded (green line is the recorded track, it´s just a straight line)

![Screenshot_20230716_080959_OsmAnd+](https://github.com/osmandapp/OsmAnd/assets/95540936/5143622c-1687-42f6-b622-235b2cc00c9d)

**Comment by DmitryAlexei** [comment]
Found no errors in realistic simulation using files attached. 

The only strange thing was that route recalculations were not voiced before the turn to Gemeinde Weitersfeld, but the route itself was recalculated multiple times (see video, sound is on). Probably after that issue https://github.com/osmandapp/OsmAnd/issues/16315 (too many messages about route recalculation when moving in the opposite direction). I'm not quite sure, that voice prompts can be improved in that case.

Perhaps in this case, the problems with track recording were caused by a bad GPS signal or a lack of memory on your device.

https://github.com/osmandapp/OsmAnd/assets/116079541/3065f3db-3978-4b53-97d8-46c7859dc830


Route on the OsmAnd map [link](https://test.osmand.net/map/?start=48.821417,15.739692&end=48.208366,16.372545&type=osmand&profile=car#13/48.8063/15.7818)

GPX files (zip archives):
1. [route.zip](https://github.com/osmandapp/OsmAnd/files/12130770/route.zip)
2. [Actual_route.zip](https://github.com/osmandapp/OsmAnd/files/12130772/Actual_route.zip)
3. [recorded_track.zip](https://github.com/osmandapp/OsmAnd/files/12130789/recorded_track.zip)

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/3d782d76-7ecb-422d-86e6-2491aec3512f"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/34770564-1b61-4409-b58e-ce39726bc963"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/cd47c003-4452-431f-8999-9c64f567f0b6"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by Rowin63** [comment]
Osmand really confuses me again and again. Today I set a finish point, about 120km away. Then I was driving around, never reaching and not even getting close to it. Tracking as well as route recalculating worked fine and without any interruptions. 🤔

**Comment by scaidermern** [comment]
I also tried to reproduce this but I couldn't. OsmAnd 4.5.6, Android 10, Samsung Galaxy S9.

Maybe for some reason your device didn't have enough free RAM and OsmAnd's route recalculation lead to the track recording service being killed. Just a guess.

**Comment by Rowin63** [comment]
I don´t know and don´t know how to find out... The Tab Act3 has 4GB and everytime I have a look at it there is about 1GB available.

**Comment by vshcherb** [comment]
4GB is not available per app! You can see how much available in Development -> Dalvik memory - max 64-128 MB

**Comment by Rowin63** [comment]
I know, but I meant as answer to the general question "if the device does not have enough free RAM". I think it has.

**Comment by vshcherb** [comment]
> ) Osmand needed about 4-5km / 3-4min for the recalculating

That's not how it works it recalculates full route 100 km and that takes 3-4 min...

Other observations could be valid due to high load on the system but hard to reproduce and hard to fix. We definitely need to spend more time on fast routing rather than this issue.

**Comment by vshcherb** [comment]
We fixed an issue with route recaultion that caused Application Not Responding (ANR), so it could be related fixed
