### ISSUE TITLE
Constant "Cannot download mapillary (raster tiles) " toast

### ISSUE THREAD

**Issue by 825i** [osmandapp/OsmAnd#17709]
## Description
Even though I have disabled Mapillary everywhere I can find. I am getting an error whenever I zoom in/out of a map. I'm using local files and offline maps but I am getting this constant toast. Even if I go online it doesn't go away. I don't have any DNS / VPN filtering or anything else. The toast notification is truncated so I can't see any useful information either.

![Screenshot_2023-07-24-21-54-55-931_net osmand-edit](https://github.com/osmandapp/OsmAnd/assets/58630825/4638d12b-28b2-4721-8925-72b785f60c80)

### How to reproduce
Open OsmAnd, move around the map and zoom in/out get a consistent notification as aforementioned. 

### Actual result
Constant complaints that Mapillary (raster tiles) couldn't be downloaded. I have no idea why or what for when I have no other over/under layers. I am not using any online maps and I have removed all local files for Mapillary and turned it off everywhere I can find. 

### Expected result
That it either downloads these Mapillary raster tiles or stops harassing me with these toast notifications.

**Environment**
OsmAnd Version: 4.4.7
Android/iOS version: Android 13
Device model: Xiaomi 13 Ultra

**Comment by DmitryAlexei** [comment]
Have you tried to reset to default profiles you used with Mapillary plugin? 
Settings > Driving (for example) > go to the bottom of the list > Reset to default (see https://osmand.net/docs/user/personal/profiles#actions). But first make a backup of important settings.

You can also try to clear cash of Mapillary online tiles in Maps > Local > Online maps (https://osmand.net/docs/user/personal/maps#local-maps)

If problem persists, please send us Logcat.log file (after you see this message on the screen). You can attach it here or send it to support@osmand.net.
How to send logs see https://osmand.net/docs/user/troubleshooting/crash-logs#crash-and-logcat-logs

**Comment by scaidermern** [comment]
Check if you have any overlay or underlay maps enabled. If so, disable them. If Configure map / overlay/underlay map is not present, then enable the online map extension first. Afterwards, check if there are overlay/underlay maps enabled.

If I recall correctly, someone else in one of the Telegram OsmAnd groups had exactly the same problem (or was it you?). And I think this user had a Mapillary layer enabled somewhere but didn't see it because the online maps plugin was _disabled_. But maybe I got that wrong, I'm not really sure.
