### ISSUE TITLE
map goes blank when zoomed out

### ISSUE THREAD

**Issue by muzirian** [osmandapp/Osmand#1777]
Map goes blank when zoomed out, eve when the scale shows 10km.running ver 2.1.1. World base map isnt installed, but still downloaded local area are way too large to still fill the screen

**Comment by xmd5a2** [comment]
Please clarify - do you have world basemap installed or not? If not then it's expected behavior.

**Comment by muzirian** [comment]
Worldmap is not intalled, but still downloaded map is large enough to zoom out even more,only if its displayed.

**Comment by vshcherb** [comment]
I recognize that request as a feature, indeed we had an issue with maps < 11th zoom and in order to display everything better and adopt rendering for basemap,  we decided to split it to 11th zoom level. It doesn't take much and it is highly recommended to have 150MB of basemap, usually detailed maps are taking much more space. It is possible to have displayed some data from original maps, but it has some rendering issues.

**Comment by muzirian** [comment]
Thanx for the response :)

**Comment by sonora** [comment]
Let's merge this to #2818.
