### ISSUE TITLE
Navigation arrow gets stuck on turns

### ISSUE THREAD

**Issue by lcosmin** [osmandapp/OsmAnd#18018]
## Description

Noticed this when using Android Auto and map being set to automatically rotate to the navigation direction and using an external GPS receiver sending data via the Android Mock Location feature.

Behavior exhibited [here](https://drive.google.com/file/d/1R784BpefqeBS-1is7KFvmr7bU1L1xDM8/view?usp=sharing).

It might not be very clear in the video, but the arrow gets stuck for a few moments when the map needs to rotate, then "jumps" to the actual position. 
You can notice that it's not a "jump' caused by a GPS error, as the green (recorded) track fits the road ok, just that the navigation arrow freezes for a while on turns, and it did it often during that navigation session (almost on every turn).

### How to reproduce

Navigate on AA (will try to test with regular on phone navigation too and/or without external gps), set map to be rotated to point to the navigation direction.

### Actual result

Arrow on maps gets stuck on turns

### Expected result

Smooth navigation.

**Environment**
OsmAnd Version: 4.5.10
Android/iOS version: Android 13
Device model: Samsung S20 FE

**Comment by scaidermern** [comment]
Sounds like #17505 and possibly #16081.

The workaround for #16081 is: Disable Settings / Profile / General settings / Animate own position. Check if this works for you, too. I'm not sure how Android Auto is related to this bug.

**Comment by lcosmin** [comment]
I can confirm I had "Animate own position" enabled, _but_ - because i've seen it mentioned in another ticket - I'm not using rendering engine v1, but v2. 
I'll try the animate option tomorrow, see if it fixes anything. Also tried the external GPS receiver with some other nav app and I saw no issues, so I definitely suspect there's an issue in OsmAnd (given the number of complaints in the other tickets, too).

**Comment by lcosmin** [comment]
didn't notice the issue with "animate own position" disabled anymore; will have to re-test with the external GPS too

**Comment by DmitryAlexei** [comment]
@sonora please, have a look at https://osmand.net/docs/user/navigation/guidance/map-during-navigation#animate-my-location

**Comment by sonora** [comment]
@DmitryAlexei Ah, very god, thank you! It had not shown up when I searched, probably because the headline did not contain _"Animate own position"_. But it has a good text and explanation. I have aligned and combined the two, please see if you like it once it arrives on the web server.

- [ ] Dmitry, would you know if "Animate own position" really only affects the map **during navigation**? I believe it affects the map panning also when not navigating, as long as simply the map is linked to your location, i.e. you always after you have tapped the blue "My position" widget?
- [ ] Also, our explanation of the similar "No animations" (https://osmand.net/docs/user/map/interact-with-map/#no-animations) is a bit brief. Would you know what exactly is affected by the setting, so we can provider a better sentence, like maybe explicitly list all "map animations" which are affected?

**Comment by lcosmin** [comment]
Adding a bit of extra info, maybe it's useful:

I did a re-test, a longer trip with the external GPS and animate own position disabled. 

Regarding the current issue: with "animate own position" off there seems to be an improvement, but I think it's only masking the real issue, as I've still noticed tiny lags around road bends, but not as visible as before.  If I were to guess, I'd say that rotating the map smoothly around a road bend gets too cpu(/gpu?) intensive and it makes the whole thing lag because the actual position of the car changes faster than the software is able to draw it on screen.

And with the external GPS I've noticed another issue which I haven't seen with the internal one... sometimes, the navigation arrow turns to a blue circle (as if stopped), but keeps moving on the map.
