### ISSUE TITLE
Crashes when zooming or moving map

### ISSUE THREAD

**Issue by Saturo78** [osmandapp/OsmAnd#18123]
## Description
Since the laste update the app crashes when i zoom or move the map.

### How to reproduce
Zoom or move the map

### Actual result
Blackscreen and crash to home screen

### Expected result

**Environment**
OsmAnd Version: 4.5.5
Android/iOS version: 13
Device model: SG 20 FE

**Comment by TheSnoozer** [comment]
Can you provide a crash log (https://osmand.net/docs/user/troubleshooting/crash-logs/)?

**Comment by DmitryAlexei** [comment]
@Saturo78 
You need to update OsmAnd to the latest version. Known crashes with zooming have been fixed already.

**Comment by Saturo78** [comment]
I´m already on 4.5.8. Crashlogs are sent.

**Comment by DmitryAlexei** [comment]
@Saturo78 the latest version from Google play is 4.5.10 and almost all the crashes have been resolved
please also try beta version from Google play or the latest nightly build 
see https://osmand.net/docs/versions/nightly_versions

Most likely, your issue is related to the 3d relief display. So disabling this option (menu > configure map > 3d relief) or updating the app to the latest version, should resolve it.

**Comment by Saturo78** [comment]
Thank you. I have installed Osmand via Fdroid, so i have to wait for the update.

**Comment by Saturo78** [comment]
Just to give feedback: disabling the option (menu > configure map > 3d relief) changes nothing.

**Comment by ironspock** [comment]
I'm facing similar issues.
App Version: 4.5.8 (F-Droid)
OS: Android 12

**Comment by DmitryAlexei** [comment]
@ironspock please update the app (4.5.10 available)
