### ISSUE TITLE
Zooming with volume buttons does not work

### ISSUE THREAD

**Issue by Nine-Tailed** [osmandapp/OsmAnd#18193]
Zooming with volume buttons does not work.

```
OsmAnd Version: OsmAnd~ 4.6.0#783m, Дата выпуска: 2023-09-19
Device model: poco f3
```

**Comment by DmitryAlexei** [comment]
@Nine-Tailed Please, go to menu > settings > your profile > general settings and enable *Volume buttons as zoom* option

in OsmAnd~ 4.6.0#785m, released: 2023-09-20 works fine

**Comment by Nine-Tailed** [comment]
@DmitryAlexei, see video
https://github.com/osmandapp/OsmAnd/assets/12549744/2848bf81-2139-4ebe-b317-437bf81ea391

Updated version - OsmAnd~ 4.6.0#787m, Дата выпуска: 2023-09-20

**Comment by Nine-Tailed** [comment]
@DmitryAlexei, my profile
![Osmand.zip](https://github.com/osmandapp/OsmAnd/files/12677343/Osmand.zip)

**Comment by yuriiurshuliak** [comment]
The bug couldn't be replicated despite our efforts to do so. We attempted the following steps in order to reproduce it:

-We imported the profile you provided for this bug.
-We enabled the use of the Volume buttons as a zoom option in the settings.
-We attempted to replicate the issue by using the volume up and down buttons.
-We confirmed that map zooming worked correctly using the Volume buttons.

It's worth noting that we didn't encounter any issues with other profiles or settings. It's possible that the problem is related to hardware rather than software.

OsmAnd~ 4.6.0#791m, released: 2023-09-21

https://github.com/osmandapp/OsmAnd/assets/127092082/98b1aa6d-4d6a-4951-ab01-2c3aa6990f12

**Comment by mikehgentry** [comment]
I'm seeing this too on a Samsung XCover 4s. As far as I know it was working on 4.5.x, but I only checked it after seeing this report so can't say when it stopped working for me.

I think @sonora also has the same phone, maybe he can check it.

**Comment by scaidermern** [comment]
Works on my phone, Samsung S9, Android 10, OsmAnd 4.6.1.

**Comment by Nine-Tailed** [comment]
@yuriiurshuliak, hmm, I just found out that zooming with volume buttons only works if the external input device option is enabled and keyboard is selected. If the external input device is set to no, then zooming stops working.

**Comment by scaidermern** [comment]
> @yuriiurshuliak, hmm, I just found out that zooming with volume buttons only works if the external input device option is enabled and keyboard is selected.

I can confirm that.

**Comment by DmitryAlexei** [comment]
OsmAnd~ 4.6.0#792m, released: 2023-09-21
For me works even if *External input devices* option is disabled

https://github.com/osmandapp/OsmAnd/assets/116079541/edbe390f-2872-4ff4-bc80-2a9615e8c982

**Comment by vshcherb** [comment]
To do: check if we can support zoom in without set external input keyboard

**Comment by nazar-kutz** [comment]
This issue occurred after a global refactoring of button event handling. 
I thought I fixed it here https://github.com/osmandapp/OsmAnd/pull/18178. 
But it seems I missed the details that led to the bug. So I fixed them here https://github.com/osmandapp/OsmAnd/pull/18223.
