### ISSUE TITLE
Broken routing at multiple locations near Leermos, Austria

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/OsmAnd#18215]
### Describe the routing engine used (required)

- [x] OsmAnd's in-app offline routing
- [ ] Any online routing provider (YOURS, openrouteservice, OSRM, etc.)

### Describe your routing Profile (required)

Car

### Describe your start and end points (required)

First scenario:
From: 47.40693, 10.86679
To: 47.41050, 10.86235
https://osmand.net/map?start=47.406929%2C10.866795&end=47.410503%2C10.862352&mode=car#16/47.402943/10.864573

and

Second scenario:
From: 47.41071, 10.86214
To: 47.41433, 10.85431
https://osmand.net/map/?start=47.410709%2C10.862140&end=47.414326%2C10.854309&mode=car#15/47.405315/10.858170

### Describe the actual route (required)

First scenario: Routing via primary_link (longer in duration & time)
Second scenario: Routing via track next to primary road

### Describe the expected route (required)

First scenario: Route via trunk road "Fernpass"
Second scenario: Routing via primary road

### Describe what Maps you used (online or offline) (required)

- [x] Offline maps offered within the OsmAnd app for download. 
- [ ] Online (tile / raster) maps 

### Your Environment (required)

```
OsmAnd Version: 4.6.1
Android/iOS version: 10
Device model: Samsung S9
```

### Anything else? (optional)

First scenario:
Routing from south to north is wrong, routing from north to south is correct:
![photo_2023-09-24_20-32-11](https://github.com/osmandapp/OsmAnd/assets/1040784/8df5fe27-4119-4416-829f-5fa65f145211)

Second scenario:
Routing is broken in both directions. OsmAnd jumps from primary road to track.
![photo_2023-09-24_20-52-54](https://github.com/osmandapp/OsmAnd/assets/1040784/60e962b0-2b14-4e00-b71c-84e57043eb00)

**Comment by yuriiurshuliak** [comment]
The bug was not reproduced. When attempting to reproduce it in both scenarios by following the provided coordinates to create the route, no issues with routing were observed. We attempted to reproduce it both with and without live updates enabled.

OsmAnd~ 4.6.0#818m, released: 2023-09-29

<table style="width:100%">
  </tr>
  <tr>
    <th>First scenario 1</th>
    <th>First scenario 2</th>
    <th>Second scenario 1</th>
    <th>Second scenario 2</th>
  </tr>
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/0efeb232-c43b-4811-9c90-fcb659858e50"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/8006953c-1682-4738-8bdc-925c3890206a"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/d9974cf1-82fd-4468-8f05-1f7813e34c1f"  width="300" height="auto"/> </th>
  <th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/2e16c158-5821-4002-a799-4775df4e212f"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by scaidermern** [comment]
I can't reproduce it either with OsmAnd 4.6.2 with the same map as before. Looks like it was a bug in 4.5.x.
