### ISSUE TITLE
Chinese transliteration (to pinyin) has many duplicate syllables

### ISSUE THREAD

**Issue by pieleric** [osmandapp/OsmAnd#18272]
### Description

When the map data (eg, POI names, street names...) is only in Chinese characters, but OsmAnd is set to display the map in English with transliteration, then many names are incorrectly transliterated because many characters are replaced by multiple syllables instead of one. For instance, “大同大学” would normally be written in pinyin "datong daxue". However, currently, it's shown as "dadai tongtong dadai xue". 

In some cases, some characters are replaced by up to 4 syllables! It makes the map quite unreadable, especially for someone not very familiar to Chinese... which defeats the purpose of transliteration!

### Steps to reproduce

Download China Shanxi Province map.
Select Map rendering/Map language/English (or any other "latin" language) + Use latin name if available .
Go to : 40.09503° N, 113.34373° E

### Actual result

The name of the building is "dadai tongtong dadai xue". See screenshots.
Note that the same issue happens to all the POI and streets names displayed.

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/99444/35b6bfdc-f046-4fff-abdc-03d0f600edf8"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/99444/b2ba3279-ca2b-47ac-b1de-9358c790ec0d"  width="300" height="auto"/> </td>
  </tr>
</table>

### Expected result

A little bit of context about the Chinese characters, pronunciation, and pinyin transliteration: in a sentence, every Chinese character correspond to a single syllable. Most Chinese characters are almost always pronounced the same in any context. However, it can happen that they have multiple pronunciation. Often the variation happens solely on the tone, which is shown in pinyin as various accents on top of the latin characters. When transliterating, an error on the tone is only a minor error. Some characters have more variation, and are pronounced completely differently depending on the context. This is relatively rare.

For example:
* 学 is always pronounced "xué"
* 中 is usually pronounced "zhōng", but sometimes "zhòng"
* 乐 is pronounced sometimes "yuè" and sometimes “lè”

Ideally, only the right pinyin syllable based on the context should be displayed. That might be quite complex to do (without including a huge dictionary or neural network into OsmAnd just for this task). However, if only the most common syllable of each character is used, that should work 95% of the time.

My guess is that currently OsmAnd uses a dedicated library to obtain the pinyin writting for each Chinese character. It's possible that the call to the library return every possible pronunciation, and OsmAnd just displays all of them, concatenated. If so, most likely, displaying just the first possibility should be fine.

### Your Environment (required)

```
OsmAnd Version: OsmAnd~ 4.6.0#806m, released: 2023-09-25 (Android)
Device model: One Plus 11 (Android 13), also Xiaomi 11 Lite (Android 12)
```

**Comment by yuriiurshuliak** [comment]
The bug has been reproduced. While setting up OsmAnd to display the map in English with Chinese transliteration, there is an issue with the transliteration of the name "大同大学," which is incorrectly rendered as "dadai tongtong dadai xue" instead of the correct "datong daxue." To reproduce this issue, follow these steps:

- Download the China Shanxi Province map.
- Choose English as the map language. Go to Menu → Configure map → Map rendering → Map language.
- Locate the coordinates: 40.09503° N, 113.34373° E.
- Verify the transliteration of the name "大同大学."

You can also access this area on OpenStreetMap through the following [Link](https://www.openstreetmap.org/search?query=40.09503%2C%20113.34373#map=19/40.09503/113.34373).

OsmAnd~ 4.6.0#844m, released: 2023-10-06

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/8ada2d65-847f-4ffb-a83b-8db9cfcba1f5"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/40be582b-25e7-45b9-89b0-97ee10162879"  width="300" height="auto"/> </th>
  </tr>
</table>


![photo_2023-10-06_15-40-31](https://github.com/osmandapp/OsmAnd/assets/127092082/ecc3187e-9350-4b34-8402-0151d8ca1c53)

**Comment by vshcherb** [comment]
We still won't be able to do correct glyph combination (limitation of the pinyin4j library), so "大同大学" -> "dà tóng dà xué"

**Comment by vshcherb** [comment]
https://github.com/osmandapp/OsmAnd-tools/commit/397aa23031dcbe26e651a8887663613fdaa78d86

**Comment by yuriiurshuliak** [comment]
The bug has been resolved. Following the recent fix, the name is now correctly displayed. But it is worth noting that the correct rendering doesn't have spaces between the characters: "datong daxue."

OsmAnd~ 4.7.0#1346m, released: 2024-01-10

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/f98ad6f5-a456-4cb7-af11-cdb368554662"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/5581849f-f3fb-42b5-b9f6-cea93961579c"  width="300" height="auto"/> </th>
  </tr>
</table>
