### ISSUE TITLE
seamarks: fog signal and radar transponder symbols not rendered

### ISSUE THREAD

**Issue by quantenschaum** [osmandapp/OsmAnd#18285]
### Description

see title

possible reason: `seamark:radar_transponder:category`and `seamark:fog_signal:category` are consumed by entity conversion in `rendering_types.xml`, such that `<apply_if additional="seamark:fog_signal:category" ...` will never be activated.

### Steps to reproduce

look at this test data

[test.zip](https://github.com/osmandapp/OsmAnd/files/12807697/test.zip)

### Actual result

![image](https://github.com/osmandapp/OsmAnd/assets/3985599/2caee326-5cd7-4c0c-bf2c-0ed201416f86)

### Expected result

![image](https://github.com/osmandapp/OsmAnd/assets/3985599/595ccfd3-39b8-4634-ba6c-2aa623152d20)

### Your Environment (required)

```
OsmAnd Version: 4.5.10
Android/iOS version: 11
Device model: Nokia X20
```

**Comment by DmitryAlexei** [comment]
OsmAnd~ 4.6.0#871m, released: 2023-10-13 Not reproduced

The display of marine objects has changed significantly since the last release. Please see screenshots and tell if everything is ok for you.

Tested on
1. https://www.openstreetmap.org/node/10242033482 Coordinates 55.88 / 20.54
2. https://www.openstreetmap.org/node/1852947125 Coordinates 53.5408465 / 9.9512549 (object is in the middle of the screen)

Actual result:

<table style="width:100%">
  <tr>
    <th>1 </th>
    <th> 2 </th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/97146c58-4da9-4419-b909-c4a0ebbb455e"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/21b95ba3-64e0-47e3-9ae7-b02c049f84cc"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by quantenschaum** [comment]
Actually not. The legend does already show the fog signal and radar transponder icons as expected.

![image](https://github.com/osmandapp/OsmAnd/assets/3985599/ad4d142d-3f38-4175-b5c4-bf8bfbb8df6d)
![image](https://github.com/osmandapp/OsmAnd/assets/3985599/bfbca49c-725a-4135-8e47-4ade129384b6)

Just some of the tags do not make it into the OBF and some are not used in the `render.xml`.

**Comment by xmd5a2** [comment]
This bug was introduced by this [commit](https://github.com/osmandapp/OsmAnd-resources/commit/500655f165b36d3fc702638f12008dd41bffb09a)
[line 6949](https://github.com/osmandapp/OsmAnd-resources/blob/master/obf_creation/rendering_types.xml#L6949)
`
<entity_convert pattern="tag_combine" separator="." from_tag="seamark:fog_signal:category" if_not_tag1="seamark:light:character" if_not_tag2="seamark:light:1:character" from_tag4="seamark:fog_signal:group" from_tag5="seamark:fog_signal:period" from_tag6="seamark:radar_transponder:category" from_tag7="seamark:radar_transponder:group" to_tag1="seamark:light:character"  additional="text"/>
`
Problem is in fact that **entity_convert pattern="tag_combine"** removes original tags them from the object but we use **seamark:fog_signal:category** and **seamark:radar_transponder:category** in rendering. I propose to add parameter **keep_original_tags="true"** to **entity_convert pattern="tag_combine"**.
I've commented out these strings until this is implemented.

**Comment by vshcherb** [comment]
@xmd5a2 you just need to write  ``` to_tag8="seamark:fog_signal:category" ```

**Comment by quantenschaum** [comment]
Same for `radar_transponder` and `seamark:fog_signal=yes` is not processed at all.

**Comment by xmd5a2** [comment]
> @xmd5a2 you just need to write `to_tag8="seamark:fog_signal:category"`

Doesn't works. This also produces combined value. I think these lines should be commented out until this is fixed.

**Comment by xmd5a2** [comment]
@quantenschaum seamark:fog_signal=yes is not described in wiki and used infrequently: just 46 appearances.

**Comment by quantenschaum** [comment]
@xmd5a2 It is described in the Wiki: https://wiki.openstreetmap.org/wiki/Tag:seamark:fog_signal%3Dyes

And it does make sense in cases where there is a fog signal but it is not specified what kind of signal it is.

**Comment by DmitryAlexei** [comment]
OsmAnd~ 4.6.0#1205m, released: 2023-12-13
World seamarks map and standard maps are updated to the latest versions (it is stated that they are from 01/12/2023)

1. https://www.openstreetmap.org/node/1852947125 Coordinates 53.5408465 9.9512549 Object is tagged `seamark:fog_signal:group`.
As I understand, this object should have a *[Fog signal icon](https://wiki.openstreetmap.org/wiki/Tag:seamark:fog%20signal:category=horn?uselang=ru)* attached. But it still displays the same way (as before), it **does not have fog icon**.

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/d6b2cab1-e9d7-4ec1-a45c-f8aa1621a570"  width="300" height="auto"/> </td>
  </tr>
</table>
