### ISSUE TITLE
Track selection doesn't apply in Configure Map – Search

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd#18298]
## Description
Track selection doesn't apply in Configure Map – Search

### How to reproduce
* Open **Menu** – **Configure Map** – **Tracks**
* Tap on **Search** button
* Select first tracks, tap **Apply**

### Actual result
<table style="width:100%">
  <tr>
    <td><video src="https://github.com/osmandapp/OsmAnd/assets/9365308/2e16bd5d-1abb-4f68-9002-76278ecb698f
"  width="300" height="auto"/> </td>
  </tr>
</table>   

* After taping Apply, search screen is closed, but track selection doesn't apply

### Expected result
* Selected tracks will be visible on the map

**Environment**
OsmAnd Version:
Android/iOS version:
Device model:

**Comment by sonora** [comment]
So instead of fixing ever more bugs and features on this duplicate (and for folder users not very useful) screen, isn't it about time
- we point _Configure map > Tracks_ to the same screen we already have when going via _MyPlaces > Tracks_,
- and produce there a good and fast mode showing which tracks (of which folders) are visible, and facilitates easily adding more or removing some, like is e.g. proposed and illustrated in #18024 ?

**Comment by vshcherb** [comment]
@sonora that's ongoing discussion doesn't lead us to solution. We have 2 screesn: 1 to select tracks to get visible on map, 1 screen to manage tracks. 

Manage tracks is more generic and suit for all people but it doesn't provide very simple function to quickly enable / disable tracks to get visible on map. 

Nobody is going to have 2 duplicated screens it will be nonsense, if we don't get how to make flawless and easy experience of selecting tracks on map, we will just delete this screen and that's it.

**Comment by sonora** [comment]
@vshcherb You're right, we're going around in cicles...

But in my mind you can't say we are lacking an "essy experience" idea, because the way how to create intuitive "Visible" and "Visible selection" modes is long proposed, see here https://github.com/osmandapp/OsmAnd/issues/18024#issue-1868410588.
