### ISSUE TITLE
cycleway:left/right no shouldn't change bicycle routing

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/OsmAnd#18327]
### Description

Bug 1: OsmAnd fails to route across an intersection in bicycle mode.

Bug 2: OsmAnd fails to recognize a turn restriction in bicycle and car mode.

### Steps to reproduce

Bug 1:
https://osmand.net/map/?start=51.071415,13.750559&finish=51.071308,13.750978&type=osrm&profile=car#19/51.071489/13.750721
From: 51.071415,13.750559
To: 51.071308,13.75097

Bug 2:
https://osmand.net/map/?start=51.071531,13.750822&finish=51.071308,13.750978&type=osrm&profile=car#19/51.071489/13.750721
From: 51.071531,13.750822
To: 51.071308,13.75097

Happens with and without live updates. Driving style in bicycle mode has no influence.

Online routing at https://osmand.net/map is correct, offline routing isn't.

### Actual result

Bug 1:
OsmAnd chooses a detour instead of routing directly across the intersection (in bicycle mode). Routing in the other direction works fine.

![01](https://github.com/osmandapp/OsmAnd/assets/1040784/f770181e-8f88-49d6-8626-138dd6c2680f)

Bug 2:
OsmAnd performs a left turn although there is a [turn restriction that forbids turning left](https://www.openstreetmap.org/relation/120884) (in bicycle and car mode).

![02](https://github.com/osmandapp/OsmAnd/assets/1040784/d71f7256-2e99-4402-83ba-7b050ad5f7f0)

### Expected result

Bug 1:
OsmAnd routes directly across the intersection.

Bug 2:
OsmAnd forbids turning left and chooses a different route.

### Your Environment (required)

```
OsmAnd Version: 4.6.2
Android/iOS version: 10
Device model: Samsung S9
```

**Comment by yuriiurshuliak** [comment]
Bug 1:
The issue has been replicated. In the cycling mode, when transitioning between two points, OsmAnd opts for a detour instead of a direct route through an intersection. Interestingly, if you swap the start and end points, the routing in the opposite direction works perfectly. You can view the route in the web version using this link: [[link](https://test.osmand.net/map/?start=51.071420,13.750560&finish=51.071310,13.750980&type=osmand&profile=bicycle#20/51.07137/13.75058)].

Bug 2:
We've also successfully reproduced this problem. However, it's worth noting that the application currently generates the route differently from what was originally described in the bug report. For both the car and bicycle profiles, the route takes a detour through a footway zone.

Bug 2 (Web version):
We've identified a similar bug in the web version. The car profile generates the route correctly, while the bicycle profile, just like in the application, directs the route through a footway zone.

Here are the links to the web versions:

Car Profile: [[link](https://test.osmand.net/map/?start=51.071530,13.750820&finish=51.071308,13.750978&type=osmand&profile=car#17/51.07152/13.74927)]
Bicycle Profile: [[link](https://test.osmand.net/map/?start=51.071530,13.750820&finish=51.071308,13.750978&type=osmand&profile=bicycle#19/51.07153/13.75051)]
OsmAnd~ 4.6.0#868m, released: 2023-10-13

<table style="width:100%">
  </tr>
  <tr>
    <th>Bug 1(first direction)</th>
    <th>Bug 1(other direction)</th>
    <th>Bug 2(Bike)</th>
    <th>Bug 2(Car)</th>
  </tr>
  <tr>
  <th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/0be11ed4-3b8f-4010-8266-bf907a01795f"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/0f988e83-6c5f-4963-9e5d-61eb43629016"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/91106a88-9213-463a-bccc-178ae238ab2b"  width="300" height="auto"/> </th>
  <th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/732b0d85-1e64-44f6-b44c-6cbe00b473b8"  width="300" height="auto"/> </th>
  </tr>
</table>

<table style="width:100%">
  </tr>
  <tr>
    <th>Web version Car</th>
    <th>Web version Bike</th>
  </tr>
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/5f095df3-096f-4a9f-be32-319b60995b86"  width="300" height="auto"/> </th>
  <th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/e674bd77-6172-41ee-83cf-e3f54d666e30"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by scaidermern** [comment]
I've found another, similar problem. Probably caused by the same bug.

https://osmand.net/map/?start=51.064087,13.740272&finish=51.065044,13.739969&type=osrm&profile=car#18/51.064863/13.740437
From: 51.064087
To: 13.740272

Left: bicycle mode, right: car mode

![foo](https://github.com/osmandapp/OsmAnd/assets/1040784/ea127027-40c0-4775-a586-94b72c91af81)

In bicycle mode OsmAnd fails to route across the intersection, choosing a strange detour instead.
In car mode everything is fine.

**Comment by vshcherb** [comment]
No issue with bug 2 - there is a road restriction https://www.openstreetmap.org/relation/120884.
Second issue is related to interesting tagging - https://www.openstreetmap.org/way/776800012
It's actually oneway because of 
```
cycleway:right:oneway | yes
cycleway:left | no
```
A bit more complicated siutation with https://www.openstreetmap.org/way/33713954

But I think first of all we need to understand tagging scheme and actual situation

**Comment by scaidermern** [comment]
> No issue with bug 2 - there is a road restriction https://www.openstreetmap.org/relation/120884

Exactly, and OsmAnd ignores it! Please reopen. 

What about the third issue?

**Comment by scaidermern** [comment]
> Second issue is related to interesting tagging - https://www.openstreetmap.org/way/776800012 It's actually oneway because of
> 
> ```
> cycleway:right:oneway | yes
> cycleway:left | no
> ```

Sounds correct to me. The direction of the way is from east to west, the direction of the route is from west to east. So there is no cycleway for the direction of the route and thus cyclists must use the road. I fail to understand why OsmAnd forbids cycling from west to east. 


> But I think first of all we need to understand tagging scheme and actual situation

By closing this ticket? That's not going to fix anything here.

**Comment by scaidermern** [comment]
> What about the third issue?

The third issue has been resolved. There was a wrong bicycle=no at the road (https://www.openstreetmap.org/way/30503863).

The other two issues remain unresolved.

**Comment by vshcherb** [comment]
@scaidermern I did not see any issues, routing is correct based on restrictions on cycleway. You can't go the opposite direction on one-way road , it is applicable for bicycles as well. Description is pretty vague, please specify which object you want to pass and why it is passable according to tags


Based on my investigation I don't see any issue but I could have misinterpreted the cycleway tags

**Comment by scaidermern** [comment]
> @scaidermern I did not see any issues, routing is correct based on restrictions on cycleway. You can't go the opposite direction on one-way road , it is applicable for bicycles as well. Description is pretty vague, please specify which object you want to pass and why it is passable according to tags
> 
> Based on my investigation I don't see any issue but I could have misinterpreted the cycleway tags

Let's take a look at it step by step.

From: 51.071415,13.750559
To: 51.071308,13.75097
![foo](https://github.com/osmandapp/OsmAnd/assets/1040784/0ea74f23-d0e0-4598-b352-183ef56fd3c4)

The direction of the [road](https://www.openstreetmap.org/way/776800012) is from west to east (right to left). The user wants to drive into the other direction, from east to west. Therefore, the only relevant tag here is `cycleway:left=no` because it applies to the _left_ side of the road, which is according to the direction of the road the one the user wants to drive on (the southern side of the road). There is _no_ oneway tag for this direction and `cycleway:left=no` simply indicates that there is no cycleway present. It does _not_ indicate a `bicycle=no`.

Is this clearer now?

For reference, any other routing engine is handling this case correctly:
* [GraphHopper](https://www.openstreetmap.org/directions?engine=graphhopper_bicycle&route=51.07142%2C13.75056%3B51.07110%2C13.75114#map=19/51.07132/13.75090&layers=N)
* [OSRM](https://www.openstreetmap.org/directions?engine=fossgis_osrm_bike&route=51.07142%2C13.75056%3B51.07110%2C13.75114#map=19/51.07133/13.75090&layers=N)
* [Valhalla](https://www.openstreetmap.org/directions?engine=fossgis_valhalla_bicycle&route=51.07142%2C13.75056%3B51.07110%2C13.75114#map=19/51.07133/13.75088&layers=N)
[BRouter](https://brouter.de/brouter-web/#map=19/51.07148/13.75050/osm-mapnik-german_style&lonlats=13.750384,51.071447;13.751065,51.07129)

Only OsmAnd fails:
* https://test.osmand.net/map/?start=51.071565,13.749754&finish=51.071186,13.751407&type=osmand&profile=bicycle#17/51.06961/13.74632

So, please reopen and fix it :)

**Comment by vshcherb** [comment]
@scaidermern reading your answer.
- https://www.openstreetmap.org/way/776800012 goes from right to left and cycleway-left is no, it means opposite direction of driving in Germany. So you can't go from Right (West) to Left (East) cause you need to use left side of the road (according to orientation)

**Comment by scaidermern** [comment]
> @scaidermern reading your answer.
> 
>     * https://www.openstreetmap.org/way/776800012 goes from right to left and cycleway-left is no, it means opposite direction of driving in Germany. So you can't go from Right (West) to Left (East) cause you need to use left side of the road (according to orientation)
> 
> 
> > cycleway:left=no simply indicates that there is no cycleway present. It does not indicate a bicycle=no.
> 
> Why? and how user will indicate then that you can't go from right to left? `bicycle:left=no`?

No, such a tag doesn't exist. There is `bicycle:forward=no` and `bicycle:backward=no` to indicate that cycling is forbidden in one direction only. The same way as there is `vehicle:forward=*` etc. None of these tags are present here. 

> No I still can't understand... One lane is oneway and the opposite direction, another lane doesn't exist so you can't travel then.

You are still mixing up cycle lanes with the regular road. If there is no cycleway present than bicycles use the regular road. It's as easy as that. The presence or absence of a cycleway doesn't tell you anything about the legal permission to use the OSM way. We have access tags for that. Don't mix up access tags with infrastructure tags, they are a completely different thing.

Try to ask one of your colleges if you are unsure about these tags. Hopefully there is a person in your team that understands basic access and infrastructure tags. If not, get one.

**Comment by scaidermern** [comment]
I agree that it is a little bit irritating that there are tags with left/right and others with forward/backward. No idea why there isn't one consistent scheme.

The important part here is, as already explained, to distinguish between physical presence and legal permission.

**Comment by scaidermern** [comment]
Another approach for an explanation: there are many roads with a cycleway=no tag. Does OsmAnd forbid cycling on these roads? I don't think so, it shouldn't. Why does it forbid cycling in this example then?

**Comment by scaidermern** [comment]
Please reopen. This bug is still present with OsmAnd 4.6.6 and November maps. All other routing engines handle this case correctly, only OsmAnd fails to route across this intersection.

**Comment by xmd5a2** [comment]
@scaidermern I propose to remove `from_tag="cycleway:right:oneway" from_value="yes" ` rule. This doesn't breaks [https://github.com/osmandapp/OsmAnd/issues/9782](https://github.com/osmandapp/OsmAnd/issues/9782) and fixes this issue. Looks like it is wrong after this discussion.

**Comment by scaidermern** [comment]
> @scaidermern I propose to remove `from_tag="cycleway:right:oneway" from_value="yes" ` rule. This doesn't breaks #9782 and fixes this issue. Looks like it is wrong after this discussion.

I can't really comment on that since I'm not familiar with this syntax.

`cycleway:right:oneway=yes` and `cycleway:left:oneway=yes` (and also value `-1`) describe whether that the cycleway can only be used in one direction.

`cycleway:right=no` and `cycleway:left=no` only describe whether a separate cycleway exists or if cyclists have to use the road instead. They don't tell you anything about in which direction cyclists are allowed to travel.

**Comment by xmd5a2** [comment]
Fixed. `Germany_sachsen` map will be regenerated today.

**Comment by yuriiurshuliak** [comment]
The bug has been fixed. Currently, in two cases the route is built correctly.

OsmAnd~ 4.7.0#1248m, released: 2023-12-20

<table style="width:100%">
  </tr>
  <tr>
    <th>Bug 1(first direction)</th>
    <th>Bug 1(other direction)</th>
    <th>Bug 2(Bike)</th>
    <th>Bug 2(Car)</th>
  </tr>
  <tr>
  <th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/5a76ce25-fca3-45fd-96d9-52b214065955"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/1533cd9f-78df-49c1-abce-b01dda651098"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/6f5768f0-b956-4f82-ab2d-511a61b85b17"  width="300" height="auto"/> </th>
  <th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/9c62c01d-b3dc-478a-9c03-53d393c5d5f1"  width="300" height="auto"/> </th>
  </tr>
</table>
