### ISSUE TITLE
maxweight/maxweightrating tags ignored using the truck profile

### ISSUE THREAD

**Issue by aearil** [osmandapp/OsmAnd#18346]
### Describe the routing engine used (required)

- [x] OsmAnd's in-app offline routing
- [ ] Any online routing provider (YOURS, openrouteservice, OSRM, etc.)

### Describe your routing Profile (required)

Using OSMAnd truck profile, fastest, no general restrictions but a few ponctual ones nowhere near the issue in question.

Vehicle parameters : 
* weight: 44t
* height: 4m
* width: 2.55m
* length: 16.5m
* max speed: 85km/h

### Describe your start and end points (required)

From: Route de Tours, Noyant
Location: geo:47.51543,0.12843?z=17
https://osmand.net/map?pin=47.51543,0.12843#17/47.51543/0.12843

To: Location: geo:47.49898,0.10373?z=18
https://osmand.net/map?pin=47.49898,0.10373#18/47.49898/0.10373

### Describe the actual route (required)

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/45526730/f3de20a7-7718-4fb9-a0dd-fffbc824342a"  width="300" height="auto"/> </td>
  </tr>
</table>

### Describe the expected route (required)

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/45526730/06f82ccb-a367-41db-99b2-b02ca966bbc9"  width="300" height="auto"/> </td>
  </tr>
</table>

### Describe what Maps you used (online or offline) (required)

- [x ] Offline maps offered within the OsmAnd app for download. 
- [ ] Online (tile / raster) maps 

France Pays de la Loire, 2023-10-01 at 02:10 am

### Your Environment (required)

```
OsmAnd Version: OSMAnd~ 4.5.10
Android/iOS version: Android 11
Device model: Xiaomi redmi 10
```

### Anything else? (optional)

Since version 4.5.8 (I think), OSMAnd has started seemingly ignoring some maxweight restrictions using the truck profile. While taking the screenshots for this bug report I realised that if I set the car profile to a weight of 4.5 tonnes (this particular street is max 3.5t), the routing is correct. 

Noyant's Grande Rue also has `maxweight:conditional: none @ delivery` which might have something to do with this?

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/45526730/de3c74f7-ef79-458a-8f2a-056d4c363f96"  width="600" height="auto"/> </td>
  </tr>
</table>

**Comment by yuriiurshuliak** [comment]
The bug has been reproduced. By using the truck profile with the specified vehicle parameters for navigation, a route is calculated from the initial coordinates 47.515427,0.128413 to the final coordinates 47.498953,0.103721. However, this route does not align with the designated parameters.

The navigation system fails to consider the "maxweight" tag and proceeds to guide through a particular road segment on OSM, as indicated by this link: https://www.openstreetmap.org/way/108354924#map=14/47.5051/0.1367&layers=N

You can also view the route in the web version through this link: https://test.osmand.net/map/?start=47.515433,0.128428&finish=47.499131,0.103802&type=osmand&profile=car#15/47.5112/0.1074

This issue is directly related to the bug mentioned in this GitHub report: https://github.com/osmandapp/OsmAnd/issues/18307

OsmAnd~ 4.6.0#880m, released: 2023-10-17

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/a8a1f7aa-7fcb-4910-bb86-d66d157db7eb"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/a3d060b4-1bdf-47c2-8367-b114dc09d781"  width="300" height="auto"/> </th>
  </tr>
</table>
