### ISSUE TITLE
Widget "Elevation profile" not loaded at navigation start

### ISSUE THREAD

**Issue by Dollarius** [osmandapp/OsmAnd#18411]
### Description

Similar to https://github.com/osmandapp/OsmAnd/issues/18326 but for the "Elevation profile" widget.
@nazar-kutz Maybe the fix is similar to https://github.com/osmandapp/OsmAnd/pull/18344 ?

### Steps to reproduce

1. Kill and restart OsmAnd app
2. Start cycling navigation based on a gpx file in order to load the "Elevation profile" widget
3. Navigation starts but no widget "Elevation profile" is shown on the map screen
4. Wait a long time with the screen on (>5min): no changes
5. Switch off the screen and then back on: the "Elevation profile" widget is now displayed
6. The same can be achieved by switching cycling/walking profiles back and forth

### Actual result

No visible widget.

### Expected result

The widget should be loaded upon starting the navigation.

### Your Environment (required)

OsmAnd Version: 4.6.0#897m, released 2023-10-22
Android/iOS version: Android 13
Device model: Samsung Galaxy S23 SM-S911B/DS

**Comment by yuriiurshuliak** [comment]
The bug was not reproduced. Here are the steps to reproduce:

-Add the Elevation widget (Navigate to Menu → Configure screen → Bottom panel → Available widgets → Elevation profile).
-Create a GPX track for the cycling profile.
-Initiate navigation using the bicycle profile on the previously created GPX track.
-Upon constructing a route, the Elevation widget promptly shows up.

OsmAnd~ 4.6.0#910m, released: 2023-10-24


https://github.com/osmandapp/OsmAnd/assets/127092082/343d371c-d221-43c7-aabf-05568269d63e

**Comment by Dollarius** [comment]
I just upgraded to 2023-10-24 and the problem seems to be gone.
Downgrading to 2023-10-22, the problem reappears,
so I believe it got fixed in the latest release even though I could not find the specific commit that fixed it.
