### ISSUE TITLE
OsmAnd ignores turn restriction in bicycle and car mode

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/OsmAnd#18422]
### Describe the routing engine used (required)

- [x] OsmAnd's in-app offline routing
- [ ] Any online routing provider (YOURS, openrouteservice, OSRM, etc.)

### Describe your routing Profile (required)

Car and bike routing profiles

### Describe your start and end points (required)

Start: 51.062943,13.736733
End: 51.063786,13.7364

Bicycle (also wrong online):
https://osmand.net/map/?start=51.062943,13.736733&finish=51.063786,13.736469&type=osrm&profile=bicycle#17/51.06336/13.73420
Car (correct online, wrong offline):
https://osmand.net/map/?start=51.062943,13.736733&finish=51.063786,13.736469&type=osrm&profile=car#17/51.06266/13.73454

### Describe the actual route (required)

OsmAnd's internal routing engine ignores a [only_straight_on turn restriction](https://www.openstreetmap.org/relation/2952247) in bicycle _and_ car mode.

![photo_2023-10-24_08-44-17](https://github.com/osmandapp/OsmAnd/assets/1040784/c9475642-1fd1-4e43-b9f5-d68fcadc3887)

### Describe the expected route (required)

OsmAnd respects the turn restriction and calculates a detour.

### Describe what Maps you used (online or offline) (required)

- [x] Offline maps offered within the OsmAnd app for download. 
- [ ] Online (tile / raster) maps 

### Your Environment (required)

```
OsmAnd Version: 4.6.4
Android/iOS version: 10
Device model: Samsung S9
```

### Anything else? (optional)

Same wrong behavior as already reported in #18327 ("Bug 2"). Unfortunately the problem in this ticket was not fixed but just ignored instead 🤷

Start: 51.071531,13.750822
End: 51.071308,13.75097
https://osmand.net/map/?start=51.071531,13.750822&finish=51.071308,13.750978&type=osrm&profile=car#19/51.071489/13.750721
Turn restriction: https://www.openstreetmap.org/relation/120884

**Comment by vshcherb** [comment]
- Car needs to be checked
- Bicycle doesn't use car restrictions (so it's known issue if it's an issue) - I think it's open discussion

**Comment by scaidermern** [comment]
>     * Bicycle doesn't use car restrictions (so it's known issue if it's an issue) - I think it's open discussion

Why not? 🤔 If a turn restriction doesn't apply to bicycles then the tag `except=bicycle` should be set. Without this tag, a turn restriction applies to all vehicles.

**Comment by vshcherb** [comment]
This is the question if we need to support that on regional level of Germany or Worldwide, I think data is not consistent about bicycle routing.

**Comment by yuriiurshuliak** [comment]
The bug was not reproduced. Here are the steps to try and reproduce it:

- Download the map for Saxony, Germany and enable Live Updates.
- Start by using the Bicycle profile.
- Input these coordinates for the starting point: 51.062943,13.736733, and these coordinates for the destination: 51.063786,13.7364.
- Then switch to the Car profile and use the same coordinates.
- In both scenarios, it can be noticed that the navigation is built correctly, without ignoring the turning restrictions.

However, it's important to note that the web version generates different routes for Bicycle and Car:

For Cars: [Car Route Link](https://test.osmand.net/map/?start=51.062942,13.736728&finish=51.063785,13.736395&type=osmand&profile=car#17/51.06282/13.73405)

For Bicycles: [Bicycle Route Link](https://test.osmand.net/map/?start=51.062942,13.736728&finish=51.063785,13.736395&type=osmand&profile=bicycle#18/51.06354/13.73516)

OsmAnd~ 4.6.0#930m, released: 2023-10-27

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/f09ecb35-1b33-4ae3-b96a-56f9cdfcb582"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/7e64037a-ebce-4fde-be30-51cbe182a951"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by scaidermern** [comment]
I can confirm. For some reasons the turn restriction is now respected, for both car and bicycle. Strange 🤷‍♂️

@vshcherb This also means that turn restrictions _are_ respected in bicycle routing.

**Comment by vshcherb** [comment]
@scaidermern I'm very confused now and we need to be attentive cause there is a bug somewhere... probably it's still that hard bug with live data.
