### ISSUE TITLE
Traffic_calming=hump or bump

### ISSUE THREAD

**Issue by Barrocas** [osmandapp/Osmand#1846]
These points on the road used to be rendered with an orange circle marking their location (like POI), it was easy to see them on the map and preview their location/distance on navigation.

Now they ate still rendered, but only visible at closer zoom levels (not visible at driving speeds), and lost the orange circle.
We still get a visual and alert sound warning on the left side info signals, but we cannot see where they are on the map while driving.

The warning:
![screenshot_2015-10-28-16-35-30](https://cloud.githubusercontent.com/assets/4006691/10795779/3619f568-7d93-11e5-8fa5-a2f9199cb31a.png)
I was almost hitting the hump, and I know were it was, since I placed it on the map, but for other users, and when humps are around corners, it was usefull to see them on map.

Here is another hump, only visible at closer zoom level:
![screenshot_2015-10-28-16-36-02](https://cloud.githubusercontent.com/assets/4006691/10795858/8d481d4c-7d93-11e5-8d41-0d9db5882ca9.png)

**Comment by xmd5a2** [comment]
Ok, I moved them back to POI. Couldn't imagine how they can be useful but now I see.

**Comment by pierre-haessig** [comment]
Hi,

I was about to create a new issue, but I think my issue is related to this. Indeed, I came across the map of a parking lot with several `traffic_calming=hump` and I find their display too obtrusive!

Now reading the previous discussion, maybe this strong display is useful while driving (but then the same idea would lead to highlighting pedestrian crossings as well), but not while browsing the map in general. 

![screenshot_20170807-094821](https://user-images.githubusercontent.com/1010404/29029165-05a5dc00-7b87-11e7-89f3-4f9b66f2a686.png)

This is the place of the screenshot: https://osmand.net/go.html?lat=48.08777&lon=-1.7047477&z=18

In order to satisfy the different use cases, maybe there should be a generic option "highlight road obstacles as POI"?
