### ISSUE TITLE
Online routing : wrong voice indication

### ISSUE THREAD

**Issue by SKOHscripts** [osmandapp/OsmAnd#18498]
### Description

While using https://openrouteservice.org as an online routing service, a right turn on the map will be announced as "turn left". It has to be changed because it is a really serious problem ! We can't trust the voice anymore.

### Steps to reproduce

Just use the online service. 

### Actual result

Turn left, while map shows a right turn.

### Expected result

Turn right and map shows a right turn.

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: OsmAnd~ 4.5.10
Android/iOS version: Android 12
Device model: FP4
Crash-Logs: ?
```

**Comment by yuriiurshuliak** [comment]
The bug was not reproduced. Here are the instructions to recreate it:

- Set up Custom Online routing and choose Openrouteservice.
- Download the Amsterdam, Netherlands map.
- Pick two points with a right turn and activate the navigation simulation.
- While making a right turn, ensure that the voice prompts correctly indicate the right turn.

Provide more detailed information and videos.

OsmAnd~ 4.6.0#966m, released: 2023-11-03

<table style="width:100%">
  </tr>
  <tr>
    <th>Attached user track</th>
    <th>Unattached track</th>
  </tr>
  <tr>
    <td> <video source src="https://github.com/osmandapp/OsmAnd/assets/127092082/a441bf67-6e0a-4a14-8916-8a26a9dac4ad"  width="300" height="auto"/>   </td>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/82f4a154-595e-469b-a21a-4ef0849cc643"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by SKOHscripts** [comment]
I tried a few things with different voices, but the result was always the same. 

This one is using offline bike routing. All is fine. (Sorry for the sound quality).
https://github.com/osmandapp/OsmAnd/assets/63296980/a5e33a82-4d04-4445-95bd-9b90c493456c

**Comment by SKOHscripts** [comment]
But this one is using openrouteservice with bike support. 
All is strange. 
https://github.com/osmandapp/OsmAnd/assets/63296980/02a0f212-220e-4a13-9b48-9d31a580e64e

![signal-2023-11-05-23-00-22-051.jpg](https://github.com/osmandapp/OsmAnd/assets/63296980/c12332eb-f974-4d6a-af8d-5ad2323c57c0)

**Comment by yuriiurshuliak** [comment]
The bug was not reproduced.We attempted to test bicycle navigation using Openrouteservice with the Berlin map as an illustration. The voice prompts functioned as expected, accurately announcing the turns.

Additionally, we encountered a server error when choosing the Cycling option for Amsterdam and New York, but everything functioned correct for Berlin and Paris.

OsmAnd~ 4.6.0#991m, released: 2023-11-07

<table style="width:100%">
  </tr>
  <tr>
    <th>Left turn</th>
    <th>Right turn</th>
    <th>Cycling (api server error)</th>
  </tr>
  <tr>
    <td> <video source src="https://github.com/osmandapp/OsmAnd/assets/127092082/3d5a2789-87aa-4645-b512-da715687a20c"  width="300" height="auto"/>   </td>
    <td><video source src="https://github.com/osmandapp/OsmAnd/assets/127092082/d82bab00-699f-496e-afe6-d7f2ece571bf"  width="300" height="auto"/>   </td>
    <td><video source src="https://github.com/osmandapp/OsmAnd/assets/127092082/2ee548b7-d1d9-405d-8541-3d529459d38e"  width="300" height="auto"/>   </td>
  </tr>
</table>
