### ISSUE TITLE
Avoid unpaved roads in Moped profile

### ISSUE THREAD

**Issue by dolf-s** [osmandapp/OsmAnd#18538]
### Describe the idea (required)

Currently, the only navigation restriction allowed in the Moped Profile is to avoid Ferries. The consequence of this is that unless an unpaved road or track is explicitly not permitted for mopeds, the routing algorithm will route over such a track if it is the shortest/fasted route. Needless to say that it isn't fun to go offroad with a small Vespa ....

### Tell us about the expected behaviour (required)

I would like to have more options available to restrict the routing algorithm like they are available in the other profiles. If I could only have 1 addition restriction, it would have to be to allow for avoiding unpaved roads.

### Tell us about alternatives you've considered (required)

I've tried looking at using the motorcylce profile but it leads me over motorways and all kinds of other streets which are not allowed for mopeds. Likewise, the bicycle profile leads me over bicycle paths which are not allowed for mopeds.

**Comment by xmd5a2** [comment]
How to test: [http://www.openstreetmap.org/#map=13/52.743736/21.479216](http://www.openstreetmap.org/#map=13/52.743736/21.479216)
Map: Poland_masovian_europe
Turn on **"Avoid unpaved"** option in moped navigation setting
_start_lat=52,76667, start_lon=21,39525
target_lat=52,71987, target_lon=21,54322_
Routing should avoid [this way](https://www.openstreetmap.org/way/498038264)

Route without "Avoid unpaved":
![Screenshot_2023-11-22_09-47-04](https://github.com/osmandapp/OsmAnd/assets/5829014/2f5c1507-e9b1-4bd8-aa34-99de9c13a11f)

Route with "Avoid unpaved":
![Screenshot_2023-11-22_09-46-34](https://github.com/osmandapp/OsmAnd/assets/5829014/38dff80b-3bbe-42f3-9b73-0a17fa0b07e3)

**Comment by yuriiurshuliak** [comment]
The bug was fixed. Here are the steps to reproduce:

- Download the Poland - Masovia map
- Select a moped profile.
- Input the correct coordinates: 52.76667, 21.39525 and 52.71987, 21.54322 to create the route.
- View the route without the "avoid unpaved roads" option.
- View the route with the "avoid unpaved roads" option activated.

OsmAnd TestFlight 4.6.2.6

<table style="width:100%">
  </tr>
  <tr>
    <th>The "avoid unpaved roads" option is disabled</th>
    <th>The "avoid unpaved roads" option is enabled</th>
  </tr>
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/26ee1b3b-12ea-4c4a-9fdb-4a253b0ca240"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/5b2c2250-148f-425c-a7c5-1f1311fe62b0"  width="300" height="auto"/> </th>
  </tr>
</table>
