### ISSUE TITLE
Trim search term before searching POI

### ISSUE THREAD

**Issue by pft** [osmandapp/Osmand#1856]
Trailing (or leading) whitespace in POI search messes up results.

E.g. "rijksmuseum " (sic) yields 4 results, none of which is the actual Rijksmuseum, but Museum Rijksmuseum van Oudheden, Museum Rijksmuseum voor Volkenkunde etc., which have the literal space in the result.

It is easy/common to get the trailing space (e.g. by using type completion software).

Interestingly, a leading space -- but who would type that -- yields no results at all.

**Comment by CJTmmr** [comment]
Searching POI this is working Okay;

When Searching an Adress - Street  with "Search street in neighborhood cities" with a trailing space (caused by auto-completing keyboard) no (or not all) results are found.

I use "Search in neighborhood cities" often to find a street in villages of hamlets (which are not indexed)

This is probably a small simple fix?

Thanks
Kees-Jan
