### ISSUE TITLE
Option to Skip address search by default, when creating a favorite

### ISSUE THREAD

**Issue by opk12** [osmandapp/OsmAnd#18580]
### Describe the idea (required)

A setting to auto-Skip the address search, when I create a favorite.

### Tell us about the expected behaviour (required)

When I make a favorite, the app waits to search the address, which I do not need. So I always press Skip anyway.

(Edit: Removed any reference to the network connection. There is a connection to `osmand.net` (bugreport [here](https://github.com/osmandapp/OsmAnd/issues/18637)) but it is not the cause of the delay, thank you @scaidermern and @DmitryAlexei.)

### Tell us about alternatives you've considered (required)

I make a large number of favorites, when I survey for OpenStreetMap data, so I would avoid pressing Skip every time, if possible.

**Comment by ceever** [comment]
Totally agree! 🙏

I don't even understand why this is a default to begin with. What do I need the address for when creating a favourite? It's right there in the map with proper GPS location, no one cares about its address!

Thanks for opening this issue ... this nonsense functionality wastes a lot of my time as well.

**Comment by scaidermern** [comment]
@opk12 Address search is performed offline, so your Internet connection is not relevant.

Apart from that I agree. The address search is rarely useful and most of the time just steals time from the user.
Maybe add a button at the following dialog to insert the address. In case anyone needs this functionality.

**Comment by ceever** [comment]
> @opk12 Address search is performed offline, so your Internet connection is not relevant.
> 
> Apart from that I agree. The address search is rarely useful and most of the time just steals time from the user. Maybe add a button at the following dialog to insert the address. In case anyone needs this functionality.

I don't think that is entirely true.

Definitely there is something influencing the address search if the connection is sketchy. When I am offline, I quickly get an address. When I am in a bad WiFi, it can take up to 5 sec for the address search to come up with something.

**Comment by DmitryAlexei** [comment]
@opk12 cannot reproduce with 4.5.10 and latest nightly build versions
- OsmAnd works completely offline, so no internet connection is needed to create favorite
- sometimes the process of favorite creation may take a bit longer due to map indexing on a fresh start (or maybe when maps are stored on a SD card) 
- see videos (note, that it was recorded in airplane mode). The first one was recorded immediately after the application was launched, and the second one was recorded a moment later.

 <table style="width:100%">
  <tr>
  </tr>
  <tr>
    <td><video src="https://github.com/osmandapp/OsmAnd/assets/116079541/15e45774-3c5d-4b2c-9dc2-5333e6210949"  width="300" height="auto"/> </td>
    <td><video src="https://github.com/osmandapp/OsmAnd/assets/116079541/f4e102df-b769-4f4f-8ca2-2e74762c7c4b"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by ceever** [comment]
> @opk12 cannot reproduce with 4.5.10 and latest nightly build versions
> 
>     * OsmAnd works completely offline, so no internet connection is needed to create favorite
> 
>     * sometimes the process of favorite creation may take a bit longer due to map indexing on a fresh start (or maybe when maps are stored on a SD card)
> 
>     * see videos (note, that it was recorded in airplane mode). The first one was recorded immediately after the application was launched, and the second one was recorded a moment later.
> 
> 
> video_2023-11-22_13-10-56.mp4
> 	
> video_2023-11-22_13-12-08.mp4

Did you actually read the issue description?

The issue describes an issue happening with bad internet connection.

How does producing two screen recordings where both times the phone is offline cover the issue condition "bad internet connection"?

**Comment by DmitryAlexei** [comment]
@ceever have you read my answer? 
OsmAnd is fully offline app, so *Looking for address...* message doesn't indicate bad internet connection. 
So this issue cannot be reproduced with bad internet connection either.
First video recorded on a fresh app start, second one - a few seconds later.

<table style="width:100%">
  <tr>
  </tr>
  <tr>
    <td><video src="https://github.com/osmandapp/OsmAnd/assets/116079541/b9ad42ce-dbd8-4adf-9a52-c78435638a78"  width="300" height="auto"/> </td>
    <td><video src="https://github.com/osmandapp/OsmAnd/assets/116079541/d5748d1b-f305-4df4-8a8a-33829a918970"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by ceever** [comment]
I heard you loud and clearly.  But even you have to admit that OsmAnd is indeed not a completely offline app; it downloads maps, it uploads edits to OSM, it might even send statistics while the user is online.

I don't know what OsmAnd is doing when retrieving the address and on which Android specific features it relies on to do so. But it could well be that OsmAnd uses the Android API in a way that behaves differently depending on the connection speed of the internet ... who knows. Maybe the API records the app behaviour for Google and therefore works badly if the connection is on but bad — I have no idea, could be everything.

However, the issue is out there and I can confirm to have experienced this behaviour. Unless you come up with a better way to show that we appear to have hallucinations, proving something else and stating that the original issue cannot be because you are 100%-certain that it acts in the way you believe, is not sufficient to resolve such an issue.

I am sorry to say that, but I am also a little surprised about the way you treat this issue — an experienced developer would never make such a statement. An experienced developer would have had dozens of cases where he believed in a certain reality but was later surprised to learn that the opposite was true, just because he forgot to think of that one little thing.

And you know what, I find it hilarious that in your third video the address lookup takes about twice as long as in the first video while >>surprise<< your internet connection is on Edge. Could be a coincidence or the very problem we are arguing about here.

**Comment by DmitryAlexei** [comment]
I have great respect for your comments and would suggest trying to test the creation of favorites in various conditions on your device. Including with a bad or missing Internet connection.
In my experience, creating the first favorite on a map that has not been used before (located far from the current location) takes longer. When creating subsequent favorites on the same map - much less. 
It also may take some more time if you downloaded your maps not in the internal storage (e.g. on a SD card) or if you have a device with slower (or insufficient) RAM.

**Comment by ceever** [comment]
Well, independently of the question whether the connectivity does influence the address lookup, the original query is not about the speed of the lookup, but the sense of the lookup. It wastes time and nerves for 100 % of the users, while only 5% might actually use it.

Hence, this should really be optional and not an enforced feature because some developer though it could be useful to people. OsmAnd is already not the quickest app and the search is even another topic. Why have another features in place that make the app slower and more difficult to use?

**Comment by ceever** [comment]
@opk12  ... and now just for the record: In how many of these 2–3,000 cases did you actually need the address lookup?

**Comment by vshcherb** [comment]
I will keep this for reference but we're not going to fix it. Favorites are designed to input the data and that's why they attach all additional info collected, if you want to create a marker fast - then you need to use marker.

If you want to have some predefined case or complex scenario, you better look into quick actions functionality.

**Comment by scaidermern** [comment]
> If you want to have some predefined case or complex scenario, you better look into quick actions functionality.

How does using a quick action solve the problem of an unnecessary, delaying address search?

During surveys, I often add many GPX waypoints. Each new track point triggers an address search that is delaying my work.

**Comment by ceever** [comment]
> I will keep this for reference but we're not going to fix it. Favorites are designed to input the data and that's why they attach all additional info collected, if you want to create a marker fast - then you need to use marker.
> 
> If you want to have some predefined case or complex scenario, you better look into quick actions functionality.

I am sorry, but this decision seems kind of arbitrary to me.

Some developer thought of this to be a great idea, clearly never did a deeper use case and implementation analysis of this feature, and now we are stuck with it, wasting 2 seconds of everyones time every time they create a favourite, just because you are too proud to acknowledge that OsmAnd is not the pinnacle of app development.

Why doesn't it do the address collection _after_ the editing window opened like it happens when I select an arbitrary point in the map?

Why is the address even filled into the name field if it is already in the address field? Why this duplication, to waste another two seconds of the user's time that now has to delete this "name" to put in their own proper and custom name?

Why do you argue that just because there is an address field for favourites that it also has to be filled? That's again totally arbitrary — just because something is there doesn't mean you are forced to put in data. It is called extensions for a reason, because they are not standard and thus even less reason to enforce them onto the user unless he specifically wants them. 

Where does this address data even come from and how acurate is it? It doesn't seem to be a well established nor certified way to determine the correct address. I just clicked a point in the map which came up with a house number, but actually the house with that number was on the other side of the street. And you are telling us that it is absolut necessary to have such rather inaccurate data derived time-consumingly and then stored with the favourite? This doesn't compute.

Also, what kind of an advice is it, to recommend markers instead of favourites when they have clearly different application scenarios? How about we use Mapy.cz or Google Maps, because maybe there we don't have the same problem?

Furthermore, regarding your second advice about the quixk actiona, switching from a poorly implemented feature to one that is even more poorly can't barely be the solution. Because if I count correctly, with "quick actions" I need three steps to get to the regular editing window of a favourite: 1) Hit the "Quick actions" button, 2) navigate the pointer to the right location (and don't tell me you already pointed the map in the right location, because you would know where the pointer would appear), and 3) Hit "Add favourite". However, the usual way was simply to 1) select a POI or arbitrary point on the map, and 2) hit the add favourite icon. So, I don't even understand why you call this feature "quick actions" when it clearly takes longer. But let me guess no one really has reviewed the addition of this feature properly, because it was thought to be a "cool" addition, right?



I have great respect for the work and effort you put into OsmAnd and I understand that users of open source software can be very unthankful sometimes, but what is really frustrating to see since I have joined this issue tracker is the lack of awareness what the standard user of OsmAnd really needs or just a clear concept what the priorities for development of OsmAnd should really be. To me this forum seems to be white noise with arbitrary arguments, arbitrary decisions and arbitrary implementations, and no clear user and implementation strategy.

**Comment by aceman444** [comment]
This is only getting worse (slower) with Osmand 5.1. Also, the address search happens also when displaying POIs (not just creating favorites). Until the address is found, no POI details are shown for the touched item. Here, the address may be more useful, but it could be filled by an async thread later, after all other POI details are shown instantly.

**Comment by scaidermern** [comment]
> Until the address is found, no POI details are shown for the touched item.

Agreed. When tapping on a POI, sometimes there is a significant delay of 1-2 seconds where the bottom drawer is just empty (except for the name of the POI). This is tedious.

**Comment by opk12** [comment]
It is a deeper problem that easing surveyor's work is not among the top priorities, not because you use our map for free (it is welcome and intended by the license), but because the app target is the non-professional (this is not a GIS) OSM user-contributor (they are synonyms, because to use the map is to verify the map). The delay and other issues have made me switch to surveying with a real GIS (SMASH + gpx overpass results) and OsmAnd is my fall back for navigation.

**Comment by aceman444** [comment]
It seems this got somewhat better in OsmAnd 5.2. Some POI details are already shown while the address is still being searched.
