### ISSUE TITLE
Lane Assistant / Favorites along a track / road name - is this as it is meant to be?

### ISSUE THREAD

**Issue by Rowin63** [osmandapp/OsmAnd#18589]
### Description

Recently the widgets "lanes" and the "favorites along a track" / "road name" are displayed side by side and now the second one is not readable anymore. 

### Steps to reproduce

---

### Actual result

as it is displayed

### Expected result

As it was before - "road name" / "favorites along a track" on top and the "lanes" below.

### Your Environment (required)

OsmAnd Version: +4.6.6
![Screenshot_Fahrspur-Anzeige](https://github.com/osmandapp/OsmAnd/assets/95540936/238a6015-d6a6-47c2-9fd9-37d8dc7dd1bd)

**Comment by Rowin63** [comment]
HI! 
Here´s the settings screens. Main, left, top.
But there is no optional setting for "lanes" and "points along athe track" or "street name". Only on or off.
Anyway I did not change anything here and this issue seemed to appear with the last update (to +4.6.6.). before it was displayed as usual. And still the same device (Samsung S20+).

Now as long as there is no "lane"-widget, everythging is displayed correctly, "street name" or "points along the route" are displayed in one line on top. As soon as the "lane"-widget appears, it does in the left top corner and forces the other in the right top corner.


![Screenshot_20231121_142355_OsmAnd+](https://github.com/osmandapp/OsmAnd/assets/95540936/a474871c-f67a-4e14-bc82-98cb7f573397)
![Screenshot_20231121_142347_OsmAnd+](https://github.com/osmandapp/OsmAnd/assets/95540936/a80eaa5b-48a9-4092-8f49-f4fc2ed001be)
![Screenshot_20231121_142406_OsmAnd+](https://github.com/osmandapp/OsmAnd/assets/95540936/02c44c2d-cedf-4ea6-9a6a-d65aab1e14bc)

**Comment by Rowin63** [comment]
This is how it was positioned and still is in the 1042 Beta

![Screenshot_20231121_105840_OsmAnd~](https://github.com/osmandapp/OsmAnd/assets/95540936/c45e9755-e983-4fd1-82a5-e740c9094d43)

**Comment by vshcherb** [comment]
@Rowin63  did you change it manually widgets or they clashed in 1 row automatically?

**Comment by Rowin63** [comment]
It does happen automatically. I´m not aware of changing anything - changing what?

But now I see a difference: 

![Screenshot_20231121_142406_OsmAnd+](https://github.com/osmandapp/OsmAnd/assets/95540936/f3c8d282-f9f5-4dd9-8d93-50cacd671688)

**Comment by Rowin63** [comment]
In the Beta each line has a number: 1, 2 and 3

**Comment by yuriiurshuliak** [comment]
The bug was not reproduced. To try, follow these steps:

- Choose a car profile and add "Lanes" and "Street names" widgets to the top bar.
- Activate navigation simulation and check how the top widgets display. The "lanes" widget appears below, separate from the others.
- Next, attempt to add a "map marker bar" and place a marker on the map. The "lanes" widget still appears separately.

However, the "Street names" widget and the "map marker bar" is not fully readable. 

For now we ask you to import your profile settings for us to check. 

OsmAnd~ 4.6.0#1071m, released: 2023-11-22

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/df190940-7b29-40c7-b64b-6c1f56a9092d"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/e7fa6c2e-2c80-4708-93b7-deae237af904"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/87258125-16c6-4bd6-9aab-e4418dd3cfef"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by Rowin63** [comment]
As said before, I solved the problem by adding pages to the top section. 
Now it works as it did before and as expected.

But of course you can see the profile. Had to rename the *.osf to *.txt for uploading here.
[Auto.txt](https://github.com/osmandapp/OsmAnd/files/13452036/Auto.txt)
