### ISSUE TITLE
Erroneous public transport stop names

### ISSUE THREAD

**Issue by MeijiRestored** [osmandapp/OsmAnd#18701]
### Description

When using public transport routing to go from one stop to another of a specific bus ligne (in my case, this one : https://www.openstreetmap.org/relation/13654149 ), wrong stop names are displayed. This seems to happen only for this line as other lines have correct stop names shown.

### Steps to reproduce

Route from one stop to another of the 19 (Angres → Hénin-Beaumont) bus line. I tested it from IUT to Bibliothèque in my case.

### Actual result

Incorrect stop names :
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/42336759/66b15e86-c52d-4149-92e8-6f8b000d1b4c"  width="300" height="auto"/> </td>
  </tr>
</table>
Also notice the incorrect line name (19: Bourdonnais)
Seems like the names are coming from another unrelated bus route 100km away :
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/42336759/5859e04d-9ca5-451b-bc31-b178da29897e"  width="300" height="auto"/> </td>
  </tr>
</table>

### Expected result

Stop names shown should be the correct ones. In this case, it would be IUT - André Boulloche - Bibliothèque.

### Your Environment (required)

```
OsmAnd Version: 4.6.0#1181m
Android/iOS version: Android 13
Device model: Poco X3 Pro 
```

**Comment by yuriiurshuliak** [comment]
The bug was not reproduced.  I attempted to replicate the issue by creating a route from IUT to Bibliothèque (50.438, 2.81062 - 50.43335, 2.82108) using the "Public Transport" profile, and the stops were correctly named. You can find the details and links for the routes I generated here:
OSM link: [Route](https://chat.openai.com/c/link)
Web version link: [Route](https://chat.openai.com/c/link)

Additionally, regarding the incorrect line name issue, upon checking the screenshot, it appears to display the route of bus 5, which is 74 kilometers away from the indicated route.

Here's the OSM link to the bus 5 route for reference: [Bus 5 Route](https://chat.openai.com/c/link)

Could you provide more detailed steps of encountering the error and perhaps a video demonstrating the issue? Also, I suggest updating the app and maps and retesting to see if the problem persists.

OsmAnd~ 4.6.0#1193m, released: 2023-12-11

<table style="width:100%">
  </tr>
  <tr>
    <th>Names of bus stops</th>
    <th>Incorrect line name</th>
  </tr>
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/4ac628c4-543d-450d-9ef1-8389053a1ec6"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/26c8f5a6-101b-4856-b781-a0b5a4cacc7c"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by MeijiRestored** [comment]
I was unable to replicate the problem too, I guess that was just a one off bug, probably with osmand live updates
