### ISSUE TITLE
Fix issue with disappearing first segment in the Route (after start)

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/OsmAnd#18787]
![telegram-cloud-photo-size-2-5195149036758355908-y](https://github.com/osmandapp/OsmAnd/assets/1042025/2bdeb479-8181-463a-bee6-c76b7d23c2f3)

https://github.com/osmandapp/OsmAnd/pull/18786

To do: test that after start of the route the whole route  (blue line) is visible

**Comment by DmitryAlexei** [comment]
To test: sometimes the route line is not visible while building navigation along existing recorded track  (it may be displayed or even hided on the map)

**Comment by yuriiurshuliak** [comment]
The bug was not reproduced. To reproduce it, I attempted by recording a track, making another one, and saving a point-to-point navigation track. Despite overlaying navigation on each track, the issue captured in the screenshot didn't recur. I made multiple attempts, closing the completed navigation and retrying, but unfortunately, couldn't achieve the same result.

OsmAnd 4.6.9, released: 2023-12-20

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/d27e3955-4047-40da-97ec-164a545359cc"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/55a9c28c-19a2-4688-b156-cad33e4d538b"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/6220ba37-ef68-42c5-b7bb-363d48af524d"  width="300" height="auto"/> </th>
  </tr>
</table>
