### ISSUE TITLE
Route generates Straight turn lanes where it could generate Straight and Slightly turn Right

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/OsmAnd#18789]
https://osmand.net/map/?start=48.529338,9.033508&finish=48.495223,9.219589&type=osmand&profile=car#14/48.5016/9.1309

[MUTE] Keep left (+C|+C|C) onto B 28 and go 1.6 km.  [Way 747131036](https://openstreetmap.org/way/747131036.171875)
[MUTE] Keep left (+C|+C|C) onto B 28 and go 1.6 km.  [Way 747131036](https://openstreetmap.org/way/747131036.171875)
[MUTE] Keep left (+C|+C|C) onto B 28 and go 2.3 km.  [Way 35560707](https://openstreetmap.org/way/35560707.171875)

**Expected**:
- [x] (+C|+C|TSLR)
- [x] Create a test and check it doesn't break other cases

**Check** why is muted:
- [x] https://github.com/osmandapp/OsmAnd/commit/fd7deb06e2cfdd33238ed409af58dd4e097b5499 - https://test.osmand.net/map/?start=49.177720,9.224997&finish=49.041469,9.267654&type=osmand&profile=car#17/49.16055/9.28215 (looks like this one shouldn't be muted)

**Comment by vshcherb** [comment]
Technical plan: do we have an example where (in our tests) where we need (+C|+C|C) and not (+C|+C|TSLR)

**Comment by ivanPyrohivskyi** [comment]
Examples in the tests where we have +C|C instructions.
In the tests we have two cases where present +C|C simultaneously
49.Turn lanes are shown as through lanes in lane overview https://github.com/osmandapp/OsmAnd/issues/12481
50.Turn lanes highlight wrong turn https://github.com/osmandapp/OsmAnd/issues/12933

But in fact these tests age ignored !
Because segments with turn lanes is set to NULL after _removeMuteGoAhead(result);_
Test before set to NULL _49.Turn lanes are shown as ..._ **Keep right (+C,TSLL|+C,TSLL)** ([MUTE] KR:C|C|+C|+C in test)
Test before set to NULL _50.Turn lanes highlight wrong ..._ **Keep left (+C|+C|+C,TSLR)** ("[MUTE] KL:+C|+C|+C|C" in test)

Causing of such behaviour related to comment above. We set this turns as muted and after this is deleting in _removeMuteGoAhead(result);_

**Comment by ivanPyrohivskyi** [comment]
Is need to fix Test framework if tested turn lanes is set to NULL, but in test case is present?

**Comment by ivanPyrohivskyi** [comment]
Why is muted [way 4228009](https://www.openstreetmap.org/way/4228009) ?
Because we mute all through turn lanes in [this place of code](https://github.com/osmandapp/OsmAnd/blob/26edf2392628bc37c30d57fe31115d33378867d3/OsmAnd-java/src/main/java/net/osmand/router/RouteResultPreparation.java#L1584).

I suggest solution that occur minimal change of tests (3 units). 
Solution: if any attached road has lanes count more than current segment - then need to speak.
Affected tests:
51.The wrong turn is announced in voice navigation (29183562 ~~[MUTE]~~ C:TL|+C) 
63. Turn is not indicated (also traffic lanes) (610913306 ~~[MUTE]~~ KR:TU|C|C|+TR)
70. Incorrect turn lanes (62775363 ~~[MUTE]~~ C:+C|TSLR)

Other solutions (different highway types or different count of lanes of current and previous segments) are affected approx 20 test units.

**Comment by vshcherb** [comment]
Latest status:  
- [x] Couldn't find +C|+C|C - probably fixed
- [ ] https://test.osmand.net/map/?start=49.177720,9.224997&finish=49.041469,9.267654&type=osmand&profile=car#17/49.16055/9.28215 (looks like this one shouldn't be muted)

**Comment by ivanPyrohivskyi** [comment]
_https://osmand.net/map/?start=48.516022,9.061071&finish=48.515169,9.064740&profile=car#18/48.51585/9.06226 - Bug Turn left... (not a regression ```"Turn left (+TL|C|C)"```)_
Wrong mapping [way 561588444](https://www.openstreetmap.org/way/561588444) must divide on two segments, first segment _left|through|through;right_, and second segment _left|through|through_

**Comment by ivanPyrohivskyi** [comment]
_https://test.osmand.net/map/?start=49.177720,9.224997&finish=49.041469,9.267654&type=osmand&profile=car#17/49.16055/9.28215 (looks like this one shouldn't be muted) - not a regression_
We mute all through turns with keep left|right .

**Comment by vshcherb** [comment]
Changed data for TL
