### ISSUE TITLE
maps.me like rendering ,feature request

### ISSUE THREAD

**Issue by muzirian** [osmandapp/Osmand#1879]
The rendering of maps.me looks much cooler than what osmand has now, it would be nice if that rendering is adapted for osmand.

**Comment by sonora** [comment]
Can you elaborate a little bit what exactly you have in focus? I have looked at the screenshots in their user guide at http://maps.me/files/MAPS.ME%20User%20Guide%20v5.1.pdf and do not see any striking advantages over the different map styles we offer. (Are you aware in OsmAnd you have a choice of various on-board map styles?)

**Comment by muzirian** [comment]
I am aware tht osmand has different styles already, but maps.me looks more classy,better colored and all.I ve read somewhere maps.me dont show much details data like omand,but the rendering is looks better than existing styles, So was hoping that if that too could make it into osmand, as another rendering style.

**Comment by muzirian** [comment]
Attaching screenshots for comparison 
![screenshot_2015-11-08-17-21-02](https://cloud.githubusercontent.com/assets/14972525/11020171/32a5c3c8-863d-11e5-9e2f-8dd7ca684ca4.png)
![screenshot_2015-11-08-17-20-56](https://cloud.githubusercontent.com/assets/14972525/11020172/3bdc66f4-863d-11e5-9b08-64124f7bbcfd.png)

**Comment by Barrocas** [comment]
That is a matter of personal opinions.
Nothing against creating another style, but I prefer Osmand style :p


-- 
Cumprimentos,
D.er Hugo Barrocas

**Comment by muzirian** [comment]
But I think there are more people who prefer maps.me rendering ober osmand, and i noticed a discussiom somewhere else.And as osmand offers multiple styles, adding this type of rendering will only do good i guess.So just put up a request :)

**Comment by govvin** [comment]
Let me just add a few observations. I've been using OsmAnd for a long time, and have been intrigued by comments from Maps.Me (M.M) users about usability.

In my experience working with OsmAnd with new users is that there are **too** many features available that clunks up the interface. I love OsmAnd for its many features, and I use a lot of it, but I don't think many users share my use-style, and would prefer to have a "Simple Mode" that only shows the most basic features necessary to use the maps. 

With regard to map rendering, I have received many comments that the M.M rendering looks better than OsmAnd's.  I also think it looks to similar to Google's, and maybe that's why many people find it familiar or more user-friendly. Many people think that M.M is fast, but I believe it is so because everything's been stripped down.

I still think OsmAnd, over-all is the superior app, but having a more intuitive interface, including having a "Simple mode" option, including simpler map rendering would further improve OsmAnd's market reach.

**Comment by vrtareg** [comment]
Hi

Have you looked for the roads only maps which have much more less details, 

Regards, 
Areg

**Comment by vshcherb** [comment]
M.M fast not only because it has less features just because it is opengl rendering.

**Comment by RicoZ-OSM** [comment]
One thing that impressed me with maps.me is the world overview map: it is small enough that together with the whole app it fits into the ~55MB and as an overview map it leaves nothing to desire.

**Comment by muzirian** [comment]
Also text rendering is better on maps.me, on osmand names placed on curved roads are often unlegible, refer the pic above

**Comment by pl71** [comment]
Street names should be more 'straight' and readable.

**Comment by sonora** [comment]
A simpler map style is on the way ("City view"), no further action planned.
