### ISSUE TITLE
Review and double check all sizes Widgets

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/OsmAnd#18800]
## Sizes
| Text size  | S | M | L | 
|---|---|---|---|
| Widget name | 11 sp | 11 sp | 11 sp |
| Value | 24 sp  | 36 sp | 60 sp  |
| Units | 11 sp | 11 sp | 11 sp |

| Min. Text size  | S | M | L | 
|---|---|---|---|
| Widget name | 11 sp | 11 sp | 11 sp |
| Value | 20 sp  | 30 sp | 40 sp  |
| Units | 11 sp | 11 sp | 11 sp |

| Widget | Widget height  | Icon | Margin Left | Margin Right | Text Align |
|---|---|---|---|---|---|
| S | 48 dp  | 24dp  | 16 dp | 16 dp | Center (if 1 in row), Left  |
| M | 72 dp |  24dp  | 16 dp | 16 dp | Center (if 1 in row), Left  |
| L | 96 dp  | 24dp  | 16 dp | 16 dp | Center (if 1 in row), Left  |

_Originally posted by @vshcherb in https://github.com/osmandapp/OsmAnd-Issues/issues/1892#issuecomment-1867632309_
            
- [x] To do check that All text sizes scales correctly (sp, dp) with System settings changed (1) Text size - system setting 2) UI scale - system setting)

**Comment by dmpr0** [comment]
# Review 

<table style="width:100%">
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/6df5e324-9cca-4e10-a021-e734c06fc911"  width="300" height="auto"/> </td>
  </tr>
</table>   

- [ ] Value should fit into available frame 
- [ ] Hole is visible sometimes below first widget / text align?

- - -

**Comment by dmpr0** [comment]
# Review 2

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/1ea1c30b-4335-4917-b3a9-e54e89d5003a"  width="300" height="auto"/> </td>
      </tr>
    </table>
</details>  


- [ ] Wrong text align for widgets that take part of the row

**Comment by dmpr0** [comment]
# Review

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th></th>
      </tr>
      <tr>
        <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/b8f5e973-e7c6-42d3-8272-b1746bfff5f5"  width="300" height="auto"/> </td>
      </tr>
    </table>
</details>  

- [ ] Text is not align to the left side in **small** widget when **icon** is off

**Comment by dmpr0** [comment]
# Review 3

**Comment by Guylby** [comment]
Hi, I've had an issue with the Distance to destination and the Time to destination widgets on my Xperia 10 III since 4.7.9:
The Xperia 10iii has a non standard display ratio so that may contribute to the issue: the screen is 21:9 or 2520 x 1080 px

The numbers get cut off and change size when navigation is started:

<details open>
<summary>Screenshot: Navigation starts, Numbers are cut, left widget has increased size text</summary>
<img src="https://github.com/osmandapp/OsmAnd/assets/151167525/b8a34905-1f10-4086-94e5-a16d8f36d87e" width="50%">
</details>

Going into the settings and changing the widget size to "small" (even though all 4 widgets were already on "small") makes the Destination Distance widget text the right size and show the full number on the Intermediate stop Time Widget:
However, stopping and starting another navigation makes the bug reappear everytime.
<details open>
<summary>Screenshot: Top Intermediate stop Time widget gets "small" size reapplied</summary>
<img src="https://github.com/osmandapp/OsmAnd/assets/151167525/1b4499da-0afb-4543-ae79-b48aa67aeeea" width="50%">
</details>

<details open>
<summary>Screenshot: Bottom Destination Time widget gets "small" size reapplied</summary>
<img src="https://github.com/osmandapp/OsmAnd/assets/151167525/773f206e-3bce-46f5-85da-418f0add10bc" width="50%">
</details>

**Comment by vshcherb** [comment]
- [ ] To do Fix screenshots @Guylby , text size wshould be maximum and compensate by shrinking units size

**Comment by vshcherb** [comment]
@Guylby you can test already 4.7.10 / nightly though we are still about to finish full testing and then will close the issue

**Comment by Guylby** [comment]
I'll test the widgets once 4.7.10 is available on the google play beta program!
If anything new pops up is it better to open a different issue since you want to close this one?

**Comment by vshcherb** [comment]
You can write here we will move around ourselves

**Comment by Guylby** [comment]
In Osmand 4.7.10, text size is ok and no cutting occurs at up to 3 widgets per line. Some text gets cut with 4 widget in a row but that's to be expected on such a narrow screen.

Thanks for the fix!

| Medium size widget  | Small size widget | Small size widget, 3 per rows |
| ------------- | ------------- | ------------- |
| ![438203799_234324013102388_222663125397222475_n](https://github.com/osmandapp/OsmAnd/assets/151167525/b0f83f04-bcf1-4c97-b4ee-290e1f4759e7) | ![438231550_758872042900602_1200683660847959119_n](https://github.com/osmandapp/OsmAnd/assets/151167525/e0386271-11fa-431d-8f46-571cd169f9be)  | ![438271413_415697958069107_3747072463849631514_n](https://github.com/osmandapp/OsmAnd/assets/151167525/1b6ab2ef-42b7-4dea-9eb2-1082ef12b884) |

**Comment by dmpr0** [comment]
# Review
<img src="https://github.com/osmandapp/OsmAnd/assets/9365308/6b37fe99-887d-409f-847b-1243b8ef8f51"  width="300" height="auto"/> 

- [ ] Value is not aligned horizontally sometimes
