### ISSUE TITLE
The map should always be shown north up, until route has been started

### ISSUE THREAD

**Issue by schubi74** [osmandapp/OsmAnd#18805]
### Discussed in https://github.com/osmandapp/OsmAnd/discussions/18089

<div type='discussions-op-text'>

<sup>Originally posted by **wehkah** September  4, 2023</sup>
Hello!

When you plan a trip, after entering the destination, the app calculates the route and displays the hole route. This should always be done with north pointing upwards, for easing the orientation. The map should not be rotated until the user hits "Start".

I find it extremely inconvenient, when I look at a map that shows my route from east to west, and that route goes from top to bottom of the screen. </div>

**Comment by Rowin63** [comment]
I agree, it´s inconvenient and always a bit confusing, until finding the correct orientation of the route. As long as the route is not started, map should be "north up". This has been bothering me for a long time too.

**Comment by schubi74** [comment]
I think every profile should have an option "orientation north up while not routing". This would let you choose how the overview is shown before you actually start the routing.

**Comment by scaidermern** [comment]
If I remember correctly, several versions back (i.e. maybe two years ago) this was the normal behavior. After that, OsmAnd started to remembered the map rotation after the navigation finished instead of resetting it. This also bothers me a lot.

**Comment by DmitryAlexei** [comment]
OsmAnd 4.6.9

- When you set up a route in *Driving* profile and the map orientation in this profile is set to *Movement direction*, the calculated route is also shown in movement direction mode (not in *North is up* mode).
- When user starts navigation in *Browse map* profile (*North is up*), the map orientation changes to *Driving* profile and *Movement direction* in preview mode (after route calculation finishes). 

Probably in that issue old behavior is described https://github.com/osmandapp/OsmAnd/issues/2735

**Comment by Rowin63** [comment]
I´m personally talking about this.
I want to see a route. The steps I do:

I´m in the "browse map"-profile
Magnifying glass: search and select the finish
Next: finish is shown on the map (still north up")
I tap "navigation" and this is what I see:

![Screenshot_20231225_082522_OsmAnd+](https://github.com/osmandapp/OsmAnd/assets/95540936/7e962cc5-5854-49dd-870e-1f312df8ca43)

Here I have no idea about the orientation, but I know, it is not "nort up" anyway.
This screen would be verry helpful for orientation displayed in "north up".
And beside this you can see, there is no compass to switch over to "north up" or any other orientation.

Merry Christmas!

**Comment by Rowin63** [comment]
I personally am talking about this:
After selecting a finish and tapping "navigation" I see this:

![Screenshot_20231225_093207_OsmAnd+](https://github.com/osmandapp/OsmAnd/assets/95540936/34d32bba-ade8-450b-af96-a417974f3f73)

Though I know Graz is not west of Vienna, the first view always is confusing. Especially in places away from home. Here at this screen I defenitely would prefer a "nort up"-view.
Yes, I can switch now the compass to "nort up", but then at the next step "start" it remains "north up" instead of switching back to "routing direction", 

Merry Christmas!

**Comment by Rowin63** [comment]
This one is "south up"... Why?

![Screenshot_20231226_084138_OsmAnd+](https://github.com/osmandapp/OsmAnd/assets/95540936/ab733442-8f47-4992-8770-0d5335d781fa)

And it seems, on every new start of the app Osmand has one "favorite direction" a route is displayed.
In this session all calculated routes are displayed orientated like this one, "south up" ...

**Comment by DmitryAlexei** [comment]
@Rowin63 The map in your examples is shown in *Movement direction* mode.

**Comment by Rowin63** [comment]
Exactly, and that's my point - the map should remain in the "browse map" or "north up" mode, as long as I don't hit the "start" button!
After selecting a finish the map switches to the driving profile and is orientated in any possible direction, because of switching to "driving mode".

Driving mode should not happen before touching "start"!

**Comment by scaidermern** [comment]
> Driving mode should not happen before touching "start"!

Well, it should be possible to start driving mode without an active navigation. However, after stopping the navigation OsmAnd should return to north up. Currently it keeps the last rotation state - resulting in a somewhat randomly rotated map. This is really irritating and not very useful. Maps are supposed to be north up unless there is a very good reason to use a different rotation.

**Comment by vshcherb** [comment]
I cound't reproduce it, I just restarted and it shows North Up. But @scaidermern it's probably random in some situations...

**Comment by naoliv** [comment]
The current behavior is as follows: during route planning, the system automatically switches to the car profile.
This alteration modifies the map style, view angle, and direction according to the configured settings.

It would be preferable, however, for the system to persist in browse mode or the selected profile until the Start button is pressed, avoiding any profile changes during the planning or route viewing phases.

**Comment by sonora** [comment]
> It would be preferable, however, for the system to persist in browse mode or the selected profile until the Start button is pressed, 

Yes, exactly: The issue was created about 2 years back when it was implemented that the App changed to the App profile the navigation is calculated for **already while the routes is calculated and afterwards just displayed on the screen**. Behavior before that since the biginning of OsmAnd had been the profile (including the map orientation that implied) only changed when, and if, a user started the turn-by-turn follow mode.

As someone who rarely uses the turn-by-turn mode that essentially forced me to set the map orientation to North iscup in all my profiles.

I can research the exact commit, if you want. Not sure which issue that tried to solve. If you ask me, we could revert to our prior behavior.

**Comment by yuriiurshuliak** [comment]
This bug is currently unreproducible. When the Map orientation mode profile is configured to follow the movement direction, the map appears in the orientation where the North is up in the route calculation dialog window.

OsmAnd~ 4.7.0#1352m, released: 2024-01-11

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/859882b9-3626-4aa6-8576-ee126717cafa"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/9ce93fbc-3e94-461e-a5bd-8333e022f946"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/87e55cae-9388-4d73-9c47-31660cb124c9"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by naoliv** [comment]
It's reproducible (tested right now with `4.7.0#1353`)

Before hitting `Navigation` I have my map in browse mode:
![](https://github.com/osmandapp/OsmAnd/assets/982338/cd70190a-8fc6-49b5-ab6e-aba445301645)

When clicking on `Navigation`, it switches to the car profile (which completely changes everything for me, including the orientation mode):
![](https://github.com/osmandapp/OsmAnd/assets/982338/b178e852-1bb4-4d7f-b020-98d04f69df1e)

Notice that I still haven't clicked on `Start` (thus, I am only _viewing_ the route).
It should stay in browse mode unless the user starts the navigation.

**Comment by dmpr0** [comment]
* Launch "Navigation" will switch App Profile to the first with Navigation type. 
* This was done to avoid unexpected surprises after pressing the Start button. All Map appearance settings, visible POI's or any other settings will be visible before taping Start.

**Comment by naoliv** [comment]
>     * This was done to avoid unexpected surprises after pressing the Start button. All Map appearance settings, visible POI's or any other settings will be visible before taping Start.

But this is incorrect.
I am unaware of any other app that works in this way.

Please note that we are only _viewing_ the route and not actually navigating.

**Comment by dmpr0** [comment]
> Please note that we are only viewing the route and not actually navigating.
We want users viewing and setting up the route in the environment that will be the same while navigation.

**Comment by Rowin63** [comment]
Of course you make it as you want it to be.

But to get an overview of a route, it is better having the map north up, everything else is confusing. Like a map usually is seen. 
And at the start of the route of course switch to moving direction.

**Comment by scaidermern** [comment]
> But to get an overview of a route, it is better having the map north up, everything else is confusing.

Exactly. Having the map rotated in a somewhat random orientation is definitely very confusing.

**Comment by naoliv** [comment]
> We want users viewing and setting up the route in the environment that will be the same while navigation.

So, can we assume that alternative routes (#1294) will never be implemented while planning the travel, right?
It appears to be impossible to display multiple possible routes, sometimes going in opposite directions, in a driving mode view.

**Comment by scaidermern** [comment]
Looks like this will be fixed in #19166.
