### ISSUE TITLE
Route data is lost when using Quick Controls on Android Auto

### ISSUE THREAD

**Issue by jsastreh** [osmandapp/OsmAnd#18855]
### Description

Route context data is not preserved when returning to the app via taskbar widget (taskbar) on Android Auto

### Steps to reproduce

- Enable "Taskbar Widgets - Show quick controls for apps" in Android Auto settings
- Open OsmAnd+ and set a route
- Open another app
- Tap OsmAnd+ quick control button on taskbar (note: not the app shortcut) to return to OsmAnd+ and resume navigation.

### Actual result

Route data is partially lost. Next maneuver, distance to destination, etc. data is missing.

At this point it is needed to set the destination again.

### Expected result

Route data is preserved and no need to set it again.

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: OsmAnd+ 4.6.9 and 4.6.11 (beta) from Google Play
Android/iOS version: Android 14
Device model: Samsung Galaxy A34
Crash-Logs: ?
```

**Comment by DmitryAlexei** [comment]
OsmAnd 4.7.10, released: 2024-04-18
Since the last release, the work of Android Auto in OsmAnd has been slightly improved.
I didn't manage to reproduce this issue  in the simulator using provided steps to reproduce. See video.
Although there was a slight delay in rendering the map after switching to OsmAnd from another app, route information was preserved.
@jsastreh Could you please check the latest OsmAnd version and say if the behavior you described has not been fixed. 

https://github.com/osmandapp/OsmAnd/assets/116079541/5254fa28-bbcf-4e50-aeb6-087d5554401a
