### ISSUE TITLE
Serbian Latin is missed as Map language 

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd#19086]
## Description 
Serbian Latin is not present as Map language

<table style="width:100%">
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/57571db2-e14f-41f6-9e01-7ff18a197f90"  width="300" height="auto"/> </td>
  </tr>
</table>   

## ToDo
- [ ] Add `sr-Latn` as map language 

Related issues:
https://github.com/osmandapp/OsmAnd/issues/13900
https://github.com/osmandapp/OsmAnd/issues/9393

**Comment by vshcherb** [comment]
Surprisingly it's very popular https://taginfo.openstreetmap.org/keys/name%3Asr-Latn#overview

**Comment by ZeljkoBG** [comment]
The map in Serbian Latin appeared in a new version. Well done for being up-to-date.

There are a lot of mistakes.
1. Instead of the name, in Serbian Latin, "Bulevar oslobođenja" the name appears in English "Liberation Boulevard".
2. Letters that do not exist in Serbian Latin appear in Latin names. Look at the picture.
The letter under arrow 1 should be written like this "j"
The letter under arrow 2 should be written like this "nj"

![Strelices](https://github.com/osmandapp/OsmAnd/assets/53188843/3b769265-5563-4a27-bd71-7be1794cf34b)

**Comment by ZeljkoBG** [comment]
Translation table:

"А" => "A",
"Б" => "B",    
"В" => "V",
"Г" => "G",
"Д" => "D",
"Ђ" => "Đ",
"Е" => "E",
"Ж" => "Ž",
"З" => "Z",
"И" => "I",
"Ј" => "J",
"К" => "K",
"Л" => "L",
"Љ" => "LJ",
"М" => "M",
"Н" => "N",
"Њ" => "NJ",
"О" => "O",
"П" => "P",
"Р" => "R",
"С" => "S",
"Ш" => "Š",
"Т" => "T",
"Ћ" => "Ć",
"У" => "U",
"Ф" => "F",
"Х" => "H",
"Ц" => "C",
"Ч" => "Č",
"Џ" => "DŽ",
"Ш" => "Š",
"а" => "a",
"б" => "b",
"в" => "v",
"г" => "g",
"д" => "d",
"ђ" => "đ",
"е" => "e",
"ж" => "ž",
"з" => "z",
"и" => "i",
"ј" => "j",
"к" => "k",
"л" => "l",
"љ" => "lj",
"м" => "m",
"н" => "n",
"њ" => "nj",
"о" => "o",
"п" => "p",
"р" => "r",
"с" => "s",
"ш" => "š",
"т" => "t",
"ћ" => "ć",
"у" => "u",
"ф" => "f",
"х" => "h",
"ц" => "c",
"ч" => "č",
"џ" => "dž",
"ш" => "š",

**Comment by pedjas** [comment]
Here is logic that should be used to display Serbian Latin:

- if name:sr_Latn exists, use that
- if name:sr exists use that but transliterated to Latin using transliteration table already posted by ZeljkoBG
- if none of theese tags exists, use name tag  and do transliteration to Latin using transliteration table already posted by ZeljkoBG

**Comment by strn** [comment]
Addition of so-called "Serbian Latin" script is completely unncessery and as such violation of Serbian constitution, article 10. Shame on those asking for this change!

**Comment by strn** [comment]
Please revert thi change.

**Comment by pedjas** [comment]
> Addition of so-called "Serbian Latin" script is completely unncessery and as such violation of Serbian constitution, article 10. Shame on those asking for this change!

Please, disregard this person named strn. He has serious issues with understanding Serbian language and also law. Serbian OSM community already has problems with this person as he intentionally vandalizes OSMAnd map for Serbia.

Serbian language uses both Cyrillic and Latin scripts. Cyrillic is primary but Latin is also part of the language. There is official Serbian Latin Alphabet. Serbian Latin alphabet is also more commonly used, which is regretful fact.

Claims about unlawful use of Serbian Latin script are false. Of course even law recognizes and allows it. 

Serbian Latin script transliteration is needed in OSMAnd map of Serbia because OSM map is 100% in Cyrillic script for territory of Serbia. That is problem for foreigners who do not use Serbian language and cannot read Cyrillic. For them it is more practical to use map transliterated to Latin.

Serbian OSM community maintains OSM map in Serbian Cyrillic script as it is primary, but also offers special render of map of Serbia that shows OSM map tiles transliterated to Serbian Latin script. You can see that render at https://tiles.openstreetmap.rs 

Also, every OS, application and service that offers multiple language user interface, offers both Cyrillic and Latin versions for Serbian language.

**Comment by pedjas** [comment]
Updated transliteration table from Serbian Cyrillic to Serbian Latin script.

At the end of the table special character groups are added that fix transliteration of capitalized words. Thing is, some Cyrillic letters are transliterated to two Latin letters. If such letter is capitalized in Cyrillic, without this fix it would be transliterated to two capitalized Latin letters.

"А" => "A",
"Б" => "B",    
"В" => "V",
"Г" => "G",
"Д" => "D",
"Ђ" => "Đ",
"Е" => "E",
"Ж" => "Ž",
"З" => "Z",
"И" => "I",
"Ј" => "J",
"К" => "K",
"Л" => "L",
"Љ" => "LJ",
"М" => "M",
"Н" => "N",
"Њ" => "NJ",
"О" => "O",
"П" => "P",
"Р" => "R",
"С" => "S",
"Ш" => "Š",
"Т" => "T",
"Ћ" => "Ć",
"У" => "U",
"Ф" => "F",
"Х" => "H",
"Ц" => "C",
"Ч" => "Č",
"Џ" => "DŽ",
"Ш" => "Š",
"а" => "a",
"б" => "b",
"в" => "v",
"г" => "g",
"д" => "d",
"ђ" => "đ",
"е" => "e",
"ж" => "ž",
"з" => "z",
"и" => "i",
"ј" => "j",
"к" => "k",
"л" => "l",
"љ" => "lj",
"м" => "m",
"н" => "n",
"њ" => "nj",
"о" => "o",
"п" => "p",
"р" => "r",
"с" => "s",
"ш" => "š",
"т" => "t",
"ћ" => "ć",
"у" => "u",
"ф" => "f",
"х" => "h",
"ц" => "c",
"ч" => "č",
"џ" => "dž",
"ш" => "š",
"Ња" => "Nja",
"Ње" => "Nje",
"Њи" => "Nji",
"Њо" => "Njo",
"Њу" => "Nju",
"Ља" => "Lja",
"Ље" => "Lje",
"Љи" => "Lji",
"Љо" => "Ljo",
"Љу" => "Lju",
"Џа" => "Dža",
"Џе" => "Dže",
"Џи" => "Dži",
"Џо" => "Džo",
"Џу" => "Džu"

**Comment by ZeljkoBG** [comment]
![Screenshot_2024-03-04-17-55-00-660_net osmand plus](https://github.com/osmandapp/OsmAnd/assets/53188843/775ef129-6173-4fa8-b2ff-a2658aa3f628)

Bravo OsmAnd. Everything is fine for now.

**Comment by dmpr0** [comment]
# Review

<table style="width:100%">
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/ec328b91-5ba4-4dff-a626-08003e970dc7"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/7e32adaa-739d-4af2-97b2-259644dd944d"  width="300" height="auto"/> </td>
  </tr>
</table>   


- [ ] Does't work on iOS. 
* * Tested on 4.7.2.6

**Comment by pedjas** [comment]
Cyrillic used for displaying Serbian language in OSMAnd is not Serbian but Russian Cyrillic.
Differences are in letters к, г, п, т and б, especially in italic writings.

**Comment by dmpr0** [comment]
> Cyrillic used for displaying Serbian language in OSMAnd is not Serbian but Russian Cyrillic. Differences are in letters к, г, п, т and б, especially in italic writings.

It would be better if you can provide links to OSM and screenshots from OsmAnd.

**Comment by dmpr0** [comment]
Works on iOS.

<table style="width:100%">
  <tr>
    <th>Latin</th>
    <th>Cyrillic</th>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/b8ce8170-fc23-4d2b-a63f-d11caa6ec267"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/62144fb3-f16a-4d7e-800f-3b9b4086cda4"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by ZeljkoBG** [comment]
It doesn't even work on iOS! The error is not in the font. Don't try.

It is very complex to explain why it is an error.

If I'm well informed, everything is correct only with OTF fonts...

**Comment by ZeljkoBG** [comment]
![GV-u7vtXkAAvgqP](https://github.com/user-attachments/assets/3c8b4197-2f24-4f39-97cc-6d3d1cdd99b9)

 
The middle row, italics, is incorrect, and the right row is how Serbian letters should look properly in cursive.
