### ISSUE TITLE
Weather mode causes issues when elevation profile widget is visible in bottom panel

### ISSUE THREAD

**Issue by mikehgentry** [osmandapp/OsmAnd#19157]
### Description

The weather mode controls and the elevation profile widget overlap, and you get duplication of some UI elements.

### Steps to reproduce

Create a profile with the elevation profile widget in the bottom panel

Start a navigation

Enter weather mode

### Actual result

Overlapping UI, duplicated UI

### Expected result

I suppose you could just stack them, or suppress the elevation profile

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: + 4.7.1
Android/iOS version: 11
Device model: Xcover 4s
Crash-Logs: ?
```

**Comment by yuriiurshuliak** [comment]
The bug has been reproduced. When the elevation profile widget is visible in the bottom panel during navigation, switching to weather mode results in the elevation profile widget being covered.

OsmAnd~ 4.7.0#1648m, released: 2024-02-22

https://github.com/osmandapp/OsmAnd/assets/127092082/cf6e3141-7d98-45e5-9f02-81f66ca50221

**Comment by mikehgentry** [comment]
The quick action button and the scale get duplicated too (and weirdly, the scale is showing two different distances - and it's not just different fractions, they're actually different). The weather panel in the top right became messed up (possibly duplicated) while I was playing around with it, but unfortunately I don't know the circumstances and didn't get a picture.

<img alt="" width="300" src="https://github.com/osmandapp/OsmAnd/assets/1724168/07a61799-0ecb-4562-84ed-7d4e371d2d7a">

**Comment by dmpr0** [comment]
## ToDo
- [ ] Only set list of weather widgets should be displayed on Weather screen

**Comment by yuriiurshuliak** [comment]
Currently, during navigation when switching to weather mode, the elevation profile widget is not displayed at all on the bottom panel, only the weather information is visible. However, it is worth noting that the Alert widgets also overlap.

OsmAnd~ 4.7.0#1841m, released: 2024-03-15

https://github.com/osmandapp/OsmAnd/assets/127092082/4bf1b64a-7b0e-4d5e-ba0d-74360314009e

**Comment by dmpr0** [comment]
# Review 

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th></th>
      </tr>
      <tr>
        <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/1803a104-bed2-44ee-9e82-15f92189cfe1"  width="300" height="auto"/> </td>
      </tr>
    </table>
</details>  

- [ ] Street name widget is visible

**Comment by 0xRe1nk0** [comment]
## Investigation part

**Custom containers for widget works like this: If widget type has a custom container and the widget is the last one in the order list, then this widget will be displayed in the custom container, otherwise it will be displayed in the vertical panel.**

<details>
    <summary>Vertical widgets with custom containers</summary>

- Lanes(Both orientation)
- Street names(Landscape orientation)

</details>  


All vertical widgets still visible in follow track and destinations screen. Coordinates widgets(only) is also visible in navigation menu when bottom sheet in collapsed state(3 screen)
<details>
    <summary>Screenshots</summary>
<table style="width:100%">
  <tr>
    <th>Follow track</th>
    <th>Destinations</th>
    <th>Coordinates widget in navigation menu</th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/89801357/962f710a-413a-46fa-9fb5-05b834e2ba42"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/89801357/a47c572a-07ab-4f84-8438-c4d8717043ec"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/89801357/13868263-b544-4a97-874e-187c382f4c6b"  width="300" height="auto"/> </td>
  </tr>
</table>  

</details>  

1. Should we display widgets on these screens(Follow track, Destinations)? 
2. Do we need to keep displaying only the coordinate widgets in the collapsed navigation menu?
3. Is the current mechanism for choosing whether to display a widget in a custom container or in a vertical panel suitable for us?
