### ISSUE TITLE
wrong POI data interpretation

### ISSUE THREAD

**Issue by mariush444** [osmandapp/OsmAnd#19192]
### Description

https://www.openstreetmap.org/node/1164539238
this is hotel with name in English and Georgian language
osmand displays it as tourist attraction without name

### Steps to reproduce

goto to 42.3267419, 42.5949079 in osmand and compare with osm.org (link above)

### Actual result

no name shown by osmand
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/66887280/9675cc38-c12f-447e-a599-f008f16828bf"  width="300" height="auto"/> </td>
  </tr>
</table>

### Expected result

name should be shown (it can be hotel or tourist attraction as is but name should exists)

### Your Environment (required)

.

**Comment by hakuchi** [comment]
The building is mapped as a tourism= attraction.     
https://www.openstreetmap.org/relation/11158884

Delete the attraction from the building should fix this.

**Comment by yuriiurshuliak** [comment]
The bug was not reproduced. Please attempt to zoom in and select a hotel.

The distinction lies in the fact that the building [link](https://www.openstreetmap.org/relation/11158884) is labeled as 'tourism=attraction,' whereas the hotel [link](https://www.openstreetmap.org/node/1164539238) is tagged as 'tourism=hotel.'

OsmAnd~ 4.7.0#1691m, released: 2024-02-27

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/552f6caf-269a-464f-901f-2b2b6f92e561"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by mariush444** [comment]
OK, so it was missleading that when I tap then osmamd showed just only one POI.
It usually shows 2 or 3 if there are vere close together.

So, I try to modify OSM but this is your decision if problem "not showing 2 POIs after tap" is a
bug or not.
If it is not problem in your opinion then you can closw the issue.
I prefer to see both POI.

**Comment by vshcherb** [comment]
Mostly OSM is pretty nice with keeping coherent data
