### ISSUE TITLE
Favorite search >>> back to the result not possible

### ISSUE THREAD

**Issue by Rowin63** [osmandapp/OsmAnd#19242]
### Description

When performing a search in the favorites and check one of the listed results (tap it > see it on the map), it is not possible to switch immediately back to the search result list. The "back" button leads back to "my places/ favorites" overview and the search has to be performed again.

### Steps to reproduce

do a search in the favorites and tap one of the results

### Actual result

no "back to the result" possible

### Expected result

"back to the result" possible

### Your Environment (required)

+4.7.1

**Comment by Sonwon1** [comment]
This needs fixing!

**Comment by yuriiurshuliak** [comment]
I am experiencing the same behavior.  When conducting a specific search, selecting a favorite, displaying it on the map, and attempting to return to the search results, the app redirects to the general "My Places/Favorites" section instead of the intended search results list.

OsmAnd~ 4.7.0#1773m, released: 2024-03-07

https://github.com/osmandapp/OsmAnd/assets/127092082/fd24f7ec-0aa4-4762-bb1c-049f37937b4b

**Comment by KnollFrank** [comment]
see pull request https://github.com/osmandapp/OsmAnd/pull/19762
