### ISSUE TITLE
The software cannot be downloaded from the Microsoft App Store

### ISSUE THREAD

**Issue by Y-PLONI** [osmandapp/OsmAnd#19260]
### Description

Although in a Google search:
https://www.google.com/search?q=xp8k0h83nf6rz4
It seems that there is a possibility to download the application for Windows computers as well, but when clicking on the link it seems that the application does not work. why?
![image](https://github.com/osmandapp/OsmAnd/assets/116633732/57f84eeb-d696-4cd7-a7b4-e83fb266fb5a)

![image](https://github.com/osmandapp/OsmAnd/assets/116633732/6fc06e86-494f-4561-95d0-7fde1ba356cb)

### Steps to reproduce

Search Google for the link, and click on the first result

### Actual result

Unable to download

### Expected result

can be downloaded

### Your Environment (required)

Windows 11 23H2

**Comment by yuriiurshuliak** [comment]
Since Microsoft and Amazon are essentially interconnected, a recent check revealed that starting from March 6, 2024, the Amazon Appstore cannot be downloaded from the Microsoft Store on Windows 11 devices. This led to a misunderstanding on our part. We are actively looking into this matter. For more details, you can refer to this link: https://www.amazon.com/gp/help/customer/display.html?nodeId=G2HAJZVD9V6KJT7A

**Comment by EugeneZmeuk** [comment]
https://learn.microsoft.com/en-gb/windows/android/wsa/?ranMID=46128&ranEAID=kXQk6*ivFEQ&ranSiteID=kXQk6.ivFEQ-9mwLZCitPqKSBymqm_R3Eg&epi=kXQk6.ivFEQ-9mwLZCitPqKSBymqm_R3Eg&irgwc=1&OCID=AIDcmm549zy227_aff_7794_1243925&tduid=(ir__g6anjllybskfdx9lavlr2e1hsf2x9bjz2fg2mt0200)(7794)(1243925)(kXQk6.ivFEQ-9mwLZCitPqKSBymqm_R3Eg)()&irclickid=_g6anjllybskfdx9lavlr2e1hsf2x9bjz2fg2mt0200
