### ISSUE TITLE
Review landuse commercial color rendering styles from PR

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/OsmAnd#19327]
https://github.com/osmandapp/OsmAnd-resources/pull/1051

Please attach screenshots and confirm the changes

**Comment by xmd5a2** [comment]
| Before | After |
|--------|--------|
| ![Image](https://github.com/osmandapp/OsmAnd/assets/5829014/dd985669-687f-4433-a0c3-a37020a7107c)| ![Image](https://github.com/osmandapp/OsmAnd/assets/5829014/b0117e55-ddca-4f5a-9361-82f476e8fdb2) | 

Merged manually. "scrub" shader can't be applied with color_0 because it is opaque.
