### ISSUE TITLE
Not possible to create route along path

### ISSUE THREAD

**Issue by Lemoert** [osmandapp/OsmAnd#19325]
### Description

When trying to create a route that passes from Path [#525885573](https://www.openstreetmap.org/way/525885573) to Path [#705126028](https://www.openstreetmap.org/way/705126028) via Track [Strada della Blina](https://www.openstreetmap.org/way/524667827), OsmAnd does not create a straight route (500 m) but takes a long detour. It works fine on, for example, GraphHopper, so not sure what the problem is. Attaching screenshots.

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/44477593/7839250e-d365-48ee-b38d-ff255276699d"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/44477593/7eb27fe3-e08b-48c9-8e77-c559c449181c"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/44477593/e84d7292-4fab-4b81-8fe8-276814841e35"  width="300" height="auto"/> </th>
  </tr>
</table>

### Steps to reproduce

Try to create a route (hiking) from point A to point B.

### Actual result

OsmAnd creates a long loop of 7 km.

### Expected result

A short stretch of 500 m.

### Your Environment (required)

```
OsmAnd Version: 4.5.10
Android version: 13
Device model: Fairphone 3
Crash-Logs: N/A
```

**Comment by vshcherb** [comment]
I think it shouldn't be reproducible on 4.7 version as I see based on website - https://test.osmand.net/map/?start=45.263983,7.487762&finish=45.253576,7.489264&profile=pedestrian#16/45.2592/7.4900. Also please double check you are using pedestrian as for bicycle profile indeed this hill could be very steep and produce lots of penalties.

**Comment by Lemoert** [comment]
Thanks @vshcherb ! Are the versions different based on where the app has been downloaded from, as far as you know? I have OsmAnd from F-Droid, and there 4.5.10 seems to be the latest version available.

**Comment by yuriiurshuliak** [comment]
The bug was not reproduced. I attempted to reproduce it both on the pedestrian and bicycle profiles using the coordinates provided for the start (45.26392, 7.48757) and finish (45.25755, 7.48954). A direct road is constructed from point to point without any detours. 
Please try to use the release version of the app or update your maps.

Here is the link to the web version: [link](https://test.osmand.net/map/?start=45.263915,7.487569&finish=45.257550,7.489543&profile=pedestrian#16/45.2614/7.4881)

OsmAnd~ 4.7.0#1864m, released: 2024-03-19

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/49af2811-d7ac-4ce6-ac39-c1488bb09dc7"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/a0b27994-69d2-481c-a5f4-00583eaf7a3d"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by Lemoert** [comment]
Thanks @yuriiurshuliak, it was the map that needed updating. Didn't know it could be done manually, thought it was all automated. My bad.
