### ISSUE TITLE
Error in elevation graph

### ISSUE THREAD

**Issue by mikehgentry** [osmandapp/OsmAnd#19339]
### Description

In Wales calculate a route (on foot or bicycle) from Brockweir village (16.4 miles / ~26.4km from Newport, just to the North of Chepstow) to Beeches Farm campsite just to the South East

The elevation graph for the route shows a maximum height of 80m, though the campsite is in fact at ~200m. The net ascent in the top left of the graph seems to be correct.

Installing or removing world altitude correction has no effect.

### Steps to reproduce

As above

### Actual result

Graph shows 80m peak.

### Expected result

Graph shows ~200m peak.

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: + 4.7.4, UK Wales 2024/3/1
Android/iOS version: 11
Device model: XCover 4s
Crash-Logs: ?
```

**Comment by yuriiurshuliak** [comment]
Please clarify the specific coordinates where the incorrect elevation is indicated.
Related to https://github.com/osmandapp/OsmAnd/issues/19142

**Comment by mikehgentry** [comment]
It isn't a specific point, it's the whole route - compare the contour lines and the graph.

Brockweir is at 51.70710° N, 2.66789° W, the camp site is at 51.70208° N, 2.65498° W.

<img alt = "" width = "300" src="https://github.com/osmandapp/OsmAnd/assets/1724168/2691df8f-1b03-4b60-bf53-e2a27ba1329b">

**Comment by yuriiurshuliak** [comment]
The bug was not reproduced. I attempted routing through both the bike and pedestrian profiles from the coordinates (51.70741, -2.66780) to the finish line (51.70279, -2.65483). Based on observation, the peak height on the elevation graph is 221 meters.

To ensure accuracy, I suggest updating your maps and trying our beta version: [Osmand Beta Version](https://osmand.net/docs/versions/nightly_versions#google-play-beta-builds)

Here is the link to the Web Version: [link](https://test.osmand.net/map/?start=51.707410,-2.667800&finish=51.702790,-2.654830&profile=bicycle#15/51.7077/-2.6701)

Here is the link to OSRM: [link](https://www.openstreetmap.org/directions?engine=fossgis_osrm_bike&route=51.7074%2C-2.6678%3B51.7028%2C-2.6548)

OsmAnd~ 4.7.0#1864m, released: 2024-03-19

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/365575fb-ae5e-4ac2-99db-a6371ea804f3"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/510063bf-eb27-414f-89b7-4b09f4c8bf9c"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by dmpr0** [comment]
Related to https://github.com/osmandapp/OsmAnd/issues/18204

**Comment by dmpr0** [comment]
Should be fixed in the latest nightly builds
