### ISSUE TITLE
Says Turn Left when it should say Go Straight

### ISSUE THREAD

**Issue by lunkhub** [osmandapp/OsmAnd#19343]
### Describe the routing engine used (required)

- [X] OsmAnd's in-app offline routing
- [ ] Any online routing provider (YOURS, openrouteservice, OSRM, etc.)

### Describe your routing Profile (required)

Car, fuel efficient, avoid motorways 

### Describe your start and end points (required)

Example start: 35.22387, -80.87947
Example end: 35.22484, -80.89745 Mystik station
Issue location: 35.22435, -80.89065

https://www.openstreetmap.org/edit?editor=id#map=19/35.22435/-80.89065

### Describe the actual route (required)

Where a right turn could be made, but main road and route goes straight, OsmAnd says Turn left and go...

### Describe the expected route (required)

OsmAnd should say Go straight...

### Describe what Maps you used (online or offline) (required)

- [X] Offline maps offered within the OsmAnd app for download. Latest NC USA, but this has been happening for months.
- [ ] Online (tile / raster) maps 

### Your Environment (required)

```
OsmAnd Version: 4.6.14 from F-Droid (Thanks!), but this happened in previous versions
Android/iOS version: Android 14 CalyxOS minimal install
Device model: Pixel 6a
```

### Anything else? (optional)

I looked for a map issue at that point, but did not find one.

**Comment by zipav** [comment]
OsmAnd Nightly 4.7.0#1908m, released: 2024-03-24

The voice prompt does suggest turning right a few times along the route. 

https://github.com/osmandapp/OsmAnd/assets/123936521/50799947-c67d-406a-95db-2e8bfab737a7


https://github.com/osmandapp/OsmAnd/assets/123936521/c203a0c9-75b9-451b-8a8f-4cb2e8e7e9ad

**Comment by DmitryAlexei** [comment]
Issue can be reproduced on the [OsmAnd web](https://osmand.net/map/?start=35.223870,-80.879470&finish=35.224840,-80.897450&profile=car#15/35.2205/-80.8981)
 
![Screenshot 2024-03-25 193214](https://github.com/osmandapp/OsmAnd/assets/116079541/51e9a311-5082-4a29-9713-a323d1f88198)

**Comment by mirror176** [comment]
> Same issue as in Germany we fixed manually, looks like popular issue so we need to fix it properly - here again we have long route https://www.openstreetmap.org/way/1049870350 where turns lanes should applied only to the end segment. So turn lanes should be ignored at point https://www.openstreetmap.org/node/10863993992

If I am seeing things right, that is a map issue where the Wilkenson Boulevard should have been split at the node you pointed out. The node to its right has turn lanes including the ';right' which should be lost once traveling past that point. If someone wants to correct, in JOSM you can likely merge those two points into the left one to save splitting/joining that road's way or moving the right turn way to the other correct node + relocating it. I didn't notice other tags changing in a relevant way so that should be fine but watch that it toesnt realign.

Another change I usually make is removing the triangle from the intersection just to the left as there really isn't one there. I basically move the Ashley Road fork to start splitting at (or above) Wilkenson Boulevard. Mouse currently has issues on this computer so I don't trust my clicks to be good and safe to do for editing.
