### ISSUE TITLE
no "download map" - dialogue appears

### ISSUE THREAD

**Issue by Rowin63** [osmandapp/OsmAnd#19434]
### Description

The dialogue for downloading maps does not appear.
But: it does not happen everywhere in the world. Some places yes, other places not.

Examples:
Italy: region around Lake Garda does not appear.
Russia: the regions along the Georgian borders do appear.
See screenshots.

Option is switched on:
![Screenshot_20240401_120035_OsmAnd+](https://github.com/osmandapp/OsmAnd/assets/95540936/72b3e869-8392-4d1a-9c0e-d532fe3fab2d)

No maps in this area downloaded:
![Screenshot_20240401_120102_OsmAnd+](https://github.com/osmandapp/OsmAnd/assets/95540936/f56e178b-b4ff-49e1-acaa-5a1888e3bb15)

No dialogue appears, at no zoom level:
![Screenshot_20240401_120141_OsmAnd+](https://github.com/osmandapp/OsmAnd/assets/95540936/983dcc13-a4f8-48e4-be7b-3a9a718b321d)

Other countries:
![Screenshot_20240401_121638_OsmAnd+](https://github.com/osmandapp/OsmAnd/assets/95540936/b13f3d82-a51f-4644-809a-a81827706f9c)

### Steps to reproduce

see above.

Note: this Italian regions have been on my device before, but I deleted them some days ago (via the app´s "maps & resources" section). Perhaps Osmand now does not remeber that correctly. 

### Actual result

no dialogue appears

### Expected result

display the dialogue

### Your Environment (required)

OsmAnd Version: +4.7.4
Android/iOS version: 13
Device model: S20+

**Comment by yuriiurshuliak** [comment]
The bug was not reproduced. I investigated the Italy region mentioned and also attempted to reproduce the issue by removing a previously downloaded map of Bulgaria. In all cases, the dialog box for downloading maps appeared without any issues.

OsmAnd~ 4.7.0#1969m, released: 2024-04-03

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/44f80aab-e3e8-4f6a-993b-e92c66678a8c"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/d172d265-6769-42ca-8257-fd368507a446"  width="300" height="auto"/> </th>
 <td><video source src="https://github.com/osmandapp/OsmAnd/assets/127092082/035fd8b3-868f-47b3-ad4c-473f3f31e5b7"  width="300" height="auto"/>   </td>
  </tr>
</table>

**Comment by Rowin63** [comment]
Sometimes strange things happen. I had to find this italian regions by name and download them.

So I'm fine by now, it was again a "one-day-issue".
Thanks.

**Comment by Rowin63** [comment]
I can´t really reproduce it.
For some regions I get the download offered, for other regions not.
And also: the regions with an "offered download" turn "yellow" by tapping on the map, the others don´t show any reaction, just mark the spot on the map.

**Comment by Rowin63** [comment]
"not planned" but... still exists.
Download-dialoge does not appear always, but only in a certain zoom range.

![Screenshot_20240806_090006_OsmAnd+](https://github.com/user-attachments/assets/df0b1081-1ab7-4a0c-8309-57d99403f1bc)

![Screenshot_20240806_090014_OsmAnd+](https://github.com/user-attachments/assets/7ea5e107-92eb-4849-bbe3-cb1c8c003684)

![Screenshot_20240806_090043_OsmAnd+](https://github.com/user-attachments/assets/2b24f7a7-65c5-4cea-858a-f29449c4c378)
