### ISSUE TITLE
Language

### ISSUE THREAD

**Issue by anten1222** [osmandapp/OsmAnd#19454]
### Describe the idea (required)

Please change the standard language output from "German" to "German informal". "German" output is too much disturbing information

### Tell us about the expected behaviour (required)

Please change the standard language output from "German" to "German informal". "German" output is too much disturbing information

### Tell us about alternatives you've considered (required)

Please change the standard language output from "German" to "German informal". "German" output is too much disturbing information

**Comment by anten1222** [comment]
Please change the standard language output from "German" to "German informal". "German" output is too much disturbing information

**Comment by yuriiurshuliak** [comment]
Could you please specify where exactly you want to change the language from "German" to "German informal"? Additionally, it would be helpful to understand why this change is necessary and why you find the current "German" output to be unsatisfactory.

**Comment by anten1222** [comment]
There are a lot of unnecessary and annoying announcements in German. There are far fewer in informal German. Please use informal German as the standard.

**Comment by pebogufi** [comment]
@anten1222 Please give examples.

**Comment by sonora** [comment]
I guess the user's talking about the TTS voice: I had once designed the "German (informal)" one as an alternative, with quite some abbreviations and omissions. While it may be more appealing to some users, in the end it is a matter of taste, and also environment. E.g. under noisy circumstances, more verbose announcements may be preferable, because they carry more redundancy.
