### ISSUE TITLE
road name overlap from vector map and .sqlitedb offline map

### ISSUE THREAD

**Issue by pfbreton-perso** [osmandapp/OsmAnd#19477]
### Discussed in https://github.com/osmandapp/OsmAnd/discussions/18675

<div type='discussions-op-text'>

<sup>Originally posted by **wu520609** December  6, 2023</sup>
	
Wu520609

Dec 5, 2023, 13:08 GMT+3

Hello：

I have put my own offline map (.sqlitedb) to osmand.
Yes,It can show my offline map(.sqlitedb). But the road name from vector map also appear. There is 2 road name in one map.So it cause some interference,
Please see attached file(offline.jpg). I have put some red circle for some road name from vector map in offline.jpg.Please take a look. Is any setting we can hide road name from vector map when we use our own offline map(.sqlitedb)?
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/49671574/2a992ff0-cff5-4157-8f57-7e7fca24bd19"  width="300" height="auto"/> </td>
  </tr>
</table>
</div>

**Comment by yuriiurshuliak** [comment]
To better assist you, we'd need a copy of your custom offline map (.sqlitedb) so that we can reproduce the problem locally. Please provide us with a download link or instructions on how to obtain your map.

In addition to the map file, could you please provide detailed steps on how to reproduce the issue you're experiencing? Screenshots of the problem, like the one you attached, would also be very helpful.

Also we recommend trying the workaround suggested in this comment: [link to the comment](https://github.com/osmandapp/OsmAnd/discussions/18675#discussioncomment-7884064).

Lastly, could you clarify whether you are use raster map as main map source or overlay?
