### ISSUE TITLE
OsmAnd does not recognize POIs or named areas/buildings

### ISSUE THREAD

**Issue by raindropsfromsky** [osmandapp/Osmand#1951]
Hi

Although OSM has a huge number of POIs, OsmAnd does not recognize them. The direct disadvantage is that we cannot share such POI with others. Only its latlong can be shared.

For example, I cannot share a restaurant's name and other attributes with a friend, like a visiting card (vcf). I can only send its LatLong, and then type the restaurant's name, level (floor) number, cuisine, etc. separately.

Desired: If we long-press on such a POI, OsmAnd should recognize it, and show its tags in the context menu (card). Next, it should be possible to share these details in human-readable form with others, even when they do not use OsmAnd.

Similarly, if we long-press anywhere on a named building or area, the name should appear in the context menu (card).

**Comment by sonora** [comment]
I think this has been improved to at lease include names now, but not all attributes.

**Comment by lenzwerf** [comment]
Why is this closed? OSM mappers who follow the mapping rules Tag buildings. So in my area the hospital dissapeared. The problem is not only sharing a POI, its finding and showing a POI. POI's like a hospital are independant of names and language. If I search for "ziekenhuis" on my dutch version of OsmAnd while I'm in the UK it will show the hospitals. This doesn't happen when the Hospital tag is on the building like the OSM standard dictates..

This is a huge problem. If all important buildings get tagged like they're supposed to OsmAnd will not find them.

**Comment by sonora** [comment]
I think the first point in the issue, sharing names of 'tappable' POIs, has been fixed?

Looks to me like the second aspect, which POI should be tappable and/or included in search results, deserve separate issues and discussion?

**Comment by lenzwerf** [comment]
Sorry, something got corrupted. After some cleanup actions and reinstalling the map tags on buildings work fine.
