### ISSUE TITLE
Location radius artefacts with enabled 3D relief

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd#19516]
## Description
When 3D Relief is enabled location radius is rendered with some visual distortion.

### How to reproduce
* Open **Menu** – **Configure Map** – **Topography** 
* Android – turn on **3D Relief** 
* iOS – **Terrain** and **3D Relief**, download terrain map
* Go back to map

### Actual result

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th colspan=2>Android</th>
        <th colspan=2>iOS</th>
      </tr>
      <tr>
        <th>3D Relief – On</th>
        <th>3D Relief – Off</th>
        <th>3D Relief – On</th>
        <th>3D Relief – Off</th>
      </tr>
      <tr>
        <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/c2cb371c-ae59-46aa-8fe5-8e84d0d42ad9"  width="300" height="auto"/> </td>
        <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/a10f19b9-cf6e-4952-9895-f8ef3441ef52"  width="300" height="auto"/> </td>
        <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/3abf7e2d-efa4-40df-a8ac-475f465c7b77"  width="300" height="auto"/> </td>
        <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/0b636c65-9287-4d25-baa0-f90a863fa730"  width="300" height="auto"/> </td>
      </tr>
    </table>   
</details>   

* Artefacts

### Expected result

* Location radius without artefacts

**Environment, Android** 

> OsmAnd Version: OsmAnd~ 4.7.0#2027m, released: 2024-04-09
> Android: 14
> Device model: Pixel 6A

**Environment, iOS** 
> OsmAnd Version: 4.7.3.3
> iOS version: 17.4.1
> Device model: iPhone XS Max

**Comment by Nine-Tailed** [comment]
Artifacts are also observed on the route line![Screenshot_2024-04-11-22-58-56-910_net.osmand.plus-edit.jpg](https://github.com/osmandapp/OsmAnd/assets/12549744/1cc0e18c-ff66-4738-bcf6-dc561f9a4d1e)

**Comment by gileri** [comment]
Similar distortions here on OsmAnd Android 4.7.10, Android 14 on Samsung Galaxy A52s 5G.
Both on 2D and 3D mode, but only on high zoom levels.
<details>
<summary>Screenshot</summary>

![image](https://github.com/osmandapp/OsmAnd/assets/493438/a540d20b-01e0-4e07-b829-4cbefc6f2b09)


</details>

**Comment by DmitryAlexei** [comment]
Steps to reproduce the issue with cluttered route line
- download Belarus standard map
- set navigation through the Nezalezhnasci ave
- enable 3d relief. Issue can be reproduced even when without Belarus Terrain (3d) map. Although with 3d map, the issue seems to be more obvious.
- set map magnifier to 75% or less (press and hold + or - buttons). As the value decreases, artifacts become more clearly visible.

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/52e86117-8bd6-4418-8b37-114c0df47c5a"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/39f2f3eb-a35c-4e33-8029-34803e868b89"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/480a8484-c8ea-4e0c-995f-0efaa02b1100"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by DmitryAlexei** [comment]
OsmAnd~ 4.8.0#2370m, released: 2024-05-22
The issue with route line artifacts seems to be fixed. I've tested with 3D relief enabled (and terrain 3D maps downloaded), also with different map magnifier levels, and haven't seen any artifacts.
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/6b119819-a99f-4a44-b226-422cafdd9a09"  width="300" height="auto"/> </td>
  </tr>
</table>
