### ISSUE TITLE
'Test voice prompts' and 'Logcat buffer' sometimes grayed out

### ISSUE THREAD

**Issue by sonora** [osmandapp/OsmAnd#19520]
![Screenshot_20240411-080419_OsmAnd~](https://github.com/osmandapp/OsmAnd/assets/845735/f50b5a2e-a51a-4c53-bfbc-480545120221)

I am not sure when this happens, it seems not permanent, but usually e.g. after a fresh app start.

The items remain clickable, though, they are only not displayed as clickable.

**Comment by yuriiurshuliak** [comment]
The bug was not reproduced despite multiple attempts. I tried various actions such as closing and reopening the app, toggling different options, but the issue was not reproduced. Both options consistently appeared to be functioning properly. More detailed steps are needed to accurately reproduce the bug.

OsmAnd~ 4.7.0#2050m, released: 2024-04-12

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/209b7cb3-0d75-448c-aba8-14273da4441e"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by sonora** [comment]
In deed this seems no more reproducible on latest builds, let me close it.
