### ISSUE TITLE
Exit ramp on left ignored from freeway in Western Australia

### ISSUE THREAD

**Issue by fvanrenterghem** [osmandapp/OsmAnd#19668]
### Describe the routing engine used (required)

- [X ] OsmAnd's in-app offline routing
- [ ] Any online routing provider (YOURS, openrouteservice, OSRM, etc.)

### Describe your routing Profile (required)

Car

### Describe your start and end points (required)

https://osmand.net/map/?start=-31.947653,115.881805&end=-31.944813,115.877449&profile=car#17/-31.94638/115.87683

Note this link seems to give the right turns when exported in both online routing and offline routing scenarios.

### Describe the actual route (required)

In-app offline routing suggests a right turn while on the freeway (left-hand drive in Australia), which in reality should first be a left turn to the offramp followed by a right turn over the bridge.

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/6618468/352923fa-5ce6-4fd6-949e-48562c562495"  width="300" height="auto"/> </td>
  </tr>
</table>

### Describe the expected route (required)

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/6618468/4474c6a0-fbfa-4921-8cba-fefc1ae932ca"  width="300" height="auto"/> </td>
  </tr>
</table>

### Describe what Maps you used (online or offline) (required)

- [X ] Offline maps offered within the OsmAnd app for download. 
- [ ] Online (tile / raster) maps 

Latest Western Australia updates using live update.

### Your Environment (required)

```
OsmAnd Version:
Android/iOS version:
Device model:
```

**Comment by yuriiurshuliak** [comment]
The bug was not reproduced. I attempted to reproduce it, both with and without live updates. In two cases, the turn instructions differ from the above screenshot.

OsmAnd~ 4.8.0#2184m, released: 2024-04-26

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/b8ba7d7c-e542-4000-a13f-ec4a3cadf6ab"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/bcb1c8b8-0b07-4298-a646-2ee4ab4127b9"  width="300" height="auto"/> </th>
  </tr>
</table>
