### ISSUE TITLE
No map is rendered due to crash (NullPointerException)

### ISSUE THREAD

**Issue by equaeghe** [osmandapp/OsmAnd#19693]
### Description

I'm running OSMand+ 4.7.10 from the Play store. Recently, possibly since the update to 4.7.10, it started not rendering any maps and giving an error message (see screenshot below) saying something like

> Error occurred generating map for the selected area.

The original Dutch is

> Fout opgetreden bij kaartgeneratie van het geselecteerde gebied.

Routes, favorites, and slopes are rendered, but not the underlying maps.

I have reinstalled OSMand+, switched between V1 and V2 rendering engines, disabled all plugins, downloaded the most recent maps, but nothing changes the issue. From the crash (exception) log, it seems to be a `NullPointerException` in OSMand code.

![Screenshot_20240429_103833_OsmAnd+](https://github.com/osmandapp/OsmAnd/assets/601177/3abdae03-eab0-40b6-b2b2-0346f4d94887)

### Steps to reproduce

- Open OSMand+ (to observe that there is no map being rendered and get error message)
- Do anything that changes the map view (to get error message again)

### Actual result

No map rendered

### Expected result

Map rendered

### Your Environment (required)

```
OsmAnd Version: 4.7.10
Android/iOS version: 13
Device model: SM-A515F/DSN (Samsung Galaxy A51)
Crash-Logs: Yes
```
[exception.log](https://github.com/osmandapp/OsmAnd/files/15146697/exception.log)

**Comment by vshcherb** [comment]
Try to change map style and set some settings. Reset profile could also help

**Comment by equaeghe** [comment]
> Try to change map style and set some settings. Reset profile could also help

Thanks for the suggestion. It doesn't seem to affect the issue. Namely, still no rendering after resetting the single profile I still have active (others deactivated), changing some settings of that profile, and restarting OSMand.

I would guess a `NullPointerException` shouldn't occur in any case and that there must be some underlying bug, no?

**Comment by yuriiurshuliak** [comment]
This bug was not reproduced in today's nightly version. However, in the April 27 nightly version, following a clean installation, I encountered a similar issue. To reproduce it, you would need to set up point-to-point navigation, load the desired map, and check OpenGL rendering. This caused the navigation to be initiated but the map to appear blank. Additionally, clicking on the map would display the address. Switching to 1 rendering version helped.

This behavior is not currently observed. Please test it on the nightly version linked here: [nightly versions](https://osmand.net/docs/versions/nightly_versions#nightly-builds).

OsmAnd~ 4.8.0#2208m, released: 2024-04-29

<table style="width:100%">
  </tr>
  <tr>
    <td> <video source src="https://github.com/osmandapp/OsmAnd/assets/127092082/d5af1730-e3e3-43ab-84c8-e7024d5bd241"  width="300" height="auto"/>   </td>
    <td><video source src="https://github.com/osmandapp/OsmAnd/assets/127092082/4cddb868-3c05-442b-beaf-f441a1f24c62"  width="300" height="auto"/>   </td>
  </tr>
</table>

**Comment by equaeghe** [comment]
I've installed the beta version 4.7.14 and the problem is (seems) fixed. Closing. I'll reopen if the problem reappears.
