### ISSUE TITLE
Not finding address when physical street and `addr:street` differs

### ISSUE THREAD

**Issue by wolfy1339** [osmandapp/OsmAnd#19747]
### Description

OSMAnd can't find an address that isn't on the same street as defined in `addr:street`.

There is a private street off of the municipal street of which the address refers.
Let's say the address is

12A 6th Row Road, MyTown, MyProvince, MyCountry

the address is located on a side street of "6th Row Road" named "1st Cross road". OSMAnd cannot find that address, you have to select it by coordinates

Example OSM address node: https://www.openstreetmap.org/node/11801192374

### Steps to reproduce

- Open the search menu
- click on address
- click on "first specify city/town/locality"
- search for an address where the nearest physical street doesn't match `addr:street`

### Actual result

The address doesn't show up in the search

### Expected result

The address should show up in the search

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: OsmAnd 4.7.13
Android/iOS version: 14 AP1A.240405.002.B1
Device model: Google Pixel 7 Pro
Crash-Logs: N/A
```

**Comment by Sonwon1** [comment]
I find the whole street search spotty. There should be a better way?

**Comment by vshcherb** [comment]
We need to wait for new maps !

**Comment by yuriiurshuliak** [comment]
The bug was not reproduced. For instance, I attempted to locate the address: "57-K, 6e Rang, Saint-Fabien-de-Panet, Montmagny (MRC), Chaudière-Appalaches, Quebec, G0R 2J0, Canada", and it was successfully found.

If you are referring to a different address or encountering another issue, please specify the exact address and include a relevant video demonstrating the problem.

OsmAnd~ 4.8.0#2299m, released: 2024-05-14

https://github.com/osmandapp/OsmAnd/assets/127092082/d0437f26-c771-40bc-841b-561b7ad8cf2b
