### ISSUE TITLE
Path difficulty classification (alpine scale) is /sometimes/ wrong on Touring View map style

### ISSUE THREAD

**Issue by valschneider** [osmandapp/OsmAnd#19769]
### Description

I've reproduced this on 4.3.5 and 4.7.10.

These three convering paths highlight the issue:
- https://www.openstreetmap.org/way/606473932 (westbound path)
  - sac_scale: alpine_hiking (T4)
- https://www.openstreetmap.org/way/888157125 (eastbound path)
  - sac_scale: alpine hiking (T4)
- https://www.openstreetmap.org/way/606473931 (northbound path)
  - sac_scale: demanding_alpine_hiking (T5)
  
Using the Topo map style, these are rendered as T4, T3, and T5:

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/5830891/2cfe4853-c4d3-4714-91a2-463002994375"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/5830891/5cdd6b55-78fb-4093-b0dc-6c981ba6017d"  width="300" height="auto"/> </th>
  </tr>
</table>

Using the Touring View map style, these are rendered as unclassified, T3, and unclassified:

### Steps to reproduce

- Visit the paths/ways described above
- Enable Touring View map style
- Observe wrong display

### Actual result

Alpine scale rendering doesn't match tag associated with the way.

### Expected result

Alpine scale rendering matches tag associated with the way.

### Your Environment (required)

```
OsmAnd Version: 4.7.10
Android/iOS version: Android 12
Device model: Pixel 5
Crash-Logs: ?
```

**Comment by yuriiurshuliak** [comment]
The bug was not reproduced. In order to reproduce this issue, I changed the map style to Touring View and enable Difficulty Classification (SAC) and Hiking routes.  Paths are shown based on the Map Legend guidelines found here: https://osmand.net/docs/user/map-legend/osmand#path-difficulty.

I've included the relevant screenshots below. Could you review them and let me know if you notice any mistakes or inconsistencies?

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/dbf4d354-e837-4147-84e7-39fc871fcd21"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/3652eb18-a020-4522-a40d-3a9267b7d499"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/de29df4f-d96d-413d-a53f-520b0370ad10"  width="300" height="auto"/> </th>
  </tr>
</table>
