### ISSUE TITLE
wrong navigation guidance while actual route is correct

### ISSUE THREAD

**Issue by gerhard-s** [osmandapp/OsmAnd#19800]
### Describe the routing engine used (required)

- [x ] OsmAnd's in-app offline routing
- [ ] Any online routing provider (YOURS, openrouteservice, OSRM, etc.)

### Describe your routing Profile (required)

car

### Describe your start and end points (required)

Start point: Hainburg/Hessen/Germany
End point: Schulstraße 56, Esslingen am Neckar
Intermediate point (selected by map) on A81 right behind the junction A3 to A81 (wanted to force the navigation on this route)

### Describe the actual route (required)

route was Hainburg - A3 - A81. The route was fine and correct, but the navigation arrows were nonsense when I had to leave A81, see screenshot, at Kallenberg direction Stuttgart/Feuerbach. Arrows indicated to continue 24 more km on A81

### Describe the expected route (required)

Should have shown guidance being consistent with the correct route maked in pink.

### Describe what Maps you used (online or offline) (required)

- [x ] Offline maps offered within the OsmAnd app for download. Baden Württemberg, standard map, 01.05.2024
- [ ] Online (tile / raster) maps 

### Your Environment (required)

```
OsmAnd Version: 4.7.10
Android/iOS version: BLA-L29 10.0.0.159(C432E5R1P3)
Device model: Huawei Mate 10 Pro, BLA-L29
```

### Anything else? (optional)

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/95910446/a3b7f300-26eb-4717-b7c9-90a20e652a2e"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/95910446/816e28ee-d315-4b9a-ab8f-3e2956717048"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by yuriiurshuliak** [comment]
The bug was not reproduced. Please attempt to use the "Attach to the roads" option, located in the Navigation menu. You can find more information about this option here: [Attach to the roads option](https://osmand.net/docs/user/navigation/setup/gpx-navigation/#attach-to-roads).

Additionally, try updating the map and then test to see if the issue persists.

Here is a link to view the route on the web version: [Route Link](https://test.osmand.net/map/?start=48.860485,9.126721&end=48.716532,9.324025&profile=car#13/48.8444/9.1446)

OsmAnd~ 4.8.0#2277m, released: 2024-05-09

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/581b2fb6-06dd-431b-89c9-68925ca4c93b"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/79a1dcb5-b379-480f-b7c5-a5ab930832bc"  width="300" height="auto"/> </th>
  </tr>
</table>
