### ISSUE TITLE
Live updates lead to crash

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/OsmAnd#19890]
### Description

Enabled live updates slow down the map drawing and cause a crash shortly after. Unfortunately no crash log is generated. Since many other apps crash at the same time I assume an out of memory situation occurs.

### Steps to reproduce

* Go to 51.04912, 13.74365 with the base map for Saxony, Germany enabled
* Enable live updates
* Zoom or pan the map to trigger a map redrawing
* Everything becomes super slow until OsmAnd crashes
* Restart OsmAnd
* Shortly after the same crash occurs, no interaction needed
* Delete live updates
* No crash anymore

With rendering engine v1 this crash doesn't occur. 

Yesterday this crash didn't occur with live updates, today it does. 

### Actual result

Crash

### Expected result

No crash, maybe cake?

### Your Environment (required)

```
OsmAnd Version: 4.7.17
Android/iOS version: Android 10
Device model: Samsung S9
Crash-Logs: no
```

**Comment by Velomeloman** [comment]
OsmAnd~ 4.8.0#2315m, release : 2024-05-16
Confirm crash

**Comment by scaidermern** [comment]
Could be related to #19511. In this other ticket one user reports that live updates cause a slow down.

**Comment by Sonwon1** [comment]
Now that I think about it I was having crashes after I turned on live updates. At the time I thought maybe it was related to live updates however I also had an ODBII monitor running at the time. When it happened the screen flashed black a few times and then I lost all touch screen control. I finally pulled over and forced closed OsmAnd and ODBII monitor. When I got home I turned live updates off and it has not crashed again since. That was several months ago.

**Comment by vshcherb** [comment]
I think I have same situation but I'm not sure that I have live updates. App freezes and crashes 10 seconds after start

**Comment by yuriiurshuliak** [comment]
The bug has been reproduced. To experience it, go to the specified coordinates and enable live updates for the map. When you then try to zoom in and out or pan the map, the application crashes. No crash logs are generated.

OsmAnd~ 4.8.0#2330m, released: 2024-05-17

https://github.com/osmandapp/OsmAnd/assets/127092082/07c47ad8-a15d-4313-a3a4-fcd0ea6a8296

**Comment by pebogufi** [comment]
"Me too"

**Comment by vshcherb** [comment]
Unfortunately it won't be fixed quickly as "Data was corrupted" (not tested for live in such quantities, the only solution seems to disable live maps for this month). 

**Dirty Workaround** It's possible to quickly zoom out once you enter app and then go to settings and delete live maps

**Comment by scaidermern** [comment]
> Unfortunately it won't be fixed quickly as "Data was corrupted" (not tested for live in such quantities, the only solution seems to disable live maps for this month).

Shouldn't there be a fix to handle corrupted live data? Instead of waiting for the next monthly map update? 🤔

**Comment by vshcherb** [comment]
We trying to update live maps as well now though it's very tricky to exclude some portion of data. Also users will need to clean data anyway and redownload fresh. 
~10 min To test first patch

**Comment by vshcherb** [comment]
We identified 2 suspciously large data changes (probably they included data areas too big): 14:20-14:30 UTC and 22:40-22:50 UTC

**Comment by vshcherb** [comment]
Problem is fixed ready to test. Full osmand live redownload is needed

**Comment by scaidermern** [comment]
Actually I was referring to a fix in the app so that future cases of corrupted data won't lead to crashes :)

But thanks for the quick fix!

**Comment by vshcherb** [comment]
Corrupted data had 1000 very long lines, next time we will be able to prevent it on the level of data preparation.

**Comment by langfingaz** [comment]
I completely reset OsmAnd (4.7.10 from f-droid) three days ago and downloaded the standard map of Scotland. After enabling live updates the app slows down heavily and/or crashes. I was zooming into Montrose, Scotland when this happend.

Are you sure, that this issue is resolved? As soon as I deleted the live updates (Maps and Resources -> Local > Live Updates) the performance is way better again.
