### ISSUE TITLE
favorite markings are marked as flags, after restoring backup

### ISSUE THREAD

**Issue by ErikWannee** [osmandapp/OsmAnd#19934]
Recently, I lost all favorite markings that I had entered in OsmAnd.
With help of the support team, I could restore them from a backup version.
But now, all markings that I had made, f.i. museum signs, viewpoint signs and parking lot signs, have been replaced (or overwritten) by flags. The flags have the same colors as the favorite markings had.
Only if I tap on a symbol, I get the symbol that I had originally entered. And there I get buttons 'marking passed' and 'activate', which I don't understand because I'm only a beginner.
When I changed language setting, I could see the original markings for a short second, but then they were immediately replaced by those (irritant) flags.

My question is: what might have gone wrong? And how can I get the favorite markings back, instead of all those flags?

Thanks, Erik Wannee.

**Comment by yuriiurshuliak** [comment]
The bug was not reproduced. Here are the steps I followed: I imported a large number of favorites, customized their appearance (colors, icons), backed them up, deleted them, and then restored them from the backup. All the favorites were successfully restored with their customized appearance intact.

OsmAnd~ 4.8.0#2400m, released: 2024-05-27

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/520d73fe-4339-469f-a848-f34b044585d2"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/b38c2491-7dc4-4f5d-af8c-55796cc062f6"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by ErikWannee** [comment]
Oh, that's pity.
Another option would be that I replace all (100 or so) flags by markings manually.
But if I tap on 'edit favorite', I see the right symbol, so there is nothing to replace.
Every time I see 'marking passed', and if I tap on that, the color is removed, and it becomes grey. When I try to edit it, I see the right color, so it is not possible to replace the grey color.
I don't understand why the app asks 'marking passed', as I don't want to pass it; I only want to mark it. It is very confusing to me.

**Comment by DmitryAlexei** [comment]
@ErikWannee do you use favorites as route waypoints? Waypoints icons may overlap favorites on the map
Please add a short video or screenshot of your issue, so we can reproduce it.

**Comment by ErikWannee** [comment]
On the first picture, you can see the image that I get, with a flag instead of the waterfall sign that I had previously.
![Fosslaug1](https://github.com/osmandapp/OsmAnd/assets/170624791/00d59bbb-c4ba-4eb4-9331-d929c8986c17)
When I tap on that sign, I get the second picture. There the waterfall sign shows on the right. That is the symbol that I had entered to the favorite.
![Fosslaug2](https://github.com/osmandapp/OsmAnd/assets/170624791/06bf094d-a4ad-4fc5-bd19-742dbc67d494)
If I tap on 'edit favorite', I get the 3rd image. There you can see the pink waterfall symbol that I had entered. But if I continue with 'enter' or 'cancel', I get that flag sign on the map again.
![Fosslaug3](https://github.com/osmandapp/OsmAnd/assets/170624791/ba6ee3d0-07bc-46f8-98c1-092e254501eb)
Those flags instead of the normal symbols appeared after I restored all favorites from the backup after they were lost.

**Comment by ErikWannee** [comment]
Indeed is may well be that waypoint flags overlap all my favorites. That happened after I restored my favorites from a backup file, after they were lost.

But now my question is how I can remove all waypoint flags that overlap all my favorites?

**Comment by yuriiurshuliak** [comment]
@ErikWannee Could you attach your restored favorites file so we can check it on our side?

**Comment by ErikWannee** [comment]
@Yuri, I have sent an email to you with the backup file attached.

**Comment by yuriiurshuliak** [comment]
The bug could not be reproduced. We successfully imported the backup files you provided into OsmAnd, and your favorites appeared correctly instead of flags. Please try deleting all your favorites and re-importing them into the app as demonstrated in the attached video. Use any messenger or cloud service to send your backup file with favorites, then open it. When prompted, select OsmAnd to import your favorites. This should ensure your favorites are preserved and displayed correctly. 

Here is the backup file you sent: [favorites_bak_2024-05-05_135718.zip](https://github.com/user-attachments/files/15775963/favorites_bak_2024-05-05_135718.zip).


OsmAnd~ 4.8.0#2469m, released: 2024-06-10

<table style="width:100%">
  <tr>
   <td><video source src="https://github.com/osmandapp/OsmAnd/assets/127092082/c54c65c2-f5c2-479b-90a0-ddad18126baf"  width="300" height="auto"/>   </td>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/1f358826-bac4-4e60-8039-bd9ed2f91742"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by ErikWannee** [comment]
I tried deleting favorites and then restoring the backup file. The favorites reappeared, but again with those irritant flags over it.
Then I decided that the backup file wasn't the problem; the program itself must have been damaged or corrupt.
I decided to uninstall the program and then reinstall it. Then I restored the data from my backup file. And TADAAAA! Everything was OK.
Problem solved; I am happy again.
