### ISSUE TITLE
Support 'health_specialty:*' in poi details

### ISSUE THREAD

**Issue by jf-simon** [osmandapp/Osmand#1996]
Please support 'health_specialty:*' in poi details. The poi is tagged with 'health_specialty:*' but in poi details there is no entry. It would very useful for searching the right doctor
![screenshot_2015-11-29-02-10-01](https://cloud.githubusercontent.com/assets/11144987/11454838/c75cd360-963e-11e5-95f8-44c2c4f6120c.png)
![screenshot_2015-11-29-02-09-15](https://cloud.githubusercontent.com/assets/11144987/11454840/cdb124aa-963e-11e5-8502-e5f65046757a.png)

Getting Simon

**Comment by morray** [comment]
In this course also the more used healthcare:speciality and healthcare:speciality:* tags should be used

**Comment by xmd5a2** [comment]
These commits https://github.com/osmandapp/OsmAnd-resources/commit/a3df1e195ce5b849c9e15efb31f82c8a8bcd2a00 https://github.com/osmandapp/Osmand/commit/344e81b6dfb260dd68187140471be5874384dc27 should cover most of these tags. healthcare:speciality=* converted to health_specialty:*=* scheme because it allows many specialities on the same object without semicolon.

**Comment by morray** [comment]
*thumbsup*, but what about: healthcare:speciality:*

**Comment by jf-simon** [comment]
Thanks

**Comment by xmd5a2** [comment]
@morray Added most used tags. Three parallel tagging schemes makes things very complicated.
