### ISSUE TITLE
Remove login/password authorization in OpenStreetMap Editing plugin

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd#19970]
## Description
Due to deprecation https://github.com/openstreetmap/operations/issues/867 of this methods of authorization we need to remove button **Use username and password** in login dialog.

> Previous task https://github.com/osmandapp/OsmAnd/issues/18243

## ToDo

<table style="width:100%">
  <tr>
    <th>Main bottom sheet</th>
    <th>Benefits...</th>
    <th>Upload OSM Note</th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/10a2c27a-315c-4ac7-a69f-c91d8f22af57"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/0bb64961-2d7d-421e-8bde-5798560b3725"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/1324ee3f-5ed8-41ca-8127-cd1c190624d6"  width="300" height="auto"/> </td>
  </tr>
</table>   

- [x] Remove **Use username and password** button from:
- - [x] Main bottom sheet
- - [x] Benefits for active OSM contributors
- - [x] Upload OSM Note dialog

**Comment by Nine-Tailed** [comment]
But today authorization via OAuth does not work. The problem in Osmand or on the OSM website is not clear.  Now you can only log in using your username and password.
![Screenshot_2024-05-28-23-09-35-013_com.vivaldi.browser-edit.jpg](https://github.com/osmandapp/OsmAnd/assets/12549744/6fee1998-278c-4579-a2aa-0125028ef733)

**Comment by mnalis** [comment]
@Nine-Tailed which OsmAnd version are you using? Have you logged in using Oauth2 or old Oauth1.0a?

see https://community.openstreetmap.org/t/oauth-1-0a-and-http-basic-auth-shutdown/108490/17 there are intentional occasional brownouts active for old Oauth 1.0a. 

It is intended that with 1 June 2024 neither old Oauth 1.0a nor login/password will work any anymore. So the username/password workaround that you mention will only work for few more days.

Only new Oauth 2.0 will be supported from June 1st onwards, and it requires both new OsmAnd and a re-login (i.e. `Settings` / `Plugins` / `OpenStreetMap editing` / `Settings` / logout icon near `Account` / `Login to OpenStreetMap` (appers in its place) / `Sign in with OpenStreetMap`)

However, **currently OsmAnd Oauth2 login is broken too**, see this: https://github.com/osmandapp/OsmAnd/issues/19841#issuecomment-2136407479

**Comment by Nine-Tailed** [comment]
@mnalis osmand 4.7.17.

**Comment by shurasmiling** [comment]
- https://osmand.net/docs/user/plugins/osm-editing
- https://osmand.net/docs/user/plugins/configure-plugins (additional)
