### ISSUE TITLE
Online map renders text and symbols from non-active vector maps

### ISSUE THREAD

**Issue by brbar** [osmandapp/OsmAnd#20003]
### Description

Online map rendering mixed with some other map data which was not selected by user.
Seems like this issue tied to the bigger problem with application settings and how the new settings applied during profile switch.

### Steps to reproduce

1. Add new online map USGS Topo using this URL: https://caltopo.s3.amazonaws.com/topo/{0}/{1}/{2}.png
Zoom levels 1-15
2. Create new profile USGS Topo. Choose Map source = USGS Topo. The rest of settings leave disabled

If you can't reproduce this issue on first attempt try to switch to Browse map profile and back. I'm still did not found a 100% way to reproduce it but in my environment this issue appears in 9 of 10 cases.

I noticed that once this issue appears there is a mess with a settings (see this issue - #20002)

### Actual result

In my situation I see the actual USGS Topo map with parts of regular OSMAnd offline map. See the screenshot:

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/97563684/6b0ec6e7-4fca-4c2c-8920-37bfffdd102c"  width="300" height="auto"/> </th>
  </tr>
</table>

I highlighted in green the contour lines from the regular contour lines layer of OSMAnd. It shows not only contour lines but street names, fords, some pois, etc.

### Expected result

USGS Topo map profile should show only actual map from USGS Topo URL. Without any additional data - just bare topo map.

### Your Environment (required)

```
OsmAnd Version: 4.7.17
Android version: 13
```

**Comment by dmpr0** [comment]
Hi! 
Online map is set as Map source, Overlay or Underlay?

**Comment by yuriiurshuliak** [comment]
The bug was partially reproduced. To reproduce it, insert the provided URL as the Map source and activate USGS Topo for Map source, Overlay map, and Underlay map. Next, attempt to view the map of Switzerland; at this point, the additional details from the contour lines won't show up. Interestingly, if you download the map of Switzerland and the contour lines beforehand, and then activate the online map, these details will appear.

OsmAnd~ 4.8.0#2434m, released: 2024-06-04

<table style="width:100%">
  </tr>
  <tr>
    <th>With a pre-loaded map and contour lines</th>
    <th>Without a pre-loaded map and contour lines</th>
  </tr>
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/76b9683e-56f0-403f-a9a2-a306736766d1"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/2de2e973-da10-470c-900e-a1d150c666a7"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by brbar** [comment]
@dmpr0, maps was set as Map source

**Comment by Nine-Tailed** [comment]
If there is a vector map of the region, then the name labels will appear on top of the raster maps selected as the source.

**Comment by soshial** [comment]
What @Nine-Tailed provided above — same thing happens on my device, when vector map is available.

**Comment by vshcherb** [comment]
It's expected behavior, you can't disable POI symbols coming from basemap and only see contour lines. So you need to archive vector maps.

On the other hand @Nine-Tailed case looks like a bug, it needs to be reproduced.

**Comment by Nine-Tailed** [comment]
Video in telegram chat about this bug. After changing the map source to raster, you need to restart osmand. Also pay attention to the osmand freeze at the end of the video when I tried to return the vector map.
 https://t.me/ruosmand/158475

**Comment by vshcherb** [comment]
Probably related https://github.com/osmandapp/OsmAnd/issues/14347

**Comment by vshcherb** [comment]
Bug reproduced after restart the app! Map source is Online tiles and labels strangely appears.

**Comment by Raiedecharles** [comment]
Thanks a lot :)

**Comment by soshial** [comment]
What version is this fixed for?
Still reproduces in v4.8.5.

**Comment by Raiedecharles** [comment]
4.8.6
cheers
