### ISSUE TITLE
Could not calculate route.: Empty result

### ISSUE THREAD

**Issue by maltfield** [osmandapp/OsmAnd#20021]
### Description

Since I upgraded from v4.6.14 to v4.7.10, I cannot calculate this route:

Ibarra, Ecuador (0.35205, -78.1197) to Aeropuerto International Mariscal Antonio Jose de Sucre (-0.12546, -78.35643)

### Steps to reproduce

1. Upgrade to the latest version of OsmAnd (either 4.7.17 or 4.7.10)
2. Disable GPS
3. Open OsmAnd
4. Tap on Aeropuerto International Mariscal Antonio Jose de Sucre (-0.12546, -78.35643)
5. Tap "Aeropuerto International Mariscal Antonio Jose de Sucre / Airport"
6. Tap "Navigation"
7. Tap "From: My Position"
8. Tap "Select on Map"
9. Tap on "Ibarra, Ecuador" (0.35205, -78.1197)
10. See Error

```
Could not calculate route.: Empty result
```

### Actual result

I get an error, not a route

```
Could not calculate route.: Empty result
```

### Expected result

I should get a route

### Your Environment (required)

```
OsmAnd Version: 4.7.10
Android/iOS version: 14
```

**Comment by albansuser** [comment]
"2. Disable GPS"

What happens if you leave GPS on?

**Comment by yuriiurshuliak** [comment]
The bug was not reproduced. To reproduce,  I chose the car profile, downloaded the relevant map, and used the specified coordinates. The route built without any issues.

- Please try resetting the profile settings by navigating to Menu -> Settings -> App profile (Driving) -> Reset to default.
- Ensure your app is updated to the latest version.
- You can also change the routing algorithm by going to Menu -> Settings -> Driving -> Navigation settings -> Route Parameters -> Development -> Routing algorithm.

If the issue persists after these steps, please attach a screenshot of the error and your profile settings.

OsmAnd~ 4.8.0#2454m, released: 2024-06-07

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/fd13ffb9-90aa-48fe-a501-a3c3da7e3fa4"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by maltfield** [comment]
> "2. Disable GPS"
> 
> What happens if you leave GPS on? I don't understand why you would turn it off.

If I turn on GPS, then OSMAnd routes me from my current location, even if it change the "Start Point". I guess this is another bug...

**Comment by Max1234-Ita** [comment]
I guess it works with GPS turned on because the route is calculated from "current position". If such information is not available, then no route calculation can take place.

@maltfield , please try this:
1. After the initial failure go back to the Navigation menu.
2. Tap on the "start" textbox
3. Instead of "My position", choose "search" or "select on map" option
4. manually pick the destination point, either by searching for it (i.e. as an address) or long-tapping on the display and selecting "Navigation -> Use as start point"

In this way, the route should be calculated, (however if you keep your GNSS receiver turned off, there's no way to get proper turn directions)

**Comment by Max1234-Ita** [comment]
> > "2. Disable GPS"
> > What happens if you leave GPS on? I don't understand why you would turn it off.
> 
> If I turn on GPS, then OSMAnd routes me from my current location, even if it change the "Start Point". I guess this is another bug...

I don' think it's a bug.
Even if you calculate the route starting from a spot not in your current position, when you start navigating OsmAnd will take you to the destination.

If you want to prepare a route and follow it in the future, you can usa the **_/// -> Plan a route_** function and save the route into a gpx file that you'll recall when needed. 

In that case you'll use the "Follow a track" option, and OsmAnd will also guide you to make you reach the planned course at first, using the selected approach type ("Nearest point" or "Start point"), then navigate along it to the nearest waypoint or the final destination.

**Comment by DmitryAlexei** [comment]
We should probably add more info about how to choose a starting point of navigation to documentation
https://osmand.net/docs/user/navigation/setup/route-navigation#choose-starting-point
If you would like to build navigation not from *my location*
- long tap on the map (on a poi, favorite or on a map itself)
- go to actions > directions from
After a starting point is selected, you can pick up a destination in a same way. Long tap on a map > navigation.
You can also save your route for future use or share it. Go to Navigation > Details section and choose save / share option.
For more information see https://osmand.net/docs/user/navigation/setup/route-details#share--export-actions

**Comment by sonora** [comment]
You can set up a route from **anywhere to anywhere** by this 'normal' procedure:
- Select a target, in any fashion, e.g. select something on the map and tap the "Navigation" button on its context menu.
- OsmAnd will immediately calculate the route _from your current position_.. But you can click on the "My position" text in the "From" line and change this here!
- Now here's where you (and many users) fail: **Just wait!** OsmAnd will calculate the route. **Don't tap 'Start'!**

Because tapping 'Start' at any point in this procedure will start the **turn-by-turn live guidance**, and that will automatically use your current position for the live guidance, what else...

**Comment by maltfield** [comment]
@sonora that's the UX bug I'm referring-to. If a user clicks "Start" and their "start point" is not "my current location", then it should *not* route from your current location.

**Comment by sonora** [comment]
Yeah, I know: bug or misunderstanding. Question is: What do you actually expect to happen if y,ou are in London, have just  calculated a route from LA to SanFrancisco, and now tap 'Start' to begin the turn-by turn guidance...  

"_In 6 tenths of a mile, turn right onto the 4-0-5 freeway.._."...  😢

**Comment by sonora** [comment]
From my personal experience with many users, we should probably find a more specific wording for 'Start', somenthing which makes it clear this now refers to '_live guidance_', not just to arbitrary route calculation.

**Comment by albansuser** [comment]
> @sonora that's the UX bug I'm referring-to. If a user clicks "Start" and their "start point" is not "my current location", then it should _not_ route from your current location. It should route from the start point that the user entered. That's a bug.

In my view, why would someone click Start at if they are not at their intended  point of departure? I don't think it's a bug. Seems logical to me.

**Comment by maltfield** [comment]
> In my view, why would someone click Start if they are not at their intended point of departure? I don't think it's a bug. Seems logical to me.

And that's precisely why engineers shouldn't be making UX decisions :sweat_smile:
