### ISSUE TITLE
Feature request: Allow OsmAnd to display photos with a default external app

### ISSUE THREAD

**Issue by raindropsfromsky** [osmandapp/Osmand#2007]
As I mentioned elsewhere, I am generating a large number of POIs in OSM.

My method is to pass through a new area, and take photos with OsmAnd.
Then return home, and look at the details of each photo, and then create POIs.

Usually each photo gives me several POIs (shops that are vertically stacked on different floors).  
So I have to zoom in different parts of the photo and look at the details.

But OsmAnd's native photo viewer is too small for this purpose. It also does not allow me to zoom in. That's why I prefer to watch the photos in an external app (e.g. Google Photos).

But OsmAnd does not allow me to open all my photos directly with this app.

So every time I end up wasting one click.
1. On map, find the photo marker, and tap on it.
2. The photo opens in the built-in viewer.
     I select the "Open with external app" option below the photo.
3.  The photo opens in Google Photos. Now I can pinch and zoom.

**Desired:** Allow the user to bypass step#2. The photo should open directly in the external app.

**Comment by shorty66** [comment]
I feel like this is a general shortcoming of OSMAnd: It doesn't play very well with other apps and instead integrates crappy features like the photo viewer or the wikipedia articles...

**Comment by sonora** [comment]
My firm opinion is that having an option to include *location-tagged* Wikipedia data offline into (and onto) OsmAnd maps can be considered a justified core feature of an offline mapping app, as long as no link to a 3rd party offline app, which can be set up easily by people who would want this feature, is available (e.g. most Wikipedia inclusions people would hit upon when researching it would require online connectivity. And most people I know would not even have hit on the idea to research connections between maps and wikis apps). Also: Including offline wiki is a stepping stone for new business opportunities for OsmAnd when it comes to developing e.g. an offline travel guide.

But that aside: short66 does, however, have a point which brought a little smile to my face ... I agree that both of his points are valid: Our interoperability with other apps (contacts, picking up address links in different formats, sharing address data etc.) has room for improvement, and instead of working on that we sometimes seem to spend a lot of resources on features which less than 1% or our users will appreciate ... 

I wish we had a useful statistics of
- Which or our functionalities is used by what percentage of our users (identify our core features), 
- Which are the issues most users fight with and would like to see fixed (whether they realize it or not). Quite naturally, the most frequent issues will b related to our core features).
- Which of or features is "strategic" because it opens new developments and business opportunities
- And which is what I call "fringe functionality", something we will never get to perfection and most users turn to other apps for this in the mid run anyway.

If we then took this and compare to where we spend our resources on, we may be surprised ... :) 

(What I outline above is called product management in industry, and I do realize this constitutes a special challenge in open source projects ...  :-)  )

**Comment by sonora** [comment]
No action planned here, it seems.
