### ISSUE TITLE
Russian texts all over maps

### ISSUE THREAD

**Issue by nktrjsk** [osmandapp/OsmAnd#20095]
### Description

Hi, in zoom level 15-20 start appearing anti-Putin Russian texts, I only see this on OsmAnd maps, not on OpenStreetMaps

### Steps to reproduce

Look at map level 15-20

### Actual result

Map with Russian texts all over it

### Expected result

Map without Russian texts

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version:
Android/iOS version:
Device model:
Crash-Logs: ?
```

**Comment by dmpr0** [comment]
Hi! Could you please provide screenshot? 
Also please check what language is selected as Map language in Menu – Configure Map – Map rendering.

**Comment by nktrjsk** [comment]
Hi, there's a screenshot of Brno
![image](https://github.com/osmandapp/OsmAnd/assets/32244066/feb3553a-73c9-4148-abba-d44de6b41959)

I'm not logged in, so I don't see that option.

**Comment by dmpr0** [comment]
> Hi, there's a screenshot of Brno ![image](https://private-user-images.githubusercontent.com/32244066/339252940-feb3553a-73c9-4148-abba-d44de6b41959.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyNjMzNTQsIm5iZiI6MTcxODI2MzA1NCwicGF0aCI6Ii8zMjI0NDA2Ni8zMzkyNTI5NDAtZmViMzU1M2EtNzNjOS00MTQ4LWFiYmEtZDQ0ZGU2YjQxOTU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEzVDA3MTczNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNmODQ5NjFiOWZmYzg1MTBlZjIzZjg3ZjJlMWExYjEwNWI1MzJjM2EyMjMwYWE1MmU5ZDg0MzU2YmRlM2M2MDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.brZUrhV7KT3WmASUEt-vLL6wWJDLAdmvTdyMiypPEoM)
> 
> I'm not logged in, so I don't see that option.

I see the same on Osm.org https://www.openstreetmap.org/#map=16/49.1790/16.5929, so it's not related to OsmAnd.

**Comment by Max1234-Ita** [comment]
It Is some lounge of attack/vandalism affecting OSM since the past month of may, it started after a user was banned by a OSM member of the DWG (Data Working Group) named Andy Townsend: after that the banned user opened another account and started adding those straight ways all around the world, naming them with anti-Townsend insults. 

Apparently he has somehow evolved, as since a couple of weeks he slightly changed the way those roads are added and moved to anti-Putin/anti-Russian phrases (someone thinks he/she is Ukrainian).

There is a ticket opened on the OSM forum, so of you spot those lines on there OSM map, please report it there, they will revert and restore the vandalised part as soon as possible.

https://community.openstreetmap.org/t/have-you-spotted-vandalism-on-openstreetmap-org/114684
