### ISSUE TITLE
RailwayInfra map style crashes with OpenGL rendering engine

### ISSUE THREAD

**Issue by lrnsdb** [osmandapp/OsmAnd#20096]
### Description

OsmAnd crashes when using a custom map style "RailwayInfra" and the OpenGL render engine. It works correctly with the Version 1 rendering engine. 

### Steps to reproduce

- Enable the OpenGL rendering engine
- Download custom map style from https://github.com/fuzzysolutions/OsmAndRailwayStyles
- Move it to ~\Android\data\net.osmand\files\rendering
- Open OsmAnd menu > Configure Map > Map Style > RailwayInfra

### Actual result

The application closes immediately.

After restarting the app 3 times a message is shown "OsmAnd's map rendering has recently crashed. OsmAnd has reverted to 'Version 1' map rendering." The "Share crash log" function does not work (there is no actual file attached). 

### Expected result

Open the application and show the map. 

### Your Environment (required)

OsmAnd Version 4.6.12
Device Model : Samsung SM-T575
Android Version : 13

**Comment by yuriiurshuliak** [comment]
The bug could not be reproduced. I used OpenGL rendering with the RailwayInfra custom map style, and the app did not crash after changing the map style. However, it's worth noting that the RailwayInfra map style does not appear when using OpenGL. It only displays when switching the rendering to version 1.

OsmAnd~ 4.8.0#2501m, released: 2024-06-13


https://github.com/osmandapp/OsmAnd/assets/127092082/2582615a-199d-42ed-bf55-cacaf23d377f

**Comment by e-LUNATIC** [comment]
I have the same issue since a few days. German Maps with Open gl activate crashed osmand.

**Comment by xmd5a2** [comment]
Not reproducible in OsmAndMapCreator and Android OpenGL

**Comment by ratti** [comment]
Bug is closed, however, I think I can add some context here.
Days before this crashes happened, someone vandalized OSM with long straight roads across the world. The physical size of that roads seem to have had an impact on OsmAnds workload.

Some of these streets seem to have crossed a territory without having a node in that. For example, they had a start node in the map of lower saxony and and also the end node, but they run through the map of hamburg without having a node there. This seems to trigger something.

I guess the issue was not reproducible since OSM removed that streets from the data, making this an edge case again. After maps updates a week later all was fine.
