### ISSUE TITLE
OpenStreetMap and OsmAnd is not korresponding

### ISSUE THREAD

**Issue by Kerstin-Svard** [osmandapp/OsmAnd#20097]
Why is OpenStreetMap (OSM) more updated than OsmAnd? There are roads and paths on OSM that is not present on OsmAnd. I have updated the map but OsmAnd is still less current that OSM.

I have payed to have a uppdated map in OsmAnd and expected that it would be up-to-date.

I attach a pdf with some exampels of the discrepancy between OSM and OsmAnd.

I have send email to support@osmand.net, and got the answer that I should be submitting the issue here.

Regards,
[Example.pdf](https://github.com/user-attachments/files/15821396/Example.pdf)

Kerstin
Gothenburg, Sweden

**Comment by scaidermern** [comment]
> Please keep in mind that the maps in OsmAnd are updated once a month.

The missing ways are much older than just a month.

In the first example, at least these two paths seem to be missing:
* https://www.openstreetmap.org/way/1155718108 (more than a year old)
* https://www.openstreetmap.org/way/1155718112 (more than a year old)

In the second example, these roads (and several others) are missing:
* https://www.openstreetmap.org/way/1125428857 (8 months old)
* https://www.openstreetmap.org/way/1180045460 (8 months old)

So something definitely seems wrong here.

@Kerstin-Svard From which month are your maps in OsmAnd?

**Comment by scaidermern** [comment]
Could it be that you still use a map that doesn't get updated any more? Sometimes large regions get split into smaller regions and the large region is dropped. In such a case you have to remove the map for the large region and install the smaller ones instead.

@vshcherb Is there any notice for the user in such a case? Maybe OsmAnd should warn somehow if the user still has a map installed that isn't updated anymore. Otherwise the user will never notice this.

**Comment by Kerstin-Svard** [comment]
Shouldn't it show in the list over maps if there is changes in regions. If I look there is just the map I have downloaded. I chose Sverige-Västra Götaland County and there is no more region below that level. (And Västra Götaland County isn't that big.)

**Comment by Kerstin-Svard** [comment]
Now I have updated the app and tested a lot of different settings and downloading the map several times. 
AND if I change from Walking (the walking person) to World (the world-picture) under Configuring Map so suddenly is it a updated map. I don't understand it but I'm glad. If I goes back to Walking it is the unupdated map again. Its a mystery to me.
But I guess I'm happy now. Thank you for your interest in my problem.

**Comment by pebogufi** [comment]
@Kerstin-Svard 
Please compare in the two profiles:
Configure map - Map rendering - Details
Configure map - Map rendering - Hide

May be in one of the profiles there is something hidden.

**Comment by Kerstin-Svard** [comment]
Yes! Now I have changed the Walking map rendering to the same as it was set under World. From OsmAnd (online tiles) to Offline vektormaps. 
I should need a multiple weeks course in OsmAnd to understand half of it.

**Comment by scaidermern** [comment]
* OsmAnd (online tiles): This is an online map from the OsmAnd servers and requires Internet access (may cause high mobile data usage!). The typical use-case is if you don't have a downloaded map for the current region. They should update automatically from time to time.
* Vector maps: Offline maps from your device, no Internet required. Need to be updated once a month.

Now the question remains why your online tiles were completely outdated. Either there is a problem on the OsmAnd servers or there was a caching problem on your device. Since https://osmand.net/map/#16/57.7353/11.8746 looks good to me I suspect the second is true and your OsmAnd didn't refresh the online tiles.

**Comment by Kerstin-Svard** [comment]
Now I have uninstalled and installed the app again. And now the map OsmAnd (online tiles) is up-to-date. I have an old phone with the app also and it was the same there, after uninstall and install it was ok. 

But I hope I don't have to do this every time the map should be updated. I lose markers.

**Comment by scaidermern** [comment]
Provably because you are using a vector map as base map and online tiles as underlay?

Is there any particular reason why you are using online tiles at all?

**Comment by Kerstin-Svard** [comment]
Base? Underlay? Sorry, I'm not so good at this. I attach a screenshot of my settings.

I have changed back to vector maps. I just thougt that the look of online tiles was nicer. But that is probebly just what I was use to.
![Screenshot_20240614_214952_OsmAnd](https://github.com/osmandapp/OsmAnd/assets/172609405/130f79a7-ccef-448e-9540-7c4c8d277dff)
