### ISSUE TITLE
after update to 4.7.17 (latest) no Downloads...msg: no Internet Connection

### ISSUE THREAD

**Issue by mathhen** [osmandapp/OsmAnd#20110]
After Update to latest Version with Galaxy S22 Ultra (uptodate) there are no Maps, no Ressources available.
Message: Check Internet Connection.
Before Update everything ok!
When i change between downloads and updates ,osm crashes...

**Comment by dmpr0** [comment]
Hello! Thank you for the feedback. 
Could you please provide crash file? You can find it in Menu – Help – Help improve OsmAnd – Send logcat log

**Comment by mathhen** [comment]
thanks for help, here it is
[exception.log.txt](https://github.com/user-attachments/files/15863712/exception.log.txt)

**Comment by yuriiurshuliak** [comment]
The bug was not reproduced. After updating to version 4.7.17, all my maps, tracks, and favorites were not lost. The app runs smoothly without any errors or crashes when switching between downloaded maps and live updates.

Additionally, we reviewed your crash logs and found that the crash was caused due to lack of memory.

OsmAnd~ 4.8.0#2528m, released: 2024-06-18

https://github.com/osmandapp/OsmAnd/assets/127092082/f7d9cc0c-c8cd-4289-9240-2f362888a063
