### ISSUE TITLE
"Attach to the roads" ignores waypoints

### ISSUE THREAD

**Issue by admirabilis** [osmandapp/OsmAnd#20126]
### Description

Hi! On an imported [GPX file](https://github.com/user-attachments/files/15892625/route.gpx.txt), after selecting "Attach to the roads", it simply ignores many waypoints.

Things that don't help:

- Setting the threshold just gives slightly different results.
- Doing a fresh OsmAnd+ install.
- Using routepoints in the GPX file, instead of waypoints.

Sample:
![route](https://github.com/osmandapp/OsmAnd/assets/3650039/81db1c80-ad63-4ead-8ec7-67c90140e9b1)

### Steps to reproduce

Use "Attach to the roads" on an imported GPX route [route.gpx.txt](https://github.com/user-attachments/files/15892625/route.gpx.txt), on a fresh install of OsmAnd+.

### Actual result

Many waypoints that were being correctly routed in the GPX track are now ignored.

### Expected result

Only attach to the roads, without removing any of the roads included in the GPX file.

### Your Environment (required)

```
OsmAnd Version: 4.7.10
Android/iOS version: Android 14
Device model: Galaxy S21+
```

**Comment by yuriiurshuliak** [comment]
The bug was not reproduced. To reproduce the issue, import the provided GPX file, attach it to the road, and set the threshold distance to 10 meters. Then, attempt to build the navigation. This should result in waypoints being considered in the navigation process without skipping any track sections.

Please try updating the app or check out our beta version using this link: [OsmAnd Nightly and Beta Builds](https://osmand.net/docs/versions/nightly_versions#google-play-beta-builds).

OsmAnd~ 4.8.0#2533m, released: 2024-06-19

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/ecf29d1e-bd88-47e4-9a5c-8a117947825f"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/f52735a2-7bef-49da-845f-99486bef98cc"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/c4f5dd82-e57c-4715-bf82-0ab7c64a69f1"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by admirabilis** [comment]
Thanks! I don't understand what you mean by first attaching to the road and then building the navigation. After attaching to the road, the navigation is ready, and the Start button appears. I've already test on the latest stable release, perhaps this is fixed in the beta.

**Comment by admirabilis** [comment]
OK. Fresh reinstall of OsmAnd 4.8, the only difference I see is Attach to the roads seems to be faster.

**Comment by admirabilis** [comment]
Think I've figured it out. There is an option between starting from the closest waypoint or the first, and this is reset after attaching to the roads. But it seems I can just readjust it after without affecting the result. Thank you for your help!

**Comment by 0709wiwiwi** [comment]
@admirabilis

Out of interest, I follow various road matching results 
I test only by the current OsmAnd web version, though.
Your example file.
The (10m) Java routing result is quite fine altough some wpt are not visited.
And at some 180° turning points, an expected u-turn is not generated
Do you notice this also by using the OsmAnd app Beta version ?
Can you eventually tell the original track and waypoints source ? 
Do these waypoints possibly indicate a delivery round ?
What is most important,  waypoint order or follow the track precisely?
What do you expect to get as an extra by using the road matching ? 
Add and to use TBT ? With or without waypoint announcements ?
