### ISSUE TITLE
Deletion error from search list

### ISSUE THREAD

**Issue by mp13mp13** [osmandapp/OsmAnd#20196]
### Description

Hello
I have recently come across a problem:
I can't seem to successfully get rid of two records in the search logs, this may have something to do with errors sending remarks to OSM.
(I create a remark and when trying to send it, I miss the send button - the remark disappears. It has not been sent, it is not in memory. I have to create a new remark. This is how the entry " Krzyż" appeared to me)

Attached is a video showing the problem and logs.

Greetings
M

https://github.com/osmandapp/OsmAnd/assets/75844217/2609dcec-4029-4e7b-9f7d-47c5e7355c3f

[exception.log](https://github.com/user-attachments/files/16024572/exception.log)
[logcat.log](https://github.com/user-attachments/files/16024574/logcat.log)

Device : e3q
Brand : samsung
Manufacturer : samsung
Model : SM-S928B
Product : e3qxeea
Build : UP1A.231005.007.S928BXXS2AXEF
Version : 14
App Version : OsmAnd+
Apk Version : 4.7.17 4717

### Steps to reproduce

Latest, up-to-date version of OSM+
Erroneous sending of comments to OSM

### Actual result

None

### Expected result

Effective removal of entries from the search list

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version:
Android/iOS version:
Device model:
Crash-Logs: ?
```
Device : e3q
Brand : samsung
Manufacturer : samsung
Model : SM-S928B
Product : e3qxeea
Build : UP1A.231005.007.S928BXXS2AXEF
Version : 14
App Version : OsmAnd+
Apk Version : 4.7.17 4717

**Comment by yuriiurshuliak** [comment]
The bug was not reproduced. To test it, follow these steps: open an OSM Note, then go to MyPlaces - OSM Edits - Upload edit to OSM. Before uploading, disable your internet connection and try to download the edit. OSM Edits will fail to load and display an error. Next, search for the objects you edited and then clear the search history and restart the app.

This process should result in the search history being successfully deleted.

If these steps are not precise, please provide the exact steps you used to reproduce the issue below.

OsmAnd~ 4.8.0#2610m, released: 2024-06-28

https://github.com/osmandapp/OsmAnd/assets/127092082/e50616a5-bfd5-4e9a-9c57-b09cf79276e3

**Comment by mp13mp13** [comment]
I tried to delete the records while having the phone offline. After restarting OSM, the records come back.
Some internal OSM app error.

https://drive.proton.me/urls/KQ995DVQ54#hfIFJWSX4_WN

**Comment by mp13mp13** [comment]
After reuninstalling the application cleanly, without restoring the data, the problem disappeared.
Topic to be closed.
