### ISSUE TITLE
Malfunction when displaying Quick Action names.

### ISSUE THREAD

**Issue by franco999** [osmandapp/OsmAnd#20254]
### Description

I have noticed, and I don't know if it is just me, that the custom names of the individual Quick Actions are not displayed and instead a standard name is displayed.

`OsmAnd~ 4.8.0#2694m, Released: 2024-07-06`

<img alt="Screenshot_20240706-190711" width="300" height="auto" src="https://github.com/osmandapp/OsmAnd/assets/12088580/22f2dd42-f9d0-4773-924a-caaad2a22a39">

<img alt="Screenshot_20240706-191522" width="300" height="auto" src="https://github.com/osmandapp/OsmAnd/assets/12088580/0f05f6f3-3e34-438a-99ea-d4f40bd6e1ab">

### Steps to reproduce

1. Create a list of Quick Actions.
2. Press the Quick Actions button on the map.
3. Check names of each button created.

### Actual result

The names of each button are not displayed correctly.

### Expected result

Each Quick Action created should display its respective individual name. For example:

<img alt="Quick Actions" width="300" height="auto" src="https://osmand.net/assets/images/quick_action_widget-855f92d8cd6b2d2fba9ee5cfd2b877b6.png">

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version:OsmAnd~ 4.8.0#2694m, Released: 2024-07-06
Android/iOS version: Android 13
Device model: Motorola Moto G32
Crash-Logs: ?
```

**Comment by yuriiurshuliak** [comment]
The bug has been reproduced. To reproduce this issue, create multiple "Add POI" actions under one Quick Action, each with a different name. When you click on the Quick Action button, observe that in the top menu of the action selection, all the actions are labeled "Add POI" instead of the unique names assigned during creation.

OsmAnd~ 4.8.0#2700m, released: 2024-07-08

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/9de1513c-e453-4957-9900-281f58e0097b"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/60e5c728-f292-47ad-84fc-607ac7e6c2bf"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by dmpr0** [comment]
# Review

<details>
    <summary>Add favorite</summary>

<table style="width:100%">
  <tr>
    <th>4.6.9</th>
    <th>4.8</th>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/982a5126-9886-48e6-93fb-65e67ab3cf9f"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/3e3060c5-c163-41f4-abb8-265d380c32ee"  width="300" height="auto"/> </td>
  </tr>
</table>  

</details>  

<details>
    <summary>Add OSM Note</summary>

<table style="width:100%">
  <tr>
    <th>4.6.9</th>
    <th>4.8</th>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/2170cd25-bf1c-48c3-ac21-51400d41adcc"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/6d491c50-f903-4fee-a3b0-87b5208594b9"  width="300" height="auto"/> </td>
  </tr>
</table>  

</details>  



- [ ] Verb is missing for some actions. Tested on 4.6.9 and on current nightly build
