### ISSUE TITLE
Map route rendering problem

### ISSUE THREAD

**Issue by sylvaticus** [osmandapp/Osmand#2035]
As from the attached screenshots, the rendering of the map route got often crazy, especially approaching curves.
I have tried with several map layers, but it seems it doesn't depend from it.
I have tried both Osmand 4.2 and Osmand+ 4.4 (paid version)
Device: Ulefone "Be Touch" (5.5'', Android 5.0)

I am willing to help debugging this issue, if you tell me how can I be more precise in my report.

Kind regards

![2015_12_07_22 24 24](https://cloud.githubusercontent.com/assets/2077159/11655876/6a93e8b0-9db1-11e5-9758-1124b4b70ce1.png)
![2015_12_07_22 42 49](https://cloud.githubusercontent.com/assets/2077159/11655878/6a98e342-9db1-11e5-9d5a-b088c2d55f8a.png)
![2015_12_07_23 23 42](https://cloud.githubusercontent.com/assets/2077159/11655877/6a97f6d0-9db1-11e5-8f5b-f599dbd599ad.png)

**Comment by stephan75** [comment]
maybe related to #2024 ?

**Comment by sylvaticus** [comment]
Thank you.. possible (both issues on android 5.0), but in my case zooming reduces the distortion but it doesn't remove it.
Also I noticed that panning the map on the horizzontal axis (but not on the vertical one!) moves the distortion:

![2015_12_08_22 01 29](https://cloud.githubusercontent.com/assets/2077159/11668523/f45638be-9df7-11e5-8818-5ea4319174e8.png)
![2015_12_08_22 01 42](https://cloud.githubusercontent.com/assets/2077159/11668547/1026075e-9df8-11e5-91a3-57fa1d4307dc.png)
![2015_12_08_22 02 01](https://cloud.githubusercontent.com/assets/2077159/11668572/284d22fe-9df8-11e5-8d45-2d5d0ed0ff35.png)

Zooming in: still I got the route distortion:
![2015_12_08_22 02 35](https://cloud.githubusercontent.com/assets/2077159/11668597/4eec0de4-9df8-11e5-9865-b6d26467bb02.png)

**Comment by vshcherb** [comment]
Looks like a bug in video driver or in a OS. The only thing we did last release we increased width of the route such nasty things. May you can update rendering style to change it. https://github.com/osmandapp/OsmAnd-resources/blob/master/rendering_styles/default.render.xml#L165
stroke_width=6:6 ..... ( @xmd5a2 )

**Comment by sylvaticus** [comment]
Thanks, I tried to set:

    <case color="#88aa0088" strokeWidth="1:1" color_3="#ffde5b" strokeWidth_3="1:1">

but I still have the render problem, even on a 1 px line (bdw, aside this bug, I agree the route width is too thick).
It would be strange as a driver bug, as everything else works fine.. is there a repo of old compiled and packaged releases to test ?

**Comment by xmd5a2** [comment]
@sylvaticus http://download.osmand.net/night-builds/?C=M;O=A

**Comment by sylvaticus** [comment]
I have tried with OsmAnd-old-master-nb-2013-06-12.apk, OsmAnd-old-master-nb-2014-01-03.apk and  OsmAnd-master-qt-nb-2015-12-09.apk, but no luck..

**Comment by sylvaticus** [comment]
Interesting,  issue #2024 has been documented on a Sony C5 Ultra dual, that wikipedia say has the same chip as mine, a MT6752..
I really think now this issue should be marked as duplicate of #2024 and closed..
(still a putty I have a phone I can't run my favourite GPS app :-/ )

**Comment by vshcherb** [comment]
Duplicate

**Comment by JeanDom** [comment]
I understand that this issue (#2035) has been closed because it's a duplicate of issue #2024, but when opening issue #2024 that one has also been closed, because it duplicates #2035 !

Must I understand that the problem is ignored now? Maybe I am wrong as I am new here.

Just to emphasize that this is still a NASTY BUG that makes downtown navigation very difficult. I am attaching some new screenshots.

Made on a new Lenovo Tab 2 A7-10F with Mediatek MT8127 GPU: Mali-400MP2 
Running Android 5.0
OsmAnd+ Version 2.2.4 from Google Play (paid version)

Thank you guys for helping.... Great App otherwise

As you see the weird route distortion is even present at close zoom levels (50 meters)
 
![2016_01_06_14 31 09](https://cloud.githubusercontent.com/assets/16562157/12146956/ec9f92f4-b496-11e5-9e68-92cd2b37dd16.png)
![2016_01_06_15 24 00](https://cloud.githubusercontent.com/assets/16562157/12146957/eca4d610-b496-11e5-9940-4609653e7098.png)
![2016_01_06_15 31 11](https://cloud.githubusercontent.com/assets/16562157/12146958/ecaa361e-b496-11e5-9747-2376976f5e5b.png)
![2016_01_06_15 33 26](https://cloud.githubusercontent.com/assets/16562157/12146959/ecaac692-b496-11e5-8b20-d97bf28f8625.png)
![2016_01_06_15 33 41](https://cloud.githubusercontent.com/assets/16562157/12146960/ecacd220-b496-11e5-9c57-35c57ed45e5e.png)

**Comment by vshcherb** [comment]
#2024 still open
