### ISSUE TITLE
track recording not possible

### ISSUE THREAD

**Issue by t-h-oma-s** [osmandapp/OsmAnd#20377]
### Description

The recording of a track often, approximately every third record stops several times. GPS is available and the mobile is on the same Position as always. You can See this on the Screenshots I shared. Have the same error in the same paths, therefore buildings,... can not have an impact on GPS. The root cause is the app.
<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/7d4ac27e-c4c7-4a6a-ac70-ebbbfcd199de"  width="300" height="auto"/> </td>
  </tr>
</table>
### 
<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/89f8c266-a050-419e-9ea1-d28057e54a0b"  width="700" height="auto"/> </td>
  </tr>
</table>

### Steps to reproduce

Started recording, no energy saving active, Often, also at the hiking trip visible in the screenshot, the recording was stoppen. But there was no problem with GPS, this was available.

### Actual result

Have the same issue approximately once per week without any change in settings...

### Expected result

Track recording without gaps

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version:
Android/iOS version:
Device model:
Crash-Logs: ?
```

**Comment by sonora** [comment]
Any track recording filters active? Like a speed filter, or a displacement filter, and you had a break? Then perhaps this was caused by setting "Auto-split recording after gap" being set to "true".

(You could manually combine sub-tracks again by manually editing your gpx file and removing the interim inserted
```
</trkseg>
/trkseg>
```
lines.)

**Comment by scaidermern** [comment]
> no energy saving active

It is not quite clear from your comment whether battery optimization for OsmAnd really is _disabled_ in your Android settings.

**Comment by yuriiurshuliak** [comment]
The term "no energy saving active" can be understood in various ways. Simply disabling the phone's energy-saving mode won't suffice; you need to disable optimization for the specific application.

The issue is likely specific to your device. Please check if your device has any power optimization settings that might be impacting the app's performance. You can find more details on power optimization at https://dontkillmyapp.com/.

Additionally, we recommend joining our beta testing program to see if the issue persists. Information on how to sign up for beta testing can be found here: https://osmand.net/docs/versions/nightly_versions.

**Comment by sonora** [comment]
As I saidd, it may well be a filter issue the way it looks on your screenshots. But regarding Power Saving, most OsmAnd users have good experience with these settings: https://osmand.net/docs/user/troubleshooting/track-recording-issues#tested-power-settings-for-android-9-10-and-11-hardy-2020-08-25

**Comment by t-h-oma-s** [comment]
Thank's a lot. had to adjust one setting. Going to check within the next days if this had solved the problem.Am 24.07.24, 18:10 schrieb Hardy ***@***.***>:

   
  As I saidd, it may well be a filter issue the way it looks on your screenshots. But regarding Power Saving, most OsmAnd users have good experience with these settings: https://osmand.net/docs/user/troubleshooting/track-recording-issues#tested-power-settings-for-android-9-10-and-11-hardy-2020-08-25

**Comment by t-h-oma-s** [comment]
Tested the track recording 5 times with these settings and Till now everthing was ok. Thank's a lot for your help.

‐------
Thank's a lot. had to adjust one setting. Going to check within the next days if this had solved the problem.
Am 24.07.24, 18:10 schrieb Hardy ***@***.***>:
As I saidd, it may well be a filter issue the way it looks on your screenshots. But regarding Power Saving, most OsmAnd users have good experience with these settings: https://osmand.net/docs/user/troubleshooting/track-recording-issues#tested-power-settings-for-android-9-10-and-11-hardy-2020-08-25
