### ISSUE TITLE
Make Premature rotation of map during navigation optional

### ISSUE THREAD

**Issue by max69dm** [osmandapp/OsmAnd#20422]
### Description

With reference to ticket 19706, the opposite is now happening. The cursor correctly follows the route line, now it is the map that rotates incorrectly before intersections, roundabouts or other intersections of roads. The thing is very, very annoying 

### Steps to reproduce

![Uploading Screenshot_20240726_210237_Gallery.jpg…]()

### Actual result

Not correct

### Expected result

The map must work as in the version of 07/05/2024 4.7.17 

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version:
Android/iOS version:
Device model:
Crash-Logs: ?
```

**Comment by yuriiurshuliak** [comment]
To reproduce this bug, please provide the specific coordinates for the start and finish where the issue occurs. It would be helpful if you could also provide a video or screenshot demonstrating the error, as the screenshot you attempted to attach earlier didn't load. Additionally, export and attach your profile settings where the bug was observed by going to Menu → Settings → Import/export → Export to file. And lastly, please include the app version you are using.

**Comment by vshcherb** [comment]
Unfortunately we don't see your screenshot, also we fixed exactly premature rotation in animation, so now it should be delayed

**Comment by vshcherb** [comment]
https://github.com/osmandapp/OsmAnd/issues/19706

**Comment by max69dm** [comment]
Buongiorno
Per quello che posso ti inoltro questo video.
Se avete già corretto, posso vedere subito la modifica, oppure aspetto la
prossima release sul playstore?
Grazie

Il Lun 29 Lug 2024, 14:32 vshcherb ***@***.***> ha scritto:

**Comment by max69dm** [comment]
Buongiorno
Ti allego il video. Coordinate tra 45.449123,11.047416 e 45.0683,11.047447
Versione app del 24/07/2024

Il Lun 29 Lug 2024, 14:24 yuriiurshuliak ***@***.***> ha
scritto:

**Comment by vshcherb** [comment]
Sorry didn't get the video yet, can you double check it

**Comment by max69dm** [comment]
Non riesco ad allegare il video poiché troppo grande di dimensioni


Il Lun 29 Lug 2024, 15:40 Massimo Dongilli ***@***.***> ha scritto:

**Comment by yuriiurshuliak** [comment]
You can send this video to our support email at support@osmand.net or upload it to a cloud service and share the link here. Alternatively, you can cut the video to 10 MB and upload it directly to GitHub.

**Comment by max69dm** [comment]
Tramite Jumbo mail ti ho inviato il video all'indirizzo ***@***.***

Mi fai sapere per favore se l'hai ricevuto?
Grazie

Il Lun 29 Lug 2024, 16:18 yuriiurshuliak ***@***.***> ha
scritto:

**Comment by max69dm** [comment]
Non riescobad inviare un video nemmeno tagliandolo.
Spero riuscite a sistemare il problema ugualmente

Il Lun 29 Lug 2024, 16:01 vshcherb ***@***.***> ha scritto:

**Comment by max69dm** [comment]
https://github.com/user-attachments/assets/4e2ee074-6b82-444f-8c2e-e24c39f7f4e3

**Comment by max69dm** [comment]
Ho allegato il video su GITHUB

Il Lun 29 Lug 2024, 23:19 Massimo Dongilli ***@***.***> ha scritto:

**Comment by max69dm** [comment]
On GitHub screenshot


Il Mer 31 Lug 2024, 14:38 Massimo Dongilli ***@***.***> ha scritto:

**Comment by DmitryAlexei** [comment]
I think, the issue is when navigating in 3d mode, map start to rotate slightly in advance of the turn, which sometimes makes the turn not even visible for a moment. 
OsmAnd~ 4.9.0#2875m, released: 2024-07-31
 
<table style="width:100%">
  </tr>
  <tr>
    <th>user's screenshot</th>
    <th>my screenshot</th>
  </tr>
  <tr>
<th><img src="https://github.com/user-attachments/assets/50084179-10bb-44e3-95db-0d49f9ec2ffd"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/5d457a2e-85a1-4978-a3c2-42df3cbe9fed"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by max69dm** [comment]
The visual is very very annoying especially for such an important and
graphically beautiful application. If you can fix the problem it would be
great

Il Mer 31 Lug 2024, 15:07 DmitryAlexei ***@***.***> ha
scritto:

**Comment by Andrewschenko** [comment]
It looks like with certain parameters applied (3D relief is on, close-up auto zoom is selected), in some cases the map rotates too early.

**Comment by max69dm** [comment]
where can i find the zoom function to adjust it if necessary ?


Il Gio 1 Ago 2024, 12:32 Alex Andrewschenko ***@***.***> ha
scritto:

**Comment by K-Krs** [comment]
Hello, I also experienced this bug. I am using the latest version of Osmand 4.8.4. In the bicycle profile, with 2D display, you can see from the attached screenshots that the map 
rotation starts too early.

![Screenshot_20240728_113900_OsmAnd](https://github.com/user-attachments/assets/0c1c18e3-054c-4690-ad69-0551dc2db761)
![Screenshot_20240728_115225_OsmAnd](https://github.com/user-attachments/assets/7d10725f-0a33-4c15-9252-7febc0df6a6a)
 regards, Klaas

**Comment by mryx007** [comment]
I noticed the same problem yesterday in 4.8.4

**Comment by max69dm** [comment]
the bug is there with both the 2D and 3D map. Some time ago the "3D
Surveys" function drove the direction slider crazy, i.e. many times
compared to roundabouts, at intersections the cursor went completely out of
the route line. Could it be that the problem has not been completely fixed?
Furthermore, can it also depend on the combination in the "route
parameters", development, type of route and gpx approximation?

Il Gio 1 Ago 2024, 12:52 K-Krs ***@***.***> ha scritto:

**Comment by vshcherb** [comment]
No it's not a bug, that's a feature to turn to see next 400m after turn. I just forget about this behavior.

**Comment by vshcherb** [comment]
Probably it could be linked with Animate my location option

**Comment by max69dm** [comment]
Do we have to do something or wait for the fix in the next update?

Il Gio 1 Ago 2024, 13:31 vshcherb ***@***.***> ha scritto:

**Comment by K-Krs** [comment]
Hi, now I understand the dilemma you are facing. You're goal is to make the 200 meters after the exit visible and the map should be rotated in the direction of travelling. And in some cases that conflicts with each other.

As a cyclist, I prefer that the map always is in the direction of travelling. So the map rotates at the moment I'm at the turn and not before. Is it possible to add an option in the settings where the user can choose when the map rotates (prefer 200 meters visible after the turn or prefer map rotation at the turn)?

**Comment by max69dm** [comment]
Dov'è che vedere ed eventualmente impostare questo parametro?

Il Gio 1 Ago 2024, 17:10 K-Krs ***@***.***> ha scritto:

**Comment by DmitryAlexei** [comment]
@D33zN0tz84 there is no such an option. It is implemented as is.

**Comment by mryx007** [comment]
this bug should have priority number 1 and not just in the next version. When cycling, it's extremely annoying when the map turns too early. I've often taken the wrong turn. I'm already thinking about using a different navigation app because it's so annoying. Also, it can't be a feature because the function doesn't even work properly. The map doesn't always turn too early. It often works normally.

**Comment by max69dm** [comment]
I absolutely agree with mryx007, this is a very very important bug that can make you wrong... It is absolutely not an option or anything and needs to be corrected immediately.

**Comment by DmitryAlexei** [comment]
Auto-zoom can be completely disabled in navigation settings (Menu → Configure profile → Navigation settings → Map during navigation). For more information, see https://osmand.net/docs/user/navigation/guidance/map-during-navigation#map-during-navigation

**Comment by max69dm** [comment]
Buonasera, finalmente sono riuscito a comprimere il video e riesco ad allegarlo.
Come si vede la rotazione della mappa in anticipo è evidente. Questo succede in molte altre occasioni su altre strade. Comunque le coordinate di questo tratto stradale sono 45.449322,11.047441 via san michele a Verona italy

**Comment by max69dm** [comment]
Uploading Screen_Recording_20240816_190431_OsmAnd.mp4…

**Comment by max69dm** [comment]
https://github.com/user-attachments/assets/19b35044-5dce-4bbd-a74f-54f232edceb7

**Comment by Rowin63** [comment]
Android +4.9.0 still irritating.

See this example: My position still is BEFORE the intersection, but the map already has turned.
Let´s assune it´s a lot of traffic and I really have to be attentive, now I just want to see with a short view the direction where to go.
The map displays "straight". In that moment I don´t have the time to analyze the map direction, my vehicles direction. I just see "go straight" and that´s wrong, because map view is different from my direction of view.

Please make this function optional. In certain situations it is really confusing.
(and yes, I know, thete is no "straight" in this example intersection, but it is just an example of the function)

![Screenshot_20241023_123435_OsmAnd+](https://github.com/user-attachments/assets/1eef96d3-55a6-4d78-be4a-bebfcfba1b23)

**Comment by Davi427** [comment]
![Screenshot_20241024-104601](https://github.com/user-attachments/assets/11ce51e3-7912-4997-8408-52dcf1a5ed1d)

Same unwanted behaviour here on OsmAnd+ 4.9.0, Released: 2024-09-04. I am more interested in seeing the correct turn now than some future 400 metres. I'll deal with those once I get there. Making the future a priority over the present in these scenarios seems entirely counterproductive to me.

**Comment by dmpr0** [comment]
# ToDo

<table style="width:100%">
  <tr>
    <td><img src="https://github.com/user-attachments/assets/ce81ac82-06df-4f27-abdf-92b4a8a06e03"  width="300" height="auto"/> </td>
  </tr>
</table>   

- [ ] Add new option **Preview next turn**
- [ ] Should be part of **Map during navigation** options list
- [ ] Icon:
- - [ ] On – `ic_action_turn_preview_enabled`
- - [ ] Off – `ic_action_turn_preview_disabled`

**Comment by max69dm** [comment]
Buongiorno
Allego videata di quello che ho io.....non vedo l'opzione che indicate
Esce con la prossima revisione o devo impostare qualcosa io?
Premetto che io ho OSMAND normale a pagamento e non OSMAND PLUS
In attesa Vi ringrazio
Massimo

Il Lun 4 Nov 2024, 15:25 Dmytro Prodchenko ***@***.***> ha
scritto:

**Comment by max69dm** [comment]
![Screenshot_20241104_154211_OsmAnd](https://github.com/user-attachments/assets/028c245f-b038-40e9-9d07-45c7f62f3be3)

**Comment by nazar-kutz** [comment]
@max69dm, Yes, this feature is not yet implemented and is currently under development.
