### ISSUE TITLE
Sunset today but no sunrise tomorrow

### ISSUE THREAD

**Issue by luigifab** [osmandapp/OsmAnd#20447]
### Description

After a while of 24/24 daylight, sunset is back today, as you can see on the following image, but there is no sunrise tomorrow!

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/b5415aa8-e489-457c-ae45-77df8b461c2f"  width="300" height="auto"/> </td>
  </tr>
</table>

### Steps to reproduce

Go to the coordinates (70.51708 26.99096) today (29/07/2024).

### Actual result

No sunrise.
PS: say hello to my 3D button.

### Expected result

Sunrise.

### Your Environment (required)

```
OsmAnd Version: 4.8.4
Android version: 11
Device model: Wiko
```

**Comment by DmitryAlexei** [comment]
- You can change the position of the 3D button after a long tap on it
- Does the issue persist with internet connection?

**Comment by DmitryAlexei** [comment]
@luigifab could you please clarify what does abbreviation lun. in your widget mean? Is it for Monday?
Have you set a specific day/time on your device? Or do you use Automatic day and time (in system settings)?

I have retrospectively set day and time to 29/07/24 and 14.40 and all widget data was gone. That also works starting yesterday and previous days.

But for the actual date/time everything worked

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/64eb7c41-e58d-45ab-abaf-e8f4ebb29d03"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/f2a7a6c2-9dfb-40db-868e-ca05e8d44275"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by luigifab** [comment]
ok thanks for the 3D button

yes l'un for Monday
yesI use automatic day/time from network (automatically set to UTC+2)
yes the problem persist with internet connection

yes today by moving the map to the coordinate it's working (mar for today, mer for wednesday)
![Capture d'écrans_20240730-193240](https://github.com/user-attachments/assets/7ba0ad24-3e29-4ce5-86de-0b783b014704)

but if I move the map to the north, sunrise disappear
(near 70.69712 27.07937 for example)
![Capture d'écrans_20240730-193330](https://github.com/user-attachments/assets/98fb8d26-df43-471e-9255-e176ca5ece87)

**Comment by DmitryAlexei** [comment]
OsmAnd~ 4.9.0#2879m, released: 2024-08-01 
issue reproduced: sunrise and sunset data not present for specific day/time and map coordinates

Steps to reproduce
- in system settings set device date and time to 29/7/24 14:40
- go to coordinates 70.51729 26.99111
- see if date for sunset/sunrise is present in widgets
- scroll the map to the south and see if info is present in widgets (see video)



https://github.com/user-attachments/assets/6179c0fd-a92c-40a4-b943-42c987e2511e

**Comment by vshcherb** [comment]
@Chumva we need more information what's hapenning and where is the bug

**Comment by nazar-kutz** [comment]
It seems that the issue lies in the calculation algorithm we are using. It is based on the idea that only the sunset or sunrise occurring within 24 hours from the current moment will be calculated. Here is the calculation method: https://github.com/osmandapp/Osmand/blob/2f8462f7c33db79c5e66d7cfec051ecc86dc4926/OsmAnd-java/src/main/java/net/osmand/util/SunriseSunset.java#L278. 

If the sunset or sunrise does not occur within the next 24 hours, the calculations will not be performed, and the algorithm will return null for the sunrise or sunset request: https://github.com/osmandapp/Osmand/blob/2f8462f7c33db79c5e66d7cfec051ecc86dc4926/OsmAnd-java/src/main/java/net/osmand/util/SunriseSunset.java#L612-L645

It appears that for the coordinates provided in the screenshot (70.51708 / 26.99096), the algorithm indeed cannot calculate the sunrise and sunset for the next 24 hours, and this seems to be the correct result, as I checked with other online calculators and it seems that for the chosen date, July 29, 2024, it is indeed not possible to calculate sunrise and sunset data.

This means that we either need to improve the algorithm so that it can calculate the sunrise or sunset over an interval longer than 24 hours, or explicitly state that we have this 24-hour limitation (for example, in the documentation or in the widget description within the app).

**Comment by nazar-kutz** [comment]
For testing I used calculations from https://latlongdata.com/sunset-sunrise-calculator/

**Comment by vshcherb** [comment]
> This means that we either need to improve the algorithm so that it can calculate the sunrise or sunset over an interval longer than 24 hours, or explicitly state that we have this 24-hour limitation (for example, in the documentation or in the widget description within the app).

I think it's wrong conclusion. Current algorithm is enough. App widget should display next sunrise time. 

As we see on screenshot Sunset is calculated and it's summer, so sunrise should be very soon after sunset for example 23:50 lun or 00:30 <next day>, so I don't think it has something to do with algorithm.

**Comment by luigifab** [comment]
Now it's working!
