### ISSUE TITLE
Rotation malfunction on map.

### ISSUE THREAD

**Issue by natuwes** [osmandapp/OsmAnd#20443]
### Description

Since the latest up- or downdate of your app, the "button" to switch between map rotations doesn't work anymore when pushing on it. It now only works when long-pressing on it. See enclosed pictures.

Device : a52xq
Brand : samsung
Manufacturer : samsung
Model : SM-A526B
Product : a52xqnaeea
Build : UP1A.231005.007.A526BXXS8GXE1
Version : 14

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/b6813144-176b-4009-8cd1-7ad017f5ff23"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/86c08bcd-790b-409a-a6ed-3bdb3ff4de10"  width="300" height="auto"/> </th>
  </tr>
</table>

App Version : OsmAnd+
Apk Version : 4.8.4 4804

### Steps to reproduce

See one of the enclosed pictures. Open the map and try to rotate the map with the compass button. It will not rotate anymore.

### Actual result

No rotation anymore.

### Expected result

Map rotation in accordance with the direction as seen in one of the enclosed pictures.

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version:
Android/iOS version:
Device model:
Crash-Logs: ?
```

**Comment by yuriiurshuliak** [comment]
The bug was not reproduced. I attempted to reproduce it, and you are correct: clicking the compass icon once does not change the map orientation mode. However, double-clicking the compass icon does change the map orientation mode. Additionally, long-press this icon allows you to select the map orientation mode from a list.

OsmAnd 4.8.4, released: 2024-07-24

https://github.com/user-attachments/assets/1bf89046-8293-4871-af02-0412c1d84c0f

**Comment by natuwes** [comment]
This issue is, so I've read, a new feature made by the app builders of OSMAND+. More information of it is written in the update information given in the app itself.

**Comment by natuwes** [comment]
Problem solved - see my reply to it.
