### ISSUE TITLE
Strange navigation around Amsterdam

### ISSUE THREAD

**Issue by Ernst-47** [osmandapp/OsmAnd#20490]
### Description

I open a bug report on request of C from the support team.

I encountered strange navigation behaviour around Amsterdam.
See attached screenshots.

This is consistent over time ans on different Android devices. Android 8 and 14.

On a different journey along the A10 in Amsterdam I lost navigation instructions in that area. Only after the junction A10/A9 near Badhoevedorp the instructions picked up again.

I noted that the detailed Amsterdam map has a green line raster and some green bold line marker lines. Could that be the root cause?
This is from the map NORTH HOLLAND 01.07.2024

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/a1c9411d-c62e-4a94-855a-572d28cacc41"  width="300" height="auto"/> </th>
<th><img src="https://github.com/user-attachments/assets/f364b08a-8006-4947-a236-cac8e295bf7d"  width="300" height="auto"/> </th>
  </tr>
</table>

### Steps to reproduce

Simpel by starting a new navigation for locations in te Amsterdam area.
Start: Huizen Piersonlaan 9
Destination: Amsterdam Mosveld 125
I could not create a navigation simulation. It simply does not work for this itinerary.

Other example:
The startpoint: Europaboulevard Zuid Amsterdam. the entrance to the A10.
The destination: Exit on A4 to Schiphol.
For both I used: Choose on Map.

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/33a64c0a-d317-4e61-9f93-239ace5fd147"  width="300" height="auto"/> </th>
<th><img src="https://github.com/user-attachments/assets/8038f6fd-151c-4292-9d12-6b3c46cb45c5"  width="300" height="auto"/> </th>
  </tr>
</table>

### Actual result

No navigation possible.

### Expected result

A navigation recommendation as usual. Since the last 12 years that I am an OSMAND User.

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: OSMAND+ 4.8.4 - 2024-07-24 
Map:  NORTH HOLLAND 01.07.2024
Android/iOS version: 8 and 14
Device model: S7 Edge and S24+
Crash-Logs: ? I could not load my profile osf.  (We don’t support that file type.) I have e-mailed this earlier to Zinaida. 
```

**Comment by yuriiurshuliak** [comment]
Related to https://github.com/osmandapp/OsmAnd/issues/14613

**Comment by vshcherb** [comment]
- I noted that the detailed Amsterdam map has a green line raster and some green bold line marker lines. Could that be the root cause?

It's Limited E zone, it's unrelated.

This looks superweird, as it doesn't recognize start point correctly. Do you have maps updated to the same version 01.07. I understand new maps are released and they could create a different issue

**Comment by Ernst-47** [comment]
Guys, thanks for your attention.

I downloaded North-Holland Map of 01.08.2024. 
This one gives the same result. Unfortunately.

**Comment by yuriiurshuliak** [comment]
The bug was not reproduced. To reproduce this issue, I selected the approximate start and finish points you mentioned on the map and enabled navigation simulation.

The navigation route was  built correctly, without the straight line issue previously described.

This problem might occur if there are no valid roads for navigation or if the necessary maps are not fully loaded. To reproduce this bug, we need the logs from when the issue occurred: go to Menu → Help → Send logcat log. Additionally, please provide the exact coordinates of the start and finish points where you encountered this problem, and your profile settings: Menu → Settings → Import/export → Export to file. Updating the maps might also resolve the issue.

OsmAnd 4.8.4, released: 2024-07-24

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/765628c1-5c41-4f5d-b8ac-e80aecd3e1b2"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/24a89ad1-4bcd-4bbe-939d-bf59191b1c23"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by vshcherb** [comment]
Could you try independelty install https://download.osmand.net/latest-night-build/OsmAnd-default.apk and check with default settings

**Comment by Ernst-47** [comment]
Attached the logcat.log
[logcat.log](https://github.com/user-attachments/files/16510109/logcat.log)

**Comment by Ernst-47** [comment]
I also tried yesterday again on my S7Edge to plan a route to Ilpendam Town.
First of all I got a request to load the Frisia/Friesland map. Which is the map adjacent to North-Holland on the north side.
As you can see the route calculated is not the mos logic one, which should go east of Amsterdam following the A10. 
![Screenshot_20240805-192903_OsmAnd+](https://github.com/user-attachments/assets/d1ff7ac7-8a6b-497d-b156-9219ccecf619)
![Screenshot_20240805-193604_OsmAnd+](https://github.com/user-attachments/assets/817ae178-fcc8-47a6-8156-32f5347a7930)
![Screenshot_20240805-193644_OsmAnd+](https://github.com/user-attachments/assets/8a6141d8-48e3-49d5-96df-c9f6329366a4)

**Comment by vshcherb** [comment]
The results should match website - https://osmand.net/map/navigate/?start=52.364175,5.256958&end=52.455591,4.944534&profile=car#11/52.2791/5.1248
It leads to sort of conclusion that during updates app get into some kind of corrupted state? So if you can export personal valuable data and reinstall with new settings / maps , you will get it fixed very likely. 

If you had installation since 4.5-4.6 than it could be there some faults introduced

**Comment by yuriiurshuliak** [comment]
The bug was not reproduced. I imported your profile and attempted to build the route using the provided coordinates. With your profile, the navigation indeed takes a detour. However, I observed that the "Avoid low emission zones" option is enabled in your profile, which influences the route calculation and causes the detour. Disabling this option results in the route being build correctly.

I suggest resetting your profile. Go to Menu - Settings - App profile (Driving) - Reset to default.

<table style="width:100%">
  </tr>
  <tr>
    <th>"Avoid low emission zones" Enabled</th>
    <th>"Avoid low emission zones" Disabled</th>
  </tr>
  <tr>
<th><img src="https://github.com/user-attachments/assets/5dc33fbe-a96c-408e-992e-7c950067b45e"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/d2fd0a19-ba70-460b-b0f6-78f9dfe71389"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by Ernst-47** [comment]
Thanks guys. 
App profile (Driving) - Reset to default did is the solution. 

I have to investigate on this low emission setting. My main requirement is to have it on in Italy where they work with the ZTL ( Zona a Traffico Limitato') Just see if I can make these working without the "low emission"setting.

For the moment you can consider the case as closed.
A happy OSMAND User. !!!
