### ISSUE TITLE
routing somehow "crashed" after a "screen refresh"

### ISSUE THREAD

**Issue by Rowin63** [osmandapp/OsmAnd#20525]
### Description

Following a route I noticed something like a very clearly "screen refresh".
After this the route line and also the lane indicators were not displayed anymore.
I restarted the routing (selected the same destination again) and osmand asked me "if I want to replace or add" so that means, in the background the previous routing still was active. 
But without route line and lane symbols.
After "replacing" the destination, route line and lane indicators were displayed correct again.

### Steps to reproduce

I dont know, it just happened.

### Actual result

...

### Expected result

...

### Your Environment (required)

OsmAnd Version: nightly 4.9.0#2904
Android/iOS version: 13
Device model: S20+

**Comment by yuriiurshuliak** [comment]
The bug was not reproduced. To test, I launched navigation and then completely closed the app. Upon reopening it, navigation was successfully restored.

I also tried running navigation and leaving the app in the background by switching to another app. When I returned, navigation was still restored.

Please try updating to the latest nightly version and see if the issue persists there.

OsmAnd~ 4.9.0#2935m, released: 2024-08-08

https://github.com/user-attachments/assets/b53f5e0c-c9d8-42d6-b747-c2471c06a551

**Comment by Rowin63** [comment]
Anyway I didn´t expect this issue/happening being reproduceable.
But in case it will happen again or to somebody else, then it is already documented here.

**Comment by Rowin63** [comment]
"not planned" but happened again.

Today I was following a route and at one moment I noticed, that the route line was gone. Routing still was active (you can see this by some info, like distance to the finish point).
When selecting the finish again, Osmand asked me "do you want to replace the finish?" and after doing so, the route was calculated and displayed.

You can see at this screenshot:
) routing still is active (distance to the finish)
) there is no routing line on display
) by the way, the displayed speed limit is wrong, it is 80km/h on this highway (I´m not sure (!), but I think it was displayed correctly before this issue happened)

![Screenshot_20240826_141901_OsmAnd+](https://github.com/user-attachments/assets/7c217ef1-4e0c-4aaf-ab2e-dc55f9545b2c)
