### ISSUE TITLE
Setting map to Italian with "use latin names " doesn't seem to switch to latin characters

### ISSUE THREAD

**Issue by Max1234-Ita** [osmandapp/OsmAnd#20549]
### Description

I've encountered a quite strange behaviour while exploring the map over a region of Russia Oblast of Pskov): all the names were shown in Cyrillic characters (as expected, actually), si I decided to switch to Latin characters, si I set /// -> Configure map -> Map language  to Italian and also enabled the option "Use Latin names if missing".

After doing that, I saw the cyrillic names were still visible, so I changed the language to English and the names became in latin characters.

### Steps to reproduce

1. Launch OsmAnd; go to /// -> Configure map -> Map language; Ensure that the selected option is _"Local names"_

2. Download a map of Russia (i.e. Pskov oblast).

3. Scroll the map over the downloaded region: the names are in Cyrillic 

4. Go to /// -> Configure map -> Map language; Select _Italian_ + _"Use lain names"_
   --> The toponyms remain in Cyrillic.

5. Go to _/// -> Configure map -> Map language_; Select _English_ + _use Latin names_;
   --> The names switch to latin alphabet

6. _Go to /// -> Configure map -> Map language;_ switch to Italian + latin names:
   --> the Latin characters remain.

7. Go to /// -> Configure map -> Map language; Switch back to _Local names_
   --> The cyrillic names comes back

8. Go to /// -> Configure map -> Map language; Select Italian + latin names again.
   --> Names are still in Cyrillic

### Actual result

Toponyms on the map are still in Cyrillic alphabet even if "Italian" and "use of latin names" option is selected

### Expected result

Names in latin character should become visible, as it happens with English language.

I haven't tried, but I suspect this behaviour is present also with other languages different from English.

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: OsmAnd Plus v. 4.8.4
Android/iOS version: Android 11
Device model: Samsung Galaxu A50 (SM-A505 FN)
Crash-Logs: ? None
```

**Comment by yuriiurshuliak** [comment]
The bug could not be reproduced. To reproduce, try downloading the map of the Pskov region and set the Map language to "Local names"—you should see the names in Cyrillic. Then, switch the Map language to Italian and enable "Use Latin names."

This should result in Latin names being applied. Please update the app or try our beta version at https://osmand.net/docs/versions/nightly_versions#google-play-beta-builds, and let me know if the issue is resolved.

OsmAnd~ 4.9.0#2976m, released: 2024-08-14

https://github.com/user-attachments/assets/0c85a0ff-77d1-4253-a2e1-b8c20219a5f9
