### ISSUE TITLE
keyboard layout issue: US qwerty always present in input keyboards, only in OsmAnd

### ISSUE THREAD

**Issue by spongebyte** [osmandapp/OsmAnd#20579]
### Description

Pixel 6a, LineageOS 21 (Android 14).
OsmAnd~ 4.8.5.

US qwerty keyboard always shows up in OsmAnd input text windows, even though I have US qwerty configured nowhere in my phone. This happens only in OsmAnd.

Thank you.

### Steps to reproduce

Have UK English as system language. Possibly any other keyboard language.
Input any text in OsmAnd.
https://imgur.com/a/whNOOeK you can see me in OsmAnd showing input methods (extra US qwerty always present), I am showing enabling/disabling FR azerty (no impact on US qwerty), and I am showing input methods in another app (no extra US qwerty).

### Actual result

US qwerty is present in the input methods as if I had configured it in Android, but I have not.

### Expected result

I am expecting to see input methods that I configured in Android, no extra method.

### Your Environment (required)

Pixel 6a, LineageOS 21 (Android 14).
OsmAnd~ 4.8.5.

**Comment by MarioSwitch** [comment]
Same issue here, forced to set OsmAnd language to French to have actual AZERTY keyboard...

OsmAnd 4.8.6 / Android 14 / Google Pixel 7

**Comment by yuriiurshuliak** [comment]
I couldn't reproduce the bug. I tested it with both British and American system languages, using British and Ukrainian keyboard settings. In every scenario, the American QWERTY keyboard didn't appear in the OsmAnd text input windows, unless it was manually configured. This issue seems to be related to your device's settings.

OsmAnd~ 4.9.0#2997m, released: 2024-08-16

https://github.com/user-attachments/assets/7a091908-f1a7-4638-9f0a-4714200c479e
