### ISSUE TITLE
Automatic "direction of movement" when starting navigation.

### ISSUE THREAD

**Issue by raleik-pl** [osmandapp/OsmAnd#20606]
### Describe the idea

It would be nice to have an option to automatically set map orientation to "direction of movement" when starting navigation. Right now it's only possible with manual setting by multiple/long-pressing a button.

### Expected behaviour

Having a map oriented north-up when browsing, and in "direction of movement" when navigating is what all other apps (I'm aware of) do by default.
I'd like to see an option to automatically switch between those two, just like there is an option to automatically display current position centered or down the screen.

### Alternatives you've considered

There aren't any. You have to switch orientation manually everytime.

**Comment by vshcherb** [comment]
I think you don't need to switch map orientation is tight with profile, so it should work as you saved last time

**Comment by pentastich** [comment]
> I think you don't need to switch map orientation is tight with profile, so it should work as you saved last time

I use CycleOSM in my Cycling profile, so I'm usually in the Cycling profile when planning a route. While I'm planning I want "North is Up" orientation, but when I'm actively navigating I want "Movement Direction".

For that use case, attaching the orientation to the profile (e.g., "Cycling") isn't sufficient. The ideal would be either a separate setting for Cycling and Cycling+Navigating, or an option to switch orientations when navigation starts.

**Comment by sonora** [comment]
Out-of-the-box behavior: The app uses the default profile, which is 'North is up', for planning and viewing, and automatically switches to a corresponding 'Direction of motion' profile, like car or bike, for exactly the duration of any navigation .

So what you expect is automatic, the app
- uses the Cycling profile with 'Direction of motion' for navigation, 

and for viewing and planning you can
- either use the Browse map profile in 'North is up' mode (out of the box default) and perhaps configure with additional cycling elements as needed,
- or define a copy of the cycling profile as your default profile.

**Comment by pentastich** [comment]
That seems like a lot of work for a feature I expect a lot of people want to see. It would also require that any change to the "cycling" profile be made in multiple places, which is awkward and error prone.

Navigation and planning are two distinct activities. When planning I, and I suspect many (even most) people, want "North is Up" because it allows us to use "muscle memory" to find locations on a map, and to quickly evaluate the quality of different routes. When navigating, however, I'm mostly interested in the next turn (left or right), and that's best communicated by "Movement Direction". I shouldn't have to maintain two separate profiles and switch between them in order to achieve what is the default behaviour on many navigation systems, such as Google Maps.
