### ISSUE TITLE
Wikipedia links lead to main page 

### ISSUE THREAD

**Issue by mitkin89** [osmandapp/OsmAnd#20620]
### Description

When saved in favorites pressing to read Wikipedia article online leads not to the article but to the main wiki page 

### Steps to reproduce

Open a favorited wiki article from on the map and press to view it online

https://github.com/user-attachments/assets/82a5a9cf-639d-4876-b3ce-f1126ae99708

### Actual result

Leads to main wiki page 

### Expected result

Leads to the actual article 

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: 4.8.6
Android/iOS version: Emui 14
Device model: Mate x3 
Crash-Logs: ?
```

**Comment by yuriiurshuliak** [comment]
The bug has been reproduced. To reproduce: enable the Wikipedia plugin, download the Wikipedia packages, display the Wikipedia POIs, add one of the Wikipedia POIs to your favorites, select this favorite to read the article, click "Read full article," and then click "Read full article online."

As a result, instead of being redirected to the specific article, you'll be taken to the main page of Wikipedia in the browser.

OsmAnd~ 4.9.0#2997m, released: 2024-08-16


https://github.com/user-attachments/assets/dc53f012-a742-4ac9-a5ec-dedc28173340

**Comment by vshcherb** [comment]
@yuriiurshuliak is it a regression (4.5)? is it for all languages / articles that are not inside obf files?

**Comment by yuriiurshuliak** [comment]
Since the issue also occurs in version 4.5, it is a regression. The problem relates to downloaded OBF files and has been verified in Polish, German, and English languages.

When you add Wikipedia POIs to your favorites and then try to read the article online in a browser, you are redirected to the main page. However, if you don't add the Wikipedia POI to favorites and attempt to read the article online, you are correctly redirected to the specific article.

OsmAnd 4.5.10, released: 2023-08-09

<table style="width:100%">
  </tr>
  <tr>
    <th>Polish</th>
    <th>German</th>
    <th>English</th>
  </tr>
  <tr>
    <td> <video source src="https://github.com/user-attachments/assets/deea8e2d-e25d-4145-9e23-b8010d0e518a"  width="300" height="auto"/>   </td>
    <td><video source src="https://github.com/user-attachments/assets/9b0f79f2-fcbc-41b9-9d7b-ad556ed0e59c"  width="300" height="auto"/>   </td>
    <td><video source src="https://github.com/user-attachments/assets/d44709a4-17be-44db-8da1-1bed59243171"  width="300" height="auto"/>   </td>
  </tr>
</table>

**Comment by RZR-UA** [comment]
The feature of adding Wiki Articles as Favorites is somehow lost in the current nightly build.

To Do:

- [ ] figure out and get back the broken feature
- [ ] fix the wrong URL on save/click for favorites.gpx with wiki-points

**Comment by DmitryAlexei** [comment]
- test iOS version

**Comment by Zirochkabila** [comment]
- [ ] Follow the direct link to the Wiki article


<table style="width:100%">
  <tr>
    <th>OsmAnd~ 5.0.0#3748m, Released: 2024-11-18</th>
    <th>4.9.0.2</th>
  </tr>
  <tr>
    <td><video source src="https://github.com/user-attachments/assets/6264df3f-900e-4dc2-a6ac-133ddd9fed01"  width="300" height="auto"/></td>
    <td><video source src="https://github.com/user-attachments/assets/3dd37e55-070f-4cad-85c6-b6fc9f519e72"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by vshcherb** [comment]
- [ ] Link is ok  http://en.wikipedia.org/wiki/March_(territory) - probably Android doesn't do correctly encodeHttpParams with '('

**Comment by 0xRe1nk0** [comment]
The wikipedia links are incorrect, **"wikpedia"** is missing **"i"**. Potential place with bug [here in map creator](https://github.com/osmandapp/OsmAnd-tools/blob/b0af64c9780c1c27a3b897ab34b5d0be7a6f0a8d/java-tools/OsmAndMapCreatorUtilities/src/main/java/net/osmand/wiki/WikiDatabasePreparation.java#L1865)

Example of incorrect link in article - http://en.wikpedia.org/wiki/March_(territorial_entity)

**Comment by RZR-UA** [comment]
The URL in the generation is fixed. We have to regenerate Wikipedia data ASAP.

**Comment by Zirochkabila** [comment]
```
4.9.0.8
OsmAnd~ 5.0.0#3832m, Released: 2024-11-28
```

Behavior is unchanged:
1. If clicked on Read full article, the correct transition occurs
2. If click on any link inside the article, user is redirected to the Home Wiki page

**Comment by RZR-UA** [comment]
@Zirochkabila, please try downloading fresh Wikipedia maps on Friday afternoon.

**Comment by Zirochkabila** [comment]
Done
