### ISSUE TITLE
Incorrect turn lanes (Mapping)

### ISSUE THREAD

**Issue by Prusaker** [osmandapp/OsmAnd#20642]
### Description

Incorrect turn lanes when turning right (Instead of a right turn, two lanes for going straight are shown).

### Steps to reproduce

Build route (car profile) from 53.6181349, 23.870238 to 53.6179878, 23.8727604.
Two lanes for going straight are shown instead of a right turn:
![111](https://github.com/user-attachments/assets/63de6cce-62e8-4938-8749-b652706e0c6e)

This place on Yandex Panoram:
[https://yandex.by/maps/10274/grodno/?l=stv%2Csta&ll=23.870569%2C53.618794&panorama%5Bdirection%5D=63.261374%2C-5.197025&panorama%5Bfull%5D=true&panorama%5Bpoint%5D=23.870240%2C53.618075&panorama%5Bspan%5D=105.076188%2C60.000000&z=18.16](url)

This place on OSM:
[https://www.openstreetmap.org/way/744599679](url)

### Actual result

Two lanes for going straight are shown instead of a right turn.

### Expected result

Right turn must be displayed.

### Your Environment (required)

OsmAnd Version: 4.9.0 #3018m
Android/iOS version: 7.1.1
Device model: Nexus 6

**Comment by yuriiurshuliak** [comment]
The bug has been reproduced. To reproduce this bug, go to the provided coordinates, build a route, and start navigation. You will notice that the Lanes and Next Turn widgets display incorrect turns, showing a straight path instead of a right turn.

Interestingly, the turn is displayed correctly in the web version.
Here is link: [link](https://test.osmand.net/map/navigate/?start=53.618130,23.870240&end=53.617988,23.872760&profile=car#17/53.61818/23.87004)

OsmAnd~ 4.9.0#3030m, released: 2024-08-20

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/97759f97-c482-4a7c-b0b3-c16700fd6fcc"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/d4dd8c0a-1690-4a59-a772-f2d8f16496a3"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by vshcherb** [comment]
Probably this is incorrect mapping - https://www.openstreetmap.org/way/539317843 cause here it's unlikely possible to turn right

**Comment by vshcherb** [comment]
With changed mapping to "left;through|through" - data looks correct
![Screenshot 2024-08-30 at 14 32 56](https://github.com/user-attachments/assets/f502323e-d85a-4ab1-bd0b-110f20e95afe)
![Screenshot 2024-08-30 at 14 32 12](https://github.com/user-attachments/assets/abddb7f3-10c7-48b6-b026-69e0e2805c6b)

**Comment by Prusaker** [comment]
Thanks, I will change turn:lanes to correct value.
