### ISSUE TITLE
Switching the keyboard location

### ISSUE THREAD

**Issue by Tobiasgit0** [osmandapp/OsmAnd#20678]
### Description

Android 14; Osmand 4.8.6

I have three keyboard locations activated: German, English and Spanish. I use my phone in the English language but with the German keyboard.

Problem: Everytime I open Osmand (behaviour is odd since very few versions) the keyboard now switches to the English location. And I have to readjust it.

### Steps to reproduce

Activate three keyboard locations: German, English, Spanish. Set the phone's language to English. Use the German keyboard as standard. Open Osmand. It should now switch the keyboard to the English location

### Actual result

see description

### Expected result

The expectation is no change of the keyboard location when opening the app

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: 4.8.6
Android/iOS version: 14
Device model: Pixel 8 Pro
Crash-Logs: ?
```

**Comment by yuriiurshuliak** [comment]
The bug was not reproduced. To test it, I enabled three languages for the keyboard: German, English, and Ukrainian. I set the phone's language to English and made the German keyboard the default. Then, I opened OsmAnd, went to Search, and the keyboard appeared as expected.

The German keyboard layout was displayed.

OsmAnd~ 4.9.0#3071m, released: 2024-08-25

https://github.com/user-attachments/assets/9a1cd7f7-7cf8-4e79-9e89-6d58b77c7fc4
