### ISSUE TITLE
Favourites in webinterface

### ISSUE THREAD

**Issue by pawelpbm** [osmandapp/OsmAnd#20690]
### Description

In the web map (https://osmand.net/map/) when you click on favourite icon on the map instead of opening favourite point details, first list of all favourites is opened. You have to click the second time to actually show the details of the favourite point.

This used to work fine ~week ago.

### Steps to reproduce

1. Have some favourites on the map
2. Click it once - list is opened
3. Click it again - point details are shown

### Actual result

Favourite list is opened on the first click.

### Expected result

Favourite point details are opened on the first click.

### Your Environment (required)

Google Chrome 125.0.6422.142

**Comment by yuriiurshuliak** [comment]
The bug has been reproduced. Here are the steps:

- Open some favorites on the map in OsmAnd web.
- Click on a favorite icon on the map.

Actual Result: Instead of opening the details for the selected favorite, a list of all favorites appears, which in my case is the favorites folder. 
Expected Result: The details of the selected favorite should display immediately upon the first click.

- Click the favorite icon again to view the specific details.

https://github.com/user-attachments/assets/f520aaa0-c933-4489-a2b8-bcca4c9b930f
