### ISSUE TITLE
Compass icon contrast

### ISSUE THREAD

**Issue by sonora** [osmandapp/OsmAnd#20773]
As a spin-off of #20764: The icon contrast for the gray 'N' portion has now become very poor. It uses a much brighter shade of gray than the other gray widgets like e.g. the magnifier icon, see below. Not sure that is intended?

![Screenshot_20240907-095301_OsmAnd~](https://github.com/user-attachments/assets/b7dad9e5-677d-40e6-bb0c-5f6d160a3019)

(Even the contour line label shining through the search icon seems to have better contrast?)

**Comment by Rowin63** [comment]
I think it's also related to this one (general viability of buttons)

#16079

**Comment by yuriiurshuliak** [comment]
The bug has been reproduced. To observe it, update to the latest nightly version and check the compass icon.

The issue is that the contrast for the gray part of the "N" in the compass icon has become poorly visible compared to the magnifier icon.

OsmAnd~ 4.9.0#3148m, released: 2024-09-09

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/7b1ecb70-f98e-4d2f-9eb7-d4bfb5d97a91"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/142eb215-19a3-47eb-bed5-286773107f6d"  width="500" height="auto"/> </th>
  </tr>
</table>

**Comment by vshcherb** [comment]
@Chumva contact @dmpr0 if needed
