### ISSUE TITLE
Unable to interact with markers on POI

### ISSUE THREAD

**Issue by Cwpute** [osmandapp/OsmAnd#20803]
Description

I usually set markers for points where i want to go someday. So i put them in lots of different places, but usually on points of interest. The problem is that some markers can't be directly accessed or interacted with once they are set on POI.

Steps to reproduce

1. Set a marker flag on a POI
2. See problem
3. Set a marker flag on a Favourite
4. See problem

Actual result

When i tap on the POI or the marker, a list of interactible objects are shown, but the marker is not listed.

<table style="width:100%">
  <tr>
<th><img src="https://i.postimg.cc/RVxwDczD/Screenshot-20240910-142322.png"  width="300" height="auto"/> </th>
  </tr>
</table>

However, if i choose to view details for my Favourite, located on the same point:

<table style="width:100%">
  <tr>
<th><img src="https://i.postimg.cc/DyCyXT5P/Screenshot-20240910-142342.png"  width="300" height="auto"/> </th>
  </tr>
</table>

I can interact with the marker, but only because it appears as "linked" to that Favourite.

Another example:

<table style="width:100%">
  <tr>
<th><img src="https://i.postimg.cc/sD23yLyQ/Screenshot-20240910-142437.png"  width="300" height="auto"/> </th>
  </tr>
</table>

Here, when you tap the POI, you're not even presented with a list of objects on the same spot: the UI instantly shows you the POI, but contrary to the Favourite interface, you cannot interact with the marker below (you can see a small bit of the marker flag pointing from below the location marker).

Expected result

OSM&+ should present you with a direct and consistent access to the marker flag and its options from the map.
The easiest solutiwn would be to always show the marker alongside in the list of objects sfaring the same spot.

Your Environment (required)

Android 11
OSM&+ v4.8.5

**Comment by yuriiurshuliak** [comment]
The bug was not reproduced. To test this, I placed a marker on both a POI and a favorite, then clicked on each with the marker active.

As a result, when I touched a POI with a marker on it, a list of interacting objects was displayed, including the marker. When I touched a favorite, the context menu of the favorite appeared, allowing interaction with the marker.

Please try using our nightly version and let us know how it works for you: [Nightly Builds](https://osmand.net/docs/versions/nightly_versions#nightly-builds).

OsmAnd~ 4.9.0#3179m, released: 2024-09-12

https://github.com/user-attachments/assets/90d3ec17-0849-4473-bf4e-4db1f5dddb0b

**Comment by Cwpute** [comment]
I won't be testing with the Nightly build, sorry, because the apk in itself is very heavy and i'm on a limited data plan :(
Can you *test* with the previous version ? if the bug does occur as i describe it then it means it was fixed in the Nightly so this issue can be closed.

**Comment by vshcherb** [comment]
Ok, soon we will release a beta (that has tiny update) so it's possible to update will be .

**Comment by Cwpute** [comment]
cannot reproduce it either in the nightly. i'll wait for a public release and test it again.
