### ISSUE TITLE
All maps are lost after update. serious BUG.

### ISSUE THREAD

**Issue by gorn** [osmandapp/Osmand#2081]
After upgrade to 2.2.4 osmand+ from Google play all maps disappeared. I will need to fing way to download them back (not easy wit mobile data abroad). There should be a WARNING - maps lost on upgrade, proceed only when you do not mind. It happened also 4 days ago when i upgraded.

This has bitten me twice during last week and since I am travelling (i.e. on unreliable data connection and relying on nav) it is gery inconvinient.

**Comment by sonora** [comment]
I have heard nothing the like from other users just yet, so I would say this is not general behavior ...!?!

Can you please report more details on your particular environment like device, Android version, path to the data folder you are using, what version were you upgrading from, etc .

Also: Can you verify whether the map files have really disappeared from your device, or maybe OsmAnd just somehow changed the path to the data folder (maybe from internal to external storage or similar) and is pointing to a new/empty folder, so that resetting the path fixes the issue?

**Comment by vshcherb** [comment]
Did you change Android version in between 2.2.3 and 2.2.4? 
Technically 2.2.4 has very small but important bugfix with waypoints and nothing has changed with sd card.
I think your maps are still available, but they might be in a different folder. If you just upgrade (not uninstall and install again), the maps should stay.

**Comment by vshcherb** [comment]
It is very serious bug we need to investigate what are the circumstances and how many people experience it.

**Comment by stephan75** [comment]
Was it an upgrade from free Osmand version to plus version?

**Comment by noci2012** [comment]
What i have noticed is that the maps seem to be lost because the maps have local names and after upgrades the enlish name is used to find data...

Maps: NEDERLAND
After upgrade address search shows NETHERLANDS in region.

Just clearing and selecting a new region was sufficient.
I did loose some maps because the SD card was not sync()'ed and the phone crashed a day after the downloads were done due to a corrupted SD card.

**Comment by vshcherb** [comment]
Investigated that issue, but the actual reason was not found yet. If we get more feedback for other cases, it could be helpful. For now we will focus on other issues.

**Comment by gorn** [comment]
I was on OsmAnd plus all the time and in happened in two consecutive upgrades (to 2.2.4 and to some few days before it - do not have the number). The most annoying thing was that it happend on slow internet abroad (i.e. high roaming prices) when i relied on OSMAnd. I updated recently again but now everything works fine. I am aware that without more evidence you can not proceed, so unless someone else experiences the issue, this should stay closed. Thanks anyways

**Comment by sonora** [comment]
Just t mention it here again for future reference: The only well-known issue I am aware of (and it is an android issue) is this:

If you UNINSTALL (not upgrade) any app under Android 4.4.x (possibly also higher), Android also wipes all the data in the app's assigned data folder (for OsmAnd under Android 4.4.x usually something like (selected-storage)/Android/data/net.osmand(.plus). (Unfortunately, for OsmAnd this affects all your maps, often GBytes worth of data!)

So in order t keep your data you would have to remember RENAMING that folder before you trigger any uninstall operation(!)

**Comment by skipgilles** [comment]
Same issue here. Upgraded to plus; no map whatsoever (also no overview map of the world).

I used to have my maps saved on SD card.

**Comment by vshcherb** [comment]
This is standard Android behavior it deletes all file if the app is deleted. If you still have the app, you can change storage folder in OsmAnd app and in OsmAnd+ to Shared storage and restart. The maps will be available in 2 apps

**Comment by skipgilles** [comment]
Ah, it works now, thanks. I now want to delete my non-plus OsmAnd app. Gonna see whether unsharing first helps.

**Comment by gorn** [comment]
Just for the record: I did NOT unistall the app and reinstall it again. I only upgraded already installed plus version to new plus version.

**Comment by matthias-reimann** [comment]
Hi, I am surprised that nobody else reported this issue in the meantime. 
I lost all my offline maps during upgrade for the third time now. 
- Upgrade of osmand.plus without any uninstall
- map files are actuality gone (not just in a different folder) 
- maps were stored on SD card using standard path (/storage/01C6-xxxx/Android/data/net.osmand.plus/files)
- current version is 2.6.2, Android 6.0
- device is Honor 7

Thanks for looking into this

**Comment by sonora** [comment]
I must be really specific to your environment, because I cannot reproduce this at all ....

Can you please specify all details available, like
- from what version to what version exactly you are updating
- what app store you are using
- is your data storage path before an after an update the same or different
- do you see any dialogs related to the app storage folder in the process
- are you using a stock ROM or a modded one, etc.

I cannot think of more questions to ask here, but have to repeat that by all evidence we have about this it does not seem to be a general issue, and may actually be limited to your setup..

**Comment by ducky64** [comment]
I'm getting this issue too, regularly after Play store updates. All the files directly under net.osmand.plus are deleted, this is typically the map files. But things in subdirectories like contour lines, road-only maps, and hillshades are not affected.

I don't know if it matters, but I'm using multiuser storage (Android/obb/net.osmand.plus). This occurs consistently on two devices, one with LineageOS 14 and another with LineageOS 15. There is no indication of the wipe pre-update, but starting OsmAnd afterwards starts the usual download your maps startup flow. OS upgrades and device reboots do not wipe map data.

**Comment by gorn** [comment]
As you see the bug is closed for some years.  You may consider to ask for reopening it

**Comment by miro-janosik** [comment]
I had automatic updates for OsmAnd disabled for a long time because of this.
Now when I updated the maps are still there, maybe it is fixed now.
