### ISSUE TITLE
Recalculate Route Without Profiles Changing does not update GPX

### ISSUE THREAD

**Issue by david-gpu** [osmandapp/OsmAnd#20870]
### Description

When you select a track and click on *"Recalculate Route Without Profiles Change"*, the route is updated on the screen. However, if you then click on the *"Save"* button on the upper right corner, the GPX is left unchanged.

### Steps to reproduce

Open a track. Click on the bottom right icon that indicates which type of routing is used. This opens a menu that reads *"Route between points"*. Scroll down and click on *"Recalculate Route Without Profiles Changing*".

A new route will appear on the screen after a few seconds -- e.g. because the map has changed or because `routing.xml` is different from the last time the route was computed. Now click on the *"Save"* button on the upper right corner.

### Actual result

The track remains unchanged after saving.

Note that the new route *will* be saved *if you click on a transportation method, such as Cycling*. But if you select  *"Recalculate Route Without Profiles Changing*" then the changes are not saved.

### Expected result

The track should be updated with the new route as it appeared on the screen after *"Recalculate Route Without Profiles Changing*" was clicked.

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: 4.8.6
Android/iOS version: Android 13
Device model: Samsung A71
Crash-Logs: ?
```

**Comment by yuriiurshuliak** [comment]
The bug is reproducible. To reproduce it, follow these steps:

- Import the track [Furkot_Test_Route_-_2.zip](https://github.com/user-attachments/files/17096376/Furkot_Test_Route_-_2.zip).
- Navigate to Menu → Plan a route → Open existing track → Options → Route between points.
- Select Recalculate route without profile changing.
- Then choose a profile, such as car, and wait for the route to be recalculated.
- Save the track.

As a result, after recalculating, the track is updated, but once you save it and review the changes, they won’t appear. Instead, the original track will be displayed without the modifications.

OsmAnd~ 4.9.0#3258m, released: 2024-09-23

https://github.com/user-attachments/assets/3271f00e-38c1-48cb-bcc7-d8b114acf820

**Comment by nazar-kutz** [comment]
It looks like the problem has already been fixed. I can't reproduce it anymore.

**Comment by david-gpu** [comment]
Were you ever able to reproduce it yourself, or only somebody else?

Because I can still reproduce this issue on Android 4.9.4 (2024-11-05) beta.

**Comment by Zirochkabila** [comment]
`OsmAnd~ 5.0.0#3793m, Released: 2024-11-25`
Done
