### ISSUE TITLE
Incremental updates on maps

### ISSUE THREAD

**Issue by davidbaumann** [osmandapp/Osmand#2110]
Hello together,

I think there should be an incremental update on the maps. There are some ways to do this, which should be tested which is more effective, and causes less server load.

I don't really know how the new maps are generated, but there should be something like an update schedule, e.g. update end user offline maps once a week.

- Use rsync to update
+ Maps on the server can just stay as they are, only an rsync server needs to be set up.
+ Update process on the client won't change so much
+ Any update path is possible. The more changes, the more data to be transferred. But never more than a full update
- Will demand CPU load on the server, maybe this is the problem

- Use binary updates
So for update 1 in 2016, there is the file 201601.map. To get your local version 201552 to update, you just need to download and apply 201552201601.diff and you are done.
+ Small updates
+ No CPU server load (only once during creation)
- Needs creation of the incremental update files. But this should be scriptable
- The map will take about 2.5x the space during update (old mal, new map, diff file)

- Use sqlite updates
Also the same like in binary updates, but create update scripts.
- Might break the sqlite file on error.

So any change will have the need to change the client, so I did not list it for the options.

**Comment by xmd5a2** [comment]
It is already in development since end of 2015.

**Comment by davidbaumann** [comment]
Ok, sorry. Didn't find any issue about it.

**Comment by raindropsfromsky** [comment]
I have raised several, but since it is a WIP feature, they were closed.
I hope those issues would be addressed...

**Comment by sonora** [comment]
Yes, work in progress, in deed. The one point which is very justified in the original thread, though, is that I understand the suggestion in a way that we treat the local maps almost like some sort of database, and any delta update to that (however complex the process would be) yields local data which is functionally 100% equivalent to having downloaded the complete map file in one go, i.e. all new data fields are merged, and all outdated data fields are purged. A very justified requirement I also always had in mind when requesting the delta update functionality.

The way I understand we are implementing "OSM Live" now is a little different: Delta upgrades are done by co-existing different local files, like maybe a full download from last month, a one-week delta file, and maybe 2 daily delta files on top. The way I understand it this has some issues, because the files are not really consolidated entirely (in a db merge/purge manner) to form something which is 100% equivalent to the current OSM data (as it would be downloaded in one complete file). I am not even convinced we know completely what the pitfalls are, leave alone we have documented them anywhere. This could potentially mean that OSM Live is a "fringe functionality" useful for e.g. OSM editors, but for people with a focus on routing/navigation using it may have undesired side effects?

**Comment by vshcherb** [comment]
Modifying files directly on the device is it ouf of options. We have quite high percentage of corrupted maps due to several reasons (sdcard corruption and so on). It is not safe to update the file on the mobile, cause it could be easily corrupted.
We combine delta files on the sever, but we always keep possibility to disable Live updates, so in case of troubles, user can rollback to original state.

Implementing files not aware delta is very big, it goes up to 30% of the file, so it is impossible to use for hourly updates, so it is also out of the option.

Current approach is the most difficult, but could bring the best results. Again this is WIP and there are some open issues with it.
