### ISSUE TITLE
Incorrect calculation of uphill & downhill elevation

### ISSUE THREAD

**Issue by Thiodwitnir** [osmandapp/OsmAnd#21105]
### Description

The calculated uphill and downhill elevation sum displayed in track and route details is incomplete/ missing or wrong for some tracks/ routes.

### Steps to reproduce

Navigate from 47.55293N, 11.79729E to 47.54634N, 11.79290E (Guffert Nordwandsteig) with a fresh install using the pedestrian profile:

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/990e830e-b986-4e63-9efb-1966aa4b40b6"  width="300" height="auto"/> </th>
  </tr>
</table>

Alternatively create a straight line track with just the start and end points from above and calculate heights from terrain map (red line in picture above)

Other locations (but not all?!?) provided similar results in my testing - reversing the examples shows incorrect downhill/ elevation loss calculation.
Even recorded GPX tracks show incorrect elevation sums.

### Actual result

The displayed uphill elevation gain is incorrect - the height difference of start and end point alone is more than the calculated elevation gain:

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/27c95ae4-dc19-4e38-9bf6-a1e8bebb1f7c"  width="300" height="auto"/> </th>
  </tr>
</table>

Using just the track with only start and end points, the calculated elevation gain is zero:

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/bec6adf8-fe12-4756-8669-8ca3435dc4d1"  width="300" height="auto"/> </th>
  </tr>
</table>

### Expected result

The elevation gain/ loss should be the sum of all inclines/ declines - and at least as big as the pure height difference.

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: OsmAnd~ 4.8.6
Android version: 15
Device model: Pixel 7a
Crash-Logs: -
```

**Comment by Thiodwitnir** [comment]
Maybe related (and maybe not): the calculated steepness of the route above is „undefined“ for large segments:
![IMG_0021](https://github.com/user-attachments/assets/459a0cc0-6103-4e2c-ad21-695cc1979c11)

**Comment by Thiodwitnir** [comment]
The problem is not, that the route or track does not contain height information - as you can see in the screenshots above, the information is there.
But the calculated uphill elevation sum is incorrect - e.g. according to the screenshot the route starts at 1511m and ends at 2062m but the calculated elevation gain for the route is impossibly 260m and should be at least 551m (if there was no downhill section in the route - which there is).

**Comment by yuriiurshuliak** [comment]
The bug was not reproduced. The elevation gain calculation now correctly displays 550m instead of 260m. However, when using the Plan a Route with the straight-line method, the elevation gain still incorrectly shows as 0m.

This discrepancy might be due to recent updates in the map data, which were regenerated mid-month. We recommend uninstalling and re-downloading the map to see if this resolves the issue.

OsmAnd~ 4.9.0#3603m, released: 2024-10-30

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/6cfb899e-d233-4d4e-b477-12e36b329c7a"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/ba858274-4f61-4190-a812-53d826069e0f"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/d3af08c2-a448-4f1a-9b88-b953445efd01"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by yuriiurshuliak** [comment]
After testing the issue on OsmAnd version 4.8.6, the bug is still present. For the specified route from **47.55293N, 11.79729E** to **47.54634N, 11.79290E** using the **Pedestrian profile**, the calculated uphill elevation gain incorrectly shows **260 meters**, which is less than the expected value of at least **550 meters**.  

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/f3993815-dd26-46bb-af28-8e8734c318d9"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/9ad71ba8-7357-44a4-a839-39648cba4c80"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/c1bbad1b-4ba8-42c0-acb8-c735f5e07d85"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by alex-osm** [comment]
Since the issue is not reproducible in version 4.9.0 - seems it fixed

**Comment by Zirochkabila** [comment]
Bug still present

<table style="width:100%">
  <tr>
    <th>OsmAnd~ 5.0.0#3870m, Released: 2024-12-03</th>
    <th>OsmAnd 4.9.7, released: 2024-11-18</th>
  </tr>
  <tr>
<th><img src="https://github.com/user-attachments/assets/7324e8a2-cc73-4efb-95bf-1a7d60e6567e"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/6f75961c-bdb3-4ad4-95e3-5d8b313d0555"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by vshcherb** [comment]
550 m uphill looks correct https://osmand.net/map/navigate/?start=47.552933,11.797439&end=47.546340,11.792900&profile=pedestrian#17/47.55074/11.79486

**Comment by Zirochkabila** [comment]
My apologies - **DONE**

**Comment by Velomeloman** [comment]
OsmAnd~ 5.1.0#5021m, released: 2025-04-15
Total Uphill/Downhill isn't calculated using roads elevation data

https://github.com/user-attachments/assets/e9fafa37-b217-456d-906f-5dba5b5cd5b3

Calculating by terrain maps is ok

PS: I suppose the use of Ascent/Descent more correct than Uphill/Downhill terms.
