### ISSUE TITLE
name:signed

### ISSUE THREAD

**Issue by gtrus21** [osmandapp/OsmAnd#21111]
### Description

name:signed see as norvegian name

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/7fd53b73-7c02-459a-b949-e767f4462b37"width="300" height="auto"/> </th>
<th><img src="https://github.com/user-attachments/assets/4f7525e9-665d-4cdb-9906-cea310a822d2"width="300" height="auto"/> </th>
  </tr>
</table>

### Steps to reproduce

-

### Actual result

-

### Expected result

-

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version:
Android/iOS version:
Device model:
Crash-Logs: ?
```

**Comment by yuriiurshuliak** [comment]
Please provide a more detailed description of the issue. We need the exact steps to reproduce it, along with the coordinates where the problem occurs.

**Comment by gtrus21** [comment]
56.14349 47.20467
I don't know what exact steps you need. In the tags there is such a record, and in the description of the object this tag is shown as Norwegian

**Comment by gtrus21** [comment]
OsmAnd~ 4.8.6

**Comment by yuriiurshuliak** [comment]
The bug has been reproduced. To reproduce it, go to the coordinates 56.14349, 47.20467, tap on the POI, and view the detailed information.

As a result, the Name is displayed in Norwegian.

This issue is likely connected to the name:signed=no tag, where =no is being interpreted as Norwegian. For reference, see this link: https://wiki.openstreetmap.org/wiki/Tag:name:signed%3Dno


OsmAnd~ 4.9.0#3527m, released: 2024-10-23

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/09bec5f1-4b8d-49a3-851f-de1e6fae8cb3"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/ae6e86c0-5421-4746-a5bd-977a9d52468b"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by Chumva** [comment]
This happens [here](https://github.com/osmandapp/Osmand/blob/48987c95b31230b7ed33df19ce3c83f0a1594815/OsmAnd-java/src/main/java/net/osmand/data/Amenity.java#L246-L247) we need somehow check that it is not language name tag

**Comment by Chumva** [comment]
Probably we need support for translations for this no lang tags with name: prefix

**Comment by dmpr0** [comment]
# Review 

<table style="width:100%">
  <tr>
    <td><img src="https://github.com/user-attachments/assets/b53a10e5-dcbf-4c40-b28a-7734a382b8a3"  width="300" height="auto"/> </td>
  </tr>
</table>   


- [ ] Proper name for info field is missing

**Comment by vshcherb** [comment]
https://github.com/osmandapp/OsmAnd/commit/4154c1b14b2550b3d889f50d817de02146e2a569

**Comment by vshcherb** [comment]
- [ ] Check name:signed shouldn't pass into maps as we never implemented that feature

**Comment by xmd5a2** [comment]
Germany_berlin map was regenerated for testing

**Comment by ivanPyrohivskyi** [comment]
Test with December maps !

**Comment by Zirochkabila** [comment]
Done
`50.097500, 14.418995`

OsmAnd~ 5.0.0#3821m, Released: 2024-11-27
4.9.0.7

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/b035b56d-1d00-4895-baf3-a3077d8b1c7f"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/354416ce-6a0c-4ee7-8d49-7be733466978"  width="1250" height="auto"/> </th>
  </tr>
</table>
