### ISSUE TITLE
Rendering of some areas in relations

### ISSUE THREAD

**Issue by utack** [osmandapp/Osmand#2119]
In this location:
https://www.openstreetmap.org/#map=19/51.06298/13.74700&layers=N
The fountain+park on the left, that are "inner" of a Multipolygon are not rendered, and the park (not in a relation) and fountain (role inner) on the right, are rendered.
Maybe a test case to improve the renderer logic
(or fwiw just map data nonsense, i have not quite understood everything going on here)
![screenshot_2016-01-05-18-19-15](https://cloud.githubusercontent.com/assets/8551234/12122215/eec84476-b3d9-11e5-9ef2-275fd8202fbe.png)

**Comment by xmd5a2** [comment]
This is because of wrong tagging and old maps you use. Until 06.01 outer line of area was tagged as area=yes + highway=pedestrian which is wrong because outer lines of multipolygon shouldn't have area tags.
https://dl.dropboxusercontent.com/u/4624786/osm/Screenshots/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%20%D0%BE%D1%82%202016-01-08%2014.22.21.png
Now this area is rendered as osm.org mapnik does:
https://dl.dropboxusercontent.com/u/4624786/osm/Screenshots/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%20%D0%BE%D1%82%202016-01-08%2014%3A22%3A37.png
New maps (after 06.01.2016) should be ok.

**Comment by utack** [comment]
Ah hell no, I reported this as a possible tagging problem and a very experienced mapper said it was correctly done.
Sorry for reporting this nonsense.
