### ISSUE TITLE
Routes off and on motorway, even if clearly longer and slower

### ISSUE THREAD

**Issue by elgaard** [osmandapp/OsmAnd#21200]
### Routing engine

- [X] OsmAnd's in-app offline routing
- [ ] Any online routing provider (YOURS, openrouteservice, OSRM, etc.)

### Routing Profile

car, fuel efficient.

Can be seen with on the osmand.net/web link

### Start and end points

https://osmand.net/map/navigate/?start=48.509135,7.497118&end=48.459661,7.507782&profile=car&params=car,short_way,#15/48.5001/7.4981

### Actual route

![Screenshot 2024-11-01 at 01-54-40 OsmAnd Map](https://github.com/user-attachments/assets/9dd90d43-6ea4-4899-b405-8c998e560014)

### Expected route

Staying on D500

### Maps you used (online or offline)

- [x ] Offline maps offered within the OsmAnd app for download. 

2024-10-01
- [ ] Online (tile / raster) maps 

### Your Environment

```
OsmAnd Version: 4.8.6
Android version:9
Device model: Samsung S8

```

**Comment by Sonwon1** [comment]
FYI, I've seen similar behavior when importing a GPX track file and then trying to navigate that route.

**Comment by yuriiurshuliak** [comment]
The bug is no longer reproducible on the test web version of OsmAnd. After updating the maps, the route now appears to be built correctly. You can view it here: [test.osmand.net](https://test.osmand.net/map/navigate/?start=48.509140,7.497120&end=48.459660,7.507780&profile=car#15/48.5044/7.4933).

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/038ec521-7867-4f42-8cc6-1550deed2183"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by Sonwon1** [comment]
So I suppose we should assume those bugs are map issues or is there something that could be done with Osmand to recognize the bug and self correct? Maybe the routing algorithm could check between points to see if deviating off the Autobahn (highway) makes sense?

**Comment by vshcherb** [comment]
No longer reproducible
