### ISSUE TITLE
Change position GPX waypoint does not work

### ISSUE THREAD

**Issue by martinstingl** [osmandapp/OsmAnd#21209]
### Description

When the position of a track waypoint is changed, the new position gets lost when the track is saved.

### Steps to reproduce

- Start track recording
- Long Press on map, Actions -> Add track waypoint -> Save
- Actions -> Change marker position, Change Position -> Apply
- Finish track recording

### Actual result

With the last step the waypoint is moved back to its original position

### Expected result

The modified position should be stored in the gpx file.

### Your Environment (required)

```
OsmAnd Version: OsmAnd~ 4.8.6
```

**Comment by yuriiurshuliak** [comment]
The bug was not reproduced. To reproduce, started Trip Recording and recorded a route, adding a track waypoint along the way. Added a marker on the map, clicked on it, and used the Change marker position option to move it.

After finishing the route recording, the track waypoint remained in its original location, and the marker position updated as expected. No issues were observed. Please note that track waypoints and markers are separate functions, so Change marker position only applies to markers, not track waypoints.

OsmAnd~ 5.0.0#3652m, released: 2024-11-05

https://github.com/user-attachments/assets/7ccf7265-4239-46a9-a1ca-e095ad238478

**Comment by martinstingl** [comment]
The error happens to me with version 4.8.6 from f-droid.
Can someone confirm that this has been fixed on the way to version 5.0.0?

**Comment by yuriiurshuliak** [comment]
The bug has been reproduced. To reproduce it:

- Started Trip Recording and recorded a route.  
- Added a track waypoint via **Long press -> Actions -> Add track waypoint -> Save**.  
- Used **Actions -> Change marker position -> Apply** to move the waypoint.  
- Finished the track recording.  

The issue occurs as described: after finishing the Track Recording, the waypoint reverts to its original position instead of retaining the updated location.  

OsmAnd~ 5.0.0#3746m, released: 2024-11-18

https://github.com/user-attachments/assets/91912832-c6d0-49e2-a107-74a73607b88d

**Comment by Zirochkabila** [comment]
`OsmAnd~ 5.0.0#3793m, Released: 2024-11-25`

Done
