### ISSUE TITLE
Start app before AA and connect AA leads to ANR

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/OsmAnd#21259]
Worked 2 out of 3 times
Previous App should be enabled by default (OsmAnd~)
- Start app before AA 
- Connect USB
- Start ./desktop-head-unit --usb
- See to ANR
![telegram-cloud-photo-size-4-5861655354675417328-y](https://github.com/user-attachments/assets/5b37d981-a645-48fe-a6cd-4e1d804856af)

![telegram-cloud-photo-size-4-5861655354675417331-x](https://github.com/user-attachments/assets/9d05c81f-d013-4861-9c38-d6acd5850861)

![telegram-cloud-photo-size-4-5861655354675417329-y](https://github.com/user-attachments/assets/02d23662-8a85-41d6-886d-cbf9ec93bc25)

**Comment by Andrewschenko** [comment]
Can't reproduce it. Could somebody reproduce it? Some other device may be?

**Comment by vshcherb** [comment]
https://github.com/osmandapp/OsmAnd-core/pull/803

**Comment by sjvudp** [comment]
> Can't reproduce it. Could somebody reproduce it? Some other device may be?

I can't reproduce it that way, but just touching a few GUI items caused a similar state (ANR).
The *really annoying* fact is that you cannot recover from the situation via the Android Auto screen, because what ever your choice is, the same popup will appear again until you stop the app in Android (swipe it from the task list).

**Comment by Zirochkabila** [comment]
not reproduce anymore
