### ISSUE TITLE
When you browse map zoom changes with 3D relief is on

### ISSUE THREAD

**Issue by luigifab** [osmandapp/OsmAnd#21250]
### Description

Sometimes (from PL-CZ border, along CZ-SK), the zoom level changes frequently.

### Steps to reproduce

I don't know.

### Actual result

Here is an example: I define a position and a zoom level, then I don't touch anything or I swith off the screen, some minutes after zoom level is not the same.

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/c6e3a625-f73c-4af3-ab7f-3582a4305abf"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/e48e9ab4-3813-45a0-815a-7bba9859438c"  width="300" height="auto"/> </td>
  </tr>
</table>

### Expected result

Don't do that.

### Your Environment (required)

```
OsmAnd Version: 4.8.6
Android version: 11
Device model: wiko
```

**Comment by yuriiurshuliak** [comment]
As I understand it, this is expected behavior. The zoom level in OsmAnd can automatically adjust based on the terrain data settings and your travel distance. Specifically, the zoom may change if the terrain data is toggled on or off, as it dynamically adjusts to provide optimal view levels. Additionally, the zoom adapts to your distance traveled to maintain consistent navigation detail.

You can monitor this using the Camera Elevation widget, which shows the camera's elevation above the surface level. This should help you see how these adjustments are linked to the terrain data and travel distance.

OsmAnd~ 5.0.0#3656m, released: 2024-11-05

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/e0c94694-3a96-4aac-b10a-077916a34488"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/c4db820d-98e6-4802-80a2-40de43017cf6"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by luigifab** [comment]
no it's bad, I got this only from 2 or 3 weeks

if you look at my screenshots, the zoom is updated, I don't know why, and the first screenshot is better than the second one

for around 11,000 km, when I set the zoom level to the level of my first screenshot (for example), the zoom is never updated (from the start of the day to the end), except now for the last 500 km (from screenshot 1 to 2)

where is the 'Camera Elevation widget'?

**Comment by DmitryAlexei** [comment]
The Camera elevation widget can be found in the developer widget section: menu > configure screen > right (or left ...) panel
Please note, that you need to enable the developer plugin first. You may also need zoom level widget to see changes
For more information, see https://osmand.net/docs/user/widgets/info-widgets#developer-widgets

Zoom level can slightly change with 3D relief option enabled when you move the map in mountainous regions, as high objects will be taken into account.

**Comment by vshcherb** [comment]
I also didn't reproduce it, please enable widgets to trace it further

**Comment by luigifab** [comment]
here is an example

![Capture d'écrans_20241107-131556](https://github.com/user-attachments/assets/f42cdf2d-0dbc-46ea-8eff-9842a7a83d2b)

![Capture d'écrans_20241107-131926](https://github.com/user-attachments/assets/4032951f-87df-41de-800c-2d3412dcdb40)

position and zoom defined on screenshot 1
then I switch off the screen
some minutes after I switch on the screen
and zoom is updated

**Comment by vshcherb** [comment]
Yes, in high mountain areas and especially with elevation scale on, zoom calculated dynamically based on the height of the point. As you have my location linked so you see difference shift:
16-0.12=15.88 -> 15+0.54 = 15.54 - So delta is about 0.34 of zoom. 

This feature is important especially for 3D though you use 2D landscape for now so you don't need to have 3D relief on.

**Comment by vshcherb** [comment]
Continuously jumping from 15 +0.56 <-> 16 -0.44 and vice versa seems like a bug cause nothing actually changes

**Comment by Andrewschenko** [comment]
It seems, that this bug is the same as in [#21512](https://github.com/osmandapp/OsmAnd/issues/21512).

**Comment by dmpr0** [comment]
https://github.com/user-attachments/assets/6be982fd-916d-4256-bf46-fcfcdbf2fac2
