### ISSUE TITLE
Route maneuver next turn icon missing

### ISSUE THREAD

**Issue by Davi427** [osmandapp/OsmAnd#21254]
### Description

Sometimes the next turn icon is missing. 

<table style="width:100%">
  <tr>
 <td> <video source src="https://github.com/user-attachments/assets/12145cb1-bfd3-4f2c-8191-cbea83c14ec5"  width="300" height="auto"/>   </td>
 <th><img src="https://github.com/user-attachments/assets/a0fb7489-54d3-4fb2-ba61-ab65a5e03a08"  width="300" height="auto"/> </th>
  </tr>
</table>

As seen in the video the next instruction will be shown.

### Steps to reproduce

I am not sure how to make it happen. It has happened several times but I don't know what was the same in these scenarios 

### Actual result

Route maneuver icon not shown

### Expected result

Route maneuver icon shown.

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version:OsmAnd+ 4.9.2, Released: 2024-10-25
Android/iOS version:14
Device model:FP5
Crash-Logs: ?
```

**Comment by yuriiurshuliak** [comment]
The bug was not reproduced. I tried to build a navigation route from Tartu to Jonvi and monitored the next turn widget throughout the route.

As a result, the next turn icon did not disappear or become invisible; the next turn widget functioned correctly at all times.
Please try testing this on the nightly version to see if it resolves the issue for you: [Nightly Builds](https://osmand.net/docs/versions/nightly_versions#nightly-builds).

OsmAnd~ 5.0.0#3656m, released: 2024-11-05

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/46c10b7a-a450-4dbf-bac2-b8783120b1cd"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/b5f2b70c-50e4-491f-a67e-03c84098d66a"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by Davi427** [comment]
Yeah I don't think it is specific to the route, since it happened on two different routes. I am currently not able to use the nightly, I have not seen the error in OsmAnd+ 4.9.3, Released: 2024-11-01 today.

**Comment by vshcherb** [comment]
Let's reopen once it happens again in 4.9. There was issue fixed with incompatible turn output to UI
