### ISSUE TITLE
The "direction" arrowheads in the search results do not turn to point at the POIs

### ISSUE THREAD

**Issue by raindropsfromsky** [osmandapp/Osmand#2130]
When we search for any type of POI (e.g. Finance), OsmAnd shows the search results.
The second line of each result has an orange arrowhead that points to the POI.

If we rotate the device,  the arrowhead is supposed to rotate automatically, to keep pointing at the POI.

But this does not happen in 2.3.0#15167M (and also in last few releases).
The arrows do not point at the correct direction in the first place, and are permanently frozen.

**Comment by sonora** [comment]
Tried to reproduce and get a mixed picture here (disabling Kaiman filter in General settings helps  by displaying more instantaneously):

Looks like it works ok on the Search/POI screen and the Dashboard, but fails on the Search/History and the Search/Favorites screen, right?

**Comment by sonora** [comment]
To be more precise:
(1) On the Search/History and Search/Favorites screen, all arrows statically point "Up", always, so this is a bug (and not a recent one, it seems).
(2) On the Dasboard, the blue arrows work ok (vs. "My Position"of course) when you have a location fix. When not, arrows appear orange, and are vs. the map center and relative to how the map is shown (turn the map with 2 fingers to verify if yours is set to "North is up") , so no bug here, right?
(3) I also notice initial directions are ok (2), but there is no live update for orange Dashboard icons if map is set to "to compass", although map visibly rotates behind the dasboard whe you rotate the device. Could be considered a bug, but probably without much harm in practical use?

**Comment by raindropsfromsky** [comment]
The Kalman filter is already turned off on my phone.

I can confirm all your three observations, but the bug I reported is additional. 

(1) I do not use the History+Favorites screens, so has not noticed the behavior on these screens. But yes, this is a bug.. 

I also agree that bug in (3) can be ignored.

But the bug I mentioned is on search screen itself, and all arrows are locked even when the screen is centered around the current location.

OsmAnd shows the arrows in different direction, depending on the map-orientation mode: "North up" and "Compass". But both these directions are WRONG vis-a-vis the actual direction in which these POIs lie.

**Comment by sonora** [comment]
Strange, that I cannot reproduce. On the Search/POI screen (once it is displaying results) all arrows are updated correctly in real time.

Please try finding the exact circumstances to reproduce, maybe also check another device to aid that? Can you pinpoint a build when you think it started? (No change to that code in a long time, I think).

**Comment by raindropsfromsky** [comment]
In my earlier post, I was inside my house, and failed to see that my GPS fix was incorrect. As a result, the arrows were pointing in wrong direction. But this time I went to my balcony to get a very accurate fix.

I am attaching screenshots of the bugs.

In the map, I am at the Favorite marked in gold star called "Home" (the GPS fix is very accurate). I am trying to see the bearing of a known POI, a petrol pump marked with red star.

I repeated the experiment in different conditions, and found this:
1. In the ***Compass*** mode, if the map is centered around the current location, then the initial bearing is correct.
2. In the ***Compass*** mode, if the map is NOT centered around the current location, then the initial bearing is wrong.f the 
3. In the ***North Up*** mode, if the map is centered around the current location, then the initial bearing is wrong by x degrees, where x is the bearing of the device from North. In other words, if the device points to North, the arrows will show correct direction, otherwise not.

[POI Arrow.pdf](https://github.com/osmandapp/Osmand/files/84086/POI.Arrow.pdf)

**Comment by raindropsfromsky** [comment]
New observation:
If I select any of the search-results, OsmAnd pops up a card for that spot.
In this, the direction+distance arrowhead is blue. OsmAnd live-updates this arrowhead.

Not only that, it seems to be pointing correctly to the physical POI, regardless of map's orientation (***North up*** or ***Compass***).

Now this last is only HALF good, because just the arrowhead shows the direction and distance accurately; but the map does NOT!

**Comment by sonora** [comment]
Narayan, Please note that for the POI search results screen
- when the map is centered at your location, all arrows point at the POI (i.e. where POIs are in the real world)
- When the map center is arbitrary, the arrows point at where the POI is located relative to the (fictitious) map center. 

So, looking at your PDF:
- Case1 seems 100% ok,
- Case 3 also is also 100% correct;  You selected "North is up" for the map. Obviously you pointed the device so that it looks ENE, while the gas station is located SE, so the arrow pointing some 80 degrees right from your viewing direction should point right at the gas station
Case 4: Looks like an issue there. You were looking straight south when you took the map screenshot. Gas station is SE, so arrow should be pointing some 45degrees left. But you reported that on your device, which I cannot reproduce on any of mine, you see no live updates for the arrows. So did you tilt the device between the 2 screenshots, that would explain it?
Case 2: Also slightly off, but not much. Was the device tilted between the 2 screenshots? (Please note that here the arrow should point as if you device was located at the map center.)

Again, I simulated all your cases on some of my devices, and here everything looks as expected ...so I really have an issue reproducing what you report, other than the "live update issues" I listed above.

Please play with portrait vs. landscape orientation, General setting "screen orientation", etc. and calibrate your magnetic sensor, then check if you can systematically reproduce anything. From the 4 screenshots you produce I do not understand why 2 are 100% correct and 2 are not? You need to find out when you produce ok vs. false results.

PS: Blue data on the context menu is always relative to "My Position", regardless of how the map is centered. that's the reason for the blue print.

**Comment by raindropsfromsky** [comment]
Yes, prior to the experiment, I took care of those factors: 

I tried both ***landscape*** and ***portrait*** modes, by holding the phone appropriately. 
(The general setting is "same as device").

Before the experiment, I calibrated my magnetic sensor by turning my phone through a figure of 8 movement. (The map is perfectly aligned with the street in front.)

I had held the phone in my hand during the entire experiment, so it might have turned it a bit when I took the screenshots. But then my main bug is that the arrows do NOT auto-update when I change the bearing of my phone! So we can rule out the possibility that the arrows turned due to my movement.

I will repeat the experiment by holding the phone steady.

But all said and done, these factors are to enhance accuracy. My main problem is that the arrows do not turn at all. (Similar to the case when the ***Accessibility*** plugin caused the same issue.)

BTW I just noticed that for any given POI, the angle of arrow changes by 90 degree when I flip between  ***landscape*** and ***portrait*** modes.

**Comment by sonora** [comment]
Summary:

(1) I think we should concentrate for now on why your device does not auto-update on the Search POI/Results screen, which I cannot reproduce on any of my devices.

(2) I can, however, reproduce that no auto-update happens on the Search/Histpry and Search/Favorites screens.

(3) Remaining Issues may be loosely related to the device-specific Issue #2131, just to mention this cross-link here.

**Comment by raindropsfromsky** [comment]
Well, 1 and 2 are OK. But regarding 3, I carried out some careful experiments, and found that when I flip the device (landscape-portrait), it changes the direction of only some POIs randomly.  
 * Some POIs are not affected at all.
 * Different POIs experience different shifts in angle

This is so weird that I repeated the experiment for two different locations of the city.

Location-1:
![randomchangeportraitlandscape-2](https://cloud.githubusercontent.com/assets/9047168/12318301/50bfdbe4-babf-11e5-9a4c-35b76bbbbc84.png)

Location-2:
![randomchangeportraitlandscape-1](https://cloud.githubusercontent.com/assets/9047168/12318312/61406d12-babf-11e5-85a3-df4dd88c0fd4.png)

In both experiments, I kept the plane of my screen vertical (never tilted), and kept the bearing constant while I flipped between portrait and landscape modes.

**Comment by vshcherb** [comment]
(1) Is not a bug it is a conscious decision. Arrow also distance indicator not only direction. We try to not use compass on all possible screens without necessity - bad for accessibility and bad for battery
(2) We display direction only if you search POI around your location, around other location displaying arrows doesn't make much sense. It is contrintuitive and only confusing. 

Not sure I understand everything but this issue does not make much sense to me, cause I don't see any important reproducible issue.

**Comment by sonora** [comment]
I guess to prevent users raising further issues like this, maybe we should hide the direction arrows on the screens where we explicitly chose to not update them , i.e. on the Search/Histpry and Search/Favorites screens. (Instead of showing them statically and not updating them, i.e. they are useless or it is not obvious what they mean to say.).
