### ISSUE TITLE
Compass 90 degrees off on Samsung Galaxy Camera 2

### ISSUE THREAD

**Issue by CJTmmr** [osmandapp/Osmand#2131]
Hi,

My device is a Samsung Galaxy Camera 2 (EK-GC200, Android 4.3)
With "Map-orientation=To compass" the map is always displayed 90 degrees off.
The North on the map is always heading to the East.
I have calibrated many times - that makes no difference.

In car-navigation I mostly use "Map-orientation=to direction of movement", so that's no problem.
But wih hiking and exploring the 90 degrees off is really annoying.

Are there more devices with the same problem?

To be honest: a lot of the G-Playstore Compass Apps have the same problem.
Like "GPS-Status&Toolbox" 
and "AR Bearing+Baseplate Compass" from Appyhand
and "inViu GPS-details"
I raised issues there, but no reaction from those devs.

But some other Compass-apps are working real fine.
Like "3D Compass and Magnetometer" from Plaincode.
and "Compass & Spirit Level" from Crunchy ByteBox

I suppose it has something to do with landscape being the default screen orientation on startup of the Galaxy Camera.

Cheers
Kees-Jan

**Comment by sonora** [comment]
Needs more investigation. From what I see we have used this code http://stackoverflow.com/questions/18162642/how-do-i-get-the-correct-bearing-magnetic-orientation-regardless-of-screen-ori/18170142#18170142 for a long time now, and yours seems to be the very first device reported where this fails...

Chances are your device is not or differently reporting its "natural" screen orientation, and the code is using a wrong fallback. Victor, would you know how to debug this without actually having such a device? I see we create a log entry for the fallback case?

**Comment by sonora** [comment]
PS: I notice tis is not a "flat" device but a camera, so its "natural" positioning in use is with the display perpendicular to the ground. This potentially makes the difference of how the device reports its natural screen orientation (maybe 3D-like). I assume you observe the issue regardless of how you hold the device (parallel to the ground or upright)?

**Comment by CJTmmr** [comment]
Hi,

The error is the same with app in landscape- and in portrait-mode.

When the camera is lying flat (screen parallel to the ground, pounting up) the error is about 
75-80 degrees. 

When I lift the top slowly up, to change position to perpendicular, the map also turns a bit, and in upright position the error is about 100-110 degrees.

When I lift the left side up a bit (20-30 degrees) , the map also turns like 20-30 degrees..
Normally I would expect the map not to turn.

One should make a video of the map-turning-behavoir to understand well what happens... but I think this is not so easy for me to do...

I experience the same behavior with other compass-apps (GPS-Status, AR, inViu): they probably use the same method to read compass bearing.

In "3D Compass and Magnetometer" from Plaincode the 3D-compass-arrow is always pointing North - is every tilted position of the camera or even upside down. They found a way to read the compass-bearing correctly.
I suppose however there code is not open-source..

Maybe this info can help you to debug.

Thanks

Kees-Jan

**Comment by CJTmmr** [comment]
Edit:  third line should be:

In  landscape mode, When I lift the top slowly up, to change position to perpendicular, the map also turns about 180 degrees, and in upright position the error is about minus 90 degrees.! 
 
Tilting a few degrees in this position makes the map turn like mad, 180 degrees left and right

**Comment by sonora** [comment]
Just for reference, here is the "normal behavior" (I observe on all devices I have) for 2D compass implementations: (i.e. compass apps, which are supposed to display magnetic North on the Earth's 2D surface)

(1) Device held flat, display pointing up: Compass disk displays like the "real world" directions, i.e. "North" indicator points north, south indicator points south, etc.

(2) Device is held perpendicular to the ground, i.e. display points parallel to the ground: The compass on the device displays the direction you point the device to (i.e. the direction the back camera points to). In other words: If you point the device east (display now faces west), compass would display "East" (the compass disk now would show "East" in the 12:00 o'clock position).

(3) Now the interesting part: Hold the device overhead, so that the display faces downwards. The device does now not "know" if your are "looking" east, west, north or south, and the compass would rotate depending on the slightest tilts of the device in any of these directions.

(Our code in OsmAnd, on all devices I have tested so far, behaves exactly like this, too.)

I think (3) is the "instability" you observe in your Edit to your post ("map turns like mad").

Now we have to research how exactly your device "behaves" for cases (1)-(3). From what you write, it sounds to me like you observe the "overhead instability" actually when the device is held perpendicular to the ground, not overhead (?), which seems to indicate that on your device the x/y/z axes are somehow assigned differently, and hence the 2D projection of compass apps creates a systematic rotation error by 90 degrees (while 3D apps have no issue).

In other words: I have a hunch, your device behaves as follows: Place your camera on the table such that the display faces perpendicular to the table (like you would normally hold a camera). Now put an (imaginary) smartphone flat on the top of the camera (display facing down, towards the table. ) I think the coordinate system your device seems to use (and report to app code) is that of the smart phone display (!), while what you observe is of course what is on your camera display (facing perpendicular to the table surface) - can you confirm?

It only remains to be determined if the smart phone's long or short edge needs to be aligned with the camera's width (this is your 90 degree error), then we would know the transformation how your device reports its position vs. all other devices - and what correction any app code would need. I am not sure if what your device does is on purpose or an oversight of the manufacturer - Looks like it simply behaves like a device where the display is not on its top (phone, tablet), but on its side (camera :-). Most apps do not allow for that somehow - or your device does not report this in the expected fashion Not sure yet what to do about it. .

**Comment by CJTmmr** [comment]
Hello Hardy,

Many thanks for your reply.
I think I can confirm what you say.
Somehow the X-Y-Z axis are mixed-up, but how exactly...
I could try and contact Samsung, but a fear we will not get a quick response....

I was able to make some videos of the "turning map"...
To be sure:   Kalman-filter is ON; In OsmAnd Development Plugin: Use magnetic mensor is ON
(btw With Orientation sensor ON the behavoir is slightly different, but still comparable)
All in landscape-orientation of the app. (in portriat behavior is different but still awkward)

First Video: https://www.dropbox.com/s/hbnhfhzq038huv4/DSCI0425.AVI?dl=0 (you can simply skip the Dropbox login)
The camera-screen is perpendicular to the table, looking to the North, like taking a picture.
I am slowly tilting the camera forward en backward, and you can see the map turning.

Second Video: https://www.dropbox.com/s/memlqoyg40iqpkc/DSCI0426.AVI?dl=0
The camera-screen is perpendicular to the table, looking to the North, like taking a picture.
I am slowly turning the camera, parallel to the screen.
The map turns in very different directions...

Third Video:https://www.dropbox.com/s/eo069am91ym11gc/DSCI0429.AVI?dl=0
The camera is lying flat on the table, top to the actual North.
The Map-North is pointing to the East.
I am slowly lifting the camera on the left side, and later on the right side.
Map is turning again.

I hope this makes thing a bit more understandable.. (a video says more than a thousand words)

I made two more videos from the Magnetmeter-app from Plaincode:
Forth Video: https://www.dropbox.com/s/m4qnufv4cw63m4u/DSCI0430.AVI?dl=0
The camera-screen is perpendicular to the table, just about looking to the North, like taking a picture.
Tilting and turning camera: the North stays North.

Fith Video: https://www.dropbox.com/s/jmb7m4x5c2ijipj/DSCI0431.AVI?dl=0
The camera is lying flat on the table, top to the actual North.
Lifting the camera in different direction: the North keep point to the North.

If you could think of a fix, it would make me very happy.

Cheers,
Kees-Jan

**Comment by sonora** [comment]
Thanks for your movies, yes, they depict what is going on and seem to confirm that somehow the coordinate system reported on your device is different from the other devices I have access to.

One thing that bugs me: On the movies you took of OsmAnd, the Android notification bar (the one created by the Android OS, with all the system icons like WiFi or battery status) is displayed along the top (long) edge of the screen, while in the movies taken of the 3D compass app it shows along the left (short) edge of your display.

Could I please ask you to play with
- the OsmAnd setting "General settings / Screen orientation"
- the Android setting "Display / Auto rotate screen"
and check out if some configurations of these make a difference (particularly the ones where you disable the Android auto-rotate sensor, and set OsmAnd to a fixed portrait/landscape mode?

**Comment by CJTmmr** [comment]
I have played with Screen Orientation.
The behavior of the map stays the same;
Both in locked landscape and locked portrait-mode; Both with settings from Android (Screen rotation On/Off) as from OsmAnd 
With camera-screen flat: map is about 90 degrees off, but a small tilt makes the map turn like on the movies.

The 3D Magnetmeter-app is always in portrait-mode; it does not change screen-orientation at all.
(as several other apps do ... e.g. WordFeud, Speedtest (Ookla) etc..)

**Comment by sonora** [comment]
Victor, since you assigned me: I think we have pretty much researched what is going on here. And the only fix I can think of for now is an 'ugly' one: We could introduce a new Setting (working tilte "Upright device"), which, when checked. 3D-rotates the device's coordinate system such that it allows for how the Samsung camera reports its x-y-z axes.

If this is the only device reporting x-y-z like this, or if the device mistakenly reports x-y-z like this, the new setting would probably confuse more users than help anybody. But if this is the standard coordinate system for these (and future similar) devices with the "display on their side", we could introduce the setting (and possibly even research if this condition could be "auto-detected"). It will take  more research, I will leave this open but cannot promise a quick result.

**Comment by vshcherb** [comment]
I would say we need to track and get more information about devices. So far it seems more confusing than winning, we never were in the compass business and Android Platform allows you to use a separate application compass, it is quite sad but that's a workaround

**Comment by CJTmmr** [comment]
I suppose, if the new Setting for "Landscape Device" is in Development Plugin, it would not bother other users so much.

If I can help with more tests - please let me know.

Kees-Jan

**Comment by sonora** [comment]
Yes, I guess I could take some time looking into creating the correct 3D transformation in the code for such a setting. But since you are familiar with the Development plugin: I suppose you have tried the setting "Use magnetic sensor", and it makes no difference?

**Comment by CJTmmr** [comment]
I have tried both "Use magnetic sensor" and 'Use orientation sensor". The turning of the map is the same.
I have digged deeper in sensors and android;

From [android.com](http://developer.android.com/reference/android/hardware/SensorEvent.html) I learned that my Samsung Galaxy Camera 2 indeed has landscape as default orientation.

Holding the device like taking a picture:
The X-axis is horizontal - along the long side, pointing to the right; the Y-axis is upright to the sky; the Z-axis is pointing out of the screen.

I checked this with various "sensor"-apps ( Sensor Kinetics and Sensors Multitool)
The values from the Accelaration-sensor are OK:
Holding the device like taking a picture: The Y-value is about -9.90 m/s2 as expected; both X and Z-values are about zero. Tilting the camera backward and forward (turning around the X-axis) the Y and Z values change; the X-values stay about 0;
With the screen flat (like a tablet on a table): Z-value is 9.9.m/s2 and X-and Y-values about 0;
Other orientations also give the right values as expected.

The values from the Magnetic-sensor are behaving strang....
(As I am inside a building with steel construction the local magnetic field will not be to the north; but for this test, this is not important I think.)

I am turning the camera in different positions until the X-value is about zero.
This should mean the Magnetic field is pointing in the Y-Z-face
Then turning the camera around the X-axis, I would expect the X-value staying about zero; with Y and Z values changing from -43uT to + 43uT

BUT: Turning the camera around the X-axis: the Y-values stays the same, with X and Z values changing from 0 to +/- 43uT...

Apparently the Magnetic-sensor uses different X and Y-axes than the Accelaration-sensor..
Or... maybe the Magnetic Sensor was mounted on the chip in wrong direction?
X for Acc == Y for Magn   and   Y for Acc == -X for Magn ??
Curious to know about other people with a Camera 2 (but I know none...)

This definitely explaines the OsmAnd-map-turning.

I wil try to explain this issue to Samsung Support; maybe they can give a solution (update for BIOS??) - 

Kees-Jan

**Comment by sonora** [comment]
Thanks for specifying this so diligently. It seem to precisely explain what is going on.

I am more than ever leaning towards this being a device issue specific to the Samsung Camera, actually, so yes, please try explaining this to Samsung's support first. Unless  they can convince you this is by design and can explain why this would make sense, I think we should back off from making the appropriate axes-correction (setting) in the OsmAnd code.

BTW: This issue is not really related to the default orientation of any device being landscape or not, OsmAnd deals with many landscape devices correctly (many tablets are landscape by default). Your issue seems rather related to the screen on your device being "mounted on its side", AND (I think) the internal axis assigned being somehow faulty or inconsistent, just like you describe.

**Comment by CJTmmr** [comment]
The answer from Samsung came this afternoon:
"Please send the Camera to our TechRepair-partner - they can probably fix/repair this..."

I'm not sure I will do that.

Thanks for your time..

Kees-Jan

**Comment by CJTmmr** [comment]
Just to let you know, if you are interested:

I forked OsmAnd-app, and finally succeeded in building OsmAnd on Windows 10 in Android Studio; running it through ADB on my Galaxy Camera.

Addes three line of code in `OsmAndLocationProvider.java` that swaps X and Y values (X:=-Y; Y:=X)
in method: `public void onSensorChanged(SensorEvent event)`
after:
`case Sensor.TYPE_MAGNETIC_FIELD:`
`System.arraycopy(event.values, 0, mGeoMags, 0, 3);`
I added:
`float mTemp = mGeoMags[0];`
`mGeoMags[0] = -mGeoMags[1];`
`mGeoMags[1] = mTemp;`

and now in compass-mode the map is okay and stable!!

I now have "my own" OsmAnd-version....
It is just that the core-native-code is not working now - rendering and routing are much slower.
Probably because I build on Windows?

Is there a possibility to detect my device (EK-GC200) and only than performed X-Y swap?
Then maybe I could try and make pull request - do I make a chance?

**Comment by vshcherb** [comment]
Let's wait when @sonora  is back and probably he could update us how to make fix compatible with other devices

**Comment by sonora** [comment]
Still today, I have not yet heard of any other device or user who would need this. But I am glad that all our research finally bore some fruit and you got it to work!

Victor, as I probably already sated somewhere in this thread further up, what I think we could do is
- Introduce a new Setting in the Development Plugin
- call it something like "Handle magnetic sensor for Landscape Devices (like some cameras)"
- and, if selected, apply the transformation we have established this device needs (exactly like described to comments up)

If you want that done, I think it is a very easy task for one of our programmers.

Best, Hardy

**Comment by CJTmmr** [comment]
I really think it is a bug from Samsung - which they will not fix in short time (if ever....)

I made a check for build.MODEL:
see [commits](https://github.com/osmandapp/Osmand/compare/master...CJTmmr:master) on my fork of OsmAnd.
This workes for me, and will not bother any other device (I think.....)
I can not see any changes in rendering speed.

You would need commits:
from Mar 02: d14f0ae
from Mar 04: f7afa3e
from Mar 07: c3d7938

I was not familiar with Git, Pull and Push etc., so I meshed up all the other commits a bit I think
I don't know how to create the right Pull Request.

Thanks
Kees-Jan

**Comment by duanester** [comment]
i did not read carefully, but i see most of the same problems with my zte maven(Qualcomm Snapdragon 210 MSM8909). it really freaks me out when the 3d compass app works perfect then i open osmand and it off like 50 to 80 degrees. i did notice something weird the other day on the bus while changing only the elevation by about 1 foot upward while on the bus. osmand corrected to be somewhat more correct, at least in the right direction but still off by 20 degree. my theory is that when i use my open camera app that it messes up the calibration, for osmand, but again, not the 3d compass app. if that is the case, is there an app that can turn off the compass while i use that app.

**Comment by sonora** [comment]
I assume the solutipn I suggested which fixed #3926 does not work here, have you tried?
