### ISSUE TITLE
Predefined filters are empty while editing Smart Folder

### ISSUE THREAD

**Issue by Nine-Tailed** [osmandapp/OsmAnd#21331]
### Describe the idea

When selecting the menu item change smart folder filter it has to be configured from the very beginning. It would be more correct to set the values ​​in the filter that were set earlier.

There is also a need for the filter items "No waypoints" and "Number of segments".
"No waypoints" add to "Other" section, next to "With waypoints".

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/e04bcb84-8b03-43ce-8ca3-23785da5b152"  width="300" height="auto"/> </td>
  </tr>
</table>

### Expected behaviour

.

### Alternatives you've considered

.

**Comment by DmitryAlexei** [comment]
### Steps to reproduce
- (preconditions) I've created a smart folder filtered by "date of creation" and "visible on map". There were 4 tracks (out of 95) in that smart folder. 5 tracks are visible on the map and one of them is filtered by date of creation
-  tap tree dots in the smart folder cell > edit filter > and see if the filters values are set

### Actual result 
- It is clearly seen that there are 4 tracks in the smart folder 
- the filter by "date of creation" is not set 
- otherwise "visible on map" filter shows 5 tracks 

https://github.com/user-attachments/assets/738ab6dc-831e-4b81-897d-b3299b489914


OsmAnd also doesn't have filters "No waypoints" and "Number of segments" can also be useful for some users (probably another task is needed).  

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/aa690984-a3c8-49b1-a61b-01edf8e90a46"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by Nine-Tailed** [comment]
Will adding new parameters be implemented or should a separate issue be created?
