### ISSUE TITLE
Compass showing wrong north

### ISSUE THREAD

**Issue by Davi427** [osmandapp/OsmAnd#21355]
### Description

After backgrounding and foregrounding Osmand, the compass is pointing north but the map is not.

### Steps to reproduce

Have compass set to movement direction
Background osmand
Return to osmand

### Actual result

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/b2883c9e-8a63-4b8d-aecb-0811a8e0fbf4"  width="300" height="auto"/> </th>
  </tr>
</table>  

Compass points north but the map does not. As you know Kyiv is not to the northeast of Warszawa.

### Expected result

Compass and map are congruent. 

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version:OsmAnd+ 4.9.5, Released: 2024-11-12
Android/iOS version:14
Device model:FP5
Crash-Logs: ?
```

**Comment by Davi427** [comment]
https://github.com/user-attachments/assets/2eb4225f-a0c8-453f-9fd2-56899ab96e56

**Comment by Davi427** [comment]
https://github.com/user-attachments/assets/7d4d7b2c-e11f-4176-971f-bd79b188ba75

Here you see the map can be dragged and when rotated the compass direction is corrected.

**Comment by yuriiurshuliak** [comment]
The bug has been reproduced. To reproduce it, try the following steps:

- Set the compass mode to "movement direction."
- Rotate the map so that the compass points to the East.
- Run a navigation simulation.
- Move the app to the background several times and reopen it.

As a result, you will notice that the compass points North, but the map orientation remains to the East.

OsmAnd~ 5.0.0#3746m, released: 2024-11-18

<table style="width:100%">
  </tr>
  <tr>
    <td> <video source src="https://github.com/user-attachments/assets/ff9d97dc-427e-4394-a6f1-f110b4c71d61"  width="300" height="auto"/>   </td>
    <td><video source src="https://github.com/user-attachments/assets/35208e97-2cda-450d-8bfc-e5db72dc2097"  width="300" height="auto"/>   </td>
  </tr>
</table>

**Comment by alex-osm** [comment]
https://github.com/osmandapp/OsmAnd/commit/71dd64edc161e7989431d1eaa400b787a3507e0c
