### ISSUE TITLE
Track: Change activity fails

### ISSUE THREAD

**Issue by outdoorbits** [osmandapp/OsmAnd#21381]
### Description

In Tracks - Selection Mode - Change activity I could change the activity in the first try only. Activating the track I cloud see the activity type in the track settings.
Any further try to change activity for this or another track failed without a message, activity is always empty now.

### Steps to reproduce

Menu - My Places - TRACKS - press one track until selection mode is activated - Change activitiy - select one.
Click on this track, the activity is shown correctly in the overview at the bottom.

Repeating the same on the same or another track causes a empty activity setting.
After closing and restarting OsmAnd, it works again one time.

### Actual result

I can do one activity change and have to restart OsmAnd for the next one.

### Expected result

Allow more than one change and allow change on multi select.

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: OsmAnd+ 4.9.6
Android/iOS version: 15 AP3A.240617.008
Device model: Xiaomi 13T Pro 23078PND5G
Crash-Logs: ?
```

**Comment by yuriiurshuliak** [comment]
The bug was not reproduced. Here’s what we observed during testing:  
1. Opened **Menu → My Places → Tracks** and selected a track.  
2. Accessed the context menu for the track, chose **Change activity**, and selected a different activity.  
3. Verified on the map that the activity was successfully updated.  
4. Repeated the same process for the same track and observed that the activity consistently updated to the selected one.  
5. Selected different tracks and changed their activities successfully multiple times.  

In all cases, the activity was updated as expected without any need to restart the app. Please try the latest nightly version of OsmAnd; the issue might already be fixed: [OsmAnd Nightly Builds](https://osmand.net/docs/versions/nightly_versions#nightly-builds).

OsmAnd~ 5.0.0#3785m, released: 2024-11-22

<table style="width:100%">
  </tr>
  <tr>
    <td> <video source src="https://github.com/user-attachments/assets/05a40137-bda8-4892-82d2-0804363cbf92"  width="300" height="auto"/>   </td>
    <td><video source src="https://github.com/user-attachments/assets/ce4de126-681f-4275-9537-10ff0945697c"  width="300" height="auto"/>   </td>
  </tr>
</table>
