### ISSUE TITLE
Navigate button icon shows wrong profile

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd#21454]
### Description

If adding a Quick action, the button icon is displayed with the profile that was used previously

### Steps to reproduce

1. Walking profile > Menu > Configure screen > Custom buttons > Quick action > Enabled > Add action > Navigation > Navigation > Apply > go to the main screen

2. Car profile > Menu > Configure screen > Custom buttons > Quick action > Enabled > Add action > Navigation > Navigation > Apply > go to the main screen

### Actual result

https://github.com/user-attachments/assets/f88dc65b-ac97-4207-bdcb-cb409c47c219

### Expected result

Quick action button icon is displayed like at the current profile

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version:OsmAnd~ 5.0.0#3806m, Released: 2024-11-26
Android/iOS version: Android 14
Device model:
Crash-Logs: ?
```

**Comment by yuriiurshuliak** [comment]
To reproduce the issue:
1. Add a Quick Action button for **Start/Stop Navigation** while using the **Pedestrian profile**. Return to the main screen and observe the icon.
2. Switch to the **Car profile**, go to the Configure screen, and enable the same Quick Action button. Return to the main screen and observe the Quick Action button icon.

**Observed Behavior:**
In my case, the pedestrian icon is not displayed in any profile. Instead, the button consistently shows the **planet icon (Browse map)** for the **Start/Stop Navigation** action across all profiles. 

**Expected Behavior:**
The correct icon (a **Navigation Arrow**, as seen in your first screenshot) should be displayed according to the current profile.

Let me know if there are any additional scenarios you'd like me to verify!

OsmAnd~ 5.0.0#3840m, released: 2024-11-29

<table style="width:100%">
  <tr>
   <th><img src="https://github.com/user-attachments/assets/ee9cb10a-b085-4792-91c9-63c1a91ff124"  width="300" height="auto"/> </th>
<th><img src="https://github.com/user-attachments/assets/efcd3a9c-c9e8-4915-8a93-eaa67ed51e0c"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/03c62ff1-c4fb-4393-bf96-3c18d856b4dd"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by Zirochkabila** [comment]
# Testing 1
`OsmAnd~ 5.0.0#3954m, Released: 2024-12-18` - Main issue is **Fixed**

But, should the icon change when you open the custom button to the icon of the profile with which the route was created (no navigation was performed, only the route was made), or should leave the default “Car” icon remain as when you click on the “Navigation” button?


https://github.com/user-attachments/assets/8068707f-cc41-4911-bc20-70f20c2e0ea5
