### ISSUE TITLE
Units & Formats categories do not change in custom profiles

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd#21474]
### Description

If changed **Driving region**, the data in the **Unit of speed**, **Unit of volume** categories do not change. 
Provided that a custom profile is activated (any profile that has been changed)

A complete reset of the profile settings does not help

**Only a complete (clean - without data) reinstallation of OsmAnd helps.**

### Steps to reproduce

Menu > Settings > Select Driving profile > General settings > Driving region

### Actual result

After a complete reset of the profile settings or without them, the result is the same

<table style="width:100%">
  <tr>
    <th></th>
    <th></th>
  </tr>
  <tr>
    <td><video source src="https://github.com/user-attachments/assets/63d7be7f-ac3b-45c8-b73f-451df9eee95c"  width="300" height="auto"/></td>
<th><img src="https://github.com/user-attachments/assets/4ed1aaa4-0bc7-4896-8512-ce9e5732b2ef"  width="300" height="auto"/> </th>
  </tr>
</table> 

### Expected result

After a full reinstallation

https://github.com/user-attachments/assets/2ee03635-4a21-4530-aa2e-6aa13e0c79e0

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: OsmAnd~ 5.0.0#3834m, Released: 2024-11-28
Android/iOS version: Android 14
Device model:
Crash-Logs: ?
```

**Comment by yuriiurshuliak** [comment]
The bug has been reproduced. Here are the steps used to reproduce it:  
1. Select a car profile where **Europe** is set as the Driving Region by default.  
2. Navigate to **Menu > Settings > Select Driving profile > General settings > Driving region**.  
3. Change the Driving Region from **Europe** to **USA**.  

**Observed Result:**  
The **Units of speed** and **Units of volume** categories in the profile settings remain unchanged, still reflecting European units (e.g., kilometers per hour and liters), instead of switching to USA units (e.g., miles per hour and gallons).  

OsmAnd~ 5.0.0#3859m, released: 2024-12-02

https://github.com/user-attachments/assets/37d10867-47d4-437e-858d-6c16dbc3793a
