### ISSUE TITLE
“Configure map” and “Search” buttons are displayed on top of the widgets

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd#21483]
### Description

After launching the navigation, the “Configure map” and “Search” buttons move to the top of the screen and are displayed on top of the widgets

### Steps to reproduce

1. Make sure you have all the widgets activated and added as shown in the screenshot
2. Start the navigation

### Actual result

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/f365a37d-2d27-4ede-89b3-129c3640ba1f"  width="300" height="auto"/> </th>
  </tr>
</table>  

### Expected result

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/2eb94e5c-fe95-4111-b527-79018a2efdf8"  width="300" height="auto"/> </th>
  </tr>
</table>  

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version:
Android/iOS version:
Device model:
Crash-Logs: ?
```

**Comment by yuriiurshuliak** [comment]
The bug was not reproduced. To reproduce, add the **Street name widget** and **Second next turn widget** to the top of the screen for the car profile and starting navigation. As a result,  the "Configure map" and "Search" buttons did not overlap with these widgets. Instead, they were positioned correctly below the widgets, as expected.

OsmAnd~ 5.0.0#3849m, released: 2024-11-29

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/f13a4088-db61-4f5c-b71d-f8aff2d53478"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by vshcherb** [comment]
The issue was fixed by @Chumva let's see if it's reproduced in future
