### ISSUE TITLE
Revisit "Manage map files"

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#2152]
I have observed many users struggling with the way we display our screens for "Manage map files".

The primary confusion comes from how we structure the 3 different screens:

(A) The "All Downloads" screen is structured "Continent"/"Country"/"Map types", often with further subcategories "Regions"/"Map types".
 - (A1) Needless to say: Some categories overlap, and lead to users having overlapping files of the same type with no obvious way to detect this.
 - (A2) Depending on the level you are on, list entries can represent files itself, or can be headlines which can be drilled down further.

(B) The "Local" screen is structured "Map types"/ "Country-or-Region" only, all entries directly represent files.

(C) The "Updates" screen is simply a flat list with the map type indicated in the line item itself.

This creates the following issues:

(1) When you go from screen to screen, the structure changes with every tap.

(2) Our icon color coding can also not be consistent, of course: While e.g. "orange" next to something which represents a file means "updateable", "orange" next to something which represents a headline (and can be drilled down further) seems to only represent that you have the corresponding country-wide standard map present (while sub-country level standard maps or other country-wide map types present locally under that headline are ignored for the color assignment), right? As a result, the icon next to "Germany" on the "All downloads" screen always remains white no matter what you have downloaded for Germany, because there is no country-wide standard map.

(3) On some screens the dates for the items represent the server date, while on others the date of the local file. On no screen can you see both for direct comparison, this most-needed functionality is missing.

All this is not very obvious. I honestly think that a "less is more" simplification approach is better here:
- Why not use (and this partly goes back to what we had for years) only one screen
- With the elaborate structure of the "All downloads" screen
- Add 2 buttons to it "Display only locally present files" and "Display only updates", but when one of these filters is in place keep the tree structure. (Maybe expand it all.)
- The details for each file item should show, maybe in 2 lines, both the local file data and the server file data
- When the "Local" filter is set, expanding all files into one list on one screen but with the "Continent" / "Country" /... hierarchy shown, better facilitates spotting overlapping files. But we should also provide an automatic way to do display this, maybe mark overlapping files with a purple "overlapping" remark.

(4) As a secondary finding: The level on which we provide downloads is not very consistent, particularly for the SRTM downloads we often provide many very small files for provinces (while all other map types are provided on country level), Algeria can serve as an example here.

**Comment by vshcherb** [comment]
I think that's discussion has a long story. My main answer would remain the same, confusion could come from the moment you try to find objects and make object oriented UI, though this purely operationally oriented and it is focused to raise usability. All tabs are based on intents, the UI should not be much aligned with them but already aligned as much as possible, though we didn't make that consistent exactly  by the reason of usability.
Intent 1 - Download. There are lots of regions and lots of maps > 2000 , requires hierarchy.
Intent 2 - Clean up some space. Local tab. Exactly what's download how much space is taken etc.
Intent 3 - Update maps. Sizes of updates, days of overdue and so on.

Personally I oppose to mix intents in order to make consistent UI, cause any mixing will make UI less usable and less obvious for every intent.

Though my strongest argument would be to make feature freeze for Downloads at least for 9 months, this screen is subject to change for every release and it is quite too much, so if there is no critical issue let's keep it as it is.

**Comment by sonora** [comment]
Ok, I understand your reasoning.

Maybe it would help to leave all these screens in place, but still make the line-item appearance look alike as much as possible, i.e. on all 3 screens
-  Line 1 (bold font): Item title
-  Line 2: Map type ("Standard map", etc.)
-  Line 3: "Server date / size" (or "unknown", if offline)
-  Line 4: "Local date /size" (if file locally present). (add ""deactivated" if applicable)

I think this is not hard to implement, and combines the consistency and usability advantages I ask for with the screen/intent coherence you mention?

**Comment by vshcherb** [comment]
Let's make a design of it first, I'm confused it could fit 2-3 lines of the item row. CC @dmpr0
