### ISSUE TITLE
Smooth animation is broken after import profile from iOS

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd#21532]
### Description
After importing profile settings from [iOS](https://github.com/osmandapp/OsmAnd-Issues/issues/2776#issuecomment-2520902494), the map and UI animation turns into jumps

> More detailed steps and export files are attached at the link above

[logcat (97).log](https://github.com/user-attachments/files/18026865/logcat.97.log)

### Steps to reproduce

**iOS** firstly

1. Walking profile was reset to default
2. Configure Screen > Bottom panel > Add all three Sun position widgets, each on a separate row
3. Change widget size to Small
4. Go to Configure Profile > Export to file

**Android**

1. Import a file
2. Follow the steps in the video

### Actual result

https://github.com/user-attachments/assets/33262c0d-7710-4b27-b075-ef7991c94f7d

### Expected result

- [ ] Map zoom level animations and UI animations work smoothly

https://github.com/user-attachments/assets/f95e39ff-8f1d-411b-ae50-7baaeb8fab43

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: OsmAnd~ 5.0.0#3888m, Released: 2024-12-05 / 4.9.0.12
Android/iOS version: Android 14 / iOS 15.1.1
Device model:
Crash-Logs: ?
```

**Comment by yuriiurshuliak** [comment]
The bug has been reproduced using these steps:  

**iOS:**  
1. Reset the Walking profile to default.  
2. Go to **Configure Screen > Bottom panel**, add all three Sun position widgets (each on a separate row), and set their size to **Small**.  
3. Export the profile via **Configure Profile > Export to file**.  

**Android:**  
1. Import the exported profile into OsmAnd.  
2. Zoom in or out on the map.  

**Result:**  
Map zoom animations and UI transitions are choppy, with noticeable "jumps" instead of smooth movements.  

OsmAnd~ 5.0.0#3908m, released: 2024-12-09

https://github.com/user-attachments/assets/8611d578-10c4-4e9b-a9e1-e09a1d2ed751

**Comment by 0xRe1nk0** [comment]
The issue with animations is due to the "**do_not_use_animations**" preference being set to true in the provided exported osf file. This likely happened because 1 step of reproducing in iOS "**Reset the Walking profile to default.**"  and iOS team should check setting this preference when resetting profile settings to default.

After importing the settings on Android, preference **No animations** is active. If turn off this preference animations will start working again

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <td><img src="https://github.com/user-attachments/assets/a43a4755-01a6-43ed-8a36-7ff238b0e545"  width="300" height="auto"/> </td>
      </tr>
    </table>
</details>

**Comment by Zirochkabila** [comment]
`OsmAnd~ 5.0.0#3944m, Released: 2024-12-17`

The test will be completed after the iOS fix is implemented [4214](https://github.com/osmandapp/OsmAnd-iOS/issues/4214)
