### ISSUE TITLE
The half-screens that slide in using animations do not exit when swiped in reverse direction.  

### ISSUE THREAD

**Issue by raindropsfromsky** [osmandapp/Osmand#2164]
The Drawer menu slides in from left, and conversely the user can close it with a swipe in reverse direction (i.e., right-to-left).

But the same is not true of the other half-screens that arrive with a similar "slide" animation: If the user wants to dismiss them, he cannot swipe in reverse direction.

***Desired:*** The GUI screens should behave consistently.

**Comment by vshcherb** [comment]
Drawer has quite consistent behavior it is draggable from the left, that's why it is swipeable to the left, not because the animation indicates this.

This is impossible to implement for other screens, cause Dashboard/Waypoint has swipes in the row. Guidelines are not strict about animation and dismissable behavior

**Comment by Barrocas** [comment]
If the phone is in portrait mode, when we tap a POI the context menu slides from the bottom, and can be swiped to the bottom again, closing the menu and dismissing the POI orange inverted teardrop (as in selected).

It is not the same in landscape mode, the POI menu opens from the left side, but it cannot be swiped back to the left.
