### ISSUE TITLE
Needs smarter and more supported formats in search by coordinates

### ISSUE THREAD

**Issue by naoliv** [osmandapp/Osmand#2172]
In osmand we have this:

![Search by coordinates](http://i.imgur.com/EUZBD0e.png)

But we need to choose the format and the options are limited.

Could we have a smarter coordinates interpreter and also support more formats, please?
For example, in JOSM we can enter any of the following formats, without needing to select anything:

![JOSM](http://i.imgur.com/kQjcyZI.png)

Maybe osmand could use JOSM's code for this.

**Comment by vshcherb** [comment]
Possibly, but it would work better once we have 1 line search edit text and 2 text boxes. This UI is primarily targeted to enter information and copy/paste which is less frequently use case for mobile.

**Comment by naoliv** [comment]
I did ask for this exactly because I couldn't paste one lat/lot that I had copied from a message (it was in a non-supported pattern)

**Comment by vshcherb** [comment]
It would be great if you share the format what you got in a message.

**Comment by naoliv** [comment]
Right, I will see if I can find it. It was in a travel ~1 month ago.

**Comment by vshcherb** [comment]
BTW copying from other projects sometimes is not that easy. I remember one time we tried to copy OAuth from JOSM but failed due to many dependencies. So sometimes it is easy to create analogue, that's why popular formats are needed. In IOS we support urls as well http://www.openstreetmap.org/#map=16/50.0186/36.3338 (so we might better take this code).

**Comment by sonora** [comment]
I guess this should be re-visited in a new issue with concrete examples in our new search UI.
