### ISSUE TITLE
[Improvement] Simplify address search with only one field / Shared addresses not recognized

### ISSUE THREAD

**Issue by klawdhfzasjhaa** [osmandapp/Osmand#2181]
I think OSMAnd could make address search easier by adding an option to type the whole address or parts of it and let OSMAnd make suggestions (searching the available maps). Like in Google, the user would choose the appropriate and start navigation for example. It's not convenient to choose Region and City before typing the street name. 

Moreover everytime I share an address from another app (e. g. calendar) OSMAnd has no results, even if the full address is given. Probably this would work if the standard search algorithm would be different / allow above mentioned input.

**Comment by vshcherb** [comment]
Agree!

**Comment by ppenguin** [comment]
Agree too! Actually I would argue that this is a major factor keeping skeptics away from OsmAnd.
I might be interested to take a look at it, but I fear it's a bit above my skills...

**Comment by vshcherb** [comment]
We have a plan to work on it next release though it requires initial setup and after that it will be easier to contribute  & discuss

**Comment by jomo** [comment]
I agree with @ppenguin, this is the main reason why I think OsmAnd is barely usable. I kind of expect a map/navigation app to have a single search bar to enter an address, POI, or similar. OSM's [nominatim](https://nominatim.openstreetmap.org/) is a great example. I also think this should work when I have either downloaded data or a working internet connection.

At the moment I don't have downloaded any maps but they work just fine downloading on the fly. I'm confused how to search for an address if that's at all possible.

Having a single search bar that does online lookups (if desired) would improve user experience a lot!

**Comment by homersimpsons** [comment]
I think current system is good because:
1. It's easy to implement
2. It can provide a fast result with indexation
3. It avoid typing error (here maybe you can make suggestion if there is some different letter) 
4. It gives an easy structure to search an address
5. It's always fast 

I think that adress search field could be a must have, but have some drawbacks :
1. It's hard to implement
2. It can be longer to search especially if there are mispelling
4. It need to match all possible adress structure, and maybe without country (I don't think it's a problem)  or city/postcode then it needs additional comparisons to check distance 
5. It can be longer to type/ to provide a result

Finally, I don't like to compare apps, but have a look how Sygic make adress search, it's clear and fast.

Furthermore while it's impossible to search in a whole (divided) country, I think this shouldn't be implemented.

**Comment by HolgerJeromin** [comment]
Providing this backend would allow to click on a calendar event and open the place of it with osmand. This place is the same one line search.

**Comment by breversa** [comment]
@HolgerJeromin : Exactly ! That's what prevents OsmAnd to be considered a fully-functionnal navigation app IMO. While I understant the technical difficulty to implement single-field search, it's a must-have to drag in new users, who will most often choose UI simplicity anything more complicated, and expect tapping an address to open the navigation app to get there (and I do to !). :-)

**Comment by madprogger** [comment]
Must-Have!
I only can provide information to the app i already have. If i know the name of the city, but am unsure for the region, the current dialog has no use. I am bound to search the city first in google to determine the region to choose for searching. Too bad i like to use OsmAnd in offline mode, so googling is not an option. So currently i end up switching between regions manually and doing multiple searches until the correct city is found. This is a no-go. Even if a region-spannnig index will not be implemented due to complexity reasons, a simple "i have a city-name, now please search in all regions i have downloaded" - search should be possible.
A first step could be a "any" - region to choose in the search dialog, which leads to a city-search through all downloaded regions. This will be slower, but far more usable. And needs no UI-changes.

**Comment by sonora** [comment]
Implemented.

**Comment by jomo** [comment]
I've been using the new search for a while and want to congratulate you on it. It's really awesome and improves OsmAnd by orders of magnitude. Thanks a lot to everyone involved!
