### ISSUE TITLE
OsmAnd+ 2.2.4  "manage map files" screen - can't see Regions

### ISSUE THREAD

**Issue by BasTomasz** [osmandapp/Osmand#2207]
Manage maps  - on main screen I can't see "Regions" - only "Other maps".
When I click "Other maps" I can see very long list with files:
- contour lines (~90%)
- "country maps": standard, roads-only and Wiki but only a few countries...

On other smartphone with OsmAnd 2.2.4 (without +) I can see country maps groups in "Regions"...

What about "paid" version?

**Comment by crimean** [comment]
Do you have internet connection when you open Manage maps screen?

**Comment by BasTomasz** [comment]
Yes.
I can "refresh/rebuild" list but... no result.

**Comment by crimean** [comment]
What version of OsmAnd do you use? Where did you get it?
Can you try it on different phone?

**Comment by BasTomasz** [comment]
read 1.st post, please and title of this topic.

**Comment by crimean** [comment]
Looks like issue with internet connection. Can you try free version (without +) on your phone?

**Comment by BasTomasz** [comment]
No, I can't.
There is a topic about it - not mine.

**Comment by crimean** [comment]
Did you try to reinstall the app?

**Comment by BasTomasz** [comment]
Do You understand this hint is like: format disk and reinstall Windows?

**Comment by BasTomasz** [comment]
OsmAnd daoesn't remember lat setting after such operation...

**Comment by vshcherb** [comment]
There is a topic in github - fresh: last 15 days I think.
Edit: #2161 
Is already fixed you can install both versions, check latest comments.

The issue we can't reproduce the issue, unless situation change or may be some other people will give more insights, that issue won't be addressed.

**Comment by marienz** [comment]
I'm seeing the same symptom on my tablet (a Nexus 9, running OsmAnd+ 2.3.5). I definitely have a working Internet connection, as updates of maps already on the device work, but the "Regions" section in "Manage Map Files" is missing. Everything else seems to be there (comparing to my phone, which does not have the same problem).

Probably related: when I start OsmAnd+ I briefly see this error message: "Corrupt file: it should have ended as it starts with version: regions.ocbf". I can trigger that error message by leaving OsmAnd, swiping it away in the task switcher, then entering it again. It only appears for a few seconds (and I hope I transcribed it correctly).

I tried "Clear Cache" in the Android app settings. This made no difference to either the error message or the lack of "Regions".

Next, I tried "Clear Data" in the same settings panel. This cleared the problem. OsmAnd prompted me where I'd like to store maps, and through trial and error (and "Clear data" a second time to get back to that prompt) I found that using "shared" rather than "internal" storage means it finds my previously downloaded maps.

Assuming the error message about a corrupt regions.ocbf is accurate: it looks like OsmAnd detects the corruption but could recover more gracefully than it currently does?

I apologize for destroying the evidence by clearing data, but I have a trip coming up and am packing my devices full of maps in preparation for it :)

**Comment by vshcherb** [comment]
Sometimes regions are not visible if the program is not properly installed or it crashed while running first time.

**Comment by marienz** [comment]
I'm pretty sure "not properly installed or crashed while running first time" is not what I encountered, as I was previously able to install maps on the same device. But I probably installed those using an older version, and an upgrade may have crashed on first use.
