### ISSUE TITLE
Stop sign is shown up to early and direction isn't respected

### ISSUE THREAD

**Issue by jf-simon** [osmandapp/Osmand#2213]
The stop sign is shown up to early. On the screenshot you can see, that the sign is 500m away on the second turn.
![screenshot_2016-02-01-17-35-48](https://cloud.githubusercontent.com/assets/11144987/12746293/31c82f64-c99e-11e5-8dc7-6383b763ebfc.png)

 This is confusing because the first turn. I think I would better to check for an turn or crossing before showing the sign.
Somewhere else, I couldn't find the issues, it was also reported the the value 'direction' isn't respected. That's also very confusing while driving and a stop sign is shown when there is non to seen in the way out.

Getting Simon

**Comment by sonora** [comment]
I have simulated this, and cannot reproduce your issue. The stop sign warning for the corner of  Kälberbronner Straße and B28 only appears 150m short of B28 (so about where you are closest to the residential Hofenstraße), which is our default (150m or 10 sec, which ever comes first.)

This matches my personal experience and testing, and I also re-inspected our code.

Could it be that there used to be a stop sign a the corner of Weilerstraße and Kälberbronner Straße, and that is being announced to you? Cannot see one in OSM now, though. Wurttemberg map I used for my simulation is of November 3.

I suggest the following: Calculate the route again, then go to the Waypoints screen, tap on the Stop sign (under "Traffic warnings"). The sign in question is then highlighted on the map, verify which one it is, and check if you see more than one.

Please note that I do think we do in deed have the following issue in OsmAnd (and I am not sure how to fix): There is no directional information about a stop sign, so you may get one announced even if it "faces" the opposite direction you are driving, so is not really "relevant" for you.

**Comment by vshcherb** [comment]
That issue bothers me as well, I'm not exactly sure that 10 seconds is correct.
My example with barrier: 
http://www.openstreetmap.org/?mlat=52.28677&mlon=4.86810#map=17/52.28677/4.86810&layers=N
from that point in 90% I see the coming sign, the speed is average to 40-50kmh.
The barrier itself is here
http://www.openstreetmap.org/?mlat=52.28280&mlon=4.86533#map=17/52.28280/4.86533&layers=N.

Which is approximately 300-400m away and it is about 15-20 seconds. I think it is quite far away and actually I would not expect 10 seconds and I would expect 5-7 seconds. Of course it is always a matter of try, but I definitely would like to reduce the time for barriers, stop-signs, railway crossing, because usually it happens in rural area with a slow speed, so reaction of the driver is quite fast and waiting >7 seconds doesn't feel correct

**Comment by sonora** [comment]
Victor, from what I see we set these AlarmInfo lead times here: https://github.com/osmandapp/Osmand/blob/master/OsmAnd/src/net/osmand/plus/routing/AlarmInfo.java#L120, and they have apparently never been changed since your first implementation in 2013. Would be easy to tweak them a bit, I agree 7 seconds is probably enough for most warnings.

But it sounds like we are dealing with another bug here, and by simulation and I cannot reproduce the issue originally reported (and yours sounds similar). I think to solve that we have to verify first that OsmAnd is really referring to the traffic_calming you assume, or one off-route, or even "behind" you. Of course, your "90%" bothers me. We have to find a way to make this reproducible. I assume you are always talking about cases where the follow nav mode is active, not cases where it has been canceled, or has never been on?

Chances are we may somehow confuse our list of Waypoint alarms if a speeding alarm interferes, which has the highest priority, but inspecting the code following https://github.com/osmandapp/Osmand/blob/master/OsmAnd/src/net/osmand/plus/helpers/WaypointHelper.java#L175 I cannot see an issue for now ...

Best, Hardy

**Comment by sonora** [comment]
Leave a comment

**Comment by sonora** [comment]
PS: We divide int by float here: https://github.com/osmandapp/Osmand/blob/master/OsmAnd/src/net/osmand/plus/helpers/WaypointHelper.java#L190 Not sure if that produces unwanted results in some cases.

**Comment by sonora** [comment]
On second thought: I wonder why we leave updateDistanceAndGetPriority with return=0 on the occasion that nothing is coming momentarily, shouldn't it be return=Integer.MAX_VALUE ?

**Comment by jf-simon** [comment]
I also cant reproduce this while simulation. But yesterday i drove this route and get the stop sign. maybe because i drove about 80km/h before entering the village. 
About the direction of the stop sign. like in osm wiki [http://wiki.openstreetmap.org/wiki/Tag:highway%3Dstop](url) i have added ` direction=forward` to the sign.
thanks for working on this issue.

Simon

**Comment by sonora** [comment]
Let's wait for Victor's judgement but I think my analysis with the speed alarm is correct and also the solution I prpose may likely already solve it (or we have to cleaner reset events).

**Comment by jf-simon** [comment]
Ok Thanks for all

**Comment by sonora** [comment]
I have made the commit, let's test with the nightly build.

**Comment by vshcherb** [comment]
I don't think 0 is bad there,  because we have nothing starting with 0
	SPEED_CAMERA(1, R.string.traffic_warning_speed_camera) ... 
I will test it as well and I will share GPX track next time, I hope I will be able to do this today :) Thanks, will download the latest version

**Comment by sonora** [comment]
We actually had 2 situations where thus bug occurred, both should be fixed now:

Situation (1):
During a navigation, within <1500m of a stop sign, you are over speed:  So line https://github.com/osmandapp/Osmand/blob/master/OsmAnd/src/net/osmand/plus/helpers/WaypointHelper.java#L175 triggered a SPEED_LIMIT alarm. Then subsequently line 191 of that file returned "0" for the stop sign in <1500m,, and in line 192ff this stop sign was now found to be the most important alarm (0 having higher priority than the speed alarm's 2), so the stop sign became displayed/announced.

Situation (2):
If you started your route anywhere within 1500m of a stop sign, the stop sign got announced immediately, you did not even need a speed alarm to trigger it.

Both situations should be cleanly fixed as we have it now: No alarm in reach: Let's sett the priority to "lowest" (MAX_VALUE), rather than 0 (highest).

**Comment by vshcherb** [comment]
I tested the day I mentioned and it works good, I got notification in 7 seconds and 150 meters ( I was driving 35kmh). Thanks!
