### ISSUE TITLE
Add move down/move up in Waypoints actions

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/Osmand#2221]
The only possibility to delete/change order in waypoints is swipe left or drag/drop we should add these actions to action list as well.

**Comment by therob84** [comment]
In v2.5.2 at Android 5.1 (Fairphone 2) I even can't find any way to sort waypoints in any of the confusing menus/lists (neither with drag/drop nor with any other way). 
Where did you find it or which version you used?
This could be related to #2158

**Comment by vshcherb** [comment]
Sorting is available on the first item 3 dots

**Comment by therob84** [comment]
@vshcherb Can you please provide a screenshot in which of the menus it should be located?

I really can't find any manual sorting option in my OSMand. Only the door-to-door I can find, but no manual way.

**Comment by sonora** [comment]
I am not sure if this is in the release yet, but in our nightlies we have had this for a long time: On the Waypoints dialog screen
- swipe a point left or right removes the point
- swiping it up or down facilitates easy sorting.

**Comment by therob84** [comment]
Thanks for your answer!
> I am not sure if this is in the release yet...

I can assure you, that none of the waypoint menus do support swiping (for up and donw after a long-tap I assume) or drag and drop in my version 2.2.4. 
It was at least in a simpler way possible in v2.1.1.
Though: you really should integrate it to the release version as fast as possible, because without this routing with waypoints is simple not usable!
