### ISSUE TITLE
[IMPROVEMENT] map rotation should switch back to "north up" at certain zoom-out level

### ISSUE THREAD

**Issue by therob84** [osmandapp/Osmand#2229]
If the map orientation is set to "compass" it is changed back to "north up" if I reach a certain level during zooming-out.
Is this intented behaviour? If yes, it is really disturbing if I want to get an overview of the area or a route, as the orientation I set before is overwritten with "north up".

I vote for removimg this anti-feature. 
The user can use "north up" if he want, but should not be forced to use it.

I use v2.5.2 at Android 5.1 at a Fairphone 2.

**Comment by vshcherb** [comment]
It is already implemented LOWEST_ZOOM_TO_ROTATE=9

**Comment by therob84** [comment]
But I find no way to change it in the menu.
How it is intented to get changed?

That any value exists I got from my trial-and-error-tests. But how to change?

**Comment by therob84** [comment]
@vshcherb: Still I don't know if it is possible for the user to change this value? If yes, where?

**Comment by vshcherb** [comment]
No it is not possible, but it is doable with custom compilation

**Comment by therob84** [comment]
I don't know why the issue is closed as the user have still no control over this feature.

Maybe I made myself not clear enough (and I did make a mistake in the title):
I vote for **REMOVING **this feature, as I find it not useful.
Or at least include a switch to disable it or adjust the level inside the GUI.

**Comment by vshcherb** [comment]
OK, now it is clear, yes it is to disable that feature, unfortunately the Github issues are not considered by us as polls cause there is not enough audience here. The issue is closed because we are not doing anything yet with it. 
It will be good to question others and we will try to reach a wider audience about this question and make a decision.

IMHO it makes sense to switch to north up after certain zoom but I could be wrong.

If somebody wants to share his opinion, he is always welcome and we are watching comments on the closed issues as well.

**Comment by therob84** [comment]
OK, thanks for coming back here.

In the following scenario I DON'T want to have the map with "north-up":
**I want to know which mountain/city at the horizon (far away) is visible.**
--> I use OSMAnd and zoom-out as much as necassary to identify this landmark
--> I WANT to make a bearing with the compas-aligned map at the landmark's direction along the OSMAnd-map to identify the landmark
**Problem**: Map is meanwhile rotated with "north-up" and now I have to rotate my whole phone to find the direction! That phone is not SMART anymore with this....

**So again I vote for an option to disable this feature!**
I would like to use this very frequently and it annoyes me a lot!

[It's the same problem during navigation, where I would need "direction of travel" to stay activated while zoom-out]

**Comment by DFyson** [comment]
Yes I agree it would be good to keep map orientation no matter the zoom level. But I also see it useful to switch back to North up since at low zooms we are most familiar with the maps with N up. Depends on the user and their application. So in my option there should be an option to set which zoom level causes the map to switch back to N up.
