### ISSUE TITLE
[Feature Request] time average of "Current Speed" and orientation "Moving Direction"

### ISSUE THREAD

**Issue by therob84** [osmandapp/Osmand#2230]
**_1.) Time Average of "Current Speed" display:_**
Especially during walking the speed calculated at the basis of the GPS signal is very inaccurate and unsteady although I walk very steady.
The displayed "current speed" in the right upper corner (if activated) could be massively improved, **if a time-average function is implemented**.
This could be done by providing e.g. 1/5/10/60/300 second intervalls in which the calculated speed is averaged. An easy GUI implemtation could be a long-tap at the speed display to toggle between these values displayed then inside the symbol.

**_2.) Time Average of orientation speed if  "Moving Direction" is selected:_**
Especially if one moves fast through very sharp curves (lets say a double 180° curve) it makes no sense that the map orientation follows the movemente instantly if "moving direction" is selected.

A better way would be **time-average rotation of the map**, to allow fast changes of direction and only if one stays at a new direction the map should be orientated. 
This could be done by providing e.g. 1/5/10/30/60 second intervalls in which thedirection needs to be changed until the map orientation is also rotated. An easy GUI implemtation could be a long-tap at the "moving direction" symbol to toggle between these values displayed then inside the symbol.

It could also save some CPU power if less orientation-rendering has to be performed.

It would be great if these improvements could be implemente in the next version of OSMAnd.

**Comment by sonora** [comment]
My thoughts:

Ad (1) OsmAnd's core features should clearly not be very elaborate statistical calculations and evaluations, **when this complicates the usability or UI for the majority of "standard" users**. Having different time average mechanisms or selections of such for speed display seems like such a complication for many. While I agree the punctual measurement is not extremely useful in pedestrian mode, most users, in car mode, would need the actual non-averaged speed for e.g. the speed zone warnings, etc. Many advanced users, like e.g. hikers on a longer trip, can always evaluate their current travelling speed over different intervals and in different places using a GPX tracking and selecting different split intervals for the track analysis.

Ad (2) This display mode is mostly used for car users with no good compass reception due to lost of metal around them. And I think they need "instantaneous" response, what the see when looking through the window needs to be what they see in terms of map orientation, any delay would be confusing.

For pedestrians, I would always recommend "North is up", or "According to Compass" map orientation

**Comment by sonora** [comment]
No action planned here, it looks like.
