### ISSUE TITLE
[Feature Request] Add option of "Discard last GPX segment/track"

### ISSUE THREAD

**Issue by therob84** [osmandapp/Osmand#2231]
Scenario: A GPX track was begun and stopped again.
Now, If the GPX button is pressed again only 
**"Begin GPX-Track"** (=start new segment) and 
**"Save Track now"**
is available, which does not cover all option I usually need.

There should be also the posibilty to **discard the last segment and the complete last track** (which is not saved yet).

Please integrate this to the next version of OSMAnd.
I use v2.2.4 at Android 5.1 and the Fairphne 2.

Btw.: Is there a possibilty to merge **two GPX-segments to one** or merge ALL segments of a track to only one segment? 
This would allow to see the statistical data for the complete GPX track, and not only separated in segments.
Another possibilty would be to add this feature in the staitistic window to see the statistical data of the complete GPX track or even select the segments which should be included in the calcula

**Comment by dthgeek** [comment]
The problem with this idea is that it will also make it easier to accidentally delete GPX tracks and having lost tracks that took me hours to record with lots of waypoints in them which then couldn't be used to improve OpenStreetMap because of bugs that were either in old versions of OsmAnd+ or in old version of Android (Which thankfully has been fixed) I would hate for a new way to lose data to be added to OsmAnd. If "Discard last GPX segment/track" is added PLEASE make it an option that has to be enabled (not on by default) in the "Configure screen" settings or in the "Trip recording" plug in settings. 
Thank you

**Comment by therob84** [comment]
OK, but a confirmation Dialogue like "Are you sure you want to discard/delete previous track?" should be enough to avoid accidently erase data, shouldn't it?
And I am only talking about tracks which are not saved yet....
Not tracks from last week, only the GPX which is still in the "active memory" of OSMAnd...

**Comment by samir213** [comment]
Yes, me too, I miss the option to discard the track, and also to give a name to the track when saving it, every couple of days I find my mobile full of tracks with date/time names, wich I have to verify every single one of them before deleting the unnecessary ones...

**Comment by sonora** [comment]
I think we should not overcomplicate OsmAnd by trying to make it a full-blown GPX management software, there are some things suggested here for which much better specialized software is available.
