### ISSUE TITLE
Keep green flag for starting point when defining a destination point manually.

### ISSUE THREAD

**Issue by stephan75** [osmandapp/Osmand#2238]
_Issue similar to #2192:_

Preparation for reproducing issue: (seen on 2.3.0#15657 from 09-02-2016)

Have NO destination and NO waypoint defined inside Osmand app, and have NO GPS fix.

When defining a STARTING point via long tap on the map, via three-dots-menu and then choose "Directions from" ... I can see the starting point with the green flag, covered by the orange round position marker, with the "Navigation Menu" where you can choose car foot bicycle etc. OK.

According to the user interface intention I can now define my destination by tapping the "Select destination" field, by choosing a Favourite..., Selecton map or Address...

This also works fine, and after some seconds, the route is calculated wit that purple line.

BUT now imagine the case where I have defined only the starting point via the green flag, and I dismiss the dialog field (with the icons for car, bicycle, foot, from: to: Distance, Time, the X, flag, gear wheel and the Go field) because I want to scroll first to quite another part of the map or find POIs manually in my destination area.

So you have the map again covering the whole screen, and only a start defined with green flag.

Now I decide to define my destination point manually by a long tap anywhere on the map. So the dialog box with Location, icons for favourites, waypoints, share and the three dots comes up.

The only way to define the destination now is to select the blue circle with the white arrow symbol.

When doing this, the green flag and so my starting point is **deleted**!

**Why??**

I have to define my starting point **anew **from the dialog box!

What is the reason for "deleting" the green flag, and not keeping it like the destination flag or waypoint flag?
Are there any technical reasons?

Because I really would appreciate when a defined starting point is kept by osmand, to do a free route planning.

Starting point and green flag could be overridden when navigation is started by user via Go-button or similar, and when Osmand app HAS a GPS fix.

So please:
Keep green flag for starting point when defining a destination point manually afterwards.

PS: also when having a green flag on the free whole screen covering map, and then choosing the "navigation" button (white button in the bottom left corner with a grey square and a white arrow inside), the green flag gets deleted also! Why?

**Comment by vshcherb** [comment]
The main technical reason, that you can't navigation from any other point than start point. Though you can calculate the route from the start point. Technically saying when you click navigate - start point should be either removed or made as first intermediate point. 
Because it is quite confusing, we are making an attempt to completely redesign map preparation stage and introducing map markers. On that screen you can preview the route and define all the points, though it is not necessarily to navigate the route and it is not necessary to clean all markers in case you want to navigate only to the first point and leave other points untouched.

Let's focus on the new feature and address this one in case markers will be switched off as idea.
