### ISSUE TITLE
Overlapping relations are not rendered properly.

### ISSUE THREAD

**Issue by DFyson** [osmandapp/Osmand#2274]
For offline vector maps, relations with role:inner are rendered following "XOR" logic whereas online OSM tiles render them as "OR". In otherwords the problem arises when two of those relations overlap, the offline vector maps show the intersection as role:outer while online tiles renders as role:inner. Compare [online](https://cloud.githubusercontent.com/assets/12941728/13278082/8cc207b0-da9b-11e5-87fd-0fdcda7d5ab3.png) vs [offline](https://cloud.githubusercontent.com/assets/12941728/13278097/aa6b47e0-da9b-11e5-8c9b-d70a9810eee8.png) screenshots.

**Comment by vshcherb** [comment]
I don't think it is advised to draw like that, in any case there are 2 strategies to draw multi polygons (winding and even/odd). We switched from winding because we had quite a lot of issue with this algorithm. According to even/odd this is a correct result.

So this issue can be considered as known and can't be fixed today.
