### ISSUE TITLE
Improvement: Resolve google maps URLs

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#2278]
When tapping on an openstreetmap.org URL like e.g. http://www.openstreetmap.org/search?query=hampton%20new%20york#map=11/40.7790/-73.9558 in Android (like in an SMS or mail), OsmAnd offers to process this and, when selected, correctly displays the position on the map.

I have a request here t do the same for google-map links (possibly also bing), i.e. other frequently used URL patterns to share locations.

**Comment by vshcherb** [comment]
Yes because #map=11/40.7790/-73.9558 it has, google maps have at least 10 different url schemas. 
Please check all supported urls https://github.com/osmandapp/Osmand/blob/master/OsmAnd-java/src/net/osmand/util/GeoPointParserUtil.java#L459

This request is too wide and duplicates request to search by name which is not supported on purpose (it was too faulty).
