### ISSUE TITLE
Osmand includes road under construction

### ISSUE THREAD

**Issue by Posteinwurf** [osmandapp/Osmand#2292]
In Berlin, Osmand tells me to take a road (track) that is under construction / projected.
I am using cycle mode (with a modified routing.xml that prefers tracks and paths over main roads). 
![1](https://cloud.githubusercontent.com/assets/17393264/13393915/c3c44de8-dee4-11e5-91a2-5d8812eb79a6.png)

Also, Osmand sometimes suggests this alternative, which might be blocked (fence / gate).
![2](https://cloud.githubusercontent.com/assets/17393264/13393914/c3c24d40-dee4-11e5-9e1d-c172cf7c0b12.png)

Thanks for checking!

**Comment by Zahnstocher** [comment]
How should this be interpreted?
highway=construction
bicycle=designated
foot=designated

Currently OsmAnd thinks that foot/bicycle=designated overwrites highway=construction.
I don't know if this is correct.
This situation seems not be defined in OSM wiki?

https://www.openstreetmap.org/way/293386232

The problem is that there are highway=construction which are still under construction but are already passable by foot and bicycle.

**Comment by vshcherb** [comment]
I don't think it is correct (osmand interpretation). I think highway construction should disable routing anyway it is ambiguous situation. 

I think today it is easy to disable routing bicycle=no and use construction=yes and highway=cycleway. Rather these confusing schema when everything is related to same tag highway. 

P.S. : I'm not an expert in OSM

**Comment by xmd5a2** [comment]
I think it as a tagging problem (or not a problem at all)

> The problem is that there are highway=construction which are still under construction but are already passable by foot and bicycle.
