### ISSUE TITLE
Road Shields Netherlands: int_ref in White-Red instead of Green-White

### ISSUE THREAD

**Issue by CJTmmr** [osmandapp/Osmand#2318]
In latest nightly's:
Some Motorways in the Netherlands have a double int-ref;
e.g. [Motorway A12](http://www.openstreetmap.org/way/7359667#map=17/52.06644/4.75190)
ref=A12; road shield is Red with White text = nice and okay
int_ref=E 25;E 30; road shields are Green with White text = okay
A12 is member of road-relations E25 and E30.

At some zoom levels the second int_ref  E 30 has a White road shield with Red text.
This color-combination is only used for bicycle-routes in the Netherlands...
![2016-03-06 04 33 40](https://cloud.githubusercontent.com/assets/15076257/13649183/af8d103a-e63c-11e5-989d-b65fe79717ff.png)

**Comment by vshcherb** [comment]
I think it is a bug and it should be the same as E 25

**Comment by xmd5a2** [comment]
1.int_ref is not used at all. route=road relations are used to determine road numbers.
2.In this particular case e-road E 30 relation  does not contains network=e-road which is used to determine shield color and shape. We can't blindly assign green shields to all refs starting from "E" because some countries use "E" prefix in their national road system (f.e. Greece, Equador). I added network=e-road tag to that relation.
3.It seems that you are using old nightly because red text on white background was used for testing purposes as fall-back and now it is not by default.

**Comment by CJTmmr** [comment]
Thank you for explanation and fixing relation e-road E30
I now build OsmAnd on Windows 10 with Android Studio, with latest commits merged,maybe there is still a littke twitch.
