### ISSUE TITLE
Symbol for skilift is always a gondola

### ISSUE THREAD

**Issue by CJTmmr** [osmandapp/Osmand#2353]
In ski-areas the symbol for a aerialway-station is always a gondola:
aerialway_station.svg
![image](https://cloud.githubusercontent.com/assets/15076257/13933070/ad5bfd58-efab-11e5-91ea-83e14247f111.png)

You could use different icon for cablecar, gondola, chairlift and draglift/t-bar lift:
http://wiki.openstreetmap.org/wiki/Aerialway

Difficulty is maybe that the type of aerialway is only tagged on the way and not directly on the station-node...

chairlift
![image](https://cloud.githubusercontent.com/assets/15076257/13933296/bbdfd5ba-efac-11e5-9e85-452132a2055f.png)

cablecar
![image](https://cloud.githubusercontent.com/assets/15076257/13933251/74ca8db4-efac-11e5-9916-4c8a044a3ae3.png)

draglift
![image](https://cloud.githubusercontent.com/assets/15076257/13933283/a2eebe04-efac-11e5-99bb-5f95de81442b.png)

**Comment by xmd5a2** [comment]
Not possible without maps preprocessing at that moment

**Comment by vshcherb** [comment]
Today it is not possible to do with custom mapping or custom rules of processing because we don't have possibility to propagate tags from line to the center point (we use similar technique for relations -> ways, so we can propagate bus relations and display combined text on the line, but we don't have that technique for way -> node)

**Comment by sonora** [comment]
No action planned.
