### ISSUE TITLE
Announcing: Turn around in stead of turn left/right

### ISSUE THREAD

**Issue by CJTmmr** [osmandapp/Osmand#2420]
![2016-04-02 14 18 51](https://cloud.githubusercontent.com/assets/15076257/14234426/da60a3d0-f9e2-11e5-82b7-1ae9b4c9c3a0.png)

It is [this location](http://www.openstreetmap.org/#map=18/52.07573/4.82049)

When there are two left (or right) turns close after each other, OsmAnd announces "turn around to  streetname...." (in Dutch: "Keer om naar ....) not even specifying left of right.
Also the wrong streetname is used.

It could be better to show and say "turn right and immediately turn right again" (of left..)
A "turn around" should only be used for a real U-turn when the names of the streets are the same.

This was changed about half year ago - before that it was okay.
It also happens with two turns to the right.

Another example: on [this location](http://www.openstreetmap.org/#map=18/52.08987/4.87933)
![2016-04-01 06 44 53](https://cloud.githubusercontent.com/assets/15076257/14234538/97f1b8a6-f9e5-11e5-8d95-3f7299cf5914.png)

**Comment by vshcherb** [comment]
I think here https://github.com/osmandapp/Osmand/blob/master/OsmAnd-java/src/net/osmand/router/RouteResultPreparation.java#L425 we should check 1st/2nd roads are oneway and then assume it is a uturn.
P.S. Sometimes it is hard identify uturn when roads in 2 directions are split in OSM.

**Comment by rominf** [comment]
@vshcherb Could you look at the code? It seems to be working in this case, but this approach breaks this: https://www.openstreetmap.org/#map=17/36.56330/-95.92840. Should we add rule for `turn:lanes=reverse` => "make a u-turn"?

**Comment by rominf** [comment]
I think it would be better to allow merging different segments to u-turn, but calculate angle between nearest _long_ segments, ignoring short ones.

**Comment by CJTmmr** [comment]
In last nightly: Much better already, I think

Thanks
Kees-Jan
Op 5 apr. 2016 22:44 schreef "Roman Inflianskas" <notifications@github.com>:

**Comment by rominf** [comment]
Thank you for feedback, @CJTmmr, but I'm not sure my solution works good in all places. 

I've reverted simple solution: 
```
boolean turnOnSameRoad = result.get(i).getObject().id == result.get(next).getObject().id;
if (turnOnSameRoad) {
...
}
```

It probably breaks more than fixes, because it doesn't detect u-turn even here (it worked correctly before my fix):
![mapcreator5](https://cloud.githubusercontent.com/assets/3449635/14308630/58128396-fbe8-11e5-96db-c6202c56e4ac.png)

But if you don't have such turns nearby, consider to continue using today's nightbuild till we fix this issue a better way.

**Better solution**
Yet another idea came into my mind. I'm thinking about approximation of segments points (probably simple [Least squares](https://en.wikipedia.org/wiki/Least_squares) is a good candidate). After that we can make numeric differentiation, make a sequence of derivatives (tangents) and then extract all turns (including u-turns).

I think it wouldn't be too hard to implement, we don't need to process all roads (only in resulting way; long segments can be filtered out), so it should work quite fast, it also provides better results for several short segments linked together (this method would produce less turns).

Technically this could be used for visualisation on a small zoom (where difference between non approximated road and approximated way wouldn't be visible; on the other hand this approach would give cleaner resulting way). Also this could be used to create validator for `turn*` restrictions (to mark all suspicious places where `turn*` restriction says about left turn where only right turn is present, for example).

**Comment by vshcherb** [comment]
Yes it is incorrect check.
+				boolean turnOnSameStreet = result.get(i).getObject().id == result.get(next).getObject().id;
It breaks many legal Uturns.

I proposed quite different one: we identify uturn only if we start turn from oneway and end up with oneway street. Uturn on the same street, I think, is handled before.

**Comment by vshcherb** [comment]
The issue should be fixed now

**Comment by CJTmmr** [comment]
Indeed all the turns to the left are fixed. Good job!

But.....
Using Yesterday;s build: OsmAndF~ 2.4.0#12613D --; OsmAnd OfflineRouting, Car-mode

Two turns close after each other to the right are sometimes shown as U-turn and announced as "Turn Around to...." (Dutch: "Omkeren naar Burgemeester Bruntstraat")
Not speaking "left" or "right"

Today I came across this situation: [route is this on OSM](http://www.openstreetmap.org/directions?engine=osrm_car&route=52.07580%2C4.82022%3B52.07670%2C4.81993#map=18/52.07631/4.81965) 
and on [Streetview](https://www.google.ru/maps/@52.0762414,4.8191414,3a,75y,316.32h,76.55t/data=!3m6!1e1!3m4!1sfteuFlO2bmvakQ-hxPnygQ!2e0!7i13312!8i6656)

OsmAnd shows:
![2016-04-20 17 00 30](https://cloud.githubusercontent.com/assets/15076257/14687523/4afabe92-073e-11e6-8774-37b3f71861ea.png)

I hope this can improve OsmAnd

**Comment by rominf** [comment]
Yes, that's not a u-turn. Thank you for reporting, @CJTmmr, we'll investigate this.
