### ISSUE TITLE
Add setting for non-vehicle speed

### ISSUE THREAD

**Issue by mathstuf** [osmandapp/OsmAnd#2426]
Walking speed seems to be set to about 3 mph. It would be nice to be able to set an average and/or target speed for time estimates (e.g., higher for running, lower for snowshoeing).

**Comment by littlehelper** [comment]
+1
This would be also very handy when using different bicycle types (e.g. road bike or mountain bike).

**Comment by mathstuf** [comment]
Hmm. Even better is if it would take a running average of your speed during the navigation to get a more accurate speed.

**Comment by akahl** [comment]
+me
Sometimes Road conditions do not permit driving the assumed speeds rendering arrival times unusable. It would be great to be able to adjust speeds for routing calculations

**Comment by Buntbart** [comment]
+me
I can set my personal weight limit and a height limit. 
I would appreciate a speed limit as well because I want to use the german "Autobahn" but usually not much faster than ca. 100km/h. I think this might be an important presupposition to calculate the actual "fastest route" for me.
Plus, there are a lot of vehicles that are not allowed to go faster than a specific speed although the speed limit of the road can be much higher. Trucks, busses, heavy load, ...

**Comment by polarbearing** [comment]
Related to #3353 which is more vehicle-specific. But probably a personal max speed per profile will solve both issues.

**Comment by uwe347** [comment]
This would be a very helpful feature! It would bring up a better estimated time of arrival also for slower vehicles as trucks or caravans.

**Comment by Chumva** [comment]
It is possible now to set the speed for any profile used in navigation

<img src="https://user-images.githubusercontent.com/19220417/178826627-64184c7b-3cac-4c86-815a-e33905dc60a4.png" width="350" height="700">
