### ISSUE TITLE
Add ability to save routes

### ISSUE THREAD

**Issue by mathstuf** [osmandapp/Osmand#2427]
It'd be nice to be able to save routes (type, waypoints, exclusions, options, etc.) for future use. Being able to show multiple at once would be nice to compare different approaches to a location, trip planning and probably other use cases as well.

**Comment by kompowiec** [comment]
run route -->dashboard-->info-->save icon-->save to file GPX ? This is only available at this time.

**Comment by mathstuf** [comment]
That saves the output; I'd like to save the input (so that map updates can be taken into account).

**Comment by sonora** [comment]
Very questionable if it is worth it. If you look at other nav systems, the trend is to go more and more dynamic, like including live updates from traffic data etc.

So it is not very customary to save a lot of data other than your destinations, and some user settings which are mostly sticky anyway. Maybe we should concentrate on which of this data you need to remain between navigations but is not sticky in OsmAnd, rather than creating yet another "Save" interface.

**Comment by mathstuf** [comment]
Things which are important:

 * excluded roads/features;
 * waypoints;
 * gpx track (if any);
 * navigation type (car, bike, walk); and
 * options (avoid tolls, ferries, etc.).

**Comment by vshcherb** [comment]
Effective saving routes is technically not possible cause the underlying data could change. The only possible way to save approximate geometry, though later loading approximate geometry not always could be mapped to real geometry. So saving route as GPX is good for external programs, but we don't have a goal to provide all features of "Gpx navigation" comparable with "real-time" calculation
