### ISSUE TITLE
Pass along entire track bug

### ISSUE THREAD

**Issue by Barosky** [osmandapp/Osmand#2434]
Hello,

I think I've found a bug in the "Pass along entire track" feature.
If I enable "Pass along entire track" for a .gpx track and for wathever reason I go "out of track", Osmand wants me to restart from the beginning. In my opinion the correct behaviour should be that Osmand brings me back on track and forces me to redo ONLY the piece of track that I left out and not all the track from the beginning.

I hope my explanation is clear enough.

My Osmand+ version is 2.3.3 and I run it on a Galaxy S7 with Android 6.0.1.

Best regards,
Cristiano Dri

**Comment by vshcherb** [comment]
We need  more information about may be a GPX track and recorded track.

**Comment by edwardrmiller** [comment]
I too have had this problem. I'm using OSMAnd to follow along very specific routes, many of which overlap multiple times within a given route. I can upload these gpx tracks if it would be useful. Usually, keeping 'Pass along entire track' checked works really well.

However, when a particular turn is missed due to closed roads etc. the application navigates back to the beginning without warning. This makes the application impractical to use.

Is there a way to:

A) prevent the navigation from going back to start
B) Let user know they have gone past a given turning
C) Let users manually 'skip ahead' to another point in the GPX track

?
