### ISSUE TITLE
gpx output no longer supported by OSRM service. calculated route always empty.

### ISSUE THREAD

**Issue by rajeevn1** [osmandapp/Osmand#2436]
https://github.com/Project-OSRM/osrm-backend/wiki/Server-api

The only supported format is json.

**Comment by klic** [comment]
I found that also, last week, I wrote a mail to support, but now I did find this. Additionally, which makes planning of (long) routes difficult, YOURS only delivers a straight line, at the moment, in OsmAnd+, and the website does not do any routing at all...

**Comment by njohnston** [comment]
Perhaps an alternative here could be to add support for [GraphHopper](https://graphhopper.com/#community). It supports GPX output, and recently support for alternative routes was added too. It supports car, bicycle and pedestrian routing.

Since GraphHopper is available as one of the routing engines on OpenStreetMap.org, hopefully they'd be prepared to give OsmAnd access too :)
