### ISSUE TITLE
Split Austria & Switzerland, provide "Alpine regions"

### ISSUE THREAD

**Issue by RicoZ-OSM** [osmandapp/Osmand#2455]
Austria & Switzerland are each very large in east-west direction and very tiny in north-south direction but overwhelming majority of users will be crossing either or both of them in north-south direction. Many ways are crossing there so this may be of importance to many travellers

As an example to navigate from Bavaria to Locarno the whole maps of both countries are currently required. Similarly making a short trip from Munich to southern Lake Garda requires Bavaria, Austria and many Italian provinces. Also both countries have a few rather "heavy" cities which may be of little interest for some users.

I would propose:
* split Austria to: Vienna metro region,  rest of eastern Austria to/including Salzburg and western Austria
* split Switzerland: Grabünden, Zürich/Bern metro region, possibly also package separately the French regions west of Lausanne 
* package some Alpine regions - for example the area encompassing Bavarian Alps to Lake Garda or Ticino+the Italian part of Lago Maggiore.

**Comment by sonora** [comment]
Quick comment here: I have an increasing number of support cases and user complaints that people find themselves on a trip and have map data missing, which is naturally much hard to get on the road than it would have been to download at home.

The underlying issue is that we subdivided some regions (mainly Italy is causing big headaches now for some people), and this naturally makes the system of what you have and what you are missing more complex and less transparent than it used to be.

Complexity will further increase if we now started not only cutting along publicly known country or less-known province boundaries, but even "invented" sub-regions of our own, or started removing bigger cities.

I think the way to go for those who want to avoid too big downloads and are mostly concerned about navigation in transition regions is to load the "roads-only" maps for the regions in question.

**Comment by RicoZ-OSM** [comment]
@sonora: I agree that Italy has way too many provinces. Since few non-Italians know those provinces it makes it pretty hard to use for them and they rarely align with the need of travellers. Just a vacation at Lake Garda would require at least 3 provinces.

Austria & Switzerland are not only transit regions so getting roads only will not help everyone.

It seems that the Czech republic is subdivided in multiple ways in multiple granularities - what are the experiences with this?

**Comment by vshcherb** [comment]
We are planning to continue splitting countries though we would like to keep the hierarchy that basically means we are going to stick to official boundaries. There is a plan to enable city search in the app and make possible to download region using that search. It won't help for routing but definitely helps for map downloads.

**Comment by sonora** [comment]
Ongoing initiative to support more regional downloads, independent of this issue - closing for now.
