### ISSUE TITLE
The OsmAnd notification is problematic.

### ISSUE THREAD

**Issue by raindropsfromsky** [osmandapp/Osmand#2458]
When the screen is locked, OsmAnd shows me a notification:
**Running in background (navigation). GPS...**

This notification suffers from three problems:
 1. The first sentence is redundant: When the device is locked, it does not matter if the app is running in background or in foreground. The user does not need to know this. Just omit it altogether!

 2.  The second sentence is important, because it is supposed to tell the user what to do. But it breaks off after "GPS...". So the user never knows what it tries to say! What is he supposed to do??

 3. If I tap on the notification, my phone says "tap again to open" at the bottom of the screen. But if I tap the notification once again, the phone shows me the dot grid, and asks me to draw my screen unlock pattern. Thus the very purpose of having a notification is lost. I expect OsmAnd to come up directly without my unlocking the screen first (like how we can use the Camera app without unlocking the screen). (This may be possible only on the later versions of Android, but that's fine.)

**Comment by sonora** [comment]
Narayan,

I assume you are talking about the Android System Notification in the top bar of your device. Its primary purpose is to notify the user that an app is running as a service (less technically: "in the background") and hence e.g. is using significant battery power even when the device is in Sleep mode (Usually apps go to sleep when they are put to the background or when the device goes to sleep mode).

Ad (1+3) Hence, system notifications are not primarily targeted at the lock screen, but are general system alerts. In fact, many devices do not even show them on the lock screen. For the ones who do, the behavior of tapping on them varies. Usually, this triggers the default action (e.g. going to the app in question), but this is often broken when the lock screen has PIN etc. security configured. From my tests, this seems to behave identical for all installed apps with services active, only apps which come pre-installed on the device, like the camera, seem to have more functionality. In any case, the primary purpose of this notification is not to provide quick access to OsmAnd from the lock screen, but rather to alert about its background service being active regardless of device status ("OsmAnd is running in the background").

Ad (2) The second portion of the message is in deed hidden on smaller devices when in portrait mode (displays ok on landscape mode). It specifies why the background service is on, usually because of trip recording being active, or because a navigation is ongoing, or both, and we also specify the resulting GPS wakeup interval there. Unfortunately I find no way to line-break the message, on many Android systems it seems strictly being cut off to the available space of one line only. So the only mitigation I can think of is to re-order the message so that the reason(s) for OsmAnd running as a service and the associated GPS wakeup interval appear more to the front. If you have a good suggestion, please email me or state here.

Best, Hardy

**Comment by sonora** [comment]
PS: For reference, here is the structure of the current system notification text:

`Running in background (navigation, trip recording: xx meters, OsMo). GPS wake-up interval: xx seconds (or Continuous).
`

with either one or several of the comma-separated terms between the first parentheses.
