### ISSUE TITLE
Option to create new GPX file

### ISSUE THREAD

**Issue by littlehelper** [osmandapp/Osmand#2467]
Hi,
I love to use Osmand for planning my trips e.g. to foreign countries. Therefore I manage several GPX files (currently in Osmand called tracks), one for each country/region, and add GPX waypoints I might be interessted to visit when I am on the trip. "Add GPX waypoint" and selecting an apropriate GPX file (or track) for creating a waypoint works perfertly fine.
But starting to plan a completely new trip is a little bit tricky as long as I cannot find an option to create a new (empty) GPX file within Osmand. 

My suggestion would be to add the option to create a new empty GPX file:
1) It would be very helpful if Osmand will provide an option "New empty GPX file" or similar in the GPX file (or track) selection menu which is shown when choosing "Add GPX waypoint".
2) At the moment I think it does not make sense to add "Create a new track" or so to "My Places" > "My Tracks" as nobody would have in mind to create an empty track, I guess. But maybe in future handling of GPX files (including tracks) will look different (for example refer to [#2451#issuecomment-209286353](https://github.com/osmandapp/Osmand/issues/2451#issuecomment-209286353)). If so I would be pleased to see such option in the corresponding menu.

PS. I know that Osmand supports managing waypoints as favourites in multiple groups/categories and I like the way how these groups of favourites can be hidden. I still prefer to use separate GPX files because it is easier to share these files with desktop applications or other devices from my point of view.

Greetings

**Comment by sonora** [comment]
Re-reading this, I wonder if not the "Start editing" option of our Distance measurement plugin is exactly what you request here?

**Comment by sonora** [comment]
I think this can be done by creating your places as different categories under Favorites. With the help of the category tag, different gpx files (e.g. for different countries) can be combined in to the favorites database by successively importing them.

When creating a new category, you can export it (and hence create its own GPX file) by temporarily deleting all other categories. The favourites.gpx file will then only contain these points. Copy and rename it as needed.

Then restore your "full" favourites.gpx by re-importing all your GPX files again. I use this process often, because I have many different favorite files for travelling, test-rendering, etc. It can be done within 1-2 minutes or so.
