### ISSUE TITLE
Interface improvements in navigation options

### ISSUE THREAD

**Issue by franco999** [osmandapp/Osmand#2482]
I do not know if they are already working on this, but my suggestions would be:

1. Add category title to "Avoid"
2. Replace checkbox for at image
3. As it adds a category title, you can remove the word "Avoid" of other phrases.

![avoid](https://cloud.githubusercontent.com/assets/12088580/14689173/9adcba9a-071c-11e6-9ed5-4063178a71ef.png)

**Comment by franco999** [comment]
Deleting the word "avoid" as in step 3 above, also erased in the other navigation settings
![avoid](https://cloud.githubusercontent.com/assets/12088580/15633862/8ca50cf4-258d-11e6-92b7-adf85224a60d.png)

**Comment by sonora** [comment]
For the second screenshot (Navigation settings) I would agree, it would bring it in line with what we (mostly) do elsewhere, like on the "Announce..." or "Show..." submenu screens. But that screen is comparatively rarely accessed.

On the first screenshot (Route preferences) I feel it does not really add more clarity, could even be the opposite. Plus, it would take up more vertical space, and that is a long menu panel you have to already scroll anyway on smaller devices.

We use the same strings values for both screens, that's why I cannot change one without duplicating the set of strings or introducing some awkward string manipulation in the code (values on screenshot 1 are dynamically created by generic code). I have looked at this, but feel it is not worth the effort, we would not really gain much ...

**Comment by franco999** [comment]
On the first picture. How I see it, the only vertical space that would be needed would be the title 'Avoid ...'
By removing the word 'Avoid' in the lower options, increase the horizontal space on screens with smaller widths and in step 2, the square would be replaced by the switch.

If this is not feasible or advisable, please resolve the issue.

**Comment by sonora** [comment]
Let me close this one for now, I feel there is no good return for the effort to do anything here.
