### ISSUE TITLE
can't find addr:housenumber to a certain number.

### ISSUE THREAD

**Issue by kompowiec** [osmandapp/Osmand#2501]
Accident I discovered some issue, here: https://www.openstreetmap.org/note/499812
I try translated:
This buildings here about numeration over 500 once again have given to the collective waybills to belong to the street Freedom (pl. Wolności), however OsmAnd lists only a few of them. Is this a bug map?
checked: No, it isn't bug map. I check at OsmAnd, at this point I have only 175 buildings. It's some unknown limit application?

**Comment by rominf** [comment]
It seems that the issue has been fixed with latest versions of MapCreator and OsmAnd. Assuming you had a problem with Poland Silesian map of 03.03.2016, I've downloaded OSM dump of Zabrze of 03.03.2016, generated a map with MapCreator and loaded it into the OsmAnd. OsmAnd shows me 533 buildings for pl. Wolności.

Feel free to comment on this issue if have any questions.
