### ISSUE TITLE
Sometimes don't calculate the optimal route

### ISSUE THREAD

**Issue by naoliv** [osmandapp/Osmand#2585]
With osmand 2.4.0#12963D (but I saw it happening with older releases too) I am seeing a strange route result.

For example, while calculating a route from `-21.165123 -47.844086` to `-21.799028 -48.194436` in osmand I see:

![](https://cloud.githubusercontent.com/assets/982338/15471065/7258b750-20ca-11e6-8220-a0485babde9c.png)

While a reasonable route should be this:
![](https://cloud.githubusercontent.com/assets/982338/15471272/7c9f943a-20cb-11e6-8868-6c3103408060.png)

or this:
![](https://cloud.githubusercontent.com/assets/982338/15471275/810f9a6a-20cb-11e6-837b-72d04c7d749d.png)

I remember that osmand used to give one of these solutions.

OSRM route [is here](http://map.project-osrm.org/?z=10&center=-21.503547%2C-47.977295&loc=-21.165123%2C-47.844086&loc=-21.799003%2C-48.194414&hl=en&alt=0) for comparison

If I force an intermediate point it properly gives a good route:
![](https://cloud.githubusercontent.com/assets/982338/15471577/fabeb656-20cc-11e6-89d2-53bb3415939a.png)

Comparing with the route that it's calculating:
![](https://cloud.githubusercontent.com/assets/982338/15471585/0923286c-20cd-11e6-80fd-c2dcd79a8363.png)

It's possible to see that osmand is calculating a route that is both longer and slower.

I can't see anything wrong in OSM data (and we can confirm that there isn't any problems in the optimal route, since it's possible to use it if we create an intermediate point).

I am using the car profile with the fastest route enabled.
Avoid unpaved roads is enabled too.

**Comment by lvml** [comment]
(For similar issues see #2599 and #2509)

**Comment by vshcherb** [comment]
This issue is related to internals of how OsmAnd calculates route, there are plenty of places in Brazil where important  roads are disconnected from less important roads. For example, http://www.openstreetmap.org/way/171451138, tertiary connected to primary via small segment of residential. Many of these islands we try to fix by creating shortcut roads, though when road segments are quite long this approach doesn't work. And network graph is split by incomplete and independent road graphs and it leads to these errors. 

Disabling 2 iterations routing fixes the issue, though it makes routing considerably slower.
I would say in short term it will be easier to change the mapping rather than expect this issue to be fixed.
