### ISSUE TITLE
[Feature request] Give voice prompts to help get back to GPX track

### ISSUE THREAD

**Issue by annasoloviova** [osmandapp/Osmand#2591]
1. When a user wanders off the GXP track, they only get a voice prompt to get back. We should provide detailed instructions like if I make a left turn one street too soon, the app would say "you are off the route", "to get back on track, make a right at xxxx, then make a right onto xxxx..."  

2. Let skip a small section of the track. If providing detailed prompts is not an option, we can let users continue navigation along the track as soon as they get back on it.

**Comment by vshcherb** [comment]
Please test if we check option in GPX navigation settings (calculate OsmAnd route from beginning ) it works as Anna suggested.

**Comment by sonora** [comment]
@annasoloviova ; Anna, we have 3 additional settings appearing if someone choses to navigate along an existing GPS track:
(1) Revers GPX direction (not applicable here)
(2) Pass along entire track
(3) Calculate OsmAnd Route for first am last route segment (this is intended to "bridge" any gaps between start point and GPX track, or GP track and destination.

Un-checking (2) and checking (3) should actually solve the issue you are observing here, but I have to admit I have nave tested this in practice.

Please try this with your use case, and I will try to create one myself do the same as soon as I get a chance.

Thx - Hardy

**Comment by sonora** [comment]
I took a long test trip today(120km), scenario and findings are as follows:

**Scenario:**
I asked OsmAnd's offline router to calculate a CAR mode route from Point B to point F, it came out as follows:
- B is the starting point for this route for now, and is a point on a primary highway
- C is the point on this route where from the primary highway you enter a motorway
- C1 and C2 are 2 exits on this motorway near C, in the direction of D. No turns happen here, so these are on the route but not part of the route instructions 
- D is a motorway intersection where you change motorways onto a second one
- E is where you leave the second motorway
- F is the destination for this route for now

Now I saved this route `B2F.gpx` via OsmAnd's "Save" mechanism.

Then I physically went to point
- A, the "actual" starting point of my route.  A is in the relative vicinity of B.
- I asked OsmAnd to calculate a route to G, my final destination in the (relative) vicinity of point G.

Settings were:` "GPX route"=B2F.gpx`, `"Reverse GPX direction"=NO`, `"Pass along entire track"=NO`, `"Calculate OsmAnd route for first and last route segment"=YES`.

**Findings:**

- **(1)** OsmAnd correctly calculates a route **A-B-C-(C1)-(C2)-D-E-F-G**. (No turns at C1 and C2, only included for clarity here.) Notice the GPX portion of this route is B-...-F. So this finding is OK!
Now I deliberately left the route segment A-B and started an alternative (longer, off-route) way to reach C1.

- **(2)** OsmAnd correctly recalculated the route periodically to first send me to B.  This is OK.

- **(3)** Contrary to our "normal" behavior, i.e. when not including a GPX track in navigation, OsmAnd never played a "route recalculated" prompt on these occasions. I believe we actively suppress this prompt for routes involving a GPX track. This may be for historic reasons and we may lift this suppression if it is actually deprecated, it is a point for investigation.

- **(4)** No "You have been off the route...." is played either, probably as route-recalculation always happened fast, so I was almost always "on the route" (though not on its GPX portion at this point, of course!).

Now I approached motorway exit C1, where I can join the "GPX portion" of the whole route.
- **(5)** Interestingly, OsmAnd instructed me to enter the motorway in the "wrong" direction, i.e. first drive to point C (opposite to what makes sense here), there exit and re-enter to resume the entire C-G portion of the route. So there is little glitch here OsmAnd did not recognize it was more advantageous for me to enter the motorway directly in the direction of D.

I ignored the false direction and directly entered towards D.

- **(6)** OsmAnd produced an instruction to go until reaching exit C2, there exit, re-enter, go back to C, there exit and re-enter and resume C-G

I ignored this again, and finally when I was past Exit C2, OsmAnd acknowledged that I was on the right track and asked me to continue pursuing the route toward D.

Some time after leaving the second motorway at E, I deliberately took a wrong turn.

- **(7)** The route was immediately re-calculated, but not directly towards F, but rather "first back to point E". Again, no "route-recalculated" prompt (3), and also no "you are off the route" prompt (4), the latter probably since re-calculation always happened very fast.

- **(8)** Finally, when I was already closer to F than to E, OsmAnd re-calculated to skip E and only route via F.

So if we look at this,
- Findings (1), (2), and (8) document "OK" behavior
- For finding (3) we need to see if we cannot remove the prompt suppression we have GPX routes
- For finding (4) I am undecided: We seem to have no acoustic indication that you have actually left the GPX-guided portion of the route, because a re-calculation quickly happens and you are back in a (though not the original) route
- (5), (6) and (7) document that OsmAnd takes priority in routing you back to the NEAREST turn point on the GPX portion of the route (which may be the one in backwards direction), not recognizing that the NEXT (in forward direction) may be more advantageous even when it is still farther away. there may be an action item here.

- **(9)** Here is a finding on the side: In the GPX route files we produce with our very own offline router we do include tags like `<desc>Turn left and go A17 2.6 km</desc>`, but we fail to include the actual streetname/ref/dest etc. tags in a form our voiceRouter needs to produce turn prompts with full details as in "Turn left onto A22 towards Rome", etc. This could be a future improvement if desired.

**Comment by vshcherb** [comment]
(9) I can't recall why but I don't think we pronounce <desc> tags for turns, I think it will be useful but there were some issues and I can't recall them. It should be easy to include onto A22 towards Rome. If we go for this decision then we will use our VoiceRouter to generate text.

(5), (6), (7) I'm afraid it will be hard to improve or  I don't know the algorithm yet. Though we can always ignore some points after the closest but then we need to define how many so we don't end up OsmAnd routing instead of GPX :) 1km or more?

**Comment by sonora** [comment]
Regarding (9): Just pronouncing any odd `<desc>` text without knowing what it is and with what intention it was created could turn out a "grammatical nightmare" :)  But, yes, producing text + tags ourselves which can be re-read and used by our voice router in the same fashion our offline router produces fully-featured voice prompts should not be too difficult.

(5), (6), (7): I agree, not very easy. and maybe not worth for many use cases where GPX files are used (unlike in my long-distance test trip): Like city or hiking tours, where short distances between GPX route points will either not matter, or can be detected by simply looking at the map. The algorithm would likely be to calculate 2 new routes via the 2 closest point on the GPX route, then selecting the faster one. This would likely detect that in the vast majority of cases  the forward ("next") and not the backward ("previous") point on the GPX track should be targeted.

Any opinion on (3)? I think it may come from times when our GPX routing was way inferior (and following a GPX file sort of bogus-triggered a route recalculation all the time.), but changing it would need some testing.

**Comment by vshcherb** [comment]
I think (3) is supressed by mistake, cause now we say how far away the person is from the GPX route. So it might be interesting to hear recalculation as well.

**Comment by sonora** [comment]
I have removed the old restriction for (3), see https://github.com/osmandapp/Osmand/commit/4c88abff08c6dcdd9d56e730ba5866396f4fc93f.

I think we used to have this because without this restriction the prompt would have sounded continuously even while following the correct GPX route, and we did not have recalculation code for when using GPX routes anyway,

But maybe this is obsolete now, let's test.

**Comment by sonora** [comment]
I think the original issue is tested and works, small fix applied for the missing "route recalculated" voice prompt (3).

Issues (5), (6), (7), that re-routing does not evaluate if there is a "more forward" point on the GPX route to route you back onto, is a separate development story and not always significant.

Issue (9) is a finding on the side and relates to how we save our GPX routes to xml, respectively what data we could include to better use them also for voice guidance, but this is not related to this issue. We could potentially also include some traffic warnings etc. (see Issue #2843), but this would require a complete concept.

**Comment by sonora** [comment]
Researching (5), as a side effect of some other investigation:

Current algorithm is this: We find the **closest** point (often this is the perpendicular projection) on the GPX track to the start point (in nav mode: Where you are), and the route is calculated to **contain** that point. So if it happens to be only slightly "in the wrong direction" on the GPX track, when re-joining the GPX track OsmAnd first guides you in that "wrong direction", until the next turn point, then guides you back in the correct direction.

Sounds not impossible to fix, but in deed a better algorithm is not obvious. Maybe I find the time some day.

**Comment by vshcherb** [comment]
I think the situation that you are off the GPX route is already exceptional in sense if we get somehow to the GPX route , it is already good enough. In all other cases user need to use map and his vision how to get back to it. There is also an option "Calculate osmand route to the start and from the end of the GPX route" , which is useful in this situation

**Comment by sonora** [comment]
Yes, (5) is not a very pressing issue to fix for most users, and far from being high on my priority list to fix, too. Just wanted to record my findings here I had when fixing many things about our GPX route export this week, should I  ever want to come back to this. Please note that issue (5) is of course exactly observed when "Calculate first and last segment" is used.
