### ISSUE TITLE
Aldonu esperantan tradukon

### ISSUE THREAD

**Issue by verdulo** [osmandapp/Osmand#2614]
Mi petis antaŭe sed neniu helpis. Bonvolu aldoni al la programo Esperanton kiel elektebla lingvo por la fasado. La traduko estas kompleta en 70%, en la daŭro de kelkaj semajnoj mi eble finigos ĝin. Kial lingvoj ne estas ordigitaj laŭalfabete laŭ ISO-kodoj, kaj la angla estas unua? Bonvolu ankaŭ fari Esperanton elekteblan en 'Preferata lingvo de mapoj' agordo.

I have asked before, but no one helped. Please add to the program Esperanto (eo) as selectable language for the interface. Translation is complete in 70%, within few weeks I should finish it. Why languages are not sorted alphabetically according to ISO codes, and why English is always first? Please also make Esperanto selectable in 'Preferred language for maps' setting.

**Comment by sonora** [comment]
- I have performed a one-time maintenance on our language selection list (also in response to #2542), basically excluded all languages with no significant translation rate (<<5%), include all others, but marked the ones with <80% as incomplete. So Esperanto has taken the first hurdle, congrats!  :smiley:

- Sorting: There is currently no sorting code in our "Display language" menu, the languages are sorted statically by their English display name. While English is probably the most frequent language our users have set, there may be an action item here to sort that menu, hence I leave this issue open. (Sorting by ISO code seems not a good solution, because we do not display the ISO code on that menu.)

- The device's system language and English are always sorted to the top, I think this is common practice in many multi-lingual apps and helps many users find these two options quickly.

**Comment by sonora** [comment]
PS: On the occasion: I have also expanded our capabilities to now support locales of type language_country (commit https://github.com/osmandapp/Osmand/commit/5b97c0477c577c1ad68159875679feb2c0f776b7), so I could finally enable the selection of  locales like the different Spanish resource files (**es_US, es_AR**), traditional and simplified Chinese (**zh_TW, zh_CN**), Brazilian Portuguese (**pt_BR**) etc.

I also enabled Belarus (Latin) (**be_BY**), but I cannot seem to get this to work on my device, not sure if this is an Android issue or an issue with my western devices only.

The one language with reasonable translation percentage I have not yet enabled is Asturian, I believe there is currently still a general issue with Android's support for it.

**Comment by sonora** [comment]
Sorting also done: https://github.com/osmandapp/Osmand/commit/d79b56d5de90ec54ea9390651d2458848900c573

**Comment by verdulo** [comment]
Normal registered users on weblate for some time cannot start new languages. Could some "project manager" start Esperanto in "Phrases" pool please?

**Comment by sonora** [comment]
Should work now, right?

**Comment by verdulo** [comment]
Yes, it was temporary bug with weblate  with all projects (not only OsmAnd) - now "New translation" box is available again.

**Comment by verdulo** [comment]
One more problem: why the word "Cancel" in many parts of the program in Esperanto is not translated? For example in Settings=>Default profile, I see "Cancel" instead of "Nuligi", while in Polish version I see it correctly translated ("Anuluj").

**Comment by sonora** [comment]
Strange .... @vshcherb  Would you have an idea? It seems that e.g. Belarusian behaves the same ...

**Comment by vshcherb** [comment]
I think it is more Android runtime issue. The only dialog like that I found in OsmAnd Settings, there it is used based Android system dialog not OsmAnd one.

**Comment by sonora** [comment]
Yes, I think so, too, cannot find any issue in our code. Looks like it may some issue with language support in Android for certain objects...
