### ISSUE TITLE
Find more intuitive way to showcase the context menu's zoom-in / hide-menu / hide-menu-and-map-marker actions

### ISSUE THREAD

**Issue by HolgerJeromin** [osmandapp/Osmand#2633]
When I click an poi from the search the small info is shown. Very nice. 
But often I want to know where exactly  this poi is. But I have no zoom buttons. I have them when I swipe the poi info down, but then the target marker is gone, too.

**Comment by sonora** [comment]
It actually works like this::
1. Swiping down the context menu will make the marker disappear
2. Tapping on the map will make the context menu disappear but keep the marker
3. Tapping on the point name on the context menu will make the menu disappear and zoom in on the point

I am aware tha1 1.-3. are not very obvious, not sure how the discoverability of this could be improved?

**Comment by HolgerJeromin** [comment]
Clearing the marker on down swipe annoyed me. 
But otherwise clearing the marker would be not easy to implement...

**Comment by sonora** [comment]
I guess from the viewpoint of "intuitive" or "discoverable", (2) is ok, (1) is already a big hurdle for many users, and (3) is often not discovered at all..

I copy @vshcherb  here to get this more attention, it is probably one of the major usability issues we currently have to solve a bit better.

**Comment by HolgerJeromin** [comment]
I always did (1) and did not discovered that (2) would give another result. :-)

Related: I think the default zoom level is too low after clicking on a search result. But this can be influenced by the small village i live now :-)

**Comment by sonora** [comment]
Regarding the default zoom: What we currently test is this idea: The default zoom initially taken when displaying a search target is chosen dynamically so the point you searched fits on the map together with the actual position you are at.  This means that on the first screen you will see both the search target (in the middle of the screen, maybe we should chose the edge...) together with your own position, so that you can judge where the target is relative to your position, and how far away. A subsequent tap on the context menu will then zoom in to the point's neighborhood.

To me this is a useful procedure, essentially meaning if you search for something 100km away, the initial zoom level is far out, but if you search for something 100m away, you would immediately get your "neighborhood map" from the start.

It is a way to leverage that the app has knowledge of where you are and how far from your search target, something a paper map could not preform.

**Comment by HolgerJeromin** [comment]
Sounds good!

**Comment by sonora** [comment]
@Victor: I think in order to make the zoom behavior clearer, and also use more of the screen, we should in stage 1 not position the search target in the middle of the screen (this always "wastes" half of the map screen), but use the approach we use when a route calculation has finished: We zoom and pan so that he whole route fits on the screen. For the search operation those would mean that your position is near one end of the screen and the target at the opposite. Then only after tapping on the context menu the map marker gets moved to the screen center and zoomed in upon.

**Comment by vshcherb** [comment]
By using that feature for couple months and discussing with others, I think there are definitely positive aspects and negative. Discussing with 3-4 people I put for now min zoom of 11 to zoom out, in order to keep balance how much to zoom in and how much overview to give.

**Comment by victor** [comment]
I'm sorry, as a former TomTom contractor I'm under NDA and forbidden to participate in this kind of projects.

**Comment by sonora** [comment]
Apologies, @Victor, the at-mentions applet seems to have picked the "wrong" Victor.  :)

**Comment by victor** [comment]
Ah ok, that makes sense. Never mind then.

**Comment by sonora** [comment]
Looks like no further action planned here.
