### ISSUE TITLE
Locations folder

### ISSUE THREAD

**Issue by BengaloBongali** [osmandapp/Osmand#2636]
Wouldn't it be a good idea to put favourites in a seperate and prominent folder (on the internal storage) that sits next to `Downloads`, `Music`, `Pictures`,...?
I imagine the further structure like this: `/Locations/group1/favourite1.gpx`
This folder could be easily managed in a file explorer to copy groups or favourites and it could be easily synced with tools like `Syncthing`. It could even be used by other apps like `Maps.me`.

**Comment by sonora** [comment]
Personally, I think it is not a good idea to try to "behave" like a "system app", it is probably "cleaner" to put all data in the app's native data folder (and its subfolders). The way Android has been developing in recent years, these folders were the only ones consistently available for write access on all storage media. I am afraid any other folder we may decide to use may become unavailable at any point.

There is no objection to use a separate folder, but since we store all favorites in a single xml it seems overkill to use a folder for this?

**Comment by BengaloBongali** [comment]
> There is no objection to use a dedicated sub-folder "Favorites", but since we store all favorites in a single xml file it seems overkill to use a folder for this?

I think for syncing and management it would be better if they were stored in different files and folders as I suggested. Would that be difficult to do?
And even if that can't be changed, most syncing tools sync folders, not files, so a sub-folder would be an advantage already.

**Comment by BengaloBongali** [comment]
*reopens*
