### ISSUE TITLE
Broken regions.ocbf not detected / automatically re-downloaded (pt 2)

### ISSUE THREAD

**Issue by noci2012** [osmandapp/Osmand#2651]
The complete discussion is in issue #2639   (pt 1) which i cannot reopen.
So here is a new issue as promissed there.

**Comment by tbnorth** [comment]
+1

Seems like I have exactly this issue.  OSMAnd *does* report the corrupted file on startup.  But I can't delete it.

Could it be that it will only re-download itself on Wifi, not cell service?  No reason to think that except OSMAnd is polite enough to ask if you want to use cellular data to download maps, and I probably haven't tried starting OSMAnd with wifi coverage since this happened.

I'll experiment more when I have wifi, but don't want to root the phone just to fix this.  I can see the file in a file manager, but not delete or rename it.

**Comment by vshcherb** [comment]
You can reinstall the app and it should help.
