### ISSUE TITLE
Navigation: "Route Recalculated" voice delays other important voice commands

### ISSUE THREAD

**Issue by fho** [osmandapp/Osmand#2658]
It happens often that when I'm using OSMAnd for bicycle navigation, that I miss to turn at a junction because the "Route Recalculated" sound file is played and delays another sound file that informs me to turn.

Possible solution could be to:

- Interrupt the "Route recalculated" sound when another more important soundfile has to be played
- Ensure it's only played when no other commands have to be played in the next X seconds

**Comment by sonora** [comment]
I wonder why "Route recalculated" is played in the first place. Are you actually off route when these situations occur? Because we had a small bug with this, fixed in nightlies, but not yet in the release version. Which one are you using?

**Comment by sonora** [comment]
PS: A very quick fix I could implement could be to shorten the prompt to just say "Route recalculated" in bicycle mode also, like we do for the car profile. This should not take more than 2 seconds in most languages, and may solve the issue?

**Comment by fho** [comment]
II'm using OSMAnd+ from the google play store, version: "2.3.5, released 2016-04-28".

Yes, it happens that I get off the route, mainly because I misunderstood a turn command from OSMand.
Than it recalculates the route, I'm at a junction, have to turn immediately but it first plays the "route recalculated" sound.

I'm using the german speech output. The output is longer in german than in english "Die Route wurde neu berechnet" it could be shortend to "Route neuberechnet".
But 2 seconds is often already too long. The turn voice output is sometimes played very late, when the turn is 1-2m ahead.

**Comment by sonora** [comment]
Ok, I have shortened the German string to "Route neu berechnet, ...", so this will help a bit :smiley:

I am wondering if you do (in bicycle mode) not always also hear the "Die Entfernung beträgt " and "time needed" announcement immediately behind it, and if this is not your real problem?

I would have though behavior is like this:

- CAR mode: "Route recalculated."  (We suppress the details here)
- BICYCLE mode: "Route recalculated, distance is 5 km, time is 12 minutes"  ?

**Comment by fho** [comment]
Cool, thanks a lot for the fast processing! That could improve it:-)

No, I think I never hear the distance and time announcements

**Comment by sonora** [comment]
If, after a route recalculation, you do not hear the German equivalent of ", distance is x kilometers, time is y minutes", I think you must have calculated the route for car and not for bicycle?

(As I say, we could drop this, like we currently do for the CAR mode, but the point in having it is that some bikers and hikers may really be interested in how their travel distance/time changes when they embark on the alternative (new) route?)

Regarding your idea to suppress the entire "Route recalculated..." prompt if there is a turn prompt due: I am a little hesitant to do this, as this is the only acoustical indication that you have actually left the first (potentially better) route. And there can be situations where people would want to turn around rather than accepting a potentially much longer route. So not noticing that you have just left what was originally calculated and suggested could be an issue, or not?

**Comment by Barrocas** [comment]
Agree with Hardy, don't supress it.

and I also noticed that for Car mode that first  "Route calculated..."
and ", distance is x kilometers, time is y minutes" is now missing, I
even wondered if it was intencional or a bug, now I see that it was
intencional.

Why so much picking on the 'chattiness'?
We are supposed to start a new route before we start travelling, so it
was harmless to have that first chattiness route description.
I liked those first sentences, they informed us of what should be
expected from our planned trip, so we could hear if it corresponded to
what we intended, and it also assured us that the TTS was working.

Now everytime I start a new route, I have to look at Osmand and touch
it to check the route, see if it's working and routing correctly, if
the TTS is working (in the past, sometimes it failed), all that
because it doesn't speak to me no more, like it used to... :p

-- 
Cumprimentos,
D.er Hugo Barrocas

**Comment by fho** [comment]
> If, after a route recalculation, you do not hear the German equivalent of ", distance is x kilometers, time is y minutes", I think you must have calculated the route for car and not for bicycle?

Sorry, I was wrong, the announcement is played on route recalculation for me. 
Like you also wrote, it is helpful. Sometimes  I miss a turn and the new calculated route is much longer. The distance announcements than makes me turn and follow the old route again.

I agree, shortening or omitting voice announcements is only a hack to fit the problem.
A better solution could be:
Informational announcements ("route recalculated", new distancen..") are delayed when it's playback would delay an announcement that requires an immediate action (~"turn left in <= X m").

Maybe it can be predicted, with the help of the current route and the current movement speed if an action announcement has to be played in less than $INFORMATIONAL_ANNOUNCEMENTS_LEN_SEC. If it's the case the informational announcement would be delayed until a big enough time slot becomes available

**Comment by polarbearing** [comment]
I don't think it is feasible that the app knows the length of an announcement, since that depends on the language-specific TTS file and the voice engine in Android. 

But categorising announcements according to their priority might be possible, and queueing them accordingly.

**Comment by sonora** [comment]
Yes, a prioritized queuing of prompts is possible, we already do this for e.g. traffic warnings, where often several can occur simultaneously, and clearly some are more pressing than others. (But I think also there we then drop the less-important prompts, and we all seem to agree here that we should likely not drop, but at most delay "route recalculated" in favor of a turn prompt.)

How difficult this is to implement for the "Route recalculated" case reported here I cannot say off hand, would need to investigate. So far my impression was that this is not an extremely frequently occurring issue and not worth the effort and complications, but maybe I am mistaken.

@Barrocas : The suppression of time and distance in CAR mode has been around for years. I think this came about because by car you may in frequent succession pass many turns you maybe intentionally do not want to take, like in a residential area, and the hearing the long version of the "route recalculated" prompt every 10 seconds or so is a nag.

But this CAR-mode  omission of distance/time is strictly limited to the route **RE**-calculated prompt! The initial "The trip is..." (or in many languages a little longer: "Route calculated..." without the "re-")  should always come complete with distance and time needed(??), just like you say, as an initial confirmation that things have happened and are working.

**Comment by Barrocas** [comment]
1 - 'Route recalculated' does indeed not have the distance and time spoken
by TTS, but I wasn't asking for it, and I agree with you, keep it simple.

2 - What I noticed is that the initial 'Route Calculated' with distance and
time is missing in the latest builds.
I was wondering if it was intencional, since we have been cutting off the
chatiness, but if that's not intended, then something is wrong either with
Osmand night builds or PT-TTS files.
I also noticed some 'prepare for...' sentences are gone (sorry, going
off-topic)?


-- 
Cumprimentos,
D.er Hugo Barrocas

**Comment by Barrocas** [comment]
Correction - Just installed the latest build and the initial announcement
is working as expected. Either it was some temporary issue or related to my
other phone.

-- 
Cumprimentos,
D.er Hugo Barrocas

**Comment by fho** [comment]
Why was the issue closed?

That the "route recalculated" announcement delays turn announcement can still happen, also in the latest build, can't it?

**Comment by sonora** [comment]
It was my impression from the discussion above that we find no solution to improve these situations without unwanted side effects?

**Comment by fho** [comment]
I'm sure there are solutions for the problem. It doesn't seem to be an impossible to solve issue. :-)
Another idea:
Pause/continue or abort and replay the reroute announcemen when a turn navigation comes up to be played

**Comment by sonora** [comment]
Not worth the hassle, if you ask me.  If I left the route, I want to know **that** immediately, and you could argue this is the higher priority prompt than taking me on turns on the new route. :smiley:

**Comment by fho** [comment]
I agree for other it could be more important to be notified about the route recalcuation.
Good argument :-)
