### ISSUE TITLE
More intuitive search (like OpenStreetMap) / help with search

### ISSUE THREAD

**Issue by bjohas** [osmandapp/Osmand#2706]
I often struggle to find locations in OSMAND. The main proposal is to review the search, and create an OSMAND default search that is simpler. E.g. with http://www.openstreetmap.org/, I can just type in what I want to search for, and get a list of results, from OpenStreetMap Nominatim and GeoNames. 

In OSMAND, at least when you're online, there should be a simple option to type, search, and find. One issue is that as soon as you type into the search box, you're presented with 
"Search by name"
"Online Nominatim - Places"
"Online Nominatim - Address"
and it's not clear what these do (to the non-expert).

Another issue is that even after searching in OSMAND, you still have to tap "find more" to find results. If you search (e.g.) for a major capital city, that doesn't really make sense.

Clearly, the "POIs search" (partially a "browse") is very helpful, as are "address", "location", "favourite", "history". Maybe a "help screen" could be added in the short term, to help users find their way?

What do people think? I'd be very happy to have a chat with the developer for this feature, to see whether are better "information architecture" could be found...

**Comment by bjohas** [comment]
https://github.com/osmandapp/Osmand/issues/2623

**Comment by sonora** [comment]
Parts of this are already fixed, others currently in the works, please wait for the next release.

**Comment by bjohas** [comment]
Hello @sonora ,
I'm on the latest nightly... however, I can't see changes regarding to search...?
Thanks!

**Comment by sonora** [comment]
@bjohas: Some things are already in the nightly build, like 
- City/street search is significantly sped up with latest nightly and new maps, because we better sort the search index now
- Villages are searched automatically now (without tapping "Search villages / post codes"), if you specified a place (or a post code) and it s not found in the "big cities" list
- POI and searchByName search does not get "stuck" anymore when cancelling it, then going back and re-starting a new search

A new "google search" type textual search box is not yet in the nightlies, as still under development in a separate branch.

**Comment by bjohas** [comment]
@sonora - many thanks! I'm happy to discuss if the developer is interested!
