### ISSUE TITLE
Adding Sorbian language to display languages

### ISSUE THREAD

**Issue by annasoloviova** [osmandapp/Osmand#2714]
We already have some regional languages in the options. Users request adding Sorbian and are ready to assist if needed. https://en.wikipedia.org/wiki/Sorbian_languages

**Comment by sonora** [comment]
Ok, I have generated the 2 empty resource files, so people can start translating.

I am not sure how well or if at all this is supported, e.g. in Android. One https://hosted.weblate.org/projects/osmand/main/ the ISO 639-2 code 'wen' does not seem recognized, It is reported at the bottom of the list as "wen (generated". But I assume translations contributed there should make it into our code repository ok.

**Comment by juliannyca** [comment]
Hello! "wen" is a language code for a non-existing languages. The correct codes are "hsb" (for Upper Sorbian, which I requested) and "dsb" (for Lower Sorbian). Both have for example Wikipedia projects. My original intention was to enable hsb as map language, since the whole area of Lusatia has been mapped in this language during the past five years (see www.karta.luzica.la for the map). It would be good to let people use the results also on OsmAnd.

**Comment by sonora** [comment]
Changed ISO 639-2 code from wen to hsb.

**Comment by juliannyca** [comment]
Thanks! As I see I made a mistake uploading the so-far-made translations to the matrix, so that there are now also strings, which haven't been translated so far (the yellow ones). Is it possible to delete those?

**Comment by sonora** [comment]
Not sure how. If you want, I can empty all translations again, so you could upload again.

**Comment by verdulo** [comment]
1. The user juliannyca probably wanted to add both languages as "Map language".

2. All languages with 3-letter codes: Asturian (ast), Uppersorbian (hsb) seems to be not working (all text is in English).

**Comment by sonora** [comment]
Ad 1: In order for something to be made available as "Map language", there should be enough global coverage of OSM elements with names in that language, which is mostly not true for rarely used languages, and hence pointless. 

Ad 2: Yes, I think it is an Android issue not supporting 3 letter iso codes, at least not on any of the devices I have tested. I think I implemented everything by the book, but I cannot get it to work either. Maybe newer devices already work, or maybe Android will fix this in some future release, I have seen Android bug reports about this.

**Comment by juliannyca** [comment]
Hm, doesn't sound good. For Ad 1: Of course there is only names in that language in the area, where the language is spoken. That's the same with Breton or Welsh, which are nevertheless "map languages". The non-support of 3-letter-codes is of course a bigger problem.

**Comment by verdulo** [comment]
Ad 1: Here: https://taginfo.openstreetmap.org/keys/name:dsb and here: http://mlm.jochentopf.com/ you can see coverage of translated names, both Upper- and Lower- Sorbian have more than 1000 of values; in comparison to Cebuano, which have only 224 values. Even Kashubian (csb) have more values (285) and Silesian (szl) - 385.

@juliannyca Ad 2: You can use languages with 3-letter codes as map-languages, but you cannot use them as display language (for the program), probably because of bug in Android itself.

**Comment by juliannyca** [comment]
This is sad to hear, but then it would be nice at least to enable hsb as map language in the near future. For the display language we have to wait for Android bug-fixing then. It's a pity I didn't know that before I started translating :D Never mind.

**Comment by sonora** [comment]
(1) Cross reference: #2770, Let's have a decision from Victor there.

(2) Cross reference to 3-letter-locale Android Issues:
- https://code.google.com/p/android/issues/detail?id=49120
- https://code.google.com/p/android/issues/detail?id=106574

**Comment by sonora** [comment]
Ad (1): added.

**Comment by juliannyca** [comment]
That means it's coming?

**Comment by sonora** [comment]
Yes, I implemented in our nightly build, it should be in the next release, too.

**Comment by juliannyca** [comment]
Great! Thanks a lot.

**Comment by juliannyca** [comment]
Seems as if it wouldn't work. I chose hsb as map language, the names stay as they are. I zoom in, nothing changes. What's the mistake?

**Comment by sonora** [comment]
Can you please open a new, specific issue report specifying some OSM examples, specify what you expect to see and actually see., so I can reproduce Thx.
