### ISSUE TITLE
 [Feature request] Wikivoyage POI

### ISSUE THREAD

**Issue by DFyson** [osmandapp/Osmand#2716]
For travellers, having Wikivoyage (or maybe wikitravel) would be a great addition, similar to wikipedia POI where the article can be read offline in OsmAnd. Currently the only options for offline are Kiwix or Aard2 but they don't have a map. Currently the entire offline database without images is <100MB.

**Comment by jaduncan** [comment]
This would make me very happy indeed.

**Comment by vshcherb** [comment]
Yes it is in our plans

**Comment by elgaard** [comment]
I Agree. Osmand and Kiwix+Wikivoyage (there is also a special app for this) is already a great combination.  You can click on POI listings in Wikivoyage and they open in Osmand.

However you only get the position in Osmand. If you bookmark it in Osmand the WV listing data is not transferred.

It would be nice if there could be two-way mapping between WV and Osmand POI's. So that if you open a listing from Kiwix/WV in Osmand you get the right object, that you can bookmark. And that you could click an Osmand WV POI and have it open in e.g. Kiwix on the right page.

This will also be great for searching. In Osmand, if you go for a drive without any particular plan for the day and search for tourist attractions and sightseeing in a 100 km radius, you get thousands of POI's, most of which are unnamed places of worship, boring monuments, and public toilets.

I usually search for Wikipedia articles for this. Wikivoyage would be much better.

**Comment by sonora** [comment]
Looks like to finally achieve what is being requested here, we now need something like #5445.

**Comment by vshcherb** [comment]
Yes, Great News 2 years and we are there.

**Comment by vshcherb** [comment]
Unfortunately we don't have any really crowdsource review wiki's about places (restaurants, museums). Let's see when it will be created
