### ISSUE TITLE
Route calculation is incorrect for part of E28 road on Lithuania-Belarus border

### ISSUE THREAD

**Issue by n0vice** [osmandapp/Osmand#2729]
Issue has been originally posted in Osmand google group: https://t.co/sYEppJwGS8
More details could be found in group discussion.

When calculating route from Belarus E28 road to Lithuania E28 road, it refuses to go through Kamenniy Log-Medininkai border crossing which is also on E28 road, but leads through another border crossing instead.

Start point: Lat 54.51271, Lon 25.8711
End point: Lat 54.55963, Lon 25.65659
Navigation service: OsmAnd (offline)
Transport: by Car
Map source: OsmAnd downloaded offline vector maps (for both countries)
Route settings attached. Avoid roads setting is empty.
App: Osmand+ 2.3.5
Device: Nexus 5, Android 6.0.1
![screenshot_20160427-115342](https://cloud.githubusercontent.com/assets/1525601/16197095/66f8f1ea-3709-11e6-83dc-6b9448e29dd9.png)
![screenshot_20160426-140510](https://cloud.githubusercontent.com/assets/1525601/16197096/66f9b648-3709-11e6-9097-5cd98066725a.png)

**Comment by vshcherb** [comment]
That's a very bad issue happened because of OSM data mapping.
The way was tagged with maxspeed:practical=1  and OsmAnd uses this tag 
<select value="$maxspeed:practical" t="maxspeed:practical"/> for routing.

The OSM was already fixed and next map generation it will function correctly. Which will be next week.
