### ISSUE TITLE
Osmo plugin prevents shutting down OsmAnd

### ISSUE THREAD

**Issue by noci2012** [osmandapp/Osmand#2734]
Observed today that OsmAnd would not stop ( and close/stop Location ) when OsMo is still active.
Even when the app is requested to close. 

I didn't expect to need to first manually stop OsMo before OsmAnd would stop.

**Comment by vshcherb** [comment]
OsMo service is running in background especially if you transmit your location and it is implemented by design. On the other hand OsmAnd will be still visible in running processes because of it. Though system will kill OsmAnd once there is not enough memory. Please keep in mind that OsMo connection is still open and you get updates for your groups.

It is both implemented by design, though I think it will be nice to change it one day to normal process. 
Workaround to use: OsMoDroid separate app for OsMo.
