### ISSUE TITLE
Routing confused when traffic light is present

### ISSUE THREAD

**Issue by james2432** [osmandapp/Osmand#2737]
![tmp_31649-screenshot_20160612-160150-104812339](https://cloud.githubusercontent.com/assets/498547/16230093/da65ee7e-378d-11e6-8328-589276ee91bc.png)
I know the routing is based upon a point system, but when there are branches in the road(to turn) in a 4 way stop with a traffic light present: the routing will have you skip from branch to branch instead of going straight. This can be confusing as it says turn right and might take you down the wrong street, if you arent looking at the screen. The screen shot was taken of 10th line road in Ottawa, Canada.

**Comment by polarbearing** [comment]
Found a 10th line road in Orleans, near Ottawa. Would be good to provide an OSM link, [such as this](https://www.openstreetmap.org/node/1017337858). And note the screenshot is pointing south up.

If it were allowed, it would probably be indeed the better route since you bypass the lights. 

However, from Bing it looks that Tompkins Av has a through white line in the middle where the link roads join, so you can add a turn restriction. I have done that as an example. 

On the opposite site of the junction the link was not drawn correctly in OSM, it joins the Charlemagne Blv in a different point that it leaves, corrected now. Again white lines, added turn restriction. 

If there are stop signs posted, you might add them to the appropriate roads, however we would need confirmation from the developers if stop signs create route penalties already?

Added some turn:lanes as well.

**Comment by james2432** [comment]
Orleans in a suburb of Ottawa and not a city on it's own. You shouldn't be obligated to post a turn restriction as you are not allowed to go from turning lane to turning lane

**Comment by polarbearing** [comment]
> Orleans in a suburb of Ottawa

I don't mind. I was just wasting time to search in core Ottawa since you did not provide a link.

> as you are not allowed to go from turning lane to turning lane

How should OsmAnd know about that, as long as they are connected in a valid graph? If there weren't the white line, I doubt there is a law in Canada forbidding to drive along link roads.

**Comment by james2432** [comment]
https://www.ontario.ca/laws/statute/90h08#s141s2
You must follow the lines in your turning lane, there is a white solid line demarking that you must turn to your right, past the other junction, so you would have to do a u-turn to go grab it.

**Comment by polarbearing** [comment]
I just told you that I now have encoded the meaning of the _white solid line_ as a turn restriction into OSM. OSM cannot know about the white lines in your physical world, unless you tell it. 

The area we are looking at has roads which appear to come form an import from "CanVec 6.0 NRCan" according to their source tags. That means they would need a lot of work to align them to reality, and to add necessary restrictions and permissions.

**Comment by polarbearing** [comment]
The underlying OSM data issue for the reported case has been fixed. There might be more problems with similar junctions in the area that need the attention of a local mapper, however that is not an OsmAnd issue, can be closed here.

**Comment by scaidermern** [comment]
> If it were allowed, it would probably be indeed the better route since you bypass the lights. 

Yes you pass the lights but you still cross an intersection. Also the route leads over highway=secondary_link instead of highway=secondary. And it is slightly longer. The whole combination *must* be slower.

Looks like the speed/penalty calculation could be improved. Maybe the penalty for traffic lights is too high. Or the speed for secondary_link is not lower than for secondary.

**Comment by vshcherb** [comment]
IMHO It is just 20meters longer and link has speed > 30kmh so it is definitely faster than 30 seconds on traffic light.

**Comment by scaidermern** [comment]
That depends on the other penalties. If the penalty for a traffic light is 30 seconds then what is the penalty for crossing an uncontrolled intersection? IMHO a penalty for traffic lights only makes sense if there are penalties for other intersections, too.

**Comment by aceman444** [comment]
As said, if there is a stop sign or a give_way sign on that intersection, it should get mapped. Then OsmAnd can do proper decisions. If there is no sign, you may try increasing the leftTurn value in the car profile in routing.xml.

**Comment by vshcherb** [comment]
The issue is fixed even without adding turn resctrictions

**Comment by aceman444** [comment]
So how was it fixed?

**Comment by vshcherb** [comment]
https://github.com/osmandapp/OsmAnd-resources/commit/404843d932fd32ff052877872d3536e8ed370d3e

**Comment by travnick** [comment]
Just a note about finding something **definitely** obvious and clear.

> IMHO It is just 20meters longer and link has speed > 30kmh so it is definitely faster than 30 seconds on traffic light.

Since you stop on the red light, then it means the other vehicles are passing the road from the other direction.
So how it's possible on a busy way to be faster while you have to wait for an empty road to cross it?

As a result it's **definitely** not definitely faster. It may be faster but in my opinion in most cases it would not - depending on the road conditions. See busy roads in crowded cities, where such a maneuver is prohibited by road signs.

**Comment by aceman444** [comment]
@travnick: as already said earlier, OSM database and Osmand can't know if you have to "wait for an empty road" until you tell it with the right means: a turn restriction relation of give_way/stop signs in the OSM data. OsmAnd can't do realtime analysing of complex intersections with the limited knowledge there is in OSM data, and guess what road is "busy", where it "maybe" needs to wait etc, if the mappers forgot to tell about signs, restrictions, traffic lanes and solid white lines.
