### ISSUE TITLE
Usability: Simplify our Route Setup (once again)

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#2765]
OsmAnd recently came out 5th place of 5 tested free smartphone navigation apps in a big computer magazine. When scanning their results, it seems this is almost entirely due to what they call "awkward usability".

I have discussed this with a colleague, and the findings are as follows:

(1) On the "Route setup" screen,  after "From:" and "To:" are selected, there is no obvious way for a user to add intermediate destinations. google maps e.g. offers an obvious "+" sign to enter more destinations.

(2) On the "Route Setup" screen, we fork to a second screen "Waypoints" via the "flag" button. Only this second screen offers basic functionality like changing the order of destinations. We strongly believe these 2 screens need to be collapsed to one screen, combining their functionality.

(3)  On the "Route Setup" screen, we are still missing functionality when selecting or changing the "From:" or "To:" locations (future also "Via:"): The pull-down menu offers to select from Favorites, Select on map, or Address search, but we should offer **all** search mechanisms.

(4) Our map screen is missing a "Search" button: The **primary functionality** of a navigation app is hiding behind menus or other clicks and taps!

Looks like with these measures we could align our UI with what most users seem to expect and how other apps conventionally offer it, while still preserving our wealth of functionality (which is often superior to other's.)

**Comment by raindropsfromsky** [comment]
I agree. The GUI is unnecessarily complex; and multiple windows are used without any purpose.

IMHO the single-window design I proposed is the best solution.
In fact, the new Google App with multiple waypoints seems to have that exact GUI!

**Comment by sonora** [comment]
There is always a conflict between crowded combined screens or multiple more simple screens. My test user group seams really concerned about having to change screens not knowing how to "come back". I was surprised, but that's the lesson I am learning here ...

**Comment by raindropsfromsky** [comment]
Well, try this: Set a journey with at least one waypoint. Now try to forget that journey, and plot a new one. 

A basic functionality is missing!

**Comment by vshcherb** [comment]
(1) It is hard to say that's most important thing cause GMaps for a long time didn't have intermediate points at all. Might be a combination of (1) and (2) makes sense.
(3) I think we are coming to a point when we need only 2 features - Select on Map (I don't know how to express it via Search) and Search + possibly (My location)
(4) Deprecated :)

**Comment by vshcherb** [comment]
To summarize it we have 3 screens that influence on navigation, first simplified and we might be missing features to add waypoint (later to delete and  change the order), second focused only on waypoints and passing poi etc, third pure settings. One of the main challenge combining 1nd and 2nd, that we should leave the place for map where we display the route. 
So I don't think we will be talking about of combining these screens into 1, instead we are talking making the transitions seamless. In GMaps there are lots of transitions, pull-up, hidden clicks and so on. To be honest it doesn't make UI more comprehensible either.

**Comment by sonora** [comment]
Fully agree, conserving space is the main concern when combining the 1st and 2nd screens.

Regarding (1) and (2), I think the user feedback was mostly targeted at basic destination manipulations like changing the order of destinations (via swiping) or finding some obvious "plus" button to add intermediates, without having to go via more "obscure" buttons like the flag icon.

I guess if the additional functionality like Waypoints could remain more hidden by default, perhaps we can think of a way to show this "collapsed" on that same screen so it would by default consume little or no space.

Regarding (3), yes, "**My Position**" (only for From), "**Select on Map**" and "(Quick) **Search**" will suffice. I would also leave the "**Favorites**" in place as they are today because Favorites is a shortcut functionality, so users may appreciate seeing it here.  So essentially we are simply talking about replacing today's "Address..." by "Search" and pointing it to Quick Search, which could even be something we still want in the 2.4 release to better promote our new feature?

**Comment by raindropsfromsky** [comment]
I have a related suggestion:

The **"Find POIs along the route"** concept should have two different variants:
1. During the route-planning stage, show all POIs along the route, and let the user select only 1-2 POIs as waypoints.  Hide the rest of them. 
2. During the actual navigation, let the user toggle a similar list of POIs. But in this mode, OsmAnd announces all POIs as they come up, and the user can pick a POI and break his journey to go there. Once his need is satisfied, he can turn off the "find POI along the route" mode.

*****
So, to adopt the GUI to variant#1 above, it needs the following changes: 

Currently, when we select a POI type (e.g. cafe+restaurants), the OsmAnd shows a huge list of POIs. But in the route-planning stage, the user needs only 1-2 of them. So he has to delete most of the POIs one by one. This is tedious. Instead, provide a check box against each POI, so that only selected POIs are added to the route.

In fact, it is virtually impossible for the user to select any POI using the list. Instead, it is far simpler if the user looks at the map, picks his POIs and adds them to the route by long-pressing on them.

And here we face the next issue: The map screen shows all POIs of the selected type everywhere. It should show only the POIs that are listed in the screen#2 (i.e. POIs that are within a certain distance of the route). 
******
For variant#2, just provide the **quick search** button in the navigation mode, so the user can select a POI type, or search by name. But in navigation mode, this button should show only POIs that are within a certain offset from the route, and filter out the rest.

**Comment by vshcherb** [comment]
The design phase is finished and the implementation will start after 2.5 release.

**Comment by dertuxmalwieder** [comment]
re:4:

> (4) Our map screen is missing a "Search" button: The primary functionality of a navigation app is hiding behind menus or other clicks and taps!

It *might* be interesting to extend the "Address..." menu item in the Route menu, so I can enter the name of (e.g.) a restaurant *instead* of an address and OsmAnd will do the rest.

**Comment by sonora** [comment]
In fact I think this is implemented: Using the "Address" entry on that menu takes you to our regular Search screen, and from there you can search anything, no just addresses.... So it is all there, only our menu setup and maybe menu wording is a bit awkward.  :)

**Comment by dertuxmalwieder** [comment]
I tried that in Cologne, the Address screen did not find any café.

**Comment by sonora** [comment]
"Address" puts you on the address tab of the search screen, did you switch to tab "Categories" before searching`?

**Comment by dertuxmalwieder** [comment]
... Ouch.

Just pretend that I wasn't here.

**Comment by matthijskooijman** [comment]
Looking at the route setup screen as it is now (OsmAnd 3.7.4), it seems that all of the points in the original issue have been fixed, and some of the follow points too (though the redesign of the route setup makes it hard to tell what the original problem was for point 5/6).

I think the route setup as it is now is quite good, and this issue can be closed (keeping it open does not seem helpful, as it does not really have any actionable items anymore). Anyone with access care to close it?
