### ISSUE TITLE
Store map files in a separate folder

### ISSUE THREAD

**Issue by rododevr** [osmandapp/Osmand#2771]
This is a request to store the downloaded map files in a separate folder. Initially, this could be a subfolder of the main Osmand folder, just like for example the tracks folder, but the location of this folder should be changeable in settings -> general settings -> map storage folder (instead of data storage folder).
The reasons for this request are:

1) Many devices don't have enough storage capacity for the app plus all the map GB's in internal memory. With this change, the app itself and other small data files can reside in internal memory (for speed), while the big map files can reside in the external sd card.

2) This allows users to share the map files of Osmand Free and Osmand Plus.

**Comment by vrtareg** [comment]
Hi

This is already there.

If you got external SD card you can move all files there.

You will not be able to share same folder as from one of the Android 4.X
versions it is disabled by design.

Each app shold use it's own place not accessible by other apps.

And last if you got paid one why to keep free one?

I have got paid one and reporting any problems on it and fix will be
applicable for both of the versions.


Regards,

Areg

**Comment by rododevr** [comment]
Hi Areg,

>> If you got external SD card you can move all files there.
That's exactly the problem. If I move ALL files there from the Free version and the Full version, the settings files conflict.
I only want to put the MAPS files in a shared folder.

>> You will not be able to share same folder as from one of the Android 4.X versions it is disabled by design.
So this asked for symbolic links. (I use FolderMount, but there are several similar apps). 

>> And last if you got paid one why to keep free one?
I use the Plus version to navigate, but the Free version to browse maps, sometimes in very distant places from where I navigate.
It's comfortable to start the app and not having to scroll hundreds of kilometres. 
And no, favourites don't give the same satisfaction.

**Comment by vrtareg** [comment]
I am not sure if symbolic link are working on SD cards as they are
formatted as fat 32 file system

Regards,
Areg

**Comment by sonora** [comment]
Looks like we have no action planned here.

**Comment by mcg-android** [comment]
If anybody is ever looking back at this issue, here's another argument: I'd like to be able to use separate locations for "map data" and "non-map data", so I can easily back up only the non-map data.

**Comment by sonora** [comment]
In a sense, the suggestion is partly implemented, because as of late all different types of data are separated into _different separate sub-folders_, with OsmAnd's root folder now essentially left to be used solely by OsmAnd's obf offline vector maps. 

What is not implemented, and it may be more involved, is to not just separate the data to sub-folders, but spread it over different _storage locations_, i.e. e.g. offload the backup folder (with the deactivated map files) from the internal to the external SD card.
