### ISSUE TITLE
Map legend (Help > Map legend) should be zoomable

### ISSUE THREAD

**Issue by bjohas** [osmandapp/Osmand#2777]
The map legend should be zoomable (and higher resolution). The legend is otherwise too small to make out properly.

**Comment by homersimpsons** [comment]
Maybe it need to be change from a simple picture to an svg one

**Comment by bjohas** [comment]
At the moment, the image cannot be zoomed "in-app", it can only be zoomed through android access features.

**Comment by sonora** [comment]
Resolution is quite sufficient to depict all the details contained, but yes,
- we do not include it in the app itself (it is only available online due to its file size)
- it cannot be zoomed to its actual full resolution on small screens with in-app methods.

Not sure what can be done about it with reasonable effort.

**Comment by homersimpsons** [comment]
Can't you render this as map item followed by legend?

**Comment by bjohas** [comment]
Inclusion in the app would be good also - I'd previously seen that it wasn't included. Yes, a solution as SVG, or indeed somehow as a map rendering would be great.

**Comment by vshcherb** [comment]
Fixed
