### ISSUE TITLE
Speed limit and measurements

### ISSUE THREAD

**Issue by OpenSourceForEver** [osmandapp/Osmand#2797]
OSMAND 2.4.0#13504D Navigation service: OSMAND car profile.  Spanish (spain) tts voice

When speed limit is exceded OSMAND says: "Speed limit 80" but I think OSMAND would say "Speed limit 80 km/h" or "Speed limit 80 mph" depending on tagged info.

I also think when speed camera is announced OSMAND would say: "Attention speed cam speed limit 120 km/h (mph)"

**Comment by polarbearing** [comment]
Are you talking about the announcement of exceeding the limit, or the warning about a camera? These are different warnings. 

Exceeding the limit for Spanish is controlled in the file ```voice/es/ttsconfig.p``` which you can edit on your client device. The relevant lines are:
```
string('exceed_limit.ogg', 'límite de velocidad ').
speed_alarm(MaxSpeed, _Speed) -- ['exceed_limit.ogg', I] :- num_atom(MaxSpeed, I).
```
Thus the announcement is "'límite de velocidad 80" for MaxSpeed=80. Most drivers want that announcement as brief as possible, hearing the unit again and again becomes boring. 
See [this comment](https://github.com/osmandapp/OsmAnd-resources/commit/2112fafb2dfa7211e64f7af1b3da260f3232547e#commitcomment-17752490) for an example to briefly announce how much you are over the limit.  

There is no speed value in the camera announcement.

**Comment by OpenSourceForEver** [comment]
"There is no speed value in the camera announcement". I know it, that is the reason why I suggest it.

**Comment by franco999** [comment]
@OpenSourceForEver I could partially solved with (in es-ar) "límite de velocidad excedido. Velocidad máxima: ", but does not say if km/h or mph

**Comment by polarbearing** [comment]
> I know it, that is the reason why I suggest it.

Language misunderstanding, you mean 'should' when you say 'would'.

@franco999 - There was an example how to speak the unit afterwards in [that comment](https://github.com/osmandapp/OsmAnd-resources/commit/2112fafb2dfa7211e64f7af1b3da260f3232547e#commitcomment-17746206), but try driving with such a long sentence announced, and you will get annoyed very soon.

**Comment by sonora** [comment]
In all practical tests, and I conduct many with many people, it turns out that long prompts turn very annoying very soon. So the "art" is to cut out anything you can while the prompt still remains useful and informative. And IMHO I think something like "Speed limit 80" is the perfect compromise here ... 

I have tried all combinations I could think of with and without units, and also with actual speed and with delta (because when I implemented the feature people had also asked for the actual speed as an extra bit of data). It may all be useful in some specific use cases, but certainly not for general use.

As for extending the speed cam prompt, I am less sure, am not using it. Fact is, it would make a rather long prompt! Imagine the continuous "babbling" in an area with many installed one after another? It would be ike driving through a residential area with many pedestrian crosswalks, and we have complaints about that, even though that is a very short prompt.

Also: I think if you are over the speed limit, you "need" a prompt and you get it. No need to duplicate information in the speed_cam prompt? So I would guess if you hear the speed cam prompt without having been notified you are over, it is just a reminder not to accelerate?

I will close this for now, please post here if you think my reasoning has a practical or logical mistake.

**Comment by polarbearing** [comment]
I like my "Eight over 80" a lot, it has the same number of syllables than "Speed limit 80", and gives you the immediate feedback that you should just take the foot off the gas, or hit the brake. I agree it should be kept optional, but thanks again for implementing the parameter.

**Comment by franco999** [comment]
Just curious, how about "Slow down. Maximum "?

**Comment by OpenSourceForEver** [comment]
@sonora. I think you are right. Thank you.

Concerning speed cam I think "In 500 meters (for example) Speed cam" is better than "atention speed cam". What do you think?

**Comment by polarbearing** [comment]
I don't think it adds value. It just makes the announcement longer, and delays my reaction. A speed cam is not like a turn that I have to select exactly (e.g. with turns before and after), it just reminds me to take caution.

**Comment by OpenSourceForEver** [comment]
I think Knowing the exactly situación of the speed cam is good because people who has activated speed cam's announcement wants to know the exactly situación in order to avoid fines.
