### ISSUE TITLE
Tag desc is lost when copying POI to favourite

### ISSUE THREAD

**Issue by pebogufi** [osmandapp/Osmand#2834]
Two cases:
1 - 
I open a pgx file (with wpt which include name and desc tags) with a file manager to start it with osmand.
Then Import it. Now I have favourites with name tag, but desc tag is lost.

2 -
I have a gpx file in dir import (or a subdir of import), same situation: file with wpt which include name and desc tags.
I use function "GPX-track" to open this file. This POI has name AND desc tag until now!
When I save this POI to favourite the desc tag is lost.

Be aware: favourites may have desc tags in osmand.

In both cases please copy the desc tag!

Thanks Peter

**Comment by sonora** [comment]
Peter, it works fine for me, I use this all the time. Can you please state which OsmAnd version you are reporting this for, and also attach a small GPX here which produces the issue? Thx - Hardy

**Comment by sonora** [comment]
PS: Just for reference: Here is what is supported and what works (see tags inside `<wpt>`):
````
<?xml version='1.0' encoding='UTF-8' standalone='yes' ?>
<gpx version="1.1" creator="OsmAnd~" xmlns="http://www.topografix.com/GPX/1/1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.topografix.com/GPX/1/1 http://www.topografix.com/GPX/1/1/gpx.xsd">
  <wpt lat="12.34567" lon="-76.54321">
    <name>NAME</name>
    <desc>see DESCRIPTION.pdf</desc>
    <type>HANGOUT-PLACES</type>
    <extensions>
      <color>#b4d00d0d</color>
    </extensions>
  </wpt>
</gpx>
````

**Comment by pebogufi** [comment]
I tested with your example and my current version
2.4.0#17301M

Case -1
copy desc works only, if there is a type tag.

Case-2
Using your file.
The POI has the desc.
But if I click on the star to save it as favourite, desc is lost.
Thanks for your help,
Peter

**Comment by sonora** [comment]
Case 1 should be fixed now, can be tested.

**Comment by pebogufi** [comment]
Case-2 Using your file. The POI has the desc. --->But if I click on the star to save it as favourite, desc is lost. 
This last part does not work in version 2.4.0#17640 (today)
Thanks for your help, Peter

**Comment by sonora** [comment]
Peter,
You must be producing Case 2 differently from what I thought:
Here is how I did it (and that code is fixed):
- Put the above GPX file in OsmAnd's data folder, sub-folder 'tracks' (or any subfolders therein)
- In OsmAnd, use 'Menu / MyPlaces / MyTracks'. Find the track and tap on it.
- Then go to tab 'GPX Waypoints', an tap the star icon.

What is your procedure?  Thx - Hardy

**Comment by pebogufi** [comment]
On 25. Juli 2016 11:21:23 MESZ, Hardy <notifications@github.com> wrote:
>Peter,
>You must be producing Case 2 differently from what I thought:
>Here is how I did it (and that code is fixed):
>- Put the above GPX file in OsmAnd's data folder, sub-folder 'tracks'
>(or any subfolders therein)
>- In OsmAnd, use 'Menu / MyPlaces / MyTracks'. Find the track and tap
>on it.
>- Then go to tab 'GPX Waypoints', an tap the star icon.
>

Until now I agree.

Now I have screenshot_1, desc is present "this is a desc"

Now I tap on the star (1st of 4 symbols) to save this POI/wpt as favourite, see screenshot_2
Below Kategorie there is a EMPTY line for desc.
That is what I am missing.

Hope all was clear,
Regards Peter

**Comment by sonora** [comment]
Peter, now I know what you do different:

> - Then go to tab 'GPX Waypoints', an tap the star icon.

What I mean to say is, **do not**, then, tap on the waypoint in question, but directly tap the star icon on that screen (near the top right corner of the screen). You should get a dialog saying "Save as group of favorites", and this puts all waypoints contained in a new category of your MyFavorites, including description, from where they can be further edited or processed if desired.

When you first tap on the waypoint itself, it will get displayed on the map, together with its content menu (and its description). But tapping the star there does in deed not copy the description, I think this one may be on purpose: Because that dialog is used for all sorts of search results and points you display on the map. So the description could potentially be very long (maybe a whole wiki article) or descriptive information could be spread across **several** fields, which I am not sure how they are tagged.

I have just tested with a restaurant, and the "desc" field seems to contain "Capacity 500", while all other useful information like opening times, web site, phone number, or food selection seems to be in other "fields". (This is also loosely related to #2558 ).

So it may be quite annoying or weird if we copy the desc into "description" in that dialog.  Plus: I have just discovered, you can do it manually if desired: Long-tapping the description field on the context menu (pull up the menu to see it!) copies it to the clipboard, and later long-tapping into the AddFav's description field offers the choice to paste it there again.

So plenty of other ways now to achieve what you want done. I want to research this last remaining issue only it is really a problem and I have some time ...  we have some higher priority things going on :)

**Comment by pebogufi** [comment]
Thanks a lot for your detailed answer.
Of course there are lot of ways to use a software, to navigate through it. Not every way can be fully checked.
I am happy that case 1 works, the other way, "my way", is of VERY low priority.

Many thanks for all that work on a phantastic software !!!
Regards Peter

**Comment by pebogufi** [comment]
Thanks a lot for your detailed answer.
Of course there are lot of ways to use a software, to navigate through it. Not every way can be fully checked.
I am happy that case 1 works, the other way, "my way", is of VERY low priority.

Many thanks for all that work on a phantastic software !!!
Regards Peter

**Comment by bald** [comment]
I have the latest version from the Google PlayStore (Osmand+ 2.3.5) which still has the described issue. Could you estimate when an update with the fix described above will be available?

**Comment by sonora** [comment]
The next release is nearing completion, I would guess we are talking a few weeks at most.
