### ISSUE TITLE
Issue with opening hours

### ISSUE THREAD

**Issue by jf-simon** [osmandapp/Osmand#2846]
Something is wrong with the opening hours. See screenshot.

![screenshot_2016-07-21-09-16-46](https://cloud.githubusercontent.com/assets/11144987/17014900/63be19a2-4f27-11e6-9ad0-ac2cdb03a950.png)
![screenshot_2016-07-21-09-43-25](https://cloud.githubusercontent.com/assets/11144987/17014938/a01aa500-4f27-11e6-970c-e7e64e31f006.png)

Using 2.4.0 #17577M

Simon

**Comment by osMatt** [comment]
Is the issue that the facilities are reported as closed even though you expect them to be shown as open (Thursday, 9:43 am)? Then I think this is actually a tagging mistake in the underlying data.

The [POI shown in the first screenshot](http://www.openstreetmap.org/node/1507207129) has the following opening hours string: `Mo, Tu, Th, Fr 07:30-13:00; Mo, Tu, Th, Fr 16:00-19:00; We 07:30-13:00`. If this is rendered in [yohours](
http://projets.pavie.info/yohours/?oh=Mo,Tu,Th,Fr%2007:30-13:00;%20Mo,Tu,Th,Fr%2016:00-19:00;%20We%2007:30-13:00) (or if you copy and paste it into the [opening hours validation tool](http://openingh.openstreetmap.de/evaluation_tool/)), you will see that the string does not capture the morning hours (7:30-13:00). The reason is that a `;` will override the rule(s) set for a particular day. In this case, `; Mo, Tu, Th, Fr 16:00-19:00` overrides `Mo, Tu, Th, Fr 07:30-13:00`. A correct formulation of the opening hours can either be made day by day (`Mo, Tu, Th, Fr 07:30-13:00, 16:00-19:00; We 07:30-13:00`) or by using the `,` operator which continues (but does not override) the previous rule: `Mo-Fr 07:00-13:00,16:00-19:00; We 07:30-13:00`.

For [the second POI](http://www.openstreetmap.org/node/1453654825), there is a similar problem: Replacing the opening hours string (currently `Mo, Tu, We, Th 08:00-12:30; Mo-Su 14:00-17:30; Fr 14:00-16:30`) with `Mo-Th 08:00-12:30,14:00-17:30; Fr 14:00-16:30; Sa,Su 14:00-17:30` should solve the problem.

**Comment by jf-simon** [comment]
Thanks for the info. I will correct this
