### ISSUE TITLE
Better Strategy to Identify Turn Types

### ISSUE THREAD

**Issue by raindropsfromsky** [osmandapp/Osmand#2855]
![screenshot_20160721-152640](https://cloud.githubusercontent.com/assets/9047168/17083567/1a26a89c-51c3-11e6-986e-c3b531132a71.png)
For the situation above, the best way to describe is to say "Take a U-turn". But OsmAnd says "Take a right turn onto x road, and then right turn to y". This is technically correct, but confusing.

![screenshot_20160721-101252](https://cloud.githubusercontent.com/assets/9047168/17083577/50480a4c-51c3-11e6-916c-eb941882be94.png)
 This is best described as "take a left turn".
But in practice, OsmAnd says "take a **slight** left turn", based on the first segment only.

![screenshot_20160721-101131](https://cloud.githubusercontent.com/assets/9047168/17083599/cb16193a-51c3-11e6-90a0-3180c420b487.png)
This is also another example of left turn, which is called "slight" left turn by OsmAnd.

**Comment by polarbearing** [comment]
Observed something similar today. These are all cases where there is a little road segment between dual carriageways or on a junction with dual carriageways. The question is if that is an issue. Maybe a short enough road segment could be consolidated into a single turn, using the name of the longer target road. In the case below, I'm effectively asked to do a U-turn onto Alt Mahlsdorf, using the [short cross-segment](https://www.openstreetmap.org/way/25811873) from Landsberger Str, which is indeed 13 m long:

![screenshot_2016-07-24-10-16-36](https://cloud.githubusercontent.com/assets/8266355/17085144/94db5c46-51d1-11e6-899e-057477b99695.png)

**Comment by raindropsfromsky** [comment]
That's right.

The segment could be a dedicated link of the same type as the road (primary/secondary/tertiary...), or it could be of a different type when different types of roads intersect (e.g. the dual carriageways could be primary, and the intersecting road may be a tertiary road. Even then it serves as a median break where the vehicle can take a U-turn.)

**Comment by polarbearing** [comment]
Those in-between sections are road abstractions of junctions that differ from the real world which has an asphalted square for a junction. However that style, being a consequence of a road abstracted as a line, is the heavily established mapping style in OSM, so we need to live with this tagging. 

For the routing announcement, it would not make any difference which highway=* type it is, I prefer to have the crossing segment to have the same type as the crossing road.

**Comment by osMatt** [comment]
Some ideas on how to implement this: 

For a U turn, the highway type of the middle section can indeed be many different ones, any crossing street would be a potential candidate. Thus to check whether a the routing want to make a U turn, (1) there are two turns of equal turn type (e.g. 2 subsequent turn left or turn right), (2) the middle section between those turns should be short (e.g. below 30 m), and (3) the highway name of the initial and final section should be equal.

For left/right turns via a short highway=*_link section, those turns should be consolidated into a single left/right (not slight left/right) turn, when (1) the route leads through a short (e.g. 30 m) segment of type highway=*link. Often these *_link sections have no name, therefore if would be great if the name for an announcement is taken from the final highway segment of the turn. Maybe this does not work for motorway_link or trunk_link segments, because these should be announced, but in general these are longer anyway.

**Comment by sonora** [comment]
This issue is not about voice prompts, but generally about optimizing the algorithm to determine the turn type from the map data and hence "predict" as closely as possible how a driver would perceive a turn in the real world. And yes, I have spent many hours over the years trying to find a better strategy for what evaluation radius to use when measuring the turn angle.

It is really hard: In many "real world" places, particularly in "tight places" like medieval town centers, the evaluation radius needs to be very short to correctly measure e.g. 90-degree turns around corners of houses or city gates (even if the alleyway then continues at a much lesser angle or almost parallel).

While in "wide-road" areas like on north American highways such a short evaluation radius seems pointless, whether a turn is "slight" or "sharp", or is a "U-turn", is defined there on a much broader scale. (Cf. definition of "slight turn" here: http://wiki.openstreetmap.org/wiki/Key:turn.

What in a medieval city is clearly two subsequent lefts e,g, around two house corners, may on an American highway well have to be identified as a "U-turn" on a divided highway...(!)

So far we have a "one size fits all" strategy to define turn types, and would need a much more dynamic strategy. But so far it is unclear what input data  to base such a strategy on.

**Comment by osMatt** [comment]
> What in a medieval city is clearly two subsequent lefts e,g, around two house corners, may on an American highway well have to be identified as a "U-turn" on a divided highway...(!)

I agree that these things might sound simple when considering just a few sample places: building a special rule for just those might break things elsewhere. I tried to address this is by suggesting several (additional) conditions to be checked for a more refined choice, e.g. checking whether the street name after the maneuver is the same (-> u turn) or whether a highway=*_link is passed while doing two short subsequent turns (-> likely only single maneuver). What is currently taken into consideration to determine the turn type? Anything beyond the angle?

**Comment by sonora** [comment]
Yes, Victor just beat me to the finish line with a fairly similar implementation.  :)  Let's test that!

**Comment by raindropsfromsky** [comment]
Regarding the determination circle, can we have this as a user-selectable setting?
"Small-medium-large" should do it (default=medium). 
If the user faces the problems we described, he can set this circle differently. For example, people visiting medieval European towns can set them as small, and most of us can set them as large.

BTW I know it is not a defect in the voice prompt per se, but a problem with the algorithm: But only the voice prompt issue matters, when we are NOT looking at the screen and relying on spoken directions. When we are looking at the screen, we don't pay much attention to the "next turn" icon, as we can see the actual shape of the turn!
