### ISSUE TITLE
The voice guidance ignores the last stretch of the road to the destination, after the last turn

### ISSUE THREAD

**Issue by raindropsfromsky** [osmandapp/Osmand#2865]
The voice guidance says "turn left/right and arrive at your destination". It ignores the last stretch of the road after the last turn.

Well, most of the destinations are not attached to the last corner: We have to drive on for some distance after the last turn. The voice guidance must mention this distance.

**Comment by sonora** [comment]
Works for me, just tested: "Turn left/right and arrive at your destination" is the abbreviated version if the destination is already within twice the distance where we normally announce "turn in" prompts.

When it is farther away, I hear  "Continue for 300m and arrive at your destination" after the final turn.

If you find situations where this does not work, please report specifically or research how to reproduce.

**Comment by raindropsfromsky** [comment]
I was not aware of that logic (there should be some documentation on this..)

Yes, in my case the destination was about 100m of the turn. So it does work as designed.

But then IMHO this is not good logic: 
"Turn left/right and arrive at your destination" is the abbreviated version if the destination is already within twice the distance where we normally announce "turn in" prompts.

The driver may not be familiar with the destination to know it by sight. So OsmAnd should point out how far it is after the turn.  

In a city, a 200m stretch of uncertainty is too big. The driver is very likely to overshoot, and if this is a one-way street, he has to go on driving to make another loop; thus losing precious time. The only way he can ascertain the exact location of the destination is to look at the screen. 

So the voice guidance should tell him where the destination is, to avoid all this hassle.

Secondly, if the destination has a driveway, the driver should be told to turn in.

**Comment by sonora** [comment]
> The driver may not be familiar with the destination to know it by sight. So OsmAnd should point out how far it is after the turn. 

Should already be implemented, there should be a prompt saying "You have reached your destination". This arrival prompt is the reason for there being no time for the interim "Continue for 100m and arrive at your destination" when the destination is very close after the final turn.

- This arrival prompt is scheduled for the regular "Turn" distance (just like if arriving was a final "turn").
- It is exactly meant to prevent any "overshooting"
- If there is a mapped driveway, the turn onto this driveway should be treated as the final turn, so this entire issue is void.

It is very hard to discuss these things in theory, because you relate to situations or examples you may know (or imagine), while I can only explain how our code works, what we consider, and what maybe not. So please when you raise issues like this it would be helpful to provide coordinates and use cases so we can reproduce in simulations. :)

**Comment by raindropsfromsky** [comment]
Well, I was collecting screenshots for that very problem, which is also seen in these cases!
Now that you mentioned it, I will omit the screenshots.

If the **{last corner-to-destination distance} <2 x {turn prompt threshold}**, then we face TWO problems, not one:
 1. The voice guidance does not tell the distance of the destination from last corner
 2. After the turn, it announces the arrival long before we come up to the actual destination.

Thus the driver is not guided till the very end of the journey!

With the following trick, we can overcome both these problems:
Change the last turn announcement to: "Turn left/right; your destination is at 200m."
This sentence is not longer than the current announcement: "Turn left/right to arrive at your destination"

Also, avoid the premature announcement of arrival.

**Comment by raindropsfromsky** [comment]
I just noticed that OsmAnd uses a nice phrase in line#3 in the Route editor GUI (the turn-by-turn instructions line):

Turn left/right and go 60m.

This can be adopted for our voice guidance: "Turn left/right and go 60m to reach destination"
Short and sweet!

**Comment by raindropsfromsky** [comment]
Thanks!

BTW how about "the destination is 200m **on the left/right**"? 
(only if time permits longer announcements...)

**Comment by sonora** [comment]
In fact my last analysis was incomplete, here is an enhanced version: (distance values taken for the CAR app mode)

**(Case 1)** If your destination is >210 meters after your final turn, and chosen so that it is essentially "on" the road, the last turn prompt will not mention it (e.g. "Turn left"), but AFTER the last turn you would hear something like "Continue for 200m and arrive at your destination". So no problem there.

**(Case 2)** If your destination is anywhere closer after the final turn, but chosen a little to the right or left of the road (as is often the case when choosing buildings or house numbers), the final turn prompt would announce: Turn left, the after 30 m keep right and arrive at your destination". So no problem here either.

**(Case 3)** If your destination is again "on" the road, and closer after the final turn that 210 meters, You would in fact only hear "Turn left and arrive at your destination" in the final turn prompt. There is no time slot for another announcement before hearing ""You have reached your destination", so this is in fact the only gap

I have researched what it takes to fill this gap.
- The engine code changes are a little complex, but moderate.
- We would need 2 new strings and some scripting work in 35 voice files before this can go live. I have done this before, but it is many hours worth of work, and it will not be perfect until at least one translator per language will have checked it (which takes several years in some languages)
- The voice prompts can become even longer, and please note that this in in the very case where things are "close" anyway. As an extreme example, the final prompt (50 meters before the final turn) may well turn out something like "Turn left onto John F Kennedy Parkway, then after 120 meters arrive at your destination "National Museum of Natural History".

I have pretty much done all the research of how what needs to be done, but am still wondering if it is worth it, and if we would really appreciate the final result??

**Comment by sonora** [comment]
Looking at this, I guess a simple solution could be to announce for (Case 3): "Turn left, then continue for 120 meters and arrive at your destination". I can do tis with the existing vocabulary tool, and it will be easy to back out of we do not like it.

**Comment by raindropsfromsky** [comment]
Or even shorter:

"Turn left and go 120 meters to reach the destination."

On Jul 28, 2016 3:02 PM, "Hardy" <notifications@github.com> wrote:
>
> Looking at this, I guess a simple solution could be to announce for (Case
3): "Turn left, then continue for 120 meters and arrive at your
destination". I can do tis with the existing vocabulary tool, and it will
be easy to back out of we do not like it.

**Comment by raindropsfromsky** [comment]
P.S. It is awkward English to say "go x meters and **arrive at** your destination".
Because, the verb **arrive** is from the perspective of a person who is already present there.
("I saw him arrive with two other people")

But here you are **going to** the destination. So at the end, you **reach** there.
("When I reached home, it was already past two.")

**Comment by sonora** [comment]
Wording: May be cultural. I associate "reach" with an achievement, while "arrive" is used in travel. As in: Sitting on a plane, captain announces: "We will arrive 20 minutes ahead of schedule". See also http://www.english-test.net/forum/ftopic48474.html, 3rd entry, and several other web sites, sort of backing this up.

Re "go": It is not in our current vocabulary pool. I think I have "arrived" :) at a clear decision to only consider solutions I can quickly implement without changing language files, because we are nearing a release date.

**Comment by raindropsfromsky** [comment]
That's true: After joining a 2-hours crawling traffic, when I reach home, it **is** an achievement! :D

**Comment by raindropsfromsky** [comment]
@Go: That could be done in future, with a long-term planning (add other words also, like reach).
I thought "go" was already there, because it is used in the turn-by-turn lines.

**Comment by sonora** [comment]
"Reach" is not a tough change. Since arrive and reach are basically synonyms, an exchange need not affect other language translations and their grammar. But it would be more repetitious, because we already say "You have reached your destination" every time shortly after the arrival information. Would you like that?

"Go" I am not sure about,  we have no prompt or grammar for "go <distance>",unless I am overlooking something here. Where do you hear it?

**Comment by raindropsfromsky** [comment]
No I only saw it in the turn-by-turn listing of the Route Editor dialog (as I described earlier), so I assumed that OsmAnd converts that to speech also.

**Comment by sonora** [comment]
I think I have done what  can be done with reasonable impact - please test.

You should now either hear a distance associated to the destination arrival as part of the final "regular" turn prompt (if the destination is within about ~250m behind it),  or later as part of the prompt announcing the final stretch  (either in "continue" if it is straight on the road, or the keep/left/right indication if the destination is a little to one side of the roadway.

On rare occasions, you may hear both, it is not 100% predictable if there is time enough for the second info, so I try to err on the safe side.
