### ISSUE TITLE
The card of a new point is not an effective method of inserrting the point in a route

### ISSUE THREAD

**Issue by raindropsfromsky** [osmandapp/Osmand#2868]
Assume that we have already defined a route with a destination point.
Long-press anywhere on the map. OsmAnd places an orange spot-marker there, and shows a card.

The card has a blue button with a flag, which places the spot in different spots on the route. 

Ideally, we should be able to place the point anywhere on the route.
But it offers just four options, using very verbose and confusing options.

See the following chart, where I have shown the original route as a horizontal line with a start point, a destination point, and a few waypoints. The chart shows five different variations of this idea.

![insertion of a point in route](https://cloud.githubusercontent.com/assets/9047168/17131448/26c270c6-533b-11e6-9e54-037a20e4fe99.png)

- All the possible insertion places are shown with an arrow.
- The **green** arrows show where OsmAnd allows us to insert the new point
- The **black** arrows show the places where we cannot insert the point.
- I have used **gray** arrows near the start point, because these are rarely used positions.

To conclude, the GUI provides as many as four options, and yet it cannot place the point in many useful places of the route. For example, it is not possible to replace an existing waypoint with this point, or place it between two existing waypoints. 

We will still need the **Route Editor** GUI to do this. In that case, why should we have four options in the card? After all, these are not most frequently used options!

**Desired:** The point's own card should have just one option: To insert the point in the route as a waypoint. After that, OsmAnd should automatically switch to the Route Editor, so that the user can place all points in proper sequence, or do the **door-to-door** sorting.

**Comment by sonora** [comment]
It is quite clear that this "Quick point insertion" can only be a "lite" version of the full-blown route configuration, but it is easily accessible and comprehensive.

If you use it, which actions you need depends on your personal strategy of how you set up your route:
- If you work step-by-step towards your final destination (in the final order), you would always add the next destination using "Add as last destination"
- If you are used to setting up the final destination first, then the interims, you would need the 2 "Add as first/last" interim destination" actions, depending on in which order you tackle the intermediates
- And if you came to this dialog and accidentally still already have a old destination set,  "Replace destination" is your essential friend.

So I think all 4 options are really needed, depending on your habits.

Looking at your chart (nice analysis, by the way!), the only case the dialogue does not cater for is to insert an intermediate destination into the middle of other intermediate destinations, a possible but not too frequent occurrence if you set up your route half-way systematically. (It only affects the complex case of already having at least 2 waypoints, I think then you are better of using the full-blown config screen  ...)

**Comment by raindropsfromsky** [comment]
Thanks! :)

Yes, what you say makes sense. It also cannot replace the existing waypoint(s).

BTW the use of "last destination point" is awkward, and "first/last intermediate destination" is far far worse!

Instead of "intermediate destination", why niot use the industry-standard word "waypoint"?

Thus-
- Add as first waypoint
- Add as last waypoint. 
- Replace the destination
- Add as final destination

(The sequence reflects where the point goes, which helps visualization)

Regarding combining of two screens ("Route configuration" and "Waypoints") into one, :+1: 
But I still like my own proposed [GUI](https://cloud.githubusercontent.com/assets/9047168/12410537/309277c4-be9c-11e5-83ab-a2177547d5c9.png) !

**Comment by Barrocas** [comment]
Agree with Narayan, I would also prefer the "waypoint" instead of the
"intermediate destination", that is longer and adds more confusion.

A simple "add as waypoint" (not first nor last) would be easier, we would
just had to add them sequencially as needed.
If the order was not correct, then it could be changed on the route plan.

-- 
Cumprimentos,
D.er Hugo Barrocas

**Comment by sonora** [comment]
OK, looks like we all agree and it is down to wording now ... :)

Here is the history: Code separates between:
- **GPX waypoints:** Points annotated in GPX files
- **Intermediate destinations:** These are points you specify as targets when setting up a route, i.e. points you need to go to
- **Waypoints:** Could say these include destinations, but are more generally points along your way, either on it directly, or on the side of it, which happen to be there and which you may chose process or ignore. On e.g. the current "Waypoints" dialog you can configure which categories you are interested in, may want to have displayed, or even announced. There is a wide variety, could be a STOP sign or some other traffic warning, could be viewpoints, gas stations, restaurants, or other POI directly on or along your way.

Yes, at some point I also liked "Waypoints" and I had actually unified all categories to use "waypoints" everywhere. But this created issues:
- Users approached me saying that somehow some translations in their languages always seem wrong somewhere, an that translator were going around in circles changing this
- When talking to translators it turned out that  in many languages at least a point of type "destination"  requires a completely different translation from would be used for the other 2 categories
- Not sure if unification does not also create logical issues for a user, because setting up a destination is quite a different use case (and process) than setting up other waypoints (or making annotations to tracks).

So it may seem prudent, maybe even mandatory, to use 3 different expressions and clearly distinguish between them?

**Comment by raindropsfromsky** [comment]
Ah, do let us forget all that historical baggage, and adopt this simple menu.
I am sure the translators will be able to find their own solutions for each languages, as we just did!

- Add as first waypoint
- Add as last waypoint
- Replace the destination
- Add as final destination

**Comment by raindropsfromsky** [comment]
BTW it is impossible to translate any string into multiple languages verbatim, without losing some aspect of the original meaning. Therefore each translator will have to draw on his native vocabulary to come up with a near-equivalent word. Sometimes he may have to replace a word with a phrase and vice versa. But this should not add to the burden in the original language in which the GUI is planned.

In any case these phrases are almost like text for radio button options. So the phrases can be loosely translated without any constraints whatsoever.

**Comment by sonora** [comment]
Consistency is key here: We cannot call something "Waypoint" in one dialog, and "Destination" on other screens.

And: Any change I commit will need to performed consistently throughout the app, and in all respective documentation elsewhere (web site, help pages, FAQs) . So it is a little more involved than just  a quick "adopt this simple menu".  :(

**Comment by raindropsfromsky** [comment]
Ah yes, of course!

Well, how about replacing "waypoint" with "stop" or "stopover"? 

So our options look like this:
- Add as first stop
- Add as last stop
- Replace the destination
- Add as final destination

OR

- Add as first stopover
- Add as last stopover
- Replace the destination
- Add as final destination

What do you think?

**Comment by sonora** [comment]
My 5 cents:
- "Stop" clashes with public transport stop
- "Stopover" I like, it is a viable alternative, although in travel jargon it is often associated with a trip interruption, which it need not be, as we also use them to aide route calculation....  not sure, probably a cultural thing  :)
- I am rather hesitant about "final". If you build up your route by always adding one after the other at the end, you will always add as "last", but it will never be "final" ... if you know what I mean
