### ISSUE TITLE
Add 2gis support

### ISSUE THREAD

**Issue by KOLANICH** [osmandapp/Osmand#2913]
2gis has db of pois (organizations) and public transport networks for Russian Federation (and some for other states, mostly the members of the commonwealth of independent states). It'd be nice to augment osmand with 2gis support.

**Comment by njohnston** [comment]
Instead of focusing on one (admittedly big) country, I'd prefer to see OsmAnd using open GTFS data from Mapzen's [Transitland](https://transit.land/). I'd also like to see OsmAnd using Mapzen's [Valhalla routing engine](https://github.com/valhalla), which is written in C++ and supports multi-modal routing (i.e. routes with a combination of different means of transport such as walking and public transport). See more details in [Mapzen's blog post](https://mapzen.com/blog/transit-routing/). Valhalla also supports elevation-aware routing which would be great for walking and cycling.

Having multi-modal routing in OsmAnd would be brilliant.
