### ISSUE TITLE
Turn-by-turn navigation may announce a sharp turn as slight if it is via a slip lane

### ISSUE THREAD

**Issue by arschficken** [osmandapp/Osmand#2924]
Navigate [this round-about](https://www.openstreetmap.org/#map=19/-37.85550/145.31550) from the south along Mountain Highway, turning left into Forest Road.

Navigation will instruct you to "turn slightly left", which is misleading to a human who will see that slightly left leads through the round-about. (Navigation does not mention the round-about.)

Obviously if you just look at the way segments, it is indeed a slight left turn into the slip lane. The big picture however is:

1. A sharp left turn
2. Before the round-about
3. Via a slip lane

Unfortunately this looks like a hard problem to solve algorithmically.

**Comment by raindropsfromsky** [comment]
A similar situation arises where we have to exit from a major road onto its service road via a small opening. Thus this maneuver is not the same as changing lanes. Yet it is described as "take slight left", which can be confused with keep left on the same road. The sense of "leaving the road" does not come through.

**Comment by raindropsfromsky** [comment]
I suggest that the voice prompt should say "After x meters, exit left to xx road", and if the road is not named separately, just omit the reference to the other road, and say "After x meters, exit left"

**Comment by polarbearing** [comment]
Could the first poster please choose a less offensive user name?

**Comment by vshcherb** [comment]
Indeed it will be hard to solve programmatically so user should look at the map. If this intersection has turn:lanes tagged it could help to the drvier

**Comment by arschficken** [comment]
Thanks @vshcherb, that's a helpful tag. So in this case is it sufficient to tag [way 5441243](https://www.openstreetmap.org/way/5441243) with "turn:lanes=sharp_left;through", or should [way 48490130](https://www.openstreetmap.org/way/48490130) also be tagged, e.g. with "turn:lanes=sharp_left"?

**Comment by raindropsfromsky** [comment]
oops. On second look, I realize that the situation I described is not related. Will raise a separate issue for that).

But IMHO Viktor has not closed this bug correctly: This cannot be solved by tagging the first exit as "sharp left", because it is NOT a sharp left.

In fact, the car passes through **two** turns, one after another:
- At the junction, the first slight left (11-o'clock) turn departs from the Mountain Highway
- At the second junction, a left turn (10 O'clock) goes to the Forest Road, while the straight road goes to the turnabout.

Thus the voice prompt should say: "Turn (slight) left and then (slight) left" to mention both turns, because there is not enough time to announce them separately.

So has OsmAnd not detected the two turns here??

**Comment by arschficken** [comment]
That first slight left is just the northbound traffic splitting off from the southbound traffic as the road splits in two around the triangular traffic island. So it's consistent if OsmAnd+ does not announce that specific deviation of the road, isn't it?

**Comment by raindropsfromsky** [comment]
P.S. We are again coming to the same situation that Sonora mentioned: At a junction, the first line segment may have a gradual turn, which invokes the "slight left/right" voice prompt. But actually the subsequent segments constitute a "full" turn. 

While a "full" turn is NOT a "sharp" turn, the amount of turning is the same; 

Thus, while the driver can visually see a "full" turn, the voice prompt says only a "slight" turn. 
Thus the OsmAnd fails to to guide the driver properly.

**Desired:** OsmAnd should consider 2-3 segments within a evaluation radius. As explained by Sonora in the other bug, the radius should be user-settable, so that we can adjust it to match medieval towns (tight cornering) vs rest of the world (gradual cornering).

**Comment by raindropsfromsky** [comment]
@arschficken, No it is not the same, because if you see the roads in Edit mode, the road is a single line (not shown as a dual carriageway. Thus OsmAnd must respect the junction, where the left branch goes toward the roundabout. It is NOT the same road.

In fact, the left link is named as "mountain highway" and classified as a "road", which is wrong tagging: It should be identified as a "secondary link", and named differently. It is no longer "Mountain highway").

On the other hand, if this is a dual carriageway, and if the left half deflects at the traffic island (triangular), it is fine. But that's not applicable here.

**Comment by arschficken** [comment]
Wouldn't a dual carriageway be implemented the same way though, as two one-way ways side by side? A northbound user can't (legally) take the eastern one-way road, so wouldn't expect the navigation to announce the split as a turn. In human terms it's just a deviation. This is clearer in the aerial imagery.

Of course we still have the "slight left" problem ...

**Comment by raindropsfromsky** [comment]
What I meant is, if this were depicted as a dual carriageway, then the eastern half would go straight into the roundabout.  Then the traffic going to the Forest Road would see only one exit branch.

But because this road is drawn as a single bidirectional road, it has two branches. First at the traffic island, and then the exit branch that goes to the Forest Road.

**Comment by arschficken** [comment]
Oh, I think I see what you mean. (The unnamed slip lane should be a secondary link; and there should probably be a turn restriction where the northbound lane of Mountain Highway arrives at the round-about.)

What we keep coming back to is how much to fix in data versus in code. Compared to Google for example we can't mandate advanced tags like turn restrictions and lane descriptions for casual mappers. So we're in the unenviable position of needing better algorithms than Google to make sense of what we have ...

Which is the bug that refers to the evaluation radius? That solution seems workable.

**Comment by raindropsfromsky** [comment]
https://github.com/osmandapp/Osmand/issues/2855

Unfortunately that bug was closed without a full resolution (Viktor fixed only the U-turn part). IMHO the other parts are also worth pursing.
