### ISSUE TITLE
Serious problems with the new quick search

### ISSUE THREAD

**Issue by enomat** [osmandapp/Osmand#2928]
- download Hungarian map
- go to this position (move map center to this position): Lat 48.14476 Lon 19.85933
- open Quick Search
- type in this: "tó" ("tó" means "lake" in Hungarian)

Problems:

<img src="https://cloud.githubusercontent.com/assets/12612250/17529716/b544850c-5e74-11e6-8950-7061588d5d04.png" style="max-width:100%;" height="500px"> <img src="https://cloud.githubusercontent.com/assets/12612250/17529736/ca89fece-5e74-11e6-8d77-63ddbca20ce1.png" style="max-width:100%;" height="500px">

**1.** The UI does not always show the distance (and icons) of the search results. If they are just categories, they should have a bit different design to make it obvious that they are not results but categories.
**2.** The Quick Search can't distinguish the accented and non-accented characters, for example "ó" vs "o"
**3.** The search results it shows do not even contain the "tó" string. There are two lakes nearby, but the search engine can't find them:

-- Tehenesi-bányató
-- Középbánya-tó

**4.**. The search engine can't search for substrings:

<img src="https://cloud.githubusercontent.com/assets/12612250/17529812/20c4d534-5e75-11e6-9466-876a38ee193e.png" style="max-width:100%;" height="500px"> <img src="https://cloud.githubusercontent.com/assets/12612250/17529823/2a2cf494-5e75-11e6-8276-574730116f87.png" style="max-width:100%;" height="500px">

**Comment by vshcherb** [comment]
1. Yes, make sense, will share with designer.
2. That's feature
3-4. Known issue and it is not planned to do that.

**Comment by david-ukr** [comment]
I also have serious problems with the new quick search in Osmand+ 2.5.4. I have about 10 country maps downloaded and several German states. Suppose I am currently in Germany and looking at a Bavaria map and I want to search for Bangkok, Thailand. If I enter "Bangkok" in quick search, it takes at least 10 seconds (sometimes 15 seconds) to find on my Galaxy Note 3 because it first finds and lists more than 40 Bangkok restaurants in Germany before it shows the city in Thailand. Then I tried to switch the map by searching for "Thailand". This also took at least 10 seconds to find because there are many restaurants mentioning Thailand in their names. Entering "country thailand" in quick search did not work either. 
Please let me have back traditional search, for example on the Search button in the menu as you did when quick search was first released (leaving quick search on the Search button on the map). Then I can choose country Thailand by entering two characters (th) followed by Bangkok with two characters (ba).
I also tried to use Google Maps to copy the geo URL to Osmand, but searching on a url like www.goo.gle.com ... in Osmand didn''t work either, although this syntax example in shown in your help.
It's also a pity you must enter city then street and not vice versa, so you can't just paste in an address from an imprint of a web site.

**Comment by vshcherb** [comment]
Duplicate issue, though it will be valuable if you could specify exact geo URL which is not working

**Comment by david-ukr** [comment]
Problem string example https://goo.gl/maps/qb7caUW6Jdo (this is Mühlenhof 1 in Neustadt, Germany). Note that the Share Action string from the Google Maps Android app includes the street and house number too: "Mühlenhof 1 https://goo.gl/maps/qb7caUW6Jdo". Searching on the **entire** string in Osmand with quick search finds Mühlenhof 1 in various towns after quite a few seconds, including the one I want. Finding multiple hits is probably not intended, fast or useful. To simplify pasting a geo url Share Action string from the Google Maps app to Osmand I suggest quick search should ignore all characters before the https. 

By the way, Osmand is rarely found among the recipients of a share action (the list of apps suggested when you tap the Share button in another app). Now you plan to support a geo url from Google Maps, it would be handy to find Osmand in the list.

**Comment by vshcherb** [comment]
Thanks
