### ISSUE TITLE
If I dismiss a route, OsmAnd should not recalculate the route when I launch the Route Editor

### ISSUE THREAD

**Issue by raindropsfromsky** [osmandapp/Osmand#2958]
If I dismiss the route, OsmAnd retains the **From** and **To** addresses. 
This persistence is OK if I want to re-launch the same route once again.

But the problem is, that's not my intention: I want to define a new route.
(Otherwise I would not have dismissed the route in the first place!)

But whenever I launch the Route Editor, OsmAnd immediate recalculates the same old route immediately and shows it on the map. This is irritating.

**Desired:** OsmAnd should re-caluclate the route only if I press **Go**. otherwise just wait for user inputs.

**Comment by vshcherb** [comment]
Disagree, you dismiss a route because you don't want to follow it now, but may be in 5-10 minutes it will be perfectly ok. Actually that's my standard usage

**Comment by polarbearing** [comment]
Agree with @vshcherb. 
However I observed recently that dismissing a route also switches off the red air-direction arrow and the air-distance widget, his that intended? Often I appreciate having shown the correct direction of the target and air distance while not requesting the device to route.

**Comment by vshcherb** [comment]
Widgets are mostly related to profiles and not to navigation/non-navigation mode. Though In navigation mode "destination widget" shows distance to target via route (non air-distance)

**Comment by polarbearing** [comment]
I'm under the impression that while calculating the route, it shows the air distance.

**Comment by sonora** [comment]
Certainly, while the route is still being calculated, the "distance via the route" is of course still unkown  :)
It will switch immediately after the route calculation has finished,

**Comment by polarbearing** [comment]
Yes. Let's phrase it differently: I'm looking for a setting that simply shows me the air distance and the red arrow, without calculating a route.

**Comment by sonora** [comment]
Something like "Navigation settings / Navigation service / Straight line"?

But that calculates a "pseudo-route". We used to have exactly what you ask with the orange arrow displayed on the screen, and the aerial distance displayed in the destination widget, back when we had stuff like "Set as destination" (which required starting route calculation as a separate user action). The setting "Configure screen / Show destination direction" still available in map browsing mode is a remnant of this.

But most of this functionality was changed to much simpler calculate the route with much less intervention and fewer settings, to better cater 99% of OsmAnd users' use cases, who want more straightforward and more automated behavior, and fewer "states" the app is in. (States "destination is set / not set" are now rolled into whether a route is calculated or not, rather than being separate.)

**Comment by polarbearing** [comment]
Ok so at least my memory is still functional as I remember seeing it before. 

The feature is useful when you do several errands in an area you know and don't need routing, but want to keep the final destination in mind; or when you explore an area touristically, based on beauty and signposting, while overall heading towards your night accommodation.
