### ISSUE TITLE
Feature request: miles/meters units

### ISSUE THREAD

**Issue by tobydickenson** [osmandapp/Osmand#2975]
When driving in the UK it makes sense to have speed reported in miles/hour (to match the car speed indicator, which shows miles/hour) and trip distances in miles (to match local road signs).

However that doesn't mean I understand what feet or yards are. I still want voice guidance to say "turn left in 50 meters".

Please add a "miles and meters" units option.

**Comment by vrtareg** [comment]
Ah I so understand you ...

**Comment by vshcherb** [comment]
I'm surprised that request didn't come up earlier. Implemented and even made default. @sonora  could you please double check commit/details.

**Comment by vshcherb** [comment]
https://github.com/osmandapp/Osmand/commit/a5384abb1358f9ceb47294dc6a6bee7468dfffe5

**Comment by sonora** [comment]
@tobydickenson , @vrtareg : So this was a serious request, and not an outbreak of British humo(u)r  ?  :)

I have spent some years at Cambridge University myself,, and mixing measurement systems sounds like something we would have come up with in our undergrad years early mornings after long nights of celebrating with too much booze ...  :)

In any case, apologies, did no mean to ridicule this. I have reverted this as the default for the US (https://github.com/osmandapp/Osmand/commit/cb5aa0dee3dbd39b7e68e932705cf78331a63451), where there are certainly communities (and highways, see I-17 Tucson-Nogales) using SI unit label(l)ling, but I am afraid any mixture of miles and met(e|r)s is quite unacceptable. I am hoping, though,  it does meet the **majority** of British taste as the "default" for the UK? (Please let me know if objectively we should make this an option only rather than the UK default).

I will have a pint of beer now, wish it was Imperial, it would be about 20% larger  ;-)

Best, Hardy

**Comment by vrtareg** [comment]
Hi Hardy

This is really interesting if requested is real or joke.

As for me I get used to yards option as it is more meaningful for me.

Even after 7 years living here I never got familiar with miles and yards or even feets.

I have got yards back multiple times as for example 100 meters = 109 yards = 328 yards ...
So kill me but I never could imagine how much is that 328 feets ....

Not mentioning pints and pounds

So question in the market 
"In pounds as weight or pounds in money ..."

I just commented that for me who came from old Soviet Union school all this measurements was crazy at first view. 

Now we get used to it by multiplying and dividing. 

Enjoy your pint and take life easy :)

Regards, 
Areg

**Comment by tobydickenson** [comment]
I have been extensively using the nightly build from when this was first added, and it looks good. However there are a couple of glitches. In a quick check, both these issues seem to be still present in yesterdays nightly build.

1. With miles+meters selected, it is missing all voice prompts that include a distance. Sometimes it omits the whole prompt, and sometimes it just skips the phrase that includes the distance. Voice prompts work fully after switching back to other units.

2. At one specific zoom level the scale bar is labelled "0.62 miles", which is deliciously silly (1km, expressed as a decimal fraction of a mile). The scale bar is labelled in meters up to 200m, and in miles for 0.5 miles and above. That all seems right except for this one specific level.

![screenshot_20160829-144427](https://cloud.githubusercontent.com/assets/292492/18053510/a9a789b4-6df7-11e6-98ed-61304cdbe002.png)

**Comment by sonora** [comment]
Tough work, but fixed. :)

**Comment by tobydickenson** [comment]
that looks good :-)
