### ISSUE TITLE
Use punctuation in TTS

### ISSUE THREAD

**Issue by cmeeren** [osmandapp/Osmand#2985]
AFAIK OsmAnd does not use any punctuation when creating TTS output. I have tested with the TTS engine I've installed (IVONA UK "Amy"), and commands sound much more natural if commas are inserted (I'm not sure if periods help or not).

For example, I suggest "in five hundred meters, turn left." instead of "in five hundred meters turn left".

This may be related to #2983 (which could be another and more flexible way of solving this problem, though probably a bit more involved).

**Comment by vshcherb** [comment]
We are going to support it cause we need to have better Notification messages, for voice messages it doesn't matter much. So it is planned in the scope of another task.

**Comment by sonora** [comment]
@cmeeren: This may be very language-related, and on top even be a matter of engine and taste.

May I suggest you enable the Development plugin in your OsmAnd app, then go to Settings /Development /Test voice prompts. I have recently updated this module to contain all major combinations of prompt fragments, capture the grammar peculiarities of many languages, and I also numbered the commands, so they can be easily referenced.

Maybe you can report some command numbers here and suggest what punctuation you think would be a general improvement . (PS: It is not true that we do not use any punctuation: Most if not all languages use e.g. a comma before "then").

Thx - Hardy

**Comment by vshcherb** [comment]
I keep open that issue cause now we display it for Android Wear and for display we need to use proper punctuation. Though if it is hard to achieve we can think not to use Voice prompts as messages similar to what we do in Route Screen.

**Comment by sonora** [comment]
I have played with this a little, my findings are

- In many languages I have the feeling that the extra pause a comma does cause in the phrase you suggest "in five hundred meters, turn left." is a little strange, and also in many languages this is not where orthography would place a comma.

- I do think though, that the absence of commas in the phrases about route calculation and route recalculation was a bug, most languages' orthography would likely separate off the distance and time portions there by commas

- I find no difference in intonation when adding a period to the end of statements.

I have prepared the en and de tts voices for testing (latest nightly build), but only changed the second (route re-calculated phrases)and third bullets above (inserted commas and periods in the route re/calculated prompts).

**Comment by sonora** [comment]
Fixed via https://github.com/osmandapp/OsmAnd-resources/commit/205bb4be8c1c0d84935251a530486b4ec0d5d323.

I think more should not be done on a generic level. When investigating I fin that some of our language files do already use extra commas in some situations, others have added and extra "and" in some places, so it is in deed very dependent on the language.

For English, I have done a few experiments and I am very hesitant to go beyond what I have committed already. As I said, too many additional pauses, particularly where orthography does not mandate commas, may make the voice prompts sound "disconnected" on some voice engines.

**Comment by vshcherb** [comment]
@sonora Do you suggest to show this messages or not? Or should we choose another method to format message what's next "prompt" to display in the notification bar.

**Comment by sonora** [comment]
@vshcherb Victor, I am not familiar with how this would work or look. But from our code point of view, either way is viable:
- We have a "display navigation instructions as text" logic we use on the route details screen, also used to print out nav instructions from there if desired
- We have a different (much ore advanced) logic and text we pass to the tts engine

Some time ago I had looked into harmonizing the 2, but it is lots of work with little benefit. Both have advantages and disadvantages.
- What we use in Route details is very rudimentary grammar-wise, but I had recently upgraded it at least to now include street name, ref etc. display (although not full-blown waypoint or destination names etc.)
- TTS is much more advanced when it comes to localization and grammar, but it may not always have perfect orthography, because some spelling and character replacement may happen in some languages to aid pronunciation (it is not originally designed to be displayed as text). Punctuation should be mostly correct, though, and not an issue for your purpose.

My feeling is, if you want to display instructions also as text (not sure if I understand correctly what you are trying to do), go try the tts text first, is has been much more subject to fine-tuning and localization maintenance.

**Comment by vshcherb** [comment]
Actually you convinced me not to use TTS, cause it is overcomplicated and it will take a lot of time to make it nice, though for text which will be read you don't need to invest much of correct form 1 kilometer/kilometers, you can simply use "1 km" and it will be clear enough.

**Comment by sonora** [comment]
Yes, in that case the shortened and almost "grammar-less" "Turn and go" type text prompts we use on the route details screen may suffice, or maybe even still less like just something like "turn type and distance".
