### ISSUE TITLE
Offline routing: Don't say "turn slightly right" when exiting a highway where turn:lanes=..|..|slight_right

### ISSUE THREAD

**Issue by cmeeren** [osmandapp/Osmand#2986]
Take a look at [this road segment on OSM](https://www.openstreetmap.org/way/46953598) (street view [here](https://goo.gl/maps/jqghtFhxyAr)). It's tagged with `turn:lanes=none|none|slight_right`, as it should be according to the blue street sign. The actual junction node is tagged with `motorway_junction`, and the exit way is tagged as `motorway_link`.

Using offline routing, TTS told me to "turn slightly right" when taking this exit. I'd like the voice to say something like "take the exit" or "take exit 5" (or whatever number the exit might be).

I might also have experienced TTS saying "keep right" in similar cases if there are no `turn:lanes` tags, though I can't remember any concrete examples to show this.

Might be related to #1347.

**Comment by polarbearing** [comment]
> Might be related to #1347.

I'd say it is a duplicate.

**Comment by cmeeren** [comment]
> I'd say it is a duplicate.

I disagree. While I wasn't entirely clear in the description, I think this should be handled no matter if there's a `motorway_junction` or not, e.g. on trunk roads, primary roads etc.. These roads can have similar types of "exits" without there being a numbered/named exit that can be tagged with `motorway_junction`.

**Comment by raindropsfromsky** [comment]
I have highlighted the same problem recently, but the issue got closed.

Whenever we use a junction to reach another road, OsmAnd should treat it as an "exit", and announce it as such. 
- This  junction may or may not be tagged.
- The junction may be created with a link, or can be formed when another road intersects two parallel roads.

**Comment by raindropsfromsky** [comment]
See https://github.com/osmandapp/Osmand/issues/2924

**Comment by raindropsfromsky** [comment]
![exits](https://cloud.githubusercontent.com/assets/9047168/17845369/ff185016-685e-11e6-9edf-da55db5b3427.png)

**Comment by polarbearing** [comment]
I don't get the point. While I agree that it would be highly useful to announce a numbered exit with "do something ... at exit 25", I prefer to get the announcement to turn slightly right when the link road goes slightly right. 

The latest picture from @raindropsfromsky confuses me completely, are these supposed to be dual carriagelanes or what? What difference does the "equal" vs "unequal" road make? What is the expected behaviour?

**Comment by cmeeren** [comment]
I don't understand the relevance of that picture either, but my point is this:

The `turn=slight_right` tagging of the exit/deceleration lane makes sense from a purely visual lane assist perspective (like the one in OsmAnd), since the exit lane then will show an arrow pointing slightly right. This makes sense because the "slight right" arrow is also, incidentally, a logical marker for exit lanes. The voice command "turn slightly right", on the other hand, is IMHO a confusing command to get when exiting a highway (or any other road, possibly without numbered/named exits, such as [this exit](https://goo.gl/maps/tEoyNYQDWjJ2) from a trunk road).

**Comment by raindropsfromsky** [comment]
**Clarification:**

No they are not dual carriageways (the traffic on other side of a dual carriageway is in the **opposite** direction. so you cannot switch to the other side of a dual carriageway!)

My case is a more generic case of what @cmeeren described: Instead of branching off the main road, I have shown a road that extends backwards also. But so far as the exit is concerned, they are identical cases (IINW). In my drawing, the road on the right is the current road (left-hand driving), and I want to exit to the road on the left.

I have shown three different cases: 
1. Both roads are of same hierarchy (e.g. "secondary"), and connected with a link of same type 
2. The current road is primary, but the exit road is secondary, and link is also secondary.
3. A primary road and a secondary road are intersected by a secondary road.

In all these cases, I expect OsmAnd to tell me **exit** to xxx road.
(Not "take a slight left", which sounds like change of lanes.)

**Comment by vshcherb** [comment]
I agree it is more a duplicate or a subissue, since we don't even show exit number yet, we can't pronounce it either.

**Comment by raindropsfromsky** [comment]
@vshcherb 

My point was that OsmAnd should use the magic word "exit" instead of the misleading ""turn slightly left/right". That fires the correct neurons in the driver's brain. :) 

So far, I have I added this issue to two bugs because they seemed to be similar in nature.
But both times you addressed only the main issue.

Should I raise this bug separately?

**Comment by raindropsfromsky** [comment]
p.s. I am trying to highlight a use case that is converse of the "U-turn" case:

where-
left turn+left turn = U-turn.

But-
Left turn+right turn = exit the road
(In countries where people drive on the right, this is "right turn+left turn")

**Comment by polarbearing** [comment]
OsmAnd already announces the target road, such as "turn right into ACB-street", thus that clearly indicates you change roads. If your link-roads have no names, you can add ```destination, destination:forward or destination:backward```, including ```destination:ref:*```, so you will get clear instructions matching your destination signs on the road.

**Comment by cmeeren** [comment]
> OsmAnd already announces the target road

...if you have enabled it in the settings. I have disabled it, because listening to the TTS engine trying to pronounce Norwegian road names cause more harm than help. :)

**Comment by polarbearing** [comment]
Google TTS claims to support Norwegian.

**Comment by raindropsfromsky** [comment]
@polarbearing 

If OsmAnd did announce something like  "turn right **into** xxx", I would have no complaints at all.
It only says "turn slightly left".

BTW I conducted some experiments, and IINW here is the reason:
The "turn into" is applicable only if the next road joins the first one directly.
But in my examples, the first joint that turs off the main road is a short link. 
Probably that's why OsmAnd does not announce "turn into" there.

So, OsmAnd  should evaluate what comes **after** the link, and announce it.
(Note that if the link is curved, it may have multiple line segments.)

So, in my example, OsmAnd should say: "in 200m, turn left and then right, to join xxx road"
(If there are two consecutive turns, we don't say "turn into")

**Comment by raindropsfromsky** [comment]
p.s. It is nice if mappers used tags for link roads.
But they don't. (Even I came to know about them just now, after reading your post. And I am a "[great mapper](http://hdyc.neis-one.org/)"!

**Comment by raindropsfromsky** [comment]
...And the reason is clear: Neither openstreetmap [wiki](http://wiki.openstreetmap.org/wiki/Key:highway) nor the **iD editor** give any importance to such obscure tagging. 

The mapper draws a way, and tags it as a link of appropriate type (primary/secondary...).
Note that even the [wiki page for a link](http://wiki.openstreetmap.org/wiki/Highway_link) does not describe the destination tag you described. 

In fact, there is no reasonable way to access any wiki page on the tags you described.
That means, only advanced mappers would be using these tags, and most links won't have these tags.

So, it is best if OsmAnd does not rely on these tags.
Instead, it should examine the local road network to decode the situation, and tell that to the driver.

This will forewarn the driver of what comes next.

Also note that the advanced highway engineering concepts are not used in developing countries. Thus we do not have exits, merge lanes, links, etc. OsmAnd should work well on these badly engineered roads also.

**Comment by cmeeren** [comment]
@polarbearing 
> Google TTS claims to support Norwegian.

Not Norwegian words in the middle of English sentences, I assume?

**Comment by polarbearing** [comment]
> Not Norwegian words in the middle of English sentences

So there would be two ways for you, either talk to Google to improve their TTS, or create the Norwegian speech templates in OSM. [Here is the Swedish](osmandapp/OsmAnd-resources/blob/master/voice/sv/ttsconfig.p) for example. These files are visible in your android device, so you can test them independently, and make a pull request to contribute it when it works.

> p.s. It is nice if mappers used tags for link roads. But they don't.

I do. Many others do. I feel insulted by your "they don't". What statistic is your claim based on? I see [over 250000](http://taginfo.openstreetmap.org/search?q=destination) tags in the destination tree, rapidly growing. 

[Destination is described well in the wiki](https://wiki.openstreetmap.org/wiki/Key:destination). If iD does not support it, open a ticket there. 

> Note that even the wiki page for a link does not describe the destination tag you described. 

Sorry, [I can read there](https://wiki.openstreetmap.org/wiki/Highway_link): 
- "Link roads normally do not have names. Please use the destination=* and it's extensions tag to give the cross-street's ref=* and signed destinations such as a city or the name of the destination street, so that routing engines can correctly announce the exit to the "name or ref of the destination street" as you enter the _link."

> So, it is best if OsmAnd does not rely on these tags.

I am quite happy that it supports them, and my [proposal](#2968) to implement destination:forward|backward was implemented witin 2 days - thanks @sonora + @vshcherb. 

No, OsmAnd should not make convoluted assumptions about road layout that can be fixed by better tagging. And it needs to make navigation announcements brief and concise, and not long and complicated.

**Comment by raindropsfromsky** [comment]
Hi polarbearing,

First, apologies if my post seemed insulting. That's a waste of effort, and only creates bad blood.
So next time you see anything like that, just assume best of intention from my side! :)

But when it comes to logic, we must do it without feelings attached.
So here goes:

1. How did you even _think_ of **destination** as a tag? Yes, once you searchj for it, you get plenty of stuff. but otherwise it won't come up as there is no advise on using this tag whenever you create a link.
2. Destination would be used for roads, and not for links, yes?
3. Of the total you quoted, how many are there in India (or for Asia, for that matter?)
4. What percentage of the links are tagged this way? how many of them in India/Asia? This is critical to answer your question.
5. I never suggested that OsmAnd should ignore the tag. I suggested that it should check what lies beyond the link. It helps people like us who live in poor countries</br>Incidentally, this issue is similar to the evaluating the **corner type** that @sonora described a few days ago: Rather than checking only the first segment of the link, OsmAnd should evaluate the link till a user-defined distance to determine what's the exit angle.

BTW if you compare the number of mappers and also per-mapper contribution, some European countries are far ahead of India (e.g. Germany, Netherlands). In India, most of the mappers only register, but don't contribute. They just make up a large number. Then it is unrealistic to expect that we will see sophisticated tags any time soon. We haven't mapped all the roads yet, forget POIs and tagging! So even if iD had that tagging capability, it won't help us!

The OSM file for entire India is smaller than some German cities, despite being #6 in the World in area, and #2 in the World in population, and #7 in the World in economy size.

So that was my appeal to help us out, considering our limitations.
