### ISSUE TITLE
OSRM routing error: Calculated route is empty

### ISSUE THREAD

**Issue by edwintorok** [osmandapp/Osmand#3055]
> What version of OsmAnd are you using, on what device and Android/iOS version?

OsmAnd~ 2.4.4, Android 5.1

> Do you use the offline maps offered within the OsmAnd app for download, or online (tile / raster) maps?

Offline maps

>__*In case of wrong routing:*__
> Tell us whether you have used OsmAnd's in-app offline routing, or any online routing provider like YOURS, OpenRouteService or OSRM.

OSRM gives me the error 'Calculated route is empty' all the time. YOURS works, and so does the offline/built-in routing.

> What routing profile is choosen in OsmAnd app? (car, bike, pedestrian, fastest or shortest)

Car, fastest.

> Please specify as exactly as possible the start and end point of your route by telling us city name and street name so that we can find it via in-app address search easily. Also a permalink from openstreetmap.org can be helpful.

Start: Timișoara, Timiș, Romania
End: Pensiunea Melba, DN57, Dubova, Mehedinți, 227170, Romania

Routing on openstreetmap.org and map.project-osrm.org works:
http://www.openstreetmap.org/directions?engine=osrm_car&route=45.7538%2C21.2257%3B44.6303%2C22.2629#map=9/45.2275/21.8188
http://map.project-osrm.org/?z=9&center=45.225118%2C21.817835&loc=45.753836%2C21.225747&loc=44.630343%2C22.262939&hl=en&alt=0

> Tell us your expected routing, and how OsmAnd routes, or add screenshots here.

OsmAnd fails to find a route with OSRM. OSRM used to work in the past though, don't know if its a problem due to new OsmAnd version or due to server-side changes.

This is from `adb logcat`:

```
E/net.osmand(12822): RouteProvider Failed to find route 
E/net.osmand(12822): org.json.JSONException: Value The of type java.lang.String cannot be converted to JSONObject
E/net.osmand(12822): 	at org.json.JSON.typeMismatch(JSON.java:111)
E/net.osmand(12822): 	at org.json.JSONObject.<init>(JSONObject.java:160)
E/net.osmand(12822): 	at org.json.JSONObject.<init>(JSONObject.java:173)
E/net.osmand(12822): 	at net.osmand.plus.routing.RouteProvider.findOSRMRoute(RouteProvider.java:1200)
E/net.osmand(12822): 	at net.osmand.plus.routing.RouteProvider.calculateRouteImpl(RouteProvider.java:318)
E/net.osmand(12822): 	at net.osmand.plus.routing.RoutingHelper$RouteRecalculationThread.run(RoutingHelper.java:833)
```

**Comment by osMatt** [comment]
Potentially this is related to the [shutdown of the old OSRM API](https://lists.openstreetmap.org/pipermail/osrm-talk/2016-September/001310.html). The URI [here](https://github.com/osmandapp/Osmand/blob/f30318bf49b58f679e2e6bc4de0563063600e08e/OsmAnd/src/net/osmand/plus/routing/RouteProvider.java#L1139) seems to be still using the old API version.

**Comment by vshcherb** [comment]
Is anybody aware of the new service provided?

**Comment by polarbearing** [comment]
Maybe the [changes on the OSM website](openstreetmap/openstreetmap-website/pull/1261) provide insight?

**Comment by osMatt** [comment]
I had a look at the [documentation of the new API](https://github.com/Project-OSRM/osrm-backend/blob/master/docs/http.md). Apparently not too much has to be changed in the Osmand code to make it work again.

An example URI with three waypoints returning a polyline object is this:
[`http://router.project-osrm.org/route/v1/driving/13.388860,52.517037;13.397634,52.529407;13.428555,52.523219`](http://router.project-osrm.org/route/v1/driving/13.388860,52.517037;13.397634,52.529407;13.428555,52.523219)

Therefore, in the Osmand code the following changes are necessary in RouteProvider.java:
- Replace `://router.project-osrm.org/viaroute?alt=false` with `://router.project-osrm.org/route/v1/driving/`
- No `&loc=` is needed before the first lat long pair
- The function to add (additional) coordinates needs to be changed to make `;` the separator (instead of `&loc=`
- Note the change the order of lat and long in each coordinate pair so `getLatitude()` and `getLongitude()` need to be switched
- The polyline object is called `geometry` (not `route_geometry`, [line 1164](https://github.com/osmandapp/Osmand/blob/f30318bf49b58f679e2e6bc4de0563063600e08e/OsmAnd/src/net/osmand/plus/routing/RouteProvider.java#L1164) needs adjustment)

I am not sure about adding the `?overview=full` option at the end of the URI. This might be useful as it returns a more detailed (not simplified) route geometry.

**Comment by vshcherb** [comment]
If somebody needs it soon, please feel free to create pull-request to this file https://github.com/osmandapp/Osmand/blob/master/OsmAnd/src/net/osmand/plus/routing/RouteProvider.java#L1180

**Comment by sonora** [comment]
I have merged the fix, so we can test.

**Comment by Zahnstocher** [comment]
With overview=full the geometry looks better.
We also need a small polyline decoder change:
https://github.com/osmandapp/Osmand/pull/3104
