### ISSUE TITLE
Turn restrictions missing in current offline maps

### ISSUE THREAD

**Issue by IntendedCrash** [osmandapp/Osmand#3067]
It seems the turn restrictions are missing within the offline maps from 09/01/2016 (at least in Germany - tested within Bavaria and Hesse). When using OsmAnd offline navigation (car mode) with the current version of the maps, the router ignores any turn restriction. However previous version of the same map (07/01/2016) works fine.

Tested with OsmAnd 2.4.4 and 2.4.6.

**Comment by vshcherb** [comment]
I can't recall any change to the generation process in that area, so we might need to double check it by regenerating map

**Comment by kreuzschnabel** [comment]
See discussion on German user forum: http://forum.openstreetmap.org/viewtopic.php?id=55758
Osmand could be pushed into ignoring each of TR on the junction given by appropriate routing requests.

Osmand+ 2.4.6, standard map of 01.09.2016, Android 6.0.1.

Since I never had such occurrences before, I suspect a bug in the latest maps. However, there also has an Android update taken place last weekend, which might contribute to the malfunction.

--ks

**Comment by polarbearing** [comment]
Confirming the bug in the Germany/Brandenburg map, [this restriction](https://www.openstreetmap.org/relation/84453) is ignored in the September map, and complied with in the August map.

Screen shots will follow.

**Comment by dinamit123** [comment]
Same issue with the latest map of Moldova. Turn restrictions are ignored. (Osmand 2.4.6)

**Comment by vshcherb** [comment]
Fixed, new maps should be generated.

**Comment by polarbearing** [comment]
Found a new Sep-1 map generated and available on Sep 18, and confirm fix for my example.

**Comment by tarator** [comment]
There was the same problem with the Austrian map (noticed it multiple times in Vienna). I updated OsmAnd+ (via Google App Store) and the map yesterday. A quick check shows me that are Turn Restrictions are working again with this version.
