### ISSUE TITLE
"Great Britain" displayed in the centre of GB maps since September update

### ISSUE THREAD

**Issue by njohnston** [osmandapp/Osmand#3074]
Since the 1st September map update, "Great Britain" is displayed in the centre of GB maps (England and Scotland at least) at zoom levels 13 and higher.

According to a [discussion on the OsmAnd forum](https://groups.google.com/forum/#!topic/osmand/w9111YDV_r8), this is caused by someone adding [place=island for Great Britain](http://www.openstreetmap.org/api/0.6/relation/6038068).

This "Great Britain" label is distracting and annoying. It appears over paths and roads, even in navigation. Examples:

![osmand_gb_1_small](https://cloud.githubusercontent.com/assets/638458/18482042/8676512e-79d6-11e6-82e3-101d5ebafb41.jpg)
![osmand_gb_2_small](https://cloud.githubusercontent.com/assets/638458/18482050/8bb9a442-79d6-11e6-9ec6-86ed0c2fc73d.jpg)

Here, the label appears in a very similar font as labels on parts of the castle:

![osmand_gb_3_small](https://cloud.githubusercontent.com/assets/638458/18482054/9265aa66-79d6-11e6-8d62-a9f22c3e2f9a.jpg)

Can this tag be ignored for future map updates so that "Great Britain" isn't displayed like this?

Can this label be hidden using a custom rendering style?

**Comment by RedKobold** [comment]
I think that this issue should include all polygon types. The same problem occurs with any large polygon regions, for example nature reserves.

It may be better to limit the appearance of the polygon name so that it is only displayed when most of the polygon is visible (opposite edges for example), irrespective of zoom level.

**Comment by rogerjames99** [comment]
I think the general case of handling large area polygons should be raised as a separate issue. It is difficult to see how it can be resolved in a way that is not computationally intensive. It would probably need analysis of the polygon data itself.

However the case that has highlighted this is due to the rendering of tags on a multipolygon relation. Specifically the place=island name=xxxxxxx pair. The place=island tag is normally only allowed on single polygons. However there is an exception to this rule for "large islands" (>2000 nodes) when the tag must be placed on a multipolygon relation. The raiser of this bug asks a good question.

"Can this label be hidden using a custom rendering style?"

So could this be fixed by treating a multipolygon relation with a place=island tag as denoting a large island and handle that as a special case, and can this be detected in the rendering XML?

Roger

**Comment by xmd5a2** [comment]
It's not possible to fix this issue by rendering style. Preprocessing is needed.

**Comment by njohnston** [comment]
@xmd5a2: that's a shame. The rendering XML contains:

```xml
<case minzoom="11" tag="place" value="island" nameTag="" textSize="14" textOrder="113">
  <apply_if minzoom="16" textSize="16"/>
```

What is this for? place="island" is checked in some other places too.

**Comment by xmd5a2** [comment]
@njohnston it is possible to remove text from "place=island" tag or limit it by zoom but keep in mind that there are very small islands (less than 1 km in diameter) whose names will not be displayed at all.

**Comment by njohnston** [comment]
@xmd5a2: how do I change what zoom levels the label appears at? This could be a useful temporary fix.

In the XML that I included, can the name ("Great Britain") in this case be specified in the nameTag attribute?

**Comment by xmd5a2** [comment]
@njohnston
```xml
<case minzoom="11" maxzoom="14" tag="place" value="island" nameTag="" textSize="14" textOrder="113"/>
```
nameTag will not work that way. It is used to specify a TAG not tag's value.

**Comment by rogerjames99** [comment]
#xmd5a,

Any chance you could give us a clue on what to put in a custom render XML 
to kill all the island names as a short term workaround.

Roger

**Comment by xmd5a2** [comment]
@rogerjames99 just remove lines 4610-4612

**Comment by njohnston** [comment]
@xmd5a2: sorry for bothering you again--I don't like changing the default rendering file. I already have my own custom rendering file. What's the minimum I need to put in there to make this work?

**Comment by xmd5a2** [comment]
@njohnston 
```xml
    <text>
        <case  tag="place" value="island" disable="true"/>
    </text>
```

**Comment by njohnston** [comment]
@xmd5a2: thanks for your help. Your suggestion worked but I went for this compromise:

```xml
  <text>
    <case tag="place" value="island" minzoom="14" maxzoom="22"/>
  </text>
```

This will show the labels at zoom 13 but nowhere else, so I can see them if I want, but not at all the time :)

**Comment by rogerjames99** [comment]
<﻿renderingStyle name="IslandKiller" depends="default" 
defaultColor="#f1eae4" version="1">
<text>
   <case tag="place" value="island" disable="true"/>
</text>
</renderingStyle>


Thanks  @xmand5a

Works a treat.

Roger

**Comment by cepesko** [comment]
Noticed the same thing last summer when travelling on the island of Madeira. Was really annoying seeing it in the centre of the screen all the time. Would keep me away from using osmand as a local inhabitant, knowing which island I live on.

**Comment by xmd5a2** [comment]
@cepesko I have limited island names to zoom 16 as temporary solution.

**Comment by rogerjames99** [comment]
@xmd5a2 The custom rendering has stopped working on the current version.  Is this due to your recent change?

Here is what I was using.

<﻿renderingStyle name="IslandKiller" depends="default" defaultColor="#f1eae4" version="1">
<text>
   <case tag="place" value="island" disable="true"/>
</text>
</renderingStyle>

Roger

**Comment by rogerjames99** [comment]
Oops forgot to quote the xml.

`<﻿renderingStyle name="IslandKiller" depends="default" defaultColor="#f1eae4" version="1">
<text>
   <case tag="place" value="island" disable="true"/>
</text>
</renderingStyle>`

**Comment by vrtareg** [comment]
Hi 
I still can see this in latest nightly with November maps. 
Haven't tried December one yet. 
Do I need manually add renderer code? 
Regards, 
Areg

**Comment by rogerjames99** [comment]
My custom renderer ceases working as I mentioned above. Since then the text has appeared and disappeared. It also seems to depend on where you are in the UK! I have not got a clue what is going on.

**Comment by vrtareg** [comment]
I am driving between Cambridge and St Neots and I can see this all over on the map.

![screenshot_2016-12-05-08-55-07](https://cloud.githubusercontent.com/assets/2562730/20905064/3cd7a108-bb3a-11e6-8746-171b346d446a.png)
![screenshot_2016-12-05-17-58-02](https://cloud.githubusercontent.com/assets/2562730/20905075/463ed63a-bb3a-11e6-9694-595a6cebefd1.png)

**Comment by sonora** [comment]
@vshcherb I guess a solution needs to be along these lines: We should not attach island names (and maybe he name of some other potential large are features, like military areas, etc.) to the area itself, where we have a mechanism in place to make sure the label remains visible on the screen even when you zoom far in to where there is only a portion of the area visible on the screen.

Instead, we should attach the name to an (invisible) point node (static, and somewhere in the center of the area). When you zoom far out, the point is in the viewed screen area and its name will be visible, but when you zoom further in, usually the node would at some point end up outside the area you are viewing on the screen and its label would disappear as well.
