### ISSUE TITLE
Storing GPX track does not add .gpx suffix and doesn't show keyboard

### ISSUE THREAD

**Issue by Unnamed-1** [osmandapp/Osmand#3125]
Version: 2.4.6

There is a minor issue with the navi route details dialog. When I try to store that as GPX track (the floppy icon) then:
1. the keyboard is not shown. I have to type the text field once.
2. When ".gpx" is not added manually, the stored file seems not to get the correct file name ending. Therefore, it's not displayed in the map configuration options later (GPX track selection).

**Comment by sonora** [comment]
(1) is by design: The default is to just use the date, so if you want to accept this, no need to mess with the keyboard, just hit "Save". If you want to change anything, just tap in the text field the keyboard will appear.

(2) The file extension is hidden by default, so you cannot accidentally change it. The file is named and appears all right, I have just checked.
