### ISSUE TITLE
(please ignore)

### ISSUE THREAD

**Issue by bjohas** [osmandapp/Osmand#3174]
(please ignore)

**Comment by vshcherb** [comment]
Anyway I would cc @sonora on this request cause we need to review new strings anyway.
Original request
Time before logging -> Logging interval. "Time before logging" suggested to me that there would be some time before the first log.

Retry time interval for accuracy -> Duration to improve accuracy. "Retry time interval" suggests several events, rather than a duration.

Absolute timeout -> Time to (initial) GPS fix. "Absolute timeout" suggested to me that this would be for the whole operation (initial fix + improved accuracy).

**Comment by bjohas** [comment]
.... except that those weren't osmand strings! :)

I'd be happy to review strings though if it's needed.
