### ISSUE TITLE
Navigation notification

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/Osmand#3207]
After click Pause on Navigation notification, notification disappears and does not appear again.

**Comment by sonora** [comment]
In addition, there is the following glitch:

When manual trip recording (started via the GPX widget) is active, and then a navigation (in follow mode) is started, the navigation notification does not disappear again after the navigation was stopped (neither is the GPS wakeup-interval reset to what it was before). Both are only corrected when the manual trip recording is stopped. (This all worked directly with the old notification).

**Comment by sonora** [comment]
@crimean Reset of the GPS wakeup interval still broken, as follows:
- Start GPX logging via the widget, interval 30 sec. (You can verify this works ok and GPS correctly goes to sleep between measurements by putting OsmAnd in the background and watching the behavior of the Android GPS icon in the notification bar).
- Now start a navigation in Follow mode. -> GPS wakeup will correctly go to continuous, even when the app is in the background
- Now stop the navigation again: GPS wakeup will remain continuous, instead of correctly going back to 30 sec.

**Comment by vshcherb** [comment]
@sonora first I think you slightly took over of the original issue, which is about notification dissappears. Second, I think we could discuss it here, I'm afraid it is not that critical issue in sense we won't be able to do it before release.
Last week I was struggling to get it down to reasonable size and we can't move release too much off this week cause of other plans. 

I don't mind if you open another issue though it won't be 2.6. It would be great if we could help Alexey on such small issues though I'm afraid we need to keep going now.

**Comment by vshcherb** [comment]
https://github.com/osmandapp/Osmand/commit/0570e872073acfe020690c763c8fa5bf68ac5a43
looks like this is related to the fix you mentioned.

**Comment by sonora** [comment]
Sure. It is a clear regression, appeared after the introduction of the new Notifications, that's why I thought it fits here. But it is not a critical one (transferred it to #3604). Maybe next week I can have a look myself, I think I had implemented the prior solution years ago which worked until we created the new Notifications.
