### ISSUE TITLE
How to donate

### ISSUE THREAD

**Issue by guettli** [osmandapp/Osmand#3227]
I found this in the README on github:

> It is also possible to fund specific new features, or to make a general donation on http://osmand.net.

I look at above page, but could not find a entry matching "donat.." (ctrl-f on html page).

Please tell me how to donate :-)

**Comment by RealRancor** [comment]
Seems its possible via Bitcoin: http://osmand.net/help-online#buy_app

**Comment by guettli** [comment]
Know I know more. But only me. Who can update the README?

**Comment by sonora** [comment]
Fixed, thanks!

**Comment by bonanza123** [comment]
Can you also be a bit more precise how to "to fund specific new features"?

**Comment by sonora** [comment]
A quick search reveals this http://www.bidforfix.com/p/osmand.net/, but I am not sure if this is not deprecated ... @vshcherb .

**Comment by vshcherb** [comment]
We can't take donations from the user because they could come with obligations. For example it takes much more efforts to create 3D rendering than people could contribute. The best donation for us is a paid subscription, in that case we have a guaranteed budget and we can focus on difficult features like 3D. 
May be we will introduce different subscription prices, so people could contribute more or less.

Also just as a side effect, donations are not that easy to convert into a legal income, so we mostly stay away from it.

**Comment by bonanza123** [comment]
@vshcherb with paid subscription you mean [osmand live](http://osmand.net/osm_live) ? May I kindly request to update the README with the full details how to donate / subscribe? I guess that is in particular needed for F-Droid users who more or less use the full version for free and can't / don't want to buy the app because of the google stuff required for that.

**Comment by vshcherb** [comment]
@bonanza123 yes I will, though for today, the only way will be to donate to the BTC address http://osmand.net/osm_live.php (1GRgEnKujorJJ9VBa76g8cp3sfoWtQqSs4)

**Comment by nakic** [comment]
> We can't take donations from the user because they could come with obligations.

I disagree. I would like to donate as gratitude for using the free version so far: no future obligations. I'd be extremely surprised if I was the only one.

> May be we will introduce different subscription prices, so people could contribute more or less.
> Also just as a side effect, donations are not that easy to convert into a legal income, so we mostly stay away from it.

I do not accept Google Play's ToS, do not want Google to know my credit card number and do not want to finance them (which is why I've been using the free version of the app). I would love to give OsmAnd a, say, 50 Euro donation as a token of gratitude: it's a disappointment that there's no obvious way to do it.

**Comment by Iey4iej3** [comment]
I hope that osmand will offer methods to donate like through liberapay. I don't use bitcoin. I tried, and found that to buy bitcoins documents like passports and selfie are necessary, which I am reluctant to offer.

**Comment by scaidermern** [comment]
> For the moment I donate to OSM Foundation. I don't know whether it is closely related.

OSMF and OsmAnd are completely different and not related at all.

**Comment by vshcherb** [comment]
OSMF is worth to donate anyway cause it stays behind OSM maps which are used in many other apps as well and what makes OsmAnd successful too.

**Comment by scaidermern** [comment]
> OSMF is worth to donate anyway cause it stays behind OSM maps which are used in many other apps as well and what makes OsmAnd successful too.

Yes, definitely!

**Comment by naomap** [comment]
> > We can't take donations from the user because they could come with obligations.
> 
> I disagree. I would like to donate as gratitude for using the free version so far: no future obligations. I'd be extremely surprised if I was the only one.
> 
> > May be we will introduce different subscription prices, so people could contribute more or less.
> > Also just as a side effect, donations are not that easy to convert into a legal income, so we mostly stay away from it.
> 
> I do not accept Google Play's ToS, do not want Google to know my credit card number and do not want to finance them (which is why I've been using the free version of the app). I would love to give OsmAnd a, say, 50 Euro donation as a token of gratitude: it's a disappointment that there's no obvious way to do it.

Has there been any move on this topic since 2019 ? I do really want to make a donation to OsmAnd as this is such as great tool. I would be happy to subscribe to OsmAnd Pro however I do not want to register my credit card number on the PlayStore. Is there any other way I can show my gratitude ?
