### ISSUE TITLE
Problem with opening hours with times span over midnight

### ISSUE THREAD

**Issue by quelbs** [osmandapp/Osmand#3229]
As an example https://www.openstreetmap.org/node/198204777
OSM Data: opening_hours=Mo-Th 07:00-01:00, Fr 07:00-02:00, Sa 07:00-02:00, Su 08:00-01:00
Osmand Displays: Mo-Th 07:00-01:00, 07:00-02:00, 07:00-02:00, 08:00-01:00

From Fr-Su the location is always shown as closed although it is defined as open in the OSM Data.

According to http://wiki.openstreetmap.org/wiki/Key:opening_hours the OSM Data is correct. "Because of the definition that following rules will overwrite previous once, times which span over midnight have to use additional rules which are separated by comma instead of semicolon."
Also the opening hours evaluation tool at [http://openingh.openstreetmap.de/evaluation_tool/](http://openingh.openstreetmap.de/evaluation_tool/?EXP=Mo-Th%2007:00-01:00,%20Fr%2007:00-02:00,%20Sa%2007:00-02:00,%20Su%2008:00-01:00) shows the opening hours as they are.

**Comment by vshcherb** [comment]
Proper delimiter is ';' between days.

**Comment by quelbs** [comment]
That was my initial thought, too. But when I had a look at the Wiki before adjusting the OSM data I figured out that if the opening time of the day goes beyond midnight the proper delimiter is ',' as stated in the quote from the wiki above.

**Comment by vshcherb** [comment]
Yes wiki has changed several times and instead of original ';' which was always work in Osmand they went to incredibly complex format. Though most of the programs support ';' now they specially quote for ',' and as I know very few have correct support.

Here we have a list what is not supported https://github.com/osmandapp/Osmand/blob/master/OsmAnd-java/src/net/osmand/util/OpeningHoursParser.java#L1507 ( and ',' is 2nd). I hope in future we will be  able to support it, but unfortunately not now.

',' in OsmAnd could be used only for week day, day delimiters, but not ax rule delimter
