### ISSUE TITLE
osmand forgets old data directory

### ISSUE THREAD

**Issue by onnokort** [osmandapp/Osmand#3288]
Hi,

I have a Samsung S4 with the osmand directory originally set up on the SD card, 

`/storage/extSdCard/osmand`

First of all, whenever I open osmand now, I get the 'first steps' screen. When I close osmand than and reopen it, I usually get the main screen after 2-3 tries.

Then, it appears that osmand loses the location of the data directory periodically, and creates a data directory 'osmand' one level below where the actual osmand data should live. This has the effect that currently, on my cellphone, osmand has the data directory path set to something like this:

`/storage/extSdCard/osmand/osmand/osmand/osmand/osmand/osmand/`

I didn't do that.

I also have intermittent problems to write to the SD card while recording a track, so this might be related to #3105.

When I reset the data directory in the settings screen to `/storage/extSdCard/osmand/`, osmand sometimes works properly and sometimes it doesn't (no map shows, but other functionality seems to be fine). 

Whenever I close it and open it again later, it will usually jump one directory level deeper, with an additional osmand/ subdir. Regardless of whether it managed to display the map correctly.

This is on Osmand 2.5.3, Samsung S4 GT-I9300 with Android version 4.3. I use offline maps.

**Comment by sonora** [comment]
Can you elaborate on what occasion this first happened, was it a first installation of OsmAnd, and update, after you changed the storage folder, etc.?

My first suspicion would be a defective SD card or SD file system. Does it also happen when you use /storage/emulated/0, or with another SD card?

**Comment by onnokort** [comment]
> Can you elaborate on what occasion this first happened, was it a first installation of OsmAnd, an update, or after you changed the storage folder, etc.?

I believe it started to happen with a more recent update to Osmand. I see this behavior since maybe a month or two. I didn't change the storage folder.

> My first suspicion would be a defective SD card or SD file system. Does it also happen when you use /storage/emulated/0, or with another SD card?

Now that I ponder about this, that might be a good point. Since I have this cellphone (5 years?), I have *occasional* issues with the SD card reinserting itself. It happens quite rarely though (maybe twice per month?), and I don't have issues with other applications saving to or reading from the card, such as the camera/gallery or my media player. Tried to clean contacts, didn't help, never figured that one out.

Should I try moving the whole folder to internal storage and see whether OsmAnd still behaves like it does? Can I do that, or will something break? (I would do a simple 'mv' command after mounting the cellphone with jmtpfs).

OsmAnd was not having this 'extra' folder behavior before.

**Comment by sonora** [comment]
From my experience with countless test devices over the years, I would try the following:

**(1)** "Refresh" your existing SD card. This costs no money, only some time: Use a PC, connect your phone to it via a USB cable. Copy the entire content of the SD card to a folder on your PC (using Windows Explorer or some equivalent file manager software). Then, using the Android Storage/Memory menu on your phone, format the SD card. Afterwards, copy the entire contents of your backup folder back to the SD card.

**(2)** If tis does not help, you may want to try a new SD card. If you copy all data over from the old to the new one (similar to what I describe above), then swap them, you will not lose any data either.

**(3)** As an alternative experiment, you may also just try, within OsmAnd, to change the data folder to internal memory. OsmAnd has a menu item in General Settings  to do this, and also asks if it should copy the data (but you can also do this manually outside OsmAnd). If you copy all data in the entire OsmAnd folder to the correct new folder, you will not lose any data or functionality (and you can keep a backup copy of your data in the original location, or elsewhere). But check if you have enough space available in the internal memory, the map data is potentially huge, and on older devices internal memory may not be big enough.

I guess there is a pretty good chance that this issue is SD card or other hardware related. I would be surprised if this was an OsmAnd issue, because I have never seen it, and know of no other user reports.

**Comment by onnokort** [comment]
Moving osmand to internal storage seems to have fixed this problem! Also, thanks for the general suggestion regarding the SD card, I did a reformatting from Android and hope (that needs more time to gather statistics on, though) this will fix the reinsertion issue I have (what a mess the filesystem handling seems to be).

**Comment by 1aladdin1** [comment]
@onnokort how can you close this issue at this point? Apps have troubles with data especially on external SD card - due to the ever changing Google API for accessing removable media. imho evading to internal memory is not a solution.

**Comment by onnokort** [comment]
I was fine with the workaround by @sonora. Of course I'd be happy with more robustness on all fronts, but I am purely an osmand user - so I think you devs should decide whether to leave it open or close it ...

The one peculiarity is the string of osmand/osmand/osmand directories - I guess I could make a minor suggestion there to maybe display a message when creating an 'osmand' subdirectory and telling the user that if that happens repeatedly, that it there might be an issue with the underlying storage of something. And/or maybe check for such a nested directory situation.

Also, if the reformatting fixed my SD (as I said: I am not sure yet), I'd locate the bug rather in the external storage handling of Android than in osmand, or do you disagree?

**Comment by 1aladdin1** [comment]
As offline map files are usually huge, many users run out of internal memory capacity. So capabilities to handle external SD cards is crucial for usability of OSMand.

@external storage handling: I agree. Googles changes API for handling removable media in every version in an attempt to enhance security. This is OK,  but on the other hand requires app devs to update their code accordingly.
