### ISSUE TITLE
Change non-free assets

### ISSUE THREAD

**Issue by mobtechpd** [osmandapp/Osmand#3291]
Please change non free assets with free ones

**Comment by vshcherb** [comment]
What exactly the issue is about?

**Comment by julianfairfax** [comment]
It's about this: https://github.com/osmandapp/Osmand/blob/master/LICENSE#L52 (they're probably referring to https://github.com/osmandapp/Osmand/blob/master/LICENSE#L55 too but changing that is unrealistic)
![image](https://user-images.githubusercontent.com/43753131/143722141-8a48ca21-6ca4-40d1-abcb-4d2a6d2c7769.png)

**Comment by julianfairfax** [comment]
I also support changing the icons since they're the relevant non-free part (I don't know where you got the voice recordings from but I doubt you can get a free version of those), and there's no real *point* having 75 non-free icons when you can probably find (or create, if you have a designer willing to do it) a free version of those icons.
