### ISSUE TITLE
Quick search should list the locality

### ISSUE THREAD

**Issue by raindropsfromsky** [osmandapp/OsmAnd#3327]
The Quick search results show the name of the POI (e.g. "Dominos"), type of POI (e.g. "Restaurant"), distance and direction.

But if there are multiple outlets of the same chain, and we want to pick a particular one, it is a difficult task.
The distance+direction are not much useful in guessing the locality of the POIs.

If the search result shows the locality name also, choosing the right target becomes easy.

**Comment by sonora** [comment]
I am not sure how difficult this is to implement, but I have in deed also several user requests asking to have some better way of identifying search hits in the result list by also adding the locality.

Sometimes you look for a chain store, and there may be many all over the place, but you have a certain area/suburb you would prefer to go to (maybe because of parking facilities you know, or you need to go near there anyway), so it would be good to be able to pick one with less "trial and error" of tapping one, looking at the map, then go back and tap another one.

**Comment by raindropsfromsky** [comment]
That's exactly what I had in mind, too!

Two use cases I had in mind:
1. someone gives you directions to a spot near that particular POI 
2. Someone recommends THAT specific joint because of better taste/service,.....

**Comment by Hjart** [comment]
The danish OSM mailing list discussed this issue a few days ago.
Some mappers tend to add the name of the street shops are at or the village it's in to the name of the shop, so we end up with e.g. "Netto Mainstreet" or "Netto Smallvillage". This of course helps a lot when doing quick searches in Osmand etc.
But personally I'm not a big fan of adding "place annotations" to the shop name and I see in https://wiki.openstreetmap.org/wiki/Shops#Name that I'm not the only one.
I think it could prove difficult to automatically produce meaningfull "place annotations" (since in some cases the street is more meaningful and in other cases the village etc), so how about inventing an OSM tag called "locality" or ""place_annotation" which could be displayed next to the shop name in search lists?

**Comment by DFyson** [comment]
The branch tag might be useful (at least for banks). Location annotation would be nice, but that would require widespread adoption in OSM before it becomes useful. How about generating a short meaningful address below it? For example the street it's on, the cross street (a major one if close by), or the name of the mall if it's inside one, any 'significant' POIs in close proximity, etc. And omitting common information such as the city or country if they are all the same. It would be a little challenging, but I suspect someone could come up with a good algorithm for displaying a concise meaningful location.

**Comment by Hjart** [comment]
To me the [branch](https://wiki.openstreetmap.org/wiki/Key:branch) tag appears perfect for identifying the location of individual branches. Anyone interested are hereby encouraged to promote it some more.

**Comment by jfburke3** [comment]
I want to add my support to this request.

**Comment by mutipg** [comment]
Similar issue:
[[Feature Request] Show address in search result #9586](https://github.com/osmandapp/OsmAnd/issues/9586)

**Comment by mutipg** [comment]
Is there any chance to add this feature to OsmAND?

**Comment by yaomtc** [comment]
Using "branch" would depend on whether that place has a branch tag. Many do not. More useful to me would be street and neighborhood/community area.

**Comment by EvanCarroll** [comment]
I don't think street is very useful at all. Who actually knows the name of the street you're traveling too when you use search -- most of the time not me anyway. I can see the administrative boundary being useful, but it's not nearly as useful as branch (if available). I wonder how many cities even have these divisions? Certainly megacities do, but many cities just have downtown/midtown suburb designations and a mayor. 

It seems like the starting point here, should be "branch" if available. And then functionality afterward should better handle when Branch isn't available.  For reference to the OP, the Domino's branch name is the actual street: https://www.dominos.com/en/pages/order/#!/locations/search?type=Carryout&c=Houston%2C%20TX&s=&locationName=

**Comment by yaomtc** [comment]
Why not use both? Often, data will not be available for "branch". If this is missing, the street name should be shown instead of nothing.

**Comment by EvanCarroll** [comment]
Fully agree, anything is better nothing and if branch isn't available I'll take literally anything that helps disambiguate but this is more technically complex, less direct (while it may help, it's not certain to help like Branch), and it's not certain to be unique for the POI. Just trying to help prioritize this issue, I can see something like this getting, but I can't see it being preferred to `branch` which was first mentioned years ago.

**Comment by vshcherb** [comment]
Merged to https://github.com/osmandapp/OsmAnd/issues/2993
