### ISSUE TITLE
Search issue related to favourites

### ISSUE THREAD

**Issue by xmd5a2** [osmandapp/Osmand#3338]
Imagine situation: user have 100 favourites in fav group "Moscow". If he wants to search something (address, poi) in Moscow, he types "moscow" and gets huge list of favs. It is not clear what to do in this situation because non-fav search results are at the bottom of list. User can think that whole search is favourite search only (real situation in my experience).

**Comment by sonora** [comment]
I guess this is equivalent to #3062, and should be fixed in the same way: It is a simple matter of the order in which we display the results. Cities, towns, then vilages and other settlements need to be sorted to the top, only then lower-ranking (more specific) results like street names or Favorites. Good test examples are e.g looking for "Roma" on an Italian map, or for San Francisco.

**Comment by vshcherb** [comment]
Disagree #3062 is fixed by fixing order. Here we need somehow to limit the search i.e. make it available only on Search more button.

**Comment by sonora** [comment]
Why not just also fix it via order here?
