### ISSUE TITLE
[Feature request] different colors for different GPX routes

### ISSUE THREAD

**Issue by arteme** [osmandapp/Osmand#3345]
OsmAnd does a great job of visualizing imported GPX routes and the appearance of GPX routes can be changed, but it affects all routes shown. Sometimes when visualizing multiple routes, it is useful to give them different styles so as not to get confused as to which is which.

**Comment by njohnston** [comment]
@arteme: this is already supported. Open the main menu and then select "My Places". Tap the "My Tracks" tab:

![osmand_my_tracks_1_small](https://cloud.githubusercontent.com/assets/638458/21141323/69e7305a-c134-11e6-984d-be296859f99e.jpg)

Tap a track you're interested in, and then tap the top right map icon:

![osmand_my_tracks_2_small](https://cloud.githubusercontent.com/assets/638458/21141333/75f8e3ac-c134-11e6-9b1e-bc5fd28bde09.jpg)

Now tap "Show on map" and select the colour you want.

If this is not enough, you can also open your GPX files in a text editor on a computer and insert a custom colour by putting this XML into the `<trk>` tag:

```xml
<extensions>
  <color>#aafaf700</color>
</extensions>
```

Make sure you specify an alpha value (the first part of the colour--aa here), as otherwise the line for the route or track won't be transparent, and will obscure details on the map.

**Comment by arteme** [comment]
Wow, thanks a lot!
