### ISSUE TITLE
Don't show hill shading at high zoom levels

### ISSUE THREAD

**Issue by ejain** [osmandapp/Osmand#3359]
When hill shading is enabled, the boundaries of the shading tiles are very visible at high zoom levels. Perhaps an option could be provided to disable hill shading above a certain zoom level?

![screenshot_20161215-170714](https://cloud.githubusercontent.com/assets/1323903/21443363/036330a6-c87b-11e6-846a-d6fb2582182c.png)

**Comment by sonora** [comment]
I would argue it is a bug with our hillshade files, it should be solved by creating new hillshade data rather than suppressed at high zoom levels.

**Comment by littlehelper** [comment]
From my point of view, when using zoom levels higher than 16/17, most times I am not able to "see" hills anymore (when looking at the hillshades) because the hill (shade) covers the whole display. Ok, but the whole display gets darkened due to the hill shadow and map readability gets worse.
Therefore introducing a maximum zoom level for displaying is a good idea in my opinion.
(Idea: keep a slider for quickly enabling/disabling the hillshades and additionally provide a submenu for generally setting a min/max display level, see also #3192)

**Comment by sonora** [comment]
Yes, probably true!

**Comment by DFyson** [comment]
I like the min-max slider idea. For reference, the hillshade rendering issue is #2183 and is a problem with OsmAnd, not the tiles.

**Comment by vshcherb** [comment]
New hillshade data will be 4 times bigger at least. I like idea of max zoom, though it is not applicable for all areas. Possibly we could set it to 19 only (18?)

**Comment by littlehelper** [comment]
I prefer to have a submenu of the 'Configure map' > 'Hillshade layer' menu entry (like 'Overlay map...' and 'Underlay map...' have) to set a min and max zoom level in the submenu.
Default could be 18/19, I would set it to 16/17 depending on the region.

The same 'menu with quick slider and submenu with min/max zoom level settings' concept would be perfect for customizing the display of contour lines (ref. #3192).

**Comment by aceman444** [comment]
So was this fixed in OsmAnd 3.6 already?

**Comment by vshcherb** [comment]
in 3.7 settings were introduced
