### ISSUE TITLE
[Feature request] much larger zoomfactor when driving on a motorway

### ISSUE THREAD

**Issue by harvey637** [osmandapp/Osmand#3382]
Hi,
when you drive on a motorway you normally drive long distance.

Abstract: change autozoom behaviour on a **motorway** independent of speed.

My personal idea is, that without a destination the shown distance on the screen 
- when driving on a **motorway** 
should be something like **50 km**. This has nothing to do with speed, even when there
is a traffic jam or slow driving I am interested in the "big picture", not in the nearest 100m or 500m.
Most likely I am looking for a way to circumvent a jam, and it is normally to the next exit/entry that is 15 km ahead. Manual zooming is annoying, as it zooms back after autozoom-timeout.

Also the speed sensitive autozoom causes lots or in- and out-zooms. This is specially true, when
your vehicle is a bit slower and driving 100km/h +/- 10 km/h.
- With a destination (or intermediate waypoint) set zoom should be also around 
**50km or the distance to your destination, whatever is nearer**. So you see 50 km until you destination comes into sight.

After leaving the motorway and driving in the city autozoom works great, but I dont want to change
anything in the configuration while driving.

Also the wording "slightly turn left/right" may be correct from the angle of turn, but is a more important move. So "leave motorway at the next exit" might be more appropiate (or "leave the motorway at exit number xxx," if exits are numbered).

just some idea to make it less distractive while driving
cu
Harvey

**Comment by pebogufi** [comment]
1++
A larger zoomfactor on motorways would make me happy.
Peter

**Comment by sonora** [comment]
Some quick feedback:
- Are you aware that Auto Zoom can be disabled?
- Are you aware that there is a setting "AutoZoom: To long range"? (although it may not be long enough for what you are suggesting here)
- For the "extra long range": When I am on the motorway and am interested in the "very long" range (on long drives my set range is several hundred kilometers), you can simply adjust the zoom you want by tapping on the + or - zoom buttons in the lower right corner of the map screen, to your liking. The map will still follow you, and you can adjust to precisely the zoom factor the situation requires, that's how I do it. I think this manual way is superior to any automatism or additional setting, because it can vary quite a bit what range you prefer in different situations.

**Comment by Doogse** [comment]
Yes, long range zoom is useful at times especially on long journeys.
Most of the time osmand handles the zoom level 
fairly well. It would however be useful to have some method of switching to long range instantly for a selectable time ( say 5 - 10 seconds) either by a screen button or perhaps a double tap on the map. The selectable time could also have an option to stay in long range and only return on another press of a screen button or double tap on the map again. Manually zooming in and out is too distracting whilst driving, but a double screen trap would be ok.

**Comment by sonora** [comment]
@Doogse: Sounds like 2-finger tap is your solution, have you tried it?

**Comment by Doogse** [comment]
Yeh, I realised that it was already being used to zoom in so that's not an option unless it could be a special area to tap like an unused corner of the screen somewhere.

**Comment by harvey637** [comment]
Hi,
Im happy with some answers and will try 2-fingers.
yes, autozoom can be disabled or adapted, but:
- changing the autozoom while driving is a NOGO, just count the taps: config-navigconfig-car-zoom +++
- autozoom work greats great in citys, so I dont want to disable it when Im driving from one city to another city over 100km motorway.
- 2finger tap is quite complicated, just think of bikers with gloves, too easy to move the car position
- +/- zooming is ok, but sometimes redrawing the map and going back to autozoom colides, so I cant really to a look at the zoomed map
- less distraction is more save driving, so automatic is better than configs and klicks
- if (driving on motorway) than do: (zoomfacter*10) as simplest construction
- could be more complicated if if range (50km, 100km) and distance to destination are involved too.
cu
Harvey

**Comment by sonora** [comment]
Ok, re-reading your original post above:
- Announcing exits instead of turns is a different issue investigated elsewhere, currently not supported.
- For the auto-zoom: Are you taking about the case where a turn-by-turn navigation is active, or just the map idling along with your position (with or without a route being displayed)?
- Some people prefer to monitor their "progress" on a long trip, by keeping the map fixed so that initial start point and end destination point are always visible on the screen.  Are you talking about this use case, or want to see the map being dragged your position?

As you see, there are a lot of different modes and preferences users use, so it is really hard to create an automatism here... In particular also:
- If we always zoom out to 50km on motorways, this is useless for people who just get on and after2km off a motorway or ring road commuting in an urban area
- This becomes useless in general if you are approaching an exit you may want to take (whether OsmAnd knows this fact (in a routing situation) or not.

For now I would say the idea is not very mature and should be discussed in the forum first. I do not see that this is an issue or even a well-designed improvement request to be posted here (yet)?

**Comment by Doogse** [comment]
Ok, for me this boils down to providing an easy method to alternate between auto zoom mode and perhaps "whole route" view.

**Comment by harvey637** [comment]
@sonora 
your valid critisims may be turned into beautiful refinement:
- yes, only in turn-by-turn navigation
- "allways on motorway" (may be this also applies to inner city autozoom?) zoom in a way, that at least the next turn is displayed in turn-by-turn mode. if there is no turn announced, than the road must be easy and straight to drive, so no need for a near zoom (a small zoomfactor as influenced by speed). It is not neccessary to change zoom by driving speed, as this zooms in/out at stops at red traffic lights. Sometimes the redraw of the map is annoying and hiding details of complex crossroads because of uncompleted redraw. When using an exit to get off the motorway, this is a turn point, so it will be displayed.

- 2finger zoom: is there an easy way to go back to autozoom?


@Doogse 
yes, this is something I am missing very much and includes and extends my request - great!
- whole route: to quick check that your not navigating to someplace with the same name, wrong direction
- rest of the route: the same button as whole route, but after moving away from the initial starting point

May be as toggle of the destination button (checkered flag) "zoom into destination" + "zoom to <actual_position> to destination". Terminating this view and going back to autozoom with the actual_position button. Displaying this view with an "eye" instead of the "car|bike|pedestiran" in the top-left corner makes it easy to recognise.

**Comment by sonora** [comment]
Ok, couple of thoughts here:
- I have just improved the "2 finger tap zoom out" to the effect that now the screen stays linked to the position if this was the case before the 2 finger tap. So it should be easier to operate in a car etc. (all map gestures were significantly improved, is present in latest nightly and next release)
- Quick change between Auto-Zoom or not: We have an ongoing initiative to implement a "Quick Action" button, I guess that will become the method of choice to facilitate an "personalized" action button on screen with whatever one deems important (cannot promise Auto-Zoom is currently in focus for that, but certainly could, I guess).
- Auto Zoom improvement: This is a tough one, I think, because from experience I know that there are many situations where a routing engine interpreting map data does not announce a turn, but the situation may still require the driver to take a closer look on the map screen to clarify the situation (complex intersections, multiple forks in short succession, etc.). So if we always show an overview map it may well deteriorate the quality of the guidance... As the issue of what to show at what magnification is a common question with all nav systems, we may also well do the research and shop around for some best practice here.

**Comment by harvey637** [comment]
Great news, I will keep on testing.

Please also take a look into Doogse comment, it sounds good to have something to easy
toggle between turn-by-turn (autozoom) and overview (whole [remaining] route).

The tap on the desitination_flag (which also means a destination is set so only in turn-by-turn mode)
is easy as a hint to zoom to destination (like now)  or [improvment] overview to 
complete/remaining route to go. Tap blue_circle to go back to normal mode.
I guess, that tapping the blue_circle could not only lock map movement to actual position, but also
quiclkly zooms in to make short term decisions at complex intersection easy (timeouted). Going back zu locked position, autozoom, or tap in already locked situation: near zoom (timeouted) to actual position.

Bye the way, timeouts (time to go back to normal navigation mode) is a bit confusing. but I dont know
the reason. It is definitivly not always the same timeout as configured. Also (at least on my 
lenove 7" tablet) zooming in crouded areas like metropol cities can take same time, so waiting
for the map to get ready take a long time, that is part of the timeout. Maybe the timeout
could take this inti account? (than the timeout is the time to actually SEE the map before going back.
I will post something if I get the different timeouts sorted out ... 

Thx
Harvey

**Comment by sonora** [comment]
I always disencourage new settings adding complexity to our UI. But I also cannot see how we usefully automate this. So from what I see, the optimum solution for this issue would be adding an Auto zoom quick access to our new "Quick action" button functionality (?)

**Comment by harvey637** [comment]
Hi, yes, too much config for too much different usages. 
- May be some (more) config should be only car/pedestran/biker related
- more two_tap buttons
- and most of all: document use of buttons: eg. how to fix zoom, how to return to autozoom, ...

Usage is completly different while driving (minimal distraction) or hiking (maximum "playability")

To come back to motorwaydriving:
- "destination_flag" as multibutton for "full zoom to destiantion[timeout]" + "zoom complete route[no_timeout]" + "normal(or touch actual_pos)"
- "actual_pos" as multibutton for "full zoom here [timeout to normal]" + "normal"
with mode "normal" I thinik of "autozoom, map_rotate, keep map_to_position"
just my idea ...

**Comment by sonora** [comment]
@vshcherb Could we please get a Quick action also for Auto zoom? This would greatly help with this issue. Thx!

**Comment by vshcherb** [comment]
You mean turn on/off auto zoom. Agree will add to this list.

**Comment by sonora** [comment]
@vshcherb Yes, probably we have to make it the "page through list" type, as auto zoom has 4 different possible value (off/short-/mid-/long-range). Probably not to easy to just have an on/off switch here (although it would suffice for this issue.)

Side note: I have a feeling, but it is hard to test, that there is little or no difference visible between e.g. long and mid range. Having a Quick action to toggle between these would assist discovering if we have a bug or not.
