### ISSUE TITLE
Weird notification when navigating and voice is turned off

### ISSUE THREAD

**Issue by Tejes** [osmandapp/Osmand#3386]
Since I purchased OsmAnd+, I get a notification when navigating and the voice commands are turned off in navigation settings. I googled it for a while, and have not found any info about this. 

Device: Sony Xperia Z5 Compact E5823
Android 6.0.1 (32.2.A.5.11 build)
OsmAnd+ version: 2.5.4, but it is present for at least 3 months (since I switched from the free version.)

The notification shows the ogg file to be played (but of course no sound can be heard because it is turned off) when recorded speech is set, the complete text when TTS.

<img width="180" alt="687474703a2f2f692e696d6775722e636f6d2f31446c614269392e706e67" src="https://cloud.githubusercontent.com/assets/845735/21837328/989d7a0a-d7cb-11e6-806b-d08abcf7bf7d.png"> <img width="180" alt="687474703a2f2f692e696d6775722e636f6d2f454f577578714b2e706e67" src="https://cloud.githubusercontent.com/assets/845735/21837330/9dab9f4a-d7cb-11e6-8c2e-e395f51b84ba.png">

The notification cannot be expanded, or clicked. When voice commands are enabled, everything is normal, this notification does not show up.

**Comment by sonora** [comment]
Cross reference to also check https://github.com/osmandapp/OsmAnd-resources/pull/419#issuecomment-271787475

**Comment by sonora** [comment]
Talking about the 3rd notification from the top on your screenshots, the one labeled "OsmAnd+", right?

Will have to research this. That notification does actually **not** show up on most of my test devices, but I can reproduce it at least on one Android 5.1.1 phone.

So it looks like it is actually not something we produce on purpose in OsmAnd (like the new navigation notification shown with the yellow arrow in your screenshot), but it seems rather something some Android systems produce as some reaction to events produced by the app. On the device where I can reproduce it, it actually displays Chinese characters, so something is weird here ...

Chances are this can be suppressed somewhere in your Android system settings by configuring which notifications you want to see from OsmAnd, or by simply taping the "Clear" button in your notification area.

**Comment by sonora** [comment]
The Chinese characters came from my TTS voice being set to Chinese for testing something else  : )

But it is like I said: This notification is a feature of newer Android versions to visually display app notifications, so if you mute the voice guidance sound, Android gives you a hint in writing that would have been said (works well for TTS, not quite so well for recorded voices, of course, where it displays the name of the "missed" .ogg files).

Instead of muting the sound you could set your OsmAnd TTS voice to "Do not use", in which case the System notification seems to display the textual turn instruction (I think the ones we use on the route details screen to textually describe the route).

Should you want to suppress the notification entirely, I find a setting which under Android 5.1.1 is at "Sounds and notifications / Application notifications". There I can set OsmAnd notifications to "Block", if desired. But this seems to turn off ALL OsmAnd notifications, not sure if your setting is more granular.

Not much more we can or should do here, I guess.

**Comment by Tejes** [comment]
I do not quite understand your point. That notification is completely useless, since there is the bigger one with the yellow arrow and detailed info. I do not think it is normal operation to instead of the provided switch to turn off sound, I have to set the language to 'nothing'. When I do, and enable sound with the switch, the notification is gone indeed.
Of course disabling all notifications of OsmAnd+ is not an option for me.
I am not into Android development (yet), but long pressing the notification shows that it is from OsmAnd+, not some system service. Are you sure there is nothing that can be done here?

**Comment by sonora** [comment]
Something could certainly be done, like to rework that or how we pass app events to the Android system which some newer versions of Android now seem to use for this standard notification. But it is my impression for now that this type of app notification (including telling you that there was sound output in an app but muted) is a new Android "feature", not a bug.  :)
