### ISSUE TITLE
I cannot see created and uploaded POI via OSM Editing plugin

### ISSUE THREAD

**Issue by sim6** [osmandapp/Osmand#3390]
When I created a POI using OSM Editing plugin, after upload it, then I cannot see the uploades POI, so I cannot use it or edit it again.

**Comment by sonora** [comment]
I guess the solution is to use our OSM live functionality, which gives you very prompt map delta updates.

**Comment by sim6** [comment]
But righth now OSM live is not automatic and instantaneous.

**Comment by DFyson** [comment]
Ya this is a little frustrating since OSM live isn't instantaneous but it's a huge improvement. In some cases time doesn't permit me to upload my edits then wait minutes to hours just to re-download them. Maybe it would be possible to convert the edits to an OSM live update but locally on the device? Then keep that until the next OSM live update.

**Comment by matthijskooijman** [comment]
I believe this issue is a duplicate of #2890.

**Comment by sim6** [comment]
Oh, thanks.
