### ISSUE TITLE
topo.render.xml: some bug fixes and optimizations

### ISSUE THREAD

**Issue by Thunichgud** [osmandapp/Osmand#3424]
I prefer the new Topo style very much and therefore I made some bug fixes and optimizations in the topo.render.xml. You will find the complete file in the attachment. The changes are commented at the end of the file. It would be nice, when you include the changes in the next version of the Topo style.
[Topo.txt](https://github.com/osmandapp/Osmand/files/703072/Topo.txt)

One bug I couldn't fix: In plain areas are too few visible altitude values on the contour lines. So it is often very hard to find the altitude of a specific contour line. The contour lines of 20m, 40m, 50m, 60m, 80m, 100m and so on shows their altitude values very rare and the contour lines of 10m, 30m, 70m, 90m and so on shows in most zoom levels absolute no altitude values. There should be more visible altitude values on the contour lines in plain areas. In mountain areas there are more (enough?) visible altitude values on the contour lines.

**Comment by xmd5a2** [comment]
1.Pull requests are made for that purpose.
2.Each pull request should contain single feature.
3.Idea of "topo" rendering style was to mimic most common topographic maps (one of goals)
4.I prefer color consistent styles, so no more pink borders.
5.
> Contour lines should be in lighter brown
  There is option Configure map - Contour lines color scheme.
>   and the elevation text should be brown two and follow the lines
  Disagree because these numbers are less readable if they are twisted.
> WaterwayArrows are water objects and should be dark blue, not black.
  These arrows are black because I found that this color is most contrast over other possible colors in this style.
