### ISSUE TITLE
Replace strings "GPS" with "GNSS"

### ISSUE THREAD

**Issue by polarbearing** [osmandapp/Osmand#3428]
The US based GPS is just one of [several GNSS](https://en.wikipedia.org/wiki/Satellite_navigation). Current handhelds are capable to combine signals from GPS, from GLONASS (lauched by the Russian OsmAnd developers IIRC), BeiDou, and occasionally even a glimpse of Galileo. The combination of more satellites enhances the precision significantly. 

![screenshot-21_of_34_sat](https://cloud.githubusercontent.com/assets/8266355/21948738/34a9e30c-d9ed-11e6-85b4-b98534d673de.png)

Thus I would consider helpful, and educating users what is really received, to replace all user-visible strings of "GPS" with "GNSS".
![screenshot_20170113-gnss-small](https://cloud.githubusercontent.com/assets/8266355/21948576/657729be-d9ec-11e6-98fd-790e66d670ee.png)

**Comment by sonora** [comment]
True. But I think we should not change that, because GPS is the universally known and conventionally used expression. Primary focus of our strings must be to provide maximum assistance in operating the app, not to educate people.

I would say GPS is definitely not wrong, you can consider it both a "pars pro toto", and it is also very similar to how in British English often Hoover (a registered Trademark even!) is used for "vacuum cleaner" (or  "caterpillar" fora crawler vehicle).  :)

**Comment by polarbearing** [comment]
Yes I know the effect that trade names become common language. In this case it was true as long as only the US system was available. As we have more now, we should express in the labelling that we are capable of using them all.

**Comment by breversa** [comment]
Though I understand @sonora's position, I believe that using proper terminology is always better (maybe with a one-time explanation, for instance) than incorrect words (just like I believe using Tio instead of TB).

What's more, with Galileo coming up, GPS is becoming less and less "pars pro toto", hence more and more legitimate.

Care needs to be taken for translation though, as there may not be an established translation for GNSS for every language (for instance, I only know the english term).

**Comment by vshcherb** [comment]
I definitely oppose to it, to support that idea I think we should organize a poll. We launch on a website next week.

**Comment by utack** [comment]
No need to poll
Everyone who knows about all the systems also knows GPS is just an expression
Everyone who does not know about all these systems will be confused

**Comment by sonora** [comment]
Victor, here is your poll, I asked Mr. Google :)

Looks like GPS is still **150 times** more known than GNSS. That settles it for me for me until this significantly changes  :)

![capture1](https://cloud.githubusercontent.com/assets/845735/22096227/7532f054-de1a-11e6-9b51-6c3688b85dfc.JPG)
![capture2](https://cloud.githubusercontent.com/assets/845735/22096231/7b16bfdc-de1a-11e6-8bd0-c2d2821d4c42.JPG)

**Comment by polarbearing** [comment]
@utack, very scientific indeed. Statements about 'everybody' are very dangerous. 
@sonora, the search engine of course accumulates all the old stuff. Could you do the same for year-2016 documents only?

Terminology changes with progress of technology: 
- do you use a smartphone or a PDA? 
- the device once called a 'cellular/mobile phone' is now a 'feature phone'. 

And it is the _technology leaders that drive the terminology_, I want OsmAnd among them.

**Comment by sonora** [comment]
Yes, I have to admit it reversed in 2016: For info newly published info, there are some 3.0 Mio hits for GPS, and 7.5Mio hits for GNSS. But of course, a lot of existing info naturally correlates with less need to newly publish.

Regarding your argument about being a leader: I would say, point taken. Still not sure though this would not cause us  more question marks and support tickets than we can handle. **As long as Android calls the feature GPS**, it sounds really unwise for us to introduce deviating terminology here ...

**Comment by breversa** [comment]
Why should we wait for Android/Google to make the first move ? Why be
followers instead of correct-terminology-setters ? :-)

Just add a one-time explanation when you start OsmAnd for the first time
explaining something like :
"GNSS (Global Navigation Satellite System) designates all satellite-based
location systems such as GPS, GLONASS, Beidou, Galilelo, depending on what
your device uses."

2017-01-19 17:33 GMT+01:00 Hardy <notifications@github.com>:

**Comment by noci2012** [comment]
What we tag as GPS is actually called NavStar GPS...
http://www.space.com/19794-navstar.html

**Comment by sonora** [comment]
From what I can see, where we use "GPS", we refer to no particular brand, provider, or satellite system at all. We simply refer to what on your Android device is provided and accessible under

- Android Settings / Location / Mode / **GPS**

**Comment by Tony-il-Capo** [comment]
I kinda understand both sides here, while "GNSS" is the most right term, the "GPS" is a conventionally used expression on our daily lives to describe a satellite navigation device. It's used literally everywhere!
Like the "caterpillar" example, or even the "Jeep", commonly used to easily describe a similar vehicle... makes it understandable by anyone.

In the end, I would vote against changing it from "GPS" to "GNSS".

**Comment by breversa** [comment]
In this "Age of information" we now live in, I believe that it's A Bad Idea to NOT use the best/proper/true terminology.

(Also, resistance to change goes against the human's best advantage : adaptability)

**Comment by Tony-il-Capo** [comment]
Then, ask Android developers to change this.
> We simply refer to what on your Android device is provided and accessible under
>- Android Settings / Location / Mode / GPS

Should osmand be the first? No, osmand depends on Android to run.

In this "Age of information" people know we shouldn't  waste time on things that don't really matter, on the practical side, osmand will behave exactly the same way.
'GNSS' is not used and not adopted in many countries, this would create a massive confusion.
'GPS' is globally known.

So, 'adaptability', is having an expression, that literary, everybody understands, so that we are all equal.

**Comment by polarbearing** [comment]
@Tony-il-Capo - if you officially call your similarly produced vehicle a Jeep, you'll face trademark litigation.
In which countries is GNSS 'not adopted'? How do you measure the massiveness of the confusion?

**Comment by Tony-il-Capo** [comment]
By adopted, I mean accepted or choosing it as standard expression. Real world is out there, you know, just go out and ask **common** people! You will understand.

I won't certainly waste any more time with this.

**Comment by vshcherb** [comment]
I support the idea that we should be align with Android Settings.
