### ISSUE TITLE
Please add option not to split recorded track logs

### ISSUE THREAD

**Issue by akkana** [osmandapp/Osmand#3430]
When using trip recording, starting a couple of months ago OsmAnd splits track logs into separate segments if I stay in one area for some (unknown but relatively short) length of time. Before that, it only split the track if I chose "Start new segment" explicitly.

That means there's no longer any way to get the total distance of a trip; the distance displayed is only the length of the last segment, not the whole trip.

Please offer an option to disable the auto-splitting, or to configure the length of time you have to be "stopped" before the track splits (someone who doesn't want it at all could set it e.g. to 24 hours).

Thanks!

**Comment by vshcherb** [comment]
The code is located here https://github.com/osmandapp/Osmand/blob/master/OsmAnd/src/net/osmand/plus/activities/SavingTrackHelper.java#L316. I hope for @sonora  won't be difficult to add it. 
Anyway I support this idea for plugin settings  (https://github.com/osmandapp/Osmand/blob/master/OsmAnd/src/net/osmand/plus/monitoring/SettingsMonitoringActivity.java)

**Comment by sonora** [comment]
Done: https://github.com/osmandapp/Osmand/commit/6d6fd608fa5c47c97c48eade95c6467c6be8840b

Maybe someone can double-check and/or test, if I got the logic right.

@vshcherb Victor, that reminds me we agreed to make all recording parameters global, due to
- The issue that parameters for an ongoing recording currently change unnoticed (behind the scenes) when people change app profile to check something on the map
- Starting a recording from the new notification uses undefined/not evident parameterization

**Comment by vshcherb** [comment]
The commit looks good, I don't remember about all parameters make sense, though @xmd5a2 might   confirm better.
