### ISSUE TITLE
Pedestrian navigation frustratingly bad. (Route constantly being recalculated)

### ISSUE THREAD

**Issue by T-vK** [osmandapp/Osmand#3458]
So I was trying to use Osmand for a longer trip recently. And instead of walking about 20 kilometers (which was the original route length that Osmand calculated), I ended up walking for about about 25 instead. Why? Because the route was constantly recalculated. For instance sometimes it wasn't exactly clear if I should a turn into street A (directly next to me) or street B (2 meters in front of me). And as soon as I walked pass Street A, the route was recalculates as if I couldn't just turn around. Do you know what I mean? It's like Osmand doesn't understand that pedestrians can always instantly do a U-turn anywhere without any drawbacks.  
This really needs to be fixed. There should at least be an option to not automatically recalculate the route. So if you walk too far it should simply tell you to go back.  

Just fyi, I tried to look on my phone as rarely as possible and to only listen to the audio navigation and only pull out the phone when I was unsure... but at that time the route was almost always already being recalculated. I also want to mention that it is extremely easily to overlook a small footpath in some places, you really can't compare it to normal roads.

**Comment by vshcherb** [comment]
Is it possible that GPS signal was flaky or you suspect the route guidance. I understand you had hard time with it, please help us to get into the reason. 
The most important question, was original route (which was calculated in the beginning) already bad? May be you tried in the middle to cancel navigation and start it all over again, was bad as well?

**Comment by T-vK** [comment]
I'm using a OnePlus One. So the signal is pretty decent in general. It supports GPS, GLONASS and Beidou satellites. So to answer your question, no, the signal was not flaky.  
The original route was fine. I mean it was definitely shorter that what I actually ended up walking and it didn't navigate me onto highways etc. So that was good.   
I did not cancel the navigation at any point.  
But just fyi, I had the exact same problem on a shorter trip, too. I was navigating to a cinema and accidentally walked past it because I didn't initially see it. Then suddenly Osmand recalculated and told me to go around the whole block again which would have been 1 kilometer instead of just 10 meter if I had turned around. For a car that would have made sense because it was a one-way street. But not for a pedestrian.

**Comment by sonora** [comment]
Victor, this reminds me of our investigations many years ago, when we used to have the prompt "Please make a U-turn when possible" quite frequently. While I originally had felt that in many cases the best first solution after leaving a calculated route is telling a driver to make a U-turn where he sees fit, over time we agreed that guiding a driver in forward direction may be the more elegant (event though sometimes not completely optimized) solution.

I think the point made in this issue is that for pedestrian routing (contrary to car and maybe also bicycle)) the direction of motion of should not play a role for the route calculation (and re-calculation). Meaning if someone walks "the wrong way", for walking we should advertise the U-turn, and not try to find a better way in "forward" direction like for driving?

**Comment by cvwillegen** [comment]
I also ran into this problem recently. Added 15 minutes to a 35 minute walk... I advise to tell the user (if in pedestrian mode, perhaps also in bike mode?) to turn around as soon as possible...

**Comment by T-vK** [comment]
@vshcherb @sonora So are you planning to fix this?

**Comment by vshcherb** [comment]
@T-vK we are planning to fix it, but we need some given coordinates (screenshots could be helpful) in order to set a baseline before fix.

**Comment by cvwillegen** [comment]
I don't understand the need for screenshot.  When a pedestrian walks into a street or path he shouldn't have, just tell him/her to turn around. Could you clarify your request for screenshot?

**Comment by T-vK** [comment]
@vshcherb I doubt that would be of any help. Just set your Osmand to pedestrian mode and set up a simple route that tells you to go make a turn. Once you're at the turn, keep straight on and pass it. Osmand will pretty much instantly recalculate.  
The baseline for fixing this should not be some random coordinates that I give you. This is an issue that will occur on every turn that you miss.

**Comment by T-vK** [comment]
@vshcherb @sonora
Any news? Does this issue have any kind of priority?

**Comment by vshcherb** [comment]
Did a 1km pedestrian navigation and unfortunately I didn't notice any recalculation at all, sometimes tried to deviate for 10-15 meters and it didn't  cause it. I think because we attract location quite strong to the route.

I suspect @T-vK issue is mostly related to jumping GPS location it is especially visible on some devices when you navigate with a small speed.

Unfortunately not much could be done right now.

**Comment by cvwillegen** [comment]
Have you tried this in a city and not take a right or left turn when navigating?

**Comment by vshcherb** [comment]
@cvwillegen Just straight navigation. Will give a try though it well depends on the surroundings. If there are high buildings, GPS will be flying and navigation will be terrible.

**Comment by sonora** [comment]
I have tested this a bit on hiking trails myself mow, and my impression is that for pedestrian routing we should drop (or decrease) the impact of any actual direction of motion a person on foot may have. In other words: If at a trail intersection I deliberately walk down the 'wrong' trail, even if it is 100 or several (maybe many) hundred meters longer, our routing engine will rather quickly decide to re-route me down that overall longer trail. But if I stop, stand still,  and then recalculate the trail (at rest), OsmAnd will route me back some 10 m or so to the intersection and from there guide me correctly  via the overall significantly shorter route. Since U-turning and backing up a few meters is never an issue when on foot, maybe the lessons learned here is that --contrary to car routing-- for pedestrian routing we should always calculate the route as if the person is at rest?

**Comment by T-vK** [comment]
Well, at least that should be the default. An option to get the old behavior wouldn't hurt, I guess.
