### ISSUE TITLE
Feature request: Upload pictures of house numbers

### ISSUE THREAD

**Issue by andrasfuchs** [osmandapp/Osmand#3468]
Finding an exact address is difficult in many places, because OSM doesn't have the house number information for many buildings. Normally a contributor would manually upload the house numbers one-by-one.
Sometimes, if I have a few seconds, I would be glad to upload house numbers around my location, but it is not that straightforward at the moment.
Ideally I would only take a few pictures of the house numbers with my phone, and store it somewhere for later processing at a desktop computer.
So, it would be nice to have a quick "take a picture now, process the image later" with geo-location info.
Optionally this feature could attach tags (like #housenumber) to the photos, so it could be then later extended to traffic signs, opening hours and any other information upload activity which is inconvenient to complete on site. 
The image could be stored locally on the phone only, or even with a public, free service as a host for this pictures, so others can take care of the processing, regardless who took the original picture.

**Comment by stephan75** [comment]
I think this feature is overloaded for Osmand ...

Do you know the apps of Mapillary or OpenStreetCam?

They do exactly what you want, IMHO. You are NOT forced to upload your images there.

**Comment by andrasfuchs** [comment]
Sound great, thank you!

I used Mapillary, but their most recent Android app is very buggy, it doesn't even log in for me, so I abandoned it. 

I will definitely give OpenStreetCam a try!

**Comment by sonora** [comment]
Also in OsmAnd: Have you tried enabling our "Audio/video notes" plugin, I think it may also facilitate what you need.

**Comment by polarbearing** [comment]
In addition, every stock-android camera app can write the geo-location into the EXIF data, which you can load into your JOSM.

**Comment by andrasfuchs** [comment]
Thank you guys for the help!

I enabled the audio/video notes plugin in OsmAnd, that's exactly what I needed.

I also tested JOSM, opened a few geo-tagged photos of mine, it put them on the map, so it worked exactly as it should.

**Comment by goldfndr** [comment]
Another option, for those viewing this issue, is [StreetComplete](https://wiki.openstreetmap.org/wiki/StreetComplete). It downloads *quests* in the nearby vicinity that can be simply answered while walking or bicycling nearby.

A housenumber quest was added to it after this issue was created and closed. It's coded to only ask for a subset of `building` values to avoid false positives on some `building`=`yes` buildings (e.g. garages, sheds, chicken coops). An upcoming quest will ask about building architectures for `building`=`yes` buildings and enable the housenumber quest (and roof shapes and building:levels if enabled) for appropriate building types.
