### ISSUE TITLE
German TTS is a lot too fast

### ISSUE THREAD

**Issue by beerisgood** [osmandapp/Osmand#3472]
In the last 3 or maybe more F-Droid releases the TTS German speak a lot too fast and not one word is understandable.
The normal German works without problems.
I reinstall Osmand but doesnt make any difference.
Problem exist in Android 6, as well in 7.1 (LineageOS)

**Comment by sonora** [comment]
I have just checked our code history and find no reason in recent months which could cause this. Neither can I reproduce it myself at all (using our latest nightly build).

Are you saying you observe this on different devices? Because normally I would suspect you (or some other app) accidentally changed the Android TTS speed setting, usually in or near `"Android (not OsmAnd) Settings/Input and Language/Text-to-Speech options/Speech rate"`. (This setting may be elsewhere depending on what TTS engine you use.)

Please use the "Listen to an example" button there and check if that produces "normal" results. If the behavior persists, please state the exact OsmAnd version you are using, along with the TTS engine and settings on your device.

**Comment by beerisgood** [comment]
Thanks for the Android setting tip!
It looks the TTS in LineageOS is not okay.
