### ISSUE TITLE
Change render resolution

### ISSUE THREAD

**Issue by utack** [osmandapp/Osmand#3535]
Here is an idea to speed up rendering and save battery: allow to change resolution of the drawn map
Devices with 1440p and 4k screens are getting pretty ridiculous, rendering at lower resolution would still be crisp enough to spot all features on the map
Maybe it should be hidden in the developer plugin, not to confuse end users
Thanks for consideration

**Comment by sonora** [comment]
I am not sure there is much to be gained here ...

If we not draw at the device's native resolution, are you sort of suggesting we draw in a "smaller" rectangle, then in the end "stretch" the result so it again fills the entire screen? This procedure may require as many resources as directly drawing natively?

I think the one thing which may "help" some is what we already have: Long-tap one of the zoom buttons (or in "Menu / Configure map" select "Map magnifier"), and set it to a larger percentage. This would "blow up" the map, so that a only smaller section actually fits your screen, and there are fewer objects to be drawn.

**Comment by utack** [comment]
Hmh gave me the idea to try it  
You are right, it does not change a lot
