### ISSUE TITLE
Add possibility to set audio channel for voice guidance in routing profile

### ISSUE THREAD

**Issue by cvwillegen** [osmandapp/Osmand#3558]

**Comment by cvwillegen** [comment]
When riding a bike, I would like to get spoken instructions via Music channel. In the car, as telephone calls. I need to set this in main settings every time I switch transport. Would be nice to be able to specify this in specific routing settings.

**Comment by sonora** [comment]
I know what you mean, but I sincerely vote against us making some audio settings profile-dependent. From experience with similar requests I know that a minority of expert users are familiar with the principle and use the feature, while it confuses the heck out of the majority of users and is destined to cause numerous support tickets for us. Let's leave voice/language, audio channel, bluetooth delay etc. all as global! But what I think could /should be done here is make the "Voice guidance output" setting directly accessible on the settings tab behind the wheel icon (to the left of the "Go" button) of our route setup screen. There even possibly replacing the second line "Voice guidance" where you can pick a voice file like en-tts, because I think changing the voice file when setting up a route has a very rare use case compared to changing the voice output channel?

**Comment by cvwillegen** [comment]
You could leave it global but overridable in the specific sections. I see what you mean about confusing people. By the way I think changing tts language is not used so much. Having an override in the settings when starting a route could be useful bit might clutter the interface.

Having a route specific setting () follow global  () as media  () as message () as phone call would be possible, right?

**Comment by sonora** [comment]
The least clutter is exactly as I said: We replace the existing entry "Voice guidance" by the more often needed "Voice guidance output" on the settings tab of the route config screen, which is just 1 tap from whenever you set up a route (it is to the left of the Go button). I could only implement in a few weeks, maybe one of our team could help out.

**Comment by sonora** [comment]
@vshcherb , @crimean While https://github.com/osmandapp/Osmand/commit/3512b82f9bb1c31f9f4337e68c1283ad591970b1 may  not be a bad solution either, my suggestion was to simply place our setting "Voice guidance output" in the place I indicate in this screenshot ... in this fashion the setting could simply be adjusted very simply at every route setup if needed:
<img width="135" alt="screenshot_2017-04-01-22-00-41" src="https://cloud.githubusercontent.com/assets/845735/24585113/a98f1f84-1782-11e7-88bf-94daab57d0cc.png">

**Comment by vshcherb** [comment]
Voice output is needed to be configured by smaller percentage of the audience that's why we kept in the settings which are accessible from this UI as well.

Voice guidance needs to be configured by many users that's why it deserves one of the most visible place.

**Comment by sonora** [comment]
I would have thought it is exactly the other way round: Voice guidance is a one time setting, and would never again be touched by the vast majority of users, while the output channel may need to be selected on a case-by-case basis? (Car, bike, rental car, etc.)

But maybe you are right, I am currently not sure how we ensure there is a first time selection of the voice guidance. Thought we have a specific dialog (independent of this menu) if unconfigured, but maybe not. In any case, that' why I suggested further up to for now and the release add the output channel item below the voice guidance setting instead of replacing it, but maybe this is not critical.

**Comment by vshcherb** [comment]
It is one time setting but used by far more people. Speculating but I guess 10% (one time) vs 1% (frequency is unknown)

**Comment by cvwillegen** [comment]
I set language only once, and set voice guidance channel every time I
switch from foot or bike to car. Foot and bike are 'media/music', car is
'phone call'.

**Comment by vshcherb** [comment]
@cvwillegen your issue is fixed, you need to change it only once now. You can set different settings per profile

**Comment by cvwillegen** [comment]
Wow,  great news!

**Comment by sonora** [comment]
Other than low-impact the solution I suggested (of just having the voice output selection switch handy on the route config dialog near where we now have the language selection), the route now chosen of making this setting profile-dependent opens the following gap here:

We have no interface to adjust the output channel for the default (Browse map) profile. But we do support voice output there, like you will get traffic or speed limit warnings, if just driving with that profile, if only your voice engine was initiated once in that app session.

And: This solution causes #3690: We currently have the testing and delay parameterization for Bluetooth SCO output in our Development Settings, but there they are designed global and would need some work (and a plan)...
