### ISSUE TITLE
Walk routing distance announcement improvement

### ISSUE THREAD

**Issue by PinkDuck** [osmandapp/Osmand#3574]
Using pedestrian routing, I often hear the voice announcement "turn left|right in 50 metres", though the turn is typically 3 to 8 metres away. I have never heard the voice announcement say "turn left|right in 5|10|15|20|25|30|35|40|45 metres", which suggests the built-in settings for creating announcements in that travel mode isn't quite right. My location as tracked by GPS is fairly accurate, no more than a couple of metres out. It does make navigating through dense residential areas tricky, as on occasion the turning is around the stated distance. I walk briskly at around 1.6 metres per second.

**Comment by vshcherb** [comment]
I guess you never heard the announcements about 8 meters cause the announcement triggered at 50 meters. Fine tuning pedestrian navigation to announce every 10-20 meters is not a priority though there is a similar feature in accessibility mode.
In pedestrian navigation it is assumed you can interact with the map much easier.

**Comment by PinkDuck** [comment]
I can tell you that as a user who actually uses it for pedestrian navigation that I need to look at the unfamiliar surroundings and prefer to hear accurate vocal announcements. Stopping frequently to check the map is a nuisance and can bother others nearby too. I just need to know how far to go, accurately, before the next turn and which way that is.

The accessibility version doesn't improve the situation I described, nor am I impaired. I am frustrated that you closed the issue so readily.

**Comment by PinkDuck** [comment]
Just to be clear, I don't want repeating announcements, I just want the one about the distance to the turn to be correct. The OSMAnd Map Creator produces the right distances to each turn, however, the application typically announces 50 metres away, when in reality it is a matter of only a few. Often.

**Comment by vshcherb** [comment]
I do see that pedestrian navigation might not be perfect. Though we are using 50 meters as a moment to pronounce the next turn that's why you can only hear "50 meters"  https://github.com/osmandapp/Osmand/blob/master/OsmAnd/src/net/osmand/plus/routing/VoiceRouter.java#L149. Also the limit in the voice is 10 meters (we announce only 10, 20, 30, 40, 50).  Taking into account the time of instruction to be announced and GPS accuracy the result of 30 meters instead of 50 meters is not that bad. Actually you should always use next turn widget and usually the difference is smaller 43-48 meters instead of 50.

**Comment by PinkDuck** [comment]
Could this be something to do with audio play delay? Such that the previous vocal instruction play-time may offset the playback of the one following but produced earlier with the longer distance to go?

**Comment by vshcherb** [comment]
Yes it could be a delay but again it is less than 1-3 seconds.
Yesterday I did a testing and my observation that OSM is quite far to support precise footways:
-  pavement bends around the corner (easily minus 5-10 m)
- Footway are combining with highway (easily minus 10 meters)
- Some footways are missing

The issue is closed cause there are no immediate plan to fix it though again if it would be a clear technical issue it could be fixed. Otherwise it is something in between 4 parts:
1) Algorithm
2) GPS accuracy
3) OSM map data
4) Reality
Where only 1 part could be changed
