### ISSUE TITLE
Licensing unclear

### ISSUE THREAD

**Issue by wiewo** [osmandapp/Osmand#3578]
There are a few parts of the licence that are not entirely clear.

At the beginning, the licence reads:
> The code in that repository is mainly covered by *GPLv3* (for code) and *CC-BY-ND-NC* (for artwork with restriction)
> ATTENTION: please be aware that some artwork has proprietary license.

Here, a clear distinction is made between the licensing of the code and the artwork. However, "artwork with restriction" makes it sound like the artwork has some sort of restriction, not that there are additional restrictions for the licensing of the artwork. I suggest using a wording like "for artwork, additional distribution restriction imposed". I'm not a native speaker, so I might be wrong.
The second "ATTENTION" part is confusing. Does this address the same artwork as mentioned before? CC-BY-ND-NC is a proprietary licence. Is this part a clarification of the artwork mentioned beforehand or does this address something else?

Then there is this part:
> * UI Design and UX work, such as layout, icons is covered by CC-BY-ND-NC 
>        - https://github.com/osmandapp/Osmand/tree/master/OsmAnd/res and others
>    Restriction to UI/UX CC-BY-ND-NC:
>    * Publishing applications using the OsmAnd UI/UX code to Google Play, Amazon Market or Apple Store must be done with written permission*

You are specifying a directory, but then add "and others". Would it be possible to add the other directories to the list so that it is complete? I suspect that the files in the directories don't contain the licence, so there could be files (code, artwork, etc.) where the licensing is entirely unclear.
In the beginning, you made the clear distinction between code and artwork. Here, you are calling it "OsmAnd UI/UX code". So is there source code covered under CC-BY-ND-NC or only artwork? To avoid confusion, I recommend using the terminology of the [GNU Free System Distribution Guidelines](https://www.gnu.org/distros/free-system-distribution-guidelines.html). The guidelines use the term non-functional data which may be applicable here.

Further below, these terms can be found:
>     * Map icons and their derived primitives are covered by proprietary license:
>        - © icons8.com (https://github.com/osmandapp/OsmAnd-resources/tree/master/icons/svg/icons8)

>    * Generated voice files from TTS files are covered by proprietary license:
>        - Voice files (https://github.com/osmandapp/OsmAnd-resources/tree/master/voice)

Could you name the licence for the icons and the voice files? "Proprietary" itself is not a licence.

Finally, I just want to let you know that the [Replicant project](http://www.replicant.us/) is currently [evaluating if F-Droid respects the GNU free system distributions guidelines (FSDG)](http://redmine.replicant.us/issues/1629). Replicant is committed to follow these guidelines and the guidelines require that non-functional data can be copied and redistributed, both for commercial and non-commercial purposes. It looks like OsmAnd doesn't fulfil these requirements and the project has to hide OsmAnd by default in the F-Droid app listing. This is saddening as there are many Replicant users who are happy users of OsmAnd on Replicant (including myself). I hope that you might someday change the licensing of the app in a way that it is compatible with these guidelines!

Thanks!

**Comment by vshcherb** [comment]
OsmAnd has the own code distributed by GPLv3 license. So no exception, no exemption. 
Though all code stored in GIT repository definitely covered by different license. OsmAnd tries to explain all License details of the artifacts but it doesn't aim to make easy to build pure GPLv3 project otherwise there will be no artwork in this project.

The repository contains some artifacts which are not copyright of OsmAnd BV and not made by contributors for all these artifacts license exceptions are made TTS voice (https://github.com/osmandapp/OsmAnd-resources/tree/master/voice/pl/voice) and Icons8. They are purchased and it is fine to use these resources for "OsmAnd" product but not copying to other projects or products.

OsmAnd artwork is licensed in a different way on purpose for forbidding Google Play distribution of OsmAnd clones. There are still plenty of OsmAnd clones though they are violating this part of license. Artwork has copyright of OsmAnd BV, so it might be changed in the future.

Finally OsmAnd represents the project that you can build yourself and use for own purposes though distributing via Google Play already has limitations. For any other purposes the deep understanding is required.

OsmAnd F-Droid distribution is something great but might not be necessary easy to make. I believe for OsmAnd F-Droid the fork of OsmAnd should be maintained to make it pure & clean in sense of guidelines. Unfortunately we don't have enough power to do this.

BTW: copying resources to repository which primarily has GPLv3 doesn't change neither copyright of the original resource neither the distribution license.
