### ISSUE TITLE
POI vs. Building Representation

### ISSUE THREAD

**Issue by annasoloviova** [osmandapp/Osmand#3585]
Our user suggests small changes to the map style. Maybe they can be helpful.

"The bar is mapped as POI and is illustrated properly in Osmand, whereas the bakery is mapped as region (building property) and illustrates with a totally different font style, size and color as well as the house number added in brackets. I'd say there's no need to illustrate the house number in such a way. 

It'd be really cool if you could discuss and change the illustration style to be consistent (like the bar) and remove the house numbers."

![rsz_osmand_-_illustration_issue](https://cloud.githubusercontent.com/assets/12711814/24331931/93f901ee-1246-11e7-8a3b-57037732f31b.jpg)

**Comment by sonora** [comment]
I actually think it is correct as it can be unless we put much more evaluation logic in place here::

We need to display the house number also, there is no excuse or good reason to suppress that bit of information if contained in the data.

And where things are tagged as "building", it seems appropriate that that font style should "win" over the POI font style in our rendering order, since it is often the "higher-ranking" object. One building could home several amenities on different floors etc. And the house number should usually also rather belong to the building than to the POI. (Of course there are also cases with a 1:1 relationship of building and amenity, like your example, or amenities with multiple buildings, like medical centers or amusement parks. All in all what we have seems a valid compromise for a non-critical issue?)

**Comment by Aiurek** [comment]
I’d say it’s definitely a relevant issue. It might makes sense to generally reconsider the illustration of buildings, POIs with and without address data added in OSM as well as buildings with POI attributes.
Following reasons:
-	The font style and size is also affected if one specifically adds the address data to a POI mapped as node and not as region in OSM.
-	We wouldn’t be suppressing important information, since one gets the complete address data of a POI when selecting it in Osmand.
-	When selecting the option to hide house numbers (under configure map>hide>house numbers), the house numbers in brackets won’t vanish, although all the others are.
-	Like illustrated in the attached image, the house number even occurs twice: solitaire in between the building boundaries and as suffix of the restaurant name, what makes the suffix more or less redundant.
-	The deviation in font style and size between the restaurant and the bar is severe, as shown in the attached image.
-	Size of POI symbols + text is significantly higher if house number is added as suffix, which thus is unnecessarily limiting the space to illustrate a higher number of POI simultaneously in a proper way.
-	It’d potentially make sense to treat special amenities, for instance supermarkets or restaurants, differently when it comes to the selection of font style. Par example: Church = building font style, McDonald’s = POI font style.
-	If it’s a building with several POIs (e.g. medical center) mapped as node, the identical suffix is added to all of them when the address data is added in OSM, like illustrated in the attached image.

**Comment by Aiurek** [comment]
I’d say it’s definitely a relevant issue. It might makes sense to generally reconsider the illustration of buildings, POIs with and without address data added in OSM as well as buildings with POI attributes.


Following reasons:
-	The font style and size is also affected if one specifically adds the address data to a POI mapped as node and not as region in OSM.
-	We wouldn’t be suppressing important information, since one gets the complete address data of a POI when selecting it in Osmand.
-	When selecting the option to hide house numbers (under configure map>hide>house numbers), the house numbers in brackets won’t vanish, although all the others are.
-	Like illustrated in the attached image, the house number even occurs twice: solitaire in between the building boundaries and as suffix of the restaurant name, what makes the suffix more or less redundant.
-	The deviation in font style and size between the restaurant and the bar is severe, as shown in the attached image.
-	Size of POI symbols + text is significantly higher if house number is added as suffix, which thus is unnecessarily limiting the space to illustrate a higher number of POI simultaneously in a proper way.
-	It’d potentially make sense to treat special amenities, for instance supermarkets or restaurants, differently when it comes to the selection of font style. Par example: Church = building font style, McDonald’s = POI font style.
-	If it’s a building with several POIs (e.g. medical center) mapped as node, the identical suffix is added to all of them when the address data is added in OSM, like illustrated in the attached image.

![osmandpoi1](https://cloud.githubusercontent.com/assets/27865200/25292876/0c2338ae-26d0-11e7-88e7-d5d88c46f378.png)

**Comment by matthijskooijman** [comment]
To add one more datapoint: To me, the house number in brackets is confusing. I've seen them on my map, but it wasn't until I read this issue report that I realized the numbers were house numbers...

**Comment by vshcherb** [comment]
@xmd5a2  I think we should delete it cause our context menu could represent that information in a better form

**Comment by xmd5a2** [comment]
@vshcherb Disagree because visual address search will suffer from that change

**Comment by matthijskooijman** [comment]
@xmd5a2, I'm not sure what you mean now. You say that deleting the house number is not a good idea, but if I read your commit correctly, you *did* delete the house numbers. Also, the commit message really does not help here, it does not tell me anything about what was changed and why (and referring to this issue also does not really help, since there is some discussion about the best course of action).

**Comment by xmd5a2** [comment]
@matthijskooijman We discussed the issue privately, and decided it would be better to remove the house numbers in the parentheses from POI

**Comment by matthijskooijman** [comment]
Ok, thanks for clarifying :-)
