### ISSUE TITLE
Route mispronounced in UK localised TTS

### ISSUE THREAD

**Issue by sdfg2** [osmandapp/Osmand#3662]
I put up with it before there was a UK localised TTS, but now there is, can we please make sure that route is pronounced 'root'?  I've checked with my TTS (Ivona) and it pronounces the word correctly, so I can only imagine that it's something in the way OSMand does things (although, if it's not, of course I'll chase it elsewhere!)

**Comment by tobydickenson** [comment]
FWIW, google TTS gets this correct.

**Comment by sdfg2** [comment]
Interesting.  I wonder where the problem lies then, because as I say, I've tested the word 'route' alone with Ivona and it pronounces it correctly.

**Comment by sonora** [comment]
Strange indeed, because the pronunciation is controlled by your TTS engine, while the OsmAnd TTS config file only specifies the wording.

So the way to debug this is finding out what engine is actually used and with what parsmeters. Can you please first state here your Android (not OsmAnd) TTS settings. Secondly, could you pleasr temporarily enable OsmAnd's Development plugin, then go to OsmAnd's Settings / Development / Test voice prompts. I am interested in what output you see when tapping button 11.3. Also just to be sure, when you tap 9.8, do you hear "crossing", not "crosswalk", right?

**Comment by sdfg2** [comment]
@sonora

11.3 English (United Kingdom) LANG_COUNTRY_AVAILABLE
9.8 Yes, crossing.

Interestingly, I did a couple of other tests.

10.3 Correct pronunciation
10.4 Correct pronunciation
2.4 Incorrect pronunciation

It could be that it is just 2.4 with trouble, and that I have heard the most (given sometimes I know my way around town better than the routing does ;-) )

**Comment by sonora** [comment]
That's rather weird. I assume if you test with google TTS, Samsung TTS, or whatever engine cam with our device originally, there is no issue?

The only bright idea I have is that there is somehow a bug with the Ivona TTS engine, maybe misinterpreting "Route" as in "Route recalculated" (with a capital "R") somehow as a proper name. I have committed this workaround https://github.com/osmandapp/OsmAnd-resources/commit/ef8d97accee7a325a95f9f1c00fd764c43fd07b4, and it could be tested with our nightly build. (Alternatively, you could locate the file `_ttsconfig.p` in the folder `voice/en-gb` on your device in the OsmAnd data folder and make the same change there.)

**Comment by sdfg2** [comment]
Well, I must admit, I'm stumped.

'route' nope
'root' nope
' root' nope
' route' nope
' root ' nope
'cheese' yup
'root,' yup
'Route -' yup

I have no idea why this is happening.  It must be a bug in Ivona somewhere, but I have no idea why that would cause it.  Especially as 'root' is never pronounced as 'rowt'.  However, as far as I'm aware, Ivona isn't in development in the same way any more since it got bought over by Amazon, so I'm not sure what can be done about it other than editing the tts file.

**Comment by sonora** [comment]
So are you saying it works like I  have it now in the nightly, right?

**Comment by sdfg2** [comment]
@sonora No, I'm saying it doesn't work.  'Route' 'route' 'Root' 'root' all fail.  It's necessary to separate 'Route' and 'recalculated' with something before it reads correctly.  Currently I use a '-'.  It doesn't flow as well, though.

**Comment by sonora** [comment]
Well, while the ttsconfig file primarily defines the spoken wording, I believe its output is actually shown in writing on auxilliary devices like Android Wear.

So while in OsmAnd we could try some awkward workarounds like word 'route' as 'root', it may have funny side effects. The actual bug clearly seems to be with IVONA, and the more I think about this the more I come to the conclusion that a bug report should actually be filed with them rather than here?

**Comment by sonora** [comment]
Looks like I found no better workaround than the one you already have: Adding a surplus hyphen to sort of mediate the issue for IVONA.

But this cannot be a general solution, as it deteriorates the intonation for all TTS engines which do not exhibit the original issue.

Let me close this here, should anybody have an idea in the future please post here. Thx.

**Comment by sdfg2** [comment]
Is there a way to carry TTS edits across upgrades?

**Comment by sonora** [comment]
@sdfg2 Maybe what you mean is avoid a manually modified tts file from being overwritten by an OsmAnd update? Simply put it in a separate folder like en2-tts or similar.

**Comment by sdfg2** [comment]
@sonora Yes, I mean exactly that.  In that solution I'd need to select en2 as the tts?  That would ignore any updates on the non-edited parts too, right?
