### ISSUE TITLE
Turn screen on (if off)

### ISSUE THREAD

**Issue by Goodingn** [osmandapp/Osmand#3677]
This used to turn the screen off after a navigation point, then back on in time for the next.

What's happening now is the screen turns off at some point, possibly around Android screen timeout, then after a couple of seconds the screen comes back on and the blue navigation arrow travels up the screen. After a number seconds the auto-centre kicks in.

If I turn the screen off, it just comes straight back on again.

Cheers,

**Comment by scaidermern** [comment]
"the screen comes back on and the blue navigation arrow travels up the screen" is the issue described in #3674.

**Comment by Goodingn** [comment]
Thanks, that does describe one element of the problem, but differing from that issue, the screen isn't going off or on for me as expected.

**Comment by scaidermern** [comment]
I noticed that this feature requires the screen to be turned off manually. My smartphone goes on if the external power changes, e.g. if the power goes away or comes back. This happens for example if I turn my car on or off. Afterwards it stays on. This is pretty annoying but probably caused by Android and not changeable by OsmAnd.

**Comment by Zahnstocher** [comment]
The first implementation (2014) also turned the screen off after an announcement, even if the screen was already on, when the announcement started.
But later someone changed this behaviour, so that the screen has to be off at the time the announcement occurs, otherwise the screen will not be turned off by OsmAnd automatically after the announcement (specified delay).
Actually the timer (to turn the screen off) does only start, if onResume is called, so if the screen is already on, the timer never starts... If I remember correctly...

**Comment by Goodingn** [comment]
I'm finding if the screen goes off, or if I turn it off, it just comes immediately back on. Less immediately maybe if I'm stationary.

Also, if Osmand doesn't turn the screen off anymore, does it still need the Device Administrator permission?

**Comment by scaidermern** [comment]
> I'm finding if the screen goes off, or if I turn it off, it just comes immediately back on. Less immediately maybe if I'm stationary.

I didn't experience this issue. Maybe it is related to a specific navigation mode or setting?

**Comment by Goodingn** [comment]
Ok, this can be closed.

My main issue was with the screen not staying off, but I've discovered this was an app I use called 'Glimpse Notifications'. It was probably responding to the notification from Osmand where it shows the next navigation.

After adding an exclusion in Glimpse for Osmand I can now turn the screen off.

The remaining issue is covered on the other referenced issue.

Cheers,

**Comment by vshcherb** [comment]
Looks like the issue is fixed
