### ISSUE TITLE
Navigating external geo lat/lon

### ISSUE THREAD

**Issue by Goodingn** [osmandapp/Osmand#3705]
This is how it used to be, from about 2.5- an improvement from previous versions I might add:-

1. Use app POIPocket to select a desired destination, stored in that app.
2. In POIPocket, press Share, then press Osmand+
3. Wait about 5 seconds for Osmand to do some 'searching' (for what, I don't know, these are co-ordinates of exactly where I want to be)
4. Osmand shows the map, an orange pin of the destination an a blue navigate to button- press it (this is the improvement from previous versions)
5. Press Go

Until today, when 2.6.3 landed and broke things, I was going to suggest the following change- in step 4 and 5 have a countdown timer to auto press these buttons for me if I don't interact with the app.

Anyway, now in v2.6.3 it goes something like this:-
1. Use app POIPocket to select a desired destination, stored in that app.
2. In POIPocket, press Share, then press Osmand+
3. Wait about 5 seconds for Osmand to do some 'searching' (for what, I don't know, these are co-ordinates of exactly where I want to be)

4. A new search screen with 'geo:xxxx,yyyy' as criteria, which after a few seconds gives me at least two options.

5. Press Show On Map.
6. Am now back at original step 4 with blue navigate button.

Or

5. Press the world icon with geo co-ordinates next to it.
6. Nothing happens?

Or

5. Press Find More.
6. More searching.
7. Press increase Search Radius.
8. App crashes.

Also, if I do succesfully get a route, if I press the Back key, the app doesn't close, it takes me to a Seach Geo Location screen with nothing on it except a back icon.

Finally, when it does show a route a lot of the map where polygons extend beyond the screen there's a lot a blue, making the route look like it's traversing an island.

Ta.

**Comment by Goodingn** [comment]
For this scenario, for a shared geo lat/lon, the new searching is all unnecessary.

**Comment by vshcherb** [comment]
It is not clear POIPocket uses a proper "geo:" intent. Anyway needs to be debugged.

**Comment by Goodingn** [comment]
Thanks.

Now you mention 'proper "geo:" intent', I've got a script I put together in an app named E-Robot (by Tamas Barta).  It stores current lat/lon when I exit car mode, i.e. stores a parking location, and when I start the script shortcut it starts a geo intent containing that lat/lon by combining strings together.

What it ultimately runs is:-
am start --user 0 -a android.intent.action.VIEW geo:xxxx,yyyy?z=16

That script also gives same behaviour as described above.

Hope that helps a little.

**Comment by foresto** [comment]
I have the same problem after upgrading from 2.6.2 to 2.6.3.

The old behavior was just fine: I would tap an SMS that contained a google maps url with coordinates, and OsmAnd~ would go directly to the map with a pin in the target locatoin.

The new behavior is to pop up an intermediate screen (shown below), requiring me to read three lines of text, figure out that all three of these are buttons, guess at which option will do the thing it was supposed to do in the first place, tap one of the buttons, and wait even longer to get the map that I wanted in the first place. It is incredibly annoying.

To make matters worse, the top item remains on screen as an overlay after the map appears, covering up information that I wanted to see. By this time I'm usually driving, so figuring out what happened and aiming my finger at the X to get rid of it is both awkward and potentially dangerous. As far as I can tell, this overlay's sole purpose is to show the url that I tapped earlier and offer a back button, bot of which are unnecessary (I already know that I tapped that url, because I tapped it after all, and Android has a back button already).

If I tap the bottom button (the one with the globe icon and a description of the location), OsmAnd~ crashes with a java.lang.ClassCastException. I'll file a separate bug report for that.

![Annoying Intermediate Screen](https://i.imgur.com/w0JIrZI.png)

**Comment by vshcherb** [comment]
Double checked the code the commit was moved to 2.6.4 and here is the build to check. More fixes need to be done on 2.6.4 before it will be  released. You can test version "-pre" here http://download.osmand.net/releases/?C=M;O=D

**Comment by foresto** [comment]
Not fixed in net.osmand-2.6.4-pre. Intermediate screen still appears when launching via lat/lon URL.

**Comment by Goodingn** [comment]
Agree- still there.

If I'm sharing a lat/lon from another app that's the exact place I want to go, I don't need a search screen.

The intermediate search screen also never returns any results. If I do a 'search near here' from the map screen I'm taken to categories and they do return results.

I use the 'back' key now to deal with this intermediate search and I'm at the map screen where I need to be. I can see the position I've shared, and I can navigate directly to it. I can also, if necessary, do a 'search near here'.

**Comment by Goodingn** [comment]
Still not fixed 2.7.2.

Why is the extra search step there for an externally shared geo: reference!?

**Comment by foresto** [comment]
Please re-open. This is still not fixed in 2.7.5.
