### ISSUE TITLE
explain OLC

### ISSUE THREAD

**Issue by HolgerJeromin** [osmandapp/Osmand#3708]
I really like the idea of open location code. I saw the codes on the "details of a point" in the beta version but i could not find out what code these numbers are. 
Only after reading the blog post i got the keyword OLC.

So perhaps the last two lines in the menu should be:
Lat 51.123 Lon 8.13123
OLC: 9F3CWG55+2H

and a click could go to http://openlocationcode.com/ or even the matching [demo page](https://plus.codes/9F3CWG55+2H)

**Comment by sonora** [comment]
I guess prefixing "OLC: " is a valid idea, but then we would likely have to do the same for e.g. UTM, and it may be clumsy to see this all the time?

The alternative is we do not by default display OLC unless a user explicitly requests it (e.g. as app default "Coordinate format" in the General settings, or by using OLC mode in Coordinate search). I have always found it awkward that we invariably display the OLC string at the bottom of our context menu and by this give OLC a "special treatment" over all coordinate formats, which we only display if the app is set to it or the users selects it). Why do we not also display UTM by default? What wuld we do if we decided to add also add support for e.g. http://what3words.com?

**Comment by sonora** [comment]
Related: #3695.

**Comment by njohnston** [comment]
OLC is of no use to me, so I'd like a way of hiding it.

**Comment by HolgerJeromin** [comment]
Perhaps OLC (and lat/lon?) at this place should be completely moved away into the share menu.

**Comment by pebogufi** [comment]
I like very much it to have the coordinates visible and to get it copied into clipboard with a long cick on it.
In which format ? Just use the format selected in settings. This is consequential.
And ONE format might be enough. So I agree to sonora.
Peter

**Comment by sonora** [comment]
So I guess we should simply remove https://github.com/osmandapp/Osmand/blob/master/OsmAnd/src/net/osmand/plus/mapcontextmenu/builders/AmenityMenuBuilder.java#L489, then the display only shows the format selected in General settings, which should suffice.

**Comment by polarbearing** [comment]
> And ONE format might be enough
As we are in a transition phase to something new, we might need both. The OLC to communicate with Those Who Know, and the Lat/Lon to call an ambulance to your car accident without fiddling in the settings...

**Comment by aceman444** [comment]
I think many common users need NO coordinates (whether lat/lon or OLC). I'd like a way to hide all of them.

**Comment by vshcherb** [comment]
Many users don't context menu or many items present there that shouldn't lead us to remove it. My point lat/lon are absolutely necessary cause it is a verbal standard of sharing location. You might need 1 out of 1000 times but you know it is always there and you don't need to dive in 100 settings to discover how to enable it.

**Comment by aceman444** [comment]
Well, there could always be some hotspot in the POI details that when activated reveals the coordinates and OLC. But until then it does not contribute to the height of the details list.

**Comment by alexanderdd** [comment]
I like OLC. I think it's the best geolocation code system there is at the moment.

**Comment by aceman444** [comment]
> It's a chicken-and-egg problem, and if the open code is not propagated by an open-source tool, using open geodata, by whom else?

Why should an open-source tool propagate anything? OLC seems to be just something invented by google thrown into the world as open source for some reason. The wikipage lists NO apps supporting the system. Even the official webpage only mentions Google maps supporting it (no wonder). So there does not seem any adoption of it.

https://github.com/google/open-location-code/wiki/Evaluation-of-Location-Encoding-Systems mentions 10 other location code systems. 

So why should OsmAnd clutter its interface with this one?

**Comment by alexanderdd** [comment]
I think implementation in OSMand should be determined by:

(1) Do we think location codes are a helpful addition to the app?
(2) If yes, do we think OLC makes more sense to use than other location
codes?

My opinion:
(1) While not commonly used yet, I believe that location codes are a great
idea and will become more widely adapted. Someone has to start, why not us
(i.e. are we innovators or followers)? Since the code is shown only after
tapping on a location/poi, I don't think it adds additional clutter.
(2) I agree with the analysis in https://github.com/google/
open-location-code/wiki/Evaluation-of-Location-Encoding-Systems and think
that OLC makes the most sense. I don't care if google developed it or not,
the design of OLC just makes most sense to me.

Other opinions? Should we do a poll on this?

Alex

On May 24, 2017 12:56 PM, "aceman444" <notifications@github.com> wrote:

It's a chicken-and-egg problem, and if the open code is not propagated by
an open-source tool, using open geodata, by whom else?

Why should an open-source tool propagate anything? OLC seems to be just
something invented by google thrown into the world as open source for some
reason. The wikipage lists NO apps supporting the system. Even the official
webpage only mentions Google maps supporting it (no wonder). So there does
not seem any adoption of it.

https://github.com/google/open-location-code/wiki/Evaluation-of-Location-
Encoding-Systems mentions 10 other location code systems.

So why should OsmAnd clutter its interface with this one?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/osmandapp/Osmand/issues/3708#issuecomment-303833833>,
or mute the thread

**Comment by Norbert80** [comment]
Please note the request for improvement in #3881.
