### ISSUE TITLE
speedlimit warning useless in Netherlands

### ISSUE THREAD

**Issue by okkebal** [osmandapp/Osmand#3719]
If you tell osmand to warn when you are 0km/h over the speed limit it does not work. It warns when you are about 5km/h over the limit, so I still get tickets.

This feature should prevent speeding tickets, but it doesn't.

Stange enough there is a warning sign that shows up on screen with current speed limit, but you are not always watching the screen. If osmand would.produce a warning sound every time the speed warning appears on screen that would be perfect.

**Comment by sonora** [comment]
I have just tested that also with speed limit tolerance set to 0 I do get warning prompts all right, plus I find no immediately obvious flaw in the code. Certainly: If you enter a speed zone say already 5km/h faster than the limit, you would of course also hear (and see) a warning, not just if you accelerate within the speed zone. I believe we may have a little grace mechsnism between entering a speed zone and when a warning would sound, to avoid false positives due to location errors, mapping errors, and in the transition time when you are already slowing down, but not sure.

But I may misunderstand your issus here, what exactly is the problem and how should I reproduce it?

**Comment by okkebal** [comment]
If you enter with 2 km/h too fast there is no sound. 

If you enter with 5 km/h too fast there is a warning, you then slow down, and a minute later (unknowingly) speed up some, no warning when you go over.

There are many instances where the speed sign appears on screen but there is no audible warning.

This "grace period" leads to speed tickets. You already get a speeding ticket when you are 2 km/h over the speed limit.

It would be perfect for me if there is a little "ding" sound every time the speed sign appears on screen.

Another solution would be an extra option to warn at "-5 km/h", but better would be the "ding" sound.

**Comment by vshcherb** [comment]
5kmh is a reasonable limit. OsmAnd doesn't support Traject Control which is quite popular in the Netherlands where the average speed measured (it might be good for another ticket). 
Usually builtin speedometer tend to lower the actual speed and GPS tend to higher it, so this feature is not supposed to warn you every second you exceed the speed limit, it would be very annoying in many cases (OSM data is not correct for example). 

This feature is designed to give you a sign if you are going with a different speed than supposed 60kmh instead of 50kmh. Since there are not speed limits 52kmh or 57kmh, this is good enough.

For precise speed tracking you could have a widget with current & max speed on display.

**Comment by okkebal** [comment]
So no solution for me, no "ding" sound when the visual warning appears...

My previous routing software did have this feature. It would be annoying if osmand would start to talk every time the on screen speed warning appears thats why there is only a small sound every time you go over the speed limit in my previous software. 

Please explain to me why you don't want an audible warning when you go over the speed limit, but you do want a visual warning... Do you really expect people to constantly look at the screen... should not the software stimulate not watching the screen.

**Comment by okkebal** [comment]
Ps: the tickets I still receive are not from traject control, but purely from driving too fast past an inspection point because osmand does not warn in time. The fix is soo simple

**Comment by okkebal** [comment]
Ps: another thing, the "ding" sound feature would also negate a new very complex traject control feature. The ding feature would.make sure that on the traject you would stay within the speed limit too. So it should solve that as well.

**Comment by okkebal** [comment]
Mapfactor gps navigation does have this feature, no irritating talking when you go over the speed limit, just a ding sound every time you go over the speed limit. Yes every time... so it nicely corrects you every time you go over. It also has a framerate in fps instead of spf (seconds per frame). Map downloads are also a whole lot smaller. So if you also get speed tickets and want this feature don't look at osmand, just get Mapfactor

**Comment by polarbearing** [comment]
Beep instead of verbal announcements was already discussed in #1739. It is a relict from old times when devices were not capable yet to give more useful information. 
Actually you can modify the TTS config file in your own device to play any ding-dang-dong you want when you are speeding. 
Further, both max and current speed are handed to the TTS config file, you can find [here](https://github.com/osmandapp/OsmAnd-resources/commit/2112fafb2dfa7211e64f7af1b3da260f3232547e#commitcomment-17752490) an example for a statement that says for example "7 over 50" when you drive 57, which is quite useful giving you both the delta and the limit.

**Comment by okkebal** [comment]
Sure, but I'll still get tickets, the police here do not have a "grace period". So no thanks, I'll use software from old times, thank you very much.
