### ISSUE TITLE
Wrong processing of opening_hours

### ISSUE THREAD

**Issue by kreuzschnabel** [osmandapp/Osmand#3731]
Using: OsmAnd+ 2.6.3 on Android 6.0.1, standard vector maps

The opening hours of veterinary practice http://osm.org/node/872551826 say "on appointment" in the database, this seems to be misinterpreted by OsmAnd as "Mo-Su off" (and given this way when viewing the POI’s properties).

Other vet practices are "Mo-Su off" in OsmAnd only (which surely would not boost business!) 

--ks

**Comment by verdulo** [comment]
Please check the rule with this tool: http://openingh.openstreetmap.de/evaluation_tool/
the correct value should be:
`Mo,Th 09:00-11:00; Tu,Fr 15:00-17:00 || "on appointment"`

Another problem related to opening hours:
https://www.openstreetmap.org/way/168471354
On 3rd May 15:31 it's displayed as "maj 1-3 10:00-19:00" but with red font (closed).

**Comment by chiak597** [comment]
Another issue related to opening hours:
https://www.openstreetmap.org/node/4518892751

"12:00-12:40 closed" is interpreted as "Mo-Su 12:00-12:40" (instead of correct "Mo-Su 12:00-12:40 closed"), overwriting previous rules.

According to evaluation tool, this opening_hours string format is correct:
http://openingh.openstreetmap.de/evaluation_tool/?EXP=Mo-Fr 08%3A30-17%3A00%3B Sa 08%3A30-12%3A00%3B 12%3A00-12%3A40 closed%3B PH closed&lat=48.7769&lon=19.1844&mode=0

**Comment by vshcherb** [comment]
"12:00-12:40 closed" not supported and may have another issue for that.

**Comment by vshcherb** [comment]
`Mo,Th 09:00-11:00; Tu,Fr 15:00-17:00 || "on appointment"`
This line works properly.

**Comment by vshcherb** [comment]
```Mo-Fr 08:30-17:00; Sa 08:30-12:00; 12:00-12:40 closed; PH closed```
might be technically correct but it doesn't logically correct there is no sense to specify ```12:00-12:40 closed; ```

**Comment by vshcherb** [comment]
https://github.com/osmandapp/Osmand/commit/09fa94a4b8210ad3af559bd1009c3757b21de9ac
