### ISSUE TITLE
Missing SRTM numbers

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/Osmand#3802]
The contour lines plugin/add-on does show contour lines but since some update the numbers indicating the altitude are missing. Only around peaks the numbers are sometimes shown. This renders the plugin less useful than before. 
Two example screenshots are attached. I am using Osmand 2.6.3 with contour plugin 1.0 (27. December 2016). 
Is this a bug or am I missing something in the configuration? 

![h1](https://cloud.githubusercontent.com/assets/1042025/26328856/f6f2b2c4-3f44-11e7-9364-7a4011ed88e9.png)
![h2](https://cloud.githubusercontent.com/assets/1042025/26328857/f70c1872-3f44-11e7-9c8e-9cc9c7798387.png)

**Comment by breversa** [comment]
Also, the altitude numbers should be oriented so that the top of the label points to the highest altitude (like all paper maps I know do).

In the Lawand exemple above, the 2100, 2120 and 2140 labels at the bottom of the screen are correctly oriented towards the higher elevation, while the 2130, 2160, 2170, 2180 and 2190 point to the lower one.

(Yes, I know that means that labels may end up being written top-down, but is there any other way to tell (quickly, without error risk) where's uphill/downhill ?)

**Comment by aceman444** [comment]
Interesting idea.

**Comment by xmd5a2** [comment]
Looks like rendering engine (tile-based, not OpenGL) renders text on line only once. textMinDistance does nothing now. Does this refer to the fixing of street names for streets with many segments?

**Comment by vshcherb** [comment]
http://www.openstreetmap.org/relation/47308#map=14/46.7342/11.1643

**Comment by xmd5a2** [comment]
Fixed https://github.com/osmandapp/OsmAnd-core/commit/a1a0fc7a3c0fe95c7b516eef76d6669ee49fd974

**Comment by Nine-Tailed** [comment]
Откорректируйте поворот меток высоты на стиле Topo, сейчас текст написан строго горизонтально, а желательно как в стиле Osmand.
Please correct the rotation of the altitude marks on the Topo style, now the text is written strictly horizontally, and it is desirable as in the style of Osmand.
