### ISSUE TITLE
Incorrect height calculation.

### ISSUE THREAD

**Issue by PaulStets** [osmandapp/Osmand#3808]
The screenshot shows an area with 29% slope. This is wrong because there is a 1 km long street going up from 280m to 370m. This is 90 m height difference by 1km length is 9% slope in reality.
The link to the location: http://osmand.net/go.html?lat=51.24712&lon=7.4845695&z=17

![screenshot_2017-04-28-09-35-09](https://cloud.githubusercontent.com/assets/20681525/26354329/d2153e80-3fcc-11e7-830d-f455c88a67b6.png)

**Comment by xmd5a2** [comment]
Is it a route or gpx?

**Comment by xmd5a2** [comment]
Looks like these graphs are calculated from GPX. It is required for analysis.

**Comment by vshcherb** [comment]
Looks like this is a problem of GPX recording device (cause this is a recorded gpx file). It is clearly visible that height is jumping up & down, though it might not be correct to reality. For that purposes high precision track system could be used

**Comment by Sixtron** [comment]
This is from me. I used high precision gps. To get a more exactly result the approximate distance for measuring the percent in high must be longer i think because of the incorrect sensor data from the smartphone. The smartphones don't deliver good high data and this you should filter out like you did with the kahlmann filter for the compass. If you don't, this percent data helps nobody.
