### ISSUE TITLE
"Error reading GPX data" when opening a GPX file downloaded by Chrome

### ISSUE THREAD

**Issue by arteme** [osmandapp/Osmand#3840]
Using OSMAnd+ 2.6.3 on an Android 6.0.1-based phone (Redmi 4 phone, MIUI 8.2 ROM, xiaomi.eu 7.1.19 version) I have an issue that when a GPX file is downloaded by the browser (Chrome), then OsmAnd fails to open the file with an "Error reading GPX data" toast, but if the same file is placed in the OsmAnd's tracks folder (/storage/emulated/0/Android/data/net.osmand.plus/files/tracks), then the track opens perfectly fine through the "My Places > My tracks" menu.

The intent to open the GPX file looks as follows:
```
Action name: 
android.intent.action.VIEW

Categories:
NONE

Type: 
application/x-gpx+xml

Data: 
file:///storage/emulated/0/Download/Korso96-kierros-1.gpx

Flags:
FLAG_ACTIVITY_FORWARD_RESULT
FLAG_GRANT_READ_URI_PERMISSION
FLAG_ACTIVITY_BROUGHT_TO_FRONT
FLAG_ACTIVITY_PREVIOUS_IS_TOP
FLAG_RECEIVER_FOREGROUND

Extras:
NONE
```
I've tried different files downloaded from different sites. Some report as "application/octet-stream", some as "application/gpx+xml", some as "application/x-gpx+xml" all exhibiting same behavior.

What am I missing?

**Comment by floscher** [comment]
The same happens when I send a GPX file via [Signal messenger](https://github.com/WhisperSystems/Signal-Android).

It shows the toast `Error reading GPX data`. But nevertheless on the dashboard an entry of size 0kB and with no name occurs in the `All tracks` card:
![screenshot-dashboard](https://user-images.githubusercontent.com/3904348/26879256-b80bdef2-4b90-11e7-9385-83ad5e284dfc.png)

I can even tap on it and it opens a details view with only the `show on map` toggle:
![screenshot-gpx-details](https://user-images.githubusercontent.com/3904348/26879340-07e868fa-4b91-11e7-92a9-73efc9e77a9b.png)
and it shows on the map normally, but when I go to `My places`, it is not appearing, neither under `Tracks` nor under `Rec`.

**Comment by vshcherb** [comment]
The problem is related to permission, OsmAnd could not access Download folder (possibly giving external storage permission would help, but not 100%). That problem was fixed recently.
