### ISSUE TITLE
Different route depending on start position 

### ISSUE THREAD

**Issue by OpenSourceForEver** [osmandapp/Osmand#3859]
Osmand nightly build downloaded on may,30
Offline maps, Spain. may, 1, 2017
Fastest route and avoid toll roads

From: https://www.openstreetmap.org/#map=18/40.98325/-4.13023
To: https://www.openstreetmap.org/#map=17/43.38901/-4.10787

From: https://www.openstreetmap.org/#map=19/43.31324/-4.07110
To: https://www.openstreetmap.org/#map=17/43.38901/-4.10787

Depending on start position route is different at https://www.openstreetmap.org/#map=13/43.3427/-4.0443

**Comment by OpenSourceForEver** [comment]
Sorry, I can not attach files with screenshoot.

**Comment by Norbert80** [comment]
- Please got to the developer plug-in and disable two-phase routing

- Re-start OsmAnd

- Try ifcthe routes are still different

**Comment by OpenSourceForEver** [comment]
Thanks @Norbert80 

If I select "disable complex routing" the issue is fixed but route calculation is very slow (more than 20 minutes waiting for a 340 km route).

Developer plug-in is for developers. Is there any way to solve this issue without select "disable complex route"?

**Comment by Norbert80** [comment]
Thanks.

Thinks this is an old bug in. OsmAnd's routing algorithm. With two-phase routing two threads are searching for the best route. One from start to destination. Ine from destination to start. Somewhere in the middle noth threads "meet". It looks like penalties are calculated wrong on that meeting point where both threads meet.

I already filed this bug (with different test coordinates) several times. But @vshcherb alamways closed this bugs without fixing the rout cause.

**Comment by Rolf558** [comment]
See also...

https://code.google.com/archive/p/osmand/issues/2580

**Comment by vshcherb** [comment]
<img width="390" alt="screen shot 2017-10-15 at 15 22 52" src="https://user-images.githubusercontent.com/1042025/31585180-dfd0d350-b1bd-11e7-8466-f1cdace13c44.png">
<img width="340" alt="screen shot 2017-10-15 at 15 22 33" src="https://user-images.githubusercontent.com/1042025/31585181-dfe79c66-b1bd-11e7-8160-5c5bb4300caf.png">
To illustrate the problem from the description.

Via highway: complete_time = "2329.987" routing_time = "1948.4299" 
Current implementation: complete_time = "1800.4788" routing_time = "1911.4451"

**Comment by vshcherb** [comment]
Observations:
1) The difference between routs is quite small *30 seconds*, so the bug could not be considered as critical from route engine perspective
2) Strange enough complete_time is smaller than routing_time 
3) complete time between 2 routes is very big *500 seconds* = 10 minutes. It needs to be investigated from routing.xml perspective what gives such a big difference

**Comment by vshcherb** [comment]
Answers:
2. Possibly smaller because A) no penalty_transition taken into account for complete time B) obstacle for routing time is higher than obstacle_time for trip time. 
3. Trip time (not routing optimization time) will be mostly equal if one rule will be disabled 
```<select value="15" t="highway" v="crossing"/>```
Then  complete_time = "1774.9877" vs  complete_time = "1680.4786", so the difference < 80 seconds

**Comment by vshcherb** [comment]
So, let me summarize. If we leave out the general issue and focus on the provided details, we have more or less 2 same routes. If we calculate the route with all details (much slower), than route A is faster than B by *30 seconds*, if we calculate the route using simplified maps for longer distance than route B is faster than A by *70 seconds* (1351.1759 vs 1280.3401). Unfortunately, I don't think changing parameters in routing.xml is feasible for this case. So it is not a critical particular issue rather a generic known issue.

Different route depending on start position. Yes, that's a flaw of current implementation. Obviously if you always calculate routes on the same data & using the same algorithm you will have same subroutes independent from a start position. Because OsmAnd uses 2 different routing data to speed up the routing, it is expected that subroutes will be different based on a start position (roughly 50 km routes always use precise data).

We can't fix the "Different subroute depending on start position" though we might be able to fix the usability issues related to that.

**Comment by OpenSourceForEver** [comment]
> We can't fix the "Different subroute depending on start position" though we might be able to fix the usability issues related to that


For example?

**Comment by Norbert80** [comment]
@vshcherb thanks for looking at this issue.  But why did you close this issue while saying that there are things that should be observed in detail and usability issues that could be fixed?

**Comment by vshcherb** [comment]
The original issue is closed because the difference between routes doesn't seem to be critical. I don't know which & how could be fixed
