### ISSUE TITLE
problem to route to the island "sylt", german

### ISSUE THREAD

**Issue by osmvermesser** [osmandapp/Osmand#3887]
in the northsea at the coast of germany is an island "Sylt". http://www.openstreetmap.org/?mlat=54.8861&mlon=8.6050#map=11/54.8861/8.6050

you only can get to the island by Train (dam), ferry or plane.

at the dam is an emergency way - start by a barrier (https://www.openstreetmap.org/node/2425961854).

if you try to route for foot the way will use the emergency-way! other routing-apps on the openstreetmap.org site will route over other islands and Ferrys

![osmand_hindenburgdam](https://user-images.githubusercontent.com/6803899/26863039-355259cc-4b50-11e7-8f90-51888995deb6.png)

**Comment by osMatt** [comment]
I think the problem is the access constraint on the [way that follows](https://www.openstreetmap.org/way/41335200), it is tagged with `access=emergency`. This is not a combination listed in [the wiki](http://wiki.openstreetmap.org/wiki/Key:access). Instead it should be probably better be tagged with `access=no` and `emergency=yes` (although `emergency=yes` as an access tag [is not undisputed](https://wiki.openstreetmap.org/wiki/Talk:WikiProject_Emergency_Cleanup#Tripple_meaning_of_the_emergency.3D.2A-Keys)).

**Comment by vshcherb** [comment]
Agree with @osMatt
