### ISSUE TITLE
SLOOOOOWWWWW Downloads

### ISSUE THREAD

**Issue by Codyclifford** [osmandapp/Osmand#3890]
I have the Paid version of OSMAND+ 2.6.5  on Android 6.0.1. I am trying to download the Maps and it is taking FOREVER. on top of that it has Corrupted my sd card twice so far causing me to have to reformat and loose what maps I was able to get, not to mention all the other data on my SD card,. Please help!!

**Comment by sonora** [comment]
I have just tested a few downloads and the download speed sees only limited by the Internef connection I have. So in order to judge this you would have to quantify what you mean by 'slow', i.e. which download takes how long exactly, and also what your Internet access speed is. Reading your post as is, I would actually suspect a hardware issue on your side. If your SD card keeps getting corrupted, please try another one (there are flaky and fske ones out there which fail after writing data beyond a certain size, and some are simply faulty or defect). If this does not help, test by temporarily setting OsmAnd's data folder to intrernal memory to see if your device's SD card reader has an issue.

**Comment by Codyclifford** [comment]
It took almost 8 hours to download the world map of 184 mb. Meanwhile my
app updates are downloading 100mb files in about 45 seconds. I have tried
it both ways internal and external... Did not make a difference. I have now
been able to make some head way, with the Florida file only taking about 3
hours  but that is still incredibly slow.

**Comment by vshcherb** [comment]
Just tested using PC version of downloads, bandwith looks reasonable http://download.osmand.net/list.php. Servers also look half empty. Please try to download using Web version.
