### ISSUE TITLE
Add chart with altitude for route in navigation.

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd#3895]
Add chart with altitude for route in navigation.

**Comment by vshcherb** [comment]
Could be a good story for trip computer

**Comment by littlehelper** [comment]
On the one hand an elevation view of the route in navigation planning menu is now available.
An elevation view showing also the ridden part of the route/track as cycle computers do on the other hand is proposed in #5684 and #9058.

**Comment by sonora** [comment]
If we do this, I have the following additional thoughts:

We have 2 largely redundant screens,
 - our 'GPX analysis' (you reach it when tapping on any GPX file under MyPlaces) screen
 - and the related GPX 'Analyze on map' screen (a little less powerful in options, but more apt to be displayed during map use.)

Can I suggest we reduce complexity by combining both into one, i.e. merge all features, and make it minizable so that a minimized version may be kept visible during navigation. Then we could add the feature to indicate your own position on its chart (if you are near the displayed GPX file).

**Comment by vshcherb** [comment]
This request is merged to https://github.com/osmandapp/OsmAnd/issues/5684
