### ISSUE TITLE
problems with to big gpx files with a lot of wpt's

### ISSUE THREAD

**Issue by treakiandroid** [osmandapp/OsmAnd#3910]
Hi there,

i have now imported the file gpx file from freifunk-karte.de 
( https://www.freifunk-karte.de/fetch.php?content=gpxfile ) which includes now 40477 points. It was now problem to work with this amount of data on the desktop with gpsprune, but osmand was on its knees (app dosent react; wait or cancel all the time...).

Also its put them together with my favoriten (default category) under which i couldn't found them anymore. All operations like renaming the category or changing its colour took much to long (as if the database would have a lot of redundancy that had to be changed)...

Could you please improve the handling of big files, or at least warn users before import if your algorithm is to weak?

Also please dont put them all in the default categories but ask the user where to put them to dont loose track of which are the own and which not.

Thanks a lot in advance

and please keep up the good work.

PS:
```
Database like i guess yours is

table points:

Point ID;	Point name;		Point latitude;		Point longitude;	category name;		Category color;		Category visibility
================================================================================================================================
1;			Home;			53.35606;			9.96106;			Favoriten;			Yellow;				true
2;			Work;			53.24819;			10.44648;			Favoriten;			Yellow;				true


How it may could be better:

table points:

Point ID;	Point name;		Point latitude;		Point longitude;	category ID;		
========================================================================================
1;			Home;			53.35606;			9.96106;			1;					
2;			Work;			53.24819;			10.44648;			1;					

table categories:

category ID;		category name;		Category color;		Category visibility
================================================================================
1;					Favoriten;			Yellow;				true
```
See also:

1 to n realation t. points > t. categories

See also:

https://en.wikipedia.org/wiki/Database_normalization

But much more annoying is that the map is unusable with to much visible points then you have to wait ages to change color/visibility/name of your big category. So you shouldn't do initialisation of all points but only them of them in the viewing area and around it and if you zoom out to much, do some points grouping so that you can have a much lesser memory/calculation footprints. Or just disable map viewable of to big cathegoryes at all and let them only search in table form (what are the nearest points from this one of the category ffnodes?)

**Comment by sonora** [comment]
Similar to #4676.

Looks what I had hinted there is becoming reality: With increasing popularity, OsmAnd will naturally be used as database and admin software to administrate larger collections of geo-points.
- If we want to support that, we need to improve our databases and related code.
- If we cannot support this well, we should warn the user when an (import etc.) operation will likely not be handled well in OsmAnd or is even likely to crash it.

**Comment by sonora** [comment]
Another observation: I have now resorted to **not** importing these big GPX files as Favorites, because their handling in OsmAnd is so slow. **Instead, I created a "TravelKnowhow" (or similar) subfolder in OsmAnd's `track` folder, and place those GPX files there.**

- If you then in OsmAnd go to My Places / **Tracks**, you can select to display those corresponding GPX that (which in this case contain no `trkpt` but only points of interest as `wpt`). Displaying, hiding, etc. here works almost instantaneously, even for large files containing thousands of points.

- In fact, I also export my Favorites as a favorites.gpx and handle them in the same fashion, MUCH faster than via the dedicated "Favorites" tab.

@vshcherb I think the lesson to learn here is that there is room for improvement in how we handle "Favorites" today, particularly in light of the new WikiVoyage "Points" display, which seems to also use my "_treat points as GPX track_" approach.
Currently we need the functionality of the "Favorites" tab because of its configuration options of adding points, managing fav categories, display color, etc.

- But in a step 1 we could, when it comes to internal handling, maybe simply create an intenal favorites.gpx and use our track related code to handle its display?

- In a step 2 it may even be feasible to combine our current Favorites and Tracks tabs in the UI,, because the logical distinction between "GPX tracks", "GPX collection of POIs", and "Favorites" seems to somehow disappear in some way...?

**Comment by vshcherb** [comment]
Yes, Favorites is legacy way of dealing with points. In the advanced future I would say. 
Favorites without group: special GPX with mostly used points (Home,. ...)
Group Favorites: each is a separate GPX track. 
And each GPX track could become Group of Favorites. 

And yes we are slowly-slowly moving to rename GPX -> Trip to complete unification.

**Comment by sonora** [comment]
Yes, exactly my opinion also.

Only the wording I am not sure about yet. 'Trip' may not hit it 100%, maybe we can keep 'MyPlaces', or expand it to 'MyPlaces & Trips' or similar.

**Comment by vshcherb** [comment]
The only issue with Trip that it doesn't represent "Collection of Points" -> like "Restaurants in Berlin".
Though anyway we started merging functionality that GPX and Favorite Groups could function very similar. For example in Markers you can select either GPX or Favorite Group, etc...

**Comment by sonora** [comment]
I will think about a wording.

Side note 1: When in a Wikivoyage article you tap the "Points" button, it takes you to you GPX analysis screen (or some derivative of that), but the "Tracks" tab is shown initially, which is usually empty. I guess we could put people to the "Points" tab of that screen right way in cases where no trkpt are contained?

Side note 2: When for any saved GPX file, you go to its Points tab, select a point, hit "Edit", but then cancel out of the dialog, the file time of the GPX file is still changed to (though the file was not changed, I hope). This is bad for people who sync their files, and we should fix in the course of migrating our Favorites mechanism to the GPX-related mechanism.

**Comment by sonora** [comment]
@vshcherb  Regarding Wording: GPX files can be
- routes (calculated)
- tracks (recorded)
- Collection of points (like from travel guides)
- Tour suggestions (from hiking guides)
- Personal location markers (collected, former "Favorites")
and maybe more...

I guess under the circumstances "MyPlaces" is the best I can come up with for all:
"My" is the convention implying a degree of personlization (here for both your personal assortment and its files' content), and "Places" covers all of the above. 

I suggest we use MyPlaces as the headline  for the combined functionality (like we have today in our menu already), and on the lower levels drop all only partially valid specifications like "Trip", "Track", "Favorites", etc.? (Unless where it strictly refers to contents of the TopoGrafix namespace, like `trkpt`, `rte`, these can continue to be displayed on tabs called "tracks", "route points", etc.)

**Comment by vshcherb** [comment]
While having a separate conversation on this topic, I would say that before changing naming in the application we need to converge some functionality and not hurry doing it this release

**Comment by sonora** [comment]
Ok, sure, no harm done yet. I had only consolidated some strings already to get ready for the task, while keeping those strings separate we may need separate. 

Only thing worth thinking about already for the release is generalize our tab headline and configure map menu item from Tracks to GPX files, because latest with the arrival of our travel guide points files listed and managed on that tab and map menu, "Tracks" has become too specific now.

**Comment by vshcherb** [comment]
One more, I'm looking forward with Tracks will becoming Trips. But that's a big step and we should prepare across all application and possible create special filers like "Tracks", "Points collections", "Wikivoyage trip", "Recorded tracks" ...

**Comment by sonora** [comment]
Yes, offering things in split tabs like that sounds like a feasible concept. Though what some tour books now start to offer is "mixed" GPS files with e.g. walking tour suggestions (contained as "track") and the "must sees" (as "points"), so in that respect a file-based approach for the UI may be superior over a split in tracks/vs. points/vs. routes.

We will see. Naming wise, the English "Trips" has considerable but not 100% overlap with the English "Travels", and in many languages there may not even be a distinction between the 2 expressions, which could lead to less meaningful translations. (Plus "Trips" does not cover point collections really well.)

Maybe "**My Trip**s" would work. Will keep thinking about possible solutions so we are ready when the time comes. :)

**Comment by vshcherb** [comment]
Just to say again, changing just a name doesn't help to solve the issue. To reach wide audience OsmAnd will need an introduction screen - "My Trips" - "Here you can find all you recorded tracks, collection of points with description, travel guides from wikivoyage,  trip files shared with others. OsmAnd natively uses GPX format to store all you trips, so you can exchange with other programs using this format."

So it is a big task to explain and it is not just wording, it is about structure first. Though I'm not ready to do it now, hope to dedicate some time for 3.1

**Comment by DmitryAlexei** [comment]
Please try the 4.6.9 release. 
Now, OsmAnd can easily work with big GPX tracks.
