### ISSUE TITLE
Distance wrong

### ISSUE THREAD

**Issue by Sixtron** [osmandapp/Osmand#3923]
I was driving yesterday 115 km by bicycle.
One way is 54 km plus 7 km around the lake.
When i arrived home it shows me 93,5km what is definitely wrong. 
On the way through the recorded track was splitted in two, on the way back in about 5-6 pieces, even splitting is disabled in my settings.
Wtf should i do with this splitted tracks ? I can not see approximately speed ect.
Then at home i saved the track and it shows me 112 km distance on the overview page and 106 km on the speed overview page. Screenshots attached.

![img_20170615_102249](https://user-images.githubusercontent.com/29046323/27173068-b3f9e5ca-51b7-11e7-8564-c5497732ba7b.jpg)
![img_20170615_102011](https://user-images.githubusercontent.com/29046323/27173090-c6c05f0e-51b7-11e7-9695-4f57c9bf6c37.jpg)
![img_20170615_102127](https://user-images.githubusercontent.com/29046323/27173137-e827ea22-51b7-11e7-8e35-d045e7a510f3.jpg)
![screenshot_2017-06-14-17-06-10-242_net osmand plus](https://user-images.githubusercontent.com/29046323/27173177-0507b6f4-51b8-11e7-8357-ad3499bb9b85.png)
![screenshot_2017-06-14-17-04-20-132_net osmand plus](https://user-images.githubusercontent.com/29046323/27173190-14bcf17c-51b8-11e7-9eb0-cef899567774.png)

**Comment by sonora** [comment]
The 112km is the total accumulated distance between ALL succeessive points recorded in the track, meaning that if you have a quick break or stand still at a red light, your position fix will still show some lateral fluctuation, which generally leads to too high distance values.

The 106km reported on the speed tab correct this by summing only over periods where the GPS chipset reports you are in motion. Und mosr circumstances this should normally be the more accurate distance (for the new release I have already renamed this to "Corrected distance").

Not sure about the value reported in the widget, would have to research. Chances are it does not report the total track distance but only that of the current segment (I think we auto-segment tracks under some circumstances). But that code portion is not authored by me, I'll leave this one for others to comment if there is a bug or not. :)

**Comment by Sixtron** [comment]
I have set the interval​ to detect a movement to 10m. So there should be no fluctuations.
Recordtime is set to 5 seconds.
My track based on a Google map track that i just have recreated like you can see on this photo.

![img_20170616_110013_hdr](https://user-images.githubusercontent.com/29046323/27220645-2d0bab32-5286-11e7-8efa-c1aefb67b2da.jpg)

It says 53,2 km.
Then i drove around the lake which took me 7km distance, but recorded only 6,2 km because whatever.

Measured track around the lake:
![screenshot_2017-06-16-11-12-05-450_net osmand plus](https://user-images.githubusercontent.com/29046323/27220843-cc4f7066-5286-11e7-977c-5104f0875a59.png)

Way through 53,2 km plus 6,2km plus way back 53.2km results overall
in 112,6km.

**Comment by sonora** [comment]
For any tests, I actually recommend to disable any of our now offered filtering. Filters can introduce artifacts, and for testing it is always better to look at data as "raw" as possible.

**Comment by Sixtron** [comment]
Google say's 112,6km. 106km don't looks right.

**Comment by Sixtron** [comment]
Even calculation from Osmand say's 53.5km for one way.

**Comment by sonora** [comment]
The track reports a time span of 7:28:54 (from 1:41PM to 9:10PM), and it reports only 6:19:24 of that time span as "in motion". So now you have to investigate why the remaining about 1 hour and 9 minutes where perceived as "not in motion". If you did not make a break, I can imagine there was some filtering going on which "destroyed" some of the data needed for a better analysis. Or your GPS unit did not report motion during that time period, for whatever reason (even tough your position shifted, this is 2 different things).

Iit is very hard to say more without having the track in hands. And even with the track, for such a long track, which was filtered at recording time, it would be rather tedious. Would be best you run some shorter test under defined circumstances, so you get a feeling for when issue occur, and what influences them...

**Comment by Sixtron** [comment]
I made pauses and stopped by traffic lights.

**Comment by sonora** [comment]
Let me reference this article http://osmand.net/features?id=trip-recording-plugin#Trip_Logging:_Some_Basics_on_Parameters_and_Filtering, not sure it helps much here, but it contains some basics about recording tracks.

Other than that, for the sake of this issue, I think I can only recommend that you
- clearly state what issue(s) you find, like with segmented tracks (and what the behavior you expect is), or which values you find may be off
- provide everything someone needs to analyze, re-produce, and debug this. This very likely includes your test track, information about the recording circumstances, and all settings and filters you have used during the recording. Please know that little can be done about something no one can analyze. :)

All this has not really made it to the surface in this issue between all the huge screenshots ... :) Maybe even start a fresh issue, or several, if you have several findings about
- unexpected track splits,
- analysis values you find not plausible,
- or obvious gaps you find in a recording ("only 6.2 of 7 km recorded").

**Comment by Sixtron** [comment]
Maybe you should ask for the information that you need to solve this problem and i can take a look if i can provide the information or not.
I am not a programmer for Osmand, i am a user of Osmand and i can tell you what is going wrong when i use Osmand.
Would be great if you try to fix the problem that is obviously there with the three different distances instead of telling me that i did wrong.
For other bugs of Osmand i wrote already 2-3 more issues.
One of this is that what you mentioned.

**Comment by sonora** [comment]
Please attach the track, and state all trip recording settings you had used.

**Comment by Sixtron** [comment]
Bicycle config, motion detection 10m, every 5 seconds. No more filters for recording tracks.

[Track driven and track planed.zip](https://github.com/osmandapp/Osmand/files/1082013/Track.driven.and.track.planed.zip)

**Comment by sonora** [comment]
Ok, lets take the issues 1 by 1:

**(1) Track segments:** Your track only contains one `<trkseg>`, so there should be no issue there. If there is one, please describe which, in a new Issue.

**(2) Total distance:** Let's do the math right: Looking at your google track: After you circled the lake, you joined it again for your return trip, but at the south-western corner of Halterner Stausee, about 1.7km before its end. So for your trip
 - the "Google distance" is 53.6km + 6.16km + (53.6km - 1.7km) = **111.66km**.
 - OsmAnd displays **112km**, so we are good here.

**(3) "Distance corrected":** Here is the problem: Your track contains a large number of gaps. Looks at e.g. your detail screenshot of Halterer Stausee above (the picture below your google screenshot), look at the stretch where you measured 6.16km: Your track cuts short around the entire eastern section of the lake, i.e. there were no points recorded there. When you look through the track, you will find hundreds of occurrences like this.

I enclose a screenshot how to make these visible in OsmAnd: You have to view the track on the "Analyze on Map" screen, then select the x-Axis as "time" (the gaps will of course not appear when plotted vs. distance), then pinch-zoom the graph a lot.

![untitled](https://user-images.githubusercontent.com/845735/27251219-f0bbb678-5342-11e7-8ddc-331a47c51267.png)


Gaps (where the orange speed curve vertically drops to zero, and the blue altitude is simply interpolated) can be found almost everywhere: Your track contains 2631 recorded points, while recording in 5 sec intervals over 7,5 hours should produce over 5000 points. On the map, you can see these gaps as straight segments, where obviously no points were recorded for quite some distance (comparing out and return trip makes is very obvious).

![untitled1](https://user-images.githubusercontent.com/845735/27251208-8fc6745c-5342-11e7-8d0f-6c589fcdce02.png)


Our "Distance corrected" analysis would see these sections as "fluctuations at rest", because the speed reported is zero there, hence the discrepancy you observed.

So I guess there is an issue with your recording device. Do you have a power saving feature active? How good is your GPS reception, do you maybe have some other hardware issue? I personally record many tracks like this, and have never seen such bad issues. I am convinced if you try another device, your issue would disappear.

Ok?

Best,
Hardy

**Comment by Sixtron** [comment]
To 3: There are a lot of trafficlights, side change of the street, pauses, bug removing from Osmand stops, stops for messaging with telegram etc.
I had this gaps.
The times when Osmand didn't continued recording overall and shorten the way by a direct line makes a difference from about +500m on the way back including​ the way that i drove to a wrong direction because Osmand didn't told me to go to the left or right. I had analyzed this too.

I am using Osmand since years and just last month i used it with Motorola Moto G Android 5.02, Huawai Honor 7 prime Android 5.1, now Xiaomi Redmi 4 prime Android 6.01 and i can sure you that this problems where i am talking from are on each device of them.
If not, i had seen this by myself and would comment that there is a problem with this device.

I have no power saving feature aktivated, instead set it to max. power.

My Gps reception is like on my two other phones.
Between you don't have reception. This is normal.

I don't have any hardware issue.

**Comment by Sixtron** [comment]
But there is maybe also a bug with the Gps reception that i comment here in another issue.

**Comment by Sixtron** [comment]
I found in MIUI 8 that there is an option to disable successive GPS detection for a specific app. This option was enabled for Osmand.
I found it by the battery options.
This is most likely the reason for missing gps signal.

**Comment by sonora** [comment]
Your file really contains a lot of gaps: The gap shortcutting across the east side of the lake alone is about 1.5km (as the crow flies. Would have been more if you recorded the way you went.). There is another gap in Hattingen between Kreisstrasse and Steinhagen, length almost 700m. It seems very plausible to me that this adds up to the overall 6 km gap between "Distance corrected"=106km and "Total distance"=112 km.

Please note that during those gaps nothing is recorded, so your speed appears as zero, and the "Distance corrected" routine suppresses this as a "fluctuation at rest". "Real breaks", on the other hand, like when standing at a stop light, cause no issues, because when you start moving again you are at the (almost) same position as when you stopped, so no error will be introduced.

Yes, it could be due to power saving. I have seen power savings features recently on some devices which cause GPS reception to be suppressed or entirely stop, I think I documented in #3556 , do not currently think we can fix this in OsmAnd. Looks like some devices try to save more power than is good for some background tasks .. :) :(

**Comment by Sixtron** [comment]
I will keep an eye on the distances by my next trips and report one day.

**Comment by vshcherb** [comment]
@sonora thanks for detailed investigation
