### ISSUE TITLE
[Feature Request] Add exit to on roundabout 

### ISSUE THREAD

**Issue by CarlosBrys** [osmandapp/Osmand#3972]
I would like the voice assistant to include the name of the street to exit a roundabout, 
eg: "take the x exit to street name".

And before the exit point say: "exit the roundabout now".

**Comment by OpenSourceForEver** [comment]
With TTS voice OSMAND says "take the x exit to street name". With pre-recorded voices it is not possible.

**Comment by polarbearing** [comment]
Turn street is in the TTS files, I checked [en] and [de]:
```roundabout(_Angle, Exit, Street) -- ['take.ogg', E, 'exit.ogg' | Sgen] :- nth(Exit, E), turn_street(Street, Sgen).```

If it does not work in your language, you can test the voice prompt (section 5.1-3 are roundabouts), and have a look into your language file [here](https://github.com/osmandapp/OsmAnd-resources/tree/master/voice).

As said above, naturally, a street name cannot be pre-recorded, in case you are not using TTS.

**Comment by sonora** [comment]
Can you please state what language you are using, and also specify the exact roundabout/exit where you observe this. I think I had once taken many hours to update all our voice files to support this, but I am happy to double-check if you give me some details. Thx!

**Comment by CarlosBrys** [comment]
Thanks  @polarbearing,

This string in the TTS file: 
_roundabout(_Angle, Exit, Street) -- ['take.ogg', E, 'exit.ogg' | Sgen] :- nth(Exit, E), turn_street(Street, Sgen)._
produces the following message:  "Take the # exit"

I expect to obtain like as this: "Take the # exit toward StreetName",  

as function here:
assemble_street_name(voice(['', Name, Dest], _), [C1, 'toward.ogg', Dest]) :- atom_concat(Name, ' ', C1). 

It is possible ?

**Comment by sonora** [comment]
Well, it is implemented. To test, please try this:

- In Settings / Plugins, please temporarily enable the Development Plugin.
- Then in Settings /  Development plugin, find the option "Test voice prompts", and tap it.
- Select language "en-tts".
 - Finally, tap the test button labeled (5.3). It produces exactly what you are asking for.

If it does not work for you in some or all non-test situations, as I said, please specify where this happens for you, and with what TTS language selected.  Most likely the issue is with the mapping of the roundabout(s) in OSM, not providing the street name of the exit, or not on the correct segment.

PS: Your request for an "Exit now" prompt in a roundabout is rather hard to fulfill, because roundabouts vary greatly in size, and any attempt to say something like "now" may result in ambiguous or false instructions: Both the time when a prompt sounds and the position of the device at that time, relativee to other nearby roundabout exits, simply carries too much uncertainty.

**Comment by sonora** [comment]
PS: Please double-check that under Settings / Navigation settings / Announce... you have not accidentally disabled "Street Names".

**Comment by CarlosBrys** [comment]
Dear @sonora  :
I did all the steps that you indicated to me, and it works perfectly.
I check and affirm that osmand is the best of all map navigators.
Thank you.
