### ISSUE TITLE
Make GPX analysis screen more obvious

### ISSUE THREAD

**Issue by njohnston** [osmandapp/OsmAnd#4039]
Yesterday I grabbed the latest code, built an APK and tested it in my emulator instance.

The GPX analysis improvements and fixes are good, but the screen is still not very obvious.

Now, the first set of stats and charts is an aggregation of all the segments in the track:

![gpx_screen_not_obvious](https://user-images.githubusercontent.com/638458/27874677-482568fa-61a8-11e7-8c1b-e8ee5f0a72ec.png)

This is much better, but it is not obvious that these stats and charts are for the whole track. Please add a "Whole track" or similar heading, and then please add a "Individual segments" / "Details" heading before showing the stats and charts for each segment. Hide the second heading if the track has only one segment.

**Comment by sonora** [comment]
Another small discoverability issue is how you get to this screen in the first place: If you are in your track list and tap on the 3-dots option menu for any track, you will see
- "Show on map", which is self-explanatory
- "Analyze on map", which does not lead to the screen you talk about above, but on the track context menu displayed on the map directly
- But the only way to get to this "Track analysis" screen talked about in this issue is to tap the track name directly, which is sort of undocumented.

I suggest to also add an option "Analyze track" to the 3-dots menu.

**Comment by esrat** [comment]
Thank you, very much, both of you!

Ever since I accidentally found this GPX analysis screen by opening a .gpx-file from another application in OsmAnd, I wanted to understand and find this view within OsmAnd itself. It was so hard!

I guess for other users this will also be the only way to find this view: Open an **external** .gpx-file with OsmAnd. This won't work with files within OsmAnd's own tracks-directory (bug?), you always have to copy the file into some other directory first, before you can use the "Open with" functionality of your file manager!
This was always very annoying to do, just to see more meta-data than OsmAnd would normally show up with.

But at least it worked as a workaround since I could not find out how to open the view otherwise. (Nobody I know of knew about this view. Without any titles / headings / labels my Internet searches did go nowhere.)
But lately I recorded a track which is kind of "broken". It resulted in two unconnected segments which I did not find or realised as a problem until now. - The only thing I found was that suddenly this view was showing not only one but three statistics parts!? Neither me nor my friend could explain why it would show some panel with a big number for the distance first, followed by a slightly lesser number and at the end a part with additional 2.something km.
I tried all the visible settings, on every part, but could not guess what this means. After hours of tinkering I gave up and thought it must have something to do with OsmAnd analysing the track (like: biggest number = complete sum of all recorded line segments; lesser number = sum of only the segments shown with a speed of > 0 km/h; smallest number = ???).
And I started searching the Internet again.

Today I found the phrase "GPX analysis screen" on some page and started to search for exactly that one. - So I finally came to this issue and was astonished to see that it has an age of over three years already and is still open!!!

I value this view as a great feature and find it sad that it is undiscoverable and incomprehensible to use.

Again, I want to thank you both. You’ve opened my eyes.
I hope that in future more users can find and use this fine analysis view.

**Comment by esrat** [comment]
Thank you, very much, both of you!

Ever since I accidentally found this GPX analysis screen by opening a .gpx-file from another application in OsmAnd, I wanted to understand and find this view within OsmAnd itself. It was so hard!

I guess for other users this will also be the only way to find this view: Open an **external** .gpx-file with OsmAnd. This won't work with files within OsmAnd's own tracks-directory (bug?), you always have to copy the file into some other directory first, before you can use the "Open with" functionality of your file manager!
This was always very annoying to do, just to see more meta-data than OsmAnd would normally show up with.

But at least it worked as a workaround since I could not find out how to open the view otherwise. (Nobody I know of knew about this view. Without any titles / headings / labels my Internet searches did go nowhere.)
But lately I recorded a track which is kind of "broken". It resulted in two unconnected segments which I did not find or realised as a problem until now. - The only thing I found was that suddenly this view was showing not only one but three statistics parts!? Neither me nor my friend could explain why it would show some panel with a big number for the distance first, followed by a slightly lesser number and at the end a part with additional 2.something km.
I tried all the visible settings, on every part, but could not guess what this means. After hours of tinkering I gave up and thought it must have something to do with OsmAnd analysing the track (like: biggest number = complete sum of all recorded line segments; lesser number = sum of only the segments shown with a speed of > 0 km/h; smallest number = ???).
And I started searching the Internet again.

Today I found the phrase "GPX analysis screen" on some page and started to search for exactly that one. - So I finally came to this issue and was astonished to see that it has an age of over three years already and is still open!!!

I value this view as a great feature and find it sad that it is undiscoverable and incomprehensible to use.

Again, I want to thank you both. You’ve opened my eyes.
I hope that in future more users can find and use this fine analysis view.

**Comment by dmpr0** [comment]
Track context menu updated long time ago.
