### ISSUE TITLE
Show 'Near city' information for all search results

### ISSUE THREAD

**Issue by littlehelper** [osmandapp/OsmAnd#4176]
Hi,
In the current version Osmand shows the information that a search result is located 'x.y km from [the nearest] city' for suburbs and hamlets only when searching for their names only.
1. This information is not shown when restricting the search to the POI category and explicitly searching for 'Suburb xy' or 'Hamlet xy' respectively.
2. This information sometimes might be useful for at least towns (in the surrounding of a well known city) too.

I guess that this kind of look-up mechanism determining the distance to the nearest city consumes computational power and therefore this information is not shown for each location and search result. If that is not the reason I would love to see this 'near city' information together with the 'is in' information proposed in #4174 for each location and search result. And then maybe the interests of #3327 coult be addressed too.

Greetings

**Comment by EvanCarroll** [comment]
This is not a good solution to this problem. The nearest City or Hamlet is basically impossible with the OSM data set. Sometimes you have two cities very close to each other. Sometimes you have two administrative zones _in side_ each other. Sometimes none of this is useful: for example, we have places technically inside the city of Porter which identify as "Kingwood" because it's nicer and more affluent. I live in Westbury but we have a sign that says Myerland at the entrance to the neighborhood for the same reason.

A better idea this would be imho to publish the "branch" name which is available in the OSM data. Every POI and chain you search for that has more than one location _should_ have the branch name filled out. Would this work for you @littlehelper? This could be done definitively and is addressed in 

https://github.com/osmandapp/OsmAnd/issues/6947

**Comment by vshcherb** [comment]
merged to https://github.com/osmandapp/OsmAnd/issues/2993
