### ISSUE TITLE
Traffic calming+ pedestrian crosswalking is not announced properly

### ISSUE THREAD

**Issue by OpenSourceForEver** [osmandapp/Osmand#4184]
When a POI is tagged with "highway=crossing" "crossing=uncontrolled" and "traffic_calming=hump" OSMAND shows properly pedestrian crosswalk and traffic calming alerts but TTS voice announces only  one of them.

Examples: 
https://www.openstreetmap.org/node/383461767
https://www.openstreetmap.org/node/3188827171

**Comment by sonora** [comment]
I can investigate, but I seem to remember this is on purpose: When several alarms occur at the same time we prioritize and only announce the one with the highest importance, rather than  spamming the driver with chattiness, and in many languages or situations even risking queued prompts sounding too late anyway.

**Comment by vshcherb** [comment]
Indeed it is on purpose
