### ISSUE TITLE
German TTS skipping latvian letters

### ISSUE THREAD

**Issue by Roxxor91** [osmandapp/OsmAnd#4257]
Hello!
I am using the newest F-Droid build of Osmand (also bought it on the Playstore just to support this great app!).
When reading, the German TTS simply skips latvian special letters: ē, ī, ū, ā.
Result for example: "Rīga" will be pronounced "Rga"; making many towns/street names unrecognizable.
I have Pico TTS activated. I tried another app, utilizing pico TTS, which is able to hand over these letters to Pico TTS, which pronounces them (in a german way obviously) mostly correctly.
So i guess the bug is that the german Osmand TTS plugin just doesn't hand them over to pico, as they are not German letters.

Thank you!

EDIT: Oh. I should not forget the capital letters! Here they are: Ē, Ī, Ū, Ā

**Comment by sonora** [comment]
I have no clue how to fix this ... it is not that we do this on purpose in any way, it may be an issue of the character set used ...

**Comment by hakuchi** [comment]
If I use Latvian TTS plugin the street names have also skipped letters.
There ar not only these letters. Latvian language have more [Link](http://www.webmaster-seo.com/unicode/language/var/lv/)
If I navigate into a road whit the name "Krišjāņa Barona iela", I hear only "Krija Barona iela"

For me this looks like a error into the TTS engine, because German Google TTS is able to reed this street names correct.

**Comment by sonora** [comment]
I think this is an issue of zhe TTS engine used, cannt be fixed in OsmAnd.
