### ISSUE TITLE
Feature request: Navigation mode for inflight tracking

### ISSUE THREAD

**Issue by 2-05** [osmandapp/Osmand#4391]
Not all flights have an on-board entertainment system with flight tracking options. With a few modifications OsmAnd could be an excellent tool for offline in-flight tracking of the planes route and for monitoring the remaining distance and time to the destination.

When sitting near a window it is possible to pick up a GPS signal while in-flight. This is also possible while the phone is in flight-mode as the phone is not sending any signal while using GPS.

Besides using OsmAnd for driving, cycling and walking, I also use OsmAnd to track the location and elevation of the plain and the distance to my destination while on flight. To calculate the distance I select a navigation mode (usually pedestrian), go to navigation settings and select the "Straight line" navigation service.

It would be nice if instead, OsmAnd would have a new navigation mode for in-flight usage, that uses the "straight line" navigation service as a default. This navigation mode can be adapted to calculated the estimated arrival time based on the current speed of the plane. 

This flight navigation mode can give a more accurate estimation of the arrival time and prevents having to switch back and forward between navigation services in deeper settings.

**Comment by sonora** [comment]
I think what you want is already implemented, just do this: Enable OsmAnd's development plugin, then in its settings go to Application profiles, activate the airplane profile, and then in Navigation settings configure it like you want. In this fashion you can chose this profile directly from the profile selection button on the map screen.

Please note that I believe that per current FAA regulations (and there are likely similar regulations in other countries) you may be breaking the law by operating GPS equipment on board of air carrier operated planes, because this is only legal for equipment the carrier has explicitly approved as "safe". Some carriers explicitly allow GPS receivers, while others do not, and there you may be in violation.

**Comment by 2-05** [comment]
Thank you for your comment. I did not notice that the airplane profile was already in the development plugin, but I found it using your instructions.

Thanks for your note on the use of GPS equipment on board. To be on the safe side I'll check it with the cabin attendant.
