### ISSUE TITLE
Hide advanced settings by introducing an expert mode

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/Osmand#4441]
New and less tech-savvy users are currently overwhelmed by the amount of (cool!) settings. How about introducing an expert mode so hat more advanced settings are initially hidden? This will make OsmAnd easier to use for newcomers but still offers the same flexibility for advanced users.

**Comment by sonora** [comment]
As a matter of fact, that is precisely what we are trying to achieve with our Plugin concept: Unless you need a Plugin and explicitly activate it, you will never see the related settings and options.

So along that line of though, what you are requesting is an additional plugin "Expert settings". I think this is a viable suggestion, but I am not really sure if there is enough common ground which of our remaining settings and options should generally be flagged as "expert". We would have to work out a list to be able to evaluate if there is a viable benefit.

In general, I am always big fan of "intelligent simplification" and rather strictly against avoidable settings, even if they can be hidden.

**Comment by scaidermern** [comment]
The plugin approach sounds reasonable.

I thought about advanced features such as "Details" and "Hide" which are probably only used by very few people. However a separate plugin for these two settings would be rather strange, I guess.

**Comment by vshcherb** [comment]
There are products on the market which have "expert" mode but they are in a minor group. Mostly we see: "advanced" settings & "quick user settings".
The problem of such settings is they are not grouped logically. And in that case it is hard to find for end user. 
I believe it is easy to everybody to have GPS Settings with 100 options, rather than GPS Settings with 10 options and 90 in advanced mode. Our biggest goal is not to make settings "easy" but to let person forget about settings completely. 
In case person needs setting I feel more comfortable to give full list of settings.

P.S. I'm not a big fan of a lot of settings by the other reason, they could easy go in conflict with different features and it is very hard to maintain big settings list (Advanced, expert, plugin doesn't solve maintenance problem).
