### ISSUE TITLE
Routing draws a straight line instead of using the road

### ISSUE THREAD

**Issue by PaulStets** [osmandapp/Osmand#4479]
Coordinates: from Lat. 28.34225 Lon. -16.92190 to Lat. 28.12106 Lon. -16.77033

Screenshots:
![screenshot_20170925-142525](https://user-images.githubusercontent.com/20681525/30806253-b5b014e8-a1fd-11e7-91f9-e308edc2e977.png)
![screenshot_20170925-142543](https://user-images.githubusercontent.com/20681525/30806254-b5b46f02-a1fd-11e7-9770-1457a725191d.png)

**Comment by vshcherb** [comment]
Possibly data is corrupted & disjoint, so map could be regenerated & checked

**Comment by PaulStets** [comment]
The issue is caused by this way: http://www.openstreetmap.org/way/430727210.

It says that the road is under construction, therefore OsmAnd ignores it.

**Comment by pwepwe973** [comment]
Hello

I just saw that this problem had not been solved.

On openstreetmap the calculation is done correctly with the attached image, but on osmand+ there is this calculation error where it asks to go through the hill at high altitude.

the problem is not due to the addition of a road in works on osmand as you can see on the image posted at the beginning of this subject I did not have any icon of works.

it's a bug on which they really have to look because he even wanted at that time to make me dive into a ravine

cordially

**Comment by vshcherb** [comment]
Yes the problem was back in 2021, so 4.2 release should provide fix for that.
