### ISSUE TITLE
Wrong street name shown in routing description (offline routing)

### ISSUE THREAD

**Issue by reald** [osmandapp/Osmand#4544]
Offline routing tells to turn left into "Thurn-und-Taxis-Straße". This is wrong. The street name to the left is "Bierweg", "Thurn-und-Taxis-Straße" is to the right. After entering "Bierweg" the correct streetname is shown very fast.

![bierweg](https://user-images.githubusercontent.com/1385404/31282994-8ae76328-aab4-11e7-850b-feb4e1466b76.png)

The intersection is here:
http://www.openstreetmap.org/#map=17/49.48942/11.12497

Route to reproduce: You can route from "Neumeyerstraße 24" to "Thuisbrunner Straße / Bierweg" in Nürnberg to reproduce the route. Disable "fastest route" because you will not be routed be default over this intersection. (But if you drive there it will also display the wrong streetname with fastest route setting.)

Version: osmand~ 2.7.5 on Android 7.1.2 (also seen with version 2.6.? a couple of month ago)
Offline map: Europe -> Germany -> Bavaria Standard Map 1.10.2017
Routing profile: Car

**Comment by scaidermern** [comment]
The part of the intersection _you will turn to_ is still called [Thurn-und-Taxis-Straße](https://www.openstreetmap.org/way/136482189#map=19/49.48924/11.12537):

![foo](https://user-images.githubusercontent.com/1040784/31285727-65e71908-aabc-11e7-89c9-75cede993573.png)

So OsmAnd's instructions seem to be correct.

I'm not sure if this is a mapping error. You could change the name of this intersection part from Thurn-und-Taxis-Straße to Bierweg (nice name, btw.). This will fix this particular issue. But then you will get wrong instructions when turning from Thurn-und-Taxis-Straße to Äußere Bayreuther Straße (coming from the east and turning downwards), because you would enter Bierweg for a few meters.

Is there any correct mapping approach for this?

**Comment by vshcherb** [comment]
I would say it is a mapping issue though it is not that obvious, but technically it is oneway and it could be only turn to Bierweg.

If you think how algorithm works, it takes just a next street name. In case you want to fix it differently you can of course use "destination" tag but that would be overkill may be
