### ISSUE TITLE
No turn indication when going into Y forking

### ISSUE THREAD

**Issue by bagage** [osmandapp/Osmand#4674]
What version of OsmAnd are you using, on what device and Android/iOS version? **Android 3.0.0**
Do you use the offline maps offered within the OsmAnd app for download, or online (tile / raster) maps? **Offline maps: France Rhones Alpes from 1st October 2017**

If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs, and its edition date.

__*In case of wrong routing:*__

Tell us whether you have used OsmAnd's in-app offline routing, or any online routing provider like YOURS, OpenRouteService or OSRM. **Using OsmAnd in-app offline routing**

What routing profile is choosen in OsmAnd app? (car, bike, pedestrian, fastest or shortest) **bike**

Please specify as exactly as possible the start and end point of your route by telling us city name and street name so that we can find it via in-app address search easily. Also a permalink from openstreetmap.org can be helpful. 
[Route URL](http://www.openstreetmap.org/directions?engine=graphhopper_car&route=45.11228%2C5.10833%3B45.10785%2C5.10512#map=17/45.11008/5.10668) from [point 1](http://www.openstreetmap.org/#map=17/45.11228/5.10833) to [point 2](http://www.openstreetmap.org/#map=17/45.10785/5.10512) 

Tell us your expected routing, and how OsmAnd routes, or add screenshots here.
![screenshot_1509484797](https://user-images.githubusercontent.com/1451988/32249537-ac4bd09c-be89-11e7-8f9b-5c387c651af7.png)

**When navigating with audio cues only, some crossroads are not supported and/or cues are misleading. This is one of them: when you arrive to the Y forking, OsmAnd do not tell you anything while they are 2 possible roads. 
Furthermore, the main/straight route (the right one) is the wrong one. 
Could it be possible in these scenarios that audio cues tell you "take the right fork" for instance?**

**Comment by bitboy85** [comment]
The behaviour of osmand depends heavily on how crossings are mapped. I agree that there exists a few cases where a [spoken] advice would be helpful while on the other Hand there are places where a spoken advice exists but is unnessesary.
For example at this place, there is always a "stay left" advice, (coming from North going to south) but there is no need to because you are already on the main road. https://www.openstreetmap.org/edit#map=19/49.91511/6.47284

At this place, there is no advice to take right lanes coming from south west and going to North on A 3
https://www.openstreetmap.org/edit#map=20/51.04084/7.00498

Another example. This place looks for a driver like an Y-junction because the straight road makes a slight left curve while the "Exit" lane is nearly straight through.
An advice to stay left would be helpful in this special case but osmand keeps silent which is correct because an announcement to stay left at every Exit would be too much.
https://www.openstreetmap.org/edit#map=18/50.76409/6.82117

It seems that on places where lanes are mapped seperatly (as line per each) an advice (take left|right) is given. But according to the osm documentation, this style of mapping is wrong because different lines should only be used where a road really splits, for lanes, there is a lane tag (http://wiki.openstreetmap.org/wiki/Lanes). But even this is not always true and the behaviour depends further on turn restrictions (which might be correct) or are wrong for some reasons. The last Thing i know is that it additionally depends on the fact if a segment is mapped as "link" or a road simply splits without having a "link" segment in between.

https://github.com/osmandapp/Osmand/issues/4336
There was an issue mentioning an additonal link Segment but i cannot find it right now.

**Comment by vshcherb** [comment]
Please send the link to roads to understand where it is missing indication. Like this 
https://www.openstreetmap.org/way/22614131#map=18/51.04129/7.00664
Use question button on openstreetmap.org.

Voice prompt is only available when 2 similar type of roads are connected i.e. 2 motorway or 2 motorway_link.

**Comment by vshcherb** [comment]
Original issue can't reproduce because the lanes information is present today.
```
Turn slightly left(+C|C)
```
Please wait December maps
