### ISSUE TITLE
Correct order on "destination" and "destination:ref" tags

### ISSUE THREAD

**Issue by OpenSourceForEver** [osmandapp/Osmand#4722]
OsmAnd 3.0.0#19090D offline maps(spain 1/10/2017) OsmAnd offline routing (car)

When you drive across a way with "destination" and "destination:ref" tags, Osmand don't order these two tags correctly. I think correct order should be for example: turn right toward "destination:ref1" "destination1" "destination:ref2" "destination2"...  
At this moment Osmand shows: turn right toward "destination:ref1" "destination:ref2" "destination1" "destination2"... but I think first option is more appropriate. This happens with text and TTS voice.

**Comment by bitboy85** [comment]
Well "correct order" is hard to realise because in reality there are many possible cases how ist written on a sign.

for Example:
Destination A, Ref A
Destination B, Ref B

But it could also look like this:
Destination A
Destination B
Ref A, Ref B

or like this
Destination A, Ref A, Ref C
Destination B

**Comment by sonora** [comment]
Yes, unfortunately I see no useful way to improve this because there there is no convention, so we will have to stay with the current order.

**Comment by scaidermern** [comment]
The OSM Wiki has several examples: https://wiki.openstreetmap.org/wiki/Proposed_features/Destination_details#Examples
You can see that it is not possible to match the destination values against destination:ref.

**Comment by OpenSourceForEver** [comment]
OK. Sorry and thanks
