### ISSUE TITLE
Issue: Misleading icon and selection in the "Map markers" list

### ISSUE THREAD

**Issue by SergeyP2** [osmandapp/Osmand#4760]
The icon that moves marker from the list of active markers into history looks like "check" icon. Also two top markers looks like being "selected". This two visual clues lead user to intuitive conclusion that "check" icon selects / deselects markers in the list, instead it moves it to history. This is annoying. I recommend to change icon to **"trash bin" icon**; also I recommend remove "selection" of two top rows – **all items should be just the same**.

![screenshot_2017-11-15-22-20-57](https://user-images.githubusercontent.com/22505250/32856534-c57877e4-ca4d-11e7-96bd-6650675e4208.png)

**Comment by vshcherb** [comment]
Marker mark as visited which moves to history but it doesn't delete it completely. The concept here is Quick Add - Quick Hide

**Comment by SergeyP2** [comment]
It is probably obvious for developer who programmed this feature for days, but not for ordinary user, especially for new one it is really misleading!

**Comment by vshcherb** [comment]
It is not a developer decision, first of all designer & product management. I think once you try you understand how it works. Also this icon is consistent in the context menu, it is explained as "Mark as visited"

**Comment by SergeyP2** [comment]
Yes, I understand your logic, yet the UI that needs to be understood isn't the best, UI should be intuitively clear from the first sight. For me this UI isn't a big problem, of course I now remember: 1) what this icon do, 2) the "selection" is not something that I can alter, 3) that "selection" and check icons are not related in any way. Do you see the problem? My intention was to give you insight how this icon together with "selection" looks like for the user who sees it for the first time -- misleading. But if you are sure that what you do is 100% right, OK, it is not a big deal for me, it's your product after all.

**Comment by vshcherb** [comment]
@SergeyP2 your input is always great. So I think nothing wrong if your opinion is different than mine and I'm not only to make decision, it is also UX-designer. If we see more complaints, it will be definitely addressed.

The only issue that we don't know yet the best solution yet, my point is to not display it as "Delete" (cross) because it has wrong semantic. 

Anyway thank you for your input, it is valuable even if it is not addressed immediately.

**Comment by sonora** [comment]
Victor, I am also struggling with the concept a bit, have been watching it for a while now: We call the "moved to history" map markers "Passed", but that is often misleading, because you may also just mark points on the map which may your never visit, then de-activate them when not needed any more. 

So I guess the concept should more be something like 
- active vs. deactivated, or
- active vs. deleted

I see fewer confusion with these expressions (and associated icons), but the concept of "Passed "together with the tick mark icon seems a bit surprising to many users, I would say...
