### ISSUE TITLE
'highway=cycleway' without 'segregated=yes' has higher priority

### ISSUE THREAD

**Issue by PaulStets** [osmandapp/Osmand#4798]
The path that has highway=cycleway+segregated=yes has a different priority than highway=cycleway. This causes unexpected detours.

Example: http://www.openstreetmap.org/directions?engine=mapzen_bicycle&route=51.51036%2C-0.07116%3B51.50985%2C-0.07535#map=19/51.51018/-0.07298

Screenshots:
![23848101_1944552302458241_1035356974_o](https://user-images.githubusercontent.com/20681525/33139422-ec355f10-cfb5-11e7-987f-4ec61b00e68b.png)
![23897049_1944549189125219_2033898614_o](https://user-images.githubusercontent.com/20681525/33139424-ec5a997e-cfb5-11e7-8118-b3a199d4b29b.png)

**Comment by maraf24** [comment]
These bicycle roads have questionable tagging.
The segregated=yes should be removed, as there is also foot=no tag - this is just ordinary cycleway.
cycleway=track also doesn't have much sense, this tag is for main road

>The path that has highway=cycleway+segregated=yes has a different priority than highway=cycleway. 

Why not? We use segregated=yes where the road is shared with pedestrians, but with seperated lanes, not roads. 
http://wiki.openstreetmap.org/wiki/Key:segregated

**Comment by tilusnet** [comment]
I agree that the segregated=yes tag is used with varying interpretation and that some of the tags marked there are redundant.

However the segregation exists, and as per tag definition is still correct since the bicycle track is segregated from the parallel footpath (i.e. is not shared).

As such, from the cycling routing algorithm's perspective that we are discussing, these segments should still have higher weights than non-segregated routes since these are not shared with any other traffic participant therefore they are faster and better for cycling.  

Looking at the map though it is strikingly wrong to recommend a twice as long detour over a stretch that has dedicated cycle lanes. It looks like as if the segregated=yes tag had introduced some sort of penalty over segments that are not segregated. That cannot be right.

**Comment by maraf24** [comment]
As wiki says: "This key is used for combined cycle- and footways. If both have their own lane, tag segregated=yes. If they share one lane, tag segregated=no. "
So this segregated=yes means one road with lanes for pedestrian and bicycle traffic. This is not for physical seperation. In that case, we draw separate lines with highway=footway and highway=cycleway.

The proper fix, without touching the tagging, is to check for foot=no or no foot tag at all and treat this as normal cycleway.

**Comment by tilusnet** [comment]
The way I see it it's rather simple:
{highway=cycleway + segregated=yes} should suffer no penalty with regards to {highway=cycleway + segregated=no} or {highway=cycleway} when routing for cycling; it should rather be rewarded! 

Segregation is a beneficial aspect for routing, be it a highway segment for pedestrians, cycling, or whatever. It doesn't matter whether the lanes are physically segregated or not; from the routing algo's perspective it's unimportant.

Therefore I don't think it is necessary (if not mistaken) to rely on the presence of foot=no/nothing since the segregation tag in tandem with highway=cycling alone contains the necessary information.

**Comment by PaulStets** [comment]
@tilusnet Yes, you are correct. segregated=yes should have the same priority as highway=cycleway. @maraf24 Unfortunately, many cycleways in the UK are tagged with segregated=yes in order not to draw a separate path for sidewalks. In this particular case the cycleway has also the tags: foot = yes, footway=sidewalk (http://www.openstreetmap.org/way/232178247), so your fix would not work. In any case, the bug in this particular case is not caused by the segregated=yes tag. The issue about this tag is #4461. 

This bug is caused by the high time penalties on the traffic signals in bicycle mode.

**Comment by tilusnet** [comment]
Interesting clarification @PaulStets, thanks.
Traffic light tagging is certainly not consistent in the area wrt traffic_signals:direction tags ─ and the suggested longer route is certainly missing a good few!
I will update the map.

**Comment by PaulStets** [comment]
Fixed with https://github.com/osmandapp/OsmAnd-resources/pull/475
