### ISSUE TITLE
Incorrect translation of the opening hours into Russian

### ISSUE THREAD

**Issue by PaulStets** [osmandapp/Osmand#4853]
The word 'off' is used to designate the day off instead of the Russian 'вых.'
![screenshot_2017-12-14-02-11-15-326](https://user-images.githubusercontent.com/20681525/34036553-3dfd0872-e18e-11e7-85a5-60bdc2ea7082.jpeg)

**Comment by pasharm** [comment]
Also the first letter of the day of the week to write with a capital letter.

**Comment by pasharm** [comment]
Need to correct weekday names:
"пн" on "Пн"
"вт" on "Вт"
"ср" on "Ср"
"чт" on "Чт"
"пт" on "Пт"
"сб" on "Сб"
"вс" on "Вс"

**Comment by PaulStets** [comment]
It will be corrected in the next update.
![screenshot_2018-01-23-21-26-53-446_net osmand plus](https://user-images.githubusercontent.com/20681525/35296335-6182d3c0-0084-11e8-9528-fb32e1aa6e27.png)

**Comment by homocomputeris** [comment]
@AlexSyt 
> Need to correct weekday names:
> "пн" on "Пн"
> "вт" on "Вт"
> "ср" on "Ср"
> "чт" on "Чт"
> "пт" on "Пт"
> "сб" on "Сб"
> "вс" on "Вс"

This change should be reverted because in Russian the names are not capitalized and should be used with periods:
[Грамота](http://new.gramota.ru/spravka/buro/search-answer?s=Пн.)
[Русский мир](https://russkiymir.ru/education2/services/ask/84123/)
[Бюро](https://bureau.ru/bb/soviet/20110526/)
