### ISSUE TITLE
Altcoins support for OsmAnd Live

### ISSUE THREAD

**Issue by hieu-van** [osmandapp/Osmand#4871]
Do you have any plans on supporting Bitcoin Cash or other altcoins for OsmAnd? Bitcoin seems to have suspended a lot of donations recently.

**Comment by jfburke3** [comment]
This sounds an awful lot like "how many global currencies will you support"?

**Comment by scaidermern** [comment]
Alternatively just discontinue supporting this waste of energy and environmental disaster. Maybe we can find a better solution for OsmAnd Live donations?

**Comment by vshcherb** [comment]
Yes, unfortunately we will need to stop supporting Bitcoin until Bitcoin fees will go lower to 20-30 satoshi per byte. We would like to add all possible cryptocurrencies support but that will require API changes on a 3rd party platform.
What's we could have implement pretty soon is only Litecoin. 

Anyway please consider to update to SegWit Bitcoin addresses as soon as possible, so redeeming the Bitcoins will be 4 times cheaper.

**Comment by scaidermern** [comment]
> Anyway please consider to update to SegWit Bitcoin addresses as soon as possible, so redeeming the Bitcoins will be 4 times cheaper.

I imagine most users not being aware of this fact. Consider sending a one-time notification to all users with a legacy bitcoin address.

**Comment by polarbearing** [comment]
And pointing to clear instructions what to do exactly.

**Comment by hieu-van** [comment]
> What's we could have implement pretty soon is only Litecoin.

Do you have an ETA on this? 😃

**Comment by hieu-van** [comment]
Maybe supporting Litecoin is a good idea. Bitcoin Cash is good but itself isn't as widespread as LTC 😕 I don't often see people using Ethereum or Dash for microtransactions.

**Comment by hapnait** [comment]
Should be many Altcoins that supported micro transaction as low fee or no-fee at all, just have to find it in cloud of thousand Altcoins 😵

I purpose to support Stellar, I think it would be perfect for you use-case as network is stable enough to use, easy to implement for dev and easy to use for user too

**Comment by erdmark** [comment]
You could use a micropayment system for cryptocurrencies. They are often used by faucets and support different currencies.
Coinpot.co for example has BTC, BCH, LTC, DOGE and DASH including an exchange beetween them so a user can decide which currency to withdraw. Osmand can pay to users from 1 Satoshi.

**Comment by vshcherb** [comment]
Now there is certainly going good picture with Bitcoin fees lowering and there are good news with Lightning network which allows to do tx without fees. The only issue with LN that having a channel with OsmAnd HUB will require OsmAnd to commit 3-6 months payouts to the channel to make it reasonable and better 12 months. Obviously we will need to fund with real Bitcoins. Another downside of LN transactions are not verifiable with Explorers

**Comment by hieu-van** [comment]
> Now there is certainly going good picture with Bitcoin fees lowering

It's still too expensive, at least for people in 3rd-world countries like me.

**Comment by vshcherb** [comment]
@hieu-van 
The situation starts changing at least as of today was possible to make transaction by 20 satoshi per byte meaning tx was 0.3-0.4$. Segwit transaction is usually 4 times cheaper by withdrawing, OsmAnd pays tx fee to send amount (50-100 bytes per output), but there is a withdrawal fee for each output 200 bytes, with Segwit address it is 0.1-0.2$. At OsmAnd site we plan to accumulate payments until they reach 5-10$, so in total tx fees will be lower than 5%. 

We prefer to do all transaction on change so it is easier to validate but it is hard to predict tx fee in Bitcoin.

**Comment by alexandrz** [comment]
Is it possible to update withdrawal address? I would set segwit bech32 address to make it cheaper. Also, it would be great to be able to set withdrawal threshold.

**Comment by james2432** [comment]
Personally Bitcoins for me is a better solution as I am currently paying for hosted services for an osm tasking manager through the bitcoins I receive from OsmAnd. They do not accept any other crypto currency.

**Comment by beatnickgr** [comment]
The future of cryptocurrency is uncertain, some might go up, some others down. Instead of OSMAnd making a bet and choosing which to use, let's give the choice to the donators and accept several currencies, Ether, Ripple, Bitcoin Cash.

Donators should be told to prefer an AltCoin because if they pay in BTC most of their donation is gonna be the fee itself.
Cartographers should be told to have wallets in AltCoins else they'll be unable to receive donations (which is already the case, if they don't have a bitcoin wallet).

**Comment by vshcherb** [comment]
Giving a choice of every crypto will delay the payouts & will keep busy an Osmand team for implementing it. 
Threshold is set by us to make sure (the rules are explained on the website), we are not paying enormous fees to deliver small amounts which anyway will be very expensive to withdraw.

As of today, it looks like the fees on Bitcoin are getting down, so it is possible that we will proceed with payouts in February. Also it looks we will rather spend time implementing Lightning Network rather than switching to another altcoin. I didn't try LN yet myself, though if somebody tries and can make a description how it works, that would be good

**Comment by beatnickgr** [comment]
Like every year, they're down in January and go up again after Chinese New Year.
But I'm not sure if it's a solution, to have payouts twice a year, February/August when bitcoin network is higher and fees are lower.

**Comment by lobit0** [comment]
> Consider sending a one-time notification to all users with a legacy bitcoin address.

I'm afraid that'd be all users. A friend of mine joined the list of recipients a month or so ago, and couldn't register using a segwit bech32 address. Form said it was an invalid bitcoin address.

> Is it possible to update withdrawal address?

Maybe it could be made to overwrite it, if you register using the same OSM nick name.

**Comment by hieu-van** [comment]
> Form said it was an invalid bitcoin address.

It seems that the (currently suspended) register platform only accept p2sh Segwit address. That's an unusual thing because mainstream wallets like Electrum have already used bech32 address instead of p2sh

**Comment by joelinf** [comment]
## Hi guys
I am a maper of osm for many years and also a cryptoactivist. Everyone is right up to a point, but nobody has considered two things.
Speed ​​and cost of transaction, and maintenance of the payment system.

I propose two alternatives

**Zero commission cost**s. I was recently speaking with David Stastebo, founder of IOTA, and he told me that the IOTA team would help the OSMAND team to implement the payment system to the contributors using IOTA.
IOTA is a currency that has no costs to transfer from one wallet to another, it does not have miners, and the transaction speed reaches 0.001ms. It has no associated miners, and each transaction is confirmed by another, which also needs to be confirmed. (Tangle) I confirm 2 transactions, and so someone confirms mine. Iota is scalable, and the more devices you use iota, the faster the speed increases.
![imagen](https://user-images.githubusercontent.com/29338249/36081323-3bab051e-0f6b-11e8-850e-abdf5b1f4e42.png)


Created to connect the "world" of the internet of things, in multiple fields.
They would be happy to help and contribute to improve management, and thus demonstrate that IOTA can be used in multiple fields. Presentation[http://bit.ly/2Cf7uGs](url) 
Wallet Iota Wallet, for linux, mac, windows, android


**GEOCOIN for cartography lovers**: geocoin is a minable coin launched in 2015, by GIS lovers, these last few months successfully managed to migrate under the Ubiq platform (based on ETH), it has a very good speed when confirming transfers, but it pays a commission to the miners. The wallet is Fusion, available for windows, linux, mac.

. Currently one of its services is geocoin cash, to "collect" money around the world (in the style of pokemon go), website whose map was made with mapbox (osm)
![imagen](https://user-images.githubusercontent.com/29338249/36081355-b4109d20-0f6b-11e8-90ab-e783bf73ddcf.png)
_**I want to know what you think about it. and we start working on an option that benefits us all.**_

**Comment by lokaman** [comment]
I digged a bit around in the crypto currency world, especially looking at the coins with the highest market caps - and would like to thank @joelinf for the suggestion of iota.

To me it seems to be relatively trustful coin for various reasons :relaxed:

I don't want go into detail here - please take this as recommendation to (critically) seek for information about iota. 

_Disclaimer: I don't hold any crypto currency. I spend my osmand live coins to a foundation. _

**Comment by hieu-van** [comment]
I, too, would love to have IOTA implemented

**Comment by beatnickgr** [comment]
Whatever currency we choose, it should be mainstream enough, so that donators have them already.
If we ask donations in IOTA, which has 1.2% market cap, probably donators won't have them.
I doubt donators would create a IOTA wallet, convert their BTC to IOTA, and donate to us, just because we told them so.
Let's choose a cryptocurrency > 4% market cap. (ETH, Ripple, BCH) If we're unable to take a decision now, let's just wait for a flippening (i predict 2018) and choose the winner.

**Comment by lokaman** [comment]
I disagree with you @beatnickgr. 

It should be a currency which fit the needs of osmand live.

+ no transaction fees (think worldwide, especially for contributers in developing countries like @hieu-van mentioned) 
+ fast transaction
+ scalability (think worldwide)
+  devs offered osmand help to implement this (which needs to be confirmed although I thrust @joelinf in this)
+ fixed sum of coins, which means that even the small payouts from osmand live are likely going to extend their value
+ run by a not for profit foundation registered in Germany
+ there are tons a firms and cities developing real world use cases based on iota

Indeed iota is not yet widely adopted by the market, this is not bad and likely going to change until more people decide to use it.

The average osm contributer have no crypto currency at all, which applies to me too (osmand live coins I receive are donated). The question arise for whom do we target here?

The 5% which already hold a crypto currency which doesn't fit for micropayments?

The 10% which are interested in crypto currency but don't hold any coin yet?

The 85% which wait for the real world mass market use case and don't hold any coin yet?

Development for the few people (probably 0,2%?) holding some coins seems to be bad priority to me. Instead we need a coins which fits the micropayments use case - to me, this is iota.

Instead of doing what everybody does, you should care about the real use of a coin. You are totally right if you mention it must be "mass market" coin that people own - however most people don't own any yet. So scalability of the coin is important. The scalability of iota is almost endless.

Disclaimer: I don't hold any crypto currency.

**Comment by beatnickgr** [comment]
- speed of transaction is not a relevant criteria. I don't mind receiving donations next day or even next week, as long as they arrive.
- "based in Germany" is not a relevant criteria. What's the problem if it's based in Catalunya or Kurdistan?

Why not the FairCoin, supporting micropayments, fixed number of coins (53M), and ALREADY used in several cities worldwide for real transactions (not just speculation), 0.0025€ transaction fee, supported by FairCoop (non profit). Market cap is 0.01%, and there is scalability, it went x24 in the last year. Several non profit organizations are already accepting FairCoins, if we send them a message they will probably implement it for us too.

I still support criteria #1 MAKE IT EASY FOR THE DONATOR
So I suggest allowing several currencies, so that the donator can choose in which currency they want to donate. Currently coins are distributed between the cartographers which have the corresponding wallet (BTC), and this will remain the same after we add the new cryptocurrencies, ETH, BCH, XRP, IOTA, FAIR, etc.

**Comment by lokaman** [comment]
@beatnickgr

You mentioned before that you even would wait half a year for payouts - again, please note that your needs are not the needs of everyone. Speed of transaction is relevant for costumers and merchants - and this is not going to change with crypto currency. Every pay solution tries to be as fast as possible - money "in between" does not generate value to anyone.

Of course it is relevant that the Iota Foundation is regulated in Germany & accepted by german law as non profit. German laws might be stricter as in Kurdistan, which isn't even a country yet (if kurds reading this: I have no knowledge & opinion in this. Don't feel offended.). Do you know a country with a better regulation & law system than Germany? What makes you think so? And if yes, is there a multi billion coin already registered as non-profit?

Is you suggestion of FairCoin even honestly?

I'm okay with thousands of options to donate as long as you help the osmand team to implement this.

Or we may just start collecting the donations from anywhere in the world. Any Currency is accepted. That would be EASY for the donators.

**Comment by beatnickgr** [comment]
The last donation I received from Osmand was 0.00019BTC (less than 1€),
that's why I mentioned I don't care accumulating the donations in a
single payout every half year.

Yes, I already work for FairCoins and spend them in a few places around
my city.
Speed of transaction is less than a minute.

The wallet app is open source (it's a fork of the BTC wallet). Developer
said that it's on the todo list to add it on F-Droid.

+ One extra criteria : Whatever currency we finally choose, I'd like to
have an open source wallet, so I can receive the coins somewhere.

**Comment by lokaman** [comment]
Okay.

So why would you prefer FairCoin over IOTA?

**Comment by beatnickgr** [comment]
1) Because I know there's places to spend them (I know nowhere to spend
IOTA).
2) Because there's a FairCoin open source wallet for my Android (I'm not
sure if there's one for IOTA).
3) Because I know people who might donate in FAIR, but nobody who might
donate in IOTA.

**Comment by lokaman** [comment]
1. In Germany there are 4 places to spend them. You probably live in Spain? The question is which coin iota or FairCoin is more widely accepted in the future? 
2. There's a os wallet for every coin I know. Atleast iota have one, but the plan release a more user friendly one in few weeks.
3. How many do you know? 5? 10? 20? Ask yourself - in the future, will there be more people who use FairCoin or Iota?

I understand you prefer FairCoin because you already use it.

In the future there will be only few payment options for crypto currencys - if they even exist. So scalability is important, media coverage is important, real world use cases are important. It is important whether people thrust the devs (which they will if the devs are regulated and committed to common good). It's important if devs have the money to extend and maintain the project - iota foundation has more funds than the market cap of FairCoin as far as I know. And these funds were donated by the Iota community. Guess that's a hole lot of thrust.

However thrust is nice - use cases are needed right now. That's why they are actively developed right know by companies (Bosch, Daimler and ~30 others) and few cities (atleast 4, want to use iota as part of the "smart city").

We will see when Iota gets mainstream. Personally - after endless hours of research about coins - I have no doubt in that it will.

And still I like FairCoin, however it seems to be poorly backed up with funds and I don't find any information where this organization is accepted as non-profit.

May the better coin "takes it all" :stuck_out_tongue_winking_eye:

**Comment by beatnickgr** [comment]
No, I don't live in Spain.
If you're correct, IOTA will do the flippenning, and if it does, let's
accept that coin for donations. "May the best coin take it all", that's
what I said few posts above.

**Comment by lokaman** [comment]
The problem is we need to develop a solution for the current problem now and not when you feel comfortable enough to follow the crowd.

If you are interested in finding a solution you may suggest a better coin. If it's FairCoin for you  then you may contact the dev and ask if he's willing to help.

What you said a few post above is ~ "I have no knowledge or opinion about altcoins, implement & accept them all, I will not help you".

After 2 months - in my opinion - we could focus on a solution.

If you could find something worse about iota / a better coin please share.

**Comment by jfburke3** [comment]
Right now, I'm visualizing @vshcherb slouched on his sofa, laptop next to him opened to this thread, 3 empty beer bottles on the table in front of him and a half-drunk one in his hand...sobbing a little.

**Comment by james2432** [comment]
@jfburke3 that seem like a cliche portrayal of a developer dont you think?

**Comment by joelinf** [comment]
**Hi guys,** 

Now let's consider the following:

**_Minimum wage_**
This is an example of the minimum wage that countries earn in these countries; most of the third world.
You can see the complete list in:_https://www.datosmacro.com/smi_
![imagen](https://user-images.githubusercontent.com/29338249/36401056-dc25e9f4-15a2-11e8-9e8c-821e0279397f.png)
In many of these countries, paying a commission of up to $ 5 dollars to send crypto, is  absurdity  in some countries is equivalent to food for a family of 4 people for 3 days And yes, there are people who live and map in those countries, its locations.

**scalability and pthers use**
 
consider for a moment IOTA :
In iota they have developed "my leaderboard" and flash channels to share IOTAS.
When you are two combine it is possible to include in the osmand app, the option to donate directly to OSMAND Live or to other users.

The first in order to quantify contributions (and even create smart contracts) and the second in order to streamline payments in certain circumstances.
[(https://learn.iota.org/tutorial/payments-and-messaging-leaderboard)]()
![imagen](https://user-images.githubusercontent.com/29338249/36401445-84fae9f6-15a5-11e8-8ab6-1ea3890149d8.png)

The latter could be used at the time of being in the field mapping when disasters occur, and volunteers require, for example, to buy travel plans, data plans, or any other need. (Even in the third world countries, ATM cryptocurrency ATMs, and payment processors are already available to convert from cryptos to fiat currency)

[https://blog.iota.org/instant-feeless-flash-channels-88572d9a4385]()
![imagen](https://user-images.githubusercontent.com/29338249/36401471-a638a072-15a5-11e8-990c-ba0434304ce3.png)


_> To think:, OSMF receives donations throughout the year, however OSMF has never donated anything to taxpayers; and just the community we are beginning to open the debate about the foundation, (you can read this article:)
> 
>   I  appreciate the work they do in OSMAND to help the mappers.

**Comment by hieu-van** [comment]
Guys, small update: 6-block fee is now 10 sat/byte

**Comment by hieu-van** [comment]
Bitcoin Cash gained some attention recently. IOTA is good but it isn't designed to be a currency. It's rather some kind of crypto-fuel for IoT network like Ethereum. Therefore, although I support implementing IOTA, I would stick with Bitcoin Cash.

**Comment by lokaman** [comment]
Bitcoin cash is the same as Bitcoin, and has the same design problems. I don't think it's usable for micropayments due high transaction fees. 

https://bitinfocharts.com/comparison/bitcoin%20cash-transactionfees.html

IOTA is much more reasonable for the project as @joelinf pointed out. And yeah, its just as usable as a currency, as any other coin.

The only downside to me - the more user friendly wallet is not released yet, but this is a matter of weeks.

IOTA ftw! :wink:

**Comment by mikeziri** [comment]
iota is full of bugs. read the recent MIT statements. it's going down sooner or later.
i propose opening Lightning Network channels and use BTC.

**Comment by lokaman** [comment]
That's interesting - i see many people, who already own other coins, arguing and spreading fear, uncertainty and doubt. As I follow this stuff with no financial interest (I own 20i for testing purposes, with a value of 0,00USD) its quite obvious that most of these claims are not solid.

https://blog.iota.org/official-statement-regarding-the-mit-dci-email-leaks-ea3cacd6699a

Regarding the latest MIT DCI stuff you may read the foundations perspective and look at these mails, which were published.

Have a nice day. 

@mikeziri

**Comment by vshcherb** [comment]
The payouts were done for all 3 months cause Bitcoin network fees went really down. The registration will be soon open again

**Comment by hieu-van** [comment]
> The payouts were done for all 3 months cause Bitcoin network fees went really down.

NOOOOOOOOOO I LOST THAT BITCOIN ADDRESS

---
Does that mean Bitcoin will still be used? Well that's good, but I suggest we migrate to Bitcoin Cash asap, because BCH tx fee is always low, not as volatile as that of Bitcoin tx.

IMHO only when true cryptocurrencies like Bitcoin or Bitcoin Cash can no longer be used should we consider to use those crypto-fuels as cryptocurrencies, e.g. Ethereum, IOTA or Ripple (as @joelinf and @lokaman suggested above).

**Comment by beatnickgr** [comment]
Instead of having the endless discussion if we should accept IOTA or
BCH, I say let's keep the current system and send payouts when the
transaction fees are low.
We'll change cryptocurrency when we have a flippening (i predict within
2018).

**Comment by lokaman** [comment]
im fine with that, although i still think with some technical stuff done and a big funding community using iota (or maybe a another good currency) there would be a HUGE (*trumps voice*) potential for mapping in poorly mapped countries with low income.

but this potential is still there, regardless if its done now or in the (very near?) future.

**Comment by BalooUriza** [comment]
I support the sticking with bitcoin.  I don't really want to have to figure
out how to spend some other new currency that isn't as widely accepted.
Better late than receiving a pump and dump toy.

**Comment by vshcherb** [comment]
Registration will be open soon, so you can update BTC address with Segwit. We have the formula mentionned on the website that we are sending payout only if tx-fee (on our side OsmAnd) don't exceed 10% of the payout itself. So in that sense OsmAnd reserves always 10% to proceed the payout itself. Of course it doesn't take into account the fees to withdraw bitcoin i.e. send to exchange etc. That fee could be lowered by using Segwit address.

**Comment by hieu-van** [comment]
As @vshcherb decided to continue using Bitcoin, I'm closing this.

**Comment by hieu-van** [comment]
@vshcherb Wait, will bech32 address be supported?

**Comment by hieu-van** [comment]
@vshcherb Has PayPal ever came up on your mind?

**Comment by beatnickgr** [comment]
@vshcherb 
I'm not sure if we can expect every OsmAnd contributor to have Segwit.
On the other hand, we can have 50% less fees if we accumulate 2 payments
in 1, which is a question of programming and will apply to ALL of us.

@hieu-van 
Did it ever came up to your mind that PayPal accepts no cryptocurrency, is only available in [these countries](https://www.paypal.com/gr/webapps/mpp/country-worldwide), and is not FOSS in the first place?

**Comment by hieu-van** [comment]
@beatnickgr Calm down, just a thought crossed my mind.
About SegWit, there are not many wallets out there that support SegWit. Another thing is that we still don't know whether @vshcherb will choose to implement bech32 or legacy SegWit address for his platform.

**Comment by bitcoinuser** [comment]
I opened an issue to osmand accept donations in bitcoin lightning payments: https://github.com/osmandapp/Osmand/issues/5248

**Comment by call-me-matt** [comment]
Do you realize that on your website there is still the comment "Important: Registration temporarily suspended. Read this article for more information." displayed on the recipients page? I think its time to remove that remark, right?

**Comment by vshcherb** [comment]
@call-me-matt Thanks corrected

**Comment by rugk** [comment]
Created a new issue for the native Segwit addresses: https://github.com/osmandapp/Osmand/issues/6302
