### ISSUE TITLE
"Store recorded tracks in monthly directories" may produce spurious deep nested subdirs

### ISSUE THREAD

**Issue by Self-Perfection** [osmandapp/Osmand#4895]
I believe the issue is perfectly described by following screenshot:

![screenshot_20180103_001_50](https://user-images.githubusercontent.com/3757038/34502534-ee7bc40a-f024-11e7-9509-01e562e8fe2d.png)

Somehow the track that I recorded on 2018-01-01 was placed in dir `Rec/2017-12/2017-12` hmmm... It's likely that the reason is that OsmAnd was launched in previous month or year relative to date when track was recorded.

Summoning @njohnston as the author with original PR #4012 with "Store recorded tracks in monthly directories" feature. BTW, thanks for this enhancement, makes my life easier.

**Comment by njohnston** [comment]
Thanks for reporting this. I noticed this behaviour once before but couldn't reproduce it.

There are actually two separate issues here, from what I can see.

### Nested subdirectories

I cannot yet reproduce this problem, and I don't understand how it can happen. The monthly directory is created (if required) in `saveDataToGpx()` in [SavingTrackHelper.java](https://github.com/osmandapp/Osmand/blob/master/OsmAnd/src/net/osmand/plus/activities/SavingTrackHelper.java#L191). It is based on the directory name passed into the method as the `dir` parameter.

Looking at the three call sites for `saveDataToGpx()`, it seems that the method is always called with `getTracksDir()` from [OsmAndAppCustomization.java](https://github.com/osmandapp/Osmand/blob/master/OsmAnd/src/net/osmand/plus/OsmAndAppCustomization.java). This trivial method just returns a constant:

https://github.com/osmandapp/Osmand/blob/3f437064c9430b3780787d7b7fb547a8c1f3c2fa/OsmAnd/src/net/osmand/plus/OsmAndAppCustomization.java#L109-L111

I'd appreciate help from @vshcherb or one of the other developers :)

### Filename date differs from subdirectory date

In the example, a track with 2018-01 in the filename is stored in the 2017-12 subdirectory (i.e. the directory for the previous month).

This is because the code uses the **UTC** time of the first point in the record track to determine the monthly subdirectory, but uses the **local** time of the first point to determine the filename.

@Self-Perfection: most likely your phone's time-zone is UTC+0300 I guess. Your screenshot shows that the local time of the first point in your record was track was 0154 on 1st January. In UTC this is still in December 2017. I can easily reproduce this using the Android emulator by setting the time-zone to any zone ahead of UTC, then setting the date and time to (say) 1st January 00:30, and then recording and saving a short track.

It's easy to fix this part of the issue: I will just use local time to determine the monthly directory.

**Comment by sisi-8** [comment]
Hello njohnston,

you mean directories, that I could browse with a filemanager? I am using an SD-Card on which all the osmand-stuff is in an osmand-directory. Could it be some stuff from older versions? Just keep the maps, languages, favorites, tracks and settings and delete all the rest for a new, clean setup? Where would be such a nested subdirectory? I can't see what you are talking about. I believe I don't have a monthly dir yet. Or if I had, where would it be?
Any Information you need for reproducing? There is no new log file, since there is no crash, just a hang up. 

Best regards,
sisi-8

**Comment by sisi-8** [comment]
Sorry, 
please ignore my reply. I thought we were talking about issue #4901
