### ISSUE TITLE
associate the app with .gpx files

### ISSUE THREAD

**Issue by imz** [osmandapp/Osmand#4913]
In which release is #2037 considered to be fixed? (So that it works as in said in <https://osmand.net/help/faq.html#importing_gpx>.)

I'm using 2.8.2~ , and a .gpx file can be opened through "My Files" on Android, but not through "File Manager" (from F-Droid) or WhatsApp (where such a file is sent).

Can you make something more to fix this?

(There are no tags corresponding to releases in this Git repo, so I cannot easily relate the fix mentioned above <https://github.com/osmandapp/Osmand/issues/2896> with a release.)

**Comment by vshcherb** [comment]
Most of intent are supported in released versions but obviously some could be missing. It might be a bug of "File Manager" itself.

**Comment by peteperil** [comment]
I have opened GPX files that I send to myself by email many times and never experienced any problems.

The problem could be related to Android handling file associations. For example opening a GPX file is associated with some other application, but you have already removed that application. Or that application simply expects the file to be another format and because of that ignores the call to open the file. (if it doesn't bother showing you an error message.)

Try to force Android to associate the file type with OsmAnd:
https://www.trishtech.com/2014/02/set-file-associations-in-android-devices/
or
https://www.howtogeek.com/howto/43135/how-to-change-the-default-application-for-android-tasks/
or
https://www.brighthub.com/mobile/google-android/articles/103415.aspx

Any one of the above could solve your problem. Just try and report back to us how it went.

**Comment by littlehelper** [comment]
I use FX file manager and it reports that Osmand does not support content URI (see https://groups.google.com/forum/m/#!topic/osmand/Ikx0fOpXeuk).

**Comment by crimean** [comment]
Fixed
