### ISSUE TITLE
Address from OSM nodes are not registered 

### ISSUE THREAD

**Issue by haadr** [osmandapp/Osmand#4947]
What version of OsmAnd are you using, on what device and Android/iOS version?
Osmand version: 2.82
Android version: 7.1 LineageOS

I have the following issue. Example: Finding a certain store.

I want to find a store called "Coop Mega" in an area called Bekkestua in Oslo.

1) Type "coop Bekkestua" into the search. 
2) Some of the first types of results that pop up are "Address" results, with the magnifying glass icon next to them. The first of those is actually precisely the address for the store I want (Coop Extra Bekkestua, 35, Gamle Ringeriksvei, Bekkestua, Bærum, Akershus, 1357, Norway).
3) I tap on that search result before waiting for the other results to populate, since that's the thing I'm interested in and I want to go there.
4) I get presented with "Nothing found :(" and I'm confused, since I just found exactly what I was looking for but it's not taking me to the map view centered on my search result, ready to press the navigate button. 

Now, in the end I figured out that in that "Nothing found" window I can still tap on "Show COOP EXTRA...." and it will bring me to the map view, centered on that address. However, that button is tiny and easily missable and since I was told "Nothing found", my first thought was just to assume that something had gone wrong. Instead, it seems the "Address" search results are somehow different. If I had waited a bit longer for the results to populate, I would actually have gotten the a POI search result for exactly that store instead of an "Address". Tapping on that gets me directly to the map. 

I've had this apparent problem of Osmand finding addresses but "still not finding them" for a while and just assumed that it was a problem of Osmand not being able to interpret the address returned by Nominatim (if that's where it comes from?). I never thought it was actually working as intended.

So I humbly propose this: When tapping on an address, that's where I want to go on the map, so instead of showing my "Nothing found", just take me there. 

Otherwise I'd be interested in the rational behind the current behaviour. Attached is a screenshot of the "Nothing found" search result screen that I find confusing. 

![screenshot_osmand](https://user-images.githubusercontent.com/16254070/35409264-f7d67cda-0211-11e8-88b0-1762719957ab.jpg)

**Comment by Codain** [comment]
@haadr I also had a hard time figuring how the search tool works and even today I avoid to use it because I never know if I use it right. The way I figured it is working can be very efficient, but I agree it can be a little bit modified for a big added value. Here is how I understand it... Please know that I'm not affiliated to OsmAnd team so everything I will say is based on my understanding and may be wrong.

The tool is searching from bigger to smaller concepts (like in a fractal). If you are looking for a shop/street A in a city B than you can either:

- Search for `A B` (`Coop Bekkestua`). In this case the engine will not know how to organize concepts (is it `Coop` in `Bekkestua` or `Bekkestua` in `Coop` or a feature named `Coop Bekkestua` ?)
- Search for `B` (`Bekkestua`), select it and then search for `A` (`Coop`) (which will be searched inside Bekkestua). When you will select Coop it will propose you to search inside Coop and so one... (imagine you are looking for an ATM or amenities inside Coop). This is very efficient in fact because the search engine knows better what you are looking for with this system.

Having said that, based from my understanding, your problem is that the search engine is proposing you what you are looking for (lucky you are!) but then it proposes you to refine your search by looking for something else in this feature. Which is sometimes anoying because you want the shop, not something inside the shop.

Imagine you are looking for `3200 2nd street Houston` then it is very efficient and handy to search for `Houston`, then `2nd Street` (I don't know if it exists...) and then `3200` (if the house numbers exist).

**Proposal to enhance the engine**
I agree with you that it would be better to:

1. Stop this fractal mechanism as soon as OsmAnd knows there is nothing more inside (instead of displaying a "Nothing found" message) and directly display the feature on the map
2. At any step differentiate between the need to get out of this mechanism and display the feature(s) on the map and the need to refine search (which is again the default action).

**Comment by haadr** [comment]
@Codain Thank you for commenting! I'm not entirely sure whether the search does always work in this fractal way, though I do know what you mean (especially with POIs). My guess is it simply searches all possible results for whether they contain the keywords from the search. 

I think the reason for why nothing further happens when you click an "Address" search result is that it's a hacky "empty" search result which simply pastes the address into the search field (see the screenshot). Instead, it might be good to elevate it to the status of a full search result with an immediately associated location. 

Then again, it's really hard to know how to address this without a dev and/or someone who knows the rationale behind this.

**Comment by vshcherb** [comment]
Points to check
https://nominatim.openstreetmap.org/details.php?place_id=23438936
https://www.openstreetmap.org/node/2260251097

**Comment by vshcherb** [comment]
The issue was fixed with new maps
