### ISSUE TITLE
Let OsmAnd handle Google map's plus codes

### ISSUE THREAD

**Issue by raindropsfromsky** [osmandapp/Osmand#4958]
Google maps is the leader app in the Navigation apps. In other words, a lot of users in the World use Google Maps.

Therefore there is a large possibility that a Google Maps user sends us the latlong coordinates of any spot, and expect us to find it.

And indeed, OsmAnd is able to handle the latlong coordinates copied from Google Maps.

But now Google has switched to Google map **plus codes**, which are easy to remember and enter manually. This is the opposite of embedding the address in a QR codes, which did not catch on.
In future, Google users are likely to catch up with this new feature and send us the plus codes only. 

It should be possible for the OsmAnd to handle these codes.

Even if this entails sending one-time query to Google server, it is worth it. The OSmAnd map still remains offline; and thus adds tremendous value.

**Comment by JonnyTech** [comment]
OsmAnd has supported plus codes for a while, I use them myself regularly.

**Comment by raindropsfromsky** [comment]
I don't get any result when I paste the plus codes in OsmAnd:

![image](https://user-images.githubusercontent.com/9047168/35474169-8b715eca-03b0-11e8-9d0e-ac4dd5b72c6f.png)

This is a working address and works in Google Maps.

**Comment by JonnyTech** [comment]
The correct term is Open Location Codes (OLC)(http://openlocationcode.com/).

To make it default in OsmAnd go to Settings >> General Settings >> Coordinate Format >> OLC

You can search map by clicking the search icon then by address then coordinate search.

Use a full 10 digit code such as 87G7MXQ4+M5 because shorter codes are local codes so it will give a different location for different people (see linked document above).

You can click anywhere on the map then swipe up and it will show you the code.

![screenshot_20180127-191753](https://user-images.githubusercontent.com/3584732/35475485-38554fa8-0397-11e8-9a10-4b1d8f03aeaf.png)

**Comment by barf** [comment]
I think this should be re-opened. The original question was asking for support for short OLC codes, only full OLCs are supported.

**Comment by tbnorth** [comment]
Searching / scrolling / zooming to the location (City name, state name) first, then searching for the short code works.  So we can use short codes. But agree with @barf, doing it in one step / pasted search term would be nice.
