### ISSUE TITLE
String format

### ISSUE THREAD

**Issue by EmrahNebiyev** [osmandapp/Osmand#4998]
Example string: Open from

At the end of this string is added time. But in some other languages, time must be at the beginning of the sentence. When I create a list of such strings, can you add variables (%s) to these strings?

**Comment by iriman** [comment]
In addition to what EmrahNebiyev said, there are some cases we should put the following text in new line due to readability of bidirectional texts. for example here:
Configure map > Hit on "GPX track..." (you should have no GPX there)
This screen will be shown:
![20180406_125916](https://user-images.githubusercontent.com/8467903/38418497-1d29b68a-398c-11e8-9792-34d77beb353f.jpg)

At the position shown on this screenshot we need to have a new line when the language of app is set to a RTL language because combination of the message(RTL) with the path(LTR) makes the path less readable:
![screenshot_20180406-124800](https://user-images.githubusercontent.com/8467903/38418587-9107d7ee-398c-11e8-9e93-8fb2c32bdef9.jpg)

Similarly there is a string on settings page of Trip recording plugin which I simply put a new line between LTR and RTL parts rather than I wrote all the text on the same line, and now it looks nice:
![20180406_155910](https://user-images.githubusercontent.com/8467903/38418913-cabc702a-398d-11e8-9349-ee950413e6c0.jpg)

**Comment by vshcherb** [comment]
Please create new issues for RTL incorrect display cause multiple places have been fixed already
