### ISSUE TITLE
OsmAnd Live lane guidance issue

### ISSUE THREAD

**Issue by jfburke3** [osmandapp/Osmand#5003]
What version of OsmAnd are you using, on what device and Android/iOS version?

OsmAnd nightly 2.9.0 #23745m dated 2018-02-04, Android 4.2.1, on Samsung Galaxy S4 (but can also produce on Android 7.0 on Samsung Galaxy S7).

Do you use the offline maps offered within the OsmAnd app for download, or online (tile / raster) maps?

OsmAnd offline maps.

If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs, and its edition date.

US Georgia map dated December 31, 2017, with OsmAnd Live enabled, and OsmAnd Live navigation integration enabled.

__*In case of wrong routing:*__

Tell us whether you have used OsmAnd's in-app offline routing, or any online routing provider like YOURS, OpenRouteService or OSRM.

OsmAnd's in-app offline routing

What routing profile is chosen in OsmAnd app? (car, bike, pedestrian, fastest or shortest)

Car profile, fastest.

Please specify as exactly as possible the start and end point of your route by telling us city name and street name so that we can find it via in-app address search easily. Also, a permalink from openstreetmap.org can be helpful.

On January 30 or 31 (can't remember, but early enough to be picked up in the monthly map update), I edited these two freeway sections to add lane guidance for the exit:

https://osm.org/go/ZSARMrMmN-?way=557129765  --  5 lanes, turn:lanes=through|through|through|through|slight_right
https://osm.org/go/ZSARMurq5?way=557129764  --  6 lanes, turn:lanes=through|through|through|through|slight_right|slight_right

OsmAnd Live picked up the changes and displays lane guidance as this:

![screenshot_2018-02-08-14-15-50_halfsize](https://user-images.githubusercontent.com/11140831/36047396-fa5576ac-0da9-11e8-8d59-2745e555fc03.png)

The "through" lanes appear to be shown twice, with no exit lane guidance.  Prior to my edit, the exit lanes were displayed as the usual "invented lanes" that OsmAnd displays for lane guidance when there are no turn:lanes directives.  I suppose that the problem could also be that OsmAnd is showing the 4 through lanes, plus its 2 "invented" lanes, plus the 2 lanes indicated by my turn:lanes edit.

After downloading the January 31, 2018 updated map file, lane guidance displays correctly, so the issue is definitely with OsmAnd Live map integration:

![screenshot_2018-02-09-10-14-43_halfsize](https://user-images.githubusercontent.com/11140831/36047552-72b6cde4-0daa-11e8-841d-83f6354f46df.png)

**Comment by hatzfeld** [comment]
I have observed the same problem. My system: OsmAnd+ 2.9.3 on Samsung Galaxy A3 (2017), Android 7.0, using OsmAn Offline Maps and Offline Routing with OsmAnd live, car profile, fastest route.

This is just one of the objects where this happens:
http://www.openstreetmap.org/way/265987206/history#map=16/50.8812/7.1917

As you can see in the history, the number of lanes has never been different from 3 (at least since 2014). Nevertheless the screenshot shows 6 lanes:

![screenshot_20180402-173648](https://user-images.githubusercontent.com/12374173/38203629-2442df76-36a0-11e8-87e8-547502656630.png)

The most annoying effect (for me) is that the voice navigation tells me to keep left (resp. right) when the routes switches between 3 yellow arrows on the left to 3 yellow arrows on the right.

**Comment by scaidermern** [comment]
I observed the same problems with OsmAnd Live on OsmAnd 2.9.3.

**Comment by scaidermern** [comment]
Looks like this issue isn't fixed completely. I didn't encounter it for several weeks but on Friday and today I saw it again:

![photo_2018-07-01_22-24-31](https://user-images.githubusercontent.com/1040784/42138425-8ec8461e-7d7d-11e8-915c-ddac22b29f9e.jpg)
Maybe this way? https://www.openstreetmap.org/way/233757915 But it has no recent edits.

![photo_2018-07-01_22-24-35](https://user-images.githubusercontent.com/1040784/42138424-8e9e5d36-7d7d-11e8-9997-38ba22a9798b.jpg)
Must be around this way: https://www.openstreetmap.org/way/12196831


OsmAnd+ 3.0.4
map: germany sachsen (saxony) from June
live data from 2018-06-22 16:59

**Comment by hatzfeld** [comment]
Today it happened to me on this way: https://www.openstreetmap.org/way/37386469

Using OsmAnd+ 3.0.4 with OsmAnd Live enabled
last Live update Germany Rheinland-Pfalz 14.07.2018, 23:28
last Live update Germany Hessen 16.07.2018, 07:18

**Comment by PaulStets** [comment]
@hatzfeld The road you mentioned wasn't edited for 9 months, so it can hardly be related to the issue with the live updates.

**Comment by scaidermern** [comment]
@PaulStets Maybe one of its adjacent ways or one of its nodes. See my last comment for a similar case where I couldn't find a promising candidate for my first screenshot.

**Comment by vshcherb** [comment]
Unfortunately we were not able reproduce with latest downloaded live data and the location @scaidermern sent to us. The issue indeed was present before and probably it was temporarily issue.

**Comment by vshcherb** [comment]
If you can reproduce please let us know. If you calculate a route and click arrows on the bottom you could see lanes details without navigation

**Comment by hatzfeld** [comment]
I just tried to calculate a route and found the issue discussed here on this way:
https://www.openstreetmap.org/way/603837352#map=17/51.15166/7.20876

The 6 lanes were shown a short distance before entering this way:
https://www.openstreetmap.org/way/10261301#map=18/51.15201/7.21039
(Both ways have been changed 10 days ago.)

My version: OsmAnd+ 3.0.4 with OsmAnd Live enabled
last map download Germany Nordrhein-Westfalen 01.07.2018
last Live update Germany Nordrhein-Westfalen 24.07.2018, 16:56

![screenshot_20180724-170338-preyersmuehle](https://user-images.githubusercontent.com/12374173/43150139-780924a4-8f69-11e8-9bc2-829fedd76a0e.jpg)

**Comment by vshcherb** [comment]
@hatzfeld We still can't reproduce... Can you please share your maps list in that area: 
 Germany Nordrhein-Westfalen, if you can show a screenshot of live maps (in live folder) you have that also could help.
So far we suspect that there are 2 maps overlay probably that's issue is not related to live at all. So you can disable Live and revert to original state. Though we are not sure, unfortunately trying to reproduce it on multiple devices and so far no luck

**Comment by hatzfeld** [comment]
My downloaded maps within Germany (Deutschland): Bayern, Baden-Württemberg (both 01.06.2018, probably irrelevant), Hessen, Nordrhein-Westfalen, Rheinland-Pfalz (each 01.07.2018)

![screenshot_20180725-162820_osmand_liveaktualisierungen](https://user-images.githubusercontent.com/12374173/43207498-8251c1f4-9028-11e8-89c0-e315b57284b8.png)

**Comment by scaidermern** [comment]
Interestingly I can't reproduce the example provided by @hatzfeld either. Looks like this issue depends on certain live update files and gets repaired by newer ones.

**Comment by vshcherb** [comment]
@hatzfeld The live maps are an overlay maps on top of the normal, in the folder osmlive, you can find which incremental files do you have:
To help http://download.osmand.net/aosmc/germany_nordrhein-westfalen_europe/ - this is all server files for this region.
  | Germany_nordrhein-westfalen_europe_18_07_00.obf.gz | 2018-07-25 00:00 | 9.6M |  
Represents all month changes for July 2018 (excluding last day)
  | Germany_nordrhein-westfalen_europe_18_07_01.obf.gz | 2018-07-02 01:50 | 566K |  
Represents only changes for 1st of July 2018 

On each devices combination of maps could be unique that's why I would kindly request to reveal that information from your device. This information is not visible in the app, so you need to use any file manager

Another kind request would be to try that issue without any live data (you can delete live data for the region in the app - disabling live update and later redownload it)

Thanks for cooperation.

**Comment by hatzfeld** [comment]
I followed your suggestion and disabled Live Updates for Nordrhein-Westfalen.
The corresponding files in .../live disappeared, and the issue disappeared, too.
Reenabling Live Updates for Nordrhein-Westfalen made appear these files:
 18.0M Jul 25 00:00 Germany_nordrhein-westfalen_europe_18_07_00.obf
  632K Jul 25 16:00 Germany_nordrhein-westfalen_europe_18_07_25.obf
but it did make reappear our issue.

**Comment by hatzfeld** [comment]
Today I have observed the issue again.

The first time when driving on https://www.openstreetmap.org/way/37386469 (but may be caused by a change to https://www.openstreetmap.org/way/34467886 28 days ago), where I saw 6 instead of 3 lanes. 

The second when I calculated a route (without actually driving) which passed the way https://www.openstreetmap.org/way/400065577 (changed by myself 28 days ago) and showed 8 instead of 4 lanes. This time I discovered that the occurrence of the issue depends (among other conditions?) very much on the exact place of the start point of the routing. In this case a change between a start point near https://www.openstreetmap.org/way/115304281 and another one near https://www.openstreetmap.org/way/286118010 made the difference, both far (about 20 km) away from the place where the error occurred. This explains why it is so hard to reproduce this error.

Nevertheless I suspect a relation to OsmAnd live. On a second device, where OsmAnd live is not activated, I have never ever seen this error.

**Comment by scaidermern** [comment]
> I think the issue is not related to original issue though the main issue actually
presence of this file Germany_nordrhein-westfalen_europe_18_06_00.obf.
> Once you have downloaded new July maps this file should have been disappeared.

I still have various 18_06_00.obf files in my live directory despite being in July now. Looks like they don't always get deleted. Maybe this has something to do with disabling maps and re-enabling them again alter? As far as I can see, after disabling a map the corresponding live files are still present and don't get deleted. This might be by design, though. However they should get deleted as soon as a new month starts or when newer map versions are downloaded.

**Comment by vshcherb** [comment]
@scaidermern , no it is not by design we are investigating still what causes it.

**Comment by InsertUser** [comment]
This bug seems to still be alive for some users. See description and screenshots in the recent [help.openstreetmap.org/questions/68182 ...](https://help.openstreetmap.org/questions/68182/troubles-with-counting-lanes-and-directions-on-osmand).

**Comment by julianladisch** [comment]
I had this bug with offline maps near the border of two neighboring map files. I opened Android/data/net.osmand.plus/files in the file manager app and found that I had two different versions for each region. After deleting all four map files in the file manager app and downloading the latest version for each region in osmand the bug disappeared.

**Comment by aceman444** [comment]
This still happens in this setup:
OsmAnd 3.3.8
Croatia map of 1.7.2019 + live updates
Plugin OsmAnd development enabled and "use live updates for routing" turned ON.

Happens when driving from on https://www.openstreetmap.org/way/228659657 onto https://www.openstreetmap.org/way/228659661 .
OsmAnd says "keep right" and displays to keep in the 2 rightmost lanes of 4 lanes.
Both roads only have 2 lanes (oneway) defined (I have now corrected them to lanes=3, but the bug happened before the change).

When the option "use live updates for routing" is turned OFF, the bug DOES NOT happen.

Yes, the second way 228659661 was modified on 2.7.2019 so the change is only visible with live updates. But the change only adds some nodes into the way and does not change any tags so it affecting the routing is strange.

**Comment by scaidermern** [comment]
I noticed something similar reported at https://github.com/osmandapp/Osmand/issues/7304#issuecomment-513725838
