### ISSUE TITLE
Parks rendered above water

### ISSUE THREAD

**Issue by treestryder** [osmandapp/Osmand#5005]
I am using OsmAnd+ 2.9.3 and offline maps. This particular problem has existed for some time.

It seems as though parks (leisure=park) are rendered above water (natural=water + water=river), yet beneath river ways (waterway=river).

I offer this example where the park boundary reaches out to include an island...

Location: geo:42.69594,-84.61494?z=17
https://osmand.net/go?lat=42.69594&lon=-84.61494&z=17

Here in standard OsmAnd mode, the river is seen cutting through the green boundary of the park and the island is not visible...
![screenshot_20180209-213033](https://user-images.githubusercontent.com/3682967/36058050-2bd8c364-0de6-11e8-98f3-3f41c5876397.png)

Where in nautical mode, the island and surrounding river are rendered properly...
![screenshot_20180209-213051](https://user-images.githubusercontent.com/3682967/36058048-27ee9e90-0de6-11e8-9b6e-cfe773f78b92.png)

I have also seen this in other locations. For instance, Adado Park, where a large river runs through the middle.
Location: geo:42.73955,-84.54907?z=17
https://osmand.net/go?lat=42.73955&lon=-84.54907&z=17

Thank you for OsmAnd!

**Comment by treestryder** [comment]
Much appreciated, thank you!

**Comment by IIVQ** [comment]
I still  have this issue on OsmAnd+3.7.2 2020-05-22 on Android.

This problem is visible in the Gaasperplaspark, where the [leisure=park](https://www.openstreetmap.org/way/336232404#map=16/52.3102/4.9937) intersects with the [multipoly natural=water](https://www.openstreetmap.org/relation/1429144). On the boundary between park and water, where they overlap, the park is rendered over the water in "world" mode.
In nautical mode the water is rendered correctly.
In bicycle mode, the park is drawn semitransparant.

Interestingly, this only happens where park and multipolygon-water intersect.
[This](https://www.openstreetmap.org/way/337152650) is part of the same water multipolygon and is entirely within the park, and is rendered correctly.

[This natural=water](https://www.openstreetmap.org/way/533600653) (single area, no MP) is intersecting with the leisure=park and is rendered correctly.

https://i.imgur.com/tlzmlpG.png : overlapping multipolygon and water in world mode
https://i.imgur.com/odjYVhA.png : same in bicycle mode
https://i.imgur.com/Ks84Ugv.png: bicycle mode: The large body of water at south is a multipolygon, together with the roundish lake at north. small lake is not drawn with leisure.mode, large lake is. 
Long water body next to Driemondsweg intersects with leisure=park (just around the "g" of the streetname) and is fully drawn correctly
