### ISSUE TITLE
Address search building=retail

### ISSUE THREAD

**Issue by OpenSourceForEver** [osmandapp/Osmand#5065]
There is a problem with some addresses (all of them on the same street): 
https://www.openstreetmap.org/node/3814262097#map=19/40.72861/-4.01563&layers=D
https://www.openstreetmap.org/way/304253055
https://www.openstreetmap.org/node/2585758852

I think addresses are properly taged (the same name on street and on POI'S) but it is strange because the problem is only on this street.

In any case it would be better if Osmand got addresses directly from tags of OSM (if they exist). Addresses could be shown on POI'S description (like phone) including postcode.

**Comment by vshcherb** [comment]
United States of America Virginia Apr. 30, 2018.

https://www.openstreetmap.org/way/144376874#map=19/38.89653/-77.10593

**Comment by vshcherb** [comment]
Though here the main issue that building is not registered in the address data at all, so it is impossible to search it by the housenumber, possibly it is related that it is building=retail.

**Comment by daviewales** [comment]
This may also be relevant to a problem I am having.
OsmAnd is not very helpful when searching for houses tagged with [addr:unit](
https://wiki.openstreetmap.org/wiki/Key:addr:unit).

For example, consider [this house](https://www.openstreetmap.org/way/647565384).
All the houses in this development have [addr:housenumber](https://wiki.openstreetmap.org/wiki/Key:addr)=150.
The only way to differentiate them is with their [addr:unit](
https://wiki.openstreetmap.org/wiki/Key:addr:unit) number.

However, OsmAnd shows *all* the houses as 150 Abbotsford Road, Picton, with no way to differentiate them.
I have checked the online OsmAnd map source, to make sure that it is not due to me having outdated maps, but the issue remains.

**Comment by vshcherb** [comment]
all original issues are correct now
