### ISSUE TITLE
[Feature request] Export / Import for settings and favorites

### ISSUE THREAD

**Issue by narcisgarcia** [osmandapp/OsmAnd#5067]
This issue parts from #1613 idea.
This feature should be as simple as normal applications do in a normal computer, as .gpx files can be used too. Useful to migrate from device to device, and to prepare 1 device and propagate customized Osmand profile to other devices.

+A particular situation today:
I'm currently using Osmand 2.8.2 from F-Droid.
I have whole device backups. I had a problem with new application installed, and no other solution than restoring a full device backup (system&data). Before doing this restoration I could backup broken system too.
Then: Last good backup has half of my Osmand favourites, and broken-system backup has a lot of favourites more. I explored backup folders and files but didn't find Osmand saved data. How can I replace current working profile with those complete files from Osman "old" data?

**Comment by spanezz** [comment]
I would also like to be able to automatically backup the information I enter into osmand, but in recent android versions an app cannot access the data files of another app, and that's fair enough. The only way to do a backup at the moment seems to be connecting the phone to the computer using a USB cable and using adb, which is something I only do every other month.
I would like to be able to, say, automatically export my content to somewhere where syncthing can read it, so that it gets automatically synced to my laptop, and then automatically backed up when my laptop does a backup run. This currently requires root.

@dmpr0 what do you mean turning on "Backup and Restore option" on my device? I'm not aware of an automatic backup and restore feature in stock android, but I do miss things every once in a while.

**Comment by gadamiak** [comment]
> @dmpr0 what do you mean turning on "Backup and Restore option" on my device? I'm not aware of an automatic backup and restore feature in stock android, but I do miss things every once in a while.

I guess @dmpr0 refers to app backup done to Google account. I haven't a chance to test it yet for OsmAnd but it happens to work for some other apps.

Anyway, it would be more than useful to have an option of exporting application setup (general settings, profiles, markers) i.e. everything which is not saved to files in `net.osmand/files` to external storage card and cloud services. I think this is more than nice to have and is offered by other apps.

**Comment by Discostu36** [comment]
This issue should get a higher priority.  Migration to another device has to be a lot easier. Or at least documented how to do it. Google Backup only transfers favorites. Tracks, notes, settings, profiles etc. are all missing. How do I get all of them onto my new device?

**Comment by narcisgarcia** [comment]
Not only for full backups or entire migrations but for sharing parts too.

Example 1: I can prepare a category with my 15 preferred parks, and I want to export them as a single file that Osmand can import at once.
Example 2: I can prepare my "perfect" navigation settings for one profile, and I want to share/save same way.

And please, it's important that backups and exports are not version-dependent.

**Comment by pebogufi** [comment]
@vshcherb The export / import functions should be ready now an work, or is something missing ? This issue is dated feb 2018.
Do you thing the issue can be closed ?

@narcisgarcia. Learning a new software needs some time which has to be invested. Trying out, testing exploring helps to learn and understand how it works.
Ex-1: In favourite groupes is a menu (three dots), there is a share function. Did you ever explore, what this share can perform ?
Ex-2: In config of profiles, did you have a look on the word "export" on this screen, and what the funtion can do for you ?
Invest time to explore the app !

**Comment by pebogufi** [comment]
... and it is a very profitable invest of time reading postings of other user before posting questions. 
Questions and answers of other users help me very much to learn new features and how to solve a LOT of tasks.

**Comment by narcisgarcia** [comment]
pebogufi is really right. I've upgraded Osmand adn: favourites can be exported per category, and settings can be exported per profile.
Export data can't be saved but it can be sent through another application (with the "Share" trigger).

**Comment by scaidermern** [comment]
Exporting and importing each profile separately is tedious, though. Would be nice to have a separate button for exporting & importing everything (all settings + maybe favorites, too).

**Comment by grravity** [comment]
I +1 this, I would love to see a **full** data export/import option, alongside our existing selective ones. It'd make re-installs and migrations so much less tedious.

**Comment by polarbearing** [comment]
Even the separate exports could be improved. Tried in today's nightly, and got confused with lots of unrelated apps to 'share' the export with. When using OsmAnd itself, eventually I found the export files in ```files/temp/*osf```

**Comment by rouelibre1** [comment]
The export feature is a great thing, I was happy to be able to export / import a profile, but with the "Include additional data" I feel the "Right panel" config is missing. Could it be added to this export feature ?

**Comment by vshcherb** [comment]
Full export / import is now possible with 3.9, so the general issue is implemented.

Right panel configuration should be part of Profile configuration (so these are profile dependent settings).
