### ISSUE TITLE
Tagging issue?

### ISSUE THREAD

**Issue by bitboy85** [osmandapp/Osmand#5132]
Hi,

please have a look at this route: https://www.openstreetmap.org/directions?engine=graphhopper_car&route=49.57074%2C6.11233%3B49.56844%2C6.10818#map=17/49.57063/6.10954

graphhopper is showing a wrong way (same as osmand), it is not possible for cars to take that route. OSRM Shows a correct route. I guess the access tagging is wrong. Maybe an experienced mapper can have a look at it.

**Comment by scaidermern** [comment]
For OSM bugs please use https://help.openstreetmap.org instead.

**Comment by scaidermern** [comment]
The [lift gate](https://www.openstreetmap.org/node/5064478459) could be the reason. It doesn't have proper access tags for (motor) vehicles. The [driveway](https://www.openstreetmap.org/way/116883195) has _access=destination_ (which is wrong and should be either vehicle=destination or motor_vehicle=destination, depending on the exact signs). So the lift gate should get this tag, too.

**Comment by bitboy85** [comment]
In some cases ist not easy to tell if it is a mapping issue or osmand handles the tagging wrong. Thats why i added the example that different routing engines provide different results.
i changed the tagging according to your advice and look at it again later.

**Comment by vshcherb** [comment]
I think the problem is here https://www.openstreetmap.org/node/1316610359.  It gives very big penalty so it takes a detour, I would suggest to  remove tag destination. 
Though it could sound strange but lift_gate already assumes that tag destination and currently routing engine gives that penalty double. 
Another solution would be to make another exit impassable with some exceptions.
