### ISSUE TITLE
Suggestions for icons in the information menu

### ISSUE THREAD

**Issue by franco999** [osmandapp/Osmand#5142]
First of all, I would like to clarify that I do not know the language to propose it with a Pull Request, but it would be good to add more specific icons in the information menu. Here are some suggestions I could come up with:
1. _Delivery:_ Something similar to this.
![delivery](https://user-images.githubusercontent.com/12088580/37678877-12ac63aa-2c5e-11e8-8eb9-c68f8b57ab47.jpg)

2. _Names:_ Everything related to a name, could have as icon the letters **"ABC"**.
 _Internet access fee:_ You could add the wifi icon along with a currency symbol **"$"** and if there is a fee for using it, cross it out.
![wifi](https://user-images.githubusercontent.com/12088580/37678884-1e291426-2c5e-11e8-95e1-6c46252ebdbb.jpg)

3. _Wikipedia:_ Add the letter **"W"** characteristic of Wikipedia and, if possible, replace the link with just the title of the article (you can also add a drop-down menu with the full link, as with opening_hours)
![wiki](https://user-images.githubusercontent.com/12088580/37678888-225e5d94-2c5e-11e8-876e-3ea7f42b900b.jpg)

If they could be implemented, that would be great.

**Comment by xmd5a2** [comment]
Delivery icons added https://github.com/osmandapp/OsmAnd-resources/commit/f882ed1ab036c8a5da149178dd6c627d954189ab

**Comment by franco999** [comment]
@xmd5a2 Great!
It also occurred to me to do something like this with the OSM link icon:
![osm icon](https://user-images.githubusercontent.com/12088580/37709332-a8f2de40-2ce8-11e8-8f06-476231685c48.jpg)
SVG of the proposed icon: [osm.svg.zip](https://github.com/osmandapp/Osmand/files/1833160/osm.svg.zip)

**Comment by IgorEliezer** [comment]
If I may:
* Names: I think the name icon ("ABC") is too generic. I suggest using something that resembles a sign (e.g. "nameplate icons": [google](https://www.google.com.br/search?q=nameplate+icon) or [these](https://thenounproject.com/search/?q=nameplate)). Perhaps alt and old name can get variants of that.
* Internet access - no fee: I would cross out only the $ sign, not the whole thing. That can be mistaken with "no internet" at all.
* Start and end dates and dates in general: a numberless calendar icon (e.g. [google](https://www.google.com.br/search?q=calendar+icon) or [these](https://thenounproject.com/search/?q=calendar)).
* Name of a person (artist, architect etc): a generic person icon :bust_in_silhouette:.
* Description and other data:
  - Instead of using the "text icon" :page_facing_up: for generic data, "Description" would use a cursive info icon (e.g. [OpenLevelUp](https://user-images.githubusercontent.com/4673289/38116087-f68fbef0-3384-11e8-8b8a-8bbcccf1d3db.png))
  - For all the other data (operator, number of rooms, capacity etc), use the current circled info icon :information_source:.

**Comment by IgorEliezer** [comment]
Can I suggest changing something that feels quite off? The `historic=memorial` objects (e.g. bust, plaque, obelisk) have a tombstone icon in the POI detail and show/hide POIs. It's weird to see a tombstone icon next to details about a commemorative plaque.

**Comment by xmd5a2** [comment]
Added "person" and "date" icons https://github.com/osmandapp/OsmAnd-resources/commit/19927e7ceea15263e990e10873b6b7335b7b730c

**Comment by franco999** [comment]
It seems that @dmpr0 added some new icons (https://github.com/osmandapp/Osmand/commit/9933c02a5d8c23ba59892b58012b15014b6e1ba1 , https://github.com/osmandapp/Osmand/commit/75ce79155ceeb1248e72aa48ccda5c75f7e718ff) but they are not reflected in the Nightly version.
![f](https://user-images.githubusercontent.com/12088580/40192953-2bbb8fe6-59dc-11e8-9214-243e0d741cab.jpg)

**Comment by dmpr0** [comment]
@franco999 Yes, i added few new icons for request, we add them soon, this task is on the list.

**Comment by IgorEliezer** [comment]
Please dismiss this reply if aware of the following:
* Architect: needs an "Architect" label, otherwise it's hard to guess what the name is supposed to mean.
* Artist: still missing the person icon.
* Start date: I'm undecided on this one. Without a "Start date" label, it can be confused with end date or something else.
  * Localized version: the date is interpreted as telephone number.

![screenshot_2018-05-26-20-07-06](https://user-images.githubusercontent.com/4673289/40580913-a7afbe24-6120-11e8-8123-dc4a7c6729c2.png)
![screenshot_2018-05-25-15-44-33](https://user-images.githubusercontent.com/4673289/40580914-a7d183a6-6120-11e8-8012-673558ea41b9.png)

Nightly 21317d

**Comment by vshcherb** [comment]
This issue might be outdated please open separate issue
