### ISSUE TITLE
Facebook analytics

### ISSUE THREAD

**Issue by littlehelper** [osmandapp/Osmand#5155]
Hi,
Some recent commits are named "Facebook analytics". I assume that these are related to https://analytics.facebook.com
Will the Osmand app send data to Facebook in future? What kind of data? Position related data?
What will be the benefit for the users?
thanks

**Comment by naoliv** [comment]
This is a bit worrisome, especially by the recent news related to Facebook.

**Comment by vshcherb** [comment]
First of all, it should be clear that OsmAnd+ doesn't have any SDK library at all.
Facebook analytics library is used by more than 2/3 of Google Play apps especially non-open-source.  There is no need to hide the fact that OsmAndFree is using cause it is always possible to inject it just before publishing to Google Play.

We prefer to be clear about the decisions we make and explain it. Facebook Library serves solely marketing purposes of Ads & Interests. There is no company in the world that knows more than Facebook though most of information was provided by people on FB site. If user has an installation of FB messenger or FB app, this will allow our team to understand which area of interests people are focused on FB.

Because this is a pure marketing purpose it will be only related to Free version. In case we make mistake and it can't be turn off, please let us know.

**Comment by noci2012** [comment]
So if some jump into icy water it is custom to jump in as well?

Are you aware of GDPR? With FB integration you are purposely collecting personal data,
so a clear consent is needed, not a waiver like before. Also a description what you collect and why en how you will use it. (Detailed, not vague like we collect some data and use it.. you accept by clicking OK).
Now Facebook is caught with it's pants down,  but you as controller are responsible, are you willing to pay up a minimum of EUR 1M in fines if the shit hits the fan? I'd consider FB services a liability in stead of a bonus. (Or is there a contract about FB paying up for damages?).

Ireland has some readable (in english) documents, 
Main Site
http://gdprandyou.ie/

GDPR document
https://www.dataprotection.ie/docimages/documents/The%20GDPR%20and%20You.pdf

More formal information online
https://www.dataprotection.ie/docs/GDPR/1623.htm

my opinion:
I have NO FB whatsoever anywhere, an no intention to become an FB member anytime. Although i have no doubt they have collected info on me because of al the FB beacons everywhere.
I started to deinstall apps that require FB or even secretly try to.  (I will notice it sometime sooner or later).  Imho it must not be in the payd version, and should not be anyway.

**Comment by vshcherb** [comment]
We did some investigation in between to confirm what's going on: 
1. The biggest data collector is the phone owner in case Android - Google, IPhone - Apple. Only they could provide the most advanced statistics which is not possible to get from the application itself. Google is collecting it via Google Play services
2. Second if there was no user information leaks from Apple, Google it doesn't mean, it won't happen in future
3. Most important point to Facebook Analytics plugin, if you are not using Facebook application on mobile (the browser doesn't count), the app won't be able to get/give any information about it. There is no possibility today that Facebook plugin will be collecting something which is not provided from OsmAnd code itself. As today there are only 3 events published: install, uninstall, app started.

--------------------------

Again this is only related for non-paid users which prefer to use free application and they are most likely the users of FB anyway. If we notice some personal information is possibly leaking, this plugin will be disabled.

**Comment by franco999** [comment]
@vshcherb How would this addition of Facebook Analytics code in the F-Droid store and the like (if at all) affect to the app?

https://f-droid.org/wiki/page/net.osmand.plus (Antifeature)

**Comment by vshcherb** [comment]
Paid app and F-Droid app doesn't have any analytics included. If you build yourself, you can double check that.

**Comment by ciconi** [comment]
If anyone is interested: I checked the latest ~osmand app with [exodus standalone ](https://github.com/Exodus-Privacy/exodus-standalone)on f-droid and there is no facebook tracker included :-)

=== Information
- APK path: net.osmand.plus_316.apk
- APK sum: d87435ae445c46e8e1dcc6a777fcee6d3276f2b7716c6e15539d9dadf668e1f5
- App version: 3.1.6
- App version code: 316
- App UID: 06B53889943FAFC82C76BCE94164AEB3E942F95A
- App name: OsmAnd~
- App package: net.osmand.plus
- App permissions: 15
    - android.permission.ACCESS_COARSE_LOCATION
    - android.permission.ACCESS_FINE_LOCATION
    - android.permission.ACCESS_LOCATION_EXTRA_COMMANDS
    - android.permission.INTERNET
    - android.permission.WRITE_EXTERNAL_STORAGE
    - android.permission.STORAGE
    - android.permission.ACCESS_NETWORK_STATE
    - android.permission.ACCESS_WIFI_STATE
    - android.permission.WAKE_LOCK
    - android.permission.CAMERA
    - android.permission.VIBRATE
    - android.permission.RECORD_AUDIO
    - android.permission.MODIFY_AUDIO_SETTINGS
    - android.permission.BROADCAST_STICKY
    - android.permission.BLUETOOTH
- App libraries:
- Certificates: 1
    - Issuer: countryName=UK, stateOrProvinceName=ORG, localityName=ORG, organizationName=fdroid.org, organizationalUnitName=FDroid, commonName=FDroid 
Subject: countryName=UK, stateOrProvinceName=ORG, localityName=ORG, organizationName=fdroid.org, organizationalUnitName=FDroid, commonName=FDroid 
Fingerprint: ad4edf28b5e062353678691aa308b3f5be4eb263 
Serial: 1308863683
=== Found trackers: 0
