### ISSUE TITLE
Routing bug caused by height restriction penalties (motorway exit and than next acces back to the motorway)

### ISSUE THREAD

**Issue by Norbert80** [osmandapp/Osmand#5170]
Hello,

below you find a screenshot where you can see that OsmAnd takes the motorway exit and than the next access back to the motorway.

I couln't find any map data issue. Other OSM routing services including MAPS.ME, Magic Earth, MapFactor and OSRM are calculating correct.

OSRM link:
https://www.openstreetmap.org/directions?engine=osrm_car&route=48.07442%2C11.09380%3B48.07539%2C11.10492#map=17/48.07482/11.09942

![osmand](https://user-images.githubusercontent.com/6921696/37956147-cf972f58-31aa-11e8-949d-dc202246c773.jpg)

Found with:
OsmAnd+ 2.9.3

**Comment by Zahnstocher** [comment]
Do we really need a penalty for height restrictor?
It should have maxheight already.
It is like passing under a bridge, which also does not have a penalty, only maxheight.

https://www.openstreetmap.org/node/2733546066#map=19/48.07528/11.10064

 `<select value="100" t="barrier" v="height_restrictor"/>`
https://github.com/osmandapp/OsmAnd-resources/blob/542c33d860c658a81f4c56b81a8a3b4b85308ad8/routing/routing.xml#L480

**Comment by aceman444** [comment]
Some height restrictors may not have a height specified (in OSM) or in reality. The height may not be signposted on the device so the driver may know know immediatelly what the height is and if he passes. So he may need to slow down radically.

Also, I'd think height restrictors are mostly placed in tight areas (underground parkings, shopping centre lanes and parking places, etc), not on motorways. Is there a real height restrictor on that spot? Or is it bad tagging and a plain maxheight= would suffice (on the way, not node)?

**Comment by Norbert80** [comment]
I don't remember such details. Sorry. But I know that OsmAnd is the only (OSM based) routing service that has this issue.

**Comment by Zahnstocher** [comment]
Warning 1700m ahead:
https://www.mapillary.com/map/im/Iu2mZGcDI7_raiV597IRRg

This is the height restrictor:
https://www.mapillary.com/map/im/3NiOjGwgnyJMk6W2wh3sWQ

**Comment by Norbert80** [comment]
Cool. I didn't know Mapillary.

So the question remains why OsmAnd calculates penalties for a 4.3m height restriction in car navigation mode.

**Comment by Zahnstocher** [comment]
> I didn't know Mapillary.

Mapillary images are also available in OsmAnd. :-)
Configure map -> Mapillary

**Comment by Zahnstocher** [comment]
> Is it correctly mapped?

In this case, it is on the wrong position (maybe 50m behind?).
But the question remains.

**Comment by Norbert80** [comment]
Thanks. The exact position should nit matter in this case.

I see the problem in OsmAnd approach to calculate penalties for height restrictions. Height restrictions don't slow down.

Can we eliminate these penalties by XML modification only? Are there any scenarios known/expected where it could lead to regressions?

**Comment by aceman444** [comment]
Thanks for the images. This device is an interesting height restrictor, but I can't say it isn't one. It may have been built for the purpose of limiting height, in contrast to e.g. a bridge which is also a height restrictor, but as an "unwanted" sideeffect.

You can't remove the height_restrictor from routing.xml (as it would make the node totally impassable for a car), but you can change the penalty to 0 (or maybe 1 as the driver could slow down to check the number sign :))

**Comment by Norbert80** [comment]
Would a penalty of 0 be a considerable fix?

**Comment by aceman444** [comment]
It is documented at the top of the file to be in seconds.

**Comment by Norbert80** [comment]
Thanks. How can we proceed with this issue?

**Comment by vshcherb** [comment]
The issue has only 1 way to be fixed, we need to justify whether the 
height_restrictor penalty should be dropped. Unfortunately it is not clear whether using "barrier" in this case was legitimate or not i.e. somebody put a penalty in first place, so in case to drop it somebody need to observe other height_restrictor in OSM.

**Comment by vshcherb** [comment]
Fixed https://github.com/osmandapp/OsmAnd-resources/commit/9d04b691a59dbc1e0943842c819afc1ea56d9da7

**Comment by aceman444** [comment]
The fix is wrong, if you wanted to remove the nepalty, you should have made it "0". Now height_restrictors will be totally avoided as being an unknown barrier not passable to car (see issue #6530).

**Comment by Zahnstocher** [comment]
@aceman444 
Unknown barriers are passable by default in car mode, but for "shortest way", the default is "not passable".

**Comment by aceman444** [comment]
No, unknown barriers are specifically NOT passable. There are many known barrier values that are known not passable by car and they are not listed in OsmAnd's routing.xml as not passable, because there is a catch-all rule to forbid any unlisted barriers. Also see https://wiki.openstreetmap.org/wiki/Barriers#Routing .

Why would there be a difference in barriers for the 'shortest way'? If you choose 'shortest' you suddenly can pass some obstacles?

Yes, there is a difference now, because the catch-all rule was wronly removed in issue #6530.
I now fix it all in pull request 545 (https://github.com/osmandapp/OsmAnd-resources/pull/545).

**Comment by scaidermern** [comment]
> No, unknown barriers are specifically NOT passable

Exactly.

There are very few barriers with implicit access values which allow car routing. Almost all barriers prevent access if not otherwise specified, with a few exceptions for foot and bicycles (bollards, bicycle barriers, lift gate, stile and so on). However all of them disallow car routing if not overridden by additional access tags.

Also see https://wiki.openstreetmap.org/wiki/Barriers#Routing which suggests:

> Barriers with undocumented default access imply access=no. This default restriction prevents softwares from routing through undocumented barriers (and generating a potentially unsafe route).

**Comment by vshcherb** [comment]
I think we are definitely not going to imply "access=no" for a broad list of values even if documentation assumes it.
The changes to documentation could be done in several weeks but the changes in the app could be done only in several months.

So in that case we can only substitute non-listed values in the map itself while building the map. We support that mechanism here https://github.com/osmandapp/OsmAnd-resources/blob/master/obf_creation/rendering_types.xml and I will be open for suggestions.

For sure the changes done in a routing.xml by different people lead to these annoying issue and it took me a while to understand the whole story. In order to avoid these problems in future, I suggest to only white list tag/value and definitely not hide behind generic tag.

**Comment by aceman444** [comment]
Victor, I'm not sure you understand the issue here and my patch in https://github.com/osmandapp/OsmAnd-resources/pull/545 .

And I'm not understand what you are saying. Which lines in https://github.com/osmandapp/OsmAnd-resources/blob/master/obf_creation/rendering_types.xml are the barrier whitelist for routing? Also, why would you make a whitelist when creating obf file and prevent the user from adding his own choices of barriers in the routing.xml file?

So which line in https://github.com/osmandapp/OsmAnd-resources/blob/master/obf_creation/rendering_types.xml will now prevent OsmAnd from routing a car by default through barrier=bollard, gate, turnstile, bus_trap, block? Tell us exactly.

**Comment by vshcherb** [comment]
barrier=bollard, gate, turnstile, bus_trap, block - I guess there is no such line yet and we need to add it to routing.xml

**Comment by vshcherb** [comment]
Added https://github.com/osmandapp/OsmAnd-resources/commit/b333adec120bcb38b216c02ce6f4ff2e806f2d51

**Comment by aceman444** [comment]
And what about 10 other values, that I haven't mentioned? And what about the million other values that users around the world have added to OSM?

NO, anything unknown is NOT passable! It is a BARRIER after all! Only a very few carefully whitelisted ones can be passed by a car.

You accepted the PR with the concept of <select value="-1" t="barrier"/> and whitelist in the past (I was the author). Why are you now deciding completely backwards?

**Comment by vshcherb** [comment]
@aceman444 disagree, while fixing bugs I think it was a mistake. 
Technically it doesn't change anything except the way we should approach the issue. I believe not making a proper route is more critical (in case barrier passable) than making route (in case barrier is impassable). 

It is subjective obviously but I believe it will cause less issues in real scenarios

**Comment by aceman444** [comment]
I think that is not true. Avoiding an unknown barrier and making a possibly longer route is no problem, user will get to the destination (unless that was the only access road). But arriving at a barrier that the navigation thinks is passable, but user sees it is not and then he has to fight the app to somehow avoid that road/barrier, is much bigger problem and quite disqualifies the app from serious consideration.

**Comment by aceman444** [comment]
If that unknown barrier is on the single road to the destination, I think OsmAnd routes as close to the destination as possible (probably to that barrier). Then when the user sees the barrier and decides to pass it, OsmAnd can continue routing forward. But it is the user's decision, not the apps.

You now allow OsmAnd to propose impossible and dangerous/life threatening routes. I don't think user's will appreciate it.

There are 1800 different 'barrier' values currently in OSM data. Good luck analysing them and adding to the blacklist (of unpassable ones) in routing.xml.

**Comment by gadamiak** [comment]
> There are 1800 different 'barrier' values currently in OSM data. Good luck analysing them and adding to the blacklist (of unpassable ones) in routing.xml.

Just curious @vshcherb how far you've gone in the list of barriers for almost half a year?
