### ISSUE TITLE
maxspeed:conditional erroneously overrides unconditional maxspeed

### ISSUE THREAD

**Issue by hatzfeld** [osmandapp/Osmand#5198]
Navigating on a road tagged with "maxspeed=100" *and* "maxspeed:conditional=80 @ wet" makes me see 80 as maxspeed instead of 100 (which I would expect - at least when it's not raining :-) ). 

Here is an example:
https://www.openstreetmap.org/way/35484170#map=15/50.4549/7.8768

**Comment by bitboy85** [comment]
Maybe there could be a mixed way. In the right panel it is always showing the value of maxspeed. If a special weather condition exists there could be an Icon at the left bottom.
If a device has an Internet Connection it might be possible to use data from open weather map to give the correct Information. http://openweathermap.org/current

**Comment by pebogufi** [comment]
I had a similar problem. On highway Lat 47.64243 Lon 6.88904 direction SW there is

maxspeed=110
maxspeed:conditional=80 @ (weight>3.5)

Driving a camping car (caravan) with maxweight of 3.5t and using 3.5t in routing.xml which is calculated as 3.49 (see section of routing.xml as follows

	<parameter id="weight" name="Weight" description="Maximum vehicle weight to be permitted on the route" type="numeric" values="0,1.49,2.99,3.49,4.99,7.49,9.99,14.99,19.99,39.99" valueDescriptions="-,1.5t,3t,3.5t,5t,7.5t,10t,15t,20t,40t"/>
)
	
I get information of maxspeed as 80 instead of 110.
So I don't thing the condition "wet" is the problem but the wrong interpretation of conditional as a general problem.
Peter

**Comment by pebogufi** [comment]
One more example on motorway driving direction east at pos  47.74344  7.25731
The street is tagged as follows:
hazard=deer
highway=motorway
int_ref=E 54;E 60
lanes=2
**maxspeed:conditional=80 @ (hazmat:water)
maxspeed=130**
name=La Comtoise
oneway=yes
ref=A 36
shoulder:right=yes
source:maxspeed=FR:motorway
surface=asphalt
toll=no

I get information of maxspeed as 80 instead of 130.
Again like in last comment:
I don't think the condition "hazmat:water" is the problem but the wrong interpretation of "conditional" as a general problem.
Peter

**Comment by vshcherb** [comment]
it looks like it started evaluating condition as time to always true

**Comment by Aiurek** [comment]
Is vehicle weight something that needs to be implemented into profiles, being able to switch between a truck and a car profile? Thus, e.g. the maxspeed:conditional=80 @ (weight>3.5) can be taken into account.
