### ISSUE TITLE
Avoid motorways causes incorrect routing

### ISSUE THREAD

**Issue by PaulStets** [osmandapp/Osmand#5210]
While driving on a motorway section with Avoid Motorways enabled, the app will suggest going off the route even if there is no road.

Coords: Between lat 37.64961, lon -1.18616 and lat 37.60419, lon -1.33363

Screenshot:
![image](https://user-images.githubusercontent.com/20681525/38367042-44089020-38ea-11e8-978c-80be77d7090e.png)

**Comment by ADepic** [comment]
I mean, you told it to not go on a moterway so it is trying to avoid  the motorway at all costs...

**Comment by hakuchi** [comment]
The problem is, if you are on a restarea on a motorway and change to avoid motorway, OsmAnd is not using the motorway to the next exit. OsmAnd is using the nearest road to calculate new route.
Somethimes the next exit is 30-40km ahead and a lot of streets crossing the motorway. This is giving a lot of voice prompts.

**Comment by scaidermern** [comment]
How about adding a high penalty to motorways instead of avoiding them completely? This way the routing will avoid motorways where possible and falls back to motorways when no other route is possible.
