### ISSUE TITLE
Show image of same tag

### ISSUE THREAD

**Issue by osmvermesser** [osmandapp/Osmand#5271]
Many objects die have a Image define by image-tag. 

So i would like to show this additional to mapillary Photos.

If there are licence problems filter before if this are wikipedia images.

Jan

**Comment by AlexSyt** [comment]
We already show that images. Сan you specify the place where it does not work?

**Comment by SantiagoCrespo** [comment]
Hi,

Guess that the OP means that if the "image" tag is present, it would be nice to load that image  along with the mapillary ones.

Image tags are present in 98k elements in OSM, such as this node:
https://www.openstreetmap.org/node/4111680641

As this would be just one image for element, and specific to that element, I would load it before the mapillary images.

Found this issue because I also miss this feature. 

Thank you,

**Comment by xmd5a2** [comment]
https://github.com/osmandapp/OsmAnd-resources/commit/2e44e13b6e7575fc0024781781b90b16d40313da
Test object (image=https://commons.wikimedia.org/wiki/File:Trenes_linea_1klk.jpg):
![screenshot_2018-05-25-12-20-01](https://user-images.githubusercontent.com/5829014/40537420-8aad39be-6017-11e8-80f0-a74ca69d4405.png)

**Comment by SantiagoCrespo** [comment]
Hi xmd5a2,

Tried with several objects and still cannot see the images, only Mapillary. I'm using v 2.9.3
Examples:
https://www.openstreetmap.org/way/377875377
https://www.openstreetmap.org/node/4111680641

Note that the first one have a wikimedia URL:
https://upload.wikimedia.org/wikipedia/commons/f/f1/Arc_de_Triomf_Barcelona_2013.jpg

![screenshot_20180525-133550](https://user-images.githubusercontent.com/26406165/40542831-0eec9fb2-6022-11e8-92b4-5b3cb40a958e.png)

**Comment by xmd5a2** [comment]
@SantiagoCrespo will work with june maps
