### ISSUE TITLE
Question: Translating (weblate) - connected to OsmAnd/res/values-xx/phrases.xml

### ISSUE THREAD

**Issue by majkaz** [osmandapp/Osmand#5278]
I have started translating Osmand on Weblate (mostly inspired by incorrect translations in Osmand). However, I have few questions:
I have found some untranslated phrases. Some of these seem to be however discouraged / rejected tags in OSM - for example [couloir](https://wiki.openstreetmap.org/wiki/Proposed_features/couloir), [cousine](https://wiki.openstreetmap.org/wiki/Key:cuisine#Suggested_values)=sub instead of preffered cousine=sandwich.
What is the best way to point out the discouraged/rejected tags included in Osmand?

**Comment by vshcherb** [comment]
Please check if they are actually included in 
https://github.com/osmandapp/Osmand/blob/master/OsmAnd/res/values/phrases.xml
Couloir
https://github.com/osmandapp/OsmAnd-resources/blob/master/poi/poi_types.xml#L3639

Usually we are driven by data rather than proposals. Possibly @xmd5a2  will give more complete answer.
