### ISSUE TITLE
Routing error

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/Osmand#5332]
When following from right to left, the routing doesn't take shortest path
<img width="866" alt="screen shot 2018-05-03 at 01 40 49" src="https://user-images.githubusercontent.com/1042025/39554442-1fd292b6-4e73-11e8-8743-5323a2cc6fe6.png">

**Comment by tobydickenson** [comment]
I occasionally used to see silly routing like this on UK roads.

Since January I have been experimenting with a modified routing.xml which seems to have fixed this for me. issue #4896 is the background to this experiment. I have set:
1. `rightTurn="0" `. #4896 tells us that this field is nothing to do with right turns, but rather a penalty that gets applied for turns which are between 90° and 120° (in either direction). Many roads join at nominal right angles, so it seems irrational to have a penalty conditionally applied depending whether the angle is slightly above, or slightly below 90°.
2. `leftTurn="600"`. This is a penalty applied to turns above 120° (in either direction). It looks to me like there are two such turns in the route above.

That's all with standard code and modified routing.xml. My next step (which I havent yet had free time for) would be modify the code with a softer turn penalty profile. Something like:
* zero turn penalty up to maybe 45°
* A turn penalty that gradually ramps up at something like 0.5 second per degree, from 45° up to 105°. This is a normal range of road corners.
* A much steeper rate at something like 5 seconds per degree above 105°, which are all non-preferred turns.

**Comment by PaulStets** [comment]
I cannot reproduce this using the latest nightly and MapCreator.

![image](https://user-images.githubusercontent.com/20681525/40305048-9967250a-5d01-11e8-8f41-adee46f1f096.png)

**Comment by vshcherb** [comment]
@PaulStets could you please send location for this error cause it is not mentioned here.
@xmd5a2 could you please double check and close the issue?

**Comment by PaulStets** [comment]
@vshcherb @xmd5a2 Here: https://www.openstreetmap.org/#map=19/-38.69381/146.08672

**Comment by xmd5a2** [comment]
![screenshot from 2018-05-22 10-48-53](https://user-images.githubusercontent.com/5829014/40348962-ccb856ca-5dad-11e8-84ba-e3d559063299.png)

**Comment by PaulStets** [comment]
I seem to have uncovered a more general issue with the routing behavior. The routing seems to ignore the links if they differ in class from the current road.
![image](https://user-images.githubusercontent.com/20681525/40410358-44dd74dc-5e76-11e8-93ec-78d32003a239.png)

**Comment by vshcherb** [comment]
The issue is not longer reproducible with latest maps and it looks like priority of roads was changed. The issue is definitely related to some small tweaks but I guess we've better fix another one if this not reproducible any more
@PaulStets may be it is a different issue so you need to open it separately. Your issue looks totally different btw.
