### ISSUE TITLE
cycle routes rendered ugly

### ISSUE THREAD

**Issue by JuangDse** [osmandapp/Osmand#5355]
If "Show cycle routes" is activated, those routes (apart from being too fat) appear quite ugly (in most resolutions), see attached screenshot.
It may be related to the fact that the routes are actually _relations_ between individual paths, and the edges are created between these paths.

Using Osmand 2.9.0 on Android 5.1.1
![screenshot_2018-05-05-21-04-24](https://user-images.githubusercontent.com/17064606/39666774-87b3a98c-50a9-11e8-94d6-6b975a566596.png)

**Comment by xmd5a2** [comment]
The easiest way to solve this is to change cap to "ROUND". But I don't know which variant is uglier
![screenshot from 2018-06-01 11-43-40](https://user-images.githubusercontent.com/5829014/40831269-40807f7a-6591-11e8-997b-9504d0aad1ff.png)

**Comment by scaidermern** [comment]
Why is there a "gap" between individual paths of a route in the first place? Can't OsmAnd / the renderer to detect consecutive ways inside a route?

**Comment by vshcherb** [comment]
It looks like the rendering is not really correct. Possibly because the line is too thick. 
Though there are 3 options: butt, round, square. Possibly square will be better. 

Though the biggest issue of course using transparency and put these roads over and not under the main road layer

**Comment by majkaz** [comment]
For me, the ideal display would be to reverse the order (layers), in which the additional tags are rendered: cycle route on bottom, then mtb route,  then the "normal" way display and surface/quality on top. 
The current order somewhat hides the details under the cycle route tag (can be seen in the first post).

If solid colours instead of transparency would be used for the routes, one has to think about how both cycle and hiking route can be rendered at the same time. Perhaps offset - the cycle routes on right, the hiking routes on left? Even now with transparency, several hiking routes and a bicycle route on the same way lead to muddy colour.

**Comment by xmd5a2** [comment]
![screenshot from 2018-07-16 20-27-08](https://user-images.githubusercontent.com/5829014/42897161-cdc9615c-8ac7-11e8-8c03-1038afbca51f.png)
