### ISSUE TITLE
Wikivoyage: Some UI related issues

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#5411]
(1) Open a Travel article, tap on "Points", then tap on any point of interest. The desired behavior is that the point tab disappears and the map screen appears, centered on the tapped point. Instead, the Wikivoyage article screen appears again (map is hidden behind it). To worsen things, the article's top-left "Back" arrow is now non-functional, leaving that screen now only works via the device's "Back" button.

(2) Unrelated, but similar topic: Some articles do not contain points, but this can only be found out by tapping on the Points button and reaching an empty points screen. For articles not containing points it  would be better we gray out the Points button form the start?

(3) Every time an article's Points button is tapped, its corresponding GPX file is added to the list of GPX files currently visible on the map (without users being immediately aware of it). I guess we should add the possibility to remove it again by showing a top bar with an (x) button at the top of the map screen, similar to how we do it when e.g. displaying a bus route (after tapping one on a bus stop's context menu)?

(4) When surfing Travel articles while being online (e.g. via Wi-Fi), a significant amount of cached image data may collect. I guess we should
   (a) introduce a maximum limit and upon reaching it delete the oldest pictures again (revolving deletion)
   (b) display the current size of the image cache (number of MB) somewhere, e.g. in the "Clear image cache" line of the Travel settings?

(5) For the sake of power saving, it would make sense to turn off GPS while users are viewing Wiki articles, as it is not needed during that (potentially extensive) time period.

**Comment by vshcherb** [comment]
(1) Serious issue - it is tracked separately and it will be a refactoring to separate activity
(2) Fixed https://github.com/osmandapp/Osmand/commit/9eedf1d7ce6747998efbffc5198218e3517b12f1#diff-bc3abc4f38beffd30ceb6ffdc605522bR297
(3) back button should delete it properly (just tested). But back button will be fixed with (1). Top bar is beyond todays scope.
(4) we didn't manage to properly implement that technique (so we disable displaying size and etc) but that's not bad because you can check it in standard Android Settings (Cache size etc) . Advanced feature of LRU is welcome but it is beyond today's scope
(5) Will be fixed with (1) as it will be separate activity

**Comment by sonora** [comment]
Ok, great!

Regarding image cache (4), I guess the main thing to make sure is that extensive viewing of travel articles does not completely clog a device's internal memory and the user does not notice it is simply the image cache ... so some sort of upper limit may make sense here ..
