### ISSUE TITLE
Duplicated label

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/OsmAnd#5504]
An [object](https://www.openstreetmap.org/way/137307836) tagged with

```
barrier=fence
leisure=water_park
sport=swimming
name=Freibad
```

gets rendered with labels both at the object center and the object outline:
![photo_2018-05-27_20-17-20](https://user-images.githubusercontent.com/1040784/40589311-7aee758a-61eb-11e8-813e-54b67cf6d81a.jpg)

(meanwhile I fixed the tagging from leisure=water_park to leisure=sports_centre)

**Comment by StenSoft** [comment]
This is because OsmAnd interprets the provided data in such a way that the name is the name of both the water park and the fence. I think the proper way would be to separate the fence from the water park. I personally tag places like this as a multipolygon for the water park with the fence as its outer way.

**Comment by scaidermern** [comment]
Yes, sounds reasonable. Although I think the tagging is not exactly wrong. It could be changed of course but this fixes only this specific case and not others. Alternatively OsmAnd could suppress names on barriers. I'm unsure which implications this will have.
