### ISSUE TITLE
Travel guide split by regions/areas/countries

### ISSUE THREAD

**Issue by naoliv** [osmandapp/OsmAnd#5509]
Instead having to download one big worldwide travel guide, couldn't we have it available for small regions/areas/countries, please?

**Comment by sonora** [comment]
I actually quite like having one global file - it saves you the hassle of updating before you gou, and the global download is less that that of thd msp for a mid-size country. So why bother?

**Comment by naoliv** [comment]
Of course it's convenient and practical to have a single file, but it also has drawbacks: you need to download/update a big file (+420MB; a problem if you are using a slow or limited Internet connection), together with more space used on the device.

**Comment by franco999** [comment]
**I agree with @neoliv.** Not everyone has fast Internet connections and not everyone has so much space or wants to take up space on their device with such a large file.

Bearing in mind that the regional map archives are already quite large in themselves, including the world map, I believe that it would be appropriate to divide them by continent at the most. (I think that the world base map should also be divided by continent)

In my case, for example, only with the size of _OsmAnd (~100 MB uncompressed) + world base map (~272 MB) + Argentina (~450 MB) + Wikipedia (~122 MB) + Wikivoyage (~425 MB) and without the nautical depth curves (~677 MB), the nautical depth points (~466 MB) or the contour lines_, I end up occupying **~1.5 GB**. The normal user sees these file sizes and is scared.

**Comment by vshcherb** [comment]
That was original idea and we did some steps to support it. Unfortunately that task looked bigger that we could afford for this release. We still want to split it by continents (50-100 MB) but that requires some work / testing + UI improvements. 

The biggest downside: Travel guide is limited only to 1 Travel Book! So today you could put extra Travel books but Search, Favorites only will work with 1 Travel book. Because it is very big limitation we definitely want to have World wikivoyage file but it makes confusing to have continents & world maps at the same time.

I don't like splitting by language because >50% is English which is necessary as a 2nd backup option (possibly we need to introduce something like Google Translate to other language?)

**Comment by vshcherb** [comment]
BTW: the reasonable size for files is 30-100 MB which is today more like continent size

**Comment by MakiWolf** [comment]
Since the last version there was some little bit improvement not to download the whole world.
![grafik](https://user-images.githubusercontent.com/73300633/108103898-dc5fdd80-708a-11eb-89e5-2fcaee727f71.png)
But it would be great when for example Europa is also split into their countries.

**Comment by vshcherb** [comment]
Our rational size is 50 MB per file, I'm afraid most of the countries will be 5 - 10 MB but you are right that a next reasonable step, let's see if size continue to grow > 300 MB
