### ISSUE TITLE
Display lanes and speed limit for current road, not nearby named road

### ISSUE THREAD

**Issue by nickgl** [osmandapp/Osmand#5510]
I have been verifying the lane count and speed limit using osmand, but when you are on a road without a name it displays 'Near Road Y' but also shows the lane count and speed limit of Road Y, not the current road.

Ideally the speed limit should always be for the road you're on, not a nearby road that has a name.

Many fairly major roads around me don't even have names, so for these the displayed speed limit will be misleading.

Many thanks.

**Comment by tazva** [comment]
Can you provide a road which OSM says doesn't have a name or speed limit? Then it can be determined if that's true or not. I ask this because I'm wondering if your OSM is 'lagging' and getting out of sync with actual location, which is why it's showing nearby data (it shouldn't show 'nearby').

It reminds me of #3898 which still hasn't been fixed.

**Comment by nickgl** [comment]
Hello,

I can provide other screenshots, but here is a pretty good one. I am on a road with no name, and it shows 'Near Kothabah Road' which is the yellow road labelled F08.

![screenshot_20180529-145207](https://user-images.githubusercontent.com/4984886/40699394-0b2f1cf8-63e5-11e8-8765-b3d071514510.jpg)

The two lanes and 60km/h are shown for the road that I am near, not the road that I am on (which is more like 20km/h). That might be how it was intended to work, but I think the speed limit should certainly be displayed for the road you are on, which could be a major road that doesn't yet have a name.

It certainly isn't lag, about 10 seconds after this screenshot it switched to the road just off the left of the screen, displaying 3 lanes.

Thanks,

Nick

**Comment by tazva** [comment]
Nick, thanks for that. I'm a map developer and I try to help out where I can, so I looked at the map to get an understanding of the issue. Your location: https://www.openstreetmap.org/#map=19/25.12096/56.33071

I can definitely say the map lacks a road name or speed for that service road running behind the trade center, so you've identified a bug, and make an excellent point. It likely does simply stem from the simplicity of interpreting the map data, "this road was X limit, so the nearby one is likely the same". 

Since it's a service road, I too would think it shouldn't simply grandfather the speed of the highway. Hopefully the App developers can find a swift resolution to this.

**Comment by nickgl** [comment]
Hello,

Yes, that was the location from the screenshot. Well located.

If it would be useful to have another screenshot from a more significant road. Quite a lot of roads around here don't yet have names yet, and so this issue is cropping up quite frequently.

Here's an example of a pretty major road which is unnamed. I'll try to get a screenshot from a road like this one to show another example.

  https://www.openstreetmap.org/#map=17/25.11825/56.28401

Thanks everyone,

Nick

**Comment by tazva** [comment]
If you know & can provide information for the names & speeds, it can be rectified. As to the app issue itself, that will be up to @vshcherb  or someone else. Thanks for providing screenshots & help, so all of this can be improved.

**Comment by vshcherb** [comment]
Should work now
