### ISSUE TITLE
FOSS or not FOSS

### ISSUE THREAD

**Issue by prog-amateur** [osmandapp/Osmand#5531]
Hello, 
First of all, I don't want to troll anything here. I really appreciate the app. I am just wondering if OSMAnd is FOSS or not FOSS ? 
The main problem is due to F-Droid Warning claiming that "some parts of the app are not open-source". 
How to clarify ? I was thinking about extensions, or optional services, but it is clearly said "parts of the app". 

So, please, could you clarify, and if so, is there any Full Open Source fork of this app ?

Thank you very much.

**Comment by ADepic** [comment]
Mapillary isn't fully open source and that is the anti - features listed on osmand. Otherwise it is open source

**Comment by vshcherb** [comment]
It is a tough question. Again every product should be carefully reviewed by committee, we are not targeting to make it completely FOSS, that's why we support F-Droid publishing philosophy (it is not done by OsmAnd team).

I hope to dedicate time and write an article what's our mission and explain all details about Licensing and other details
