### ISSUE TITLE
Routing issue in Poland

### ISSUE THREAD

**Issue by PaulStets** [osmandapp/Osmand#5544]
Route: 
Mieczysława Wolfkego, Wrocław (51.15950, 16.87320) 
Aleja Generała Józefa Hallera, Wrocław (51.09440, 16.98030)

Screenshot:
![screenshot from 2018-06-04 15-08-18](https://user-images.githubusercontent.com/20681525/40916704-578d1e24-6809-11e8-860f-d711551f7058.png)

**Comment by naoliv** [comment]
Maybe it's not properly dealing with turn restrictions with ways as `via`, like https://www.openstreetmap.org/relation/5586928

**Comment by majkaz** [comment]
There is [similar issue ](https://groups.google.com/d/msg/osmand/bwPVefDxgQU/If4EoE9ABQAJ)in Germany, mentioned in the forum.

Even taking in account missing restrictions, the route doesn't make sense: Instead of one primary_link connection (which would be the correct routing), you get two traffic lights and two sharp left turns. No way this can be faster then the correct and simpler route route.

![image](https://user-images.githubusercontent.com/23097386/41666200-36c50b22-74aa-11e8-896a-41de75b70dc4.png)

**Comment by hakuchi** [comment]
can this be fixed when the right turn have a lover time value as the left turn?
On a left turn/u turn you loose more time as on a right turn.
maybe this can be implemented into OsmAnd, so not all intersections need a turn restriction to work.

**Comment by xmd5a2** [comment]
Not reproducible any more in car routing
![Uploading Screenshot from 2019-11-27 11-22-26
![Screenshot from 2019-11-27 11-19-49](https://user-images.githubusercontent.com/5829014/69706204-3da73400-1108-11ea-963c-b9a35dc98118.png)
.png…]()
