### ISSUE TITLE
Display elevation profile during navigation

### ISSUE THREAD

**Issue by PaulStets** [osmandapp/OsmAnd#5684]
It would be convenient to add an elevation profile (e.g. at bottom of the map) so that users could see the elevation ahead during the navigation with the gpx track.

**Comment by mahdi1234** [comment]
In general this be great to see directly after route calculation, i.e. when in walking/cycling mode and unknown area i'm really interested to see elevation profile and maybe adjust route a bit if I'm in mood for more flat trip profile.

**Comment by quax2712** [comment]
I used OSMAnd first time touring in blackwood (Germany). If it would get problems, I had my Garmin navi as a backup with me. OSMAnd works very helpfully. The only questions, I could now answert were about elevation. This is the only feature I realy miss very much. Every touring person (walking/cycling) need this feature. May be it could be displayed in the upperline, where normaly the road name is displayed. Ofcourse a littel higher, so that height lines could be displayed.

**Comment by yourealwaysbe** [comment]
Just posting my vote for this feature -- it would be very useful when cycling to know what the remaining hills look like.

Many thanks for all your work.

**Comment by yourealwaysbe** [comment]
I have had a go at implementing this, and have a commit for it [here](https://github.com/yourealwaysbe/Osmand/commit/9bbef4ed14fd316bb5d2b539bd84474090406c2b). It's a bit rough around the edges, and i'm not fully sure how to test it against the bleeding edge version of OsmAnd (the commit that was latest when i put this together does not compile for seemingly unrelated reasons).

I'd be happy to work with someone to get it finished off and polished.

**Comment by vshcherb** [comment]
@yourealwaysbe  Please share screenshots how it looks
