### ISSUE TITLE
OsmAnd is no longer suggested to open the links shared from the Google maps

### ISSUE THREAD

**Issue by PaulStets** [osmandapp/OsmAnd#5735]
It is no longer possible to share a location from the Google maps to OsmAnd.

**Comment by thompehw** [comment]
Google maps has changed. For example, the Android "GPS Bridge" app has had to close down. 

And they've changed how they give "plus" (open location) codes to [short-code, Locality] which OsmAnd doesn't seem to accept. If you search for a location in Android Google Maps, then drop a pin on/near it (long press) then finally you get lat/long that you can copy and paste into OsmAnd (just tap on them to copy).

**Comment by ADepic** [comment]
@thompehw  It's not that either. All you have to do is copy the google maps link, paste it into the osmand search, and the correct location (lattitude and longitude) will appear in the search results. If this works I don't see why osmand can't just get shared links.

**Comment by vshcherb** [comment]
There was ongoing effort from Google that only Google Maps could open Google links, I think now it comes true, I don't have any other explanation cause OsmAnd is registered for all google.com ,... links to handle

**Comment by jkarlson** [comment]
There is some code to deal with this. eg., if you can emulate any such tool that resolves the url to the form that osmand understands, you should be able to fix this. There is eg. libcurl.

curl -I https://maps.app.goo.gl/SnMec
...
location: https://www.google.com/maps/place/60.199452,24.795212/data=!4m6!3m5!1s0!7e2!8m2!3d60.199451999999994!4d24.7952115?utm_source=mstt_1
...

**Comment by giner** [comment]
@jkarlson apparently not anymore. It has only `data` now but not coordinates.

**Comment by Friptick** [comment]
Why does Osmand not simply allow inbound sharing of plain text?

In other words: (1) select text address, _or coordinates_, _or shortcode_ ; (2) share to Osmand; (3) tap Search. Done!

At present it is:

1. Select text address or shortcode
2. Long-press selection
3. Select copy
4. Long-press search field in Osmand
5. Select paste
6. Search

Fastidious. This problem would be almost fixed by just allowing inbound sharing of text.

**Comment by Friptick** [comment]
Update. The main issue here was fixed with PR #9317 (see issue #8201) . Now it is possible to share arbitrary text addresses direct to Osmand. Thanks! 

**There is one remaining annoyance. Osmand does not understand Open Location Codes (AKA "short codes", "plus codes") _when they are suffixed with text_.**

`AB1C+A2` > WORKS! 

`AB1C+A2, Salzburg, Austria`> DOES NOT WORK :( (but this is how Google outputs them)

Apparently the extra location data ("Salzburg, Austria") is needed only if current location is outside that region.

Open Location Codes were invented by Google but they are an open standard. It would be very helpful if Osmand could understand them properly.

**Comment by vshcherb** [comment]
Yes it's a known issue, custom region / city not supported yet.

**Comment by Friptick** [comment]
@vshcherb Please close this issue, it is solved except for the specific bit about abbreviated short codes, now here in more detail: #12809
