### ISSUE TITLE
Pedestrian navigation — Add vibration

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/Osmand#5744]
I think we need to add vibration, to pedestrian navigation, when screen is off.
Also we could test, add a borste for the left turn, and two for the right.

**Comment by thompehw** [comment]
I would love this. There are many cities where you want to minimise how much you have your phone out of your pocket to avoid theft.

But... I tried to follow a route in Rome using Google Maps with the phone vibrating in my pocket. We walked miles off course, because there was no vibration code to tell me that the GPS signal was unreliable in the narrow streets. If OsmAnd could address that, I'd never use Google maps for pedestrian navigation again!

**Comment by vshcherb** [comment]
Merged to #7484
