### ISSUE TITLE
[Feature request] Add a combined navigaion engine (OSMAND + YOURS)

### ISSUE THREAD

**Issue by MegaArthur** [osmandapp/Osmand#5787]
### (I'd code it myself if I knew how to)

Hello,

I am a long-time user of OSMAnd and seen as I frequently make long trips, I thought of a feature that would help greatly when calculating long distances.

The feature I am talking about would be the possibility of merging together OSMAND's offline nav service with the YOURS online one, in-app. 

This would work like that:

The majority of the trip would be calculated using YOURS (it's very quick when it comes to >1k km trips) so that OSMAND doesn't have to try and calculate it for 10 minutes or more (and recalculate when going off the track), but the 5-10 km fragment from the user's current location would be calculated using OSMAnd, because it's much more accurate.

Example of OSMAnd vs YOURS? Roundabouts. OSMAnd interprets them as what they are, which is roundabouts, but YOURS just marks them as turns.

Also, when the road is curved, but without any additional roads connecting to them, OSMAnd keeps silent, while YOURS alerts of every single curve saying "turn left" or right, which gets annoying quickly.

I don't think it would be hard to implement a combined nav engine and it would be of great help, especially on long roads.

**Comment by ouinouin** [comment]
Hi, facing the same kind of issues while using OSMAND, for long trips, the calculation takes forever, it could be good for osmand to retrieve from an  online router juste few points  from the online calculated routes and make calculation offline to really get the navigation indications from the OSMand offline router (since with online routers you dont get street names and other indications while announcing directions.)
Otherwise making some option for increasing the routing algorithm speed even at the cost of routing precision would be welcome, this sugginess on the routing engine made this a no-go for everyday use (i ll be ready to support financially all kind of features making routing acceptable for 500 600 km trips in europe.

**Comment by scaidermern** [comment]
In my opinion speeding up the routing (and the overall performance of OsmAnd) should be number one priority. This is way more important than constantly adding new features. Features are nice but they aren't really useful if the most basic function (map drawing & navigation) don't work as expected. This is not a rant, OsmAnd is really nice and I prefer it over every other app. Nevertheless there is still a lot to do to satisfy these basic needs.

**Comment by vshcherb** [comment]
Yours is an outdated service and soon will be gone. Indeed we rather should focus on implementing long routes in OsmAnd itself.
