### ISSUE TITLE
Add support of short OLC codes

### ISSUE THREAD

**Issue by alyonapinchuk** [osmandapp/Osmand#5798]
OsmAnd supports only full OLC codes. 
For example, ¨CGP4+FP Kyiv¨ cannot be found in OsmAnd. 
Google Maps application now shows a short version of OLC also known as plus codes.

**Comment by Franky1** [comment]
I double this feature request.
Google Search & Google Maps can handle short plus codes as well.
If you search within current view in Google Maps the closest possible location is found.

_Why do i request this feature?_

We are using Osmand quite often during **Search and Rescue** operations.
Sometimes we don't have mobile network coverage and only our two-way radios work.
So we have to handle coordinates via speech - which always causes errors.
Therefore the plus codes are an advantage and especially the short plus codes.
**The short plus codes are much shorter than the normal coordinates and can be better spelled via two-way radios.**

Since our "Region of Interest" is usually limited (short codes repeat every 100km), we don't need the full (global) plus codes (with the 4 digit leading area code).
It would be a major advantage, if we just can enter e.g. "MV5M+CH" in the current map view of Osmand and have the closest possible location for this short code.
