### ISSUE TITLE
Rendering is slow on Android O [Almost fixed]

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/Osmand#5878]
This is a spin off of #4323 which became very messy to manage the current situation.

*The short description*:
Rendering is very slow when moving the map (bug 1.) and when zooming the map (bug 2). Bug 2 is possible to have a workaround if you disable animations.

*Long description*
The rendering itself has same speed as before though double buffering technique is broken in Android O. Drawing already rendered image on the canvas couldn't reach 60 FPS, so the application looks very laggish. You could check the numbers by enabling Developer plugin and Adding FPS widget via Configure Screen.

*Android Bugs*
Here are the bugs reported to Google (which claimed to be fixed but not available on all devices yet):
https://issuetracker.google.com/issues/64882137
https://issuetracker.google.com/issues/70113293

*List of affected devices*:
Android 1.
Mi 1 - Android 8.1 (note issue wasn't present in latest Android 8.0 )  [only zoom]
Huawei p10 plus - Andorid 8.0.0  [only zoom]
Lenovo p2a42 - AOSP Extended 5.8 (android 8.1) [only zoom]
Moto Z Play - Android 8.0.0 (Security Patch June 2018)  [only zoom]
Nexus 6P - LineageOS 15.1 (Android 8.1.0) [only zoom]
ALL devices on LINEAGE OS 15.1 (Android 8.1.0) [only zoom]

*NOTE*:
Please note that messages non-helpful to fix the bug or describe the situation will be deleted. Messages reporting new affected devices will also be deleted and the description of the bug will be updated.

**Comment by xialady** [comment]
It also affects Huawei P10

**Comment by swedneck** [comment]
On my lenovo p2a42 running AOSP Extended 5.8 (android 8.1) the FPS is reported as approx 4/4 when zooming, however the FPS is fine when moving the map.

**Comment by ADepic** [comment]
Looking through the comments of #4323 we can see any device running LINEAGE OS 15.1 is affected .

**Comment by ADepic** [comment]
@swedneck if your AOSP extended build is affected, then most likely all AOSP extended devices are affected.

We still need more evidence, are there any AOSP extended users not affected by this.

Doing some skimming [here](https://forum.xda-developers.com/oneplus-one/help/aosp-vs-los-t3570047) it seems that AOSP extended is based off lineage os.

Also the download list for AOSP extended is almost the same as Lineage OS,making it seem that AOSP extended is based off lineage os.

On top of that AOSP extended's website said it put together multiple open source AOSP projects, which is more evidence it is a fork of lineage is.

Taking all this evidence into consideration, it seems quite likely AOSP extended is built upon Lineage OS.

Since we already know all LineageOs 15.1 devices suffer from this issue, it is quite likely that all AOSP extended ROM suffer too.

However, can someone confirm that AOSP extended is built upon Lineage OS? then @vscherb can add it to the list of affect operating systems.

**Comment by Digory123** [comment]
Affected device:
Motorola (Lenovo) Moto Z Play
Android 8.0.0, Security Patch June 2018
Panning ~ 60 FPS and higher
Zooming starts with 1 FPS

**Comment by sedot42** [comment]
Sony X Compact, Android 8.0.0, Patch Level May 2018: Rendering speed for both panning and zooming is about 1500ms in highly populated areas. FPS falls below 60 for zooming only.

**Comment by JulienPalard** [comment]
Affected device: Nexus 6P, LineageOS `15.1-20180813-NIGHTLY-ANGLER` (Android 8.1.0)

**Comment by ADepic** [comment]
Julien, all lineage os 15.1 devices are affected. So its more useful to report problems with default OS on the phone.

@vshcherb 
ONEPLUS 3 Oxygen OS with android 8 NOT AFFECTED. 

@raindropsfromsky didnt get affected either
"I have not observed any speed issues on OnePlus 3T after update to Android 8.0.0 (OxygenOS 5.0).
OsmAnd~ 3.0.0#23181M (released on 20th Nov 2017)"


So add Oxygen OS to the list of NOT affected devices - One plus 3,3t and probably 5,5t and 6 too

**Comment by aceman444** [comment]
The linked Google bugs claim the problem was fixed somewhere around Oct-Dec 2017. That is after the initial public release of Oreo 8.1. So unless Google packs this into the monthly "security update", this can only be fixed in Android P (9.0). Also the release notes link in the bugs at https://developer.android.com/preview/release-notes.html shows Android 9.

**Comment by Rpnpif** [comment]
I do not know if it is the same issue, but I observed that erasing with a file manager all the files of OsmAnd Live, after disabling it, increased significantly the rendering speed (perhaps 2 times) getting acceptable speed.

Is it the same issue or should I create a new issue report?

**Comment by aceman444** [comment]
I'd say that is a completely different bug. I also think I have noticed that slowdown in the past, but consider it normal operation. Because with OsmAnd Live there is the main map file and several new files in the Live folder. When rendering, OsmAnd must read objects from the main file, and from the additional ones, determining differences (they are not just cumulative (additional), but there may also be removal of objects from the main file) and then render the result. This will always be slower than just plainly reading and rendering the main file. The question is how much slower, whether 2 times is acceptable or not. Depending on how much change there is in a month in your chosen map region, the additional Live files can be a good fraction of the main file.

**Comment by Digory123** [comment]
In my case (Moto Z Play Android 8.0.0) it makes a big difference for FPS if my current GPS-position is on the visible area of the map or not (see attatchments).
![screenshot_20180824-082310](https://user-images.githubusercontent.com/40560661/44569135-af603780-a779-11e8-8d38-2849103bf07e.png)
![screenshot_20180824-082320](https://user-images.githubusercontent.com/40560661/44569136-af603780-a779-11e8-8bff-c5a876941e81.png)

**Comment by Aiurek** [comment]
Affected device:
Huawei p10 plus (Andorid 8.0.0)

**Comment by vshcherb** [comment]
Please try latest night build there are some changes in Canvas display

**Comment by Digory123** [comment]
Tried the latest night-build from http://download.osmand.net/latest-night-build/OsmAnd-nightly.apk. No improvements regarding panning and zooming on Moto Z Play with Android 8.0.0.

**Comment by miki151** [comment]
I just tried the current nightly from the above link and there is some improvement compared to 3.1.5.

Lineage OS 3.15.1, Samsung A3 2017

**Comment by vshcherb** [comment]
3.2.1 is rolled out, please feel free to give a try.

**Comment by miki151** [comment]
Thanks. You should probably update this page: https://osmand.net/downloads. It doesn't show the 3.2 release.

**Comment by sonora** [comment]
NOT affected: Samsung XCover 4 recent stock ROM update to Android 8.1 works smoothly with 3.2.1.

**Comment by ADepic** [comment]
Rendering almost fixed on lineage os. For one plus running lineage os with microg, 30fps zooming in & out. For oneplus2, zooming out is 30fps. For zooming in, the first half of zooming in is around 15fps, and second half is 30fps.

Zooming is still stuttering (15fps) for huawavi running EMUI with android 8

**Comment by Digory123** [comment]
On Moto Z Play (Android 8.0.0 Security Patch 1. August) FPS ist constantly 12/~80 with my current position visible on the map.  In a map sector without my current position visible FPS is nearly 60/60.
Zooming has improved a little bit, but still far away from behaviour in Android 7.
When zooming in FPS widget doesn't seem to refresh correctly, it hangs until rendering has finished. Zooming out process goes down to 2/25 FPS.
Actually I could use Osmand only for purposes when I don't have to zoom in or out often, for example following a track on bycicle.
When I want to discover my environment with a lot of zooming processes Osmand is actually useless, so that I have to use alternatives.

**Comment by scaidermern** [comment]
Not sure if it belongs here. Has there been any research on how other apps achieve fast drawing on a canvas? Or how/if other apps use double buffering? Some sources on the Internet say that double buffering should be avoided in Android. However I'm not really into these techniques, so just asking as a layman.

**Comment by bradmoss** [comment]
I have a Moto G6, and I had to stop using Osmand+ version is 3.2.2, released 2018-10-01
Please, do something, I don't understand what happened but I can't use the app I payed for anymore this way.

**Comment by Digory123** [comment]
Zooming has improved in 3.2.5, but still far away from performance with Android 7.
However, since it seems to be an Android bug and my Moto Z Play won't get Android Updates anymore, I'm afraid this problem cannot be solved on my device...

**Comment by aceman444** [comment]
Still using OsmAnd 3.2.2 on Nokia 6.1, which now received Android 9 (Pie). I see no obvious change in performance. But with 3.2.2 the perf was already more or less OK, as I reported in my previous comment. Is it because 3.2 workarounds the problem API of Android?

**Comment by JulienPalard** [comment]
Testing 3.2.5 on Nexus 6P with no shadows and no altitude lines, details 0/7.

- Standing still: 51/91 FPS
- Zooming in gets me to 20/14 FPS (tried again, got 15/11 FPS)
- Zooming out gets me to 31/21 FPS (tried again got 19/26 FPS)
- Moving never goes below ~40/~40 FPS

From a user point of view now, I think it's more usable than a few month ago, I'll start to use it again and see on a daily basis if it's OK.

**Comment by ADepic** [comment]
It's been a year. Any work on this critical bug???

**Comment by vshcherb** [comment]
This issue is outdated so far no glitches on new devices with Android 9 / 10.

**Comment by CliveTheSecond** [comment]
It's still extremely slow for me. I have a Pixel 2 XL running GrapheneOS (Android 11). I was using an iPhone 8 previously and it ran perfectly, so this was a bit of a shock for me.

Recording: https://tube.tchncs.de/videos/watch/3b407008-d683-4418-b146-acc52a98b84f

P.S. I tried to upload that directly to GitHub as a GIF, but I couldn't figure out how to make it small enough.

**Comment by dbadura** [comment]
@CliveTheSecond 
here is a similar open issue: https://github.com/osmandapp/OsmAnd/issues/8370
