### ISSUE TITLE
bus stops are rendered with roof when no roof is tagged in OSM

### ISSUE THREAD

**Issue by seb-1204** [osmandapp/Osmand#5935]
Before entering an issue, please read the information below.

In case you are not sure to open issue or not, please send your request to support support@osmand.net. For **general questions** about OsmAnd, please use the [Google group](https://groups.google.com/forum/#!forum/osmand).

Please be sure to have read our [FAQ](http://osmand.net/help-online) before creating an issue here. (Also, tell us in Google Groups when the FAQ is wrong or outdated.)

The best way to get help about an OsmAnd issue is to create a valid and detailed issue content.
Please give us the following information so that we can try to **reproduce** your issue:

The two bush shelters where rendered with roof on my device. The OSM data is not listing them as covered. Also see the [note](https://www.openstreetmap.org/note/1493747#map=19/47.12347/11.33152)

What version of OsmAnd are you using, on what device and Android/iOS version?

OSMAnd+ 3.1.5

Do you use the offline maps offered within the OsmAnd app for download, or online (tile / raster) maps?

in the Austria Tirol map, location here: https://www.openstreetmap.org/note/1493747#map=19/47.12347/11.33152

**Comment by hakuchi** [comment]
next time you should post a screenshot from the POI, because it is rendered with the actual symbol for shelter=no

shelter=no is rendered with a red roof "^"
sheter=yes is rendered with a blue roof
and if there is no shelter=yes/no in OSM it is rendered without roof

I think OsmAnd should render only if there is a shelter with the blue symbol and a blue roof.
It is hard to understand, that a red roof means that there is no shelter.
