### ISSUE TITLE
Mistake in navigation (Libya map)

### ISSUE THREAD

**Issue by alyonapinchuk** [osmandapp/Osmand#5947]
Start point: Lat 31.22062 Lon 16.31448
End point: Lat 31.22242 Lon 16.29993
![image](https://user-images.githubusercontent.com/40493090/44727487-d18fe780-aae2-11e8-855e-b0bfde55f0a0.png)

**Comment by naoliv** [comment]
The error is probably caused by this barrier at the highway: https://www.openstreetmap.org/node/288476324

Maybe it should be changed to [military=checkpoint](https://wiki.openstreetmap.org/wiki/Tag:military%3Dcheckpoint), to another [barrier](https://wiki.openstreetmap.org/wiki/Key:barrier) value (with a proper `access` value) or even removed?

**Comment by vshcherb** [comment]
Done
