### ISSUE TITLE
Transliteration bug in German

### ISSUE THREAD

**Issue by Discostu36** [osmandapp/OsmAnd#5954]
When using German place names and activating transliteration of non-German names, all Umlauts disappear from the location names in Germany. So e.g. Wörthstraße is rendered  (and read out) as Worthstraße.

**Comment by Discostu36** [comment]
Osmand 3.1.5 on Android

**Comment by hayosc** [comment]
I just found more or less the same bug in OsmAnd+ 3.2.7.
More or less, because for me "Wörthstraße" (Kiel, Schleswig-Holstein, Germany) transliterates to "Worthstrasse". 
This happens if "Beschriftungssprache" -> "Transliteration, wenn Namen in Deutsch fehlen" is active.
Here we have indeed two bugs:
1) Names in German should be displayed. In Germany, Austria and parts of Switzerland the standard name is the German name. There is nothing like de:Wörthstraße, which could be what OsmAnd expects.
2) The transliteration is wrong. If you transliterate German spelling to something like international 7-bit-ASCII, then it should result to "Woerthstrasse". The correct mapping is: ä -> ae, ö -> oe, ü -> ue, ß -> ss
Transposing ö to o is something the US Americans do, because they do not know it any better.

**Comment by Flexmaen** [comment]
This bug still exists in 3.5.5.

I attached some screenshots.

1. the current result
2. the expected result (check the names H**ö**nigtal, Lassnitzh**ö**he, Rastb**ü**hel)
3. prove that the name will be displayed with "ö" in the details
4. setting that causes this issue

So if you enable transliteration for other languages to German, it doesn't make sense that German gets transliterated for other languages. And btw this is wrong anyway. Since Words can have a complete different meaning if the are written with u or ü, ü usually transliterates into "ue".

![osmand_1](https://user-images.githubusercontent.com/6330276/72978925-8eb96880-3dd7-11ea-9a79-c191470ca6c3.jpg)
![osmand_2](https://user-images.githubusercontent.com/6330276/72978927-8eb96880-3dd7-11ea-84fb-414781f3f468.jpg)
![osmand_3](https://user-images.githubusercontent.com/6330276/72978928-8eb96880-3dd7-11ea-9a79-0851ca206ae2.jpg)
![osmand_4](https://user-images.githubusercontent.com/6330276/72978929-8f51ff00-3dd7-11ea-81d7-ac55703c9a4c.jpg)

**Comment by scaidermern** [comment]
Bug still exists in OsmAnd 3.9.10.

**Comment by Flexmaen** [comment]
There seem to be two bugs in here:

- One thing is the transliteration from German names where ü should be ue. Seems to be related to [this ](https://github.com/osmandapp/OsmAnd/blob/master/OsmAnd-java/src/main/java/net/osmand/util/TransliterationHelper.java#L28-L36) and [that](https://github.com/gcardone/junidecode) code.
- The other problem is that this is depending on the "name" or "name:de" field. For some reason the problem appears in Austria only. I have "München" and "Nürnberg" (Germany) as well as "Ödenburg" (Hungary) or "Wöllan" (Slowenia), but i Austria I have St. Polten (should be St. Pölten) and Murzzuschlag (=Mürzzuschlag).

**Comment by Discostu36** [comment]
I still have Worthstraße in Kiel, Germany. This is not a problem exclusive to Austria.

**Comment by Flexmaen** [comment]
Interesting. I didn't find name:de for München, but the the cities in non-german-speaking countries certainly have.

**Comment by Flexmaen** [comment]
I tested this with 4.3.12 and the result is that I get different results on 2 devices.

On the device with Android 8, this bug still exits, but all names are in latin.
On the device with Android 12, the Umlauts in German names are now shown, but not all things are transcribed into latin. For example in Serbia [Jagodina](https://www.openstreetmap.org/relation/2869333) is shown in latin, while [Ћуприја ](https://www.openstreetmap.org/node/1599441293)(shown on the other device as Tshuprija) is not.

**Comment by scaidermern** [comment]
I can't reproduce this any longer with OsmAnd 4.5.1 on Android 10 and rendering engine v2. With rendering engine v1 it still exists, though.

**Comment by Flexmaen** [comment]
> I can't reproduce this any longer with OsmAnd 4.5.1 on Android 10 and rendering engine v2. With rendering engine v1 it still exists, though.

Can I change the rendering engine manually? Maybe my devices are using different rendering engines.
How about the Serbian examples I mentioned in your case?

**Comment by scaidermern** [comment]
> Can I change the rendering engine manually?

Not with your heavily outdated version.
In recent versions, you can change it via Settings / OsmAnd settings / Map rendering engine.

> How about the Serbian examples I mentioned in your case?
They (mostly) look correct with both rendering engines as far as I can tell (I'm no expert at Serbian transliteration, though). I've checked the examples Vranje, Kraljevo, Kragujevac and Džep from #13900. They are transliterated exactly like this, except for the last one. Instead of Džep OsmAnd only shows Dzep.

**Comment by Flexmaen** [comment]
My old phone is not deppert, so it works even with Android 8! ;-)

Ok I tried again, and it is depending on the rendering engine.
The result is like mentioned before:
Rendering Engine V1: the bug here still exists
Rendering Engine V2: the bug here doesn't exist, but there seems to be a new bug where not all places are transliterated, e.g. in Serbia still many cities are shown in cyrillic letters.

**Comment by scaidermern** [comment]
> Rendering Engine V2: the bug here doesn't exist, but there seems to be a new bug where not all places are transliterated, e.g. in Serbia still many cities are shown in cyrillic letters.

Can't confirm. If I enable "Use latin name if missing", no cyrillic letters are left.

**Comment by Flexmaen** [comment]
> > Rendering Engine V2: the bug here doesn't exist, but there seems to be a new bug where not all places are transliterated, e.g. in Serbia still many cities are shown in cyrillic letters.
> 
> Can't confirm. If I enable "Use latin name if missing", no cyrillic letters are left.

Did you try to zoom in? When I don't zoom in to far it looks fine, since major cities are written in latin. If I zoom in closer, I'll have a lot cities in cyrillic. Tried with downloading the map or serbia as well as with just the world map and result was the same.

![srb_0](https://github.com/osmandapp/OsmAnd/assets/6330276/54364b3c-17b7-4422-9b0b-7554b918d069)
![srb_1](https://github.com/osmandapp/OsmAnd/assets/6330276/4c10be71-48e0-419b-879a-8899c8a9caee)

**Comment by scaidermern** [comment]
I get a similar rendering if I _don't_ enable "Use latin name if missing" - which is expected. If I _enable_ "Use latin name if missing" there are no more cyrillic letters. Same area and same zoom as you.

**Comment by scaidermern** [comment]
> I tried with OSMAnd 4.3.12 which is the latest version on F-Droid

F-Droid has version 4.4.7. 4.3.12 is just the preferred version, for whatever reason.
