### ISSUE TITLE
White squares on the map

### ISSUE THREAD

**Issue by alyonapinchuk** [osmandapp/Osmand#5999]
There are white squares on the map which do not indicate any road symbols. 
Examples: : Lat 46.32217 Lon 18.63940, other example: Lat 46.18549 Lon 18.33405.
![image](https://user-images.githubusercontent.com/40493090/45223101-fcd2bd80-b2be-11e8-943e-1cae231d7917.png)

**Comment by pietervdvn** [comment]
This is a wrongly encoded hiking symbol. Have a look at https://wiki.openstreetmap.org/wiki/Key:osmc:symbol and fix the hiking relation at openstreetmap.org. with your next map update, the icon will be filled.

**Comment by vshcherb** [comment]
closed as a map issue

**Comment by Gollam** [comment]
Hi,
There are many relations defined on this road path, at lest 2 iwn, multiple nwn-s, and one rwn. This is the rwn: https://www.openstreetmap.org/relation/6936992#map=16/46.3363/18.6491
And I think this one is preferred here. In the app version 3.7.4, these are still white squares, and the reason is because the osmc:symbol in this case is the following: "blue:white:::M:blue"
So the waycolor is blue, that is correct, the background is white, that is also good. But the last 2 fields are the letter M, and textcolor is blue. According to the osmc:symbol definition, this text should be printed over the symbol, which is not happening, so I think this is still a bug.

Best regards,
Balazs

**Comment by Gollam** [comment]
@vshcherb what do you think? The rendering should be fixed IMHO.

**Comment by sonora** [comment]
Looking at https://wiki.openstreetmap.org/wiki/Key:osmc:symbol?uselang=en, the cortect encoding should be "blue:white:M:blue".

**Comment by Gollam** [comment]
Interesting, I always thought of it like the optional fields should also be separated with a colon, to indicate which field is which one. But now, looking at the examples, I agree with you. I'll try to fix the map then and we'll see what happens :)

**Comment by sonora** [comment]
In the documentation it says 
`osmc:symbol=waycolor:background[:foreground][[:foreground2]:text:textcolor]`.
The brackets enclose exactly the optional portion, i.e. where they enclose the ':' also, it needs to be omitted also, I guess.

**Comment by Gollam** [comment]
@sonora I tried it, and it didn't work :( https://www.openstreetmap.org/relation/3345655 Changed it to "red:white:M:red" here (14 days ago), downloaded the July update but the letter M is still outside the white box. @vshcherb I still think this is a bug, what do you think?

**Comment by vshcherb** [comment]
It is not wrong it is related that we don't support Letters on the osmc:symbol i.e. 3rd or 5th parameter. We support lables on the road but not on the symbol itself.

Here the same issue https://github.com/osmandapp/Osmand/issues/9358
