### ISSUE TITLE
Maybe should not render big protected areas

### ISSUE THREAD

**Issue by naoliv** [osmandapp/Osmand#6063]
Have this big protected area https://www.openstreetmap.org/way/179088159

In OSM nothing is rendered at this location, for example: https://www.openstreetmap.org/#map=15/-22.5542/-47.9021

![](https://user-images.githubusercontent.com/982338/45688163-082bb180-bb27-11e8-99f5-196b3030e6ca.png)

But in osmand the screen is filled with light-green `P` icons:

![](https://user-images.githubusercontent.com/982338/45688195-21346280-bb27-11e8-8b71-8489df55d3b0.png)

Maybe areas like this should not be rendered at all? (to avoid filling all the map with green `P` icons)

**Comment by hakuchi** [comment]
I found a other protected area(https://www.openstreetmap.org/relation/3547850), and it looks similar to the area from your link.
In OsmAnd this is not rendered. I dont know if this is because this is a multipolygon, or for the `protect_class=5` tagging.

Can you test the rendering if you add `protect_class=5` to your area?

**Comment by IgorEliezer** [comment]
Hey, this one is very close to the region I'm mapping, so in your homage I created another: [APA Tietê](https://www.openstreetmap.org/relation/8712428).

This kind of protected area (`protect_class=5`) is less restrict than those full protected areas (`protect_class=1 to 3`). I lived there for a few years, you can do pretty much everything in a normal life except there are some restrictions as to farms, woods and specific sites. So I believe it's not necessary to render "P" icons everywhere unless the area is fully protected.

**Comment by IgorEliezer** [comment]
Update: it took a while to update the map to test how the protected area that I added would turn out.

The protected area is a boundary relation added to the administrative boundaries. The result:
1. No "P" icons.
2. The administrative boundaries with protected area relation vanished.

![screenshot_2018-09-19-00-18-42](https://user-images.githubusercontent.com/4673289/45731888-1b369400-bbb0-11e8-98ed-cf05e1c976a8.png)

**Comment by comradekingu** [comment]
What is it meant to protect?

**Comment by IgorEliezer** [comment]
> What is it meant to protect?

Mostly scenic landscape and historical sites (18th and 19th century). There are some governamental programs and laws towards environment restoration and sustainable agricultural, forestry and tourism while it allows [anthropic interaction](https://en.wikipedia.org/wiki/Anthropization).

https://www.iucn.org/theme/protected-areas/about/protected-areas-categories/category-v-protected-landscapeseascape

**Comment by xmd5a2** [comment]
@IgorEliezer regarding your example near Rio Tiete. Protected areas with protect_level>=5 are not rendered by design https://github.com/osmandapp/OsmAnd-resources/blob/master/obf_creation/rendering_types.xml#L5152
Also I can't confirm that admin_level boundaries are vanished. Do you use OsmAnd Live?
![screenshot from 2018-10-02 17-02-23](https://user-images.githubusercontent.com/5829014/46353755-a3637180-c665-11e8-9022-0428ec30d3ef.png)

**Comment by xmd5a2** [comment]
Main issue is fixed but issue regarding POI data is created https://github.com/osmandapp/Osmand/issues/6134
