### ISSUE TITLE
OSMR does not work properly

### ISSUE THREAD

**Issue by OpenSourceForEver** [osmandapp/Osmand#6081]
I have a problem using OSRM on Osmand because it does not follow the road and miss roundabouts. In addition sometimes when I want to calculate a route it  appears the message: " the route is emty". (Offline spain maps september 2018). OSRM on OSM site works properly. 
Examples:

![screenshot_2018-09-19-00-06-10-715_net osmand dev](https://user-images.githubusercontent.com/12786225/45923201-974a1800-bedf-11e8-933a-8102b291d102.png)
![screenshot_2018-09-19-00-06-28-368_net osmand dev](https://user-images.githubusercontent.com/12786225/45923203-a29d4380-bedf-11e8-9eb3-b2a73d724c74.png)

![screenshot_2018-09-19-00-07-45-518_net osmand dev](https://user-images.githubusercontent.com/12786225/45923205-b5b01380-bedf-11e8-8845-5184dbb5943b.png)
![screenshot_2018-09-19-00-07-53-000_net osmand dev](https://user-images.githubusercontent.com/12786225/45923207-be084e80-bedf-11e8-83c4-e42f1c93b3b3.png)

**Comment by blackmoon2** [comment]
I have the same problem for every nontrivial route since the last update (to OsmAnd+ 3.2.1, with updated maps) in germany. i also see sometimes the message "the route is empty" (translated from german).
Right now i can not use OsmAnd to navigate!

If i remember correctly, i used YOURS in previous versions of OsmAnd before and it worked well.
Please fix this problem and/or at least temporary allow YOURS again. #5791 even suggested other online routers (but i assume thats a lot of work to include them).

In this example there is NO direct connection:
![screenshot_20180928-220455_osmand](https://user-images.githubusercontent.com/43685645/46231799-8b41d880-c36d-11e8-9f98-9b1921edc201.jpg)

**Comment by vshcherb** [comment]
OSRM was disabled

**Comment by OpenSourceForEver** [comment]
If you close this issue OSRM will be forgotten.

**Comment by vshcherb** [comment]
OSRM is removed from OsmAnd as of today

**Comment by scaidermern** [comment]
OSRM can still be selected as routing provider and is still broken. So far there is no alternative online routing mechanism selectable. Thus routing over long distances is currently not possible with OsmAnd. Is there any plan to fix this? There are other online routers available such as GraphHopper, Valhalla and YOURS.

**Comment by WonderingDane** [comment]
This issue is still there. We really need an online router, since the offline router takes forever and doesn't even work at longer routes...

**Comment by OpenSourceForEver** [comment]
OSRM is still an option on Osmand Nightly 3.3.0# 23846d
