### ISSUE TITLE
cycle routing in case of bollard not correct

### ISSUE THREAD

**Issue by hvdwolf** [osmandapp/Osmand#6168]
Routing.xml
1.
Currently the value
`<select value="-1" t="barrier" v="bollard"/>`
is only used in the car profile.
Despite that I simply can't create a route with a bollard in place.

and 2.
Currently the routing.xml also "explains"
```
        There is no obligation to check against a value. The presence of a key can be enough to check against
        <select value="-1" t="bollard"/>
```
This is not correct. A bollard can have values yes/no or 1/0 for everything, car, cycle , pedestrian, etc.

So is it possible to remove the bug mentioned in 1. 
And could the distinction for the bollard mentioned in 2. be built in as well.

**Comment by vshcherb** [comment]
Please feel free to create pull-request, so it will be easier to understand and faster to process into the code.

**Comment by hvdwolf** [comment]
I'm willing to create a pull-request if it only comes to the routing.ml.

The issue is that the restriction <select value="-1" t="barrier" v="bollard"/> is only used in the car profile.
So what is the reason I can't create a route in cycle profile if the bollard is not even used there?
I think there is a bug in the code when calculating a route. I think that it is the bollard->value=-1 is somehow hard-coded through all profiles (or whatever the bug is)

**Comment by vshcherb** [comment]
nope, there is no hard as far as I know. Everything is profile driven so we the engine doesn't whether it is a car or pedestrian and everything should be present in routing.xml

**Comment by hvdwolf** [comment]
OK, I will work on it

**Comment by xmd5a2** [comment]
According to wiki, barrier=bollard implies access=no, foot=yes, and bicycle=yes, so car shouldn't go through it even in case of bollard=rising or bollard=removable because these bollard types actually needs a key. However, it may be worth to allow car routing through last mentioned bollard types when allow_private option is checked.
Regarding bicycle routing: I can't reproduce issue. In this example OsmAnd builds a route in cycle mode through 2 bollard.
![screenshot from 2019-01-22 10-41-59](https://user-images.githubusercontent.com/5829014/51519831-1d954d00-1e33-11e9-9c95-2863b2d5dd6d.png)

**Comment by scaidermern** [comment]
Allowing `bollard=removable` for car routing sounds like a bad idea. According to https://wiki.openstreetmap.org/wiki/Key:bollard:

> bollard=removable: A bollard which can be pulled out of the ground and removed to allow access, often **only by the person with the key**. Normally in place, and **not generally passable**.

**Comment by xmd5a2** [comment]
Doesn't that mean private access, what is the "Allow private access" option responsible for?

**Comment by scaidermern** [comment]
Yes, private access sounds fine. I missed this in your commit, sorry.
