### ISSUE TITLE
some cycle networks are missing (not visible)

### ISSUE THREAD

**Issue by pebogufi** [osmandapp/Osmand#6179]
if a way is a part of a relation (network=lcn) it is visible, ok.
if it is only tagged as lcn=yes, it is NOT visible.
This point (https://www.openstreetmap.org/node/3296684548) is splitting the two parts, in the north it is relation (visible), in the south only lcn=yes (not visible).
...
if a way is part of two cycle networks, the higher priority should be visible (icn > ncn > rcn > lcn).
version 3.2.0#26075

**Comment by Zahnstocher** [comment]
Thank you very much for this report!
I also noticed this bug very long time ago and forgot it.
I did some investigations and found out, that this commit broke the rendering of lcn=yes:
https://github.com/osmandapp/OsmAnd-resources/commit/6f91242b94faf99e1f9d076d57603cdc70f18bc8#diff-aa68e561bc04596c485828a0f39f460c
The information is still inside the obf, but the rendering is broken.
The problem seems to be tag="route" vs tag="route_bicycle".

**Comment by Zahnstocher** [comment]
2.2 (Nov 2015) is working:
https://github.com/osmandapp/OsmAnd-resources/blob/r2.2/rendering_styles/default.render.xml
Since 2.3 (Apr 2016), it is broken:
https://github.com/osmandapp/OsmAnd-resources/blob/r2.3/rendering_styles/default.render.xml
The mentioned commit (Feb 2016) is between these two versions.
