### ISSUE TITLE
Blue arrow indicating current position when not moving

### ISSUE THREAD

**Issue by alyonapinchuk** [osmandapp/OsmAnd#6207]
When standing still, the blue arrow is displayed instead of the regular blue dot that indicates the current position.
![image](https://user-images.githubusercontent.com/40493090/47300119-66ffb180-d624-11e8-9761-01b8280eb941.png)

**Comment by scaidermern** [comment]
Is this the same as reported in #5538?

**Comment by sonora** [comment]
Looks like the issue I had reported, except that on the devices where I observe it the arrow always points straight north after any gps noise has settled down.

**Comment by sonora** [comment]
It appears to me the issue is as follows: Some GPS chipsets seem to report bearing 0.0 at rest. (Maybe there are even others which simply keep reporting the last valid bearing from prior motion or fluctuation, not sure).

Our current code produces the correct location icon at rest only for those chipsets which indicate rest by reporting no bearing. Looks like we may have to add another condition, probably speed==0, or perhaps no speed reported. Needs some research to get this right for all chipsets.

**Comment by sonora** [comment]
I have managed to fix #5538 for all devices I have via https://github.com/osmandapp/Osmand/commit/c00394fc43b3b1119271ea99eaf56cfbf693887d. Turns out that some devices apparently do return hasBearing() at rest, with getBearing() = 0.0. (Valid bearings as per Android documentation are `(0.0, 360.0]`, hence a check for 0.0 makes sense here.) 

Can anybody please report if this also fixes #6207?

**Comment by sonora** [comment]
@vshcherb As I understand it now (but it seems not implemented uniformly on all devices): `hasBearing()` reports the general ability of the location provider to provide a bearing, but not necessarily if a particular location fix has a bearing associated with it. Locations without bearing may instead be reported with `getBearing() = 0.0`).

We have numerous other occurrences of `hasBearing()` in our code, I am not sure if all are aware of the above. Quite possibly adding an additional checks for `getBearing() = 0.0` where needed may fix some other circumstantial glitches.

**Comment by scaidermern** [comment]
> Locations without bearing may instead be reported with getBearing() = 0.0.

This is also documented at [Location#getBearing()](https://developer.android.com/reference/android/location/Location#getBearing()):

> If this location does not have a bearing then 0.0 is returned.

**Comment by sonora** [comment]
@scaidermern No, my fix is save, as valid (actual) bearings per documentation come from the range `(0.0, 360.0]`, i.e. _excluding_ 0.0 (true north apparently being reported as 360.0). What strikes me is that the majority of my older devices (hence I always mistakenly attributed this issue to larger screen sizes) seem to report no baring while at rest, while newer devices seem to report 0.0.

**Comment by scaidermern** [comment]
@sonora Oh, I missed that 0.0 is not part of the valid range. Thanks for the hint.
