### ISSUE TITLE
Feature request: Use proximity sensor to turn screen on

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/Osmand#6209]
I hope the following is technically possible in Android but I'm not sure about it. Usually the proximity sensor is used exactly the other way around,  i.e. for turning the screen off temporarily.

Sometimes it is hard or not possible to press the power button to switch the screen on. For example when riding a bicycle with the phone on a handlebar mount and the underground is bad. This is a typical use case where you want to save power and don't have the screen on all the time. In such situations it would be really great when you could use the proximity sensor to turn the screen on, i.e. just place your hand on the phone and it magically shows the map. Either for a fixed duration or until switched off again (maybe also by using the proximity sensor).

**Comment by Bushmills** [comment]
It is technically possible, but consider that turning onthe proximity sensor increases power consumption. You may want to use a different app for this. Automagic (for Android) is capable to do this. It also can detect whether OsmAnd is running in foreground, launch OsmAnd, turn on and off screen, detect whether device is powered, turn on and off proximity sensor, and much more which may be needed by your implementation plans.

**Comment by scaidermern** [comment]
> Seems to be technically possible:
https://f-droid.org/en/packages/com.jarsilio.android.waveup/

Indeed, nice. However using WaveUp as a third-party solution doesn't work since it only presents the unlock screen, not OsmAnd. It has to work similar to the "turn screen on" feature.

> It is technically possible, but consider that turning onthe proximity sensor increases power consumption. 

This is a good hint. However it might still be worth it as a configurable feature, especially given the use case described in my first comment.

> You may want to use a different app for this. Automagic (for Android) is capable to do this.
I couldn't / didn't want to test Automagic since it costs money. Having this feature directly integrated into OsmAnd would be really nice. Especially since the estimated effort should be comparable small. Especially since a similar feature, ""turn screen on", is already implemented.

**Comment by Bushmills** [comment]
Advantage of a  third party app is that that app can help any app to function the way you describe. Your suggested solution of adding such a feature to OsmAnd allows only one single app to operate that way. While your suggestion deals with one specific use case, using a third party app provides a more generic solution. I also prefer, for example, the printing subsystem to deal with my printer, and don't expect all kind of printer drivers in every possible app. Same with, say, screenshots - while some apps come with own screenshot capabilities,    the "system" provided screenshot feature works on about any screen. Turning screen on depending on sensors doesn't sound like a feature which should be on a per-app base. Tablets (without telephony) don't commonly have proximity sensors, as their main purpose seems to be to protect against unintended interaction when holding device to the ear - would you want additional code in the app for just a subset of devices, having no use for another subset?
Btw, costs of Automagic are considerably lower than costs of OsmAnd. There may be other alternatives which are free of charge - I mentioned Automagic because of that app I know that it provides the kind of support you're looking for, not requiring me to do any information search on that subject, before I learned that you exclude solutions requiring a one time payment.

**Comment by scaidermern** [comment]
> Advantage of a third party app is that that app can help any app to function the way you describe. Your suggested solution of adding such a feature to OsmAnd allows only one single app to operate that way. 

Right, this is the typical UNIX philosophy and the right approach for low-level functionality. However this is a completely different situation here and a typical user doesn't want to install 10 apps just in order to use a single app efficiently.

> Tablets (without telephony) don't commonly have proximity sensors, as their main purpose seems to be to protect against unintended interaction when holding device to the ear - would you want additional code in the app for just a subset of devices, having no use for another subset?

This is already the case today. Example: My device doesn't have a magnetic sensor, yet OsmAnd supports it because many devices do have such a sensor. The typical use-case for OsmAnd is a smartphone, not a tablet. Also most users won't mount a tablet on their bicycle. OsmAnd already has many nice features only needed by a subset of users (nautical map view, audio/video notes, OSM editing etc). This is one of OsmAnd's strengths in my opinion. Why are you against this one?

**Comment by macintoshee** [comment]
I can relate to that request. It could be very useful feature on motorcycle. Also, please keep in mind that not all users are technically minded and ready to use third party apps. Besides, third party apps always add complexity.

**Comment by dmpr0** [comment]
We are planning to add a proximity sensor as one of the options to Turn Screen On, I think it will be available soon, for testing.

**Comment by crimean** [comment]
Added by https://github.com/osmandapp/Osmand/commit/e9ae109ef8cf38b3cc2133b86787608c6d5ab3a1
