### ISSUE TITLE
Search: Oddity using postcode search

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#6240]
Here is another search oddity users in Germany report: Germany has 5 digit postcodes. When a user located at postcode say 12345 uses our postcode search to search for that very postcode, the following behavior is observed while typing:
- after typing '1', search reports no result can be found within 100 km
- same false negative with 12 and 123.
- but after having 1234 or 12345 the correct result(s) are/is suddenly displayed.
- Interesting: If with 1, 12, or123 you tap 'Increase search radius' on the message announcing there are no results within 100km, the results are suddenly displayed (winthin a few hundred meters)

**Comment by vshcherb** [comment]
I hope you don't see it when you navigate Address Search -> Postal code

This is part of algorithm to keep it fast, so the search is enabled only after 4 characters. Probably it is possible to change but it is not clear why if you still need to type 2 more chars.

**Comment by sonora** [comment]
Yes, all observations are for Address search -> Select Postcode.

**Comment by jfburke3** [comment]
@vshcherb This looks like one of those situations where you need to document the function and expected behavior.  I'm not criticizing how OsmAnd behaves--I just think that a formal description should be provided to users to that an expectation level is set.

Yes...this means that if you change the behavior, then the documentation needs to be updated.

(Side note:  something that seems to be the case is that you don't have a documentation manager.  Your app is sufficiently used worldwide that you need to consider getting someone to fill that role, and can update your web/doc information so that users know what to expect.  Yes, this person would need to have inside information about your future plans in order to be able to prepare docs when changes occur.)

**Comment by vshcherb** [comment]
Right now we are still stabilizing search, I hope we will be able to create a quick cheat list to validate whether we consider behavior A as a bug or as an improvement (which might not be implemented because it conflicts with other behavior B).
