### ISSUE TITLE
iPhone X screen format issues

### ISSUE THREAD

**Issue by krosola** [osmandapp/Osmand#6247]
Hello, 

I am a new user of the app and have become a huge fan, keep up the great work. 

I would like to point you to a usability issue on the iPhone X. Because of the new screen design I assume, the top portion of the graphics are not always rendering correctly. This causes a problem when interacting with UI elements in that area. The ones that give me a problem are the maps button and the back button. I have to repeatedly press them a lot of the time to get a response.
![img_0115](https://user-images.githubusercontent.com/6968255/47942342-e8dbbe80-def1-11e8-8adb-6acca1475bec.PNG)

Regards

edit: It turns out my aim is off and I think it could be because the UI elements I mentioned are positioned so high up, they occupy a reduced area for the user to touch.

**Comment by PaulStets** [comment]
@krosola Will be fixed with the next update. Here are some screenshots:
<img width="478" alt="screen shot 2018-11-22 at 11 20 51 am" src="https://user-images.githubusercontent.com/20681525/48893338-cda50480-ee48-11e8-813e-84d4da67f663.png">
<img width="478" alt="screen shot 2018-11-22 at 11 20 42 am" src="https://user-images.githubusercontent.com/20681525/48893339-cda50480-ee48-11e8-829e-77dd1efb6b74.png">
<img width="478" alt="screen shot 2018-11-22 at 11 20 20 am" src="https://user-images.githubusercontent.com/20681525/48893340-cda50480-ee48-11e8-93dd-216b4048c087.png">
