### ISSUE TITLE
Regression: Full hiking route names no longer shown at high zoom levels

### ISSUE THREAD

**Issue by kreuzschnabel** [osmandapp/OsmAnd#6311]
Hi, when Configure Map → Routes → Hiking symbol overlay was activated, OsmAnd used to show the entire route name in the labels at higher zoom levels. For instance, it was "Lim" at low zoom levels but "Limeswanderweg [Taunus]" at higher levels for relation #63178. 

This feature seems to have gone recently, now it’s "Lim" at any zoom level. I would like to have this switched back so I can look up the full name by zooming in. In many cases, and in case of multiple routes sharing a way, the abbreviations can be odd and non-informative. 

--ks

**Comment by njohnston** [comment]
I've just discovered this problem too since upgrading to 3.3.8 (but the issue existed since well before that release).

As @kreuzschnabel says, losing the ability to view the full name is a real problem. If you take the [Rheinburgenweg](http://www.openstreetmap.org/relation/2142171#map=18/50.34472/7.55970) which crosses Koblenz, Germany as an example, there's no way to see the full name now:

![route_name_missing](https://user-images.githubusercontent.com/638458/58496637-32337a00-8172-11e9-8aae-0a08c4cee5bf.png)

Before it looked like this:

![route_naming_issue](https://user-images.githubusercontent.com/638458/58496804-80487d80-8172-11e9-854b-884d2b643dce.jpg)

It's particularly bad in places with many hiking routes, near Budapest for example:

![budapest_hiking_routes](https://user-images.githubusercontent.com/638458/58496959-d3223500-8172-11e9-865c-2c8ddb9541bc.png)

@kreuzschnabel : the issue might get more attention if you give it a more descriptive name such as "Full hiking route names no longer shown at high zoom levels".

**Comment by sonora** [comment]
Does anybody know when this started? Possible culprits seem https://github.com/osmandapp/Osmand/issues/6844, or much older https://github.com/osmandapp/Osmand/issues/3816.

**Comment by njohnston** [comment]
@sonora : thanks for looking into this. I think #3816 is much too old. Before installing 3.3.8 I was using 3.1.5 and routes were labelled correctly.

#6844 seems more likely, but it only seems to be changing the rendering of cycling routes, not hiking ones. There isn't an exactly corresponding section in default.render.xml for hiking routes, but there are lots of references to `hikingRoutesOSMC` and associated formatting. I don't know enough about how this file works to see how to get the full names back.

**Comment by footils** [comment]
Are  you sure, #6844 is even active in your Osman-install? I don't think, it has found its way yet into 3.3.8: When my install updated itself to 3.3.8 I got a default.render.xml without the changes of #6844 again.

**Comment by njohnston** [comment]
Looks like this was a deliberate change by @xmd5a2 in https://github.com/osmandapp/OsmAnd-resources/commit/b4fcde8f.

I added this to my custom rendering file, but it didn't help:

```xml
  <text>
    <case minzoom="17" tag="route_hiking" value="" nameTag="hiking_route_name" textOrder="10"/>
    <case minzoom="17" tag="route_foot" value="" nameTag="foot_route_name" textOrder="10"/>
    <case minzoom="17" tag="route_walking" value="" nameTag="walking_route_name" textOrder="10"/>
  </text>
```

Can someone please let me know how I can change this back in my rendering file? :)

**Comment by kreuzschnabel** [comment]
This seems to have been solved recently (maybe by accident?). At least, Version 3.9.6 (Android) shows the route relations names again, bent along the path.

**Comment by vshcherb** [comment]
actually Fixed, so now they are displayed on the roads
