### ISSUE TITLE
Too early announcements

### ISSUE THREAD

**Issue by alyonapinchuk** [osmandapp/Osmand#6343]
start 48.59527 10.25990
end 48.62452 10.24303
https://www.openstreetmap.org/directions?engine=graphhopper_bicycle&route=48.5957%2C10.2600%3B48.6246%2C10.2429

The navigation announces "Turn right in 1 km in Margarete Steiff-Straße"
At this time I´ve been far from Giengen(Brenz).
In Giengen(Brenz) there are many streets on the right side of L1083.
The announcement is far too early!

**Comment by sonora** [comment]
I suppose it is simply the pre-announcement, something more like "After about 1km, ...", letting you know
 -  that no turn is coming up until then,
 - and that then it is to the right. As such, I would argue that it is useful, and most nav systems have it.

**Comment by romusprime** [comment]
unsubscribe

On Dec 9, 2018 3:45 AM, "Hardy" <notifications@github.com> wrote:

I suppose it is simply the pre-announcement, something more like "After
about 1km, ...", letting you know

   - that no turn is coming up until then,
   - and that then it is to the right. As such, I would argue that it is
   useful, and most nav systems have it.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/osmandapp/Osmand/issues/6343#issuecomment-445523676>,
or mute the thread

**Comment by vshcherb** [comment]
This is considered ok cause it gives an information after a long pause to get ready in 1 km (it is triggered only if you drove > 3 km straight)
