### ISSUE TITLE
Add support for countries default speed limits

### ISSUE THREAD

**Issue by Hellohat** [osmandapp/Osmand#6348]
Hello, (sorry if my english isn't very good) 
I use OSMand 3.2.7 (with an updated mal) and Android 8.1 
I add a value in the tag "speed limit" for some road in France with the app "Street Complete", 2 month ago. The key is "maxspeed:type=FR:rural" or "maxspeed:type=FR:urban" for the France. (FR is replace by another letters for others countries)

But, during the navigation, the application doesn't detect the speed limit (no alert, no speed limit display). I suppose the app doesn't recognise this key.

I thought it could be nice to add this :-)

**Comment by vshcherb** [comment]
Please add pull-request here https://github.com/osmandapp/OsmAnd-resources/blob/master/obf_creation/rendering_types.xml#L5756
Usually people use: "maxspeed=FR:rural"

**Comment by Hellohat** [comment]
That's done. Thank you :-)

**Comment by do1fmd** [comment]
The app "Streetcomplete" is using "maxspeed:type=FR:rural" instead of "maxspeed=FR:rural". [(See here)](https://github.com/westnordost/StreetComplete/issues/492#issuecomment-326080750)

More and more users will use the app Streetcomplete for easy tagging.
I think it would be great, if OSMAnd does recognise "maxspeed:type" and use it.

**Comment by Neuwessi11** [comment]
Is it possible to let OsmAnd recognize the maxspeed:type-tag? 
Maybe for Germany as well?

This would make tagging very much easier ...

Thanks!
