### ISSUE TITLE
Unnecessary "turn right" when road splits

### ISSUE THREAD

**Issue by HubMiner** [osmandapp/Osmand#6368]
Probably OsmAnd issue, reported in https://www.openstreetmap.org/note/1430795
I reproduced the issue with OsmAnd navigation.

When going through these three connected segments (https://www.openstreetmap.org/way/517272396 , https://www.openstreetmap.org/way/517272393 , https://www.openstreetmap.org/way/334361322 ), OsmAnd directs "turn right" and then "turn left".  The actual road has no turns, someone just mapped the fact the road is split.

**Comment by naoliv** [comment]
Probably it's saying to "turn right" because there is another way connected to the same node https://www.openstreetmap.org/way/517272394

ie, somebody coming from https://www.openstreetmap.org/way/334361322 can either "turn right" to https://www.openstreetmap.org/way/334361323 or "turn left" to https://www.openstreetmap.org/way/517272394

**Comment by vshcherb** [comment]
Has somebody any update about the issue fixed or not?

**Comment by HubMiner** [comment]
Looks like the issue is addressed, after map data was updated; thanks!
