### ISSUE TITLE
Change icons of Jehovah's Witnesses' places 

### ISSUE THREAD

**Issue by alyonapinchuk** [osmandapp/Osmand#6421]
Jehovah's Witnesses' places of worship (amenity=place_of_worship+religion=Christian+denomination=jehovahs_whitnes) are rendered with a cross (see the attached screenshot), but they do not use the cross anywhere, so the cross shouldn't be used to identify them. 
![image](https://user-images.githubusercontent.com/40493090/50726329-5edbec00-1114-11e9-9a01-ffe0c79ee5a3.png)

**Comment by pebogufi** [comment]
So what about to make a proposal to change the cross into what?

**Comment by Danysan1** [comment]
As far as I know Jehovah's witnesses do not venerate any religious symbol. 

Mapnik has solved this using the "man praying" symbol:
![screenshot_2019-01-06 gruppo di modifiche 65975132 openstreetmap](https://user-images.githubusercontent.com/8406735/50734683-e07a5b00-11a2-11e9-805e-20bdf1166a44.png)

Another option would be a literal "JW" symbol, since that's the symbol they attach on their buildings (example: https://commons.wikimedia.org/wiki/File:Jehovas_Vidners_St%C3%A6vnehal_i_Herlufmagle._jw.org_p%C3%A5_siden_af_Spisesalen.jpg )

**Comment by Adamant36** [comment]
They don't really knell at an alter either. I was semi involved in an issue on the Mapnik style (its actually called OpenStreetMap-Carto) to change the symbol to "JW" but it never got off the ground. While I cant remember why now, for anyone interested here's a link to it. 

https://github.com/gravitystorm/openstreetmap-carto/issues/3282
