### ISSUE TITLE
Dutch voice assist incorrect

### ISSUE THREAD

**Issue by jeroen-80** [osmandapp/OsmAnd#6479]
In Dutch, number are pronounced like: 428 = 4 hundred 8 and 20 (vierhonderd acht en twintig). Current voice assist pronounced numbers as the literally translated Dutch number (vierhonders twintig acht) which is incorrect (and sounds pretty weird).

In general I'd like to suggest to use hundreds and tens of meters / yards only for voice assist, no valuable info in single meters / yards and it takes longer to pronounce.

**Comment by Ernst-47** [comment]
Apart from the odd way how numbers are formed I also observe that in the sentence “U hebt uw bestemming bereikt” the word “bereikt” is not pronounced.
This can be simulated by running test line 7.3 in "Test voice prompts"  in the OSMAND Development mode.
7.3 test line indicates 360m. Voice return is 360m. That is OK. But the last word (bereikt) is missing.

**Comment by vshcherb** [comment]
I just tested 7.3 -and arrive at your intermediate destination and 7.4 - bereikt is pronounced in both of the cases. At least with 3.4 version (beta available)

**Comment by sonora** [comment]
Just going through some old voice issues and suspect that this one can be closed?


I think that the issue of missing rounding has been fixed a long time ago.

And should there still be an issue of e.g. distances being pronounced digit by digit, that must be fixed by an update to the TTS engine used, or simply use a better one?

**Comment by Ernst-47** [comment]
Thanks. Yes consider as closed.
Grs.,

Ernst

**Comment by nkoole** [comment]
Thank you for your response.Didn't check. Using the english voice anyway.So no problem for me.Greetings,NicoVerzonden vanaf Samsung-tablet.
-------- Oorspronkelijk bericht --------Van: Hardy <notifications@github.com> Datum: 08-11-20  08:43  (GMT+01:00) Aan: osmandapp/OsmAnd <OsmAnd@noreply.github.com> Cc: nkoole <nkoole@ziggo.nl>, Manual <manual@noreply.github.com> Onderwerp: Re: [osmandapp/OsmAnd] Dutch voice assist incorrect (#6479) 
Just going through some old voice issues and suspect that this one can be closed?
I think that the issue of missing rounding has been fixed a long time ago.
And should there still be an issue of e.g. distances being pronounced digit by digit, that must be fixed by an update to the TTS engine used, or simply use a better one?

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/osmandapp/OsmAnd/issues/6479#issuecomment-723542105",
"url": "https://github.com/osmandapp/OsmAnd/issues/6479#issuecomment-723542105",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
