### ISSUE TITLE
Navigation Issue with Bicycle: Routing through a Mall

### ISSUE THREAD

**Issue by oxxm** [osmandapp/Osmand#6483]
From: 48.58591, 7.74089
To: 48.58694, 7.74302

Osmand 3.2.7 routes a bicycle through a mall with `access = destination` and `highway = footway`. 

Openstreetmap does the same by the way. Is this a tagging issue?

**Comment by scaidermern** [comment]
> From: 48.58591, 7.74089
> To: 48.58694, 7.74302
> 
> Osmand 3.2.7 routes a bicycle through a mall with `access = destination` and `highway = footway`.
> 
> Openstreetmap does the same by the way. Is this a tagging issue?

No, GraphHopper doesn't route through the mall: https://www.openstreetmap.org/directions?engine=graphhopper_bicycle&route=48.58581%2C7.74083%3B48.58678%2C7.74305

**Comment by scaidermern** [comment]
Oh. But this is not a tagging error but a different error in the map data. The pedestrian area https://www.openstreetmap.org/way/32402744 is not connected to the surrounding roads. So GraphHopper (and possibly OsmAnd, too) route along footways which are otherwise forbidden for them. The only other option is to calculate no route at all.

Does OsmAnd route through the mall if you set start and the end point on a valid road?

**Comment by oxxm** [comment]
If the destination is the bike stand at: 48.58707, 7.74340 it routes through the mall. 

Otherwise if the destination is on a valid road, few meters next to the bike stand, it routes through normal roads, regardless of the starting point. 

So it has nothing to do with osmand, like you suggested. Thank you for the clarification!

**Comment by oxxm** [comment]
Maybe as a feature request, the ability to handle such cases in the future?

**Comment by vshcherb** [comment]
We don't forbid destination/private to suggest a bad route at least cause there are some situations when people have permission and they would like to see that navigation. So it is not possible to say whether it is a valid case or not in general.
