### ISSUE TITLE
Wrong routing

### ISSUE THREAD

**Issue by petersohn** [osmandapp/Osmand#6530]
Using the offline routing, the following route is calculated wrong.

https://www.openstreetmap.org/directions?engine=graphhopper_car&route=48.13079%2C16.33492%3B48.12317%2C16.43369#map=14/48.1262/16.3843

![screenshot_20190210-161757_osmand](https://user-images.githubusercontent.com/2822847/52535543-f05ffe80-2d4f-11e9-9ecc-c754215f204d.jpg)

It looks like it cannot take the correct way at this intersection:

https://www.openstreetmap.org/#map=18/48.13031/16.35175

![screenshot_20190210-161927_osmand](https://user-images.githubusercontent.com/2822847/52535550-0241a180-2d50-11e9-9918-5163e4423358.jpg)

**OsmAnd version:** OsmAnd+ 3.2.7.

**Map version:** Austria 1 Jan 2019.

**Comment by Zahnstocher** [comment]
barrier=height_restrictor issue:
https://www.openstreetmap.org/node/4888287242
https://www.openstreetmap.org/node/4888287241
It is already fixed:
https://github.com/osmandapp/OsmAnd-resources/commit/a78c3796550ee8ec34b81c2b753c2d65b975b056
Next OsmAnd release should contain this fix.

**Comment by aceman444** [comment]
That 'fix' is completely wrong, it will now not allow passing under a height_restrictor ever (not only with penalty).

**Comment by Zahnstocher** [comment]
@aceman444 
It is not completely wrong, because the default access for barrier is "yes" in car routing.
But you are right for "short way" setting, because in this case, the default is "no".
This is illogical.

**Comment by aceman444** [comment]
It is illogical because https://github.com/osmandapp/OsmAnd-resources/commit/a78c3796550ee8ec34b81c2b753c2d65b975b056 was partially incorrect, instead of completely incorrect (removing both occurrences) :)

**Comment by vshcherb** [comment]
As this issue is fixed with height_restrictor, the issue will be closed

**Comment by cpina** [comment]
If the majority of routing software considers unknown barriers not passable, as a Osmand user I'd like to be able to decide how I consider them. Could this be done via a setting?
Thanks!

**Comment by aceman444** [comment]
> [@aceman444](https://github.com/aceman444) It is not completely wrong, because the default access for barrier is "yes" in car routing.

And that is the problem. Default access is yes on any unknown barrier only after that commit and only in OsmAnd. The wiki says default access is no (https://wiki.openstreetmap.org/wiki/Barriers#Routing) so people tend to tag like that. This caused problems in OsmAnd after this "fix" and will cause countless ones in the future.

Even if the wiki did not say it, a barrier blocks movement. You must know exactly what a barrier is to decide whether you can pass it with a car, a bike, a bus, a tank or by foot. For each barrier the answer for these transport types may be different. You cannot decide this for an unknown barrier. That's why OsmAnd maintains a list of know passable barriers.

**Comment by aceman444** [comment]
> If the majority of routing software considers unknown barriers not passable, as a Osmand user I'd like to be able to decide how I consider them. Could this be done via a setting? Thanks!

Yes I think this would be doable, I just don't know if OsmAnd developers would want this option be exposed.
