### ISSUE TITLE
Routing ignores Interstate in favor of parallel lower-priority highway

### ISSUE THREAD

**Issue by jfburke3** [osmandapp/Osmand#6640]
What version of OsmAnd are you using, on what device and Android/iOS version?

OsmAnd night build 3.3.0#26851 dated 2019-02-27 on Samsung Galaxy S9+, Android 9.0

OsmAnd night build 3.3.0#26926 dated 2019-03-08 on Samsung Galaxy S7 Edge, Android 8.0

Do you use the offline maps offered within the OsmAnd app for download, or online (tile / raster) maps?

Your offline maps

If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs, and its edition date.

US Mississippi dated Jan 31, 2019 (and yes, I'll try the February map when it's available)

__*In case of wrong routing:*__

Tell us whether you have used OsmAnd's in-app offline routing, or any online routing provider like YOURS, OpenRouteService or OSRM.

OsmAnd in-app routing 

What routing profile is chosen in OsmAnd app? (car, bike, pedestrian, fastest or shortest)

Car profile, fastest, all "avoid" options disabled 

Please specify as exactly as possible the start and end point of your route by telling us city name and street name so that we can find it via in-app address search easily. Also, a permalink from openstreetmap.org can be helpful.

Start point: Lincoln Road Baptist Church, Hattiesburg 
End point: Lamar County Chancery Court, Purvis 
(Entering this from my phone, I'll get OSM links when I'm at a computer) 

Tell us your expected routing, and how OsmAnd routes, or add screenshots here.

I'd expect the route to go north on 40th Avenue, west on Hardy Street, then south on I 59 to highway 589. That's the shortest and fastest route to I 59 and to downtown Purvis. 

Instead , it routes me a longer way on lower-priority roads to US 11, and down that highway to Purvis.

![screenshot_20190308-092302_osmand](https://user-images.githubusercontent.com/11140831/54044933-d1f5f300-4195-11e9-9875-057b41074e7c.jpg)

![screenshot_20190308-102032_osmand](https://user-images.githubusercontent.com/11140831/54044948-dde1b500-4195-11e9-89a8-458563f350c4.jpg)

**Comment by jfburke3** [comment]
I should add that the generated route is perfectly valid, and maybe y'all want it to do something like that when the two possibilities are so similar (the generated route is shorter and only a couple of minutes longer than taking the freeway). If so, that's fine. I just thought it was odd, and wanted to bring it up in case it wasn't desired.

**Comment by vshcherb** [comment]
Primary: 1123.4904 seconds
Motorway: 653.27136 + 610.00024 seconds = 1263 seconds

So primary is somehow faster by route calculation

**Comment by vshcherb** [comment]
70 mph (roughly 110 kmh) is a limit for motorway and for primary is 45 mph (75 kmh).  I guess we need to introduce prefer motorway option or multiply priority of motorway to a slighly higher number.
So far I didn't find a parameter which changes the route

**Comment by jfburke3** [comment]
If you think that the generated route is appropriate, then maybe this can be closed?  I only opened it because it appeared to me that the selected route was less optimal than taking the Interstate.  However...if it looks good to you, then I guess it's ok.  (Side note:  I kinda would like a "prefer motorway" option, because there are times when I want to force that.)

I will note that there's nothing particularly wrong with the route that was generated along US 11.  It just isn't what I expected, nor was it the "normal" route.  But it works.

**Comment by jfburke3** [comment]
BTW, most of US 11 has a 55 mph speed limit...not sure why you thought 45?

**Comment by jfburke3** [comment]
I will note that MS 589 had no speed limit data between the Interstate and US 11, and so the lower default limit in OsmAnd might have been a factor. 

I have since added speed limit info from a survey.

**Comment by sonora** [comment]
From my testing over the last few years with our routing parameterization, I would not make a change due to what I see reported here. There are somtimes situations where it is a 'close call', and often things depend a bit on 'ground truth psychology' and driver preference. In these cases you will in practice simply ignore the proposed route for a moment (like here drive towards the Interstate), and the route will update momentarily according to your preference. (If not, it was not a close call... :) ).

**Comment by aceman444** [comment]
There is also an artificial penalty from switching from motorway to lower-level roads to avoid too much switching of roads in these 'close call' scenarios on long routes. So in this case if the roads are more or less the same, staying on the secondary/primary road seems better to OsmAnd then entering motorway and then switching back to primary.

@sonora thanks for the stance here. But sadly vshcherb is used to make random tweaks to the constants in the routing.xml file to "fix" a specific scenario (and inadvertently break others) like this one. There seems to be no test suite and a global concept on how the routing should work and how to fine-tune it. Like here he mentions to introduce a "prefer motorways" options, possibly forgetting there already was one in OsmAnd in the past... There are multiple cases of this "going in circles" development in OsmAnd.

**Comment by aceman444** [comment]
> BTW, most of US 11 has a 55 mph speed limit...not sure why you thought 45?

Because if a road does not have a maxspeed= tag set in OSM OsmAnd assumes some default average speed based on the class of the road. You can see in https://github.com/osmandapp/OsmAnd-resources/blob/master/routing/routing.xml that for primary it is actually 65kph. Which is applied to ALL countries in the world so can't actually match any particular country and is usually wrong. Then "close call" cases like this one can happen as the local situation differs than what OsmAnd estimates.
Sadly OsmAnd devs so far always rejected to create a per-country table of defaults like maxspeeds, road access, etc.
You can still make a customized copy of the routing.xml file and put it into the OsmAnd folder, in which way you can achieve much better routing and time estimation tailored to your region.

**Comment by vshcherb** [comment]
@aceman444 
we support the tagging scheme "ru:rural", "nl:motorway" but it is a manual list and it is not based on the region. We can theoretically support it per country based:
a) it is quite a lot of manual work to list & maintain the list
b) it might increase the map data cause we need to inject maxspeed tag for each road.
c) it won't help the countries which have a good mapping already

Pros/cons are not clear, in case somebody would like to imply for a specific country like "us_*", I think we can proceed faster with implementation rather than preparing maxspeed for all possible countries.

**Comment by aceman444** [comment]
"<country>:zone" schemes are no help here as in that case mappers have already checked the road and put the explicit maxspeed on the osm way. We however need to solve roads that don't any a maxspeed set in OSM. In that case the country's legal max speed should be used.
OSM even discourages to put explicit maxspeed (or any other tag) on every object in the database if that value is the default for the country.
So it is up to OsmAnd to apply those defaults automatically.

a) you only need to assemble the list once and it will only change if laws in some country exist. Users would file issues in such a case.
b) you do not need to put it in the obf file, it can be in OsmAnd runtime. But yes, you would then need to determine at runtime in which country a particular OSM way exists. It would be better to decide that once at .obf creation time and be done with it. This is similar to the default_language tags I have described in another issue filed.
c) depends on what is good mapping. Having an explicit maxspeed=50 on every road in the country can be considered wrong and incorrect by OSM rules.
