### ISSUE TITLE
Hindi TTS - nonsensical sentences

### ISSUE THREAD

**Issue by contrapunctus-1** [osmandapp/Osmand#6642]
I tried out the Hindi TTS yesterday and discovered that the sentences make no grammatical sense - it seems as if English sentences are translated word by word to Hindi 
😅

As a native speaker, I'd be happy to help fix this if directed to the right files. (Is this affected by the translations on Weblate?)

OsmAnd v3.2.7 from F-Droid

**Comment by sonora** [comment]
No,this is independent of Weblate, you would have to make a pull request improving this file:
https://github.com/osmandapp/OsmAnd-resources/blob/master/voice/hi/hi_tts.js

When you look at the structure, section `populateDictionary` contains the vocabulary, and the subsequent sections the word order and grammar.

For correct pronunciation, this is not controlled via OsmAnd: Please make sure your device has a TTS engine installed capable of pronouncing Hindi, and also make sure it is set to Hindi in its own (usually device) language settings.

**Comment by contrapunctus-1** [comment]
Thanks sonora! I've begun poking around the file and will hopefully have a PR Soon™. That said, is it not possible to move TTS strings to Weblate as well? It would make the task a lot more accessible for nontechnical users.

**Comment by sonora** [comment]
One hint: You can always  test your TTS file locally yourself as I have explained here https://github.com/osmandapp/Osmand/issues/6159#issuecomment-432028892, so for the development you are independent of a pull request.

The vocabulary contained in the tts js file is not on Weblate because it would not help much. The majority of the effort is defining the right word order, declinations, cases, plural versions, and all other grammar. Separating the vocabulary to another tool would be counter productive, the vocabulary and grammar portions need to be looked at together.

We have some time ago changed our tts definition files from PROLOG to js to reach a broader number of possible contributors. There is no economic idea beyond that for a completely 'non-technical' dev UI for this. Fortunately, we keep this rather static, so once a language is done it is done.

In order to generate a starting point for contributors, I had once provided some rudimentary language files simply based on dictionary translations and without specific grammar. Maybe the Hindi file you came across is one such example, and I hope you will be able to improve it! :)

In general, when generating a new language, it makes sense to start from, or at least look at, existing language files from languages with similar structure or grammar, it will greatly simplify to see how things are already solved.

**Comment by sonora** [comment]
I am compiling a short Technical Article on the subject, see here: http://osmand.net/help-online/technical-articles#Creating%20a%20New%20TTS%20Voice%20Language.

**Comment by contrapunctus-1** [comment]
Thanks for the detailed response, sonora. I've made a fork with some fixes, with more to come.

In the meantime, I happened to come across Project Fluent. Could this be a better solution for OsmAnd's TTS (and maybe program) translations? https://projectfluent.org/
