### ISSUE TITLE
Relation not removed OSM Live

### ISSUE THREAD

**Issue by mahdi1234** [osmandapp/OsmAnd#6743]
Osmand~ 3.3.6 from f-droid.

Czech republic maps March 2018 + latest OSM live.

I have updated yesterday relation for "Red" toursit track, by putting it on new path and removed from obsolete one.

After Live update app still shows the old one as well, so perhaps some issue with removed relation?

Relation - https://www.openstreetmap.org/relation/114334

Following ways are new path
https://www.openstreetmap.org/way/78140131
https://www.openstreetmap.org/way/229101731
https://www.openstreetmap.org/way/578384639

These ways have not relation anymore
https://www.openstreetmap.org/way/78140140
https://www.openstreetmap.org/way/78140120
https://www.openstreetmap.org/way/78140119

Both are shown in the app
![Relation](https://user-images.githubusercontent.com/1097047/54952350-1202f700-4f46-11e9-8036-fb69e0fc183f.png)

**Comment by aceman444** [comment]
Yes, OsmAnd Live isn't perfect and old data may still show in some cases.

**Comment by vshcherb** [comment]
Dev comment:
Yes, there are issues with removed relation from ways.
In order to create a map we retrieve old and new state. Because only relation has changed so we retrieve new relation (suppose it's empty) and  old relation with old ways. So we generate 2 files: old with road that has all flags and new (that doesn't have that road at all).

Obviously we can't remove the road because we just didn't retrieve to generate diff that's this change is omitted and we don't update tags on the road that are populated from relation.

**Comment by vshcherb** [comment]
As of today it is not clear how to write such overpass query to retrieve it.

**Comment by MadWasp79** [comment]
https://github.com/osmandapp/OsmAnd-tools/pull/359/files

**Comment by vshcherb** [comment]
This is turned to be very difficult issue to fix cause our maps don't have such "entity" as relation, so we need to produce correct roads. The problem that we can't track properly road/relation differences in live, hopefully to find solution later.

**Comment by ivanPyrohivskyi** [comment]
Problem fixed until April 19 2023.
Live updates will consist of nodes and ways if one of relation that taken these nodes and/or ways was added, modified or deleted.
