### ISSUE TITLE
[Bug] OsmAnd 3.3.7 locks the external sdcard1

### ISSUE THREAD

**Issue by Thunichgud** [osmandapp/Osmand#6784]
All my apps works usually with the external sdcard1 without any problems - also OsmAnd+ 3.3.6 and previous versions. After update to OsmAnd+ 3.3.7 it worked normally. But after a following download of some map-, wiki- and srtm- files, the next start of OsmAnd begun with the start screen of a first installation. Now it wasn't possible to change to the external sdcard1 where the maps of OsmAnd are stored. I got the message, that the external sdcard1 is locked. Osmand freezes. After closing OsmAnd, no one of my other apps can read or write to the external sdcard1. It is locked for all apps. After rebooting the device, the sdcard1 isn't locked. Every app can again read and write to it. But after start of OsmAnd, the sdcard1 is totally locked again and so on, and so on.
Reinstalling of OsmAnd 3.3.7 didn't change anything.

OsmAnd+ 3.3.7
Device: Samsung Galaxy S4 (GT-I9505)
OS: CyanogenMod 11.1 (Android 5.1.1)
Rooted
Firewall: NetGuard 2.229
Display: 1080 x 1920, 480 ppi
MicroSD 127 GB

**Comment by sonora** [comment]
If you ask me, this is a typical 'corrupt SD card' issue, OsmAnd map files have a comparatively high risk of being affected due to their above average file size. Please test another SD card, or at least back it up, format it, then  copy your files back. Sometines this process reveals the issue,  and sometimes it even fixes it.

**Comment by Thunichgud** [comment]
No, it is not a typical 'corrupt SD card' issue. Here is my addendum:
1. The issue always happens directly after a map indexing. 
2. Yet I stored the maps and other data in /storage/sdcard1/osmand (a short userfriendly path) and had never problems with this path. Since OsmAnd 3.3.7 this path don't works. Finally I moved all data to the very ugly default path /storage/sdcard1/Android/data/net.osmand.plus/files. This path now works but it is not userfriendly. I still think this issue is a bug of OsmAnd 3.3.7.

**Comment by bugzillus** [comment]
I second both issues: severe trouble with SD card use and annoyance that custom directories cannot be used any more.

Osmand 3.3.5 with maps on SD card is extremely buggy and close to unusable:

- Upgrading an existing 3.2.7 installation to 3.3.5 on Lineage 14.1
- offline usage, manually downloaded maps on external SD card (FAT32)

Severe and inconsistent failures which could not be solved by complete re-installation:

1. Annoying: On installation, place to choose for map storage seems incorrectly named: "external storage" instead of internal storage, "device storage" listed separately and shown with the same amount of free storage as internal storage, but without external storage (SD card)

2. Annoying: On installation, message "no maps found", but with click on "choose", all maps are shown and being active on the local maps tab. Indefinite loop of action circle.

3. With only two map files, things seemed ok, but after installing arond 10-15 map files and the large word basemap, no regular usage possible:

4. Sometimes extremely slow (dozens of seconds) map drawing

5. Sometimes white screen on any scale larger than e. g. "50 km", above "50 km" scale always stays on "100 km", no matter how often "zoom out" is clicked, no world view possible, although world basemap is installed

6. Often, searching of a city within installed maps hardly works. If view is on country scale (100 km or 200 km), search always being interrupted with "no results within 10 km". No matter how often is being clicked on "increase search radius", nothing is found at all.

7. Sometimes no search results, although the map already shows the current city: On typing the city name, the city name is shown on first results, but immediately overlaid by the message "nothing found, increase search radius" which does not help but repeats that behaviour.

8. Sometimes, after re-opening the map admin menu or disabling/enabling maps, message "index of ...obf is not supported" is shown for many/most maps, although these maps have been used before and no file corruption is known.

9. Sometimes, message "list of available regions being loaded" stays, although the device is offline.

10. Sometimes, most of Europe is drawn blue like completely being under water.

11. Once: When checking the maps menu, all local maps were shown present and active. After disabling them and trying to enable only a few, messages like "...obf: data format not recognized" are shown. After restarting Osmand, Osmand deleted all maps (around 10 GB) on the SD card but retained all other files and subdirs in the files directory.

12. Once: SD card only being used by Osmand, but appears locked/broken to Android. There's no hint so far that the SD card is damaged, it's a new brand-name class10 SD card (32G).

What a mess.

**Comment by Thunichgud** [comment]
sonora was right. It was a corrupt sdcard issue. I backed up the files from the card, formatted it and copied back the files to the sdcard. Now my short path /storage/sdcard1/osmand on the external card works again and it don't gets locked again.
I close this issue.

**Comment by Seegras** [comment]
Same issue here that bugzillus reports.

After re-opening OsmAnd, it reports "index of ...obf is not supported", and can't display the maps.

Going to "Download Maps" The maps show as not downloaded under "All Downloads", but still appear as present in "Local".

No hint SD card is damaged.
