### ISSUE TITLE
Improvement: add search and render parking spaces for disabled persons

### ISSUE THREAD

**Issue by pyrog** [osmandapp/Osmand#6805]
Could you render parking and parking space for disabled ?
And add a search for them ?

According to [wiki](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dparking_space), they are tagged with:
 * `amenity=parking_space `
* `parking_space=disabled`

According to [TagInfo](https://taginfo.openstreetmap.org/search?q=parking_space%3Ddisabled), there is 9 883 parking spaces for disabled.

**Comment by scaidermern** [comment]
Should this also include `amenity=parking` with a `capacity:disabled` value of `yes` or `>0`?

**Comment by pyrog** [comment]
No for `amenity=parking`. If parking spaces are grouped together, they used a site relation tagged with `type=site` + `site=parking`.

In France, we have a lot of parking spaces "alone".

But the usage is not clear, see http://overpass-turbo.eu/s/HRy

* `amenity=parking_space`
* `capacity:disabled=*`
* `wheelchair=*`

or

* `amenity=parking_space`
* `wheelchair=*`

or

* `amenity=parking_space`
* `parking_space=disabled`

…

* `amenity=parking_space`
* `capacity:disabled=*`
* `parking_space=disabled`
* `wheelchair=*`

Bad tagging: http://overpass-turbo.eu/s/HRx
(Must use `amenity=parking`)
- `amenity=parking_space`
- `capacity=6`
- `fee=yes`
- `access=yes`
- `parking=surface`

**Comment by alesarrett** [comment]
I also strongly support this request for improvement.
More specifically I'd like to have the possibility to set up a custom filter to visualize on OsmAnd parking spaces for disabled persons. It is really important because people with disabilities so far don't have the possibility to recognise on the map and be directed to specific parking places reserved for them.

I also add other options that I collected about different ways of mapping parking spaces for disabled persons:

- `parking_space=disabled`

or

- `amenity=parking_space`
- `access:disabled=*`

or

- `amenity=parking_space`
- `disabled=*`

All of them could be seen here: http://overpass-turbo.eu/s/Ooq

**Comment by xmd5a2** [comment]
Fixed by https://github.com/osmandapp/OsmAnd-resources/commit/08e7e53afab268df1ea2d14d5b99508530359431 https://github.com/osmandapp/OsmAnd-resources/commit/ea88e128947c29d2247d168934c464ac95bc93aa https://github.com/osmandapp/OsmAnd-resources/commit/63f692de2991deb4ce309f733b8e5291c6585cf9
