### ISSUE TITLE
OsmAnd does not use squares for pedestrian navigation

### ISSUE THREAD

**Issue by katerynakocherhina** [osmandapp/Osmand#6956]
Rue Moulay Ismail, Marrakesch/Morocco:
Standort: geo:31.625765,-7.9892926?z=19 
https://osmand.net/go?lat=31.625765&lon=-7.9892926&z=19
![image](https://user-images.githubusercontent.com/50198677/58017998-50620000-7b0a-11e9-8599-40e976023f01.png)

**Comment by scaidermern** [comment]
This should be fixed in the map data. The [pedestrian area](https://www.openstreetmap.org/relation/5991892) needs artificial cross-connections since most current routers don't support routing across areas. Otherwise they only route along the area boundary which is often longer than routing across the area.

**Comment by vshcherb** [comment]
OsmAnd supports navigation through area at least using perimeter, I guess it is a mapping issue in case lines are not connected properly.
