### ISSUE TITLE
OsmAnd Live donation

### ISSUE THREAD

**Issue by katerynakocherhina** [osmandapp/Osmand#7052]
There are differences between paid amounts and displayed for the contributors to OSM on the online charts.

**Comment by vshcherb** [comment]
I would like to make that issue public in order to start investigation. 
Indeed on our websites it states:
"Donate without any extra charges:
If you want to donate without any extra charges and directly to OSM contributors please transfer funds to this Bitcoin address
1GRgEnKujorJJ9VBa76g8cp3sfoWtQqSs4". 

The problem is that address was mistakenly reused in multiple different ways i.e. it was used https://github.com/osmandapp/Osmand/issues/3227 as OsmAnd donation address, that address was even existing before OsmAnd Live started and it is used on F-Droid where it is mentioned as donation address to OsmAnd itself not to OsmAnd Live program. 

So, my summary that we are definitely going to change address or may be create a new address for OsmAnd Live Program donation where the address will not mix at all with OsmAnd contribution address. 

Retrospectively, I'm going to collect all possible donations via that address and adjust some them with extra round ups & commissions. Historically we always add up to total payout number around 5-10% extra and to payout commissions, in the beginning it was sometimes up to 30%. 
So, in case donations to that address didn't exceed on average 10% of all payouts then whole state will be cleared now.

**Comment by vshcherb** [comment]
I see some really strange donations they were probably dedicated to OsmAnd Live Program itself. Some operations were totally internal and are allocated for different purposes to support future OsmAnd Live Program:
I would need to collection information somehow of the purposes of these transactions:
Will prepare a list below...

**Comment by vshcherb** [comment]
I made a quick revision and there is 1 quite large outstanding transaction :
https://www.blockchain.com/btc/tx/4f4e0781061007be993eb31152c117d76f98f299d090b6dad10954e211b62123.

All other transactions for 2018-2019 didn't exceed our monthly costs to acquire bitcoins, fees and the sum we add on top always (which is at least +10% to the calculated ticket). 

I will wait sometime to get some information of purpose 4f4e0781061007be993eb31152c117d76f98f299d090b6dad10954e211b62123. In case it won't be clarified till next payout (5th of July) I would consider it to split 50/50 (50% to OsmAnd Live payouts, 50% to OsmAnd). 

P.S. I will definitely create different address to track purpose clearly.

**Comment by vshcherb** [comment]
https://github.com/osmandapp/osmandapp.github.io/commit/e6226aee2554c28e68043f0d152a0750da4177b6

**Comment by vshcherb** [comment]
To be even more clear till that transaction and the internal transaction the balance was at
1GRgEnKujorJJ9VBa76g8cp3sfoWtQqSs4
June 14 2019 @ 5:12 PM
0.17442379 BTC

**Comment by vshcherb** [comment]
I don't see any reply so we are going to proceed with described plan

**Comment by vshcherb** [comment]
Final analysis as of 29 of June 2019.
Since 1st of January of 2017 there were 0.3839 BTC donations made to 1GRgEnKujorJJ9VBa76g8cp3sfoWtQqSs4.
Since 1st of January of 2017 there was 0.2255 BTC overpaid.

Taking into account formula 50/50, there is a difference 0.3839 / 2 - 0.2255 = -0.03355 (BTC) to be paid to OsmAnd Team. So here is the balance is accounted.

Overpaid situation every month now is visible on https://osmand.net/osm_live (recipients tab).

For June 2019 the donation of 2 BTC will be split into 2 parts: 1 BTC to OsmAnd Team and 1 BTC to OsmAnd Live Program.
