### ISSUE TITLE
Improve POI details when multiple POI categories are present

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/Osmand#7067]
Some objects in OSM are tagged with multiple main POI categories such as `amenity=restaurant` and `tourism=hotel`. Currently OsmAnd shows only one of these categories but not all of them.

Examples:
https://www.openstreetmap.org/node/1668883397 has  tags `amenity=restaurant` and `tourism=hotel` but in the info menu OsmAnd only shows "Restaurant":
![photo_2019-06-20_15-07-58](https://user-images.githubusercontent.com/1040784/59851612-59dec200-936d-11e9-9a37-7b3a90a4c020.jpg)

https://www.openstreetmap.org/node/297468326 has tags `amenity=post_office` and `shop=stationery` but in the info menu OsmAnd only shows "Store":
![photo_2019-06-20_15-08-02](https://user-images.githubusercontent.com/1040784/59852331-e6d64b00-936e-11e9-8dc1-8160b4ad00fd.jpg)

It would be nice to list all major POI categories in the info menu, for example instead of "Restaurant" simply "Restaurant, Hotel".

**Comment by vshcherb** [comment]
Unfortunately food and accomodation belong to different category, so they are treated as differed POIs. 
It is unlikely to change cause it requires huge refactoring on data format. 
So, it is possible to have special tag that restaurant has accommodation and accommodation has restaurant though it still be confusing rather than have 2 different amenities.
