### ISSUE TITLE
Ouverture d'un fichier contenant une trace GPX depuis une application

### ISSUE THREAD

**Issue by BorisRAOULT** [osmandapp/Osmand#7075]
Je travaille sur une application qui utilise OsmAnd sous Andoid pour afficher un itinéraire. Mon application génère un fichier GPX et ouvre ce fichier avec l’application OsmAnd.
Lorsque je génère un premier fichier et que je demande l’ouverture, l’itinéraire s’affiche correctement sur Osmand.
Ensuite, je reviens vers mon application avec la touche retour.
Le problème se situe lorsque je génère un deuxième fichier et que je l’ouvre. La nouvelle trace gpx s’affiche correctement mais la première est toujours présente.
Existe-t-il un moyen de ne pas afficher les anciennes traces gpx lors de l’ouverture d’un nouveau fichier sans faire de manipulation dans le menu deOsmAnd ?

**Comment by tuxayo** [comment]
Hi 🙂
Can you write it in English or do you need help with the translation? I can help 🙂

**Comment by vshcherb** [comment]
I'm working on an application that uses OsmAnd under Andoid to display a route. My application generates a GPX file and opens the file with the OsmAnd application. 
When I generate a first file and I request the opening, the route is displayed correctly on Osmand. 
Then I return to my app with the back key. 
The problem is when I generate a second file and I open it. The new track gpx displays correctly but the first is always present. 
Is there a way to not view the ancient traces grail when opening a new file without manipulation in the deOsmAnd menu?

**Comment by vshcherb** [comment]
I'm afraid it will be hard to help in french :-( In a short way OsmAnd has API https://github.com/osmandapp/osmand-api-demo/ and OsmAnd is designed to work with 3rd party GPX
