### ISSUE TITLE
Split analysis doesn't recognize gaps

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/Osmand#7084]
I'm not sure how it should function but it looks like we don't recognize gaps in GPX tracks which could be an issue. I saw an issue with our recording mechanism though I think we need to do it while we are parsing and analyzing 

![image](https://user-images.githubusercontent.com/1042025/59983264-cda6f600-961d-11e9-8577-8f70b6589dfa.png)
[Day 2.gpx.zip](https://github.com/osmandapp/Osmand/files/3318665/Day.2.gpx.zip)

**Comment by sonora** [comment]
The files contains a collection of 25 waypoints and 2 treks. Yes, there are clearly some bugs, as follows:

**(1)** In OsmAnd's track overview, the total distance is shown as 56.4 km, which I believe to be the correct sum of the 2 tracks. But when you tap on the track, our analysis screen shows 3 parts: Trek 1 with 63.7km, track 2 with 42.9km, both results are bogus. When you cut the track files and analyze them separately, they come out as 42,9km and 13.4km (summing up to 56.3km). The 3rd part is the waypoint collection. 

**(2)** On the track analysis screen, the elevation profile shown for each of the 2 track segments shows the same profile, that for track 1. Interestingly, the track has the 43km scale which is correct for track 1. Profile for track 2 is never shown.

**(3)** Tapping the 'Split interval' or 'Analyze on map' button below any of the 3 portions on the track analysis screen always only analyses track 1.

Have not looked at any code, but the respective bugs are probably not too hard to find for whoever authored it.

**Comment by vshcherb** [comment]
I think now we have checkbox to join gaps or not join gaps. It affects both time and distance

BTW we don't split segments automatically but it could be introduced i.e. by distance or time threshold to generate multiple tracks out of one.

**Comment by vshcherb** [comment]
@sonora please confirm that new functionality fits the needs

**Comment by sonora** [comment]
For the "Day 2" test file, when I activate "Join gaps", the only effect I see is that the distance figure of the first track on the analysis screen changes from the bogus  63.7 km to the correct overall total 56.4 km., while the data for all other segments on that screen remain wrong, The elevation graphs remain unchanged for all segments. And also when I go to a split analysis (for say 10 km intervals) for the first (now allegedly joined) segment, OsmAnd tries to evaluate the bogus 63.7 km trip (with the first four 10 km segments showing data, and  the last two intervals displayed as empty).

So lots of bugs there, I am afraid.

I think the "Join gaps" functionality could be useful if it worked in the fashion that it made split tracks appear and analyzes them as one track in every aspect (in the graphs as well as in the split analyses, etc.). In this fashion it could be useful to view and analyze imported tracks which for some reason were split by the author (such as our test track), or to view tracks split by OsmAnd during recording, e.g. due to manual pausing a recording, lack of GPX reception while e.g. indoors, or using our auto-split settings.

I have to say I have limited use for this feature. And it is definitely not the proper fix for all the bugs I report above.

**Comment by vshcherb** [comment]
Need to be checked again it might buggy but I'm not sure yet

**Comment by sonora** [comment]
Has anybody tested this and is convinced it works?

Using our provided Day2 test track: Have not tested to detail,  but e.g. on the track analysis screen, the scale of the top-most altitude graph (I suppose it is intended to show the entire track) on the Overview tab does not change at all between having Join segments selected or not. I think it even always only shows the first segment, i.e. the 43 km. (Interestingly on the neighboring tab Altitude it does correctly show and change between 56 and 63 km).

**Comment by Chumva** [comment]
Day2 test track does not have info about altitude in second segment.

**Comment by Chumva** [comment]
![Screenshot_2020-01-11-11-13-16-965_com google android apps docs editors docs](https://user-images.githubusercontent.com/19220417/72202029-6b033380-3463-11ea-99ca-56aea6983850.jpg)

**Comment by sonora** [comment]
Ah, true, my oversight. I was irritated by us showing a different range for the Altitude graph on the Overview tab vs. the same Altitude+slope graph on the Altitude tab. But I guess it is also just a weird tedt track :)

**Comment by vshcherb** [comment]
Yes it was tested, it was requested based on previous bug validation and now this feature looks more or less consistent through the whole application

**Comment by sonora** [comment]
:)

I guess the entire story around splitting vs  joining tracks is a complication we have introduced without need ... :)

For lack of significance, and benefit vs. cost, I will not reopen, though it looks like I could easily pinpoint sone remaining issues here... :)

**Comment by Chumva** [comment]
You can create new issue :)
