### ISSUE TITLE
Wrong routing

### ISSUE THREAD

**Issue by Prusaker** [osmandapp/Osmand#7142]
Incorrect routing (with Car profie) in OsmAnd 3.4.0
In this place: [https://www.openstreetmap.org/#map=18/53.15861/24.81609](https://www.openstreetmap.org/#map=18/53.15861/24.81609)

The route is created through the roads highway=service and living_streets. "Fastest route" setting is enabled. Possibly this is not the fastest route, it looks like the shortest route.

![Screenshot_2019-07-02-11-34-07](https://user-images.githubusercontent.com/32092837/60498107-ab1c7900-9cbe-11e9-83cc-372e308c0d26.png)

But on the same maps and with the same navigation settings, the OsmAnd 3.3.0 and more oldest builds creates the route ("Fastest route") correctly:

![photo_2019-07-02_11-33-10](https://user-images.githubusercontent.com/32092837/60498200-d56e3680-9cbe-11e9-97e0-3c6537ce66ef.jpg)

So the problem is not in the OSM data.

**Comment by dwcaesar** [comment]
I see similar behavior in another region.
I drive infrequently through the same rural area. Since an update, I don't know which one, it seems like osm is somewhat preferring shorter routes, even if it takes longer. It's like it's trying to get the quickest route but settles with the shortest option.

**Comment by hakuchi** [comment]
data on OSM not looks correct for me.
highway=service
living_street=yes
should not be used!

living_street=yes have no approvation in OSM.

you should better use higway=living_street and then Osmand will not allow transit trough the shorter way.

because highway service is free to use for transit and so OsmAnd use this way, but in Belarus(according to this site [link](https://kodeksy-by.com/pdd/glava/18.htm)) it is prohibited to use a living street to transit.

If you use correct tagging for the living street, osmand will avoid the "shorter way" any time.

If on this way is a living area sing(as in the 2th image from this [site](https://auto.onliner.by/2015/10/03/a-vy-tak-umeete-19)), you should tagg this as a highway=living=street.

**Comment by Prusaker** [comment]
As I know the combination highway=living_street is used only if this street has a name. For other cases usually used highway=service + living_street=yes. This can be seen if you look at how such roads are marked throughout the Belarus :)

As far as I know in the OsmAnd for driving on highway=service, a very low priority is set, and it is in version 3.4.0 that for some reason this priority does not work correctly.
