### ISSUE TITLE
Make UI miles-friendly

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/Osmand#7145]
10 miles

![image](https://user-images.githubusercontent.com/1042025/60504869-27b55480-9ccb-11e9-8857-fc20b28ccfca.png)

**Comment by sonora** [comment]
Honestly, I think that rather than tweaking that we should kill that message entirely. Users will not care much whether 'Nothing' was found within 6.21 or 10 miles, they want to FIND things. Hence I suggest if nothing was found we just keep searching, i.e. increase the radius in the background and automatically. And if something was found, we can still simply offer a button saying 'Show more results from further away' ?

**Comment by lbdroid** [comment]
Its important to have a maximum search radius, otherwise it will search the entire planet.

**Comment by sonora** [comment]
And that's exactly how it should be: While there is no hit, just keep searching (automatically). Nothing more annoying than having to manually tap 'Increase search radius' sixteen times to find something. Try it. :)

**Comment by lbdroid** [comment]
How many hours would you like for it to keep searching and how many search results would you like from other CONTINENTS?

**Comment by vshcherb** [comment]
https://github.com/osmandapp/Osmand/commit/bd1f4785e40dac808cf94f20902fa5b2879358ca

**Comment by vshcherb** [comment]
I think the radius is needed so person has a perception so we've searched AT LEAST 20 km radius. We can't afford searching > 100 km without an input, it is too slow today (could be > 1 minute)
