### ISSUE TITLE
Trip recording plugin: Settings are not connected with a separate Navigation profile

### ISSUE THREAD

**Issue by katerynakocherhina** [osmandapp/Osmand#7235]
In Menu - Plugins - Trip recording plugin - Settings such configurations like:
Logging minimum accuracy
Logging minimum displacement
Logging minimum speed
are not connected to the chosen navigation profile, but they affect all the profiles at once.

**Comment by sonora** [comment]
Yes, this is by design, see discussion here: #3200, in particular line item **(1)**.

Setting these filters can essentially impact or destroy your recordings in ways not very transparent to the user. We do not want to aggravate the issue by recordings being affected by profile changes a user may cause by manual interaction or interim navigation during an ongoing recording.

**Comment by vshcherb** [comment]
Though now we are going to move all settings to be profile dependent

**Comment by vshcherb** [comment]
For these settings we need to apply similar strategy as we applied to general settings with "apply to all" dialog
