### ISSUE TITLE
Render addr:unit

### ISSUE THREAD

**Issue by Moiman** [osmandapp/OsmAnd#7264]
In osmand it shows "3" and in openstreetmap.com "3 A"
example https://www.openstreetmap.org/way/113940210

**Comment by vshcherb** [comment]
This is really strange / mapping and rendering. Cause they are separate buildings usually in many countries units are part of housenumber in that case. So they could be used for search and not only specific rendering

**Comment by mvestola** [comment]
At least in Finland this kind of mapping is quite common in addresses. And it also seems to be used quite much elsewhere also: https://taginfo.openstreetmap.org/keys/?key=addr:unit#overview . So in Finland, we can have an apartment with address like "Kirkkokatu 1 A 23": this means that there is usually a single building which address is Kirkkokatu 1 A and then there might be another building like Kirkkokatu 1 B. Both of these buildings have tags addr:housenumber=1 and addr:street=Kirkkokatu, but then first building has tag addr:unit=A and second building addr:unit=B . OSM default map renders these letters in address correctly in the buildings. But OsmAnd does not show these letters at all which really makes it more difficult to navigate to correct building. One example of this kind of building is here: https://www.openstreetmap.org/way/232920706

This kind of apartment with address "Kirkkokatu 1 A 23" might also be inside one building which has building address as "Kirkkokatu 1" and then the building has several staircases A, B and C. In that case, those staircases are usually mapped as entrance nodes which would in this example have tags addr:housenumber=1, addr:street=Kirkkokatu and addr:unit=A. One example of this kind of node is: https://www.openstreetmap.org/node/6618594956#map=19/60.17248/24.95902

So this would be nice to get fixed to OsmAnd rendering. So basically the logic could be something that if there is addr:street and addr:housenumber tags present in building or node and there is also addr:unit tag present, one would just render whatever is in the addr:unit after the addr:housenumber separated with a space. This is at least how it works in Finland, not sure about other countries if they have different address schemes. Can this kind of rendering be applied for OsmAnd only for addresses in Finland in case it creates any issues for other countries?

Not sure if using this addr:unit is totally accepted address mapping scheme since the [wiki](https://wiki.openstreetmap.org/wiki/Key:addr#Detailed_subkeys) and the [proposal](https://wiki.openstreetmap.org/wiki/Proposed_features/addr_keys_(2011-04)) is not that clear for the addr:unit : _"The number, letter, or name of a single unit or flat that exists within a larger complex. While a big building could have only one entrance, sometimes the way inside divides into different units or staircases, where certain apartments/flats/offices can only be reached through a specific unit."_ In this case the buildings with the same addr:housenumber could be though as a "larger complex" and a single building with several staircases with letters should at least fit to that.
