### ISSUE TITLE
cleaner and simpler UI

### ISSUE THREAD

**Issue by OpenSourceForEver** [osmandapp/Osmand#7328]
I think having a simpler interface is better for many reasons, so I will give you two suggestions:

1. Delete Dashboard. All dashboard items are accessible in one or at most two steps from the menu so I don't find any benefit having the dashboard.

2. Unify map markers and my places. These two items have a relatively similar function, so perhaps it would be good to unify them into a single item.

**Comment by sonora** [comment]
There will always be different opinions on this, and we would likely take some heat. But I can definitely say that both suggestions are (and have always been) 100% my opinion also. And I can also say that all users I know in person will very much endorse this simplification.

**Comment by OpenSourceForEver** [comment]
> There will always be different opinions on this, and we would likely take some heat.
I know it but I think first suggestion should be less controversial than the second because 
dashboard is a repetitive item. Although the dashboard was created with the purpose of giving faster and easier access to several sections, this is not true because accessing these sections is neither faster nor easier via dashboard.

**Comment by IgorEliezer** [comment]
> Unify map markers and my places. These two items have a relatively similar function, so perhaps it would be good to unify them into a single item.

I agree. The user could tap a POI or item on the map, and tap "Save" (instead of the current "Add" and "Marker"). A small prompt appears saying "Save {POI_name} as: Marker/Waypoint, Favorite, {list other folders created in My Places}".

**Other ideas:**

1. "Directions" could be moved to the main toolbar: "Save" | "Share" | "Actions" | "Directions".

2. Replace "Details" with a small handle to hint the user he/she can draw the Details panel.

3. Alternatively, the "Actions" button could be moved to elsewhere, perhaps in the Details panel, for I think this is not used so often.

4. One the most frustrating thing in OsmAnd is the triad "Configure Map", "Configure Screen" and  "Configure Navigation". It seems they are spread everywhere but at the same time not available consistently. E.g. "Configure Map" and "Configure Screen" are accessible via Main Menu and App Profiles, but "Configure Navigation" only in App Profiles. They should work in tandem.

![image](https://user-images.githubusercontent.com/4673289/62089064-ec606400-b23d-11e9-9718-f68bb51acc81.png)

Here (the pic above) I would replace the "Show" field with 3 tabs "⌜Map⌝ ⌜Screen⌝ ⌜Navigation⌝".

**Comment by OpenSourceForEver** [comment]
I referenced https://github.com/osmandapp/Osmand/issues/7230 because I think having fewer options means a cleaner and simpler interface. (Maybe the same with https://github.com/osmandapp/Osmand/issues/6981)

**Comment by vshcherb** [comment]
There is an initial plan for Markers. I will lay down it here:
1. Markers will love to a separate plugin not enabled by default (Route points)
2. Context menu will have - Direction button which will enable maximum 1-2 direction points displayed in top widget.
3. Markers if enabled will be displayed in My Places
4. All route planning and sorting functions will be in this Plugin
5. My places will also have 1 more screen "History of Directions" because it is possible to have maximum 2 direction points so they will circulate and go to history

**Comment by OpenSourceForEver** [comment]
> Context menu will have - Direction button which will enable maximum 1-2 direction points displayed in top widget.

Well, but what would happen if I wanted to calculate a route with more than two intermediate points?

**Comment by dmpr0** [comment]
> Well, but what would happen if I wanted to calculate a route with more than two intermediate points?

You will get the route. Markers are not the same as waypoint/intermediate points.

**Comment by Posteinwurf** [comment]
I would very much support getting rid of the dashboard. the standard access is all that is needed. Dashboard is not faster. 

Also: New users struggle a lot because of all the (great) functions that Osmand has. So the dashboard further confuses them.

One other suggestions for a simpler menu:

for elevation choices in bicycle mode: no seperate on / off switch. Instead just ONE submenu with for choices: 0 (hill reduction off), 1, 2, 3 (strongest reduction).

I know that users use it wrongly now: the don't get that flat mode only works whrn elevation is switched on.

**Comment by littlehelper** [comment]
I am not against removing the dashboard to reduce the number of different menus providing access to the same content. I just want to say that I personally like the dashboard's way to quickly access (up to 10) closest favourites and last used/newest tracks. If removing from the dashboard I would love to see this funtionality at the favourites' and tracks' menu. Thanks.

**Comment by jkufner** [comment]
Unify "map markers" and "my places". These two items have a relatively similar function, so perhaps it would be good to unify them into a single item.

Please do not mix map markers with favorites and route waypoints. Those temporary little flags I can put on the map are extremely useful. The favorites are permanent markers, and the waypoints have a completely different purpose.

I think it would be nice to have map markers as a tab in "my places" screen, and then have a button to open this screen directly from the main view. Also, the first tab in "my places" should be a "recently used" tab which would replace the functionality of the dashboard.

**Comment by sonora** [comment]
Here is another example which makes we wonder if we really work on the right priorities:

In recent nightlies we have introduced an entire new menu entry and settings screen called "Profile appearance", facilitating to modify such significant parameters as the profile names, color of the profile icon used, and modify the position icon and navigation icon.

Yet again, I think we introduce something which does not significantly improve any serious functionality of our app, but rather clutters our menu structure by yet another settings screen which I dare say will never be used nor appreciated by 99% of users. Please keep in mind that almost every single review you can find about OsmAnd on the Internet and in magazines perceives OsmAnd as having a great and exhausting set of professional functionality, but is way more complex to use than necessary.

Options to merely facilitate over-customization of the app appearance do mostly not add useful functionality, but rather harm simplicity and a clean UI, complicate support and documentation, introduce bugs, bind developer resources, and create the appearance of a complex geek tool... ;)

**Comment by IgorEliezer** [comment]
> and create the appearance of a complex geek tool... ;)

Like I like to say "designed by engineers for engineers, not for average people". One thing you can do is to meet sone people who are used to smartphones but never used OsmAnd and simulate the usage of a set of important/1st use features (e.g. routing, search, favorite library, interesting places nearby etc) to spot the pitfalls and intuitive paths. 

BTW as to "Profile appearance", oh what a nifty feature, I can choose a car for my navigation icon... what if I could _instead_ choose a bicycle, motorcycle, bus, boat...... see? [feature creep](https://en.wikipedia.org/wiki/Feature_creep). :)

With profiles right in the top of the left menu, it makes me wonder if "Configure Map" and "Configure screen" are still necessary there.

**Comment by OpenSourceForEver** [comment]
> Methinks the trick for cleaner UI is to keep the most needed stuff on the 1st UI layer, and move the other stuff deeper following a reasonable learning curve, so 1st users wouldn't feel overwhelmed with many buttons on the screen. They will find out the more complex and customization stuff as they get used to and explore the app further.


That's! You have perfectly explained what I wanted to say in the first message. Nobody talks about removing functions but of having a simpler interface.

**Comment by IgorEliezer** [comment]
An interesting article about 10 GPS app: https://www.carbibles.com/best-gps-apps/

**Comment by vshcherb** [comment]
This becomes quite offtopic issue due to its name, so it is better not to use issue tracker for endless and non-concrete dicussions. 

Short term plan: dashboard will be move out the plugin.
