### ISSUE TITLE
Odd tts voice highway ref reading "D 71E1"

### ISSUE THREAD

**Issue by 7tonin** [osmandapp/Osmand#7379]
Hi,
when tts voice is reading some highway ref, it can tell something odd.
In France, most of roads are named like "D 71", but some are named like "D 71E1". In the second case, it is read "D 71 puissance 1" ! Looks like it interprets it like Maths (D 71^1).

**Comment by Rpnpif** [comment]
I haven't met such an highway reference yet but when I get D 71E1 pronounced directly with the Google TTS out of OsmAnd, the pronunciation is correct. So this issue seems really from OsmAnd.

@7tonin  Have you a place in OpenStreetMap with this highway to test ?

**Comment by 7tonin** [comment]
Here it is: https://www.openstreetmap.org/way/161703115
Could it be because of my Android version ? 4.2.2 (ou 4.4.2)

**Comment by 7tonin** [comment]
Also, I must have to precise that it is french locale, so "fr tts", that gives the bug to me.

**Comment by Rpnpif** [comment]
I does not observe this issue with OsmAnd 3.4.6 on Android 8 but it is pronounced one digit after the other and not as a number for 71. It is not usual in French language.

A detail:
If E from E1 means European (route), the ref should be written D 71 E 1 or D71 E1 in Osm.

**Comment by sonora** [comment]
OsmAnd simply passes the characters to the TTS engine. What is being announced is at the discretion of the TTS engine selected in your Android settings (outside OsmAnd), and they diifer wildly. Some put more stress on trying to detect something mathematical, while others pronounce numbers, yet others pronounce digit by digit. Try a few, often your device comes equipped with 2 different ones (your device manufacturer's and google) and there are also some in the play store.

Tweaking things in OsmAnd, i.e. manipulate how characters are passed to the TTS engine, is risky, usually fixing one thing will cause numerous other issues.

**Comment by bumbaras** [comment]
I have the same issue with Polish languague, leaving the national road mark like D71E1 it tries to pronounce numbers in street names like Lipowa Street 71 is made as Lipowa Street Seventieth First. 
And it is the lightest issue in such pronounciation. Because numbers in polish language can be pronounced differently to a different cases, lecteur tries it all.
It is even funny at first, but becomes annoying later. I use TTS from Google as Engine. I can't compare it to Google Maps because GM are not reading numbers od street names.
I have never seen control file for TTS engine so I don't know how it really work.
