### ISSUE TITLE
Errors in elevation data

### ISSUE THREAD

**Issue by Posteinwurf** [osmandapp/OsmAnd#7380]
Elevation data in the maps still have too much noise. this is especially true in cities, where high buildings are interpreted as mountains (the resolution is not fine enough to distinguish between the building and the adjacent road).

One example from Berlin, where (a perfectly flat) road is wrongly seen 
![Screenshot_2019-08-08-08-06-13](https://user-images.githubusercontent.com/17393264/62679532-0d9b2000-b9b5-11e9-8378-a65904d57a81.png)
as having a 52 per slope!

This leads to a grave error in routing:  ways with 52 per cent ascent or descent have to be excluded from the routing in the 'avoid hills' modes. so we have one perfectly flat road which is now excluded from the routing by error.

Maybe there is no final solution for this (unless we get perfect resolution data). but I hope someone has an idea how to ease this problem. maybe use elevation data from user-generated tracks (where available)? Maybe filter the data in big cities?

The resolution needs to come from the map data side (not from the the routing code side): The routing engine just cannot ignore a 52 per cent slope (no matter how short)! So there should be a solution to know that these 52 per cent don't exist.

**Comment by Posteinwurf** [comment]
Another thought: Maybe it is possible to generate the elevation values from the contour lines? these seem to be correct.

**Comment by scaidermern** [comment]
Maybe some smoothing can be applied to get rid of such tiny spikes?

**Comment by vshcherb** [comment]
Smoothing out will work bad for mountain areas.

**Comment by Posteinwurf** [comment]
Here is a related discussion, this time related to cycleway in the countryside. 

I have observed the same issue several times in France this year.

https://github.com/osmandapp/Osmand/issues/5568

**Comment by andreapx** [comment]
Are there news about this?
I noticed it hiking yesterday. I've recorded the track with Locus Map and it shows an ascent of 1289m.
Ive imported the track into OsmAnd+ and it shows an ascent of 1700m
![Screenshot_20210817-162128](https://user-images.githubusercontent.com/13846728/129750394-dae8c7b7-1aaf-49c7-a22c-5f62c3bbb4da.jpg)
![Screenshot_20210817-162150](https://user-images.githubusercontent.com/13846728/129750429-1ccdec55-99c6-4db7-8aeb-4d955a3e533f.jpg)

**Comment by sonora** [comment]
As the screenshot above perfectly illustrates: Deriving slopes by simply comparing single neighboring elevation values (if that's what we do?) is not meaningful, and using this for a routing decision is plain nonsense.

To lessen the issue, you need to group points and work with averages, and a certain compromise will inevitably be introduced by the grouping selection.

This issue is similar to what I faced when writing the code for the ascent/descent summation in the GPX track analysis, you can look at my code there from several years ago: There the "grouping" I selected was looking at trend channel segments and ending each segment when a meaningful elevation change in the opposite direction of the current trend is encountered. From my recollection I selected 5 m elevation change as the meaningful turnaround threshold, meaning that elevation changes will be consolidated until the trend channel changes direction by at least 5 m (when a new consolidation starts).

Transferring this idea to a slope calculation would mean you now also report "the slope" not for each track point, but only (averaged) per each of these elevation trend channel segments. This averages out single slope spikes by summarizing "the slope" in each (variable) entire distance for which the trend seems either uphill or downhill. Of course this is a compromise, essentially just another smoothing mechanism, albeit one with a given spatial flexibility. Could be worth a try.

**Comment by pebogufi** [comment]
To lessen the issue, you can also use a "moving average", which reduces such "noise".

**Comment by sonora** [comment]
@pebogufi Yes, easy to code, but tough conceptually: I find no reasonably intelligent algorithm to determine the length of the sliding interval.
