### ISSUE TITLE
[Feature request] Calculate and store bearing (aka heading/direction/course) in gpx when using track recording plugin

### ISSUE THREAD

**Issue by GPSMapper** [osmandapp/Osmand#7394]
Hi,
I am using OsmAnd android app to record gpx tracks, using 'Track recording plugin'.
Recorded tracks are used for geotagging of the images for mapillary.
Essential data required is coodinates, date&time and heading (direction).

OsmAnd track recording plugin does not store heading at the moment which makes batch processing a bit more complicated, while exiftool does not support heading interpolation from gpx either.

There are various tools available to do the job, but for the sake of workflow simplicity and speed, it would be great if OsmAnd will add heading support to its 'track recording' plugin.
Exiftool could pickup heading from gpx (looking up  <course> tags)

Sample trackpoint:

```
<trkpt lat="48.225437" lon="16.370304">
				<ele>4.76</ele>
				<time>2012-07-03T19:32:34+02:00</time>
				<course>45.16</course>
				<roll>-3.3</roll>
				<pitch>-3.26</pitch>
</trkpt>

```

**Comment by sonora** [comment]
Should probably be an option/toggle at most. It is obsolete information for the majority of use cases, so it would be awkward to generally increaee the size of all recorded tracks for all users.

**Comment by vshcherb** [comment]
@sonora  Agree

**Comment by GPSMapper** [comment]
@vshcherb , hope it will not be pushed back to 3.7 ...8 ....9  later :) Hope to see it in 3.6 soon ;)

**Comment by vshcherb** [comment]
It is already implemented, so will be soon in nightlies

**Comment by max-klaus** [comment]
Currently we added heading parameter only. It is in extensions section. Also there is checkbox "Save heading" at the plugin's settings.

**Comment by sonora** [comment]
@GPSMapper, @max-klaus Let me just comment regarding the title of this issue "bearing (aka heading/direction/course): In principle (and at least in the nautical and aviation use cases) these are certainly different. Meaning "aka" is technically wrong, and the actual request in this issue is a little unclear.

I have not checked the recent implementation, but our code used to use Android Location class' `getBearing()` (returning a value between 0.0 < x <=360.0 east of True North, with 0.0 being returned if a location has no associated bearing). The Android documentation calls this "the horizontal direction of travel", "not related to the device orientation", hence technically speaking this is the  track direction.

If this is what we use, and we leave our wording as "Heading", we are probably fine for land-based use cases, but it would confuse users knowledgeable about airborne and nautical use cases. For a detailed discussion check out this thread (first answer has a neat picture) https://aviation.stackexchange.com/questions/8000/what-are-the-differences-between-bearing-vs-course-vs-direction-vs-heading-vs-tr].
