### ISSUE TITLE
Bug report: U turn 

### ISSUE THREAD

**Issue by katerynakocherhina** [osmandapp/Osmand#7400]
OsmAnd suggests turning left on the inappropriate section of the road, while avoiding the turn on the traffic lights.
43.77566° N, 79.33753° W
https://www.openstreetmap.org/directions?engine=fossgis_osrm_car&route=43.77588%2C-79.33890%3B43.77610%2C-79.33758#map=19/43.77593/-79.33824

**Comment by MadWasp79** [comment]
https://www.openstreetmap.org/way/145889726#map=19/43.77593/-79.33660 - this road is 'unclassified' and we have a large penalty for the transition from secondary (100 vs 200).
@vshcherb what can be done here? For routing to use this turn this way should be promoted at least to tertiary. To lower the penalty for 'unclassified' because of one way is unwise

**Comment by MadWasp79** [comment]
btw issue not with u-turn, there is no restriction

**Comment by vshcherb** [comment]
I think we can safely edit https://www.openstreetmap.org/way/145889726 and the other road to tertiary_link. @MadWasp79  please do it, so I don't expect we're going to do anything here in the algorithms
