### ISSUE TITLE
[Issue] elevation given isn't the right one 

### ISSUE THREAD

**Issue by letypequividelespoubelles** [osmandapp/Osmand#7438]
The elevation given is often wrong, up to 100m difference. The elevation  given by GPS (using GPSstat app), the one we can read using position and contour lines are consistent and the right one. But not the one given by Osmand

**Comment by vshcherb** [comment]
You can try to download altitude correction package

**Comment by letypequividelespoubelles** [comment]
I already have the altitude correction. Didn't try without. Btw, why do we need to dl the altitude correction? 
Thanks

**Comment by sonora** [comment]
The altitude correction file is needed to better approximate the bare GPS reading to the regional "above sea level" elevation conventionally used.

The GPS reading alone would just give you the elevation above a perfectly regular reference ellipsoid, but the earth's sea level reference is regionally distorted by e.g. the irregular gravitation caused by mountain ranges density fluctuations in its crust. The difference can well be order of magnitude 100m.

Can you please give specifics at what location you see what reading with what app, and vs. you expectation, maybe we can sort it out then.

**Comment by letypequividelespoubelles** [comment]
I knew what's this altitude correction is. My question is : why do we need to dl it and it's already dl with OsmAnd ? What can be the benefit to not dl it ?

There is no specific location, it's everytime I'm in french mountains (Pyrenées, french and swiss Alpes). In central Asia, it seems to be more accurate.

**Comment by sonora** [comment]
Next time it happens, maybe you can record the position, and all the readings you observe from different apps.  Without specifics, I am afraid I am a little at loss how to debug what you observe in the first place.

**Comment by letypequividelespoubelles** [comment]
For exemple, this morning, in Paris (all maps up to date, of course).
In gpstest : elevation 33.7m, Lat:48,8597917°, long:2,3289500°.
In osmand : elevation :  -10m. On the map, just near the 30m elevation line.  Position shown on the map is ok. Only pb is elevation shown in Osmand. 
Thanks!

**Comment by sonora** [comment]
Ok, thanks. I may have to come back to this to research in detail if you are interested. I have 3 questions:
- (a) Are all these readings (at the same  location) reproducible over time, or do they fluctuate? (Just to rule out there is a reception/noise issue)
- (b) Would you have a second (different manufacturer) device to test, preferably using the same apps and setup (to rule out that your device applies a correction to the GPS reading already, and OsmAnd over-compensates)
- (c) In OmAnd, do you have the Altitude correction map active or not? If you activate/deactivate it, how does it change your reading? (to investigate of the OsmAnd altitude correction works on your devices, and maybe remove and over-compensation of (b) )

Preliminary results (Please refer to https://eos-gnss.com/elevation-for-beginners to understand the basics):
- Location: 48° 51' 35'' N, 2° 19' 44'' E
- GPS ellipsoidal height: 33.7 (meters)
- Geoid height: 44.533 (meters)
- Orthometric height (height above EGM96 geoid which approximates mean sea level): -10.833 (meters)
(Source: https://www.unavco.org/software/geodetic-utilities/geoid-height-calculator/geoid-height)

I am hoping that your answers to (a)-(c) will help debug this. At first sight it looks like for your readings of 33.7m GPS ellipsoidal height the conventional correction approach to mean sea level would really result in -10 m. But since 35m is about the true MSL for Paris, maybe the chipset in your device already applies some sort of correction. In this case,disabling the OsmAnd Altitude correction would maybe give you optimized/expected results?

**Comment by letypequividelespoubelles** [comment]
With a new device, I don't have this issue, I close it. Thanks.
