### ISSUE TITLE
Routing into motor_vehicle=destination not possible

### ISSUE THREAD

**Issue by Discostu36** [osmandapp/Osmand#7456]
OsmAnd: 3.4.8 (Beta 2019-08-20)
Samsung Galaxy A7 (2018)
Android 9
Germany_schleswig-holstein_europe.obf (August 1st)
Germany_schleswig-holstein_europe_19_98_22.obf
In-app car routing

**Problem:**
My problem is somehow the opposite of #6280 

If my destination is at a road that is tagged with _motor_vehicle=destination_. Osmand refuses to route me into the street and instead ends navigation at a street nearby.

Start: https://www.openstreetmap.org/node/387442693
Destination: https://www.openstreetmap.org/way/287681031

**Solution:**

Possibility 1: Allow routing into streets tagged _motor_vehicle=destination_ if it is at the end of the route.

Possibility 2: Ask the user if they want to allow routing into _motor_vehicle=destination_ for this drive (similar how routing into private roads works now)

_Edit:_
Possibility 3: Add an option to routing preferences to let the user decide, how these cases should be treated.

**Comment by Discostu36** [comment]
![Screenshot_20190822-124906_OsmAnd](https://user-images.githubusercontent.com/30999326/63508962-54bc0180-c4db-11e9-99c4-3bba5a6719c9.jpg)

**Comment by hakuchi** [comment]
General access to "Destination" is incorrect, as you do not have permission to enter this street unless you live in the area or if you have booked accommodation there.

Maybe it is different in some countries ...


Some **other solution** can be this:
If you put the end in a street with "destination", OsmAnd should **always ask** if you want to drive into the restricted zone, which you can then confirm with Yes or No.

**Comment by scaidermern** [comment]
> General access to "Destination" is incorrect, as you do not have permission to enter this street unless you live in the area or if you have booked accommodation there.

At least in Germany clients (for local shops and businesses) and visitors (to local residents) are allowed, too. Just through traffic is forbidden.

**Comment by hakuchi** [comment]
> At least in Germany clients (for local shops and businesses) and visitors (to local residents) are allowed, too. Just through traffic is forbidden.

If I place the endpoint on the house number 32 and start from my home, I am not allowed to drive to this house, because I dont know anyone in this street(also there is no business).

Because of this OsmAnd should not give to anyone the possibility to navigate(without ny notification) into a street with "destination", because in the most situations, I am not allowed to drive into this area.     

For this I think the "**always ask**" solution is the best.

**Comment by Discostu36** [comment]
I have added a third possible solution in my original post.

**Comment by NotSoImportant** [comment]
@vshcherb how does the "closed" state fit with "future milestone 3.8"?

I was about to submit a feature request like this when I saw this one.
In addition my request is also to show the warning in case of
- access=agricultural
- access=customers
(+actually all other then "yes" and empty)

**Comment by Zero3** [comment]
@NotSoImportant I believe what that means is that this issue was fixed in version 3.8. I can confirm that it remains fixed in the latest version (4.0.5) (solution 1 above, by allowing routing into the street).

If you think a solution that warns the user is better, I think you should make a feature request for that (if there is not one already) :).
