### ISSUE TITLE
[Feature request] Improve bicycle routing

### ISSUE THREAD

**Issue by katerynakocherhina** [osmandapp/Osmand#7597]
It would be useful to consider the superordinate tag class: bicycle = * and add a navigation option to give priority to cycling routes (especially of the type network = rcn and network = lcn) as these routes are often away from the major roads.

**Comment by lgmaps** [comment]
Thanks for posting, Kate!
Just to give you some background: Since April 2019 we have been running an organised editing project at Leuphana University of Lüneburg, called Lüneburg Maps. The overall aim is to make cycling easier within the city by updating the local OpenStreetMap data (adding surface, smoothness and more data in OSM). In Lüneburg, a small city south of Hamburg, many bikeways / bike paths run along major roads (OSM: primary, secondary, tertiary). But local cyclists as well as tourists prefer smaller roads without bike paths, as these roads are much nicer for cycling and less conflict-ridden. Bike navigation apps including OsmAnd often prefer bike paths. So in Lüneburg OsmAnd mainly guides you on bike paths along heavily trafficked highways instead of showing you the much better and often easier and faster routes through parks and quiet neighborhood areas. 
With Lüneburg Maps we have implemented the class:bicycle=* tag to help make routing better (http://overpass-turbo.eu/s/MzS). So far we have been using class:bicycle=1, 2 or 3 to define the most preferable routes. We'd be very grateful if you would consider this tag and (as Kate writes) also give higher priority to local and regional cycling routes to make routing better for the city of Lüneburg. Look forward to hearing from you!
Cheers
Antje

**Comment by scaidermern** [comment]
If you want to improve bicycle routing then also prioritize fixing bugs such as #6954, #7532 and #7534.
