### ISSUE TITLE
Remove speed camera data from maps.

### ISSUE THREAD

**Issue by eregwizard** [osmandapp/Osmand#7614]
Since laws regarding the presence of speed camera data in navigation apps differs from country to country, osmand should remove such data from openstreetmap data for standard maps so everyone can use osmand and maps without worry about infringement of local law.
It might optionally be provided as separate plugin.

**Comment by scaidermern** [comment]
Speed camera warnings are configurable. Disabling this warnings should comply with the law as far as I know. Do you know about countries where this still conflicts with the law?

**Comment by eregwizard** [comment]
For Europe see (in dutch, use google translate): https://www.anwb.nl/juridisch-advies/op-vakantie/met-de-auto-op-reis/verbod-flitspaalsignalering-op-navigatie
Note: the disabling option is insufficient - having the data on your device is illegal as stated on that page.

**Comment by stephan75** [comment]
Years ago I heard that just having that data on device is also illegal in Austria. Anyone can confirm?

**Comment by scaidermern** [comment]
For Germany it is not quite clear. According to https://www.strassenverkehrsamt.de/magazin/blitzerwarner-in-navi-und-handy-verboten-75-euro-busgeld-droht it _could_ be enough to disable speed camera warnings.

**Comment by zekooooo** [comment]
Maybe add an option to not download this when downloading maps, or add an option to purge speed camera data after downloading the map file?

These laws exist only in a few countries. Is it likely police will dig through your phone in Austria or Netherlands you hit the brakes before a speed trap?

**Comment by eregwizard** [comment]
So zekooooo promotes violating the law just because the chance of being detected (and losing your device) is small??
And people in certain countries should just refrain from using osmand even when openstreetmap covers those countries?
Why not drop it from the maps and package it in downloadable POI sets?

**Comment by kreuzschnabel** [comment]
German law has been clarified now. From Jan 1st on, it is illegal while driving to have a device which is capable of giving speed camera warnings, regardless of its operational status. It is NOT sufficient to disable the warnings (since they can easily be re-enabled), nor having the device switched off.

Meaning: In 2.5 weeks from now, drivers in Germany are no longer allowed to have the present OsmAnd version installed on their phones.

To solve this, either make it a plugin that can be entirely de-installed to make the rest of OsmAnd legal again, or offer alternative maps with no camera data at all. 

--ks

**Comment by pebogufi** [comment]
In earlier version of osmand (may be years ago) I got a warning on install, that activating the warnings of speed cameras could be illegal in some cointries.
Please reactivate this install warning, and ...
- if the user does not want a speed camera warning, disable the checkboxes in a way that they can not be reenabled again or remove this checkboxes.
So the use (display, announce) of this speed camera warnings is safely inhibited.

- display this install warning on each installation of osmand (also updates). So if the user travels to a country, where the warnings are not vorbidden, he can install a update and reactivate the speed camera warnings.

Please DO NOT remove speed camera data from the map.
- it is legally allowed to get informed of the position of speed cameras, if the user is not currently driving, for example before he starts for a travel.
- As a mapper who collect data I need to know, what is already on the map. Otherwise I would collect data for mapping,  which are already in the map. This would cause a lot of unnecessary work and a lot of frustration.
- remove data from the map for a group of people would set a precedent.

**Comment by eregwizard** [comment]
Doing this through reinstall would be very clumsy, especially when traveling from one country to another - reinstall at the border?? Also, asking this at each reinstall/update is very user-**un**friendly - don't ask for what is already known.
Best option is to separate speed camara data in separate map data files to be downloaded per country and/or implement the plugin described already.
Checking speed camera's before starting the trip can easily be done by visiting the openstreetmap website. Equally, as mapper the camera's can be added using the website instead of the app.

**Comment by eregwizard** [comment]
Best option is to separate speed camera data in separate map data files to be downloaded per country. This would put the user who for whatever reason does not want this data for some country or not at all fully in control in a very clear and transparant manner and be fully in line with regulations in selected countries where even having the data in the device is illegal - check boxes would not be valid or clear on inspection. Useers who want the camera's simply download the data.
Doing this through reinstall would be very clumsy, especially when traveling from one country to another - reinstall at the border?? Also, asking this at each reinstall/update is very user-unfriendly - don't ask for what is already known. Again: having the data on the device is in several countries illegal - period. Don't force users who want to use osmand to violate the law.
Checking speed camera's before starting the trip when the user decides not to have the data on the device can easily be done by visiting the openstreetmap website. Equally, as mapper the camera's can be added using the website instead of using the app.

**Comment by Galbinus-OSM** [comment]
I think both ideas are good. This one fromKreuzschnabel und that from Eregwizard. 
It is only important that the developers of the osmand-app act quickly. Because already today it is not really legal to use a navigation app with warnings about speed cameras.  The German law "Straßenverkehrsordnung" will be changed. Than it is clear, that the speed-camera-warning-function of the Osmand-App is illegal  while driving. It's even illegal if you don't use this feature at all. It is enough that it is installed on the smartphone. at the latest from the entry into force of this change in law (probably February 2020) OSMand users who drive a car not only risk a fine of € 79 but also get a point in the German "Verkehrssünderdatei". This can cost the driver's license if this one point exceeds the limit.
If OSMand created the future map downloads without speed camera information and only offered this information as an additional download (like hillshading oder contour-lines, I would have the opportunity to continue using OSMand. This solution would be my favorite.
The developers of the navigation-app Magic Earth chose another solution. There you can permanently remove the speed camera warning function after the last update. This function ist than no longer offered can then no longer be activated without reinstalling the app and is not longer offered in the settings of the app. 
I hope the development of Osmand will act quickly because I would like to continue using this app.

**Comment by vshcherb** [comment]
We're going to proceed with a solution next release.

**Comment by vshcherb** [comment]
As stated earlier if user can't access to information, it is not considered as possessed. It looks like this written in that way, so driver can't view camera's information  neither on the route nor in advance while planning.

We consider to have a permanent ban of interacting with cameras for device per installation (based on user decision after installation)

**Comment by eregwizard** [comment]
Clumsy, and questionable. Why force users to have illegal data cluttering their device that they do not want. OsmAnd is focussing to much on easy gains instead of proper design and basic usability.

**Comment by scaidermern** [comment]
> We consider to have a permanent ban of interacting with cameras for device per installation (based on user decision after installation)

I'm not sure if this is a good solution. What about users using OsmAnd for commuting or travel between different countries? With the proposed solution an user from France or Czechia driving through Germany has to reinstall OsmAnd in order to choose whether to have speed camera data or not. This isn't really feasible.

It depends on the country whether speed camera data is allowed. So please make the solution country-specific, too. Either remove this data completely from the maps of affected countries or let the users decide whether to comply with the law when downloading a specific country map.

**Comment by eregwizard** [comment]
As indicated earlier, I agree with removing the data fom the maps (and make it available as separate POI download for those in countries not affected or not caring about law).
As I understand work is being done on this, hopefully the team decided for this sound solution instead of work arounds here and there.
But as early enthousiast I'm close to giving up on OsmAnd. The team seems focussed on UI stuff neglecting design and improvements in core funtionality.

**Comment by JonnyTech** [comment]
@vshcherb if speed camera data is now removed, how can it be accessed for those of us who want and can legally use it?

**Comment by vshcherb** [comment]
It is not removed, you need to make decision after installation in OsmAnd Settings - to remove it from device or not.

**Comment by scaidermern** [comment]
> It is not removed, you need to make decision after installation in OsmAnd Settings - to remove it from device or not.

Can this setting be undone? E.g. when traveling to a different country?

**Comment by JonnyTech** [comment]
Found this: Settings >> App profile >> Navigation settings >> Screen Alerts >> Speed cameras

But I cannot work out how to show cameras on map. Can you describe please?

**Comment by vshcherb** [comment]
@scaidermern no it can't be undone this is a regulation setting, so we need to confirm that devices doesn't have that functionality at all.

**Comment by pl71** [comment]
@Galbinus-OSM: German law "Straßenverkehrsordnung" was changed or not in respect of speed cameras warnings? Can we see the regulations? Are they available in English?

**Comment by joernheissler** [comment]
https://www.gesetze-im-internet.de/stvo_2013/__23.html

> (1c) Wer ein Fahrzeug führt, darf ein technisches Gerät nicht betreiben oder betriebsbereit mitführen, das dafür bestimm
t ist, Verkehrsüberwachungsmaßnahmen anzuzeigen oder zu stören. Das gilt insbesondere für Geräte zur Störung oder Anzeige von Geschwindigkeitsmessungen (Radarwarn- oder Laserstörgeräte). **Bei anderen technischen Geräten, die neben anderen Nutzungszwecken auch zur Anzeige oder Störung von Verkehrsüberwachungsmaßnahmen verwendet werden können, dürfen die entsprechenden Gerätefunktionen nicht verwendet werden.**

The **bold** sentence was recently added, and it makes all the difference.

Roughly translated:

> If you're using other technical devices which, in addition to other purposes, can be used to display and interfere with traffic monitoring measures, you may not use those functions.

Sounds like it's now okay to use smartphones/navigation units that can show speed cameras, as long as you switch off the function. The rationale can be found here: https://www.bundesrat.de/drs.html?id=591-19%28B%29

> Begründung:
Der mit der Verordnungsänderung beabsichtigte Vorstoß, künftig auch die
Nutzung von technischen Geräten zu verbieten, die nicht ausdrücklich zur An-
zeige oder zur Störung von Überwachungsmaßnahmen bestimmt sind, jedoch
zu diesen Zwecken verwendet werden können, ist im Sinne einer effektiven
Verkehrsüberwachung grundsätzlich positiv zu bewerten. Laut der Verord-
nungsbegründung wären von der vorgeschlagenen Regelung künftig allerdings
auch Navigationssysteme umfasst, die auf Verkehrsüberwachungsmaßnahmen
hinweisen, selbst wenn die entsprechende Funktion deaktiviert wird. Darüber
hinaus würde die vorgeschlagene Regelung ausweislich der Begründung der
Verordnung auch Mobiltelefone, auf denen sogenannte Blitzer-Apps installiert
sind, umfassen. Diese dürften vom Fahrzeugführer nicht mitgeführt werden.
Derart weitgehende Nutzungseinschränkungen erscheinen angesichts der
weiten Verbreitung von Smartphones sowie auch zum Beispiel von Naviga-
tionsgeräten mit entsprechenden Funktionen unverhältnismäßig. Es wird daher
vorgeschlagen, das vorgesehene Verbot auf die Nutzung der entsprechenden
Gerätefunktionen (zum Beispiel entsprechende Smartphone-Applikationen) zu
begrenzen.

**Comment by eregwizard** [comment]
So Germany made it easier.
Which of course does not make any difference since it's not the only country in the world.
What about France for instance?
Please don't tell me the developers are so unwilling to satify valid legal restrictions...

**Comment by eregwizard** [comment]
So Germany made it easier.
Which of course does not make any difference since it's not the only country in the world.
What about France for instance?
Please don't tell me the developers are so unwilling to satify valid legal restrictions...

Anyway, it is very surprising of not worrying that the team up to now has been unable to release this basically easy feature functionally speaking.

**Comment by dmpr0** [comment]
@eregwizard Options to delete speed cameras data and mentioning are already in the nightly build and will be the part fo the upcoming release.

**Comment by scaidermern** [comment]
A global switch which can't be changed afterwards is still a pretty bad solution when driving from one country to the other. This is a country-specific regulation and thus must become a country-specific switch.
