### ISSUE TITLE
OSMAND walking i get a fix/arrow for a few seconds, turns to circle 30 sec before turning into arrow again

### ISSUE THREAD

**Issue by erikrr** [osmandapp/OsmAnd#7641]
This is a follow up from https://github.com/osmandapp/Osmand/issues/6410

I had a big problem before but luckily the problem was fixed with issue 6410 but i still had a small problem after that see title on my Oneplus 5. 

So i forget about it, it worked more of less. But later i bought a new phone Samsung S10E so all problems would be solved i thought...
The new phone had the same problem as the oneplus 5. 
So it must be something else. 

I never had the problem before in the 4 years when the big problem started. It had always a quick fix and a arrow telling me where i was and where i was heading. I had to look for a few seconds and then i put my phone away. 

Because i don't want to look like a lost tourist  i prefer not to walk with my phone for more the a few seconds especially in dangerous places.  

The problem appears only with walking, not while driving in a car. What i think that happens is that when opening OSMAND it get a quick fix in 2 secs with 20 sats and holds it for 2 seconds. Then OSMAND thinks "no" you first have to follow the the fix for at least 400 meters (example don't know how long) to be sure it knows the arrow is pointing the right direction. So after 30 secs or so the blue circle is turning is in a arrow again and i know finally where i am heading to and if i should correct.  

In a car it seems to work the fix isn't lost because what is 400 meters traveling in car it does that i 2 seconds. 

The first 2 seconds arrow while walking is always pointing correct i noticed, So i hope that you can make the distance it checks shorter or leave the check out. Because it always worked from version 1.xx
      
I hope you can find what causes it because its the only thing that makes it difficult to work with.
If you have to check late at night in a city with many streets and corners its terrible because it needs 30 secs everytime you look up where you are.
Thanks

**Comment by sonora** [comment]
I am seeing the same thing occasionally, and had researched it some time ago as follows:

It is only reproducible in a combination of very slow moving speed l(ike casual walking) and GPS reception conditions with likely a lot of reflections, like near buildings, in narrow city streets, or under thick foliage in forests. When I walk over open fields under clear skies, the effect never comes up. Can you verify?

I hence believe what we are seeing is the GPS chipset's difficulties in reporting a bearing under certain conditions. In some cases, instead of seeing no bearing,  I also see completely wrong bearing reported for some time, which is, of course, not helpful either.

Just to make sure, there are two other effects, but I think you are not talking about either one:

1. We have a gray dot icon displaying an outdated (last remembered) position. That will be displayed initially while there is no new fix yet. But it would of course not move.

2. If you turned off the screen while moving, you would in the very beginning see an outdated / remembered arrow in blue, we have no gray (outdated) arrow icon. It will disappear after about 3 sec and will be replaced by either the correct new position, including bearing if available, or the gray dot. Maybe we should introduce a gray arrow?

I am not sure anything can be improved in OsmAnd.  What I do in such situations is look at the blue dot's viewing cone showing your orientation as derived from the device's magnetic sensor.

**Comment by sonora** [comment]
PS: Ubder General settings we have a setting 'Use nagnetic sensor'. I have never played with that (it is off for me), not sure if it has anything to do with your issue, maybe you want to test. I'd have to first check the code to see what it actually does. Its description references the orientation sensor, which seems unclear.

**Comment by erikrr** [comment]
'Use magnetic sensor' i remember that i tried a few months back and switched it to on and off to see if it solve the problem but it didnt matter.

Did some testing yesterday. Open space is not around the corner but i noticed in germany where there is space there didnt seem any difference. So checked in a city leiden not much high buildings.

"1. We have a gray dot icon displaying an outdated (last remembered) position. That will be displayed initially while there is no new fix yet. But it would of course not move."
->  No i almost never see that one


"2. If you turned off the screen while moving, you would in the very beginning see an outdated / remembered arrow in blue, we have no gray (outdated) arrow icon. It will disappear after about 3 sec and will be replaced by either the correct new position, including bearing if available, or the gray dot. Maybe we should introduce a gray arrow?
I am not sure anything can be improved in OsmAnd. What I do in such situations is look at the blue dot's viewing cone showing your orientation as derived from the device's magnetic sensor."
->  Hm sounds a bit like my problem
Indeed what it happens i check where i am and put the phone away 5 min later i take the phone out and again 3 secs blue arrow then disappear for 30 secs but it shows a blue dot instead with indeed a small view cone. 
The blue dot after the 3 secs is always updating so if i walk i can see the blue dot moving with me in those 30 secs just no bearing.
The viewing cone is a bit of help but not easy to see 

I checked the magnetic bearing and in my case it was always point in the right direction ok maybe 10 to 20 off (the blue arrow has the same problem in the first 30 secs then i see a blue arrow AND a viewing cone at the same time until he has a 100% fix and bearing then the cone disappears) but  good enough to get some info about where you are heading.

Maybe a year back osmand used the magnetic bearing while waiting for the fix after 30 secs so i did see a blue arrow all the time. Doesnt matter in this discusion.

A solution i think (for me) would a option to use the magnetic bearing from the magnetic cone/sensor translate that to the blue arrow until it has enough gps data to show its own blue arrow 
Or like you suggested make it a grey arrow so one can see it uses magnetic data on that moment although blue -> grey-> blue again i think would prefer 1 color (blue) all the way :-)    

That way we walkers always have a quick way to check if were are traveling in the right direction and how far and which direction i am from my starting point

**Comment by erikrr** [comment]
Great i type a whole story on my mobile via gmail when transkitting everything gone thanks google.

However did some more testing with magnetic sensor to on.
The old test was on oneplus 5.

I dont know if and how its possible but it seems to give a quicker blue arrow. It still a blue bearing circle around it but at least it shows an bearing arrow.

Will have to some more testing to be sure.

Still it would be nice if it shows the arrow using the magnetic sensor until the fix appears.

**Comment by sonora** [comment]
Yes, as I said, I get different behavior for different devices and environmental circumstances.  That's why I think it it the chipset behaviors we are seeing., not OsmAnd code.

But I will have to take the time to check our code, even if I seem to remember from years ago we only use standard Android calls like hasBeaing() and getBearing(), and apply no extra logic, smoothing or filtering. (But this needs vetification).

Yes, for your pirpose, we could maybe work with a gray magnetic bearing icon while there is no GPS fix yet, like I suggested. The downside  is, it would be at a wrong (last remembered, i.e. potentially significantly outdated) location, which I guess can be extremely confusing. 

And maybe, on the side, get rid of the awkward 'magnetic sensor' setting I referenced above, which I will also have to research what it is good for and if a manual togle could not be replaced by some automated imtelligence. (We used to have this only in dev settings for a long time, I think).

**Comment by sonora** [comment]
PS: One more thing to test is the Kaiman filter setting. I am not a fan of it when it comes to applying it to magneteic sensor readings, because it suppresses quick changes which may well occurr in reality when you rotate your device. I have it always off, but I just notice our installation default seems always on. @vscherb Maybe another canditate for removal or some automation to simplify our UX.

**Comment by sonora** [comment]
After another round of testing today: Could it be that what you are seeing is an artefact of the Kaiman filter, i.e. dissappears when you turn it off?

**Comment by erikrr** [comment]
My first GPS was google maps. I was in Leipzig and lost. I took GM and first it send me walking in one direction then after 50 meter it send me 180 degrees back and after 50 meter it send me again 180 degrees back, i was still lost  :-(  
I felt stupid and since then i hate GM. Although for driving its great.

Then i got OSMAND and discovered the kaiman filter and i never turned it off, finally it keeps point one direction the whole trip. 

But lets test to see what happens when turning it off.  
I did some testing tonight. every 200m a 300m turn the screen on to see what happens. Should be enough because every turn on i see that it lost the sats completely and shows 0/0 or 0/18 sats and takes a few secs to find the sats again.

You seem to have a point here with magnetic sensor off and kaiman "off" it seems to show a blue arrow a faster in most but not all of the cases.

turn kaiman "on" here seems to take more time to show the arrow 

At first i was happy with the results, sometimes the arrows showed up so fast that the grey arrow would not be needed. But the last series of testing it took 15/20 sec before showing anything sometimes longer, can not explain why that happened.

So a on/off option to give us a grey or lighter blue arrow using the compass data would be great. Its up to you if automated intelligence and get rid of the magnetic compass  or to leave it like it is now.

kaiman seems useful for help with magnetic sensor. Because else the arrow goes left right left right left right in 1 second making me nervous :-) The averaging gives a more relaxed view.

On my Samsung S10E i would set it now to kaiman "off" and magnetic compass "off" i felt a bit quicker. But maybe for other people with older devices its different.

I want to add something else i noticed that when i walk with my map using the setting to always point in the direction am walking. That OSMAND doesnt turn the map if no arrow shows so the compas cone can be pointing sideways or backwards and i have to turn the map with my fingers.
It is not a big deal but it would be nice that if a grey arrow is added that it pointing up then and turn the map in the arrow/cone direction.

**Comment by erikrr** [comment]
Never heard anything back anymore. Is it still looked into or....

But i have to say with the new recommended settings the fix is quicker now.
And using the compas cone also helps. But the cone is not visible for me when the sun is brightly shining on the display, in that case an grey arrow instead of the cone would be handy.

**Comment by sonora** [comment]
I guess we pretty much nailed the few things which could be done in OsmAnd, the rest is device/circumstance related, as your experience with Google Maps also indicates.

What is worth implementing now is the final decision of our product manager ... ;)

**Comment by erikrr** [comment]
Yeah lets hope the program manager is in a good mood ;)

**Comment by sonora** [comment]
Honestly, this is not a mainstream issue, and developer capacities are limited ... :)

**Comment by vshcherb** [comment]
Recently I also experienced weird issues, though with these kind of bugs it really requires to dig on a specific reproducible device. OsmAnd algorithms are pretty simple trying to follow information provided by GPS api which comes from sensor and Android OS. So I don't think we're going to dedicate a lot of time to solve that issue that in the next OS release we will get a different one .

**Comment by sonora** [comment]
Yes, I have been playing with this a lot across different devices.  As I have said all along, I am pretty convinced it is device/device driver/Android behavior, and hence in connection with local reception conditions there is very poor to no reproducibility, at least no consistency.

Re-checking our code, we simply use the API, I do not find much we could try to improve ... (other than maybe some workarounds involving cached data and icon color, as outlined above.)

**Comment by erikrr** [comment]
Hi I had to kick this one because something has changed in a good way.
Not needed the gps for a long time because of no traveling due to COVID.

I was i a city had to find the quickest way to the train so I turned on my gps and OsmAnd.
And while putting it away and checking it I noticed it worked like it once worked so long ago. 
almost instant fix no 20 seconds wait or lock loose lock get lock again after 20 seconds.

The phone S10e is still the same, what has changed meanwhile is the android version 11, and Samsung One Ui 3.1
It seems that one them fixed it or did something that it some the lock in background somehow. 
Don’t know what and how but I am very happy with the end result!

**Comment by sonora** [comment]
Thanks for letting us know ! Glad it works now.

We had meanwhile fixed #10780 (also reported for the S10e). So it was either that or the Android upgrade that fixed it, I think.

**Comment by erikrr** [comment]
Hi one last note. 
I was curious I took my old oneplus 5 android 9, didn’t update. OsmAnd was v338 if I remember correct.
Wanted to see if I can find if it was new android or samsung OS.

to my surprise everything worked as good on my op5 without changing anything.
All problems were solved there too! Don’t know how but this is we’re I stop looking :-)

**Comment by sonora** [comment]
Google sometimes introduces issues, then fixes later, e.g. via  Google Play Services, see e.g. #10864. Maybe it was something along those lines.
