### ISSUE TITLE
Speed limit widget can't be deactivated in browse map profile

### ISSUE THREAD

**Issue by TomTurnschuh** [osmandapp/Osmand#7745]
In the ‹browse map› profile the ‹speed limit› widget is not available for (de)activation. It is always activated when centered the map to current position.

It would be nice, if this widget could be included in the corresponding widget list of the ‹browse map› profile.

Regards

**Comment by vshcherb** [comment]
Yes actually the widget is part of the problem, we don't scan user street name and road he is located cause it is impossible to do for generic profile we can do it only if we know navigation type. So, that's why widget could be visible but no information will be there. This fucntionality is only available in car, bicycle, pedestrian
