### ISSUE TITLE
Measure distance: Allow to use different navigation types for each segment.

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd#7751]
We need to redesign Measure distance UI to it make possible to allow to use different navigation types for each segment.

**Comment by sonora** [comment]
@vshcherb On the occasion we can also consider if we do not want to rename the functionality from 'Measure distance' to 'Plan a trip'. From what I see this is the much more popular use of the feature with all my runner or biker friends, but you always have to show them the feature first because it is so hidden behind its current name.

**Comment by vshcherb** [comment]
@sonora it's definitely a plan! We consider 2 name in design now "Plan a trip" and "Create new trip". Actually Measure distance will be moved to plugin which will open if configure a stripped version of "Plan a trip" only for measurement purposes or may be the name will be lost.

**Comment by vshcherb** [comment]
Nightly builds have feature supporting it.
