### ISSUE TITLE
Routing: Unnecessary detour

### ISSUE THREAD

**Issue by exploide** [osmandapp/Osmand#7772]
I noticed a strange detour when using the OsmAnd offline routing. Car routing, fastest route, mostly default settings. OsmAnd version 3.4.8, map data from October 2019.

OSM link with the relevant part of the route:
https://www.openstreetmap.org/directions?engine=graphhopper_car&route=49.86901%2C8.65616%3B49.87014%2C8.65687#map=19/49.86962/8.65705&layers=N

The following screenshot shows how OsmAnd likes to route over Nieder-Ramstädter Straße and back to Karlstraße, which is unnecessary and unlikely to be taken by a driver.

![osmand-routing-darmstadt](https://user-images.githubusercontent.com/5670236/67699241-1e53a480-f9ac-11e9-9bd3-d70e58c32fa0.png)

May it be the case that OsmAnd weights in the `level_crossing`s? On the ground, they do not hinder driving straight on Karlstraße.

**Comment by pkoevesdi** [comment]
I can add a lot of examples that seem similar to me. I postet some of them here:
https://groups.google.com/forum/#!msg/osmand/mhYaEyZPjFQ/2bjoU60nAwAJ
Please fix the routing. It's almost useless like this, it's so sad, since it used to workd fine. I almost never get the shortest pedestrian route, compared to what's obviously shorter.
OsmAnd+ 3.5.5

**Comment by elgaard** [comment]
This car routing probably happens because OsmAnd it too eager to avoid traffic signals.
In many cases the longer route probably would be taken by some drivers, except that the sharp turn is often illegal or dangerous. Which means that we should add a turn restriction in OSM.
 
And in this case, seeing the aerials, the Nieder-Ramstädter Straße U-turn point https://www.openstreetmap.org/node/3819862779 should be moved towards east.

**Comment by vshcherb** [comment]
To this issue: turn restriction is added.
@pkoevesdi : the routing is not broken. It is a configuration which everybody can change and lower penalty for traffic signals.
It is still very important: **to introduce proper turn restrictions** to the roads regardless of what is the routing configuration there are multiple usage of the route restrictions i.e. "avoid roads", using traffic jams and etc, so the data correctness is important to not create impossible maneuvers. 
When the routing configuration is discussible then the data correctness is a pretty obvious goal

**Comment by kreuzschnabel** [comment]
Same through the city of Wiesbaden. OsmAnd takes an entirely unnecessary detour when passing [here](https://osm.org/go/0DenyFz04?m=) southbound. Instead of following the main road, it takes the longer way around the Ringkirche church, see: https://ibb.co/C840wh2

There’s nothing wrong with the tagging in OSM so I think OsmAnd tries to avoid two traffic signals that way (which are actually linked for quick pass, so they are really not much of a hindrance).

OsmAnd+ 3.5.5, Car profile, Fastest route, Lineage 16.0 (Android 9), Live maps as of Sat 2020-02-15, static maps of Feb 01.

--ks

**Comment by kreuzschnabel** [comment]
Supplement to pevious post: Turn restriction added, so this won’t happen with the next update. 

However, I still think the traffic signals penalty is too high. Maybe I can change this myself but first, I don’t know how to do this, and then, I don’t know how far it should be changed – 5 secs? 1 sec? 0.1 sec? No experience with that, sorry. A router should bring properly values along out-of-the-box.

--ks

**Comment by scaidermern** [comment]
> However, I still think the traffic signals penalty is too high. Maybe I can change this myself but first, I don’t know how to do this, and then, I don’t know how far it should be lowered – 5 secs? 1 sec? 0.1 sec? No experience with that, sorry. A router should bring proper values along out-of-the-box.

I agree. Since introduction of traffic signal penalties there have been dozens of similar cases leading to very strange routing decisions like the one described above.

Maybe use the traffic signal penalty for calculating the estimated arrival time but _don't_ use it for influencing the route calculation since this obviously leads to very strange decisions. Not sure if this is possible with the current routing engine, though.

**Comment by pkoevesdi** [comment]
I also strongly agree. As a pedestrian, I used to be exulted over the good routing of Osmand compared to google maps. Since some point, probably an update, it became totally stupid and unreliable to get thte shortest route. Even the better maps didn't countervail that problem.
I often switched back to google maps.
So, please get back to the routing of before. Just give me the shortest route for pedestrian navigation. Not the fastest or whatever osmand thinks to do.

**Comment by natrius** [comment]
> Maybe use the traffic signal penalty for calculating the estimated arrival time but _don't_ use it for influencing the route calculation since this obviously leads to very strange decisions. Not sure if this is possible with the current routing engine, though.

This sounds good. And make it opt-out, so i can decide if you should decide for me :)
