### ISSUE TITLE
Add more color schemes for Contour lines

### ISSUE THREAD

**Issue by EugeneZmeuk** [osmandapp/Osmand#7808]
There is a problem of seeing Contour lines when we use Underlay (Sattelite) with dark pictures. It will be more convenient to have more color schemes for Contour Lines.
It's the issue for iOS and Android versions of OsmAnd.

This is examples of Sattelite images with Light and Dark brown:
![image](https://user-images.githubusercontent.com/44466116/67933539-0ad85180-fbd7-11e9-8d54-02a727c242c0.png)
![image](https://user-images.githubusercontent.com/44466116/67933613-365b3c00-fbd7-11e9-9288-1762bd49759b.png)

We have only a few colors in menu for Contour lines. It's not enough for our use-case.
![image](https://user-images.githubusercontent.com/44466116/67933685-5c80dc00-fbd7-11e9-9a2c-9b605bf2a484.png)

**Comment by DFyson** [comment]
More options or option to select a custom colour selector would be useful, but otherwise looks like it could be done (I haven't tried) by editing the default.render.xml by adding colour profiles [here](https://github.com/osmandapp/OsmAnd-resources/blob/5fbc3dc4ad7ab8b3bd3f298cc44b95b83b8655bf/rendering_styles/default.render.xml#L1018) and a selection for the profiles in the menu [here](https://github.com/osmandapp/OsmAnd-resources/blob/5fbc3dc4ad7ab8b3bd3f298cc44b95b83b8655bf/rendering_styles/default.render.xml#L11192).

**Comment by xmd5a2** [comment]
Fixed https://github.com/osmandapp/OsmAnd-resources/commit/0146c046330680e3f1f0bac24186e8cbc6fcbbc5
