### ISSUE TITLE
Test voice prompts text is different from the text pronounced, (In development plugin)

### ISSUE THREAD

**Issue by dbojan** [osmandapp/Osmand#7827]
Hi,
I am using test voice prompts page, in development pluging in Osmand.

There are some differences between what the page in the program says, and what is pronounced.
Here are the examples for "en" voice prompts, and also voice prompts for "en-tts" are mentioned where relevant:

For all (1.x) test prompts, text on the page issays "New route calculated ...", but the voice says "The trip is ...".   (The same thing also happens with "en-tts" voice prompts)

(1.2)  New route calculated, 1350m, 3680sec (01:01:20)" voice : ... time is one hour, one minuteS. (Should be one minute, not minutes)

(1.3)  New route calculated 3700m, 7320sec (02:02)". Voice: the trip is about 3 kilometers. en-tts voice: the trip is about 4 kilometers. (Which one is correct?)

(2.1)  Route recalculated 11500m, 18600sec (05:10)".  Voice: ... distance 11 kilometers. en-tts voice: .. distance 12 kilometers.  (Which one is correct?)

(2.2)  Route recalculated 19633m, 26700sec (07:25)". Voice: ... distance 19 kilometers. en-tts voice: .. distance 20 kilometers.  (Which one is correct?)

(2.3)  Route recalculated 89750m, 55800sec (15:30)". Voice: ... distance 89 kilometers. en-tts voice: .. distance 90 kilometers.  (Which one is correct?)

(2.4)  Route recalculated 125900m, 92700sec (25:45)". Voice: ... distance 125 kilometers. en-tts voice: .. distance 126 kilometers.  (Which one is correct?)

(3.1)  After 1520m turn slightly left. Voice: after about one kilometerS turn slightly left. (Should be one kilometer, not kilometers)

en-tts voice: after about TWO kilometers turn slightly left.  (Which one is correct?)

(3.2)  In 450m turn sharply left onto 'Hauptstrasse', then bear right". Voice: In 450m turn sharply left then KEEP right. (also in en-tts)

(3.5)  In 370m turn slightly right onto 'Route 23' 'Main Street', then bear left". Voice : In 370m turn slightly right then KEEP left (also in en-tts)

(6.4)  When possible, make a U-turn". Voice: Make a U-turn. ('When possible' is missing) (also in en-tts)

(7.1)  Straight ahead". Voice: GO Straight ahead (also in en-tts)

(8.1)  Arrive at your destination 'Home'". Voice: You have reached your destination. (Different text?) (also in en-tts)

(8.2)  Arrive at your intermediate destination 'Friend'". Voice: You have reached your intermediate destination. (Different text?) (also in en-tts)

(8.3)  Passing GPX waypoint 'Trailhead'". Voice: You are passing GPX waypoint. (Different text?) (also in en-tts)

(8.4)  Passing favorite 'Brewery'". Voice: You are passing favorite. (Different text?) (also in en-tts)

(8.5)  Passing POI 'Museum'". Voice: You are passing POI. (Different text?) (also in en-tts)

(9.1)  You are exceeding the speed limit '50' (18 m/s)". Voice: speed Limit. (Different text?) (also in en-tts)

(9.2)  Attention, speed camera". Voice: Attention, speed cam. (Different text?) (also in en-tts)

(9.9)  Attention, tunnel". Voice: Attention.  ('Tunnel' is missing)

en-tts:

(7.3)  Continue for 360m to 'Broadway' and arrive at your intermediate destination ' '".  Voice : ...continue for 350 meters...

Thanks.

**Comment by sonora** [comment]
Hi, I did this by design:

The type of prompt I specify in the button caption, and the numbers, and the spelling of street names etc. is what is being send to the OsmAnd voice processing and and the Android voice engine.

In particular the numbers are designed such that you see the correct, meaningful rounding is applied. E.g for car in mid range distances the voice config files should round to the nearest 50m, it makes no sense to announce stuff like "Turn left in 247-point-58 meters".

Similar, if you see a plural expression when pronouncing "1", it indicates an error in the config file you are testing.

Meaning: What you hear is how the voice you selected pronounces the input, e.g. the "route is calculated" message in most languages is pronounced by announcing the predicted trip distance and duration. But you can certainly also design a voice where it says "Hey Dude, your route is ready!" :) There is no intention the prompts 100% mimic the caption, this is up to how you design your voice config file.
