### ISSUE TITLE
Several Contour Lines cannot be updated 

### ISSUE THREAD

**Issue by katerynakocherhina** [osmandapp/OsmAnd#7875]
Both in Android and iOS OsmAndversions, the contour lines can no longer be updated:
Norway
France Occitania
Veneto,
Slovenia,
After removing the maps and downloading them back they are displayed as updated, but after restarting OsmAnd, they are required to be updated again.

**Comment by zekooooo** [comment]
Same behavior for me with Slovenia (don't have any of the others). After updating, the contour map now shows up green as up to date in the menu, but when I restart the app it's back to yellow - needs update. Using OsmAnd 3.5.3 on Android 7.0

**Comment by pebogufi** [comment]
same as #7635

**Comment by zekooooo** [comment]
The 20th Feb contour update seems to have come thru for Slovenia. I've downloaded the update and restarted my phone and the entry hasn't reverted to the updates available list.

**Comment by RufioHugo** [comment]
So ... I searched github but found no sollution;
since Nov'2020 I've got some contur lines (mainly Germany) that will not update.

Version 3.8.5 on different Android (7-9)!
Tried uninstall contour lines and reinstall - tried uninstall all maps and reinstall - even tried uninstall app and reinstall ... nothing changes. Any other idea what I should try?

RH

**Comment by vshcherb** [comment]
3.9.5 fixed it.
