### ISSUE TITLE
World base map shows only large cities at zoom 9 and higher

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/Osmand#7904]
Since recently the world base map lacks a lot of details for zoom level 9 and higher.

Left: Zoom level 8. Base map shows cities, roads, rivers and land use.
Right: Zoom level 9. Base map shows only cities.

![photo_2019-11-12](https://user-images.githubusercontent.com/1040784/68651690-2f61f100-0528-11ea-9a73-6b04b56d1393.jpg)

**Comment by sonora** [comment]
See here: https://github.com/osmandapp/Osmand/issues/7756#issuecomment-549043110

**Comment by scaidermern** [comment]
> See here: [#7756 (comment)](https://github.com/osmandapp/Osmand/issues/7756#issuecomment-549043110)

Thanks! However I guess I don't fully understand it. My regional maps are either up to date (from November) or deactivated. Moreover this issue appears world-wide for me.

**Comment by sonora** [comment]
From how I understand it, the new world basemap (which you probably have updated to) only contains data zooms 2-8 now, while the old one contained up to zoom 11. In regions where you do not have a regional map, the 'city only' data you now see at zooms 9-11 must come from the 'mini basemap', which is internal part of the app these days (and seems to contain city data only, zooms 2-11, it seems).

**Comment by scaidermern** [comment]
I see. So it is intended behavior to have less details with the new world map on zoom levels >9? Why not show the details already present on zoom levels <=9 if no regional map is installed? It feels very weird to suddenly loose a lot of details when zooming in.

**Comment by sonora** [comment]
Well, I was not part of the decision , but I guess was intended that the cutover between the world basemap and the regional maps is now at zoom 8/9, and not at 10/11 any more. In my mind it is a pity because you are losing a information for the case that you end up offline in a region for which you have no detailed map on your device.

Regarding your suggestion to show elements of other zoom levels if you do not have a map with actual data for a given zoom level: Yes, I very much advocate that, too. I think it did at least work before the zoom cutover change under the precondition that you watched an area ENTIRELY without a detailed map (unlike your screenshot which shows a screen portion with and one without detailed map). Now it seems it does not work anywhere, I only see the town info for regions without detailed map.

**Comment by vshcherb** [comment]
We intentionally display less information to make visible what information is missing, we also don't display polygon and lines to not run into double-line issue where they are both displayed and don't match 100%. 

So we left with idea to display only points after 8th and suggest to download map. It is intentional regression to make basemap much smaller and future-proof, probably we can build new basemap and keep it open though we are not going to distribute it cause it was over 400 MB already
