### ISSUE TITLE
Small buildings do not show up

### ISSUE THREAD

**Issue by pietervdvn** [osmandapp/Osmand#7910]
When looking to [this area](https://www.openstreetmap.org/query?lat=6.84854&lon=47.41142), small buildings such as [this one](https://www.openstreetmap.org/way/650619664) do not show up. Is it possible they are removed during .obf-creation or that they are to small to show up? (Note: i've enabled 'More Details')

MSF is on a mission there, and the local refugee camp mappers want to add every last tent and small hut. These buildings not showing up onto the maps is quite confusing for them.

Osmand+ Nightly 3.5.0#28299m, 2019-10-31, offline maps of Somalia (november download)

**Comment by vshcherb** [comment]
These buildings are too small to be significant, probably we can display them as points and apply same strategy as for trees

**Comment by Jorieke** [comment]
Hi @pietervdvn and @vshcherb thanks helping us out with this question! 

We are with MSF indeed doing a survey in the area. We basically need to visit 100 households in the area, so we randomly select with help of Qgis 100 buildings that are mapped on OSM. We'll add the sampled points as GPX into OsmAnd, and the teams on the ground navigate to the points like this. Since for some people who are working with us it is the first time that they use a smartphone and maps, we like to keep the process as simple and easy as possible. And having all buildings on the map will help them navigating so much better!

**Comment by scaidermern** [comment]
Related to #4488.

**Comment by xcharles1990** [comment]
Hello!
Thx to consider this issue!
just to be super pricese the issue occurs on the all area https://www.openstreetmap.org/query?lat=6.84854&lon=47.41142#map=13/6.8427/47.4450

thanks again

**Comment by vshcherb** [comment]
Fixed https://github.com/osmandapp/OsmAnd-core/pull/109, should be visible on certain zooms
