### ISSUE TITLE
Bicycle: (visually) distinguish between stairs with and without ramp for bicycles

### ISSUE THREAD

**Issue by Famlam** [osmandapp/Osmand#7919]
For a bicycle, a stairs (highway=steps) with a bicycle rail (ramp=yes/ramp:bicycle=yes) is a relatively small burden, you dismount and push your bike forward over the rail up or down the stairs.

However, if there is no rail on the stairs, you are more-or-less forced to carry your bike up or down, which is pretty intensive (and more dangerous), especially for longer stairs.

Hence, I would like to request that (in bicycle mode) there is a visual distinctions between ramp and ramp-less stairs. For example, by adding a thin line on the side of the drawn "highway=steps" way if a bicycle rail is present.

Would this be possible to implement?

OsmAnd 3.5.1, offline maps, on Android

**Comment by quax2712** [comment]
I used mapnik.render.xml to add a lot of things that are important for bicycle touring.
To distinguish I called it mapnik_RS.render.

Is it possible to publish this file anyhow to other users ?

example to ramp:
	filter additional="ramp:bicycle=yes" strokeWidth_5="8" color_5="#00aa00"
	filter additional="rampbicycle=yes" strokeWidth_5="8" color_5="#00aa00"
        filter additional="ramp(bicycle)=yes" strokeWidth_5="8" color_5="#00aa00"

this makes stairs green instead of red.

I although changed routing to allow this kind of steps, but of course with low priority :-)
		
greetings rainer
