### ISSUE TITLE
U-turn issue

### ISSUE THREAD

**Issue by katerynakocherhina** [osmandapp/Osmand#8011]
From 53.48379N 6.20048W

To 53.47324N 6.20276W

The issue occurs at: 53.47878° N, 6.20279° W

![image](https://user-images.githubusercontent.com/50198677/69892574-d8c22880-1317-11ea-81ff-0610e3fdd6a5.png)

**Comment by pebogufi** [comment]
The positions of from/to (Ireland near Dublin) and position of screenshot (Kiew Ukraine) differ by more that 2500 km. So please check whether you really want to drive that route... :-)

**Comment by katerynakocherhina** [comment]
From 53.48379N 6.20048W

To 53.47324N 6.20276W 
The area of the issue is present on the screenshot

**Comment by pebogufi** [comment]
Yes, compare the values, 
~ 6.20 WEST
vs 
30.5063 EAST
That is far away.

**Comment by vshcherb** [comment]
For some extreme values instead of Turn Left, we exchange to U-turn cause it is a u-turn sometimes in OSM. So probably it is easier to make this turn less sharp in OSM

**Comment by rivermont** [comment]
If the turn in question is happening on [n791059835](https://osm.org/node/791059835) then it's probably actually a routing issue. The angle is correct but a car should never be turning left onto the ramp; they should go through the roundabout and onto the other ramp.

A no-left-turn restriction in OSM would fix this case but that's not really a good solution.

**Comment by rivermont** [comment]
So I've added turn restrictions (78343382)[https://www.openstreetmap.org/changeset/78343382] to prevent this case from happening, but the routing problem still may exist elsewhere.

I think the router is avoiding the traffic light ((n246805286)[https://www.openstreetmap.org/node/246805286]) by taking a marginally longer route - leaving the roundabout and coming back. Somehow the penalty on the light outweighs the distance penalty. I'm not sure the solution to this since that is correct router behavior; maybe they should sanity-check for impossible turns and penalize them?

In any case this issue can be closed unless a discussion around the routing is wanted. The changes will take a little bit to appear in the region files but it should route through the roundabout once they're updated.

**Comment by vshcherb** [comment]
@rivermont we verify every case separately and you're right about traffic signals penalty. We've lowered multiple times since introduction though penalty for traffic lights really works great when choosing the best route in the city. In many cities there are decent highways without traffic lights and that's exactly the best route. 

We're considering to have extra penalty for very sharp turns cause in most of the cases it looks like a map data error (i.e. the turn is forbidden).
