### ISSUE TITLE
Berlin: pedestrian routing problem (cause HW=1.2)

### ISSUE THREAD

**Issue by elgaard** [osmandapp/Osmand#8023]
Routing for foot from Oberbaumbrucke in Berling to Schlesische Straße, Osmand finds the longer route along Oberbaumstrasse instead of Falckensteinstraße.
OSRM works as expected
https://www.openstreetmap.org/directions?engine=fossgis_osrm_foot&route=52.50087%2C13.44474%3B52.49986%2C13.44433#map=19/52.50036/13.44433

And Osmand/bicycle works.

This is Osmand 3.5.3 on Samsung S5
fresh offline maps 2019-11-01
![Screenshot_2019-11-28-20-19-06](https://user-images.githubusercontent.com/779040/69914838-ffcc4780-1448-11ea-88a6-46b46c1ba3b0.png)

**Comment by pkoevesdi** [comment]
I'd consider this issue as a duplicate to this, at least connected:
https://github.com/osmandapp/Osmand/issues/7772
In case it's not, here are more examples of horrible pedestrian routing like the one above:
https://groups.google.com/forum/#!topic/osmand/mhYaEyZPjFQ

**Comment by hklene** [comment]
I found, switching back and forth between bicycle and pedestrian sometimes didn't recalculate the route (the bike avoiding a staircase you won't mind on foot to spare you a detour). But as a workaround switching to car and back to either bicycle or pedestrian usually solved the issue.

Minimal changes in the start / end position can completely overthrow the chosen route. Compare:
https://www.openstreetmap.org/directions?engine=fossgis_osrm_foot&route=52.26690%2C10.52982%3B52.27081%2C10.53278#map=17/52.26887/10.53080
https://www.openstreetmap.org/directions?engine=fossgis_osrm_foot&route=52.26684%2C10.53034%3B52.27081%2C10.53278#map=17/52.26877/10.53171
https://www.openstreetmap.org/directions?engine=fossgis_osrm_foot&route=52.26693%2C10.53021%3B52.27081%2C10.53278#map=17/52.26885/10.53156

This is even more unexpected, as we are used to the "laziness" of the routing algorithm trying to cheaply "repair" a route, in case we left it. This can get as bad as trying to send you all the way back to your starting point, because you didn't properly pass through.

**Comment by pkoevesdi** [comment]
In Your examples I don't see change in destination point. The changes in the starting point also change the route right FROM the starting point. Which is not so unexpected to me (besides that it's in example 1 surely not the shortest route).

What I observed on OsmAnd+ is, that a change in the starting point changes the route LATER on: AFTER a piece of common routing among the different starting points, THEN there comes a piece of different routes. So, that's as You said: even more unexpected, because of the laziness... How come, he starts the route the same way, to later on decide differently depending only on the starting point?

Anyway, the main problem is: OsmAnd doesn't find the shortest allowed route for (not only?) pedestrians.

**Comment by elgaard** [comment]
On this route I can change between the short and the long route by toggling "use elevation".
Although there is not much change in elevation and Osmand thinks the short route is 2 minutes faster.

Also the default speed for pedestrian was 4 km/h. If I change it to 3, then Osmand finds the short route. If I change it to 5 Osmand find the long route.

There must be something on Falkensteingstrasse, that result in some kind of routing penalty.

(this is with Dec 1 map)

![image](https://user-images.githubusercontent.com/779040/70278208-22958d80-17b4-11ea-856f-4f12791c5e42.png)
![image](https://user-images.githubusercontent.com/779040/70278300-4c4eb480-17b4-11ea-9c04-949c3bfbe347.png)

**Comment by VIMVa** [comment]
I find node 834384766 ONLY in the Falckensteinstraße to have access restrictions (except bicycle). That may be the REASON? And a mapping error?

**Comment by vshcherb** [comment]
This is the problem of suboptimal routing with heurisitcCoefficient=1.2 (if you remove that line in the routing) it will be working correctly.

**Comment by vshcherb** [comment]
https://github.com/osmandapp/Osmand/issues/8035#issuecomment-572506178
