### ISSUE TITLE
New Voice Question

### ISSUE THREAD

**Issue by DemonRem** [osmandapp/Osmand#8038]
Will there be a Hebrew Voice ever for navigation?

**Comment by hvdwolf** [comment]
OsmAnd can use "recorded voices", which is actually outdated, or TTS voices. TTS voices are actually the only way forward. For a TTS voice OsmAnd needs a TTS engine like Google TTS or one of the other ones. Google TTS already supports hebrew since 2011.
Using TTS means that you have to create a tts "text-to-speech" file. This is explained [here](https://osmand.net/help-online/technical-articles#Creating%20a%20New%20TTS%20Voice%20Language). 
In this case it means you have to create your own hebrew tts file. Maybe you can find others who can help you. If it is OK, please create a pull request or simply offer it to the OsmAnd team addition.

The voices are [here](https://github.com/osmandapp/OsmAnd-resources/tree/master/voice). Note that hebrew uses the iso-639-1 code "iw", which is indeed not available yet in OsmAnd.

**Comment by Rbagman** [comment]
I don't hear any sounds from this app, is there a switch I've overlooked?

**Comment by hvdwolf** [comment]
This is a list for issues/incidents. Not user questions.
Please register and go to the mailing group for those questions: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!forum/osmand

**Comment by sonora** [comment]
Here's a little debugging guide I once wrote: https://osmand.net/help-online/faq#tts_not_working. Please also check if you did not accidentally mute the voice prompts in OsmAnd's Navigation settings or on the route definition dialog.

**Comment by hvdwolf** [comment]
Why is this closed? 
The op asked about Hebrew tts for OsmAnd, which is either a feature request or a nice to have. Rbagman hijacked this issue for his user question.
I think this issue should be re-opened and flagged as feature-request or nice to have, where the op canwork himself on the solution.

**Comment by sonora** [comment]
Well, the answer is there will be a Hebrew TTS voice when someone creates a file for it. :)

I have referenced my tech articles how to do that. If anybody sends me a file, I will gladly add it to our code - no benefit in keeping an issue open for it.
