### ISSUE TITLE
Switching to Hebrew is useless

### ISSUE THREAD

**Issue by yarons** [osmandapp/Osmand#8042]
I tried switching the app language to Hebrew, I got the restart dialog, asked for a restart, it's still in English, did the same in Arabic, the app switched to Arabic.

Hebrew is indeed incomplete but it's 99% complete, most of the strings should appear in Hebrew, could it be due to a confusion between he and iw language codes?

**Comment by max-klaus** [comment]
Looks like "he and iw" issue.

**Comment by sonora** [comment]
Yes, I am convinced it is the notorious Android iw vs. he issue.
I have gone through all my test devices Android 4-9, and do not seem to find a single one where the correct (new) ISO code he works. I also know of no good way to reference he if the device expects iw, looks like all methods suggested in the literature have drawbacks. And surely we do not want to sync-duplicate our resource folders.

Maybe we test the wotkaround to use iw instead of he, it may work better for a majority of devices?

**Comment by yarons** [comment]
How do you feel about symbolic linking where necessary?

>

**Comment by yarons** [comment]
Still not working, it's been over half a year, why am I still putting effort if nobody can use it?

**Comment by vshcherb** [comment]
Is it IOS / Android? He/iw should be supported natively by OS, so you can try to switch language in the OS to get it working.

**Comment by yarons** [comment]
I'm too poor for an iPhone so it's an Android :(

I tried switching manually and it didn't work, I'm not sure about `iw`, `he` is the proper code but it has'nt always been like that.

**Comment by sonora** [comment]
Just wondering: What language is your Android (device settings, not OsmAnd settings) set to? Does your device itself (and other app) also not show Hebrew, or is it just OsmAnd?

i would like to test the following combination: Set ypur device to Hebrew, and set OsmAnd to 'System language'.

**Comment by yarons** [comment]
I'm using English no my daily driver device.

VLC works in Hebrew for example, not many apps allow you to select your locale and override the system settings.

I don't want to set my language to Hebrew it can mess up a lot of things, I'll see if I can find someone with Hebrew Android.

**Comment by vshcherb** [comment]
We will check what's going on probably it is Weblate has chosen wrong configuration. 
Probably we need to rename folder "values-he" to "values-iw" and change it everywhere.
@Chumva
