### ISSUE TITLE
Roundabout bicycle navigation issue

### ISSUE THREAD

**Issue by katerynakocherhina** [osmandapp/Osmand#8069]
From: 51.97204° N, 7.59707° E
To: 51.96873° N, 7.55989° E
There is a roundabout at 51.97361° N, 7.59035° E
During the navigation in the cycle profile, OsmAnd suggests exiting the roundabout on the 6-th road, while it is actually the 3-d.

**Comment by vshcherb** [comment]
This is probably a map issue cause exits don't have bicycle:no on the oneway or we need to restrict bicycle going by oneway to another direction

**Comment by xmd5a2** [comment]
Can't figure out what's wrong with this route
![Screenshot from 2019-12-20 15-00-49](https://user-images.githubusercontent.com/5829014/71253681-a06fa200-2339-11ea-882c-834b02c9cf30.png)

**Comment by katerynakocherhina** [comment]
xmd5a2, on the roundabout at 51.97361° N, 7.59035° E, in the cycle profile the number of suggested exit is not obvious

**Comment by xmd5a2** [comment]
In my tests suggested exit number is 7
![Screenshot_2019-12-20-16-25-42-069_net osmand plus](https://user-images.githubusercontent.com/5829014/71257782-a79cad00-2345-11ea-98a8-ee6c25d447ab.jpg)
Actual exit number should be 5-th because of park entrance and https://www.openstreetmap.org/way/11846134 without bicycle restriction.

**Comment by MadWasp79** [comment]
Strange. It calculates correctly for me.
![image](https://user-images.githubusercontent.com/13146346/72334401-eb28d380-36c5-11ea-86a9-54165b63587f.png)
