### ISSUE TITLE
Bus route issue

### ISSUE THREAD

**Issue by katerynakocherhina** [osmandapp/Osmand#8125]
The bus route (51.04613/3.70168) cannot be used for navigation in OsmAnd. However, it is present on the map and in the OSM source:
https://www.openstreetmap.org/relation/9594575

**Comment by thibaultmol** [comment]
For context: it's a shuttle bus provided for free by the city. To connect a Park & Ride to the city center.
It's not operated by the Belgium bus transport company (De Lijn).

But I still think it should still show up in Osmand's public transport tab. Because I wouldn't have even known it existed without having seen the bus irl

**Comment by xmd5a2** [comment]
This is because route relation doesn't have "ref". Looks like it is a bug in osmand map creation process.

**Comment by vshcherb** [comment]
https://github.com/osmandapp/OsmAnd-tools/pull/340
