### ISSUE TITLE
Allow addresses to be shared to Osmand

### ISSUE THREAD

**Issue by Friptick** [osmandapp/Osmand#8201]
Please allow text to be shared from other apps to Osmand's search box!

This seems like a huge oversight. It would mostly resolve #5735 and be the obvious mirror of #5932 (outbound sharing). *Mainly it is a super necessary feature which is super simple to implement.*

At present, if you select a textual address from the browser, or messenger, or The Popular Map App, and hit "share", you can share the address to just about every app on Android except Osmand. *That is crazy!* Especially since The Popular Map App generates shortcodes which actually work in Osmand's search feature.

Osmand is an amazing project and this issue tracker seems to be drowning in non-triaged issues. But really, this one is particularly obvious, and useful, and easy to fix.

**Comment by vshcherb** [comment]
If you paste OSM url or OsmAnd url into search box it should work fine.

**Comment by Friptick** [comment]
Thanks for the reply and for your work on the app.

But i am not sure we are talking about the same thing. Or that I can explain it better than I already did.

The use case is: **getting shortcodes from Google into the Osmand search box**. Or from anywhere else that produces a shortcode, _into the Osmand search box_. This is surely super important, not just Nice To Have, because (1) Google is where all the up-to-date address data is found and (2) Osmand's search function can already understand shortcodes.

As detailed in #5735 (latest comment) the process is currently fastidious. If Osmand would just **accept inbound sharing intent for text data**, the whole thing would be much, much easier. It would even then become feasible to import lots of new up-to-date POIs to OSM using the existing Osmand plugin, thereby improving OSM without even needing to be on location.

What am I missing?

**Comment by Friptick** [comment]
Update. It seems that if you select an address in Google Maps, sometimes (_sometimes_) "Osmand" appears in the context menu alongside "Cut", "Copy" etc. (not sure why this behavior is so flaky). Then the selected text can be sent to Osmand's search box as expected. 

**But** if the text contains a shortcode, the shortcode will lose its "+" sign during the transfer! And so it no longer works, and Osmand is back to geo-decoding, with predictably terrible results!

**If address-sharing really is unavailable or broken as described here, that is surely a big deal.** The killer feature of Google Maps is its database of business addresses, which is always up-to-date because the businesses themselves are doing the work. Osmand will never be able to match that. But it can at least make importing easy. Why is no one else bothered?

**Comment by decadent** [comment]
I'd like to point out a different use-case: when browsing the web for shopping or looking for entertainment, I come across a business address, and I want to see how close that place is, without fumbling with an embedded map (if it's even there, which is often not the case in my parts). Osmand's search for the address and then routing work nicely and quickly, but first I have to go through the copy-pasting ritual. This seems suboptimal, especially when done a bunch of times, while there's an OS-wide way to get the clipboard out of the sequence. It would be appreciated if Osmand made use of this capability.

If there's already some intent or an activity that does this, by some chance, even if not through the ‘share’ function, then it might be possible to invoke it with apps like Automate or Tasker. However, we'd need to know the proper way to call the intent or activity and to specify the search text.

**Comment by Friptick** [comment]
> I'd like to point out a different use-case

But that's not a different use-case, it's exactly the **same one**! The same one that unfortunately nobody else here seems bothered about.

On my system I can share a text address from anywhere **to 28 (TWENTY-EIGHT) apps but NOT Osmand**.

Ridiculous and easy-peasy to fix. Or if it's not, then unfortunately nobody cares enough to explain why. Good luck.

**Comment by decadent** [comment]
> If there's already some intent or an activity that does this, by some chance, even if not through the ‘share’ function, then it might be possible to invoke it with apps like Automate or Tasker.

In fact, after looking through the manifest I found the ‘geo:0,0?q=’ address search intent (also mentioned in #1523 and probably elsewhere). It indeed allows to whip up a workaround with e.g. Automate.

For anyone interested: you just call OsmAnd's package in foreground, with a VIEW action (android.intent.action.VIEW) and a url like ‘geo:0,0?q=searchtext’—you'll need to encode the text, of course.

Bit of a pity that it doesn't support both coordinates and the search text at once, preferably with a zoom level (Google's ‘z’ parameter)—or I could make it always search relative to my home instead of the last position, or indeed beginning at various favorite locations. I also briefly tried ‘openstreetmap.org’ urls (supported by OsmAnd), but it seems they likewise do the one or the other.

**Comment by Friptick** [comment]
> For anyone interested: you just call OsmAnd's package in foreground, with a VIEW action (android.intent.action.VIEW) and a url like ‘geo:0,0?q=searchtext’—you'll need to encode the text, of course.

Thanks for the workaround. Unfortunately few end users are going to be do this, even I am not sure whether it is addressed to users or developers.

The reason I opened this issue was to ask for something (presumably) much simpler. Just allow the inbound sharing of arbitrary text strings. A ton of other random apps can do it, nobody including @vshcherb has explained why this is so difficult for Osmand.

Osmand's search box can already decipher text addresses _and_ short codes so the problem is all but solved.

**Comment by vshcherb** [comment]
The bug is certainly confusing we have another 5-10 bugs where our address search doesn't work as expected and they are separated by different issues. 
Here I see the only issue of some integration with other apps? Though I'm missing a point what's broken if you copy address and paste in the search of OsmAnd except that it doesn't find what's expected in certain cases

**Comment by decadent** [comment]
> Though I'm missing a point what's broken if you copy address and paste in the search of OsmAnd

Just to clarify the issue a bit: copy-pasting works fine. The problem is that copy-pasting is rather tiresome on a phone: when text is selected, you need to: tap ‘copy’, go back to the apps to run OsmAnd (two or three taps and possibly some scrolling), then go to search in OsmAnd, tap-and-hold, ‘paste’. Total: five or six taps, possibly scrolling, tap-and-hold.

Via the recent-apps list with two-button navigation: ‘copy’, swipe up, scroll to OsmAnd, tap, go to search, tap-and-hold, ‘paste’. Total: four taps, two scrolls, tap-and-hold. With three-button navigation, it's one tap-and-hold instead of one swipe.

With sharing, you get to the search in OsmAnd in: tap ‘share’ (possibly after ‘...’), scroll through the receiving apps list, another tap. Two or three taps and scrolling.

The difference is not much for one time, but it gets annoying when repeating it over and over, especially the tap-and-hold part. Additionally, at least on my phone, the sharing menu is on the bottom where my thumbs are, while switching to OsmAnd and pasting involves a tap-dance over the screen.

Overall, it's of course a convenience change and not something being broken.

As for the implementation: as far as I understand (being not really versed in Android dev), this feature requires introducing an activity that would handle the sharing intent and then chuck the search text over to the same code that handles ‘geo:0,0?q=’ requests. Of course, I don't know how much testing code and other supporting stuff this entails.

**Comment by Friptick** [comment]
> Just to clarify the issue a bit: copy-pasting works fine. The problem is that copy-pasting is rather tiresome on a phone, at least on Android. When text is selected, you need to: tap ‘copy’, go back to the apps to run OsmAnd (two or three taps and possibly some scrolling), then go to search in OsmAnd, tap-and-hold, ‘paste’. Total: five or six taps, possibly scrolling, tap-and-hold.

Thanks @decadent for describing exactly what is at stake.

@vshcherb: To confirm, this is not a bug, just a missing feature. A simple feature which might be very easy to implement. A feature which, if implemented, would make getting addresses from Google et al into Osmand (and therefore into OSM) much, _much_ easier.

**Comment by vshcherb** [comment]
Yes, we support *geo intent* and support *some intents* of Google Maps the issue that mostly new versions of Google products encode it search terms in a hidden format that only Google Products can understand and parse it. Also some devices cut integration by url i.e. if 1 application request "http://google.com/maps/..." then only Google Maps will be able to handle it. 

Obviously there are missing places of integration but it is better to be specific and check it.

**Comment by decadent** [comment]
I believe Friptick is talking about sharing an arbitrary text selection that might contain an address, or a name of some place, or say a name of business that has multiple shops or offices. At least that's how I understood the issue when I posted my comments. These cases are all handled by OsmAnd's search—the inconvenience lies in getting the selection into the search, as I detailed above.

**Comment by Friptick** [comment]
> Yes, we support _geo intent_ and support _some intents_ of Google Maps

@vshcherb Perhaps this is the misunderstanding. The issue is not with getting addresses from another app, it is about getting them _from anywhere_, which generally means _from the  web_.

As @decadent describes, this process is fastidious when it could be as easy as _(1) Tap-hold to select address (2) Share to Osmand_.

Hope it is clearer now.

**Comment by vshcherb** [comment]
I see what you mean, when you click on phone, it always suggests to open a Phone Caller, same for email. And in some cases it works for addresses and suggest to open Maps (-> Google Maps). I'm not sure how it works and whether it is Public API or not. I will need to check it.

**Comment by Friptick** [comment]
> I see what you mean,

@vshcherb But that is not what I mean. That is complicated and I am asking for simple. Apparently I am not good at this, @decadent did a better job:

>I believe Friptick is talking about sharing an arbitrary text selection that might contain an address, or a name of some place, or say a name of business that has multiple shops or offices. At least that's how I understood the issue when I posted my comments. These cases are all handled by OsmAnd's search—the inconvenience lies in getting the selection into the search, as I detailed above.

Is is clearer?

**Comment by vshcherb** [comment]
![image](https://user-images.githubusercontent.com/1042025/81916619-516e2600-95d4-11ea-8587-e8afbed34169.png)
Paste is visible here

**Comment by Friptick** [comment]
@vshcherb This is getting ridiculous but I am going to assume good faith. _Please_ just read carefully what I and @decadent have written. I do not know how the issue could be described any more simply, but you still have not understood. You seem to be skim-reading or something. 

_We know_ that it is possible to copy-paste into the search box. That is not the issue. The issue is in the title and described in detail in the posts above.

Sorry to have to be so terse.

**Comment by decadent** [comment]
For the record, #9297 is the relevant pull request now.

**Comment by erdmark** [comment]
Please note that the license of Google Maps is not compatible with the one of OpenSreetMap, so please don't copy data between these two, not even addresses.

**Comment by Friptick** [comment]
> Please note that the license of Google Maps is not compatible with the one of OpenSreetMap, so please don't copy data between these two, not even addresses.

Huh? A street address is not the intellectual property of Google. This issue was about making Osmand more useful to users, and Google Maps less useful.
