### ISSUE TITLE
Bug: fuel efficient route does not work after profile change

### ISSUE THREAD

**Issue by pebogufi** [osmandapp/Osmand#8304]
After having some trouble with the same thing, I uninstalled osmand and made a new install with nighty 3.5.6#28802 (2020-02-22). Then I calculated a route with basic car profile
from 48.04328° N, 7.87788° E
to 48.53205° N, 8.21730° E
- fast route which went via motoway
- fuel efficient route which went directly and shorter.

So far so good.

Then I created a profile for my caravan with routing-caravan.xml which had a heuristicCoeff of 1.3 and slower speeds.
Now the problem returned:
The fuel efficient route was no more different from fast route.

Then I removed the new profile and deleted the routing-caravan.xml.
No change - fuel efficient route did not work, calculation was like fast route.
For me it looks like that there are data from the other profile, which are NOT reset by profile change. 

@hvdwolf 
See also https://github.com/osmandapp/Osmand/issues/8019 with comment of Dec 4, which describes also a problem of unchanged data after profile change.

**Comment by pebogufi** [comment]
Next test:
I downloaded original routing.xml and created a profile with it.
No change in problem.

**Comment by vshcherb** [comment]
Please share your routing-caravan.xml, so we can try to test it and see the difference

**Comment by pebogufi** [comment]
[routing-caravan.zip](https://github.com/osmandapp/Osmand/files/4104769/routing-caravan.zip)

**Comment by Chumva** [comment]
I cannot reproduce it for now, can you check it in new nightly or record a video?

**Comment by pebogufi** [comment]
It is mysterious..
-- On my smartphone Samsung S7, Android 8, osmand nightly of today: 3.5.6#28925
profiles are only default, no user definef ones, dir routing is empty.
After having the problem that fuel efficient did not work, I went to:
navigation settings / vehicle parameters / default speed
and pressed "revert".
The three values did NOT change (!) but after that the fuel efficient route calculated as expected a different route. Several times switching fuel efficient route on and off always different for on/off and correct !!!
That is now fine.

-- Test with tablet samsung tab a 2016, Android 8, osmand same nightly of today: 3.5.6#28925
car profile is default, but routing-caravan.xml in dir routing for profile caravan.
- Profile car. After having the problem that fuel efficient did not work, I made a revert as above.
Now fuel efficient route is also ok.

- Profile caravan with routing-caravan.xml
Revert for speed values does NOT help.

**Comment by pebogufi** [comment]
After two more "revert" it also works with tablet and own profile for caravan.
DONT ASK ME WHY ...

**Comment by pebogufi** [comment]
@Chumva @vshcherb 
No i can tell you how to reproduce the bug:
osmand same nightly of: 3.5.6#28925. 2020-02-06.

- Profile caravan with routing-caravan.xml
After Revert for speed values fuel efficient route works as expected, it is different from fast route. That is OK.
When changing one of the speed values (min, default, max) (in navigation settings / vehicle parameters / default speed) with the slider, the fuel efficient route does NOT work any more, the route will be the same as fast route.
After revert again, the fuel efficient route is Ok AGAIN.
This can be repeated as often as you like it.

- Next test with car (default = base) profile.
-> same behavior. Changing speed with slider => calculation of fuel efficient route is broken. 
After Revert => ok again. May be a revert must be done more than one time.
Hope you can also reproduce that.

**Comment by pebogufi** [comment]
May be not only the revert but also the the change with the slider must be done repeatedly, it looks like that there is something like a delay for using the changed values.

**Comment by OpenSourceForEver** [comment]
Related with https://github.com/osmandapp/Osmand/issues/8224 ? I am trying to change values in routing.xml (speed for diferent types of PT and time per stop) and changes do not affect to calculated routes.

**Comment by pebogufi** [comment]
In routing-caravan.xml I set the speed values 
	<routingProfile name="car" baseProfile="car" restrictionsAware="true" minSpeed="**19**.0" DefaultSpeed="**39**.0" maxSpeed="**94**.0" leftTurn="5" rightTurn="5" roundaboutTurn="5" onewayAware="true" heuristicCoefficient="1.4">
After a Revert I have the values: 19, **45**, 94. The Dafault value is not changed !!

**Comment by hvdwolf** [comment]
@pebogufi You change the default speeds in the .xml. I don't do that. I simply leave them to the default. I have one mycar15.xml with default settings and speeds, with only difference the hc=1.5, both in the heading of the file (<attribute name="heuristicCoefficient" value="1.5" />), as well as in the car profile itself (<routingProfile name="car" baseProfile="car" restrictionsAware="true" minSpeed="20.0" defaultSpeed="45.0" maxSpeed="130.0" leftTurn="5" rightTurn="5" roundaboutTurn="5" onewayAware="true" heuristicCoefficient="1.5">).
Inside Osmand I create a profile "mycar 15" and a profile "mycaravan 1.5", both based on the same "mycar15.xml" and inside these profiles I change the default speeds. That works for me. 

I did not mention this in the other thread but I actually also have a "touristic car 1.5" profile, also based on the mycar15.xml profile, where I disabled toll routes (for "touristic" day trips in France). That works OK as well in the nightly builds since about 19 December.

I will test the "fuel efficient route" option, both in your setup as well as in my setup, this afternoon.

**Comment by hvdwolf** [comment]
I have varying results with the fuel efficinet route, both for the modified car profile as well as the fuel efficient profile.
Sometimes the fast and fuel efficient route IS the same, especially when travelling with carava. Due to lower max. speeds it already takes shorter routes, because travelling over motorways is normally longer but also faster with a 130 km/hr speed instead of 85 km/hr.

But it is still buggy: If I do a route calculation with  "fuel efficient", then undo the  "fuel efficient" routing, the icon remains in the routing screen. See attached images.
Here I disable the fuel efficient routing.
![FuelEfficientDisabled](https://user-images.githubusercontent.com/4520361/74087195-3bf3d800-4a8a-11ea-9b0a-d0d10a639eba.jpg)
When I come back in the screen the "fuel efficient" icon is still displayed.
![FuelEfficientStillDisplayed](https://user-images.githubusercontent.com/4520361/74087206-65acff00-4a8a-11ea-95eb-747da34eef71.jpg)
Switching the option on/off results indeed in  changing calculation, but the "fuel efficient" icon is never removed.

Secondly: profiles are read on start of OsmAnd. I did not go through all of the options (yet), but I have the idea that some options are changed immediately while other options are only re-initiated upon full stop start/start of OsmAnd.

**Comment by hvdwolf** [comment]
Sorry, I made a statement above _"But it is still buggy: If I do a route calculation with "fuel efficient", then undo the "fuel efficient" routing, the icon remains in the routing screen. See attached images."_

I removed that part with the images. The "fuel efficient route" icon remains but is grey on being inactive and blue on being active. I overlooked that.

**Comment by vshcherb** [comment]
We've 1 issue and going to refactor some code.
*Don't specify attributes at the header of routing.xml*, use attributes inside of each profile either as attribute or as internal attribute.

We're going to fix header attributes issue, so it doesn't cause misdirection
