### ISSUE TITLE
TTS Dutch (nl) doesn't work

### ISSUE THREAD

**Issue by PanderOpenTaal** [osmandapp/Osmand#846]
TTS Dutch (nl) doesn't work. There is a recorded voice for nl that works work but the TTS not. How to further investigate this? Or, if it is not supposed to be supported, please don't offer it in the app to be downloaded.

**Comment by sonora** [comment]
I cannot reproduce this, I think if you want this investigated you need to be much more specific saying what does not work. Like: Do you not hear anything, or is it just a pronunciation issue? Does any other tts voice work on your device at all? etc.

I have just tried it on mine, any the nl-tts voice did reliably produce output, for every voice prompt. Granted, the voice sounded like it has _way_ too much American accent, but that is due to the devices tts engine I have on my phone (if you want a good Dutch synthesizer voice, your phone's software must support it and be properly set up.) But I would say, your issue is likely one of the correct device settings, and may have little to do with OsmAnd.

PS: You do not report which version of Osmand you are using,  my test results above are for our latest nightly build. Should you have an issue with the latest release version only, it may already have been fixed, just not published yet.

**Comment by TheLastProject** [comment]
I downloaded Dutch TTS on OsmAnd 2.0.4 and it never outputs any sound. When switching to English TTS, navigation instructions are spoken currently, yet Dutch stays quiet at all times.

This behaviour is reproducible for me on the Huawei Y530.
