### ISSUE TITLE
"Units of length" setting gets reset to "Miles/meters" on startup

### ISSUE THREAD

**Issue by severoraz** [osmandapp/OsmAnd#8463]
OsmAnd version: 3.5.5 (from 2019-11-28)

Reproduction instructions:
1. Open OsmAnd app.
2. Set the "Units of length" setting in "Settings > Browse map (App profile) > General Settings" to "Kilometers/meters".
3. Upon request, select "Apply to all profiles" or "Apply only to ""Browse map""".
4. Quit the OsmAnd app (process must not exist after this).
5. Open the OsmAnd app again.
6. Check the previously modified "Units of length" setting(s).

At this point, you should see that the setting is "Miles/meters", regardless of what was set in step 2.

Expected behaviour:
The setting set in step 2 should remain fixed until changed by the user again, meaning that in step 6, the set setting should still be set.

**Comment by pebogufi** [comment]
Can't confirm in current nightly builds, works fine.

**Comment by vshcherb** [comment]
Can't reproduce it currently

**Comment by camelCaseNick** [comment]
Is there a automation to select units of lengths based on location? I cannot reproduce it in Germany, but in England.

**Comment by camelCaseNick** [comment]
@vshcherb Pls reopen this. Normally in Germany I use km/m and now I was in London, GB, where this problem occurred reproducibly for a week on every startup, where I have checked it in two devices for at least five times each.

**Comment by camelCaseNick** [comment]
@pebogufi Were you even in a country with miles/meter as a default?

**Comment by pebogufi** [comment]
No, only and ever central Europe (Germany, France).

**Comment by vshcherb** [comment]
If you have Driving region selected automatically it probably overrides your metric system when you move from 1 country to another.
I can't reproduce it and I don't see anywhere in the code where Metric System changes *except* the situation when Driving  Region is changed

**Comment by camelCaseNick** [comment]
@vshcherb, and how do I set the driving region for cars differently – and automatically – and apart from the distances displayed on the map?
I don’t see why I should change _both_ for every vacation where I want the same units of length, but still want adhere the law and travel left.

**Comment by vshcherb** [comment]
We still trying to understand how does it happen. Obviously these settings are interchanging so it is hard to tweak them separately. 
Default setup: Driving Region - Automatic should work fine even if you change Metric system manually. If you don't change it manually, you metric system should stay after restart.

The only case I see if you keep changing Driving Region then you should immediately configure Metric system as well.

P.S.: None of settings should be changed after restart (especially since 3.6 driving region depends on the route calculation not on restart), so this one is still not clear how it happens

**Comment by camelCaseNick** [comment]
@vshcherb I have Driving Region set to _automatic_, since if've never touched that setting. I have set the metric system manually to km/m, but that changed when entering the UK. If I do the same in Germany with setting the units of length to miles/meter, on restart of the app, those get overridden as well.
So it is not as you described, even with the one being manually set, it gets overidden!
I use OsmAnd 3.5.5 and not 3.6 (if missed that update), so I'll check whether I'll still see that problem there.

**Comment by vshcherb** [comment]
3.5 it could probably be different and we changed Driving Region how it works in 3.6

**Comment by vshcherb** [comment]
- What if you drive across borders where handedness changes and you happen to favour one of either unit systems (so SI if you're sane)?
- That doesn't work now and probably it should be optional cause could be misinterpreted by user. So the metric system is used based on start point of the track

It's probably confusing and shouldn't interfere, so I will keep this issue open

**Comment by trigpoint** [comment]
In the UK miles/metres is the perfect setting. 
It shows miles to match speedlimits and roadsigns and metric, which I prefer, for shorter distances.

**Comment by go4tidal** [comment]
trigpoint
I'm afraid I can't agree with your chin comment here
> In the UK miles/metres is the perfect setting.
UK road traffic signs, in particular hazards, are signed in miles/yards by law at the moment. So I would say the default for UK region is incorrect. Not sure what the situation is in India or other similar grouped territories. I admit heights and widths of tunnels etc are in metres. Nevertheless I always end up changing to miles/yards, with some difficulty.

You could perhaps change your walking profile to km/metres if this was appropriate for shorter distances ?

**Comment by go4tidal** [comment]
I've found that automatic driving region always overrides manual unit settings, now in 3.9.10. However if a specific region is selected then manual settings override. A little inconsistent. I would suggest that manual unit settings should override both automatic and region selected to allow for personal preference.

**Comment by go4tidal** [comment]
Apologies for making a mess of my first comment above. I've no idea what a "chin" comment is. I blame that on Google.
The first line of indentation is trigpoint's comment. The rest is mine. Not sure how that happened either. Must have been half asleep. Will blame that on Covid-19.

**Comment by vshcherb** [comment]
Moved - to https://github.com/osmandapp/OsmAnd/issues/10978
