### ISSUE TITLE
Navigation issue - wrong turn suggested

### ISSUE THREAD

**Issue by katerynakocherhina** [osmandapp/Osmand#8505]
https://www.openstreetmap.org/note/2088703#map=19/47.86060/12.16020
While moving along the Äußere Salzburger Straße, OmAnd suggests turning left when it is not necessary to take any turns.

**Comment by vshcherb** [comment]
1. It is possible to improve visualtion if turn:lanes are added to the way
2. In order to skip announcement https://www.openstreetmap.org/way/304638130 this lane should be secondary and not secondary_link. Otherwise both ways are considered equal and the announcement to "Keep left" is needed in general.
