### ISSUE TITLE
Map details at zoom level 11 uncomplete, 

### ISSUE THREAD

**Issue by quax2712** [osmandapp/Osmand#8702]
I habe noticed this wrong detail showing since 3.x (more than 5 month).
This is when bicycle mode is active, no special things active Display 'Osmand', I tried with different possibilities, but nothing did help.
The effects you can see, the map configuration too.

I thing the problem is in default.render.xml as some other May style like Touring view don't habe this effect
greetings rainer.

Zoom Level 10
![Zoom level 10](https://user-images.githubusercontent.com/42236280/77226454-d0b51f80-6b78-11ea-93e4-85b6d9aff24e.png)

Zoom Level 11 (Problem level)
![Zoom level 11](https://user-images.githubusercontent.com/42236280/77226467-dd397800-6b78-11ea-8e43-63e13a1378a2.png)

Zoom Level 12
![Zoom level 12](https://user-images.githubusercontent.com/42236280/77226469-e4f91c80-6b78-11ea-9690-efadc3ba7002.png)

Settings
![Settings1](https://user-images.githubusercontent.com/42236280/77226473-ed515780-6b78-11ea-9b0f-a9cc31230ba6.jpg)
![Settings2](https://user-images.githubusercontent.com/42236280/77226474-ee828480-6b78-11ea-958b-71596e1fe8cd.jpg)

**Comment by sonora** [comment]
There are actually 2 issues visible on your map screenshots:

(1) are the little gaps you see between street segments e.g for motorways. This seems a bug of the combination Map style=OsmAnd and Road style=German road atlas. It is independent of the app profile and the map, but renderer-specific, e.g. Touring view does not exhibit this.

(2) are segments of e.g. a motorway entirely missing. Particularly bad in, but maybe not limited to, the bicycle mode. I have tested with an old Hesse map of August 2017, and cannot reproduce, but can reproduce with our latest Darmstadt county map. When you select More details=on, the issue improves somewhat  hence I believe (2) to be due to our detail counter in the default renderer being too small.

**Comment by sonora** [comment]
(3) Another bug we could look at on the occasion: When you have Map style=OsmAnd and Road=German road atlas, then turn on More details, the UI will not accept setting the road style back to Default (unless you turn More details of before).

**Comment by vshcherb** [comment]
![image](https://user-images.githubusercontent.com/1042025/77471808-33c1e300-6e13-11ea-86cc-6a91e4c554ef.png)
I can't reproduce issue with latest map (latest build) with any rendering style - tested on zoom 9-12

**Comment by quax2712** [comment]
Please use bicycle Mode to render. When you see the earth left up, it is although ok, but it is the bicycle mode that makes the problem

**Comment by sonora** [comment]
@vshcherb  Yes, as I said, roadsDensityLimitPerTile seems simply too small in defaultrender.xml. If you use 100 like I do in Touring view, the issue is gone. But whoever takes this on should test some more, as I think also ped mode is likely affected, and there could also be other density parameters in our default renderer which are chosen to small. The amount of detail, number of road segments etc. on OSM maps has simply increased a lot in recent years.

**Comment by vshcherb** [comment]
@sonora  I think it could be partially related to this issue https://github.com/osmandapp/Osmand/issues/8371. Especially with gaps visible on original screenshot and not visible on mine screenshot. So it is probably also related to maps split / join
