### ISSUE TITLE
wrong coast displaying

### ISSUE THREAD

**Issue by ristein** [osmandapp/Osmand#8722]
Coast line is displayed wrongly, on different zoom levels, but not if zoomed closely:
![Screenshot_20200328-095819_OsmAnd~](https://user-images.githubusercontent.com/55446611/77819505-964d0480-70db-11ea-887a-2364599c9b6b.png)

What version of OsmAnd are you using, on what device and Android/iOS version?
3.6.3
Do you use the offline maps offered within the OsmAnd app for download, or online (tile / raster) maps?
downloaded
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs, and its edition date.
Norway, around Stårheim, map from Feb 1st

**Comment by vshcherb** [comment]
The problem is that after OSM imports coastline are too short....  Some of the are 50-100 m lengh
For example:
https://www.openstreetmap.org/way/639456747 is in a data for zoom 12.
But
https://www.openstreetmap.org/way/639456869
https://www.openstreetmap.org/way/639456699
are not present in data set due to map simplification for generation.

It could be solved differently though quite an easy solution could be to connect with a threshold or 2nd solution to include even such small coastlines which might have other glitches with coastline like flooding.

**Comment by vshcherb** [comment]
https://github.com/osmandapp/OsmAnd-tools/commit/c8ec9b5050521bb985c4ad7ee721c2cf98dc1ed8

**Comment by vshcherb** [comment]
https://github.com/osmandapp/OsmAnd-tools/commit/248e3e01407de74a0de30a4c21651d646d8c8c3c
