### ISSUE TITLE
Parking lot POIs

### ISSUE THREAD

**Issue by katerynakocherhina** [osmandapp/OsmAnd#8736]
The map is showing „Customer only“ and „private“ parking entries as Default. 
When clicking on details in the app they are showing the correct attribute for customer usage only but OsmAnd is showing them as normal parking lots.
It may be better to disable these per Default from Showing up on the map.

**Comment by WizoneDE** [comment]
![customer_parking0](https://user-images.githubusercontent.com/35132439/78007795-0effcb00-733f-11ea-9c2a-06d409fca3af.jpg)
![customer_parking2](https://user-images.githubusercontent.com/35132439/78007801-0f986180-733f-11ea-82fc-5d4d354d4cf7.jpg)

**Comment by hakuchi** [comment]
Maybe this can made transparent, because if I drive to the Rewe I ave to know where I can park my car.

**Comment by WizoneDE** [comment]
if transparent... this should be a toggle option (enable, transparent, disable).
in most times, if you drive to the rewe, the customer parking lot is directly next to the rewe. If the shop doesn't have a own parking lot you still have to search for a "normal" parking lot. 

in all of my driving time, a customer parking lot for amenty=shop was never relevant for me as a destination point, why should I search for a parking lot instead of the shop itself?

**Comment by pebogufi** [comment]
... because you don't want to DRIVE to the shop but to the parking. 
If shop and parking are between two streets, navigation may lead you to the wrong position (shop) instead to the parking.

**Comment by WizoneDE** [comment]
yeah  but this should be a routing search option and not a show on 2d map default thing. :) 

search for the store and than show an option, look for parking lots next to the shop, so you could get all parking spots, open and customers.

most of the navigation users wouldn't search for an customer parking lot while searching for a store.

**Comment by hakuchi** [comment]
if I scroll the map in a unknown place I would like to see, if the shop have a parking or if there is no parking.      
There are certainly a number of users who use OsmAnd as a map without navigation.

A supermarket is not the best example for this problem because almost all supermarkets have a parking.

What about smaller parking near butcher, seafood, hairdresser, clothes, pharmacy, etc.?

`access=customers` maybe need a switch function, something different to normal parking, or simply transparent as on the OSM website. 

I think, that the `amenity=parking` with `access=private` **should not be shown** in OsmAnd, because on a private parking the access is only allowed to a small amount of people.

**Comment by pebogufi** [comment]
Maybe private parkings could only be made visible in existing option "more details"

**Comment by NotSoImportant** [comment]
@vshcherb to me this is not a nice-to-have as most people have not turned on "show access restrictions" and so will see it as a public parking, which in fact it isnt.
Supermarkts might mostly not kick you out, but others might.

**Comment by vshcherb** [comment]
I missed word "private", of course private shouldn't be displayed.
 "customers-only" I think is a question of how they should be displayed but certainly should be.

**Comment by NotSoImportant** [comment]
@vshcherb where do you miss "private"? 

Is there a consense? I vote for
- don't display private (only with "more details" enabled) 
- display "customers-only" transparent (like osm website does)

**Comment by WizoneDE** [comment]
In Germany most supermarkets limits their parking lots for 1-2 hours at max and are checking it. My wife got a 50 euro ticket for parking on the supermarket parking lot and leaving the place to go to the nearby baker .... 

So for me all customer parking only parking spots are critical for a fee

In my opinion it would be nice to use them half transparent and use a custom icon (P +  shopping venture) 

 the parking icons should reflect the parking type for a better overview.

P with underline = Open parking lot
P with Overline = underground parking
P With ^ on top = parking garage
P with shopping icon = customers parking
P with lock = Private parking only

**Comment by NotSoImportant** [comment]
Related closed issues
- #3970
- #3894

**Comment by NotSoImportant** [comment]
With this change, are private parkings still shown when having "more details" activated?

**Comment by xmd5a2** [comment]
@NotSoImportant yes but only polygons, no icon
