### ISSUE TITLE
Justify Saarland boundary poly [Buildings should not be in the wrong state]

### ISSUE THREAD

**Issue by katerynakocherhina** [osmandapp/Osmand#8747]
The building at 49.11248, 7.04746 is considered to be situated in Sarreguemines in OSM https://www.openstreetmap.org/relation/9795467

While in OsmAnd app, it is Rilсhingen-Hanweiler city
![image](https://user-images.githubusercontent.com/50198677/78222799-8021b880-74ce-11ea-8a7d-839efb02405b.png)

**Comment by vshcherb** [comment]
If you download only french map, everything is correct. The problem with Saarland map so you can disable it or we will update next time 
Justify Saarland boundary poly [Buildings should not be in the wrong state]

**Comment by Vincent57200** [comment]
My aim is to improve OsmAnd and help to fix bugs. I use Saarland map because I'm living near to the border. I have noticed that when the app is seaching the address, it does'nt take care of the adress datas available in OSM. I found an example within the Moselle map with an address different that the one recorded in OSM. You will find screenshots attached. Envoyé depuis mon smartphone. 
-------- Message d'origine --------De : vshcherb <notifications@github.com> Date : 11/06/2020  19:17  (GMT+01:00) À : osmandapp/Osmand <Osmand@noreply.github.com> Cc : Vincent57200 <vbffos@orange.fr>, Manual <manual@noreply.github.com> Objet : Re: [osmandapp/Osmand] Justify Saarland boundary poly [Buildings should not be in the wrong state] (#8747) 
If you download only french map, everything is correct. The problem with Saarland map so you can disable it or we will update next time
Justify Saarland boundary poly [Buildings should not be in the wrong state]

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/osmandapp/Osmand/issues/8747#issuecomment-642820012",
"url": "https://github.com/osmandapp/Osmand/issues/8747#issuecomment-642820012",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by Vincent57200** [comment]
Sorry, attachments were missing in my previous emailMy aim is to improve OsmAnd and help to fix bugs. I use Saarland map because I'm living near to the border. I have noticed that when the app is seaching the address, it does'nt take care of the adress datas available in OSM. I found an example within the Moselle map with an address different that the one recorded in OSM. You will find screenshots attached. Envoyé depuis mon smartphone. 
-------- Message d'origine --------De : vshcherb <notifications@github.com> Date : 11/06/2020  19:17  (GMT+01:00) À : osmandapp/Osmand <Osmand@noreply.github.com> Cc : Vincent57200 <vbffos@orange.fr>, Manual <manual@noreply.github.com> Objet : Re: [osmandapp/Osmand] Justify Saarland boundary poly [Buildings should not be in the wrong state] (#8747) 
If you download only french map, everything is correct. The problem with Saarland map so you can disable it or we will update next time
Justify Saarland boundary poly [Buildings should not be in the wrong state]

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/osmandapp/Osmand/issues/8747#issuecomment-642820012",
"url": "https://github.com/osmandapp/Osmand/issues/8747#issuecomment-642820012",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by vshcherb** [comment]
Yes, we don't store POI addresses to save map size, so instead we try to calculate address each time, we hope to reach 99.5- 99.9% geocoding correct and that will be enough for us. Probably later we will save 0.001% of data which is tricky to deal with but that will save us 1000x memory obviously for download.
