### ISSUE TITLE
OSM edits in Osmand nightly are stored at wrong coordinate

### ISSUE THREAD

**Issue by ArjanOnwezen** [osmandapp/Osmand#8816]
OSM edits in OsmAnd are stored at wrong coordinate using latest nightly OsmAnd~  3.7.0 29431. 
Steps to reproduce.
- Click on place on Map (near Utrecht, Netherlands)
- Add POI
- Save to map
- Now POI is stored somewhere in Russia

**Comment by pebogufi** [comment]
Trying to create a poi 
amenity=bench
on saving, BOTH lat tag and lon tag are filled with lat value. So lat= lon.
version 3.7.0#29425 2020-04-17.
@ArjanOnwezen please check, whether it is identical problem you had.

**Comment by scaidermern** [comment]
Sounds like we need to investigate all recent changesets created by OsmAnd 🤦.

**Comment by pebogufi** [comment]
Yes, but it is easy, delete all where  lat=lon :-((

**Comment by max-klaus** [comment]
The issue was introduced by PR https://github.com/osmandapp/Osmand/pull/8779 (6 days ago)
Now it is fixed by https://github.com/osmandapp/Osmand/commit/af23ab50be4ad251dc1f535e4c225a99475e694f

**Comment by scaidermern** [comment]
@max-klaus Is there a plan for fixing all affected OSM edits?

**Comment by vshcherb** [comment]
@scaidermern they can't be fixed cause information is lost in between, so the only possible way if the author will move osm edit to right location or recreate them

**Comment by scaidermern** [comment]
> @scaidermern they can't be fixed cause information is lost in between, so the only possible way if the author will move osm edit to right location or recreate them

With fixing I meant deleting the changes or contacting the author to fix them.

**Comment by ArjanOnwezen** [comment]
Thanks for fixing the issues. Latest build works as expected. I've rolled back the incorrect edits I made.

**Comment by Nakaner** [comment]
What versions of OsmAnd are affected? Can they be identified by their `created_by=*` tag in the changeset?

In order to minimise future damage by users using the affected version but not upgrading their app, I suggest the following:
* If OsmAnd uses OAuth, the tokens being used up to now should be revoked immediately, new tokens being registered and a patch release being published. This has to be done by the person who registered OsmAnd at the OSM API with his/her OSM account when OsmAnd started to support OAuth. All existing OsmAnd installations need an upgrade to the latest version in order to continue using OAuth.
* If OsmAnd does not use OAuth, it might be worth to think about banning the affected version (contact OSM sysadmins for that) like it happened to an ancient version of JOSM which swaps latitude and longitude.

**Comment by pebogufi** [comment]
see
https://forum.openstreetmap.org/viewtopic.php?id=69202
