### ISSUE TITLE
Roundabout is not considered

### ISSUE THREAD

**Issue by katerynakocherhina** [osmandapp/Osmand#8859]
During the navigation, OsmAnd displays the wrong direction on the roundabout

Start 51.53886° N, 128.16957° E 
End 51.48597° N, 128.16800° E 
Roundabout 51.48907° N, 128.19441° E

**Comment by cebderby** [comment]
Before 13 April 2020 (and since July-Aug 2019) the data in OSM did not include oneway=yes, just (rather approximate) geometry.  If you have OsmAnd Live you can get the 13 April data, else wait a week or so for the next monthly update and it will then take the right route.
(Note that junction=roundabout needs adding to the data for the router to say its a roundabout and invite you to take 1st/2nd/3rd exit rather than turn right,turn left etc)
