### ISSUE TITLE
Can't delete favorite

### ISSUE THREAD

**Issue by ArjanOnwezen** [osmandapp/Osmand#8880]
Looks like I can't delete the favorites I created.
Using Osmand~ 3.7.0#29593.

- create favorite map
- click on favorite on Map
- try to delete it

**Comment by dmpr0** [comment]
Hello! Thank you for the feedback.
Could you please provide more details about the issue?
You need to tap "Edit" in context menu to open the "Edit favorites" screen, where in app bar you can find delete button.
In the current build, we have an issue with the button name, no it shows the text "Add" instead of "Edit".

**Comment by pebogufi** [comment]
After marking the fav on the map press "Add" below the star in the left lower corner. (Instead of "Add" it shoud mean "Edit").
Now to delete press the symbol for trash can in top right corner.
@vshcherb I think here we need some fine tuning for handling.

**Comment by ArjanOnwezen** [comment]
Thanks both! Yeah changing the text to Edit in case of opening an existing fav would make it clear.

**Comment by vshcherb** [comment]
It is a nightly build bug and it is going to be fixed this week (probably already merged).
