### ISSUE TITLE
Voice turn alerts too detailed

### ISSUE THREAD

**Issue by mattija555** [osmandapp/Osmand#8884]
When using navigation while driving, the voice says e.g. "In two... hundred... twenty... seven... meters... turn left". By the time I'm done listening to what I should do at the next intersection, I'd already driven through it! Or I am panicking because I learned that I'm in the wrong lane or smth.

Can we have these alerts dumbed down to e.g. **"In 200 meters" instead of "In 227 meters"**? Because as a driver I don't care if it's 27 extra meters or 24 or whatever. But I do care about which turn I'm supposed to take in about 200 meters.
Thanks.

OsmAnd+ latest version, on Android 10

**Comment by sonora** [comment]
Interesting, because this is exactly the functionality requested by #8749. :) But it is not our standard behavior for exactly the reasons I have stated there: https://github.com/osmandapp/Osmand/issues/8749#issuecomment-626119991

This means you are using a tts voice which is missing our standard rounding code block.

Can you please temporarily activate the OsmAnd Development plugin, go to its settings, tap "Test voice prompts",
- then provide as a screenshot the output of tapping test button **11.1**.

Also: Please tap test buttons and report the sound output of
- **2.2** (it should say the rounded "20 kilometers") and
- **7.3** (It should announce the rounded "350 m", not the 360 m I feed into the prompt)

**Comment by mattija555** [comment]
HI, here is the screenshot.
Tapping 2.2 does round it but it rounds it to 19 km, not 20?
And 7.3 says 360 m, not 350?
I am not using TTS but the recorded English (British) prompts. 

![Screenshot_20200509-123106_OsmAnd+](https://user-images.githubusercontent.com/64776615/81473602-dab1e100-91ff-11ea-8d23-2c766d8f4dcd.jpg)

**Comment by sonora** [comment]
Ok, thanks! In general, I think you'd be much happier using a TTS voice than a recorded voice, because it has more features (like being capable of announcing street names), and they are better maintained in our code (because more widely used). Recorded voices have a lot of limitations, mainly because we are limited to the expressions for which a recording exists.

Having said that, I just looked at our British English voice file and it really seems to have issues at first sight, looks like it has not been correctly maintained. I will take a look and bring it to the standard when I find some time.

In the mean time, maybe you want to test the 'regular' en voice prompts ((which will contain a bit of American vocabulary but the difference is small). And again there I recommend using the TTS version en-tts.  Even when using this vocabulary file, you may still select the British accent voice in your Android TTS settings, no problem.

I guess your system should be capable of producing TTS sound, you forgot to tap button 11.1 before you produced the screenshot, so I cannot fully tell. Even if you do not like your system's standard, there are really good and naturally sounding TTS voice engine apps out there producing rather naturally sounding British English, just explore.

**Comment by mattija555** [comment]
No, I did tap on 11.1 and now I did it again and it still looks the same.
Ok, I guess I'll switch to TTS and see how it goes. I obviously prefer the more human voice but am also aware of its limitations.
Thanks for rapid responses!

**Comment by sonora** [comment]
Apologies - yes, the TTS stuff of button 11.1 is just blanked out because you had selected a recorded voice when entering "Test voice prompts" - hence it is not tested.

But I do believe you should have no problem testing OsmAnd British English TTS voice, just try it. I know the thing about the "human sound": Different TTS engines deliver VERY different quality, so the art is to find one which sounds good on your device, and then download its high quality voice (and not just the basic one which often comes pre-installed).

I just notice the rounding function (`ogg_dist(...)`) may be broken for all our recorded voices (TTS should be fine). Likely a bug from when we transferred the config files to javascript.

**Comment by sonora** [comment]
I have introduced the proper rounding code also for recorded voices. https://github.com/osmandapp/OsmAnd-resources/commit/98799c4bfd125a93788af54c7a701fd020387010

It is quite a massive change, and I have tested a lot, but any further help testing that I did not fat-finger anything much appreciated.

@vshcherb  I leave this issue open, because someone still needs to place the new `xx-tts.js` files on the download server, i.e. **update them in the download packages we offer for recorded voices**. I am not sure how to do that, and see that the .js files currently packaged with the recorded voices we offer to download are really old.

**Comment by sonora** [comment]
After more testing: Looks like my commits fixed this. So we only need to update the recorded voice packages on our download server accordingly.

**Comment by vshcherb** [comment]
@sonora that's really tricky... We shouldn't update voice packages on the server cause they should be automatically updated from files provided inside app. So it used to work like this probably it is broken.

**Comment by sonora** [comment]
@vshcherb Yes, that what I thought also, thanks for confirming. It seems it may have become broken a long time ago, possibly even when we introduced the .js config files. I will close this issue as resolved, and open another one to investigate.
