### ISSUE TITLE
Review the new address tagging of favorites

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#9018]
As a spillover of #8926: Looks like we recently have started tagging favorites with `<extension><address>` and including this in the favorites.gpx backup files.

While it is unclear if this has a user benefit in some cases, there are clearly cases where this is just vain overhead using up storage and cpu cycles. Most notably where the address cannot or only roughly be determined (i.e. where we determine "Near XYZ"). At the very least, we should not tag favs with such approximate addresses.

**Comment by vshcherb** [comment]
It has started from Home/Work points where it was decided to display addresses, then there was a massive change to make Home/Work favorites which they should be. And apparently all favorites now resolve address.
Obviously, we need to resolve address during creation cause then it saves lots of time rather than when displaying. Many people probably don't need it at all, so we can think of making it optional. It will be investigated if addresses are used by any other large group.

**Comment by vshcherb** [comment]
Merged into #9055
