### ISSUE TITLE
Simplify what World basemaps we offer

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#9056]
We currently bother users with 3 different world basemaps, and offer them all for download:
 - the basemap mini: I understand this is part of the apk? Shouldn't we remove it from the available downloads completely, so it remains just a static and invisible built-in feature of each release?
 - the about 60M basemap only covering up to zoom 9: I would argue it is obsolete. If you really  need a basemap at all, I think you should invest in the 200M download and get the decent (called 'detailed) basemap.
- the 'detailed' basemap could simply be renamed to World basemap. It is an optional download for whoever wants a decent global basemap, or a map of their area at zoom 9 or smaller, in which case the 200M download is a reasonable investment.

**Comment by vshcherb** [comment]
We will collect more feedback throughout 3.7 release

**Comment by sonora** [comment]
Also: It looks like every time you enter map download now, you are reminded to download the updated world basemap (I guess the 60 MB version is meant), even if you have an up-to-date detailed one present, and had deleted the other one.

**Comment by scaidermern** [comment]
I strongly agree here. The detailed world map should be enough since it isn't too large. The other two are obsolete.

**Comment by foobar13372** [comment]
I totally agree. Just landed here because I now only have the "detailed" default world map installed after I discovered it - but every update suggest I should install the "normal" default world map. Very annyoing. You always think "whoops what went wrong now?" until you realise that nothing is wrong but the message itself.

I don't so much care whether there are 3 versions (mini, normal, detailed) or just one (detailed) but please change it so that it is enough to have any single of them installed to hide the message about installig a default world map when updating any other map.

But I'd also like it if the detailed one is the only possible world map and it is not deletable (only updatable) and apk already ships the newest one available on package-time. So that it's not possible to "destroy" the basic functionality of the app, so that at least the world is always viewable in the same way for every user without any further configuration.

**Comment by vshcherb** [comment]
Now detailed map is removed and normal is offered.

**Comment by vshcherb** [comment]
We need to disable now all offerings of basemap because it is optional

**Comment by 532910** [comment]
> Now detailed map is removed and normal is offered.

Is it no longer available? Why so?

**Comment by vshcherb** [comment]
the 'detailed' basemap could simply be renamed to World basemap. It is an optional download for whoever wants a decent global basemap, or a map of their area at zoom 9 or smaller, in which case the 200M download is a reasonable investment.

**Comment by 532910** [comment]
nice, clear!

**Comment by scaidermern** [comment]
Now there is only the detailed world overview map available for download. However there is a bug. After downloading it and hitting refresh the world overview map becomes gray again in the download section.

**Comment by 532910** [comment]
I'd say it works fine for me.
