### ISSUE TITLE
Address search confused by "100 Bridge Street"

### ISSUE THREAD

**Issue by blackboxlogic** [osmandapp/Osmand#9061]
Search-by-address results are _way_ off when searching for "100 Bridge Street" on the Maine-USA map.

`100 Bridge` has _good_ results!
![Screenshot_20200523-084459](https://user-images.githubusercontent.com/31355456/82731856-97637200-9cd7-11ea-9886-46bb78277dc6.png)

`100 Bridge Street` returns junk. Guessing, it might be all streets that have bridges, listed in alphabetical order.
![Screenshot_20200523-084514](https://user-images.githubusercontent.com/31355456/82731860-9d595300-9cd7-11ea-85ea-403f456adc52.png)

I'd expect both searches to return roughly the same thing. I tried it with other street names, and there wasn't a problem.

**Comment by sonora** [comment]
@vshcherb I think what happens is we do not correctly sort the search hits by relevance, something which really needs to be fixed.

Try to just search for '100 Bridge', and I am certain you would at least see some 'Bridge Streets/Roads/etc.' further up in the list of results.

Correct sorting by relevance for e.g. two word searches would actually mean that hits with an exact match for both  words should be prioritized, which I think does not happen, so that hits where just 'Street' matches may be displayed near the top, which is of course wrong.

**Comment by blackboxlogic** [comment]
My experimentation mostly confirms your hypothesis that result sets for each search term get _unioned_ together, then are ordered by distance from User's current position.
_Except_ that the search "100 bridge street" has a first result nearly 5 miles away, when I am standing on bridge street.

**Comment by vshcherb** [comment]
Fixed but we need to add tests:
1. 100 bridge, 
2. 100 bridge street 
3. 100 bridge street westbrook
