### ISSUE TITLE
Add option to customize appearance of route line

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd#9195]
We can add options to customize the route line color, thickness, and maybe opacity. We can put that option in the configure profile > profile appearance screen.

**Comment by matthijskooijman** [comment]
It seems that especially transparency would be important to configure, since there seems to have been quite a bit of tweaking the transparency in the past (e.g. see #1747, #4225, #3077).


Also, it seems that there are inconsistencies between the different route renderings:
 - Hiking routes with "Color by OSMC hiking symbol" are quite transparent and the route is rendered *below* the road.
 - Hiking routes with "Color by network affiliation" are quite opaque and renderd on top of the road.
 - Cycle routes are quite transparent and rendered on top of the road.

I'm not sure if there is good reason for this inconsistency, or it is just a matter of selectively applied improvements, but if route rendering was more configurable (e.g. transparency, but maybe also on top of / below road), maybe the defaults could be unified but users can still configure the routes exactly the way they were (or however they prefer) instead.

A related improvement could be to make the opacity dependent on the zoomlevel. When you are zoomed out, you probably want an overview of the route (which calls for higher opacity and maybe rendering on top of the road with a narrower route line), but when you are zoomed in, you more likely want to see road details (which calls for higher transparency and/or rendering below the road).

**Comment by matthijskooijman** [comment]
@dmpr0, I suddenly wonder: what route line did you mean here exactly? The markings for e.g. cycle routes on the map? Or maybe the current route when navigating? I had interpreted your request as the former in my previous comment, but now realize that you might have meant the latter. Could you clarify?

**Comment by dmpr0** [comment]
@matthijskooijman I meant a line for a calculated route, visible only in navigation mode.

**Comment by Eugene-T-gps** [comment]
Хорошо бы иметь возможность настройки внешнего вида линии проложенного маршрута навигации. На некоторых картах в различных режимах (день/ночь) цвет линии построенного маршрута может совпадать с цветом дорог. При беглом взгляде на экран линия построенного маршрута теряется. Это происходит с фиолетовыми линиями, с синими линиями.. Так же насыщенная и непрозрачная ночная жёлтая линия маршрута вызывает дискомфорт.
Нужны настройки именно этого. Или выбор из нескольких доступных, без привязки к типу используемой карты.

**Comment by sonora** [comment]
We have worked on a massive amount of customization options lately  (thus sacrificing progress in functionality , ease of use, and stability). And it has increased clutter and perceived OsmAnd complexity.

Buf if we continue that route with this request, we have to make sure, at least,
- we provide options for day and night map configuration
- provide an option to return to the renderer-specified default settings (these are optimized to each rmap style's circumstances and needs)
- have a useful concept what should happen when the user changes the map style, if the manual settings should prevail, or if the renderer defaults should take over (and if custom settings should be remembered per each renderer)

**Comment by nazar-kutz** [comment]
Figma: https://www.figma.com/file/qzrNQj0chuME6gyO038i6M/Settings?node-id=1%3A35216

**Comment by matthijskooijman** [comment]
@nazar-kutz, I get an error from Figma, did you share the file properly?

> File not found
>
> Either this file doesn’t exist or you don’t have permission to view it. Ask the file owner to verify the link and/or update permissions."

**Comment by vshcherb** [comment]
I think it was internal communication

**Comment by dmpr0** [comment]
# Review 
- [ ]  Direction arrows should use the same algorithm for color that we use in "track appearance" for finding contrast color with the line, for example when the route line is black, arrows should be white.

##### Dark theme
- [ ] Background color for empty area:
- [ ] Status bar color:
