### ISSUE TITLE
Normalize search strings

### ISSUE THREAD

**Issue by sonora** [osmandapp/Osmand#9199]
I have steted this before but I think it got somehow lost again:

It is good (and necessary) practice in search operations to normalize the search string (i.e. what the user types) to the needs of the index before passing on to the search engine. I our case, and you can easiliy test this manually, the least that must be done is to replace dashes (-) by blanks ( ), and to remove periods (.) entirely. 

This is a quick measure which will e.g. immediately produce valid results where a user specifies common abbreviations like ''XXX St.'  (e.g. in the US) or 'XXXstr.' (e.g. in Germany).

**Comment by vshcherb** [comment]
https://github.com/osmandapp/Osmand/issues/6154
We took a look at the simple fix though we didn't like the results. The issue is open and we continue to investigate.

Don't forget it works only if the dot in the end, so Rolandstr. 8 - doesn't work correctly, so it is a good question how to fix it but we are getting close to it.
