### ISSUE TITLE
[Feature request] Move a favourite to hidden category

### ISSUE THREAD

**Issue by Ofboir** [osmandapp/Osmand#9319]
Hi !
When editing a favourite, we can change its category, but only for one which is currently visible on the map. It would be nice to allow moving it to a category that has been hidden (maybe only available via the "list" button), to allow more sorting flexibility.
Thanks !

**Comment by dmpr0** [comment]
While adding new favorite point to the hidden group, we need to show warning text.

**Comment by Barkole** [comment]
That was working in older versions. It's really a pity, that this features was removed. Because I really work with that, to move out the pois and move them into not displayed groups. Google Maps is still able to, but OSMAnd removed that great feature. If I could configure it, that be fine, but currently it's really a sad thing.

Please re-enable that feature soon.

**Comment by Chumva** [comment]
Should be fixed here - https://github.com/osmandapp/Osmand/pull/9487
