### ISSUE TITLE
another turn lanes highlighting issue

### ISSUE THREAD

**Issue by 532910** [osmandapp/Osmand#9336]
It says "slight right" and shows it as the next turn, but central turn lanes are not highlighted:

https://www.openstreetmap.org/directions?engine=fossgis_osrm_car&route=59.9458%2C30.5283%3B59.9530%2C30.5473#map=15/59.9454/30.5398
![image](https://user-images.githubusercontent.com/14617699/85914580-e147f680-b847-11ea-8709-ec26d7a9d68d.png)

**Comment by vshcherb** [comment]
This is an old algorithm because turn:lanes are not present here though it should work cause here the number of split lanes match is equal  3 = 1 + 2.

It looks like instead of Keep Right, Turn slightly right generated probably because of quite sharp deviation and that's why lanes are not counted correctly.
