### ISSUE TITLE
Wikipedia layer doesn't show OSM objects with Wikipedia pages

### ISSUE THREAD

**Issue by jluttine** [osmandapp/Osmand#9424]
I like the Wikipedia layer of Osmand! However, I would have expected it to *also* show OSM objects that have Wikipedia pages defined (either via `wikipedia` or `wikidata` tag). Here's one example node with `wikipedia` tag that doesn't show up in the Wikipedia layer at all because, I suppose, the actual Wikipedia page doesn't define coordinates: https://www.openstreetmap.org/node/1551784121

But the layer could show a similar Wikipedia icon for this kind of OSM objects as it does for Wikipedia articles with location information. Would this make sense?

**Comment by vshcherb** [comment]
That's probably won't change cause we rely on another integration. You need to enter location inside Wikidata entry and then it will work correctly in OsmAnd
https://www.wikidata.org/wiki/Q11852682
https://www.wikidata.org/wiki/Property:P276

**Comment by jluttine** [comment]
Ok. That just feels a bit redundant to put the location also in Wikidata as that already has been done within OSM, so all relevant information is already available. But thanks for the answer!

**Comment by vshcherb** [comment]
It is a long-running issue where the information should be leading in Wikipedia / Wikidata / OSM. At least now all agree location information should not be in Wikipedia and should be in Wikidata. 
Historically most wikipedia articles have more infromation in Wikidata than in OSM, so we support that way of synchronization.
 Obviously both ways could be automated i.e. semi-automatically add to OSM wikipedia/wikidata of articles, automatically add/sync location from OSM wikidata to Wikidata property. 

Note: since databases are different information should be present in both datasets, though practically it will be too perfect and one data set will be always leading.
