### ISSUE TITLE
GPX files are rewritten on import instead of copied

### ISSUE THREAD

**Issue by jensMF** [osmandapp/Osmand#9455]
I use OSMAnd+ 3.7.4 and Android 8.1, but I don't think this is important for this issue ;-)

I realized, that GPX files are getting rewritten on import and think it would be better to copy them.
The rewriting leads to invalid GPX files because of #1326

I put some files in the attachment to show what I mean. (I had to rename them in .txt to upload):
[sample2_original.txt](https://github.com/osmandapp/Osmand/files/4924208/sample2_original.txt)
[sample_original.txt](https://github.com/osmandapp/Osmand/files/4924210/sample_original.txt)
[sample2_imported.txt](https://github.com/osmandapp/Osmand/files/4924212/sample2_imported.txt)
[sample_imported.txt](https://github.com/osmandapp/Osmand/files/4924214/sample_imported.txt)

**Comment by vshcherb** [comment]
GPX Files are constantly updated during Track usage in the program i.e. any changes of presentation updates file itself. It is done on purpose so sharing file between 2 OsmAnd versions will produce exact result on different devices

**Comment by jensMF** [comment]
Well if it is on purpose, we could close this issue. I just found it irritating, that the imported file is completely different to the original.

**Comment by vshcherb** [comment]
It is not a storage app and GPX could be adopted. They are adopted because of special step of validation, I consider OsmAnd as an Viewer or as an Editor in both ways OsmAnd will adopt file before use similar to KML. There is no intention to keep original file extra cause it won't be used anymore.

I agree For end-user it is not obvious
