### ISSUE TITLE
OsmAnd ignores bus stops/platforms which do not have a corresponding stop_position node in the public transport relation

### ISSUE THREAD

**Issue by aceman444** [osmandapp/OsmAnd#9672]
stop_position nodes are optional in PTv2 schema (see https://wiki.openstreetmap.org/wiki/Public_transport) and are not usually needed to represent a proper public transport relation. However, if there is a node with public_transport=platform in a bus relation, it is ignored by OsmAnd if it does not have a corresponding stop_position node in the same public transport relation. The platforms (bus stop) is not listed in the stops when a route is chosen in OsmAnd. Also, when the "display transport stops" option is used, the stop (platform) is not highlighted with the blue square bus stop icon. So the stop is completely ignored by OsmAnd even though there is a valid platform representing it.

Fixing this would be especially useful for issue #6744.

**Comment by sonora** [comment]
Have we correctly identified the issue yet?

I have personally created 100's of PT relations over this summer, 90%+ do not contain any stop_positions but just platforms. And I do not see this issue, it seems. Here is just one example: https://www.openstreetmap.org/relation/11205734, I think it displays fine in OsmAnd?

A great tool to aid investigation is this site https://ptna.openstreetmap.de by OSM user @ToniE. You can there configure yourself, via the OSM wiki, PT networks around the world and it produces nightly overpass-turbo reports for you, then nightly updated showing all existing (or missing) relations and possible flaws in the respective geographic areas.

Here is e.g. the direct link to the PT networks in North-Eastern Bavaria I have lately filled with lots of relations, many not containing any stop_positions: https://ptna.openstreetmap.de/results/DE/BY/DE-BY-TON-Analysis.html (this one displays in German, but it is configurable). I guess the ptna analysis site may be helpful to research this issue?

**Comment by MadWasp79** [comment]
Downloaded this relation in josm (https://www.openstreetmap.org/relation/11063367#map=14/48.1482/17.0826) and deleted several stop_positions not only from the relation but from points as well. After creating map all seems working fine - stops are not ignored, all info seems present.

**Comment by aceman444** [comment]
OK, I will observe it further. The sample relation contained a mix of stops where some had both a platform and a stop_position, while some only had platforms. It seems MadWasp79 tested that case.

**Comment by aceman444** [comment]
@MadWasp79 hi, this needs to be reopened. It still happens.
Check map of Slovakia, see bus route relation https://www.openstreetmap.org/relation/5940248 and the stop https://www.openstreetmap.org/node/4076650377 (Banka, rázcestie). It is platform member in the relation, but I have intentionally not added the stop_position to the relation (stop_positions are optional).

If you turn the public transport mode in OsmAnd on, and enable highlighting bus stops (the blue square icon with white bus on it), this platform is highlighted (while at all other bus stops, the stop_position node is highlighted). If you tap the icon, it shows only bus line 11, no trace of bus line 1. You can tap other bus stop icon, e.g. "Vajanského nám." to get the bus 1 listed. If you tap the bus line (the variant relation mentioned above), you get a list of stops. But you can see the stop "Banka, rázcestie" is not in the list.

**Comment by sonora** [comment]
I fail to see the pattern yet, why do you think the issue is related to the platform membership? Looks like Banka, rázcestie is platform (only)  member in both Bus 1 and Bus 11, so if platform membership was the issue, why would it fail to display only Bus 1 but not Bus 11?

**Comment by aceman444** [comment]
I claim the problem is that the public_transport=stop_position node is not part of the same relations. That's why OsmAnd chokes on the bus stop and basically ignores it in the bus route display and the highlighting the stop properly.
Yes, I do not have a theory why Bus 1 and Bus 11 behave differently in this case in OsmAnd.

**Comment by vshcherb** [comment]
@aceman444 it's probably related to OsmAnd Live where we have lots of known troubles with relation updates

**Comment by aceman444** [comment]
No, I waited on the 1 Apr full maps to avoid problems with OsmAnd live. You can see when those relations were last touched by me.

**Comment by aceman444** [comment]
This problem still remains in OsmAnd 4.0 after the map has settled for a few months. This has nothing to do with 'routing'. It is about the public transport route rendering and highlighting bus stops (an option in Map settings).

**Comment by aceman444** [comment]
@vshcherb still happens in OsmAnd 4.1 on the mentioned bus stop.

**Comment by vshcherb** [comment]
I think it's worth to open a new bug  with an example (this is resolved in 3.9)

**Comment by aceman444** [comment]
This was in no way resolved, there is no related code fix linked here.

**Comment by aceman444** [comment]
Example is in https://github.com/osmandapp/OsmAnd/issues/9672#issuecomment-813117976

**Comment by davidoskky** [comment]
I can confirm this problem exist and further highlight another one.
I tested the area provided by @aceman444: relation 5940248 and node 4076650377.
Bus line 1 is not listed among the ones going through that stop, line 11 is for some reason...
Keep in mind OsmAnd live should not matter as I downloaded the map of Slovakia just now.
Routing is also broken: selecting a spot nearby and routing via bus gives us two options: using line 11 which correctly stops at said platform, using line 1 instead makes us go to the next bus stop and walk all the way back.
<details><summary>Screenshot</summary>

![Screenshot_2022-02-01-02-59-30-388_net osmand plus](https://user-images.githubusercontent.com/13107368/151905058-4971a99f-3531-4c5a-b90a-95c7fe8ed746.jpg)

</details>

I'll give another example in which this problem is more evident: relation 908954 and the platform 4540215835.
In this relation all platforms are present, however several don't have a stop_position.
Open OsmAnd select the platform, you can swipe the menu up to select the bus line going through it; the correct line is not shown, the line going in the other direction is shown instead, this may be because there is a stop_position of the route on the other direction nearby.
Tap on that line and the full line will be displayed, you can now navigate through the stops tapping previous and next.
Next is grayed out even though this is not the first platform in the relation, if you tap previous the app will select another platform which has a stop_position nearby (skipping one in between which doesn't), you can notice that this one is on the other side of the road: the wrong line has been selected by the app, in fact if you tap next it will take you to another platform, not the one originally selected.
If you start tapping previous, you'll see the app jumping around the map, not going in order at all and selecting only the platforms which do have a stop_position nearby.
You can have fun with routing to see the absurd things you'll have to do to get nearby a platform which doesn't have a stop_position nearby.
<details><summary>Video</summary>

[video](https://user-images.githubusercontent.com/13107368/151905780-52eb2c9e-f0bc-4721-a305-0e0fe6f18f31.mp4)

</details>

**Comment by aceman444** [comment]
@davidoskky thank you very much! Can you please also add screenshot of when you enable "show public transport stops" in OsmAnd, which shows the blue squares on bus stops OsmAnd recognized. It will be seen these mentioned bus stops will not get the blue square rendered.
