### ISSUE TITLE
Regression: Continue to support sorting track folders A-Z

### ISSUE THREAD

**Issue by sonora** [osmandapp/OsmAnd#9808]
It looks like the tracks on the MyPlaces/Tracks screen are now sorted newest to oldest, and that somehow affects also all track **folders** if you have some. I suggest we should not accept that change into the product without providing a way for the user to revert back to strictly alphabetical order.

As things are in our 3.8 beta now, it leads to chaotic ordering for users having large databases of tracks arranged in folders. Sorting these by some mechanism based on time stamps of files they contain (or maybe the folder time stamp itself?) is not transparent and leads to almost random sorting.

(In addition, it seems any change of a track 'Appearance' (using that new menu) changes the track time stamp, and thus the sorting?)

**Comment by vshcherb** [comment]
Initially it was quite annoying regression of sorting tracks in the wrong date order, there were some attempts of unsuccessful fixing it by name. Due to the code structure change of the track order affected folder order change. 
To be honest I was surprised that it works better in my day to day structure cause I don't have 5-8 folders and it's easier to access latest modified folder on the top.

I agree that 20+ folder structure cause really bad experience. Here I would like to come up with compromise cause I don't want to end up in a long term implementing solution (screen is planned for redesign this year). 

Can we have structure like:
1. Visible
2. Latest modified folder 
Between 1-3 folders
----
X. Order by name

**Comment by sonora** [comment]
May be be a viable interim workaround. But 'latest modified' will remain a confusing experience for the majority of users who use OsmAnd to record and view tracks, but never edit them.(We now add appearance changes to the track body under extensions, users will not see this as a track modification, but it would affect time stamp sorting.)

Maybe as an inrerim we should simply resort to a static Z-A sorting, which would put the latest tracks starting with ISO date naming convention YYYY-MM-DD to the top.

**Comment by vshcherb** [comment]
The basic sorting is back and we plan to enhance it on other screens as well
![Uploading image.png…]()

**Comment by sonora** [comment]
Looking good, except the alphabetical sorting is Z-A now, not A-Z. if we only support one, could we make it A-Z like before?

**Comment by Chumva** [comment]
There will be A-Z/Z-A/last modified. I will add them this week.

**Comment by pebogufi** [comment]
Currently Sorting A-Z looks like this:

![Screenshot_20200927-100428_OsmAnd~~01](https://user-images.githubusercontent.com/18628183/94359795-7063e500-00a9-11eb-9eb4-22cf880bb081.jpg)

**Comment by sonora** [comment]
Yes indeed, there are issues, looks like the "native folders" Tracks, Import, Rec, as well as handling sub-folders has problems.

**Comment by vshcherb** [comment]
@Chumva @Dima-1

**Comment by vshcherb** [comment]
There is an issue that folders are sorted by "directory name" and not by "display name" but this looks like a complete mess

**Comment by vshcherb** [comment]
Can't reproduce except top folder "visible" and "tracks" empty folder

**Comment by sonora** [comment]
Looks to me like this https://github.com/osmandapp/OsmAnd/pull/9909  may have fixed it well.
