### ISSUE TITLE
v 3.8 Analyze on Map: required gesture is reversed

### ISSUE THREAD

**Issue by barteis** [osmandapp/OsmAnd#9854]
# 🐞 bug report

### Is this a regression?
Yes--worked fine before, as far as I know

- Create a route of any length
- Go to Details > Analyze on map
- Drag finger along the bottom chart in reverse, from right to left.  The behavior, analyzing the route from start to finish,  is normal except for the required gesture: it should be left-to-right.

## 🌍 Your Environment

OsmAnd v 3.8
Pixel 3, Android 10
Map: California

- [x ] Offline maps offered within the OsmAnd app for download.

- [ ] Online (tile / raster) maps

**Comment by vshcherb** [comment]
In this way it is easier to view the map. It works similar to "scroll" and scroll happens on the map, so left to right is a move from start to end.

**Comment by barteis** [comment]
If I move my finger along the bottom of the screen left-to-right, the point position goes *end to start*.  Isn't that backwards?  Or am I not understanding?

**Comment by vshcherb** [comment]
Yes, my mistake in description. 

IOS works differently cause it doesn't support My Location sync with Map. 
SInce version 3.8 you can press my location and Analyze on Map will be in sync with map and my location i.e. Pinpoint will stay fixed and graph will move from right to left till you reach the end.

In this situation, when pinpoint is fixed, you can only move the graph, so your finger is attached to the graph and the graph is moved. 

As this behavior is critical for Map Location sync, we need to change paradigm though we also don't want to have different behavior after you click or "unclick" sync with my location

**Comment by barteis** [comment]
I just tried this out.  This makes it practical to view your progress on the map and altitude profile at the same time, with the distances on the chart shown as dots on the map.  Brilliant!  Thanks!
