### ISSUE TITLE
Cannot play/view notes on the map

### ISSUE THREAD

**Issue by mircozorzo** [osmandapp/OsmAnd#9919]
In the 30646m version isn't possible at all to select on the map an existing note audio/video/picture. Playing the notes is only possible by the "My favourites" window. No way al all to open the note tapping on it by the map.

**Comment by quax2712** [comment]
This I recognizes since version 3.8.1 and 3.8.2. You can not select any POI or other things, even not waypoints or markers. It only tells .... searching for address ...
So you can not move a waypoint to a other place to change routing.

First you could select a loaded track for routing, but if you like to plan a similar route, it was only possible using a point on card, thta was a litte away of the loaded track. 
But now it is not realy useable.

greetings Rainer

**Comment by dmpr0** [comment]
Hello! Thank you for the feedback.
Are you using a long tap or short tap? Before 3.8.3 there was a bug with a long tap, it should be open just a place for the point where it tapped, but instead of it OsmAnd always opens the context menu if it any point was nearby.
A short tap on the map objects should open the context menu (and it always works like this).

**Comment by mircozorzo** [comment]
Hi, thanks a lot for the reply, I apologize for the late reply.

> Hello! Thank you for the feedback.
> Are you using a long tap or short tap? Before 3.8.3 there was a bug with a long tap, it should be open just a place for the point where it tapped, but instead of it OsmAnd always opens the context menu if it any point was nearby.
> A short tap on the map objects should open the context menu (and it always works like this).

None of the above (short or long) works for me, I can open the context menu but I cannot open the audio/video note even if the tap is very very closer.

I'm using always the latest nightly build, now 3.9.0#30811m

Bye, Mirco

**Comment by mircozorzo** [comment]
![Screenshot_2020-11-04-09-34-26-856_net osmand plus](https://user-images.githubusercontent.com/2377449/98087931-1bbe4180-1e81-11eb-91a4-8e0cd56db63a.jpg)
![Screenshot_2020-11-04-09-34-50-281_net osmand plus](https://user-images.githubusercontent.com/2377449/98087941-1e209b80-1e81-11eb-95a0-eaba32f82417.jpg)

**Comment by mircozorzo** [comment]
![Screenshot_2020-11-04-09-38-16-842_net osmand plus](https://user-images.githubusercontent.com/2377449/98088346-9be4a700-1e81-11eb-8126-588fbd4a1bce.jpg)
![Screenshot_2020-11-04-09-38-32-505_net osmand plus](https://user-images.githubusercontent.com/2377449/98088349-9c7d3d80-1e81-11eb-8abf-9c951c1bd9cd.jpg)

**Comment by vshcherb** [comment]
Did you enable accessibility plugin?

**Comment by mircozorzo** [comment]
> Did you enable accessibility plugin?

Yeeessss!

Disabling it works well again! 

Thank you so much.

Mirco

**Comment by sonora** [comment]
I guess it imay be the very purpose of the Accessibility plugin to alter the tapping behavior of the map screen.

But since this seemes to be a reccurring issue, see at least my awareness suggestion here: https://github.com/osmandapp/OsmAnd/issues/10270#issuecomment-733233095
